### ISSUE TITLE
Compatlayer present, but not loading

### ISSUE THREAD

**Issue by TBSAcheron** [McJty/RFTools#1000]
having this issue, randomly, on both my server and clients attempting to run the same pack.

I've attached the full log, as I cannot see the reason why, as in several points compatlayer is detected, but it ends up not loading, and causing rftools to crash the loading on startup.

[fml-client-latest.txt](https://github.com/McJty/RFTools/files/721396/fml-client-latest.txt)

**Comment by McJty** [comment]
This is caused by Homecraft Mineware. @AtomicBlom knows about it. Not sure if the latest version fixes this though.

**Comment by AtomicBlom** [comment]
Hi @TBSAcheron,

I had been waiting for the original reporter of the issue to get back to me to confirm my fix for it (I haven't been able to reproduce it and I suspect that it's sensitive to whether the compatlayer jar gets loaded before hcmw).
There is a build on my issue at https://github.com/AtomicBlom/HomecraftMineware/issues/7
if you could help me verify that it fixes the issue I'd appreciate it.

Regardless, I'll release that version to curse asap today, but I'd just like a bit more confidence that I have actually fixed the problem.

--Stevn

**Comment by TBSAcheron** [comment]
So far in testing, it has seemed to alleviate the issue entirely. It's
worked on the server and the 6 clients we have connecting so far.
Definitely made life easier. Have had no other conflicts so far.
