### ISSUE TITLE
Client crash with handheld modular storage on opening.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/RFTools#1006]
http://pastebin.com/gX5rb1sf

This happened during worldgen lagspikes, might be related.

**Comment by McJty** [comment]
I'll check it out

**Comment by Saereth** [comment]
I'm getting a similar crash with a standard t3 modular storage, no other cards
https://hastebin.com/avazamucep.sql

I did have some recipes saved in it before the crash.

**Comment by McJty** [comment]
This seems to be caused by some mod adding a 'null' recipe for something. I'll add code to protect against this but essentially the bug is not in rftools.

Also added a fix for the first bug. Both crashes are unrelated btw.

**Comment by Saereth** [comment]
Not sure it was a mod that added it, I tried to clear out the inventory slot in the first slot and basically set a null recipe, so rftools itself let me set that, which I guess caused the issue?

**Comment by McJty** [comment]
Not sure. That's not where it crashed though. But anyway next release should fix the crash
