### ISSUE TITLE
Builder still mining Saplings and seeds when blacklisted

### ISSUE THREAD

**Issue by jadeonking** [McJty/RFTools#1008]
![image](https://cloud.githubusercontent.com/assets/18316085/22298698/75c5f08c-e2ef-11e6-9305-ee057e56b387.png)
![Filter](http://i.imgur.com/nxXmbGn.png)

Any ideas how to fix this? If you need any more info just ask provided what I thought was needed.

Minecraft-1.10.2
Forge-V12.18.3.2185
HermitPack-V1.6.1
rftools-1.1x-5.76
rftoolsctrl-1.1x-1.6.3
rftoolsdim-1.1x-4.52

**Comment by McJty** [comment]
Did you try to enable ore dictionary in the filter?

**Comment by jadeonking** [comment]
Ore dictionary is activated which is even more strange

**Comment by McJty** [comment]
The problem is probably that the filtering works on the block and not the drops. i.e. you would have to blacklist the leaves themselves

**Comment by jadeonking** [comment]
ill give that a go and see if that helps

**Comment by jadeonking** [comment]
in the event this doesn't work would switching to whitelisting and just placing what I want counteract this?
(trying the leaves solution atm)

**Comment by McJty** [comment]
yes sure, whitelisting is usually what I do

**Comment by jadeonking** [comment]
That appears to have worked I will probably end up using whitelisting in the future however thanks for the assist and thanks for RFTools
