### ISSUE TITLE
Unable to delete dimentions from 

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#101]
Good Day,

I'm unable to delete dimensions from server console. When I try to send a command "/rftdim safedel 16" I get:
http://pastebin.com/XePNa7NF

It is all fine from client.
I would like to be able to remove the dimensions from server via script...
Version 2.55, Server: CentOS 6.6

Best Regards,
DeForce

**Comment by McJty** [comment]
Will be fixed in next version.
