### ISSUE TITLE
And N graphics driver conflict

### ISSUE THREAD

**Issue by Xiaoyan366** [McJty/RFTools#1010]
Seems to be version: 378.49 GeForce Game Ready Drive, there are conflicts 
Update will be unable to start the game 

I did not get the error file
Just the game will not start, the card is loading
I roll back to the old version does not appear after the problem.

**Comment by McJty** [comment]
Why do you report this here? This has nothing to do with rftools. Latest nvidia driver doesn't work with modded Minecraft. Not an rftools thing

**Comment by Xiaoyan366** [comment]
Haha, sorry. I also later learned that, because the driver problem.
