### ISSUE TITLE
Server crash when a fireball hit a powercell

### ISSUE THREAD

**Issue by zlainsama** [McJty/RFTools#1019]
Crash report: [pastebin](http://pastebin.com/iM0JHMiS)
There is a detailed modlist in the report.

This also corrupts the power network of the destroyed powercell.
All connected powercells exceed their maximum capacity and even input minus power.
My full tier 7 draconic evolution power ball got drained completed.
Emptying the whole power network fixed the problem.

**Comment by McJty** [comment]
Woo that's strange. I'll check it out

**Comment by McJty** [comment]
I could not reproduce this but I added some code to make sure this is more robust
