### ISSUE TITLE
1.11.2 Crashes 

### ISSUE THREAD

**Issue by iiNinetales** [McJty/RFTools#1020]
http://pussh.us/txt/475bb.txt With other mods

http://pussh.us/txt/59291.txt on its own

Downgrading to 5.76 seems to work though

**Comment by McJty** [comment]
Not RFTools problem. You have buggy nvidia drivers. This is a known problem with nvidia. These versions don't work for modded. Upgrade or downgrade them:

	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by McJty** [comment]
BTW: more info on this bug:

https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/
