### ISSUE TITLE
Endergenic generators unstable/unconfigurable/somethings wrong

### ISSUE THREAD

**Issue by jeridan** [McJty/RFTools#1023]
I am using mcjtylib-1.1x-2.3.6-SNAPSHOT.jar and rftools-1.1x-5.81.jar.

I cannot get the endergenic generators to play nice.  I set up the system based on the 4 gens with pearl monitors/sequencers between them.  This system used to work but now no matter how I set the sequencers they won't work correctly.  As seen, these are in different chunks (in the end so each gen setup is alone in the chunk) and either the gens say the last pearl arrived at 10 but are losing more rf than making or the last pearl arrived at some random interval(1,2,15 etc) and are not creating rf at all.  Please let me know what other info gathering I can do because I like this power gen but it is currently unusable.

![2017-02-04_23 43 42](https://cloud.githubusercontent.com/assets/5779504/22624009/2b1b8cc0-eb34-11e6-842d-d2fb632b357e.png)

**Comment by McJty** [comment]
It is hard to get the timing right on this as it depends on the order that tile entities tick. However, you should make sure that ALL logic (not just the endergenics) belonging to one endergenic circuit is in only one chunk. It is not clear from the screenshot if that's the case

**Comment by jeridan** [comment]
Yes everything is in one chunk.  The only things that are out of the chunk are an enderchest feeding pearls, the powercell, and the transmitter that the receivers are linked with.  Nothing else is in the chunk.  The ticking order must explain why it won't work at all if I reverse the direction.  I will move it over in the chunk and try again, maybe get lucky.

**Comment by jeridan** [comment]
Moved one setup over closer to the center of the chunk and it works flawlessly.  Moved the other one and it's still broken.  Going to try moving it again and maybe get it right but at least I know it will work.  Thanks!
