### ISSUE TITLE
[1.7.10] - Problem with some Modules for the screen.

### ISSUE THREAD

**Issue by chaos234** [McJty/RFTools#1026]
Hey McJty,

I have setuped a screen like I have it done every time incl. the modules. But actually I have discovered a few problem with those Modules.

First one is that the Energy (Plus) Module does not read out the Battery Energy Tap from the ZettaIndustrie Mods Battery correctly. It shows only a 2.1GRF instead of 3.16GRF (stored) and 56.70GRF (max.) what you can see below in the attached Images. Also it can't read out the current IN/OUT.

I don't know if this is a problem on your side or on Zetta's side because normaly this module works fine.

Secound one is a problem with the Lable (excludes the TXT-Module which works fine) which are not correctly "spaced". It seems that they have a limit for their length but you can exceed this which isn't rly good since it then goes over the the shown value.

Means if I have mor then e. g. one of those Batteries I would Lable it Battery 1/2/3/... for each Battery, incl. IN/OUT values. But for this I need a bit more space a which is limited to "Battery:"

I hope that you would and can push a fix for this because it would be rly nice.

Oh, one sidequestion: Is it normal that Liquid Modules have the option for showing the bar but didn't show it (see image 3)?

EDIT: Linking to the RF Meters results in compleatly zero values as this tool shows only the current flow and the RF flown through it.

Well, now the Images for the details above:

Problem with text length for the lable in line two and the miss shown amount of Energy:
![2017-02-08_01 22 37](https://cloud.githubusercontent.com/assets/340106/22717946/274da558-ed9e-11e6-9449-786113e8f5ec.png)

The Batteries GUI with correct values:
![2017-02-08_01 23 01](https://cloud.githubusercontent.com/assets/340106/22717970/4fe3ce5c-ed9e-11e6-936a-c7700b7e9107.png)

My Input (P1) and my Outputs (P2-  with RF Meters from ZettaIndustries Mod):

![2017-02-08_01 31 42](https://cloud.githubusercontent.com/assets/340106/22718015/869c1b70-ed9e-11e6-9f77-3c6fcec833d7.png)

![2017-02-08_01 31 46](https://cloud.githubusercontent.com/assets/340106/22718016/896a9bc4-ed9e-11e6-84bb-d7c5d704915c.png)

**Comment by McJty** [comment]
RFTools energy module normally only supports 32-bit integers (i.e. max 2 gig ram) since that's the maximum that RF supports. I made an exception for enderio and draconic evolution but I cannot support every mod that goes beyond this limitation. There is no general way to do that unfortunatelly.

Also for the other problems I'm afraid I no longer develop on 1.7.10 as this is an outdated version

**Comment by chaos234** [comment]
That's fine for me so I know that this isn't a real bug.

Well, then I have to think over placing a few EnderIO Cells between the RFMeter and the Tesseract.
Wans't that, what I wanted to do but if I want to have a screened energy I must do this.

Thanks for your replay :) .
