### ISSUE TITLE
absorption cubes not registering

### ISSUE THREAD

**Issue by mrwartooth** [McJty/RFTools#1030]
so trying to create dimlets and i cant seem to get the absorption cubes or whatever they are called to work with the recipies they dont auto filter when i double click and when i force put them in they dont register as a valid recipe

**Comment by McJty** [comment]
More info please? What exactly are you doing? What version of rftools dimensions?

**Comment by mrwartooth** [comment]
im not sure what version we have its skyfactory 3.0.5 and the issue im having is when i try to create a dimlet the absorption part of the recipe doesnt seem to work. im trying to creadt a wood materials dimlet and when i double click it it auto fills all the pieces but the absorption part and when i put it in manualy it doesnt register it either

**Comment by McJty** [comment]
Is the absorber at 100%? Show a screenshot please

**Comment by mrwartooth** [comment]
![2017-02-11_22 23 38](https://cloud.githubusercontent.com/assets/25643349/22859868/ccccfe90-f0a8-11e6-907f-17201e64d43d.png)

**Comment by mrwartooth** [comment]
also wondering how i get more terrain dimlets only one i have craftable is the void terrain dimlet

**Comment by McJty** [comment]
You didn't answer my question if the material absorber is at 100%? Did you let it absorb enough acacia wood?

For terrain dimlets you can also use a terrain absorber at 100%

**Comment by mrwartooth** [comment]
oh i didnt know you had to charge the absorbers and i suppose i wont be able to get terrain ones then because im playing in sky factory

**Comment by mrwartooth** [comment]
the only option though is void in the dimlet crafter thats why i asked

**Comment by McJty** [comment]
Ah yes. In sky factory 3 all dimensions are restricted to void only. That's done by the pack author. You can edit that config though (voidOnly).

**Comment by mrwartooth** [comment]
yeah i tried to in creative under mod options but the config button is greyed out.

**Comment by McJty** [comment]
It is a config you have to edit on file level

**Comment by mrwartooth** [comment]
aww ok. so back to absorption cube things so say i want a regular oak dimlet i need to make the absorber absorb some oak?

**Comment by McJty** [comment]
This is in the manual btw. You simply place the absorber over 128 blocks of the material you want to make

**Comment by mrwartooth** [comment]
oh i thaught i read the whole thing but i must have msised that part ill re read it but thank you for the info
