### ISSUE TITLE
RFTOOLS Spawner cannot handle VINDICATOR

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [McJty/RFTools#1032]
mcjtylib-1.1x-2.3.7.jar,rftools-1.1x-5.83.jar,1.11.2-forge1.11.2-13.20.0.2226

Shown in Spawner (gui)  nullRF ,nothing else

Please fix, they will drop emeralds 

regards

**Comment by McJty** [comment]
The spawner only supports mods that have been added to the config. You need to add several entries to the config for this

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
something like this 
____________________________________________________________________
S:"minecraft:vindicator.spawnamount.0" <
        I
        minecraft:emerald
        0
        0.1
     >
    S:"minecraft:vindicator.spawnamount.1" <
        B
        minecraft:log2
        0
        0.2
     >
_______________________________________________________________
regards

**Comment by McJty** [comment]
Should be fixed now I think
