### ISSUE TITLE
Crafting in Storage Scanner doesn't trigger Achievements

### ISSUE THREAD

**Issue by davqvist** [McJty/RFTools#1033]
I'm working on a modpack where achievements are quite important and I noticed that crafting in a Storage Scanner/Tablet doesn't trigger achievements that trigger on craft like "Benchmarking".

Forge 12.18.3.2221
RFTools 1.1x-5.82 (I will update in the next couple of days and try again)
Minecraft 1.10.2

**Comment by McJty** [comment]
I will try to see if I can easily fix this but it is not easy. Can't promise that it will be ready in a few days

**Comment by davqvist** [comment]
I know you're busy with XNet, but did you have a look at this yet? I just want to know if this can be fixed or not because if not I have to do plan for a workaround for my pack.

**Comment by McJty** [comment]
It can probably be fixed but due to some lack of time I didn't get around to it. I'll try to do it soon

**Comment by McJty** [comment]
Fixed next version

**Comment by davqvist** [comment]
Awesome, thanks.
