### ISSUE TITLE
Possible launch issue?

### ISSUE THREAD

**Issue by rakkfalen** [McJty/RFTools#1034]
initializing RFTools during loading screen causes Minecraft co completely crash... So no crash report to tell me why...

Screenshot: http://i.imgur.com/fnoTnuI.png

**Comment by McJty** [comment]
This is not rftools fault as a mod cannot cause the JVM to crash usually. I guess you have nvidia driver 378.49 which is broken for modded. Update that driver. There should be an update for it now
