### ISSUE TITLE
Feature Absorber SkyFactory 3

### ISSUE THREAD

**Issue by tryx10** [McJty/RFTools#1035]
I'm attempting to get huge orbs dimlet... and idk how to get the feature absorber to absorb a sphere :l
Thanks.

**Comment by Lupoid** [comment]
bump.. same issue, when absorbing it comes up as "unknown feature", when crafting it becomes a volcanoes feature dimlet.

**Comment by SDUBZ** [comment]
have you guys made a random dim yet to get more dims? or make a enderman farm and get dim packages

**Comment by McJty** [comment]
Note that the feature selected is random. It doesn't matter that you place it on an orb. It will just absorb a random feature from that dimension. I'll fix the bug that it always says unknown even at 100% though

**Comment by McJty** [comment]
At 100% waila, JEI, and TOP should now show the real feature
