### ISSUE TITLE
Builder with filter crashing server

### ISSUE THREAD

**Issue by thejims** [McJty/RFTools#1037]
After setting up a builder the server is now crashing on startup, filter in the builder is setup as blacklist for cobblestone and stone.

Pastebin crashreport: http://pastebin.com/gG131L1f

        Minecraft Version: 1.11.2
        Java Version: 1.8.0_121, Oracle Corporation
        UCHIJAAAA       forge{13.20.0.2226} [Minecraft Forge] (forge.jar)
        UCHIJAAAA       rftools{5.82} [RFTools] (rftools.jar)

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
This seems to be caused by another mod returning a wrong item for a block. Do you happen to know what the quarry was trying to break?

**Comment by thejims** [comment]
I do not, the game crashes instantly when I'm trying to find out.  I can remove rftools mods and load the world but not sure at what point the builder is at.  By chance could you build a version that outputs the location it is mining?  I could find out what it was if I knew where it was mining.

**Comment by McJty** [comment]
yes, I can. Hold on

**Comment by McJty** [comment]
Can you try with this version:
http://jenkins.k-4u.nl/job/RFTools/lastSuccessfulBuild/artifact/build/libs/rftools-1.1x-5.84.jar

It has an extra print right before the line that is crashing

Thanks!

**Comment by thejims** [comment]
I think this is the line you are looking for?

[23:07:20] [Server thread/INFO]: [STDOUT]: block.getRegistryName() = terraqueous:foliage2

**Comment by McJty** [comment]
yes, so they have a buggy implementation then. You can report to them and tell them that their block.getItem() is returning null on 1.11 and that's an invalid result as null itemstacks are no longer allowed

**Comment by thejims** [comment]
Thanks McJty, reported here https://github.com/ShetiPhian/Localizations-and-Issues/issues/42
