### ISSUE TITLE
Activity Probe Not Shutting Down Dimensions

### ISSUE THREAD

**Issue by Phishinabowl** [McJty/RFTools#1041]
I'm having a weird issue where every once in a while the Activity Probes will stop working and will not shutdown a dimension properly when nobody is inside of them. I'm on the DW20 1.10 pack version 1.4.1. Sometimes everything works fine but for example right now I have two dimensions in different Dimension Builders and each dimension has an activity probe right on the other side of the portal on the spawn platform. Right now nobody is in either dimension but both dimensions are using power which shouldn't be the case. Video evidence is below.

Versions:
rftools-1.1x-5.81.jar
rftoolsdim-1.1x-4.53.jar
rftoolsctrl-1.1x-1.6.4.jar

Video: https://youtu.be/Xoiy6raIgf8

**Comment by McJty** [comment]
You sure there is nothing chunkloading the dimension?

**Comment by Phishinabowl** [comment]
Positive. Nothing on the other side of those things aside from a wireless RF transmitter from extrautils to power the matter receiver on that side and the activity probe. It's even stranger in that it worked fine for the first few hours I was on the server and then I just suddenly happened to notice I was losing power and then looked around and tracked it down to those Dim Builders.

**Comment by jeridan** [comment]
I just created a new dragon spawning dimension and got the same.  Nothing is in it right now other than the wireless transmitter from extarutils and the activity probe but it is still consuming power.  Maybe it is the wireless transmitter?  Will remove mine, test and report back.

**Comment by McJty** [comment]
Fixed next release
