### ISSUE TITLE
Elevator Platform Has Broken Texture When Using Chisel Blocks

### ISSUE THREAD

**Issue by Phishinabowl** [McJty/RFTools#1043]
Just updated to latest DW20 1.10 pack v1.6.0 and I noticed that it seems that elevator platforms now have a broken texture when they're in motion if you're using a chisel block as the platform. Currently have a 3x3 elevator platform made up of factory blocks from chisel and whenever they move they turn into broken textures. Vanilla blocks don't seem to have issue. Could be Chisel's fault but not positive.

**Comment by McJty** [comment]
Already fixed in rftools

**Comment by Phishinabowl** [comment]
Awesome thanks! Sorry for posting something that was already fixed >.<
