### ISSUE TITLE
[1.10.2] Missing Descriptions on Blocks

### ISSUE THREAD

**Issue by Complx** [McJty/RFTools#1044]
The description on RFTools blocks does not show up in versions of RFTools higher than 5.62 on Minecraft version 1.10.2
This is what you see on version 5.62alpha2 and higher (taken on RFTools version 5.84 and mcjtylib 2.3.8)
![screenshot 1](https://cloud.githubusercontent.com/assets/6044152/23111585/59c75ed6-f6de-11e6-9ea4-57c7fdc04737.png)
RFTools 5.62alpha1 is also missing the description but I did not take a screenshot of that version

This is what you see on versions of RFTools 5.62 and lower (taken on RFTools version 5.62 and mcjtylib 2.2.0)
![screenshot 2](https://cloud.githubusercontent.com/assets/6044152/23111586/59c7ae04-f6de-11e6-8c97-5f52d9c0f5e2.png)

In Minecraft 1.11.2 the descriptions seem to work perfectly, also item descriptions work correctly in all the versions that I tested (aside from the Storage Tablet that does nothing when you press shift, but still displays the `<Press Shift>` message)
All tests were done with only RFTools, mcjtylib, and CompatLayer on the latest version of forge for that Minecraft version.

**Comment by McJty** [comment]
Hmm, that's at the time I ported RFTools to 1.11. I know about this bug but I have never been able to figure out what. Hopefully with your detailed version check I can find it now. Thanks

**Comment by McJty** [comment]
Fixed in McJtyLib 2.3.9
