### ISSUE TITLE
[Feature Request] Add visual status rendering to Logic Gate

### ISSUE THREAD

**Issue by scollenburg** [McJty/RFTools#1049]
Concept:
![logic gate status indicators](https://cloud.githubusercontent.com/assets/6403067/23271605/aac28a0e-f9bd-11e6-974f-830c9110fdf5.png)

A small amount of visual feedback would help troubleshoot designs involving the Logic gate. (Colors used & design were chosen for clarity. Use what you like, ignore the rest)

- Visual feedback indicating a valid redstone connection is "found". Indicated by two bright green parallel lines in the concept image.
- Visual feedback indicating an active redstone signal. Indicated by a red square nestled inside the "arrow" in the concept image. 

Thanks!

**Comment by McJty** [comment]
The logic blocks avoid that kind of thing for full efficiency. Visual changes like that is what can cause performance issues for high speed redstone logic. Also The One Probe gives you more information when looking at a logic block.
