### ISSUE TITLE
Curse won't load Mod

### ISSUE THREAD

**Issue by FuuNoKamiOka** [McJty/RFTools#1050]
I have been trying to load up this mod for a while now and no matter what I do nothing works and my game crashes. I don't actually get to go in the game with it. It crashes while still loading mods. Problem is, I get no error message. Just the log of trying to load the mods. Below is the log of me trying to load RFTools and only that mod in 1.10.2 with Forge version 12.18.2.2234. If anyone can help, please do. (As a side note, it does the same with Waila)

http://pastebin.com/Jyu55iL8

**Comment by McJty** [comment]
This has nothing to do with rftools. You are using a buggy nvidia driver: NVIDIA 378.49

This driver doesn't work for modded Minecraft. Update to the latest version
