### ISSUE TITLE
crash on world load (mod incompat) between rftools/black hole storage

### ISSUE THREAD

**Issue by SDUBZ** [McJty/RFTools#1054]
[crash-2017-02-26_09.48.19-server.txt](https://github.com/McJty/RFTools/files/801583/crash-2017-02-26_09.48.19-server.txt)
forge:1.11.2-2252/51
rftools: rftools-1.1x-5.84
mcjtylib: mcjtylib-1.1x-2.3.9
blackholestorage:Black Hole Storage 1.11.2-3a
hammer core: HammerCore_1.11.2-1.2.8

**Comment by McJty** [comment]
That's a bug in black hole storage. They appear to be handling their itemhandler wrong. Two things you can tell them:

- If hasCapability() returns true then getCapability() can NOT return null
- side parameter null is a legal value for has and get capability. It means access to the entire inventory
