### ISSUE TITLE
Ticking Block Entity crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [McJty/RFTools#1055]
I got a crash when trying to place an RFTools Matter Receiver on a Draconic Evolution Creative RF Source.

[Crash Log](https://gist.github.com/BrisingrAerowing/bc6b6e8bc3688b63be2153a98a7b4f20)

It seems that a method could not be found.

**Comment by McJty** [comment]
It seems that some mod is having a wrong CoFH API included. Going to be a bit of a trouble to find out which one...

**Comment by BrisingrAerowing** [comment]
I have Metroid Cubed 3 installed, referenced as the issue in a later issue here. I followed FirEmerald's instructions on removing the cofh folder to fix this (I have a number of mods that provide the RF API so that is no issue).
