### ISSUE TITLE
[1.11.2] Array index out of bounds (screen might be causing it when running out of it's chunk)

### ISSUE THREAD

**Issue by shortybsd** [McJty/RFTools#1057]
MC 1.11.2
Forge 2230
rftools-1.1x-5.84
mcjtylib-1.1x-2.3.9

It might be the screen in my area when running out of the chunk causing the crash.
I was just running around outside my area, then it froze and crashed with the following error:

http://pastebin.com/BAcDg3iL

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
This crash happened while in the gui for the modular storage block. Are you sure this crash happened while running around because that seems highly unlikely

**Comment by shortybsd** [comment]
I was in the tablet dumping inventory about a minute before that crash. This was client side and the server itself never showed any error rather than my connection terminated.

**Comment by McJty** [comment]
Can  you reproduce this? If not I think this is an anomaly due to bad timing and bad syncing between server/client

**Comment by shortybsd** [comment]
It was a strange factor indeed, I cannot reproduce but then again I haven't played much lately. Dying for a legit wire/item duct/conduit mod like EnderIO. Hung up MC until then. I will close for now, thanks for looking into it.
