### ISSUE TITLE
Crash on placing an environmental controller (And on any attempts to load the world)

### ISSUE THREAD

**Issue by NezcalSpindrake** [McJty/RFTools#1058]
Tried to place an environmental controller into the world, on stone. (It was cheated in, if that matters)
Crashed immediately with this error log:
http://pastebin.com/dKmd6Udw
Attempting to load the world gives this error:
http://pastebin.com/Y9Ebs4KN

**Comment by McJty** [comment]
You have a mod in your modlist that has an invalid RF api. Problem is figuring out which one.

**Comment by McJty** [comment]
What's your modlist?

**Comment by mallrat208** [comment]
It's Metroid Cubed 3

A quick look shows they're using the 1.7.10R1.0.2 version of the RF API

**Comment by McJty** [comment]
aha thanks for checking that!

**Comment by HenryLoenwind** [comment]
> Problem is figuring out which one.

For the next time: Ender IO has diagnostics for this problem, so it can be used as diagnostics tool.

**Comment by NezcalSpindrake** [comment]
I head to take EnderIO out, actually, because of an incompatibility with MC3 and Tcon
