### ISSUE TITLE
Tried teleporting, crashed and world now unplayable

### ISSUE THREAD

**Issue by mika1369** [McJty/RFTools#1061]
Might be related / same issue as my other issue:
https://github.com/McJty/RFTools/issues/1059

I tried teleporting to a rftools dimension, but it crashed and now the world crashes on startup

[crash-2017-03-02_00.00.59-server.txt](https://github.com/McJty/RFTools/files/812314/crash-2017-03-02_00.00.59-server.txt)
[crash-2017-03-01_23.55.40-server.txt](https://github.com/McJty/RFTools/files/812315/crash-2017-03-01_23.55.40-server.txt)

**Comment by McJty** [comment]
Do you have sponge? Is this SMP?

**Comment by mika1369** [comment]
I have only added optifine, so unless skyfactory 3 have sponge, then I'd say no. 

And I'm not sure what SMP means :( it's just a normal single player world as far as I know.

**Comment by BrisingrAerowing** [comment]
@mika1369 SMP is Server Multiplayer.

**Comment by mika1369** [comment]
Ah, in that case no, just singleplayer :)
Thanks

**Comment by mika1369** [comment]
Unrelated to the mod, simply me being a fool and deleting a folder  that still had a reciever in it.

Ive since learned of the safedel command, i will be sure to use that in the future.
