### ISSUE TITLE
Server problems 

### ISSUE THREAD

**Issue by HazzaTheShadows** [McJty/RFTools#1062]
hi I cant seem to get dimensions working on the server properly on the sky factory 3 mod pack want to config it to make other types not just void dimensions

**Comment by McJty** [comment]
Set voidOnly to false in the config. The SkyFactory 3 modpack has been configured for void dimensions only by default (because it is a skyblock modpack)

**Comment by HazzaTheShadows** [comment]
anyway to change this

**Comment by McJty** [comment]
I just told you. Read what I said
