### ISSUE TITLE
Clean up list of teleport receivers

### ISSUE THREAD

**Issue by BrisingrAerowing** [McJty/RFTools#1063]
How can I clean up the list of teleport receivers? I have a 'ghost' one in a dimension I deleted (not an RFTools Dim, it was added with Just Enough Dimensions), as the dimension ID conflicted with Advanced Rocketry and caused some strange issues.

**Comment by BrisingrAerowing** [comment]
I get an unknown command error. The wiki doesn't show that command for 1.1x, and I don't see it in the source, is it not implemented in that version?

**Comment by McJty** [comment]
Reimplemented in next release
