### ISSUE TITLE
Game crashes on Initializing Phase 3

### ISSUE THREAD

**Issue by juli734** [McJty/RFTools#1064]
My game crashes in loading screen when I enable RFtools in Resonant Rise 

http://pastebin.com/mn3shjNR

**Comment by McJty** [comment]
Conflict with villager ID which rftools sets to 10 by default. Edit the rftools config and change that ID to some value that works

**Comment by juli734** [comment]
it was disabled by default and I also set it to 0 but that didn't change anything
