### ISSUE TITLE
[CRASH] when I click on workbench

### ISSUE THREAD

**Issue by ARatfat** [McJty/RFTools#1066]
Hi, 

I use Forge 2239
I use biom bundle for gen
I crash when I click on workbench 

This is my crash log http://pastebin.com/9Swnykpv

Thx

**Comment by McJty** [comment]
More info please. What versions of my rftools dimensions?

**Comment by ARatfat** [comment]
RFTool dimm 1.1x 4.54
RFTool 1.1x-5.86
mcjtylib 1.1x-2.3.9
compact layer 1.10 0.2.2

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
BTW, in the future please post to the correct github. This is about RFTools but this bug is in RFTools Dimensions

**Comment by McJty** [comment]
Fixed next release
