### ISSUE TITLE
[Bug] Environmental Controller power compsumtion

### ISSUE THREAD

**Issue by DarkLight66** [McJty/RFTools#107]
As of RFtools v2.62, if you change the area of effect of the Environmental Controller it will not consume the power showed on WAILA until the internal inventory is updated (you take a module out and back in). So you could set the area to the minimum, put all the modules you want, then set the are to the maximum and barely use any power.

**Comment by McJty** [comment]
Thanks for reporting. I will check it out.

**Comment by McJty** [comment]
Confirmed and fixed for next release.
