### ISSUE TITLE
builder crashes server when moving a structure with a chest

### ISSUE THREAD

**Issue by StrommKral** [McJty/RFTools#1074]
on a ftb lite, 1.51 server, while moving an end city to the overworld, when ever the builder encounters a chest, it crashes the server(not client). repeatable, as i moved the boat also, and forgot to take out the 2 chest, hence a server crash. also, while the inventory of the space card says it will move the Shulker, it does not.
not asking for a fix, just an FYI for you

**Comment by McJty** [comment]
Can you give me a crash log in any case? I may be able to fix it

**Comment by StrommKral** [comment]
I am sorry, i cannot, i was not playing on a server I owned. all that happened on my side was a kick, I was able to log on after it reset, about 3 minuets. it was on one that is owned by a streamer. i am reluctant to post their name here, and am not sure they could produce a log as it is not hosted privately.

**Comment by McJty** [comment]
Without a log there is not much I can do really

**Comment by belathus** [comment]
One of the guys on my server caused a crash last night that might be related. He says that this was caused when he was trying to move an inventory (MineColonies inventories, I'm told, but I'm also told he tried to move a chest and a furnace, producing two more crashes). He repeated it three times, but he did so at 3 AM while I was asleep.
https://gist.github.com/belathus/2d98ee36a7aef971b5b3aa1882407b8e
