### ISSUE TITLE
Crash on dimension out of energy while in it

### ISSUE THREAD

**Issue by 252rer** [McJty/RFTools#1075]
While in a dimension extracting the remaining energy out of it when it runs out of energy the game crashes.
Have a charged PFG highlighted in hotbar.
Have the the current realized dimension in inventory.

Minecraft 1.7.10
rftools 4.23
mcjtylib 1.8.1
Forge 10.13.4.1614
CoFHLib 1.1.2-182

http://pastebin.com/bPjxAMsm

**Comment by McJty** [comment]
I will check it out

**Comment by 252rer** [comment]
Good news is it seems to be fine after reloading the world but crashes the first time a dimension runs out of energy repeatedly.

**Comment by McJty** [comment]
Oh 1.7.10... I no longer maintain that version but also rftools dimensions were heavily used on that version and this scenario (running out of power) has come up a lot of times so I doubt this is a bug on rftools side
