### ISSUE TITLE
Dupe bug with server's claim plugins -Builder block w/ quarry card

### ISSUE THREAD

**Issue by dole45** [McJty/RFTools#1076]
When the builder tries to break a block in a claim, it isnt able to break the block, but it still puts that item in the output, thereby duping it.

We came to the conclusion the issue is in your code, not the plugins.

-Dole & the ShadowNode Server

**Comment by mkrtes** [comment]
Perhaps this problem is also linked dupe blocks with elevator. In a claim elevator restore broken blocks of the floor.

**Comment by McJty** [comment]
And how exactly did you come to that conclusion?  I cannot do anything about plugins really. It is much better to avoid them and use sponge (forge version) or ftb utils

**Comment by ktole1999** [comment]
i am not a coder but i have seen other mod issues with this scenario. the security plugin is keeping you from breaking the block but not completely cancelling the event? feel free to throw me to the sharks if i am wrong.

**Comment by McJty** [comment]
Nevertheless I don't think there is much that I can do about this. The builder is calling: block.canEntityDestroy() to detect if it is allowed to harvest a block. If that returns true then I can safely assume that I can break the block. If the plugin still lets that function return true then that's a bug in the plugin and not in my mod. So unless some more clear information is given or proof that this is actually a bug in rftools I'm closing this. Feel free to comment if more information can be found.

**Comment by mkrtes** [comment]
As far as I know, this is a problem GriefPrevention. This is fixed in the latest versions.
