### ISSUE TITLE
Project Ozone, Server not launching. [02:05:42] [Thread-18/ERROR] [Galacticraft]: Galacticraft update check failed! Trying again in 15 seconds

### ISSUE THREAD

**Issue by Lashoutgaming** [McJty/RFTools#1079]
![image](https://cloud.githubusercontent.com/assets/26377670/23847933/f79f3cdc-0791-11e7-8169-f3746f47781b.png)

Started happening suddenly worked last night, not today

**Comment by McJty** [comment]
Why are you assigning this to rftools? That has nothing do with this mod. Check with galacticraft
