### ISSUE TITLE
Low Power Reciever in Dimlet Causes Crash

### ISSUE THREAD

**Issue by NullMagic** [McJty/RFTools#108]
Alright, so, I recently created a Dimension, and went to it a couple times, and came back, and then turned off my teleporter, then decided to return and tried to turn it back on, but I crashed to the desktop. Now, I crash randomly all the time, so it took me three or four tries to actually realize this was in fact a bug, however I finally checked and it indeed is generating a crash report.

http://pastebin.com/TTi2Qesc

it seems (From what my limited capacity for reading error reports tells me) to be a GUI related bug, I'd like to note that it does not activate the connection after I've crashed, I can only assume that the power has completely run out on the other end.

**Comment by McJty** [comment]
Hmm. Can you describe exactly the steps you do to reproduce this? You open the GUI of the dialing device. Then what?

**Comment by NullMagic** [comment]
Well, originally I just selected my teleporter and then the receiver in the Dim (which is Dim 9 in this case), and then hit the.... far left button (I have a terrible memory, sorry), it'd flash in red words at the bottom about low power and then the game would pause, show me the loading screen and then crash to desktop, however I just tried checking the reciever using the Check button (far right) it flashed something in red for a moment and then said it was okay, however the receiver disappeared off the list, I hit the check button again (I don't know why), and it crashed me to the desktop again...

**Comment by McJty** [comment]
Ok, I'm busy releasing 2.63 which adds more robust checking for this so this bug should hopefully be fixed. Reopen if you can reproduce it with 2.63. Thanks
