### ISSUE TITLE
[1.11.2][5.88] Some mining issues with several mods: EvilCraft, Actually Additions, Terraqueous and possibly Quark

### ISSUE THREAD

**Issue by starg09** [McJty/RFTools#1090]
Ok, I'll put all of these on one list I think. These all happen when using a Silk Touch Quarry Card (no void):

* EvilCraft: Dark Ore item has no texture/model after being mined (once placed it's back to normal.
* Actually Additions or Quark: The builder seems to also mine some vanilla logs and leaves incorrectly. Not sure whether this happens while mining ActAdd's Lush Caves, or one of Quark's new Underground Biomes (leaning towards the former, but need to do more tests).
* Actually Additions: Got this error on chat when the builder tried to mine one loot chest from the mod, that spawns at the bottom of the ocean (had to open it manually in order to continue): 

![image](https://cloud.githubusercontent.com/assets/1235066/24076742/62672848-0c17-11e7-9c40-851b0adf4f60.png)

* Terraqueous: Seems to also mine this mod's logs incorrectly, leaving them with a broken texture/model.
* Apparently, from what I see vanilla chests are mined, but no items are extracted from them. Is this intended, or a bug related to 1.11 inventory changes?
* Finally, as a similar case, crates from Actually Additions are mined with their contents intact and inside it. Once placed in world, and opened by hand, these crates become similar to a chest (breaking them drops their contents).

**Comment by McJty** [comment]
I will check it out

**Comment by starg09** [comment]
Ok, will do so then!

**Comment by McJty** [comment]
I'm working on a fix for silk touch in general for the other issues

**Comment by starg09** [comment]
Seems like 5.89 crashes on load, [here's the crash report](http://paste.feed-the-beast.com/view/5c563c71)

**Comment by sandalle** [comment]
@starg09 , that's covered in https://github.com/McJty/RFTools/issues/1093 . :)

**Comment by starg09** [comment]
Yup, also made a comment there, then I deleted it after seeing the "no more same replies pls", heh. Forgot it actually sends a mail anyway :P

**Comment by McJty** [comment]
Looking into it

**Comment by McJty** [comment]
Fixed in 5.90

**Comment by starg09** [comment]
Ok, after testing it seems like most have been fixed. Only two issues remain:

* Dark Ore from EvilCraft still gives missing texture.
* Ruby Ore from TechReborn still drops red garnets even when mined with silk touch (actually forgot to include this one before, heh 😛 ).

Want me to re-open this issue, or make a new one?

**Comment by McJty** [comment]
I don't know what else to do. Do other silk touch capable quarries manage to mine these blocks correctly?

**Comment by starg09** [comment]
~~not sure, will give it a check.~~ Allright, nvm the one from EvilCraft is bugged when generated. If you mine those it'll always have missing textures, sorry about that (the one placed from creative inv works ok, that's what I tested before... Will report to the author)

And about TR (which I hadn't reported originally), as I understand it shouldn't drop the red garnet when mined with silk. Will do some testing though, see if I can obtain one manually that way... Just in case.

**Comment by starg09** [comment]
Welp, seems like the red garnet fix may not have been ported to 1.11 TR in general, not only to the builder... Nvm everything then, all fixed on your side it seems :)

**Comment by McJty** [comment]
ok good :-)
