### ISSUE TITLE
Text imput stays in modular storage after clicking on JEI search box

### ISSUE THREAD

**Issue by LennartCockx** [McJty/RFTools#1091]
This is not really an issue but rather a convenience fix.
Currently after searching for an item in the modular storage, If I click on the JEI search box, the cursor will show as being in the JEI search box. When I actually start typing something it will type in the modular storage search box instead. 

I first have to click at a random location to remove the cursor from the modular storage search box before searching in JEI.

A possible way to fix this would be to allow synchronization of both search boxes similar to how refined storage handles it. Just having it work by clicking the JEI box would be rather nice already though.

**Comment by McJty** [comment]
Yes, but I don't know exactly how easy it would be to do that. @mezz, any input on this? Thanks

**Comment by mezz** [comment]
I replied about text input here: https://github.com/McJty/RFTools/issues/1082#issuecomment-286899845

**Comment by McJty** [comment]
Whoops sorry. I missed that

**Comment by McJty** [comment]
Closing because of duplicate with #1082
