### ISSUE TITLE
Crash with 5.89

### ISSUE THREAD

**Issue by jubalearly** [McJty/RFTools#1093]
Custom modpack, just updated both rftools, compatlayer and mcjtyLib

Here is top message, pastebin below:

There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.block.Block.getSilkTouchDrop(net.minecraft.block.state.IBlockState)

Forge 12.18.3.2239

http://pastebin.com/bK0XmRZK

**Comment by sandalle** [comment]
Same here: 
[crash-2017-03-20_13.03.56-client.txt](https://github.com/McJty/RFTools/files/856227/crash-2017-03-20_13.03.56-client.txt)

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
CompatLayer: 1.10-0.2.5
McJtyLib: 1.1x-2.3.11
RFTools: 1.1x-5.89

**Comment by mzx987** [comment]
Yep. Glad I'm not the only one getting this error.

Forge version: 12.18.3.2254
[Crash Report](http://pastebin.com/wPMc3ALa)

**Comment by HDShatter** [comment]
Also getting the same crash.

http://pastebin.com/dwdNncy6

**Comment by NerdCraft** [comment]
Same here. :c

**Comment by jem991** [comment]
same

**Comment by DeGariless** [comment]
Hey everyone. Instead of saying "same" hit that subscribe button over on the right to get notified if any new and relevant info has been posted. Don't comment unless you have new or relevant information.

**Comment by Endmateria** [comment]
"Same..."  hahahaha

https://gist.github.com/Endmateria/9edea3e3285f5465a6382112f9a99dc8#file-crash-3-20-17

**Comment by starg09** [comment]
Same 😛 

http://paste.feed-the-beast.com/view/5c563c71

**Comment by McJty** [comment]
Fixed in 5.90
