### ISSUE TITLE
RfTools Liquid Monitor doesn't work

### ISSUE THREAD

**Issue by Pac93** [McJty/RFTools#1094]
Hi, I'm playing FTB Beyond 1.2.1 and I'm trying to automate the lava input in the deep resonance tank, but the liquid monitor of rftools doesn't work, it doesn't emit any redstone signal.

**Comment by McJty** [comment]
Note that the redstone signal comes out at the back of the liquid monitor (the side with the red arrow). Are you checking from there?

**Comment by Pac93** [comment]
Omg, the only side I didn't check, I feel so noob lol.
Thank's buddy and keep up the good work

**Comment by McJty** [comment]
np
