### ISSUE TITLE
Realistic colonies modpack ssp crash

### ISSUE THREAD

**Issue by shadowwraiser** [McJty/RFTools#1095]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (LoadingProfiler-MC1.9.4-1.3.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/21/17 8:59 PM
Description: Exception while ticking a block

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_180496_d(World.java:525)
	at net.minecraft.world.World.func_175685_c(World.java:469)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.world.World.func_175698_g(World.java:381)
	at net.minecraft.block.BlockFalling.func_176503_e(BlockFalling.java:66)
	at net.minecraft.block.BlockFalling.func_180650_b(BlockFalling.java:44)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:525)
	at net.minecraft.world.World.func_175685_c(World.java:469)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.world.World.func_175698_g(World.java:381)
	at net.minecraft.block.BlockFalling.func_176503_e(BlockFalling.java:66)
	at net.minecraft.block.BlockFalling.func_180650_b(BlockFalling.java:44)

-- Block being ticked --
Details:
	Block: minecraft:gravel
	Block location: World: (-366,47,277), Chunk: (at 2,2,5 in -23,17; contains blocks -368,0,272 to -353,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)

-- Affected level --
Details:
	Level name: A WORLD
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 628 Drop: 0
	Level seed: 2141373986701923319
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-188,64,256), Chunk: (at 4,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 50809 game time, 30231 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7983 (now: false), thunder time: 67866 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1870060832 bytes (1783 MB) / 4200071168 bytes (4005 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	libVulpes{0.1.16.20170220215024} [libVulpes] (LibVulpes-1.10.2-0.1.16-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.10.2-1.0.13} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.13.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJAAAA	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	AppleCore{2.1.2} [AppleCore] (AppleCore-mc1.10.2-2.1.2.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.5.jar) 
	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
	UCHIJAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.13} [CoroUtil Library] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	deathquotes{1.0.1} [Death Quotes] (DeathQuotes-1.0.1-mc1.9to1.10.2-forge.jar) 
	UCHIJAAAA	ding{1.0.1} [Ding] (Ding-1.10.2-1.0.1.jar) 
	UCHIJAAAA	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.6b} [Environmental Tech] (environmentaltech-1.10.2-0.10.6b.jar) 
	UCHIJAAAA	epicsiegemod{11.0.152} [Epic Siege Mod] (EpicSiegeMod-11.0.152.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.1.0.4} [Zero CORE] (zerocore-1.10.2-0.1.0.4.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.27.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHIJAAAA	HoloInventory{2.0.2.144} [HoloInventory] (HoloInventory-1.9.4-2.0.2.144.jar) 
	UCHIJAAAA	ichunutil{6.1.1} [iChunUtil] (iChunUtil-1.10.2-6.1.1.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.23} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.23.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.8-1.10.2.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	LoadingProfiler{1.1} [Loading Profiler] (LoadingProfiler-MC1.9.4-1.3.jar) 
	UCHIJAAAA	lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.6.3125} [MineColonies] (minecolonies-universal-1.10.2-0.6.3125.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mycommands{1.9.4-1.10.2-02} [MY Commands] (MyCommands-1.9.4-1.10.2-02.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.4} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.4.4a.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	currency{2.0.} [Never Enough Currency] (NeverEnoughCurrency-2.1.4.jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJAAAA	samsocean{1.0.0} [Classic Oceans] (OceanFloor-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.13} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.13.jar) 
	UCHIJAAAA	packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	quantumflux{2.0.11} [QuantumFlux] (quantumflux-1.10.2-2.0.11.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJAAAA	reauth{3.4.1} [ReAuth] (ReAuth-1.10-3.4.1.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	UCHIJAAAA	rftools{5.88} [RFTools] (rftools-1.1x-5.88.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHIJAAAA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJAAAA	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.10.2-1.2a.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJAAAA	taiga{1.2.6} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.6.jar) 
	UCHIJAAAA	thutcore{3.12.1} [ThutCore] (thutcore-3.12.1.jar) 
	UCHIJAAAA	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.10.b.jar) 
	UCHIJAAAA	tinker_io{release 2.4.3} [Tinker I/O] (tinker_io-1.10.2-release 2.4.3.jar) 
	UCHIJAAAA	TinkersAddons{1.0.4} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.4.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	vending{1.4.3} [Vending] (vending-1.10.2-1.4.3.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.214.jar) 
	UCHIJAAAA	wawla{2.3.1.214} [What Are We Looking At] (Wawla-1.10.2-2.3.1.214.jar) 
	UCHIJAAAA	wct{0.0.17} [Wireless Crafting Terminal] (WirelessCraftingTerminal-1.10.2-0.0.17.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	zombieawareness{1.10.2-1.11.6} [Zombie Awareness] (zombieawareness-1.10.2-1.11.6.jar) 
	Loaded coremods (and transformers): 
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (LoadingProfiler-MC1.9.4-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.10.2-2.1.2.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-11.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.9.jar
		* BetterAchievements|API (0.3.3.10) from BetterAchievements-1.10.2-0.3.3.10.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.27.jar
		* BotaniaAPI (85) from Botania r1.9-341.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* CoFHAPI (1.8.9R1.2.0B1) from SpartanShields-1.10.2-1.2a.jar
		* cofhapi (1.4.0) from extrautils2-1.10.2-1.3.3.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Railcraft_1.10.2-10.0.1.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.10.2-1.3.3.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* compatlayer (0.2.2) from compatlayer-1.10-0.2.2.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.10.2-1.1.13.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.8.177-universal.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* environmentaltech-api (1.10.2-0.10.6b) from environmentaltech-1.10.2-0.10.6b.jar
		* EpicSiegeMod|API (1.0) from EpicSiegeMod-11.0.152.jar
		* iChunUtil API (1.1.0) from iChunUtil-1.10.2-6.1.1.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.23.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.4.6.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.416.jar
		* mcjtylib_ng (2.3.10) from mcjtylib-1.1x-2.3.10.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.10.2-1.0.13.jar
		* PsiAPI (2) from Psi-r1.0-42.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* thut|API (1.0.0) from thutcore-3.12.1.jar
		* valkyrielib.api (1.10.2-0.10.6) from valkyrielib-1.10.2-0.10.6.jar
		* VeinMinerApi (0.3) from VeinMiner-1.9-0.35.3.595+a46c1b0.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
		* wct|API (1.10.2-rv4-1.0.0b) from WirelessCraftingTerminal-1.10.2-0.0.17.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	EnderIO: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/fml/common/API
	AE2 Integration: IC2:OFF, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by McJty** [comment]
Sorry but I fail to say why this is relevant to RFTools? The crash is not in rftools

**Comment by shadowwraiser** [comment]
oh oops didnt realise was rftools area, sry
