### ISSUE TITLE
[1.10.2/1.11.2] Crash during load

### ISSUE THREAD

**Issue by Silvrus** [McJty/RFTools#1096]
RFTools ver 1.1x-5.89
McjtyLib ver 1.1x-2.3.11
1.10.2 Forge ver 12.18.3.2239
1.11.2 Forge ver 13.20.0.2255

After updating to this RFTools version the game crashes complaining about [this](https://gist.github.com/Silvrus/ef49eb025aebebc27650f3070fe85891) on launch. Downgrading to the previous fixes the crash.

Edit: Discovered the crash occurs in 1.11.2 as well.

**Comment by McJty** [comment]
If you would have checked this issue tracker and also latest version on curse you would have been able to see that this has been fixed several hours ago already
