### ISSUE TITLE
Crash on latest version (5.90)

### ISSUE THREAD

**Issue by Herblerp** [McJty/RFTools#1098]
5.88 works fine. My guess is that you just dint update the library yet, since it cant find a certain method. Will try again with newest version soon.
[crash-2017-03-21_18.33.30-client.txt](https://github.com/McJty/RFTools/files/859124/crash-2017-03-21_18.33.30-client.txt)

**Comment by McJty** [comment]
This crash is with 5.89. Please use 5.90. The bug is fixed there

**Comment by Alaberti** [comment]
I am getting this error on 5.90 - http://pastebin.com/raw/WjdH1WAb. Haven't verified if it happens on the client, but it is crashing my dedicated server.
