### ISSUE TITLE
[5.90] Crash on Server, Client

### ISSUE THREAD

**Issue by Alaberti** [McJty/RFTools#1100]
Server: http://pastebin.com/raw/WjdH1WAb
Client: http://pastebin.com/raw/HcYBy7GJ

Edit: Also, I'm #1100, get out your party hats.

**Comment by McJty** [comment]
What version of compatlayer?

**Comment by Alaberti** [comment]
1.11.2-0.2.5

**Comment by Alaberti** [comment]
...Ohhhhh
