### ISSUE TITLE
Builder Ignoring BlockBreaking Event. (Please High Priority)

### ISSUE THREAD

**Issue by Speiger** [McJty/RFTools#1107]
The Builder when placing/Replacing blocks totally ignores if it is breakable or not.
Yes it check the unbreakable state of the Block but there is no Event check if the Blocks can be destroyed.
Thats why the BlockBreakEvent exists.

A big serverhoster i try to help fixing bugs gave me the task to fix that issue.
The pack they are using is SkyFactory 3 (1.10.2).    
It would be nice if you could fix it. Or if you allow me  to make a push to you so you can release it.
At the moment the second option is not possible since i cant create dev invioments because gradlew gets connection crashes...

The fix could be really simple:
add a function that returns boolean as result and that throws a canBreakEvent(),
and add that function to all calls that would replace blocks.

Thanks for reading

**Comment by McJty** [comment]
Unfortunatelly I cannot fix this quickly as I have hardly any time this weekend and this is something that needs to be done carefully. I'll try to check it out as soon as possible though

**Comment by Speiger** [comment]
You think you would be able to fix until the end of next week?
(I will quote you on that one)

**Comment by McJty** [comment]
I did find *some* time.

I did not release this yet as I would prefer if you could test this a bit (I only did some local testing) but you can get a version that checks for break events here:

http://jenkins.k-4u.nl/job/RFTools/

If all is ok on your side with this then I can release this to the public.

Thanks

**Comment by Speiger** [comment]
Please tell me that rftools uses compact layer as basemod because then you will get no testresults. Since i requested it for 1.10.2...

**Comment by McJty** [comment]
All my mods use compatlayer so you will be fine

**Comment by Speiger** [comment]
^^"

**Comment by Speiger** [comment]
Turns out that we cant test it. For one reason: Its for a server and you gave out a version with a new version number. (for some things updating forge version ids is fine but small fixes like that should have the same version as the latest in code so servers can update without clients to do that. (for a server with over 100 people playing actively thats important)).

Luckly we exported your fix with a different version number (the one we need).
Testing is luckly happening soon with that fixed fixed version. We tell you the results later.

**Comment by McJty** [comment]
Well RFTools 5.90 is the latest so the version did correspond to the latest release of RFTools. Also when I'll do the fix fo realy this will be for RFTools 5.91 anyway

**Comment by McJty** [comment]
i.e. I didn't update the version number. I just reused the latest

**Comment by Speiger** [comment]
well he uses SkyFactory 3 so i assume that uses a outdated  version.

**Comment by McJty** [comment]
Fixed next release
