### ISSUE TITLE
When a Pearl Injector(and it's endergenic generator) is out side of a set of looped generators, it freezes the server

### ISSUE THREAD

**Issue by zlainsama** [McJty/RFTools#1108]
Versions:
- minecraft-1.10.2
- forge-1.10.2-12.18.3.2254
- mcjtylib-1.1x-2.3.11
- compatlayer-1.10-0.2.5
- rftools-1.1x-5.90

How to reproduce:

Condition 1: A Pearl Injector is already placed.
![2017-03-26_16 04 54](https://cloud.githubusercontent.com/assets/3251859/24329636/3882124e-123f-11e7-9df8-49cd235a0db8.png)
1. place 4 generators and another generator out side of the loop with a Pearl Injector next to it.
2. link four generators to form a loop.
3. try to link the fifth generator(the one with injector) to other generator will cause the server to freeze.

Condition 2: Five generators are already linked.
![2017-03-26_16 04 57](https://cloud.githubusercontent.com/assets/3251859/24329668/d1913e60-123f-11e7-9438-acb27e6b3a6c.png)
1. place 4 generators and link them with the wrench.
2. place another generator and link it to one of the four generators.
3. try to place a Pearl Injector next to the generator will cause the server to freeze.

Note:
- There is no crash report produced as the server just freeze, the server does not respond to commands and a server manager will have to terminate the server process.
- This happens in a singleplayer world as well as a multiplayer world.

**Comment by McJty** [comment]
Will check it out

**Comment by McJty** [comment]
Fixed next release
