### ISSUE TITLE
Machine blocks have improper solid block behavoir redstone wise

### ISSUE THREAD

**Issue by L0laapk3** [McJty/RFTools#1109]
minecraft version: 1.10
rftools version tested in: 1.1x-5.76

Have a look at the following image:
![Sample image](http://i.imgur.com/rjaINJA.jpg)

Expected behaviour: like any other solid block: The repeater would be powered from the redstone signal on the right, and the redstone dust beneath would be powered only by the pressure plate.

Right now, the machine blocks behave not like a solid block, and not like a nonsolid block, but more like a new kind of broken redstone behavoir that just seems to absorb all the redstone information and not pass anything along.

Admittedly, this bug does not have a very large impact, but it would clean up the mod more giving it an (even) higher standard. Also, this behavoir is very unlogical and not user friendly.

My hope is that this can be solved with a one-line fix.

Blocks tested:
-matter receiver
-matter transmitter
-dialing device
-dimension editor
I assume it applies to all machine blocks.

In case anyone is interested in an application where this fix would be useful: I had a simple pressure plate ontop of my matter receiver triggering some redstone circuit.

**Comment by McJty** [comment]
I don't want to change this behaviour as this will break many existing setups (including mine). I specifically coded redstone behaviour so that my machines 'eat up' the signal and it doesn't propagate. Otherwise it is very hard to have fine control over what machines should get redstone power and what machines don't if it simply propagates further. This behaviour is a choice and not a bug.

**Comment by L0laapk3** [comment]
I want to bring to your attention just how bad of a choice this is. Not only is this behaviour extremely unintuitive and completely goes against the spirits of the game, you also render many creative setups impossible with this choice, just because you (sorry) don't know how redstone works. I can only compare what you've done here to ripping a page out of a dictionary and throwing away the rest of the dictionary, just to make it a little easier to access this one page.

</rant>

**Comment by McJty** [comment]
I know how redstone works and this is exactly why this is implemented like I did because it was way too annoying with adjacent machines getting powered indirectly. This is my choice on how I implemented it and not because I'm lazy or not knowledgeable about redstone

**Comment by McJty** [comment]
Btw i wouldn't object to a PR implementing this optionally  (config)

**Comment by L0laapk3** [comment]
Please do, if every mod would start giving their own interpretation to "solid block" modpacks would not be playable.
