### ISSUE TITLE
crafting in a modular storage crashing

### ISSUE THREAD

**Issue by IchigoGames** [McJty/RFTools#1115]
i believe this is a rftools crash sorry if i am wrong about that here is the crash report

https://pastebin.com/DHjUkwxb

minecraft 1.11.2
rftools-1.1x-5.90
forge .2260

**Comment by McJty** [comment]
The crash doesn't contain anything that is related to RFTools. Why are you suspecting RFTools?

**Comment by IchigoGames** [comment]
your right my bad looks like it was the item that was crafted not the way it was crafted
