### ISSUE TITLE
(1.7.10) Builder block missing blocks.

### ISSUE THREAD

**Issue by StevenStone014268** [McJty/RFTools#1125]
A Builder block was set up with a Shape Card set to "Solid Box" to act as a filler to fill the caves under my base since for some reason there were a rather large amount of them this was done to help with mob spawning near my base however this didnt really decrease mob spawning with a completely lit up surface so i installed a xray mod to see if anything went wrong or some mistake on my end but ive double and triple checked the card and other settings and everything is set up to be a filler correctly but the builder block left two high gaps randomly in the selected area (256x256x60 cube) and other random one block gaps as well in this same area the only fix i found for this is to select the builder to make multiple passes on the gui but outside of using some sort of Xray to see if its actually finished the job properly or not there is no way to tell  since the builder will say its done wether its filled every single block in or not on the first pass and yes the builder block is in a always loaded chunk so that isnt the issue ^^ I apologize if its a feature but it seemed really strange to be a feature so i figured i would report it this bug appeared in for me project ozone 2 reloaded idk how that makes any difference but i thought i would include it I can add pictures if requested of what exactly the builder does when it misses these gaps

**Comment by BrianEdmonds** [comment]
One possible issue that comes to mind with using the Builder to fill in
caves, is if while placing things it causes an update that disturbs a
block such as gravel, that could then fall, leaving gaps the Builder
wasn't expecting. I don't know how it calculates the fill work, so could
see it getting out of sync with such changes in the world.

**Comment by McJty** [comment]
What Brian says is a possibility and not much I can do about that (especially not in 1.7.10 as I no longer work on that versoin)

**Comment by Blue64** [comment]
where would I find a Download for 1.7.10? I actually came here from CurseForge and none of the listed versions say they are for 1.7.10.
