### ISSUE TITLE
The sensor has to be reconfigured or broken and replaced after rotating it in order to work again

### ISSUE THREAD

**Issue by PapiDimmi** [McJty/RFTools#1136]
1. Place sensor.
2. Configure it to your liking.
3. Rotate it using some kind of wrench.
4. The sensor doesn’t work until you either change its configurations or break and replace it.

* **[Minecraft](https://minecraft.net) version**: [1.10.2](https://minecraft.gamepedia.com/1.10.2)
* **[Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) version**: [12.18.3.2272](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html)
* **[RFTools](https://minecraft.curseforge.com/projects/rftools) version**: [1.1x-5.91](https://minecraft.curseforge.com/projects/rftools/files/2399243)

**Comment by McJty** [comment]
Fixed next release

**Comment by PapiDimmi** [comment]
@McJty Thanks.
