### ISSUE TITLE
Storage Scanner Null Pointer Exception Crash

### ISSUE THREAD

**Issue by superfluke** [McJty/RFTools#1137]
https://paste.ee/p/eZhaJ

**Comment by McJty** [comment]
Sorry but you *really* need to give me more info. When is this happening? What is visible? Since many people are using this block with no issues I need to know the specific circumstances where this is crashing

Also what version of rftools?

**Comment by superfluke** [comment]
Not sure I can give you much more info that would help. Been using the scanner for a while and this is the first time I've hit an error. Version is in the crash log, 5.91. Happened while standing in a botania set up looking at a running endoflame and a mana spark, tried to open the wireless storage scanner tablet and got the crash/error. Have not been able to reproduce it. Storage scanner is attached to a few AA storage crates and powered by eio conduits.

**Comment by McJty** [comment]
I have no idea how this can happen but I'll add protection for it in any case
