### ISSUE TITLE
Terrain Absorber Liquid

### ISSUE THREAD

**Issue by hillsboro2d2p** [McJty/RFTools#1138]
Been trying to make a Liquid Terrain Dimlet.  I used the Terrain Absorber by placing it on the ground in water, using a angel block to ensure that water is directly underneath, and I have done this in an ocean biome.  All I get when the Terrain Absorber is placed in these situations is Terrain Normal.  Am I doing something wrong, if so what is it?

Thanks,

Hillsboro2D2p

**Comment by McJty** [comment]
The terrain absorber doesn't look at the blocks around it (would be a nice feature). In the overworld it will always give you normal terrain

**Comment by hillsboro2d2p** [comment]
So in order to get it to be liquid, the block would have to be used in an rf dimension that has generated a liquid terrain?

**Comment by McJty** [comment]
yep. At the moment you have to be lucky to be able to get that. I have some plans for the future to make this a more controlled process

**Comment by hillsboro2d2p** [comment]
Thank you.
