### ISSUE TITLE
Crash with RotaryCraft and RFTools

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#114]
Good Day,

I have created a new age:
http://pastebin.com/G4BuFMjK

When I entered the age my client crashed with error below:
http://pastebin.com/GrGJb3NA

Anytime I enter the game it crashes me. I can't do anything about.
Probably not RFTools error but RotaryCraft's, but still posted here, sorry if wrong.

Best Regards,
DeForce

**Comment by McJty** [comment]
Strange that this happens when teleporting to an rftools dimension though but indeed, the crash appears to be in RotaryCraft's code so hopefully Reika has a better idea of what is going on.

**Comment by RAnders00** [comment]
@ReikaKalseki poke

**Comment by ReikaKalseki** [comment]
As before, either (more likely) an Entity ID conflict between client and server (Forge and mod version mismatch?) or some mod like MobSpawnControls that thinks "An Entity! Must be a mob!".
