### ISSUE TITLE
Elevator TESR leaks render layer

### ISSUE THREAD

**Issue by tterrag1098** [McJty/RFTools#1140]
The render layer is not set back to its original value in the TESR, which corrupts the states for further renders (items).

See https://github.com/Chisel-Team/Chisel/issues/404

You should probably reset the state here https://github.com/McJty/RFTools/blob/1.11/src/main/java/mcjty/rftools/blocks/elevator/ElevatorTESR.java#L69

Additionally, you make quite a few draw calls in that renderer when it should only be a few, batch all blocks for a given layer together to save. Better yet, use [FastTESR](http://mcforge.readthedocs.io/en/latest/tileentities/tesr/#fasttesr)

**Comment by McJty** [comment]
I will check this out soon

**Comment by McJty** [comment]
One question. Is using a FastTESR a good idea for a moving object? If there are many other FastTESR's in the vicinity it will cause them to recalculate all together with every frame that the elevator moves

**Comment by McJty** [comment]
Hmm. How can I restore that state? I see no getter for it. There is a setRenderLayer() but no corresponding getRenderLayer()

**Comment by McJty** [comment]
Should be fixed next release
