### ISSUE TITLE
Endergenic Generator rendering issue

### ISSUE THREAD

**Issue by StefanTT** [McJty/RFTools#1141]
I am one of the maintainers of the [Faithful 32 texture pack](http://f32.me).

The endergenic generator in RFTools 1.1x-5.92 has a strange rendering issue when using the texture pack. As you see in the image, the pulsating ender pearls have a white background instead of a transparent one. Is there anything I can do in the texture pack to change this?

![minecraft 1 10 2_015](https://cloud.githubusercontent.com/assets/2863528/24962255/b06dcb40-1f9b-11e7-86fc-b9594539055c.png)

**Comment by McJty** [comment]
Hmm that's strange. I'm not sure what the faithful people changed that would cause this...

**Comment by StefanTT** [comment]
This is the ender pearl that is used in the texture pack.

![ender_pearl](https://cloud.githubusercontent.com/assets/2863528/24962803/38eeab0a-1f9d-11e7-9992-1ee08ac9fad4.png)

Is anything else used to generate the pulsating pearl, besides the ender pearl texture?

At the moment we have no specific textures for the endergenic generator in the texture pack. Several textures for RFTools, but afaik not this generator.

**Comment by StefanTT** [comment]
I found a workaround. The pearl that is used is not the one from minecraft items/ender_pearl.png but it is floatingpearl.png. Re-saving the F32 version of it with GIMP fixes the issue.

Thank you for your attention and sorry that I have bothered you.
