### ISSUE TITLE
Crasheo of RFTools and JABBA

### ISSUE THREAD

**Issue by HeberonYT** [McJty/RFTools#1147]
Hello
I have a public server with modpack SkyFactory 2.5, but it crashes when a jabba barrel is placed on the builder block.
I read that this error is old but has not yet been corrected, I hope it can help to solve it.
Regards!

Version of RFTools: rftools-4.23.jar
Version of JABBA: Jabba-1.2.2_1.7.10.jar
Minecraft 1.7.10

Crash Report: `https://pastebin.com/szFrGq2g`

**Comment by McJty** [comment]
Don't put a jabba barrel on top of a builder. The barrel can only hold one type of item. That's not suitable for builder output. Also this is most likely a bug in jabba and not in rftools as rftools is simply using the standard IInventory API.
