### ISSUE TITLE
Tool to manually edit user dimension

### ISSUE THREAD

**Issue by Schoktra** [McJty/RFTools#1153]
I set up a server so I could play my game from either my desktop or my laptop depending on whether or not I was away from home. I accidentally created an rftools dimension, and entered it, which has so many entities in it that no matter what machine I am using I can no longer successfully log in with my player. The connection crashes and times out before my client has even had any graphics show up. It would be nice to have a way to manually change my user's dimension back to the overworld so that I can finally load my game and go on playing it again.

**Comment by McJty** [comment]
I know that MCEdit can do that but not sure how. Never needed it myself
