### ISSUE TITLE
Void dimensions gets unloaded after leaving it

### ISSUE THREAD

**Issue by PhiPhiper** [McJty/RFTools#1155]
-Create void dimension
-Chunkload something in it
-Leave dimension and watch the server unload it although it has a chunkloaded(ftb utilities) chunk

===== Version
Modpack: FTB Beyond 1.5.3
Minecraft: 1.10.2
RFT-Dim: 1.1x-4.55

**Comment by McJty** [comment]
Please report that to FTB Utilities. I don't do chunk loading in rftools dimensions
