### ISSUE TITLE
Bug of crafter

### ISSUE THREAD

**Issue by forestbat** [McJty/RFTools#1156]
If the player leave GUI of crafter，settings of “keep/all” and “int/ext/extc” will be reseted and can't be saved。

**Comment by McJty** [comment]
Did you press apply to remember the setting?

**Comment by forestbat** [comment]
@McJty Yes I pressed。

**Comment by McJty** [comment]
I need more information.  Note that these settings are per recipe and I also know that other people have no trouble with this so can you describe in detail what you are doing?

**Comment by forestbat** [comment]
@McJty Oh，I’m sorry to disturb you because I didn't understand the crafter well，now there isn't trouble。
And I'm an editor of a Chinese minecraft encyclopedia website，www.mcmod.cn，do you agree us to repost your mod there？
