### ISSUE TITLE
Cherry Grove Dimension no trees

### ISSUE THREAD

**Issue by yo7duh** [McJty/RFTools#1158]
I'm trying to create a single biome dimension of Cherry Trees using the Cherry grove biome modifier with the Single controller. I have a bunch of efficiency dimlets and the peaceful dimlet, as well as all the default modifiers so there are no structures, effects, or dimlet huts. Skies and time are normal. However, every single time I generate a world, the biome *is* the Cherry Grove, but there are no trees. At least, not cherry trees. Industrialcraft rubber trees and random small jungle trees do spawn, but cherry trees are completely absent. 

I'm running the newest Dw20 1.10 pack, with nothing except the ExtremeReactors config modified back to default fuel usage. 

I recently had to load up a backup from a corrupted save, resulting in several dimensions existing but not being able to access any of them. I deleted these dimensions, but my minimap data for them still exists. Every time I create a new dimension, I'm using an old ID and when I enter, it reloads my Journeymap data, but over-writes the map as I explore. I'm not sure if this is causing any issues, but I don't really want to keep re-creating new dimensions and wasting ~3 million RF per until I start reaching new IDs.

**Comment by McJty** [comment]
What kind of terrain does the dimension have?

**Comment by yo7duh** [comment]
Everything is default, I'm sure. I put in a Normal Terrain dimlet. I tried some other biome controllers, but most of them tell me I have "too many biomes for XXX controller type".

**Comment by McJty** [comment]
Hmm, sounds like something which is handled in the biome itself and I don't have control over that. Perhaps the cherry biome only generates trees in the overworld or something

**Comment by yo7duh** [comment]
Ahhh, perhaps. Shame, but I guess it can't be helped. Thanks so much, honestly didn't expect a response this soon (it's 4 am here), but I'll just try something else. Thanks again!

**Comment by yo7duh** [comment]
I've done a bunch more testing, just generating random dimensions. 

It seems like none of the Biomes O' Plenty biomes will spawn trees, except for Rubber Trees from IC2, and trees from Pam's Harvestcraft (With the fruits and things on them). 

![2017-04-20_05 35 07](https://cloud.githubusercontent.com/assets/10333841/25225118/63fc7c36-258e-11e7-9a0b-60616a2a81c2.png)

![2017-04-20_05 52 41](https://cloud.githubusercontent.com/assets/10333841/25225122/69551b16-258e-11e7-9d22-347c0a2ac81b.png)

![2017-04-20_05 42 31](https://cloud.githubusercontent.com/assets/10333841/25225131/717204ee-258e-11e7-9028-cc3a2140a7ec.png)

Doesn't seem to happen with vanilla biomes though.

![2017-04-20_05 49 37](https://cloud.githubusercontent.com/assets/10333841/25225143/77130ea2-258e-11e7-97f1-b93b3a202a07.png)

![2017-04-20_05 47 01](https://cloud.githubusercontent.com/assets/10333841/25225146/7a7a8688-258e-11e7-8b82-a324f7ae6c02.png)

I found this issue which seems to be similar:
https://github.com/Glitchfiend/BiomesOPlenty/issues/818

I'm using a newer Forge version (2254). Maybe it just hasn't been fixed yet.

**Comment by yo7duh** [comment]
Ahhh I figured it out, really silly issue. 

Seems that Dw20 1.10 modpack has BoP generation disabled by default, meaning that the biomes won't actually be generated, regardless of whether you enable it after creating your world or not. 

Mods that add custom dimensions aren't able to use the BoP generation and create said biomes properly. The grass changes color and the blocks generate, but apparently not trees.

The solution is to create a new world after enabling BoP generation.

Sorry about that, but thanks for trying to help anyway.
