### ISSUE TITLE
[1.11.2] 6.00 XNet Storage Channel (non-crash, server, error)

### ISSUE THREAD

**Issue by Minizbot2012** [McJty/RFTools#1159]
Whilst playing around with the storage channel on my server I ran into this error being printed into the server console, it works on a single player test world, but not on the remote server. I have it connected to actually additions storage crates (though it works on Single Player, and is also happening with other inventories). It is a world that has upgraded from a previous RFTools version to 6.00, and XNet to 1.3.0 (now 1.3.1, and still happening)

Also to mention that when scanning in the storage scanner, it doesn't find the inventory on the server.

Error log:
https://pastebin.com/Uap41tTm

**Comment by legodude17** [comment]
Why did you report this on RFTools? This seems like an XNet issue.

**Comment by Minizbot2012** [comment]
It is the RFTools storage channel causing it, that was added in 6.00

**Comment by legodude17** [comment]
Ah

**Comment by Minizbot2012** [comment]
I seem to have fixed it just by A) removing the torcherinos nearby, and B) removing an old fixer mod for XU2 (which has been since fixed)
