### ISSUE TITLE
Buider Quarry mode stuck when trying to mine blocks with multiple drops.

### ISSUE THREAD

**Issue by SiblisCu** [McJty/RFTools#1160]
Minecraft 1.10.2, Rftools 5.92.
When the builder in quarry mode try to mine a block witch drop more than one type of item it stops mining. If the block is breaked by other means it continues to work normaly.
This happens with ruby ore when you have tech reborn installed (it drops ruby + red garnet) and gregtech small ores when they drop more than one thing (chance based).

**Comment by McJty** [comment]
What kind of quarry (i.e. type of card)? I have never encountered this before. Very strange

**Comment by SiblisCu** [comment]
The real problem was that the inventory on top of the builder only had one slot (en actually additions ESD that pushed the items into an item interface).

**Comment by McJty** [comment]
Ah yes, that doesn't work I'm afraid
