### ISSUE TITLE
Crash - Conflicts with Conquest Reforged Mod

### ISSUE THREAD

**Issue by DrakeEldridge** [McJty/RFTools#1161]
Whenever I add RFTools I crash, and if I remove Conquest Reforged or remove RFtools, everything works, but having both mods in at the same time, crashes everything every time. I would like to keep Conquest Reforged as it adds a lot for building, but would also like to have RFTools for the Redstone components. 
Hopefully, you can fix this.

Forge Version: forge-1.10.2-12.18.3.2272-universal
RFTools Version: rftools-1.1x-6.00
Conquest Reforged Version: ConquestReforged-2.0.1-RC1-mc.1.10.2

**Comment by legodude17** [comment]
Please provide a crash log.

**Comment by DrakeEldridge** [comment]
[crash-2017-04-27_15.07.33-client.txt](https://github.com/McJty/RFTools/files/960334/crash-2017-04-27_15.07.33-client.txt)

there u go

**Comment by McJty** [comment]
The crash is in 	at me.dags.blockpalette.palette.PaletteRegistry.getModel(PaletteRegistry.java:243)

That's not rftools so I think that is fro conquest reforged possibly? If so please report to them as it is most likely on their side
