### ISSUE TITLE
Spawner Bugged?

### ISSUE THREAD

**Issue by SkippyMitch** [McJty/RFTools#1162]
![2017-04-23_22 37 35](https://cloud.githubusercontent.com/assets/27940256/25321660/f72f926a-2875-11e7-9363-73203bcf99f8.png)

I tried beaming two different living materials, but they always go to the top slot...

**Comment by McJty** [comment]
Make sure you are on a recent version on RFTools and then remove your config. There was a bug in the config

**Comment by SkippyMitch** [comment]
I was on 1.10 - 5.62  
just updated it thank you
