### ISSUE TITLE
Crash on load after windows update

### ISSUE THREAD

**Issue by Ryzi1015** [McJty/RFTools#1164]
Minecraft crashes on load when running rftools after the latest update for windows 10. I originally discovered this when playing all the mods 2. I ran another clean install with only rftools plus the required libraries and was met with the same crash.

I couldn't see an obvious error in my crash log.

After reverting to the previous version of windows I was able to play rftools.

https://pastebin.com/GyhGGFyW

**Comment by McJty** [comment]
There must be another reason because there is literally no way this can have anything to do with RFTools. I do note that you are using an old version of java8 so I'm wondering if that's the case

**Comment by Ryzi1015** [comment]
Java update fixed it! Strange thing was the newer version was already installed but minecraft wasn't using it. Thanks for your help McJty!
