### ISSUE TITLE
Problem with Dimensional Enscriber

### ISSUE THREAD

**Issue by leradicateur** [McJty/RFTools#1165]
Hello,

We have a little problem with this mod.
When we click on the Dimensional Enscriber, we have this message : 
you cannot make a dimension without an owner dimlet

Can you help us?

cordially
leradicateur

**Comment by McJty** [comment]
Apparently your server admin chose to disallow dimensions without owner dimlets. That's a config option

**Comment by leradicateur** [comment]
Thanks for your answer.

But where i can find this config option? I have an access.

**Comment by McJty** [comment]
The option is named:

    # If this is enabled (non-craftable) owner dimlets are required to construct dimension tabs. This is useful on servers where you want to limit the amount of dimensions a player can make
    B:ownerDimletsNeeded=false

I cannot tell you where it is because that depends on the version of rftools and rftools dimensions which you didn't specify

**Comment by leradicateur** [comment]
version 1.10.2

**Comment by McJty** [comment]
Then in dimensions.cfg

**Comment by leradicateur** [comment]
Yeah i found it

**Comment by leradicateur** [comment]
thank you very much

**Comment by McJty** [comment]
No problem

**Comment by leradicateur** [comment]
Hello,

We hae change the option but nothing change, same messageé

Have you an idea why?

Cordially
leradicateur
