### ISSUE TITLE
Crash when Builder Block is in claimed area

### ISSUE THREAD

**Issue by Firnagzen** [McJty/RFTools#1171]
Hey McJty, I have a crash when a Builder Block is placed within an FTB Utilities chunk claimed area. This was not a problem prior to RFTools 5.8.4. Here's a crash log, is there anything else I can provide? https://gist.github.com/robertmaxton42/adfec523e3d835d7f51fc8d7eba6aeea
I've tried picking up and replacing the builder block, and I've verified that it does in fact break the blocks correctly when the setup is not claimed.

**Comment by McJty** [comment]
Fixed by updating FTBU
