### ISSUE TITLE
Endergenic generator weird? not changing even after making changes to a setup.

### ISSUE THREAD

**Issue by levaritie** [McJty/RFTools#1177]
So actualy I dont realy know if this is a bug or something but its definitly a issue!

As title states above even after making changes to a endergenic generator setup the numbers dont change..
I made a setup that has 6 generators and a pearl injector then my booting sequence is perfect I get arrive at 10, yeay. now the loop thing I use the monitors set to when fired and more sequencers. now the problem I have is when its in the loop generator 1 the one with the injector losses power all the time, generator 2 - 6 have arrive at 12 even when I make them charge later or earlier.. wich is weird? right I mean.. generator 1 always has arrive at 1 while the rest have arrive at 12. even if acourding to counting with ticks and travel time they should get arrive at 10. I have read the manual over and over again looking for something I missed but I cant find anything I think this should work.. I will make a screen shot of the setup and of 1 of the sequencers since they are all the same.

![sequencer](https://cloud.githubusercontent.com/assets/24458945/25783319/a54b3612-335a-11e7-91bb-801cd239ec4b.png)
![setup](https://cloud.githubusercontent.com/assets/24458945/25783320/a54b94cc-335a-11e7-89d5-f99b7e61f230.png)

so if I am just crazy.. please tell me?

yours truely 

Pack: Direwolf wolf 1.9.1 + Metroid cubed 3 latest.  
Mod version : 1.1x6.00
Forge: 12.18.3.2254

Levaritie

**Comment by McJty** [comment]
Are they all linked correctly?

**Comment by levaritie** [comment]
Yes they are

**Comment by McJty** [comment]
Not sure what is wrong with the timing but you can see that the middle endergenic has 'last pearl arrived at 1' which is way too soon for good results. It is hard to disgnose this from here though

**Comment by levaritie** [comment]
The problem I have is the sequencers are all the same with settings and everything but only the middle gives  "arrived at 1"

**Comment by McJty** [comment]
Well it is not because they are the same that they should give the same results because it also depends on what order the tile entities in a chunk tick (btw, is everything in one chunk?)

So you might want to adjust the settings of each sequencer to get the good results for every endergenic

**Comment by levaritie** [comment]
yes the intirety is in 1 chunk, so I should try and make  generator 1 in this case recharge 9 ticks earlier?. I could try that.

**Comment by levaritie** [comment]
omg.. I changed this (see picture 1) sequencer to 0 1 0 1 (see picture 2) result on all but the middle first one. (see picture 3)

![2017-05-07_19 38 22](https://cloud.githubusercontent.com/assets/24458945/25783461/f2b5d5c2-335c-11e7-8084-4d14dc254417.png)
![2017-05-07_19 38 25](https://cloud.githubusercontent.com/assets/24458945/25783463/f3e1dbf8-335c-11e7-9a90-6c2c1007794c.png)
![2017-05-07_19 38 50](https://cloud.githubusercontent.com/assets/24458945/25783464/f595377e-335c-11e7-9c9b-75146a6c0d6a.png)

**Comment by levaritie** [comment]
Futher observations shown that this one particular sequencers has power over all other generators...

**Comment by McJty** [comment]
Well the timing of one sequencer can of course influence the behaviour of everything as it also changes when the pearl will arrive in the next endergenic and so on. This is why this is complicated to get right :-)

I must admit that I find it easier to code such a system then to actually create a working generator with it :-)

**Comment by levaritie** [comment]
still disturbing how this one generator now has no energy loss though even thought the pearl stays 1 tick inside

**Comment by levaritie** [comment]
![2017-05-07_19 51 06](https://cloud.githubusercontent.com/assets/24458945/25783575/8dc022ba-335e-11e7-8ff5-31861db3f7eb.png)
There mission acompliced. I suppse I should remove this github post then?

**Comment by McJty** [comment]
Just close it. That will be fine. Good job :-)
