### ISSUE TITLE
[1.10.2] [v6.00] Storage Scanner Client Crash

### ISSUE THREAD

**Issue by Alaberti** [McJty/RFTools#1179]
https://pastebin.com/W7mFRZD6

Dedicated server, forge 2281. As far as I'm aware, the player who got the crash when using a scanner to scan an actually additions item interface connected to various storage drawers and crates via actually additions item lasers. I have not heard of the issue happening again, so it seems to be infrequent.

**Comment by legodude17** [comment]
More info please. What version of rftools?

**Comment by Alaberti** [comment]
V 6.00, as listed in the title and crash report.

**Comment by legodude17** [comment]
What specific version?

**Comment by Alaberti** [comment]
1.10.2, also in the title and crash report.

**Comment by legodude17** [comment]
No, what is the specific version of RFTools?

**Comment by Alaberti** [comment]
...RFTools Version 6.00 for 1.10.2. Is there another way you would like to me repeat the same information?

**Comment by legodude17** [comment]
What is the name of the RFTools jar?

**Comment by McJty** [comment]
Legodude, it is ok. I have enough information. There is only 6.00 RFTools

**Comment by legodude17** [comment]
@McJty Sorry. Thanks for the info though!

**Comment by Alaberti** [comment]
Haven't seen the issue since, will re-open if we get it again.
