### ISSUE TITLE
Yellorium ore as a dimlet

### ISSUE THREAD

**Issue by TheDutchMC04** [McJty/RFTools#1181]
@McJty Could you please add Yellorium ore/block to the dimlets. I tried it with the userdimlets.json, but that doesn't work.

**Comment by McJty** [comment]
What version of MC?

**Comment by McJty** [comment]
Lack of response

**Comment by soerenkk** [comment]
I would like it as well.

I've checked the [changelog](https://github.com/McJty/RFTools/wiki/RFTools-Changelog-1.10.2), but it doesn't mention anything to indicate that a Yelloruim dimlet have been added.

I'm playing the Direwolf20 1.10 modpack.

The modpack is currently running MC version 1.10.2, and the current RFTools Dimensions version is 4.55 (rftoolsdim-1.1x-4.55.jar as the Curse launcher informs me).

My current dimlets.json file looks like **[this](https://gist.github.com/soerenkk/db8f666e5e67c7e67b280b07182bdad2.js)**. I've added 2 custom dimlets (when I closed the game the file got regenerated for some reason, so they aren't showing up in the gist), where I've used one of the others as a template, no luck unfortunately. Before you ask, yes I've put them before the line as I've seen you referring to on Reddit posts among others. And I'm a programmer myself, and have been working a lot with JSON for some years, and I can perfectly say that it wasn't a syntax error I've created in the JSON file.

**Comment by TheDutchMC04** [comment]
Version 1.10.2


Op 9 mei 2017 18:25 schreef "McJty" <notifications@github.com>:

**Comment by McJty** [comment]
I cannot download that dimlets.json file. It looks like garbage. Can you try to upload it differently? Perhaps as a zip file?

**Comment by TheDutchMC04** [comment]
This is my Json file: http://thedutchminecrafters.tk/thehub/audio/downloader.html (couldn't upload a zip or JSON)

**Comment by McJty** [comment]
That's a userdimlets.json from 1.7.10. That no longer works in 1.10. Check this documentation to see how to do it in 1.10:

https://wiki.mcjty.eu/mods/index.php/RFTools_Dimensions
