### ISSUE TITLE
Issue with eat the eggs mod

### ISSUE THREAD

**Issue by LocoMinerDad** [McJty/RFTools#1183]
I added some fried eggs into a storage module and I can't get them out. They show up visually. I just cant click on them.

**Comment by LocoMinerDad** [comment]
Now it's happening with enchanted books, and bauxite

**Comment by McJty** [comment]
This is probably caused by some mod that adds NBT data to items client side. I've seen this reported before

**Comment by LocoMinerDad** [comment]
I am not sure if that's the problem. Also how do you transmit redstone power in your mod

**Comment by McJty** [comment]
You can transmit redstone power wirelessly using the receiver and transmitter. Is that what you mean?

**Comment by LocoMinerDad** [comment]
Yes it is. Thank you.  Going to close the thread.
