### ISSUE TITLE
Problem with same ID

### ISSUE THREAD

**Issue by DvnBthlo** [McJty/RFTools#1185]
Hello, I've created a dimension and they created with the same ID without deleted previous dimension.
Screen -> 
http://prntscr.com/f7j603
http://prntscr.com/f7j63p

**Comment by McJty** [comment]
If you use exactly the same dimlets you get exactly the same dimension. i.e. there will be no new dimension created. Use 'digit' dimlets to make new random dimensions if that's what you want to do
