### ISSUE TITLE
Rrfdim commands

### ISSUE THREAD

**Issue by DvnBthlo** [McJty/RFTools#1186]
Hello, Can you help me: How the default users on server can delete your dimension - If he write /rftdim safedel <id> ->  Command is not allowed!

**Comment by DvnBthlo** [comment]
*yours dimension

**Comment by McJty** [comment]
This is a config option that must be enabled first before this works

**Comment by DvnBthlo** [comment]
I enable this:    B:playersCanDeleteDimensions=true
But it's still the same thing

**Comment by McJty** [comment]
Enabled on both server and client config?

**Comment by DvnBthlo** [comment]
yes

**Comment by McJty** [comment]
Can you show me both configs? (client and server)

**Comment by DvnBthlo** [comment]
Server: https://pastebin.com/Q3rSZ0Wr
Client: https://pastebin.com/ADfxM61J

**Comment by DvnBthlo** [comment]
? :)

**Comment by DvnBthlo** [comment]
@McJty ?

**Comment by McJty** [comment]
I'll get to this eventually. A bit busy right now

**Comment by McJty** [comment]
I cannot reproduce this and I don't understand why it wouldn't work. Can you try if deleting the dimension works by sending tnt to the dimension with the dimension editor?
