### ISSUE TITLE
Builder in the Nether issue

### ISSUE THREAD

**Issue by SummaryPick** [McJty/RFTools#1187]
I have a clearing quarry card going in the nether, and for some reason, it is mining dirt... I'm really confused as to why this is since dirt doesn't spawn in the nether.  I am in Minecraft 1.10.2, playing in the Modpack AllTheMods.  I also have a builder running a normal quarry in the overworld, but it voids dirt.

**Comment by SummaryPick** [comment]
I am the only person on the world, it's working now.  I don't really know how to explain what just happened.  It's working normally now so i guess the problem is fixed? lol

**Comment by SummaryPick** [comment]
BTW, I love your work.  RFTools is amazing.  Never had a problem before now and it seems to have fixed itself!

**Comment by McJty** [comment]
Self-fixing mod :-)

**Comment by SummaryPick** [comment]
If a modpack doesn't include RFTools I won't play it! Simple as that :P
