### ISSUE TITLE
Will the RFT builder block work in a galacticraft space station dimension?

### ISSUE THREAD

**Issue by idiot101300** [McJty/RFTools#1188]
I am trying to build the giant sphere basis for the death star using the builder, i have it set up correctly and the preview blocks display exactly what i want but it refuses to build anything even when supplied with materials, power and redstone

**Comment by McJty** [comment]
How are you giving it the materials? Chest has to be on top or below

**Comment by idiot101300** [comment]
i tried both

**Comment by McJty** [comment]
Ok, first I need your version of RFTools. Then show me some pictures of your setup and the gui as well as the configuration of the card

**Comment by idiot101300** [comment]
1.7.10 RFTools 4.23
http://imgur.com/a/njaIz

**Comment by McJty** [comment]
A button will not work. You have to keep giving it a redstone signal. A button only gives a redstone pulse. Use a lever instead

**Comment by idiot101300** [comment]
Oh right derp. thanks
