### ISSUE TITLE
Syringe capturing fireball essences

### ISSUE THREAD

**Issue by Lukas45** [McJty/RFTools#1189]
Was trying to get Ghast essence for my Flight module, and what better way than to spam a syringe at a ghast so it doesn't die.
Well, turns out the Syringe can capture the essence of the Fireballs that the Ghasts shoots, which overwrites the Ghast essence you already collected.
![2017-05-15_16 17 42](https://cloud.githubusercontent.com/assets/4707702/26062408/027c1a00-398b-11e7-8cbf-ed1e11ef62e2.png)

Of course could be intended to increase the difficulty of getting RF powered flight? :b

**Comment by legodude17** [comment]
Can you spawn a fireball?

**Comment by Lukas45** [comment]
![18013272819831698c1e8ef437937a60 1](https://cloud.githubusercontent.com/assets/4707702/26126131/cab9c568-3a84-11e7-845e-e3e2531e9e37.png)
Doesn't look like it :P

**Comment by legodude17** [comment]
It doesn't look like it

**Comment by MRVDOG** [comment]
yeah, I just had this happen, spent 2 hours in nether hunting for ghasts and trying to get close enough to hit them with the syringe, got to 90%, then Fireball!!! -_-
https://ss.mrvdog.com/13687i3d4YT

**Comment by josephcsible** [comment]
Fixed in 7.22 and above by 61e37da.
