### ISSUE TITLE
Dimension maintenance cost is bugged

### ISSUE THREAD

**Issue by Zartanis** [McJty/RFTools#1192]
I'm playing project Ozone 2 and for a completely blank dimensional tab I get this kind of cost. Any idea?

![image](https://cloud.githubusercontent.com/assets/28744594/26134469/f01e94ee-3a7c-11e7-8569-851e568d6797.png)

**Comment by McJty** [comment]
That's because in PO the pack is configured so that random features get the full cost. Not a bug in rftools dimensions but just how it is configured

**Comment by Zartanis** [comment]
Hmmm. I've seen other people's play throughs that didn't have this problem. I'd hate to think it's just me but if that how the mod pack is set up i might as well cheat on a creative one...

**Comment by McJty** [comment]
That's because the dimension is random. It is possible you got some expensive random features that others didn't get

**Comment by Zartanis** [comment]
I understand that but even with the blindness dimlet that is supposed to reduce the cost by 400% the dimension was costing rough 2 million rf/tick. Maybe I'm insanely unlucky/lucky with my dimensions. Ive tried 3 variations in total. All of which have cost well over a million rf/tick to maintaine. I have use this mod b4 and this is my first encounter with this kind of thing. The dimlets are amazing btw. A lot of fun can be had with them.

**Comment by McJty** [comment]
I haven't played this pack myself but I have heard you can easily get crazy amounts of RF generation in it. i.e. everything is pimped up basically

**Comment by Zartanis** [comment]
I can't say I'm at that point. Our big reactor only generates half a million rf. Thanks for the help
