### ISSUE TITLE
Shield looting eats dimensional shards

### ISSUE THREAD

**Issue by SkippyMitch** [McJty/RFTools#1193]
The shield generator seems to eat way too many dimensional shards. 
 - added a stack of shards 
 -  spawned a ghast 
 -  activated shield  
 Instantly ate the whole stack after only one kill. 

Granted this is a large shield with over a stack of shield template blocks. Is it supposed to use a shard 'per' shield block? that would explain this insane consumption.

![2017-05-17_01 22 33](https://cloud.githubusercontent.com/assets/27940256/26141036/7ac485dc-3a9f-11e7-8048-45d12b42a22a.png)

 1.1x - 6.00

**Comment by McJty** [comment]
yes, it is per shield block. A better solution is to only enable this for a smaller sub shield and have the rest of the shield normal non-damaging but solid shield. That's also more efficient for power usage

**Comment by SkippyMitch** [comment]
Hmm. hard to contain a ghast to an area where it touches that one block.

**Comment by SkippyMitch** [comment]
Thanks this can be closed now :D
