### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by LocoMinerDad** [McJty/RFTools#1198]
Hello,

Minecraft 11.2
forge .2282
rftools 6.01

issue, after inserting a stack of dirt into the storage system my game crashes and wont reload. Maybe you can understand this mess better than I.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  CorePlugin (FluxedRedstone-2.6.1.59.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/22/17 5:14 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at futurepack.depend.api.LogisticStorage.canInsert(LogisticStorage.java:185)
	at futurepack.common.block.machines.TileEntityEFurnace.func_180462_a(TileEntityEFurnace.java:218)
	at mcjty.lib.container.InventoryHelper.mergeItemStackInternal(InventoryHelper.java:348)
	at mcjty.lib.container.InventoryHelper.mergeItemStackSafe(InventoryHelper.java:286)
	at mcjty.lib.container.InventoryHelper.insertItem(InventoryHelper.java:205)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.injectStackInternal(StorageScannerTileEntity.java:247)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.func_73660_a(StorageScannerTileEntity.java:182)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at futurepack.depend.api.LogisticStorage.canInsert(LogisticStorage.java:185)
	at futurepack.common.block.machines.TileEntityEFurnace.func_180462_a(TileEntityEFurnace.java:218)
	at mcjty.lib.container.InventoryHelper.mergeItemStackInternal(InventoryHelper.java:348)
	at mcjty.lib.container.InventoryHelper.mergeItemStackSafe(InventoryHelper.java:286)
	at mcjty.lib.container.InventoryHelper.insertItem(InventoryHelper.java:205)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.injectStackInternal(StorageScannerTileEntity.java:247)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.func_73660_a(StorageScannerTileEntity.java:182)

-- Block entity being ticked --
Details:
	Name: minecraft:rftools_storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity
	Block type: ID #655 (tile.rftools.storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerBlock)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (281,65,-26), Chunk: (at 9,4,6 in 17,-2; contains blocks 272,0,-32 to 287,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #655 (tile.rftools.storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerBlock)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World 2
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 717 Drop: 0
	Level seed: 7389896221439872286
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (180,64,256), Chunk: (at 4,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6272229 game time, 6846414 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 117448 (now: false), thunder time: 63624 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1268139680 bytes (1209 MB) / 2772434944 bytes (2644 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	animalbikes{1.11.2} [Animal Bikes] (AnimalBikes_1.11.2(24jan17).jar) 
	UCHIJAAAA	animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
	UCHIJAAAA	anvils{1.3.1.1} [Anvil Enchantments] (AnvilEnchantments-1.11.2-1.3.1.1.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-3.2.2} [TheDragonLib] (thedragonlib-1.11.2-3.2.2.jar) 
	UCHIJAAAA	armorplus{1.11.2-10.3.2.3} [ArmorPlus] (armorplus-1.11.2-10.3.2.3.jar) 
	UCHIJAAAA	ceanimals{1.3.1} [Crop-Eating Animals] (ceanimals-1.11.2-1.3.1.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	d3core{1.3.0.66} [D³Core] (D3Core-1.11.2-1.3.0.66.jar) 
	UCHIJAAAA	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCHIJAAAA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.11.2.jar) 
	UCHIJAAAA	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	gbook{1.6.0} [Guidebook] (Guidebook-1.11.0-1.6.0.jar) 
	UCHIJAAAA	enderrift{2.1.4} [Ender-Rift] (EnderRift-1.11.2-2.1.4.jar) 
	UCHIJAAAA	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	reborncore{2.14.2.94} [Reborn Core] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.14.2.94} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.1.59.jar) 
	UCHIJAAAA	sonarcore{4.0.0} [SonarCore] (SonarCore-1.11.2-4.0.0.jar) 
	UCHIJAAAA	fluxnetworks{2.0.0} [FluxNetworks] (FluxNetworks-1.11.2-2.0.0.jar) 
	UCHIJAAAA	fp{25.2.39 pre} [Futurepack] (Futurepack-1.11.2-25.2.39.jar) 
	UCHIJAAAA	fp.api{1.1.0} [Futurepack API] (Futurepack-1.11.2-25.2.39.jar) 
	UCHIJAAAA	gravelminer{5.1.1} [GravelMiner] (GravelMiner_1.11-5.1.1.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCHIJAAAA	intwheel{1.2.6} [Interaction Wheel] (intwheel-1.1x-1.2.6.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
	UCHIJAAAA	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.14.4-1.11.2.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.8.1440} [MineColonies] (minecolonies-universal-1.11.2-0.8.1440.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.2-1.11.2.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJAAAA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJAAAA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJAAAA	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.1x-1.6.8.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (SimpleGrinder-3.132.R11112.jar) 
	UCHIJAAAA	simplegrinder{3.122.R1112} [Simple Grinder] (SimpleGrinder-3.132.R11112.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHIJAAAA	toolbelt{1.6.1} [Tool Belt] (ToolBelt-1.11.2-1.6.1.jar) 
	UCHIJAAAA	trashslot{7.4.7} [TrashSlot] (TrashSlot_1.11.2-7.4.7.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	vending{1.4.3} [Vending] (vending-1.11.2-1.4.3.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CorePlugin (FluxedRedstone-2.6.1.59.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.2.jar)
  
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	d3core: Debug: false Silliness: true AprilFools: true PastPost:true
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.2.94
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by McJty** [comment]
It is crashing in LogisticStorage. Their item handler implementation most likely doesn't support null for side. Please report to them. You can refer to this if you want. I can advice them

**Comment by Wugand** [comment]
Hi, please help us understanding the problem.
Why your mod pass an null faceing? and what should it mean? 
It make not sense for me to insert from and magical unknow side ... specially we have rules configuratable IO rules for every face.
So what do you mean is the right reaction on it?

Thank you

**Comment by McJty** [comment]
Check the documentation for capabilities. Null is a valid direction and means direct access to internal slots. It is used by mods that have to access an inventory remotely

**Comment by McJty** [comment]
Check this:

    /**
     * Determines if this object has support for the capability in question on the specific side.
     * The return value of this MIGHT change during runtime if this object gains or looses support
     * for a capability.
     *
     * Example:
     *   A Pipe getting a cover placed on one side causing it loose the Inventory attachment function for that side.
     *
     * This is a light weight version of getCapability, intended for metadata uses.
     *
     * @param capability The capability to check
     * @param facing The Side to check from:
     *   CAN BE NULL. Null is defined to represent 'internal' or 'self'
     * @return True if this object supports the capability.
     */
    boolean hasCapability(@Nonnull Capability<?> capability, @Nullable EnumFacing facing);

**Comment by Wugand** [comment]
Ok, how I remember we said: we don't use "internal" and see no reason why other mods should use this to our machines. Seems we understood the "internal"/"self" in other way  ... well no matter.

Thanks for the information. We try to implement this case.

**Comment by mcenderdragon** [comment]
@McJty and why is your storage system using null? I mean your item pipes have a side right?

**Comment by McJty** [comment]
Actually the advanced connectors can connect from any random side so they don't know what side they will connect from when you place them in the world. That's why they are using null

**Comment by mcenderdragon** [comment]
well the capbilitys support null, but unfortunietly the IsidedInventory dont... can you also try to put a try catch around it so it wont break the whole game? Or will this makes things worse?

**Comment by McJty** [comment]
What can't you support null for ISidedInventory?

**Comment by mcenderdragon** [comment]
for exmplke my pipes render the item form the side they get inserted, so null is in this case difficult.

**Comment by McJty** [comment]
Well what will happen if they do the same through the itemhandler? How is that different?

**Comment by McJty** [comment]
In any case, whatever you do. Don't crash. If you don't want to support null then that's fine but at least put 'if' checks in there and don't cause a null pointer exception

**Comment by mcenderdragon** [comment]
so 1.11 and nulls again...,
