### ISSUE TITLE
RF Tools crafter crash

### ISSUE THREAD

**Issue by misterfixit** [McJty/RFTools#12]
I was trying to use the crafter to make a lapotron crystal from IC2, the energy crystal seemed to have a different meta data than what the recipe calls for, I attempted to bypass this with the crafter causing a server crash. I got this crash http://pastebin.com/ctXEuQQc

**Comment by McJty** [comment]
I assume this can be closed? If you still have this problem then please reopen with exact steps to reproduce. Thanks
