### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jermangarc** [McJty/RFTools#120]
Not sure if this is a configurable fix, any help with this error is much appreciated. Everything worked fine until I updated to latest version. Playing on a SMP server with version 2.61. I updated to latest 2.70 and upon testing update on a new world I got error  http://pastebin.com/3FAfEpfc trying to load new world. No crash report just takes me back to main menu.

**Comment by McJty** [comment]
Hmm, a similar report was also send to me. I'll see what's up there.

**Comment by McJty** [comment]
Can you test if the latest dev build fixes the crash:

https://drone.io/github.com/McJty/RFTools

Thanks!

**Comment by jermangarc** [comment]
Update: Tried the DEV download... nope still same error. Here is the error http://pastebin.com/kzPMcrQh.

**Comment by McJty** [comment]
Yes, I know. But there is another dev download that fixes it for real now :-)
Number 204 has been confirmed by someone else to work.

**Comment by jermangarc** [comment]
I will check in a bit, thanks.
