### ISSUE TITLE
All your Dimlets 'R belong to us

### ISSUE THREAD

**Issue by CharZinta** [McJty/RFTools#1200]
History: I ran into this bug once before in 1.7.10 but McJty fixed it faster than I could report it.

Problem: All Dimlets when created get the ID2 flag and only point to one world. The first person to create said world can use it and access it but no one else can. Users can give different names to Dimlets but they all get ID2 and different names.

Reproduce:  steps below
1) clean world
2) user 1 makes a rftools dimension szetup
   2a) enscriber, builder, dialer, analyzer, transmitter, and receiver
3) making one dimlet place in inscriber, name not required but helps confirm test.
4) place in builder and let it build.
5) a DIFFERENT user does the same steps and by step 3 will find his dimlet is ID2 and no matter what you name it, or not at all, it wont ever work.

**Comment by McJty** [comment]
That's normal. If you use the same sequence of digits you will always get the same dimension. This is a way to create duplicate dimension tabs to power the same dimension from different builders.

Use digit dimlets to make new random dimensions.
