### ISSUE TITLE
Number of channels available for Redstone Transmitter

### ISSUE THREAD

**Issue by ResqDiver1317** [McJty/RFTools#1205]
Not so much an issue, more a question that I haven't been able to find the answer for. We are wondering how many channels are available for the RFTools transmitters and receivers? One of our players thought 17, but I thought I remembered seeing channel numbers in the 70s or 80s on one of our servers. Also, are these channels shared by all players (ie, player one setups u 5 devices so they get channels 1-5, then player 2 sets up 3 devices, would they get channels 6-8 or would they get their own 1-3 that don't interfere with player 1's channels? I'm sure this probably seems like a odd/pointless question, but one of our players asked me this morning so I spent an hour trying to find the answer online before I gave up and decided to just post this.

**Comment by McJty** [comment]
You have about 2 billion channels (that's until integers run out)
