### ISSUE TITLE
rftools-1.1x-5.92 crash

### ISSUE THREAD

**Issue by ktole1999** [McJty/RFTools#1206]
here is crash report from server. user tried to create world and it crashed on 2 seperate attempts. Any help is greatly appreciated.

https://gist.github.com/ktole1999/3f67cf132f58cf1946f84251a9f6cc5e

**Comment by McJty** [comment]
It is crashing in Sponge. Please report to them

**Comment by ktole1999** [comment]
thanks. reported.
