### ISSUE TITLE
Can't start game

### ISSUE THREAD

**Issue by 47delasPECII** [McJty/RFTools#1209]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.7.102.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  HammerCoreCore (HammerCore_1.10.2-1.6.9.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  AppEngCore (AppliedenErgistics2-rv4-alpha-11.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/28/17 7:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: java.lang.NoSuchFieldError: field_190927_a
	at mcjty.lib.tools.ItemStackTools.getEmptyStack(ItemStackTools.java:88)
	at mcjty.rftools.blocks.spawner.SpawnerConfiguration.readMobSpawnAmountConfig(SpawnerConfiguration.java:162)
	at mcjty.rftools.blocks.spawner.SpawnerConfiguration.init(SpawnerConfiguration.java:79)
	at mcjty.rftools.proxy.CommonProxy.readMainConfig(CommonProxy.java:167)
	at mcjty.rftools.proxy.CommonProxy.preInit(CommonProxy.java:106)
	at mcjty.rftools.proxy.ClientProxy.preInit(ClientProxy.java:46)
	at mcjty.rftools.RFTools.preInit(RFTools.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2983172224 bytes (2844 MB) / 4043833344 bytes (3856 MB) up to 4043833344 bytes (3856 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCH	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCH	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255.jar) 
	UCH	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156.jar) 
	UCH	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCH	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (AppliedenErgistics2-rv4-alpha-11.jar) 
	UCH	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCH	JEI{3.14.7.419} [Just Enough Items] (JEI_1.10.2-3.14.7.419.jar) 
	UCH	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCH	thedragonlib{1.10.2-1.3.1} [TheDragonLib] (TheDragonLib-1.10.2-1.0.3.1.jar) 
	UCH	armorplus{1.10.2-8.6.1.2} [ArmorPlus] (ArmorPlus-1.10.2-8.6.1.2.jar) 
	UCH	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCH	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar) 
	UCH	AromaBackup{2.0.0.0.b62} [AromaBackup] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCH	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	Baubles{1.3.10} [Baubles] (Baubles-1.10.2-1.3.10.jar) 
	UCH	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCH	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255.jar) 
	UCH	brandonscore{9.9.9} [Brandon's Core] (BrandonsCore-1.10.2-2.1.7.102.jar) 
	UCH	cm2{1.0} [Compact Machines 2] (CM2-2.0.0-b104.jar) 
	UCH	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102.jar) 
	UCH	cyclicmagic{1.10.24} [Cyclic] (Cyclic-1.10.2-1.10.24.jar) 
	UCH	draconicevolution{2.0.12} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.12.222.jar) 
	UCH	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCH	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCH	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106.jar) 
	UCH	enderutilities{0.7.2} [Ender Utilities] (EnderUtilities-1.10.2-0.7.2.jar) 
	UCH	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (ValkyrieLib-1.10.2-0.10.6.jar) 
	UCH	environmentaltech{1.10.2-0.10.6b} [Environmental Tech] (EnvironmentalTech-1.10.2-0.10.6b.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (ExtraUtils2-1.10.2-1.4.1.jar) 
	UCH	zerocore{1.10.2-0.1.0.6} [Zero CORE] (ZeroCore-1.10.2-0.1.0.6.jar) 
	UCH	bigreactors{1.10.2-0.4.5.29} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.29.jar) 
	UCH	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCH	hammercore{1.6.9} [Hammer Core] (HammerCore_1.10.2-1.6.9.jar) 
	UCH	theoneprobe{1.4.7} [The One Probe] (TheOneProbe-1.1x-1.4.7.jar) 
	UCH	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
	UCH	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCH	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCH	MapWriter{2.6.19} [MapWriter] (MapWriter-1.10.2-2.6.19.jar) 
	UCH	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0.jar) 
	UCH	Mekanism{9.2.2} [Mekanism] (Mekanism-1.10.2-9.2.2.301.jar) 
	UCH	MekanismGenerators{9.2.2} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.2.301.jar) 
	UCH	moreoverlays{1.11} [MoreOverlays] (MoreOverlays-1.11-mc1.10.2.jar) 
	UCH	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCH	mysticalagriculture{1.5.3} [Mystical Agriculture] (MysticalAgriculture[1.10.2]-1.5.3.jar) 
	UCH	notenoughwands{1.4.0} [Not Enough Wands] (NotEnoughWands-1.10-1.4.0.jar) 
	UCH	nuclearcraft{2.2d} [NuclearCraft] (NuclearCraft-2.2d--1.10.2.jar) 
	UCH	ProjectE{1.10.2-PE1.3.0} [ProjectE] (ProjectE-1.10.2-PE1.3.0.jar) 
	UCH	p455w0rdslib{1.0.13} [p455w0rd's Library] (P455w0rdslib-1.10.2-1.0.13.jar) 
	UCE	rftools{6.01} [RFTools] (RFTools-1.1x-6.01.jar) 
	UCE	rftoolsdim{4.55} [RFTools Dimensions] (RFToolsDim-1.1x-4.55.jar) 
	UCH	solarfluxreborn{2.17r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.17r.jar) 
	UCH	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81.jar) 
	UCH	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90.jar) 
	UCH	tp{1.0.32} [Tiny Progressions] (TinyProgressions-1.10.2-1.0.32.jar) 
	UCH	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55.jar) 
	UCH	wct{0.1.31} [Wireless Crafting Terminal 2] (WirelessCraftingTerminal-1.10.2-0.1.31.jar) 
	UCH	Woot{1.10.2-1.4.0} [Woot] (Woot-1.10.2-1.4.0.jar) 
	Loaded coremods (and transformers): 
Brandon's Core (BrandonsCore-1.10.2-2.1.7.102.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
HammerCoreCore (HammerCore_1.10.2-1.6.9.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
AppEngCore (AppliedenErgistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4600'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from BrandonsCore-1.10.2-2.1.7.102.jar).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/BadMeetsEvil/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports:

**Comment by McJty** [comment]
What version of McJtyLib and CompatLayer do you have?

**Comment by 47delasPECII** [comment]
the latest version
CompatLayer-1.11.2-0.2.9.jar
MCJtyLib-1.1x-2.3.11.jar
RFTools-1.1x-6.01.jar
RFToolsDim-1.1x-4.55.jar
TheOneProbe-1.1x-1.4.7.jar
NotEnoughWands-1.10-1.4.0.jar

**Comment by McJty** [comment]
You are on 1.10 but you are using the 1.11 version of compatlayer
