### ISSUE TITLE
Machines still work in unpowered dimension

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#121]
Not sure if this is a bug, feature, or can't be changed / fixed. 

I have a resident ender ocean world requiring 90K/T to run, i went in, set up an ender pump, ender tank, tessaract and a chunk loader and left. 

I removed the realized dimension tab out of the builder, and let it drain. It's currently at 0 power. The drums in the Overworld are still filling up. I know it's not what is left  over as they are bedrockium drums and have put in over 8K buckets since it ran out of power.

**Comment by McJty** [comment]
I would love to turn off chunkloaders and similar in unpowered dimensions but I don't know how to do that currently.

**Comment by McJty** [comment]
Probably fixed in upcoming release (but still disabled by default)
