### ISSUE TITLE
builder won't build with a shape card

### ISSUE THREAD

**Issue by lAimBotl** [McJty/RFTools#1211]
It has power, items are in the chest next to it (shield template blocks)

![2017-05-29_17 02 03](https://cloud.githubusercontent.com/assets/10777735/26562033/f51affe6-4490-11e7-9342-b7b6546d539c.png)

no real activity, for some reason its stuck on the second chunk (yet hasn't done anything yet)

![2017-05-29_17 02 09](https://cloud.githubusercontent.com/assets/10777735/26562034/f8d7275e-4490-11e7-9598-494877477dfe.png)

You can see both corners in this one, nothing

![2017-05-29_17 02 42](https://cloud.githubusercontent.com/assets/10777735/26562075/41358996-4491-11e7-9e9f-18add4fb5e7c.png)

tried a ender io conduit, didn't work either

![2017-05-29_17 03 42](https://cloud.githubusercontent.com/assets/10777735/26562036/fba56f9a-4490-11e7-880c-9969c7c52aab.png)

![2017-05-29_17 04 02](https://cloud.githubusercontent.com/assets/10777735/26562040/008e6386-4491-11e7-809e-f4598815dccf.png)

**Comment by McJty** [comment]
Chest must go on top or below the builder
