### ISSUE TITLE
Screen mode switch not working

### ISSUE THREAD

**Issue by bkoenitzer** [McJty/RFTools#1212]
I am on ftb beyond, minecraft 1.10.2 with moving world and da'vinci's vessels added. When I right click a screen with a wrench it simply rotates in a similar fashion to other machines rather than becoming transparent or getting larger. I have tested with a variety of wrenches including the crescent hammer as recommended by one of the wikis. Thank you for any help.

**Comment by McJty** [comment]
Did you try the RFTools Smart Wrench?

**Comment by bkoenitzer** [comment]
Bless you, bless your mods, you are a god among men and we don't deserve you. I didn't know that wrench existed, it did exactly as it was supposed to. I'm sorry for taking some of your time and thank you for helping to automate my base.
