### ISSUE TITLE
RFtools crash server on load

### ISSUE THREAD

**Issue by cyris69** [McJty/RFTools#1216]
Hey there guys, been dying for any form of quarry on 1.10.2 and saw that there is something similar that can be done using this mod. So I installed this, I also have both DeepResonance and TheOneProbe installed which work perfect and both seem to require their own version of mcjtylib. RFtools wants 1.1x-2.3.11 and the others require 1.10-2.2.0 not sure why but that's how it goes. So I'm running forge-1.10.2-12.18.3.2281-universal as I figured maybe moving from 2185 to a more recent version would help but hasn't. I also run sponge if that matters. This is also a private few friends server.

So no matter how I try it it crashes out but does create a rftools config folder and config file.
I'd love to be able to use this mod any and all help would be appreciated.

I'm getting this for the crash report:
https://gist.github.com/cyris69/ef44a81c85f429966924c4f03c6e0543

Here is FML-Latest log:
https://gist.github.com/cyris69/bf3af614cdfb84e7314f55b03e6f7317

Mod list:
https://gist.github.com/cyris69/a78852649e0c91cdc51264607edc510d

API/Lib list:
https://gist.github.com/cyris69/6585a9c107b454ca6a8f7cfb488c4665

**Comment by McJty** [comment]
Update all the mods that require mcjtylib to the latest and only use mcjtylib 1.1x version.

Do not combine both versions of mcjtylib. That doesn't work and is not needed

**Comment by cyris69** [comment]
Do I use the 1.11.2 jar or the 1.10.2 jar since it states they both work on each version.

**Comment by McJty** [comment]
What?

You use the 1.1x version of every mod. That's the version that works on 1.10 and 1.11 at the same time.

**Comment by cyris69** [comment]
Ah ok just on curse it states MC version 1.11.2 for 1.1x so wanted to make sure. Thanks doing so now

**Comment by cyris69** [comment]
Worked like a charm thank you so much for the help, time, and making these mods!
