### ISSUE TITLE
Can't syringe withers. 

### ISSUE THREAD

**Issue by llloyd4** [McJty/RFTools#1223]
So, the dimlet workbench shows that a "WitherBoss" dimlet is possible, gives a recipe and everything, but when I go to syringe a wither to get the needed syringe of wither blood it ain't happening. I try from different angles, different distances, etc and nada, not getting any progress. This is on Direwolf20's 1.10.2 pack, pack version 1.10.0 .

**Comment by McJty** [comment]
Are you using left-click?
