### ISSUE TITLE
Cant config draconium blocks

### ISSUE THREAD

**Issue by Breadabix** [McJty/RFTools#1224]
Back again with another issue related to custom dimlets, I cant seem to config a draconium block dimlet. I have made it, and it works except the custom config options I have tried. Any help would be appreciated.

Custom config:
![2017-05-30_12 36 04](https://user-images.githubusercontent.com/19786108/26860427-ca19c39e-4b35-11e7-8ef8-8c35072d3339.png)

<img width="457" alt="2017-06-07_03 52 51" src="https://user-images.githubusercontent.com/19786108/26860426-ca18cf3e-4b35-11e7-92d2-ad6b80c0e4fb.png">
<img width="612" alt="2017-06-07_03 53 00" src="https://user-images.githubusercontent.com/19786108/26860428-ca22d4fc-4b35-11e7-8a82-2d26128327d8.png">

**Comment by McJty** [comment]
The best way to get info on how to configure this is using /rftcfg dimletcfg while holding the dimlet in your hand. Then you get in-game info on how to configure a dimlet

**Comment by Breadabix** [comment]
Thankyou for telling me this, I didnt realise this was part of the command, and I must have looked at it about 50 times. I dont know why but draconium blocks have " in the config, whereas most dont.
![image](https://user-images.githubusercontent.com/19786108/26880804-8e89a2e2-4b8d-11e7-9c1c-a446d7f2baa5.png)
