### ISSUE TITLE
Can't use or access any RFTools items/blocks.

### ISSUE THREAD

**Issue by Sade66** [McJty/RFTools#1227]
Hello,
I was hoping to use some blocks from RFTools when I came across the following problem; JEI/NEI will show the blocks without any ID and I cannot grab them from there (in creative). When going to the creative tab for RFTools, there is **nothing** (image below).

![image](https://user-images.githubusercontent.com/19366945/27065435-1d011636-4fcb-11e7-8074-82e92ff972a7.png)

I am running _**RFTools version 6.01 on Minecraft 1.10.2**_, on a Forge/Sponge server.

Any and all help is appreciated!

**Comment by McJty** [comment]
Hmm that's strange. What about other mods? Also is there perhaps a configuration on the server that blocks rftools? Same versions on both server+client? Same configs?

**Comment by Sade66** [comment]
@McJty We haven't notice any issues with any other mods. It looks like it was a mess up on our part; we somehow forgot to include the RFTools jar in the server's mods folder. Everything is working great now.

Thank you for your quick replay! 😄
