### ISSUE TITLE
Getting Debuffs in Dimensions

### ISSUE THREAD

**Issue by itsCumcast** [McJty/RFTools#1232]
Hey, I keep getting debuffs in my dimensions even though the dimension tabs are always have a completely stable 40mil RF. How do I solve this?
[picture of the tab](https://user-images.githubusercontent.com/24724892/27236884-bf54c948-5294-11e7-89fc-91e25c543e8c.png)

**Comment by itsCumcast** [comment]
I fixed my issue by remaking the dimlet with a different dimension number. But, the old dimension, number 3, seems to have the issue. No matter what dimension I make it, dimension 3 will always give me debuffs.

**Comment by McJty** [comment]
Sneak right click with the dimension tab in your hand. That gives more info. It is likely you got random bad effects
