### ISSUE TITLE
[1.11.2] Continual Server Console Spam mining flower_pot with builder which causes builder to stop

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/RFTools#1240]
When the builder encounters a flower pot the following line is spammed on console for a couple screen lengths before eventually stopping:

[21:41:00] [Server thread/ERROR]  [mcjty.lib.varia.Logging]: Builder tried to quarry minecraft:flower_pot and it returned null item!

Ive also just noticed that due to this issue the builder has stopped progress in its quarrying, presumably due to this error.

The odd thing is that despite the error, you still get the flowerpot anyway.

Forge *.2315
Rftools 1.1x-6.01
mcjtylib 1.1x-2.3.11

**Comment by lrwerewolf** [comment]
I hit this issue myself and found a temporary work around.  If you have COFH installed also, you can go to the the relative center of your quarry and run the following:

/cofh clearblock 512 256 512 minecraft:flower_pot

The three numbers are distances X Y and Z.  If your quarry is smaller than max-size, adjust them down as needed (note: you REALLY want to adjust them down if you can, that command will hang the game for quite some time as it searches an enormous number of blocks).

This command will remove all flower pots in the selected area, enabling the builder to continue working.

**Comment by McJty** [comment]
Fixed next release
