### ISSUE TITLE
[1.12] Latest forge 14.21.0.2372+ crash

### ISSUE THREAD

**Issue by donqixot** [McJty/RFTools#1241]
Hi, thank you very much for your mods!
You may already know or it may go away with next forge update, but with latest versions of forge 14.21.0.2372 and 14.21.0.2373, I am getting a crash.
[crash-2017-06-26_09.40.59-client.txt](https://github.com/McJty/RFTools/files/1102322/crash-2017-06-26_09.40.59-client.txt)

**Comment by McJty** [comment]
Fixed next release
