### ISSUE TITLE
[Request] Dimension Counter

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#125]
After finding out the limitation of dimensions in Minecraft itself, Would it be possible to put in a X/127 Dimensions used into the dimensional enscriber, and if you get to that limit stop the creation of more?

It will annoy some players - but it would stop world deaths (as in worlds dieing because of the issue). 

you could put in a page/paragraph into the manual about it so they are aware of it, something along the lines of:-
"Minecraft only allows a total of 127 dimensions because your world becomes unstable. This count also includes dimensions like the nether and the end. Other mods also can add dimensions as well".

**Comment by McJty** [comment]
I was considering that but then this limitation is supposed to be gone in more recent versions of Forge (but I haven't tested that) so perhaps this can soon be a thing of the past.
