### ISSUE TITLE
[1.12] RFTools is completely broken, might have something to do with new forge update?

### ISSUE THREAD

**Issue by Flugy2** [McJty/RFTools#1250]
I am using the newest forge version (14.21.1.2387) in MC 1.12, and to my surprise, RFTools was deemed incompatible!
So I reinstalled the mod and got the same results.

> The mods listed below can't run in Minecraft version 1.12
RFTools, (rftools) requires Minecraft between 1.10 and 1.12
Try to find an update or remove 
RFTools

It came with an error log, which I've attached to the post
[fml-client-latest.txt](https://github.com/McJty/RFTools/files/1114924/fml-client-latest.txt)

**Comment by McJty** [comment]
You are using the 1.11 version of RFTools on Minecraft 1.12. Please download the 1.12 version of rftools
