### ISSUE TITLE
1.12 Builder/Quarry not working

### ISSUE THREAD

**Issue by DingoX3** [McJty/RFTools#1252]
We placed a builder, set the quarry card, gave it power, placed a lever on it. Turn on lever then nothing. Inside it says Y stop as if its done. Also noticed you can't craft over tier 1 modular storage cards and the card wont craft into the wireless tablet either. Thanks in advance for looking into this.

minecraft version: 1.12
modpack: ATM3
RFtools version: 1.12-6.10beta1
Forge version: 2387

**Comment by McJty** [comment]
Is there a chest on top or below the builder?

**Comment by DingoX3** [comment]
Yes, we tried a modular storage with a tier 1 card in it and a diamond chest on it. Didnt try a vanilla chest yet. I'll try now and let you know.

**Comment by DingoX3** [comment]
Heres a Gif video of whats happening. Hope this help more.

http://imgur.com/LSenODY

**Comment by DingoX3** [comment]
Were you able to figure out what was happening here McJty?

**Comment by McJty** [comment]
Sorry not yet. I am not at my computer for a while

**Comment by Dijkstra1** [comment]
Having a similar issue with the shaped card it will not place anything full powered with a Redstone single and a chest full blocks to place but nothing happens and it says Y stop.

**Comment by poboy975** [comment]
Also having the same issue, tried with a clearing fortune quarry card, but the builder doesn't respond to any redstone signal. rftools storage under the builder.

**Comment by McJty** [comment]
I think there is a general redstone problem with rftools. I will fix this today

**Comment by DingoX3** [comment]
Sounds good McJty. Thanks for all your hard work. 👍

**Comment by McJty** [comment]
Fixed next release of McJtyLib (yes the bug is there). Will release this today. First doing some other fixes as well
