### ISSUE TITLE
Crash when loading 

### ISSUE THREAD

**Issue by Mazkiller09** [McJty/RFTools#1253]
[crash-2017-07-01_02.57.39-client.txt](https://github.com/McJty/RFTools/files/1116728/crash-2017-07-01_02.57.39-client.txt)

**Comment by McJty** [comment]
That's a crash in tinkers construct. Not sure why you put it on my github?

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Construct (tconstruct)
