### ISSUE TITLE
Crash when enabling a force field

### ISSUE THREAD

**Issue by Darkere** [McJty/RFTools#1257]
So I tried using force fields they behaved very weird. They were loosing power despite being disabled. The redstone controls did not work. And then I crashed after I added the first condition (solid,all).

[Crash Report](https://pastebin.com/KEGZBPS7)

Version rftools-1.12-6.10beta1

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
Fixed next release
