### ISSUE TITLE
1.12 Modules have no crafting recipe

### ISSUE THREAD

**Issue by Darkere** [McJty/RFTools#1260]
The modules that you insert into the environmental controller, or Booster do not have a crafting recipe.

version 6.10 beta1

**Comment by DingoX3** [comment]
The peace essence, storage module tier 2 and 3, and the item filter also do not have recipes at this time. Also the tier 1 storage module that is craftable will not combine with the storage module tablet when placed in a crafting table.
<a href="http://imgur.com/O1bkehB"><img src="http://i.imgur.com/O1bkehB.png" title="source: imgur.com" /></a>

mc version: 1.12
rftools version: 1.12-6.10beta1
modpack: All The Mods 3
forge version: 2387

**Comment by McJty** [comment]
Already fixed and ready for next release

**Comment by Darkere** [comment]
Modules for the environmental controller still have no crafting recipe.

**Comment by McJty** [comment]
They do in the current version (6.10beta4)
