### ISSUE TITLE
1.12 Powercell crash

### ISSUE THREAD

**Issue by gr8pefish** [McJty/RFTools#1261]
Was placed next to a TechReborn Fluid Generator.

Here's a [crashlog](https://gist.github.com/shadowfacts/4b0cff0bed1a042e496a0514249f97b9).

@shadowfacts was there for it as well.

It may be a TR issue, so I'll xpost there as well.

**Comment by McJty** [comment]
It is a bug in TR. It is sending energy client side which is not a good idea

**Comment by gr8pefish** [comment]
Yup, just realized this and was about to close the issue, thanks.
