### ISSUE TITLE
1.12 blocks do not respond to redstone signals

### ISSUE THREAD

**Issue by bytefray** [McJty/RFTools#1262]
Redstone signals do not appear to be receiving on at least the following blocks:

- Logic Gate (does not output any redstone signals in response to input)
- Redstone Transmitter (does not relay to receiver)
- Simple Dialer (does not dial)
- Wire (does not relay redstone signal to output)
- Timer (does not stop pulsing when redstone signal or pulse is applied)

None of these blocks respond how they do in 1.10.2/1.11.2 when a redstone signal is applied to them. Signal was applied with Redstone Torch->Redstone Dust->Block.

RFTools version 1.12-6.10beta1
McJtyLib version 1.12-2.4.2-SNAPSHOT
Forge version 1.12-14.21.1.2387

Please let me know if you require further information.

**Comment by poboy975** [comment]
I would add the builder to this list, I've got the latest rftools, but the builder does nothing when applying redstone via lever.

**Comment by McJty** [comment]
Fixed next release of McJtyLib (yes the bug is there). Will release this today. First doing some other fixes as well
