### ISSUE TITLE
Timed Out with Pixelmon and RFTools

### ISSUE THREAD

**Issue by Jiio** [McJty/RFTools#127]
Every time I warp to a dimension my server timed out for ages(never saw the end of the timed out... I reboot it after five minutes.). I isolate the error at pixelmon because if i uninstall it the dimension work fine, but once I put it back on the problem come back. I can't give a crash log because the sever doesn't crash... We are just unable to connect back...

**Comment by McJty** [comment]
Hmm, hard to say what's wrong. Can you test if this is also the case with mystcraft?

**Comment by Jiio** [comment]
Already tested and it's the same =/

**Comment by McJty** [comment]
I would report this to the pixelmon guys then because it appears to be a problem on their end.
