### ISSUE TITLE
[1.11.2] Teleporter errors in console, they forget all destinations

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFTools#1270]
Forge: 2345

Mods: mcjtylib-1.1x-2.4.3.jar
rftools-1.1x-6.10.jar
rftoolsctrl-1.1x-1.6.8.jar

Console messages: https://gist.github.com/kwpugh/e6d05a0141f7c2944aed3b84d26dcf93

**Comment by McJty** [comment]
Seems to be one of the destinations was in an invalid/removed dimension or something?

**Comment by kwpugh** [comment]
Is there a way to "reset" the destinations?

**Comment by McJty** [comment]
Sneak right click on new destinations. Was it an advanced or normal porter?

**Comment by kwpugh** [comment]
Not a porter.  Dialing device.   All of the different dialing devices have lost their destinations.

**Comment by McJty** [comment]
oh. The destinations are stored in yourworld/data/TPDestinations.dat
Was that corrupted or something?

**Comment by McJty** [comment]
Can you describe to me exactly what happened BEFORE this occured? I assume everything was ok at some point. Then what happened? Update of pack? Anything else?

**Comment by kwpugh** [comment]
I visited Saturn in the ExtraPlanets mod.  The server crashed while loading the dimension.   When everything came back, I tried a dialer and no destinations.

**Comment by McJty** [comment]
It may have crashed at a very bad time corrupting stuff. Maybe restoring from a backup would be the best solution

**Comment by kwpugh** [comment]
I updated the modpack and server yesterday.

[1.11.2] Pughland Plethora updated to v1.2.8
kwpugh a posted Thu at 15:24
UPDATES:

armorplus-1.11.2-10.7.0.1.jar
ExtraPlanets-0.2.0-Beta-Build.jar
journeymap-1.11.2-5.4.7.jar
mcjtylib-1.1x-2.4.3.jar
StorageDrawers-1.11.2-4.2.10.jar

**Comment by kwpugh** [comment]
Ok, thanks for the advice.   I will do that.

**Comment by kwpugh** [comment]
Hi again.

So I restored from a backup and all the destinations are back.   One hitch, one dimension was corrupt and needed to be manually removed from the file system.  It regenerated just fine at restart but the dialer doesn't want to forget it.  It is listed in the dialer and if used gives "invalid destination" message.   

Is the list of dialer destination stored somewhere that can be edited to remove the entry?

**Comment by kwpugh** [comment]
Awesome, that did it.  Thank you very much for answering my questions.
