### ISSUE TITLE
1.10: Potential incompatibility with Geographicraft // Climate Control

### ISSUE THREAD

**Issue by Dilnu** [McJty/RFTools#1274]
When modifying the biome distribution with Climate control this mix is applied to rftools dimensions despite Geographicraft being set to only operate in whitelisted dimensions.

Is this working as things are currently intended and if so would it be possible to add a config to disable this behavior?

Sorry if this is a bug in Geographicraft but I thought it was worth asking here.

Minecraft 1.10.2
Forge 12.18.3.2297
Geographicraft 0.87
McJtyLib 2.3.11
Compat Layer 0.2.9
RfTools 6.10
Dimensions 5.02

**Comment by McJty** [comment]
I don't understand what you mean. What is the problem exactly? Neither climate control nor geographicraft are my mods so not sure what I can do here?

**Comment by Dilnu** [comment]
What I'm wondering is if Rftools pretends to be the overworld somehow and might therefore be confusing Geographicraft.

**Comment by McJty** [comment]
No it doesn't. RFTools dimensions (not rftools btw, you are on the wrong issue tracker) properly defines its own dimensions

**Comment by Dilnu** [comment]
Alright thanks anyway.
