### ISSUE TITLE
Storage scanner shows 2 items for every one.

### ISSUE THREAD

**Issue by Valgraath** [McJty/RFTools#1275]
In the storage scanner block, the items are doubled from what i actually have in my chests. IE. showing 24 rubber instead of 12 rubber. This is on version 5.92.
Edit: I now realize that it is showing the same chests multiple times, is there any way to prevent this?

**Comment by McJty** [comment]
What kind of things is the scanner showing? Do you perhaps have a storage controller or something similar that also manages items? Show me the gui of the scanner and the list of blocks it is controlling

**Comment by Valgraath** [comment]
It has some sort of pattern, like 4 inventories that are the real ones, then it duplicates them. I'll get you a picture as soon as I can, currently using it and have the inventories that are bugged removed.

**Comment by Valgraath** [comment]
![javaw_2017-07-10_20-10-56](https://user-images.githubusercontent.com/7969192/28046835-147c9aa2-65ac-11e7-9356-0ccdb9ef8603.png)
![javaw_2017-07-10_20-11-13](https://user-images.githubusercontent.com/7969192/28046840-1f12caa4-65ac-11e7-9812-9affebe6b72c.png)
![javaw_2017-07-10_20-11-32](https://user-images.githubusercontent.com/7969192/28046844-237a1cd2-65ac-11e7-9d87-c476b75e8065.png)
![javaw_2017-07-10_20-11-44](https://user-images.githubusercontent.com/7969192/28046847-24f3ddfa-65ac-11e7-92f4-436b0ba81105.png)
![javaw_2017-07-10_20-11-54](https://user-images.githubusercontent.com/7969192/28046851-2cc50342-65ac-11e7-88b5-4827267ea46f.png)

**Comment by Valgraath** [comment]
The unrouteable ones are the ones that have the exact same items as other chests, even though none of my chests have the same two items

**Comment by Valgraath** [comment]
https://www.youtube.com/watch?v=5RF3KeGpPB8&feature=youtu.be
This is the best i could do with showing off this bug.

**Comment by josephcsible** [comment]
Are the chests being affected double chests? If so, this sounds like #1583.
