### ISSUE TITLE
Owner dimlets

### ISSUE THREAD

**Issue by kaal-1** [McJty/RFTools#1276]
I've enabled owner dimlets in the config, but can't find the command in the wiki to give one to players. Not in JEI or creative tab either. Any ideas?

**Comment by McJty** [comment]
Versions?

**Comment by kaal-1** [comment]
Sorry, totally forgot that...
Minecraft 1.10.2 (forge 2281) running on sponge server.
RFTools 1.1.x-6.10
RFTools Dimensions 1.1.x-5.0.2

**Comment by McJty** [comment]
You can cheat them in using the dimlet workbench. In creative, place it down and then shift-double click on the owner dimlet in the list on the right

**Comment by kaal-1** [comment]
Thank you!
I just found out you can give players the dimlet using the following command:
/give @p rftoolsdim:known_dimlet 1 11 {dkey: "Owner"}
