### ISSUE TITLE
Coal Generater will not accept Coal Blocks when insertion is automated

### ISSUE THREAD

**Issue by NosajDraw** [McJty/RFTools#1283]
Get:

1 Coal Generator
1 Hopper
1 Coal Block
1 Coal

Place generator down, place hopper so as to insert into Generator, place coal block into hopper.

Notice coal block remains in hopper.

Place coal in hopper.

Notice coal enters generator.

Same problems exists when using XNET which is why I first noticed it.

**Comment by McJty** [comment]
Fixed next release
