### ISSUE TITLE
Storage Filter Module in Builder Block used as Quarry can ignore ores.

### ISSUE THREAD

**Issue by togreglove** [McJty/RFTools#1285]
Ok, I set up a builder block as a quarry. I allowed all types on the shape card, no filtering. Turned it on and it started giving me cobble, as expected.  I get a Storage Filter Module and set it up to blacklist Cobblestone and Stone. Insert it into builder and turn it on, and from that point on, *nothing* is quarried at all.  For a bit, I thought it might just be a dry patch in the world, but after 2 chunks, I knew there was a problem.  I took out the Storage Filter Module and checked the cobblestone and stone boxes on the Shape Card Quarry and turned it back on and the chest immediately filled up with lots of ores and other quarried items.  

I'm sure I got the settings on the Filter Module correct, and even if I didn't, it should have either mined just cobblestone, or just other stuff, but ... nothing.

**Comment by McJty** [comment]
First: versions please

Second: Show me the gui of the builder and the filter card

**Comment by togreglove** [comment]
Minecraft: 1.12
Pack: FTB Unstable 1.0.2
RFTools: 1.12-6.10beta4
Forge: 2407

GUIS: http://imgur.com/a/D4NSz

**Comment by McJty** [comment]
Try toggling the blacklist icon in the item filter

**Comment by togreglove** [comment]
Ugh, now I can't get it to mine anything at all, it just rapidly goes through the levels, even without the filter. Not sure how I got it to work earlier.

**Comment by togreglove** [comment]
Sorry I'm not more informative. I've done at least 5 times before on other servers and never had an issue.

**Comment by togreglove** [comment]
The power keeps going up, which to me indicates it's not trying to mine.

**Comment by togreglove** [comment]
Ok, it started again. That was my bad, the quarry restarted from the start and of course had nothing to mine. The original issue remains though. Sorry for the confusing commentary after.

**Comment by togreglove** [comment]
Toggling the blacklist did nothing to help

**Comment by togreglove** [comment]
Not sure what I did, but it seems to be working with the filter now. Sorry for the issue, I honestly thought I had found a bug.
