### ISSUE TITLE
Crash on dimlit pick up

### ISSUE THREAD

**Issue by jpwanabe** [McJty/RFTools#1286]
I crashed right after picking up a dimlit and am now unable to join the server with out crashing.
Crash reports are attached.

This one is the initial crash.
[crash-2017-07-16_01.53.46-client.txt](https://github.com/McJty/RFTools/files/1150859/crash-2017-07-16_01.53.46-client.txt)

This is the follow up join crash.
[crash-2017-07-16_01.57.51-client.txt](https://github.com/McJty/RFTools/files/1150860/crash-2017-07-16_01.57.51-client.txt)

**Comment by McJty** [comment]
I will check this out soon

**Comment by McJty** [comment]
Fixed in upcoming release
