### ISSUE TITLE
[1.12] Energy Module shows the maximum energy, not the actual amount of energy

### ISSUE THREAD

**Issue by ExDomino** [McJty/RFTools#1290]
When I connect a Screen to an Energy Cell (for example) with an Energy Module, the amount of energy that the screen indicates is the maximum energy that the Energy Cell can handle, not its current amount of energy. For exemple, the RF is always 2000000, the % is always 100% and the gain is always +0/t.

RFTools version: 6.10beta4.
Edit : The Energy Module indicates 0 RF and 0% if there is no energy in the Energy Cell.
If there is any energy in the Energy Cell, it indicates the maximum capacity and 100%.

**Comment by McJty** [comment]
Ok I see the problem. It is a bug in McJtyLib. I will fix this today

**Comment by McJty** [comment]
Fixed in new McJtyLib which is now waiting approval on curse

**Comment by ExDomino** [comment]
The approval of curse if sometime very very very ... long. But it's fine, I updated and all is fine.
