### ISSUE TITLE
[1.12] Storage module does not keep stored items on upgrade

### ISSUE THREAD

**Issue by rosareven** [McJty/RFTools#1296]
(Sorry I accidentally hit enter on first submit)

When I upgrade a storage module with items inside, I get an upgraded module with nothing inside. The items were gone.

I was told items used to stay when you upgrade a module, in a previous version.

**Comment by McJty** [comment]
I will check this out. The items should indeed stay

**Comment by McJty** [comment]
Hmm works for me. What version do you have?

**Comment by rosareven** [comment]
This is the version in latest ATM3. Sorry I'm not at my computer right now
to check which version is in ATM3.

**Comment by McJty** [comment]
It is likely they have a buggy version then. Latest version should be ok

**Comment by rosareven** [comment]
Thanks, I'll report to ATM3 if I still have problem.
