### ISSUE TITLE
Client Crash on Teleport: Could not get provider type for dimension 282, does not exist

### ISSUE THREAD

**Issue by iampyrex** [McJty/RFTools#130]
I had recently updated to Infinity 1.3.4 Server.  I had to delete the RFTools files in the data directory in order to boot.  I logged in, exported my dimlets, imported, put the update tab in for world generation.  Teleported fine, started to run out of power so I went back home and removed the tab so I could build up some power reserves.  Logged of the server, came back online and inserted tab and upon teleportation my client shutdown.  Crash log attached.

http://pastebin.com/FWyc5MVQ

**Comment by McJty** [comment]
You can only go to dimension 128 because the Minecraft logon packet doesn't support more (it only has a single byte for dimensions). This is not something rftools can solve although I have heard that more recent versions of Forge fix this limitation. I have not tested this however!

So in short: nothing RFTools can do about this I'm afraid. Mystcraft has the same problem.

**Comment by iampyrex** [comment]
I haven't had this issue with Myst craft, I have a server that has over 2000 mystcraft dimensions with no issue.

**Comment by McJty** [comment]
Check this: https://github.com/MinecraftForge/MinecraftForge/issues/1621
It is the ticket in Forge talking about this issue. I have no idea how you did it in the past but note that you can actually make dimensions in that range. However, you cannot login to them. So as long as you always go back to the overworld before quitting the game it will probably work.

**Comment by iampyrex** [comment]
Ok, the crash I opened this ticket about was not from logging into the dimension.  I logged into the overworld and then stepped on the teleporter.

**Comment by iampyrex** [comment]
Looks like forge may have addressed this issue.  Thanks for your time and I will update when I find out more.

**Comment by McJty** [comment]
I'll investigate if I can find any place in rftools where I use a byte for dimension id too but I doubt it. I wouldn't trust this to work without proper support from Forge in any case. But I'll repoen this for now.

**Comment by iampyrex** [comment]
FYI, tried a build that contained the forge commit you referenced.  Still getting the crash.

http://pastebin.com/3aBFa2CS

**Comment by McJty** [comment]
Closing this because this is out of my control.
