### ISSUE TITLE
MC 1.12 RF Monitor gives no signal

### ISSUE THREAD

**Issue by Knito58** [McJty/RFTools#1300]
MC 1.12
Forge 14.21.1.2420
RFTools 1.12-6.12
RFTools Control 1.12-1.6.8
Gamemode SSP

I don't seem to get the monitor to work. It is placed beside a RF coal gen. The coal gen is set to Redstone Mode "on to activate". Which works fine if I put a lever beside it and switch it on and off. If the lever is on then the coal gen burns the coal which is inside (didn't forget that).

The RF Monitor is set to "less" and the slider to "100%" which I understand as:
"As long as the coal gen has less than 100% energy, give out a redstone signal."

I placed a redstone lamp beside the monitor to see when it fires a signal but it tends to never ever fire any signal. Whatever I give as setting - the monitor stays completely unimpressed. The graphical indicator on the front side shows the energy level of the so surveilled coal generator. But it does not work, maybe I forgot something like "feed it an egg".

When I try this in a creative test world then there happens everything the same way: nothing.

Where can I put the egg in?

**Comment by McJty** [comment]
See the orange arrow on one of the sides? That's where the signal comes out

**Comment by Knito58** [comment]
Yes! I put that egg in and it worked. To my defense: I read the help notice but there was no indication about that little arrow on the back side and that the signal would only be output to the back. I never saw it, as I tend to place the machines so that they are at a wall and facing me. 

Works now. Thanks.
