### ISSUE TITLE
[1.7.10] How to Add/edit a Dimlet?

### ISSUE THREAD

**Issue by chaos234** [McJty/RFTools#1303]
Like stated here: https://github.com/McJty/RFTools/wiki/Adding-a-Dimlet you can build your own dimlets but this seems only to applay to MC Version 1.10.2.

Is there a way to add custome Dims or editing the hole entire dimlet database directly or is this only possible through MineTweaker?

**Comment by josephcsible** [comment]
Minecraft 1.7.10 is no longer supported.
