### ISSUE TITLE
Clearing canal from Redstone Receiver

### ISSUE THREAD

**Issue by ExDomino** [McJty/RFTools#1311]
My idea is simple: allowing to clearing the canal of a Redstone Receiver. It's too simple to make a mistake and then have two Redstone Receiver on the same frequency. Also, I already wanted to take an old Redstone Receiver and then re-use it on the same frequency than an other. Or, just give it to another player on my server. At this moment I'm worried to use creative each time a player made a mistake because the Redstone Receiver is expensive. Why not just let us choice the channel manually?

**Comment by McJty** [comment]
Chosing the channel manually is a bad idea as that allows for abuse when you set the channel to a channel used by another player.

Anyway. Clearing the redstone receiver channel is not needed as you can just right click the receiver on a transmitter to copy the channel.

**Comment by ExDomino** [comment]
But you can by error copy the channel of another transmitter and be stuck with two transmitter on the same channel. And then, you cannot set this transmitter to another channel.

**Comment by McJty** [comment]
For a redstone transmitter you can clear the channel in the crafting grid

**Comment by ExDomino** [comment]
It cannot be done in 1.12, I tryed.

**Comment by McJty** [comment]
It is not needed for receiver as you can always link that to another channel. It is only needed for the transmitter. There is never a need to replace a receiver in creative. Just relink it by right clicking it on the correct transmitter
