### ISSUE TITLE
crash when player connecting last cable from solar flux to basic power cell

### ISSUE THREAD

**Issue by SDUBZ** [McJty/RFTools#1312]
Forge:1.12-2424
Rftools:1.12-6.12
Solar flux reborn:1.12-3.25r

crash report:
[crash-2017-07-27_21.09.55-client.txt](https://github.com/McJty/RFTools/files/1179712/crash-2017-07-27_21.09.55-client.txt)

**Comment by McJty** [comment]
Bug in solar flux. It is doing energy client side
