### ISSUE TITLE
mod depends on very laggy source. 

### ISSUE THREAD

**Issue by tjdagamer** [McJty/RFTools#1316]
the mod requires a mod that lags my game from 30 to 1-2 fps. and my memory used jumps from 20-40 to 70-90. is it possible to make the mods self reliant to fix lag?

**Comment by McJty** [comment]
On what laggy mod does it depend? I don't understand what you mean

**Comment by tjdagamer** [comment]
ok i just looked at some files and console logs and its not this mod. sorry for bothering you.
