### ISSUE TITLE
[1.10.2] The elevator and many floors...

### ISSUE THREAD

**Issue by TizianPlaying** [McJty/RFTools#1317]
Hey,
i have a little problem with the elevator.
Is it possible to fix it?

![elevator01](https://user-images.githubusercontent.com/29901011/28796366-91041482-763d-11e7-9246-31749afbad22.png)

**Comment by McJty** [comment]
What are you doing to get that?

**Comment by TizianPlaying** [comment]
i have simulate a large building with 35 floors.
For this i have set in every floor a elevator, screen and elevator button module. i set also 3 screen controller, to get the wireless redstone network. 

The buttons on the screen are working, but not the button 08 - 26.

**Comment by McJty** [comment]
I am afraid so many floors are not supported.  There is no room for that many buttons

**Comment by TizianPlaying** [comment]
Is it possible to make more small button?
If i dont check "large button" in the elevator button module, i have 9 small buttons in a row, from the left to the right side. After this 9 buttons i need a wordwrap for the next 9 small buttons. 

I mean like floating boxes in CSS :)

**Comment by McJty** [comment]
Working on this

**Comment by McJty** [comment]
Implemented for next release
