### ISSUE TITLE
No Dimension Manual

### ISSUE THREAD

**Issue by Iell** [McJty/RFTools#1318]
I am using the RF tools mod for Minecraft 1.12 Version 6.12.
I can't craft the dimension Manual with the recipe on the wiki page. I also tried using commands but that didn't work either. I might have used the wrong command but the recipe should have worked.
Could this be because I am using another mod that is incompatible with RF Tools? I am currently using Actually Additions, Biomes o'Plenty, Tinkers construct and a mod called Future Pack. The recipe for the other manual worked.

**Comment by Darkere** [comment]
Rftools and Rftools Dimensions are 2 different mods. You have to have both installed. Also to find out recipes always use JEI. On many wikis Information is outdated but JEI always pulls the recipe from your game. This is especially needed if you use any modpack as the author of the modpack might change recipes.

**Comment by Iell** [comment]
Thanks. I didn't know that.
