### ISSUE TITLE
Shape Card Issue

### ISSUE THREAD

**Issue by JVanhook** [McJty/RFTools#1321]
MInecraft 1.10.2
Forge 12.18.3.2422
Rftools 1.1x-6.12

Im using the builder block with a void shape card set to use the solid box setting, i seem to be having trouble with the y offset its using. I'm having to manually change it in the right click gui as it only voids 1-2 y levels at a time. It also seemed to reset the y offset to 0 when i attempted to use the preview option of the builder block with the void card installed

**Comment by McJty** [comment]
This is rather vague... Can you describe more exactly what you did?
