### ISSUE TITLE
[1.12.1] elevator possibly not letting joining a server

### ISSUE THREAD

**Issue by Yoghurt4C** [McJty/RFTools#1325]
put a premade map on a server, upon starting the server throws this
![image](https://user-images.githubusercontent.com/11313954/29064733-9a47c5ca-7c32-11e7-80aa-f6603c72c48a.png)
even though both the client and the server have the same jar/configs. if this is ignored, upon joining the client prints out **[Netty Client IO #2/FATAL] [FML]: Failed to connect to server: there are 4 missing blocks and items**. starting a fresh world doesn't help.
removing rftools from both the client and the server lets the client join the server without any problems. *there are absolutely no meaningful logs neither on the client nor the server*.

version: 6.12
forge: 2446

**Comment by McJty** [comment]
I need the logs anyway
