### ISSUE TITLE
[Crash Report] Game crashes every time you try to open the Modular Storage block.

### ISSUE THREAD

**Issue by Biggerbobs** [McJty/RFTools#1326]

**Comment by McJty** [comment]
Version and crashlog please

**Comment by Biggerbobs** [comment]
Oops, sorry! Mod version is 1.12-6.12

Crash report: 

8:19:15 | game |   | info | at mcjty.rftools.crafting.ContainerToItemRecipeFactory$ContainerToItemRecipe.func_77572_b(ContainerToItemRecipeFactory.java:62)
-- | -- | -- | -- | --
08:19:15 | game |   | info | at mcjty.rftools.craftinggrid.GuiCraftingGrid.testRecipe(GuiCraftingGrid.java:219)
08:19:15 | game |   | info | at mcjty.rftools.craftinggrid.GuiCraftingGrid.draw(GuiCraftingGrid.java:150)
08:19:15 | game |   | info | at mcjty.rftools.blocks.storage.GuiModularStorage.drawWindow(GuiModularStorage.java:616)
08:19:15 | game |   | info | at mcjty.rftools.blocks.storage.GuiModularStorage.func_146976_a(GuiModularStorage.java:597)
08:19:15 | game |   | info | at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
08:19:15 | game |   | info | at mcjty.lib.container.GenericGuiContainer.func_73863_a(GenericGuiContainer.java:229)
08:19:15 | game |   | info | at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
08:19:15 | game |   | info |  
08:19:15 | game |   | info | -- Screen render details --
08:19:15 | game |   | info | Details:
08:19:15 | game |   | info | Screen name: mcjty.rftools.blocks.storage.GuiModularStorage
08:19:15 | game |   | info | Mouse location: Scaled: (213, 119). Absolute: (427, 240)
08:19:15 | game |   | info | Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
08:19:15 | game |   | info |  
08:19:15 | game |   | info | -- Affected level --
08:19:15 | game |   | info | Details:
08:19:15 | game |   | info | Level name: MpServer
08:19:15 | game |   | info | All players: 1 total; [EntityPlayerSP['QueenGlo'/190, l='MpServer', x=68.31, y=73.00, z=25.72]]
08:19:15 | game |   | info | Chunk stats: MultiplayerChunkCache: 1089, 1089
08:19:15 | game |   | info | Level seed: 0
08:19:15 | game |   | info | Level generator: ID 04 - customized, ver 0. Features enabled: false
08:19:15 | game |   | info | Level generator options:
08:19:15 | game |   | info | Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
08:19:15 | game |   | info | Level time: 546306 game time, 385385 day time
08:19:15 | game |   | info | Level dimension: 0
08:19:15 | game |   | info | Level storage version: 0x00000 - Unknown?
08:19:15 | game |   | info | Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
08:19:15 | game |   | info | Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
08:19:15 | game |   | info | Forced entities: 69 total; [EntityChicken['Chicken'/128, l='MpServer', x=89.47, y=63.00, z=101.51], EntityBat['Bat'/8961, l='MpServer', x=94.78, y=43.63, z=63.02], EntityBat['Bat'/8962, l='MpServer', x=96.81, y=41.79, z=66.84], EntityChicken['Chicken'/131, l='MpServer', x=108.84, y=63.00, z=92.55], EntityChicken['Chicken'/132, l='MpServer', x=106.10, y=63.00, z=89.46], EntityBat['Bat'/11013, l='MpServer', x=121.25, y=38.63, z=-14.56], EntityBat['Bat'/137, l='MpServer', x=126.72, y=12.60, z=-26.28], EntityBat['Bat'/138, l='MpServer', x=127.14, y=30.66, z=43.86], EntityBat['Bat'/141, l='MpServer', x=121.56, y=33.87, z=79.43], EntityBat['Bat'/142, l='MpServer', x=142.21, y=33.22, z=68.54], EntityChicken['Chicken'/144, l='MpServer', x=136.24, y=64.00, z=24.85], EntityPlayerSP['QueenGlo'/190, l='MpServer', x=68.31, y=73.00, z=25.72], EntityBat['Bat'/158, l='MpServer', x=148.87, y=45.04, z=58.27], EntityBat['Bat'/7733, l='MpServer', x=91.68, y=37.98, z=71.21], EntityBat['Bat'/7735, l='MpServer', x=123.59, y=16.95, z=-21.52], EntityPig['Pig'/60, l='MpServer', x=2.39, y=62.20, z=-7.16], EntityPig['Pig'/62, l='MpServer', x=-9.90, y=62.45, z=2.86], EntityChicken['Chicken'/65, l='MpServer', x=-2.12, y=64.00, z=16.24], EntityBat['Bat'/13377, l='MpServer', x=6.39, y=26.30, z=28.82], EntityChicken['Chicken'/69, l='MpServer', x=19.18, y=64.00, z=6.33], EntityPig['Pig'/70, l='MpServer', x=14.36, y=64.00, z=5.76], EntityPig['Pig'/71, l='MpServer', x=14.50, y=63.00, z=13.51], EntityPig['Pig'/72, l='MpServer', x=15.49, y=64.00, z=-1.51], EntityPig['Pig'/73, l='MpServer', x=8.40, y=64.00, z=9.52], EntityChicken['Chicken'/74, l='MpServer', x=0.25, y=61.64, z=19.39], EntityPig['Pig'/75, l='MpServer', x=2.55, y=64.00, z=27.55], EntityPig['Pig'/78, l='MpServer', x=16.21, y=64.00, z=-5.46], EntityPig['Pig'/79, l='MpServer', x=22.49, y=63.00, z=31.33], EntityChicken['Chicken'/80, l='MpServer', x=26.93, y=63.00, z=33.31], EntityItem['item.item.egg'/81, l='MpServer', x=26.52, y=63.00, z=33.82], EntityPig['Pig'/83, l='MpServer', x=16.52, y=72.00, z=58.91], EntityPig['Pig'/84, l='MpServer', x=28.72, y=63.00, z=90.46], EntityChicken['Chicken'/85, l='MpServer', x=23.87, y=64.00, z=85.50], EntityChicken['Chicken'/87, l='MpServer', x=29.68, y=63.00, z=-31.64], EntityPig['Pig'/88, l='MpServer', x=46.30, y=64.00, z=-32.21], EntityPig['Pig'/89, l='MpServer', x=47.47, y=64.00, z=-18.70], EntityChicken['Chicken'/90, l='MpServer', x=40.17, y=64.00, z=-25.51], EntityItem['item.item.egg'/91, l='MpServer', x=36.10, y=64.00, z=-30.73], EntityChicken['Chicken'/92, l='MpServer', x=45.19, y=64.00, z=2.70], EntityItem['item.item.egg'/93, l='MpServer', x=44.49, y=64.00, z=2.59], EntityChicken['Chicken'/94, l='MpServer', x=49.23, y=64.00, z=-23.49], EntityItem['item.item.egg'/95, l='MpServer', x=49.22, y=64.00, z=-24.08], EntityBat['Bat'/96, l='MpServer', x=65.29, y=35.05, z=-7.88], EntityPig['Pig'/97, l='MpServer', x=47.78, y=64.00, z=-0.55], EntityPig['Pig'/98, l='MpServer', x=62.75, y=64.00, z=-5.86], EntityWorm['Worm'/99, l='MpServer', x=62.50, y=66.50, z=17.50], EntityWorm['Worm'/100, l='MpServer', x=59.50, y=66.50, z=17.50], EntityWorm['Worm'/101, l='MpServer', x=56.50, y=66.50, z=17.50], EntityWorm['Worm'/102, l='MpServer', x=54.50, y=66.50, z=17.50], EntityWorm['Worm'/103, l='MpServer', x=51.50, y=66.50, z=17.50], EntityWorm['Worm'/104, l='MpServer', x=48.50, y=66.50, z=17.50], EntityChicken['Chicken'/105, l='MpServer', x=49.51, y=63.00, z=73.52], EntityChicken['Chicken'/106, l='MpServer', x=52.52, y=65.00, z=73.87], EntityItem['item.item.egg'/107, l='MpServer', x=52.27, y=65.00, z=73.13], EntityItem['item.item.egg'/3564, l='MpServer', x=85.17, y=63.00, z=74.88], EntityChicken['Chicken'/110, l='MpServer', x=70.61, y=64.00, z=-21.54], EntityChicken['Chicken'/111, l='MpServer', x=87.20, y=67.00, z=-6.41], EntityWorm['Worm'/112, l='MpServer', x=77.50, y=66.50, z=17.50], EntityWorm['Worm'/113, l='MpServer', x=74.50, y=66.50, z=17.50], EntityWorm['Worm'/114, l='MpServer', x=71.50, y=66.50, z=17.50], EntityWorm['Worm'/115, l='MpServer', x=68.50, y=66.50, z=17.50], EntityWorm['Worm'/116, l='MpServer', x=65.50, y=66.50, z=17.50], EntityChicken['Chicken'/117, l='MpServer', x=83.13, y=64.00, z=89.55], EntityBat['Bat'/122, l='MpServer', x=91.89, y=22.10, z=-9.41], EntityWorm['Worm'/123, l='MpServer', x=80.50, y=66.50, z=17.50], EntityWorm['Worm'/124, l='MpServer', x=83.50, y=66.50, z=17.50], EntityWorm['Worm'/125, l='MpServer', x=86.50, y=66.50, z=17.50], EntityItem['item.item.egg'/3709, l='MpServer', x=23.77, y=64.00, z=86.07], EntityChicken['Chicken'/126, l='MpServer', x=84.88, y=63.00, z=74.53]]
08:19:15 | game |   | info | Retry entities: 0 total; []
08:19:15 | game |   | info | Server brand: fml,forge
08:19:15 | game |   | info | Server type: Integrated singleplayer server
08:19:15 | game |   | info | Stacktrace:
08:19:15 | game |   | info | at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
08:19:15 | game |   | info | at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
08:19:15 | game |   | info | at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
08:19:15 | game |   | info | at net.minecraft.client.main.Main.main(SourceFile:123)
08:19:15 | game |   | info | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:19:15 | game |   | info | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:19:15 | game |   | info | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:19:15 | game |   | info | at java.lang.reflect.Method.invoke(Method.java:483)
08:19:15 | game |   | info | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
08:19:15 | game |   | info | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
08:19:15 | game |   | info |  
08:19:15 | game |   | info | -- System Details --
08:19:15 | game |   | info | Details:
08:19:15 | game |   | info | Minecraft Version: 1.12
08:19:15 | game |   | info | Operating System: Windows 10 (amd64) version 10.0
08:19:15 | game |   | info | Java Version: 1.8.0_25, Oracle Corporation
08:19:15 | game |   | info | Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
08:19:15 | game |   | info | Memory: 445526592 bytes (424 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
08:19:15 | game |   | info | JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
08:19:15 | game |   | info | IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
08:19:15 | game |   | info | FML: MCP 9.40 Powered by Forge 14.21.1.2387 15 mods loaded, 15 mods active
08:19:15 | game |   | info | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
08:19:15 | game |   | info | UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar)
08:19:15 | game |   | info | UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
08:19:15 | game |   | info | UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar)
08:19:15 | game |   | info | UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar)
08:19:15 | game |   | info | UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar)
08:19:15 | game |   | info | UCHIJAAAA	actuallyadditions{1.12-r117} [Actually Additions] (ActuallyAdditions-1.12-r117.jar)
08:19:15 | game |   | info | UCHIJAAAA	cookingforblockheads{6.3.2} [Cooking for Blockheads] (CookingForBlockheads_1.12-6.3.2 (1).jar)
08:19:15 | game |   | info | UCHIJAAAA	inventorypets{1.4.9.8} [Inventory Pets] (inventorypets-1.12-1.4.9.8.jar)
08:19:15 | game |   | info | UCHIJAAAA	jei{4.7.4.81} [Just Enough Items] (jei_1.12-4.7.4.81.jar)
08:19:15 | game |   | info | UCHIJAAAA	harvestcraft{1.12c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12c.jar)
08:19:15 | game |   | info | UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar)
08:19:15 | game |   | info | UCHIJAAAA	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar)
08:19:15 | game |   | info | UCHIJAAAA	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar)
08:19:15 | game |   | info | UCHIJAAAA	roots{0.025} [Roots 2] (roots-2-0.025.jar)
08:19:15 | game |   | info | UCHIJAAAA	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar)
08:19:15 | game |   | info | Loaded coremods (and transformers):
08:19:15 | game |   | info | GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
08:19:15 | game |   | info | Launched Version: 1.12-forge1.12-14.21.1.2387
08:19:15 | game |   | info | LWJGL: 2.9.4
08:19:15 | game |   | info | OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
08:19:15 | game |   | info | GL Caps: Using GL 1.3 multitexturing.
08:19:15 | game |   | info | Using GL 1.3 texture combiners.
08:19:15 | game |   | info | Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
08:19:15 | game |   | info | Shaders are available because OpenGL 2.1 is supported.
08:19:15 | game |   | info | VBOs are available because OpenGL 1.5 is supported.
08:19:15 | game |   | info |  
08:19:15 | game |   | info | Using VBOs: Yes
08:19:15 | game |   | info | Is Modded: Definitely; Client brand changed to 'fml,forge'
08:19:15 | game |   | info | Type: Client (map_client.txt)
08:19:15 | game |   | info | Resource Packs:
08:19:15 | game |   | info | Current Language: English (US)
08:19:15 | game |   | info | Profiler Position: N/A (disabled)
08:19:15 | game |   | info | CPU: 4x Intel(R) Pentium(R) CPU N3540 @ 2.16GHz
08:19:16 | game |   | info | [12:19:16] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:552]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\angel_000\AppData\Roaming\.minecraft\crash-reports\crash-2017-08-09_12.19.15-client.txt
08:19:16 | game |   | info | [12:19:16] [main/INFO] [FML]: Waiting for the server to terminate/save.
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [FML]: Applying holder lookups
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [FML]: Holder lookups applied
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [Actually Additions]: Unloaded WorldData!
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
08:19:18 | game |   | info | [12:19:18] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
08:19:18 | game |   | info | [12:19:18] [main/INFO] [FML]: Server terminated.
08:19:18 | game |   | info | AL lib: (EE) alc_cleanup: 1 device not closed
08:19:19 | game |   | info | Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by McJty** [comment]
Please next time don't paste a crash like this. It is hard to read this way

**Comment by McJty** [comment]
Fixed next release
