### ISSUE TITLE
Builder Fill shape card

### ISSUE THREAD

**Issue by Goten87** [McJty/RFTools#1329]
is there a shape card that will fill the area u select
so the quary card mines out what u select i want a card that can do the same but fill if i profide it with blocks 
and then fill all also lava/water

**Comment by BrianEdmonds** [comment]
That sounds like the basic shape card.

**Comment by Adventure2098** [comment]
That kind of question is better asked for google and not on the ISSUES github

**Comment by McJty** [comment]
The builder can't yet fill liquids but with the normal shape card you can fill an area with provided materials
