### ISSUE TITLE
[1.10.12]

### ISSUE THREAD

**Issue by selonianth** [McJty/RFTools#1331]
Encountered an issue on a SSP game where I was unable to add myself to the allowed users list on my transmitters  when I, for some reason, labeled them as private.

**Comment by selonianth** [comment]
Modpack: Skyfactory 3
MC Forge: 12.18.3.2316

**Comment by McJty** [comment]
What? I don't understand what you mean. Can you describe the steps?

**Comment by selonianth** [comment]
I created a matter transmitter, for some reason set it to private, and received "no access to transmitter" on my dialing device. So I tried to add myself to the permitted user list, and was unable to. I could however swap it back to a public transmitter, and was then able to dial from it.

**Comment by McJty** [comment]
What do you mean 'was unable too'? What happens if you try?

**Comment by selonianth** [comment]
Nothing, it's greyed out and won't permit any attempts at all.

**Comment by McJty** [comment]
Can you show me some screenshots?

**Comment by McJty** [comment]
Ping?

**Comment by selonianth** [comment]
Sorry bout that, was away from my computer for a couple days there. Getting the screenshots now.

**Comment by selonianth** [comment]
And... I must've been being an idiot and trying to add names while it was in public mode, and couldn't, and confused myself. It's working now, I was an idiot.
