### ISSUE TITLE
Rftools dimension stuck on Downloading terrain

### ISSUE THREAD

**Issue by PundaPoo** [McJty/RFTools#1332]
I created a world with diamond blocks, orogen, ender sky, and grid. When I tried to enter it, it was stuck on downloading terrain, so I tried restarting. Now, when I try to enter my world that I worked so hard on, It gets stuck on downloading terrain for a bit, then crashes. plz help.

**Comment by McJty** [comment]
Versions and crashlog please

**Comment by PundaPoo** [comment]
The problem fixed itself after a while :/. It's all good now.
