### ISSUE TITLE
Void Dim isnt craftable

### ISSUE THREAD

**Issue by cookies934** [McJty/RFTools#1333]
Im on 1.12-5.04 and the void dim isnt craftable

**Comment by McJty** [comment]
Hmm, do you have modified configs? What other mods do you have? Perhaps show me a log

**Comment by McJty** [comment]
The reason I ask is that it works fine for me

**Comment by cookies934** [comment]
Im on the unstoppable 1.12 modpack v 1.0.0. Ive been testing the modpack with the dev, as far as im aware he didnt mod the configs

**Comment by cookies934** [comment]
I also just downloaded a fresh copy of unstable 1.12 and theres no craftable void dimlet

**Comment by McJty** [comment]
Very weird. No idea why it wouldn't work for you. Do other rftools dimensions machines show up?

**Comment by cookies934** [comment]
yes, i see other craftable dims too

**Comment by cookies934** [comment]
found something else out. The dimlet shows up if i go in creative, if i search thru JEI its not there, is this a JEI issue?

**Comment by cookies934** [comment]
just figured out the issue, JEI only shows Terrain Dimlet Flat, if you click on it 2 recipes show, one for flat and one for void
