### ISSUE TITLE
Crafter crash server when you use the option "ExtC" without remaining itels

### ISSUE THREAD

**Issue by SteveNoobGeek** [McJty/RFTools#1345]
I've a minecraft modded serveur and when I use the Crafter from RfTools with a infusion crystal(the remain item) and inferium essence(from Mystical Agriculture). When the Infusion Crystal run out of durability the server crash.

**Comment by McJty** [comment]
Logs and versions please

**Comment by SteveNoobGeek** [comment]
Version : 1.12-6.13
Log : [crash-2017-08-26_22.23.15-server.txt](https://github.com/McJty/RFTools/files/1254398/crash-2017-08-26_22.23.15-server.txt)

**Comment by McJty** [comment]
It's a bug in Quark:

	at vazkii.quark.management.feature.AutomaticToolRestock.onToolBreak(AutomaticToolRestock.java:69)
