### ISSUE TITLE
RFtools crashing upon mods loading

### ISSUE THREAD

**Issue by Zameracus** [McJty/RFTools#1350]
I have been attempting to use a number of modpacks from the curse launcher however whenever i launch one it starts loading up the mods and whenever it gets to initialising RFtools in phase 2 it promptly crashes, as shown by the following screenshot
![image](https://user-images.githubusercontent.com/21277559/30003793-4caa09ca-90bb-11e7-888b-802ba4f93f0f.png)
This never happens after i manually remove RFtools, this normally wouldn't be much of an issue as i can live without a couple tech mods, however since the game adds items if i remove it i am unable to connect to servers, which is my preferred play style, if anyone can propose a solution i would greatly appreciate it as Curse is being VERY unresponsive, simply shrugging me off and telling me to submit bug reports

**Comment by McJty** [comment]
Do you have an nvidia card? What driver version?

**Comment by Zameracus** [comment]
I do have an Nvidia card and am on driver version 382.05

**Comment by McJty** [comment]
Anyway if java is crashing there is little that I can do about it. Maybe try upgrading your java?

**Comment by Zameracus** [comment]
I have upgraded my java to the latest version of 64 bit, i'll try updating my drivers but other than that i have no clue what's going on

**Comment by Zameracus** [comment]
Well updating the drivers appears to have worked, thanks for your help, not many mod creators have an active help section
