### ISSUE TITLE
[1.10.2] Crash when scrolling through build types in cards

### ISSUE THREAD

**Issue by AveoCross** [McJty/RFTools#1352]
Game crashes when clicking through shapes in Shape Cards for Builder Block.
RFTools - 6.13
McJtyLib - 2.4.3
CompatLayer - 0.2.9
Latest Forge

Crash Log - https://pastebin.com/ViDJunuv
No other logs or crashes.

**Comment by McJty** [comment]
That's a java crash. There is literally nothing I can do about that. Try updating your video drivers and/or java

**Comment by AveoCross** [comment]
Okay. Gonna try that later. Thanks for your reply c:
