### ISSUE TITLE
RF Tools spawner only accepts Pumpkins as living matter

### ISSUE THREAD

**Issue by DietmarKrause** [McJty/RFTools#1358]
question about ATM3 rf-tools spawner.  I play the modpack All the mods 3. I messed around with the rf tools spawner yesterday and found that the living matter has to be pumpkins. Is this for purpose? regarding to wiki a few other things should work (potatose among others) but the dont seem to work.
i connected 3 matter beamers, everything has RF and the beamers got redstone signal as required. I tried to spawn wither skeletons which requires bones, nether rack and a living material (potatoes, wheat and pumpkins) and only pumpkins work for me.

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-3/issues/110

**Comment by DietmarKrause** [comment]
edit: fish seems to work, too. Nothing else i tried so far.

**Comment by DeFazer** [comment]
Try something else too - leaves, raw meat, flowers. The config file provided by the modpack doesn't change what counts as living matter or things required to summon a wither (just checked), so that's not it. Did you provide the necessary amount of it (30 items)?

**Comment by DietmarKrause** [comment]
i put in a stack always. i have tried so far wheat (doesnt work), fish (works), raw meat (doesnt work), egg (doesnt work), pumpkins (work), i will try more. The two other requirements are will "over the top" far more the needed. Could that be the problem?

**Comment by DietmarKrause** [comment]
after updating the modpack i use (all the mods 3) to latest 3.2b it seems to work now, wheta, raw meat etc. now works. can be closed
