### ISSUE TITLE
[1.10.2] Crash on startup

### ISSUE THREAD

**Issue by NuclearMegalodon** [McJty/RFTools#1359]
RF Tools caused crash on startup
MC 1.10.2
[Crash Report](https://gist.github.com/NuclearMegalodon/dc9732f333c5b2e68fb86f956770bb72)

**Comment by McJty** [comment]
You have duplicate mcjtylib in your mods dir. Only keep the latest version:

		* McJtyLib (1.10-2.2.0) from mcjtylib-1.10-2.2.0.jar
		* mcjtylib_ng (2.4.3) from mcjtylib-1.1x-2.4.3.jar
