### ISSUE TITLE
Crash connecting to server

### ISSUE THREAD

**Issue by katur239** [McJty/RFTools#136]
Updated to v2.73 and when I try to log into the server it times out, then i get this error. (The timing out part may be unrelated, but not sure.)

http://pastebin.com/UqDwyb5H

I did find out what was causing the timing out, but the error still should be looked at. Thanks :)

**Comment by McJty** [comment]
Thanks for reporting. I'll check it out.

**Comment by MrBurd** [comment]
What exactly caused the timeout? I'm having the exact same issue, can't connect to a server.

**Comment by katur239** [comment]
Time out were caused by mismatched config on server and client.

If an item is disabled in one and not the other, it'll time out.

**Comment by MrBurd** [comment]
Thanks for the quick reply! Let's see if this works.

**Comment by McJty** [comment]
Can this be closed?

**Comment by katur239** [comment]
Yup. Not a problem for me anymore. :D Thanks
