### ISSUE TITLE
[Suggestion] Change Builder Block Preview Mode

### ISSUE THREAD

**Issue by JamesCastillo** [McJty/RFTools#1360]
I would like to request that the builder block's preview when inserting the shape card to be changed into the same thing as the yellow box. The ghost blocks are pretty useless when we customize the dimension through numbers because if we try to dig and track the blocks, they do not appear or show that what we dug is a part of the builder block's area of mining/draining

**Comment by McJty** [comment]
I don't understand what you mean? What is the problem with these blocks exactly?
