### ISSUE TITLE
says is compatible for 1.7.10 but not on download page

### ISSUE THREAD

**Issue by animalman3** [McJty/RFTools#1362]

**Comment by animalman3** [comment]
this is what it says

**Comment by animalman3** [comment]
RFTools is a mod containing various tools that are related to RF (Redflux) or technology in general. The blocks and items that are in the current version are usable and feature complete. This mod is for 1.7.10, 1.8.9, 1.9 and 1.10.2. The major feature in this mod (since 2.00) is the Dimension Builder. With this device you can make your own dimensions for exploration, mining, building and so on.

**Comment by animalman3** [comment]
but 1.7.10 not option

**Comment by McJty** [comment]
You can download it from the file section on curseforge itself
