### ISSUE TITLE
[Suggestion] Sensor blocks detecting redstone signals

### ISSUE THREAD

**Issue by DeFazer** [McJty/RFTools#1363]
The title sums it up, really. Just like the sensor can detect blocks of certain type, it could be detecting blocks having redstone signal of at least <numeric parameter 0-15>. This should help fill the gap of redstone things working with partial redstone (blah, my wording is terrible. ><).

**Comment by josephcsible** [comment]
Why not just run <numeric parameter 0-15> blocks of redstone wire into a redstone repeater?
