### ISSUE TITLE
Unable to Create Draconium Ore Features

### ISSUE THREAD

**Issue by j-ki** [McJty/RFTools#1371]
I'm playing on All the Mods 1.11.2 and because it didn't come with Draconic Evolution, I added version 2.3.3-260. I'm using RFTools Dimensions 1.1x-5.04.

I tried creating a draconium ore dimension by adding draconium ore and tendrils. After 10-15 tries in a test world, I had zero success. If I swap out the material for something vanilla like diamond blocks or dimensional shards, everything works as expected.

I tried switching to orbs and the new dimension was a water world. There were orbs underwater but there was nothing but air.

https://imgur.com/a/PhwGX

I suspect that RFTools Dimension tried to create draconium ore orbs but failed for some reason. So it left these orbs (that would've been composed with the proper materials) of empty space.

**Comment by McJty** [comment]
Did you configure the dimlet for draconium ore? It is not enabled by default:

https://wiki.mcjty.eu/mods/index.php/RFTools_Dimensions

**Comment by j-ki** [comment]
Draconium dimlets aren't the problem. I can create draconium dimlets. I've also found them in worlds.

I'm having problems creating a dimension with the draconium ore.

When I swap out the draconium ore for something else (e.g. diamond ore), the world generates the features as expected.

**Comment by j-ki** [comment]
If you see the screenshot above, that's a world I created with draconium ore with orbs.

It seems that RFTools Dimensions tried to create draconium ore orbs but failed. So it left the block empty instead.

**Comment by Rimmer6617** [comment]
I have the exact same problem. Any update?@

**Comment by McJty** [comment]
I have no clue what is going on but this may be a problem in Draconic Evolution that I cannot solve on my end. It is possible their worldgen requires special things which is something I cannot provide. Maybe check with them?

**Comment by josephcsible** [comment]
Does your pack contain NotEnoughIDs?
