### ISSUE TITLE
[7.00a1] Shapes and window resolution

### ISSUE THREAD

**Issue by Thiana** [McJty/RFTools#1374]
The shape preview scaling changes depending on window size. Two image links below show the same shape preview at two different resolutions.

https://imgur.com/a/hhGfZ
https://imgur.com/a/fThrz

PS: How do you move the shape preview? LClick allows rotation. MWheel zooms but I can't shift/recenter the shape with the expected RClick. Thanks.

**Comment by McJty** [comment]
Yes I'm aware of that. Note that this is easy to correct by adjusting the offset in game with the mouse
