### ISSUE TITLE
[1.7.10] Not finding many rarity 6 dimlets

### ISSUE THREAD

**Issue by ic3cr34m** [McJty/RFTools#1376]
I've gone through about 3,000 - 5,000 unknown dimlets now and have only found around 5 rarity 6 dimlets. Is this normal?

**Comment by McJty** [comment]
Yes you even found a lot. Most people are not that lucky

**Comment by ic3cr34m** [comment]
Ah okay, thanks a lot for your help.
Keep up the good work, McJty.
