### ISSUE TITLE
Space chamber doesn't duplicate block rotations

### ISSUE THREAD

**Issue by avosirenfal** [McJty/RFTools#1379]
Copying IC2 (and other) machines works, but the blocks aren't placed facing the direction they are in the source space chamber. I'm not sure if this is NBT block data or what, but it would be very useful if it could properly copy machines.

Tested in Age of Engineering 1.10.2

**Comment by McJty** [comment]
This is in general really complicated to do as I don't know if the metadata of a block is significant to mean a different block (i.e. different colors of clay) or is used for rotation

**Comment by ouroborus** [comment]
Maybe a config option for hinting metadata treatment would work. A dictionary of block ids to metadata treatment (ignore, ignore but copy, must match and copy) would enable this functionality. Also, a way to flag all blocks in a mod, with specific block entries overriding mod-wide entries, seems like it would be a useful feature of this functionality.

In this way, the feature is made possible but the grunt-work is left up to the end user.

**Comment by McJty** [comment]
Can you try this again with 7.00? I fixed stuff
