### ISSUE TITLE
MC 1.12.x RFTools Smart Wrench not working properly in focus mode.

### ISSUE THREAD

**Issue by Gr8umbreon** [McJty/RFTools#1380]
The smart wrench does not bind in focus mode as intended. Shift+Right Click does not select the master block and right clicking does not select the secondary block. This is being done on the required Matter Beamer onto the Spawner.

**Comment by Gr8umbreon** [comment]
![2017-09-27_11 35 35](https://user-images.githubusercontent.com/24768452/30919562-5b23b05a-a367-11e7-9a26-9c5bb6c3944a.png)

**Comment by Gr8umbreon** [comment]
![2017-09-27_11 37 46](https://user-images.githubusercontent.com/24768452/30919651-a6dc0614-a367-11e7-941a-8bb317429b9c.png)

**Comment by McJty** [comment]
You should not do that in that mode. Use the normal wrench mode for that

**Comment by Gr8umbreon** [comment]
Regular wrench mode doesn't do it either. That will just make the machine drop as an item.

**Comment by Gr8umbreon** [comment]
Ok nvm found it. It wasn't clear.

**Comment by Gr8umbreon** [comment]
Thank you for the help.
