### ISSUE TITLE
Server crashed when I teleported to a new dimension for the first time.

### ISSUE THREAD

**Issue by ThereIsNoDog96** [McJty/RFTools#1385]
My first time using RFTools Dimensions on a Sky Factory 3 server. I randomly generated a dimension, got on to the transmitter, teleported to the dimenson, was successfully in there for about 5 seconds and the server closed. I've now tried 3 times to get back into the server, and I can't get past the loading screen before the server closes, I assume, because I'm loading in to this dimension.
Other people can still get in the server, it's only me who cannot.

Crash report:
[crash-2017-10-01_23.58.13-server.txt](https://github.com/McJty/RFTools/files/1347613/crash-2017-10-01_23.58.13-server.txt)

I had a look at the crash report, but I have no idea what it means.
I've also never had a crash like this before, has only happened since entering a dimension.

Any help would be greatly appreciated.

**Comment by McJty** [comment]
Update RFTools Dmiensions. Your version is outdated. That bug was fixed
