### ISSUE TITLE
Storage Scanner eats items from Storage Drawers

### ISSUE THREAD

**Issue by ouroborus** [McJty/RFTools#1387]
If the items pulled from a storage drawer or storage drawer controller are the last of the item, the items are lost. Works normally otherwise.

For example: Put 128 items in a single drawer. Pull out one stack via storage controller, end up with one stack in inventory and one stack in drawer. Pull out single item (shift-click), end up with one stack plus one item in inventory, 63 items in drawer. Pull out remaining items, end up with one stack plus one item in inventory, nothing in drawer. 63 items eaten.

All The Mods 3 v3.01
RFTools v1.12-6.13

Possibly related:
https://github.com/McJty/RFTools/issues/1377

**Comment by McJty** [comment]
Don't use the storage scanner in combination with storage drawer controller. That's not a good combination and is known to cause issues which we haven't been able to resolve yet. Let the storage scanner work on the drawers directly. Not with the controller

**Comment by ouroborus** [comment]
This issue happens in both situations of pulling from the drawer controller or pulling from the drawer itself. I haven't tried it specifically without the drawer controller attached though. I'll check into it once I have access again in about 8 hours.

**Comment by ouroborus** [comment]
After further testing, it appears that it doesn't matter if you're using a drawer controller or not. If you take the last of an item, you lose it. This occurs with:

- Just a drawer, taking from that drawer
- A drawer controller with adjacent drawer, taking from either the controller or the drawer

**Comment by McJty** [comment]
I'll try to reproduce this soon

**Comment by McJty** [comment]
I cannot reproduce this at all with latest version of storage drawers on 1.12.2

**Comment by ouroborus** [comment]
Confirmed working in 1.12.2
