### ISSUE TITLE
Storage Scanner doesn't see Storage Crates on Xnet

### ISSUE THREAD

**Issue by ouroborus** [McJty/RFTools#1388]
When using the storage scanner, storage crates (Actually Additions) are only seen via the area scan. They don't show up on Xnet scan. Xnet controller is able to see them.

All The Mods 3 v3.01
RFTools v1.12-6.13

**Comment by McJty** [comment]
What? Can you clarify what you mean exactly?

**Comment by ouroborus** [comment]
Sorry looks like I had the Xnet Controller misconfigured.
