### ISSUE TITLE
Power fluctuation in matter transmiter

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#139]
Good Day,

I have a problem with my matter transmitter, is doesn't accept power or something like that.
I have recorded the footage for that:
https://www.youtube.com/watch?v=ecHGhFAFf8Q

Mod Versions:
rftools-2.74
EnderIO-1.7.10-2.2.8.367

Best Regards,
DeForce

**Comment by McJty** [comment]
Hmm that is really weird. Do you have this with all transmitters? Did you try breaking it? What if you give it power on its own?

**Comment by DeForce** [comment]
Yep, wierd... 
With all transmitters. Seems like they are siphoning power from each other. I tried breaking it.
For temporary measures they are connected 1 dirt between each other so they don't connect to each other. That works fine... Also I have to pipe energy in, of in/out setting it starts fluctuating power again.

**Comment by McJty** [comment]
So there is only a problem if they are adjacent to each other? I'll experiment with that.

**Comment by McJty** [comment]
Actually does the receiver have enough power? You can also have that effect if the other hand is not powered enough.

**Comment by DeForce** [comment]
Well you can see at the video that I have full vibrant capacitor for that... And I did port from my compact portal to that. So yeah, plenty of power, can record and show it again.

**Comment by McJty** [comment]
Can you try with other power capacitors? Perhaps there is some incompatibility. For example a TE energy cell or something.

**Comment by DeForce** [comment]
Yep, you were correct. Interesing thing:
https://www.youtube.com/watch?v=dz8tNqrSM3k

**Comment by McJty** [comment]
What is that conduit you're using there? Is that something new from EnderIO? I'll have to test it out then.

**Comment by DeForce** [comment]
That is new textures from EnderIO. It's Ender Energy Conduit

**Comment by DeForce** [comment]
Seems like your machines acts as a in/out energy blocks:
https://www.youtube.com/watch?v=ShpgAR4Sh6E

**Comment by McJty** [comment]
Yes that could very well be. But I've never experienced any problems with that though. Strange... I'll see if I can avoid that problem somehow.

**Comment by McJty** [comment]
I'm rewriting energy handling to be more correct. This problem should be gone in the next release.

**Comment by DeForce** [comment]
Thank you!

**Comment by McJty** [comment]
Can you check the latest dev build at https://drone.io/github.com/McJty/RFTools/files
It should fix the problem. If not please let me know.

**Comment by DeForce** [comment]
Yep, at the moment it is all good... 
Will see how I'll break your mod again next time :D
