### ISSUE TITLE
RFToolsdim - Spamming Console 

### ISSUE THREAD

**Issue by Keaton1188** [McJty/RFTools#1391]
![untitled](https://user-images.githubusercontent.com/24898745/31256749-5b543600-aa2c-11e7-82c4-74125e4c3950.png)

This is constantly spamming our console, any way to disable it?

(Ftb Beyond)

**Comment by McJty** [comment]
That's AE2 reporting this. Ask them why it is telling you that and what it means

**Comment by Keaton1188** [comment]
Thanks.
