### ISSUE TITLE
RFTools farmer and mysticalgriculture

### ISSUE THREAD

**Issue by Omegapex** [McJty/RFTools#1392]
Hey, I seem to be having an issue on my server. I recently updated the server to 1.12.2 and now mystical crops seem to be dropping 2 seeds nearly every time they are harvested by the rftools farmer. this was not an issue in 1.12.1 and I can guarantee that the extra seed chance is set to 0 in the config file.

Is this in issue with MA ignoring the config or the rftools farmer?

**Comment by McJty** [comment]
RFTools Farmer? Wrong mod? RFTools does not have a farmer

**Comment by Omegapex** [comment]
SHIT sorry! The situation had me a little stressed and I guess I mixed up mod names -_-'
