### ISSUE TITLE
environmental controller infinite effects bug

### ISSUE THREAD

**Issue by tjdagamer** [McJty/RFTools#1393]
After using the environmental controller I noticed that the effects don't work with my shader pack used in game, so I simply broke the blocks. But it wasn't so simple afterwards as the effects keep coming back as if the block is still there. I reloaded the chunks, restarted my game, and disabled the controllers. It still happens...

also, I have not just made a new world because I've spent over 14 hours on the world.

**Comment by McJty** [comment]
Fixed next release
