### ISSUE TITLE
Screen GUI Does not open

### ISSUE THREAD

**Issue by KINGJOJO7086** [McJty/RFTools#1394]
Running RFTools 6.13 on FTB beyond 1.11.0. I cannot for the life of me get any screen's gui to open. I have tried everything I can think of. I've reinstalled the game, java, and twitch launcher. I have had my playerdata reset. Single player, etc. Still can't get any Screen gui to open.

**Comment by McJty** [comment]
Shift right click. You can see the instructions on a fresh screen
