### ISSUE TITLE
[issue] trying 1.12-7.00 seems to not show the previews

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#1398]
So I was trying the new projector, shape cards and all that, I can see the Gui with numbers and selection boxes, and all that, but it seems like there should be like a 3d preview that I'm just not seeing, ... the image on top of the projector seems to work well. The scanner and the locator might need a video explaining them, jajaja XD, its just me being dumb I need to read the ingame manual a couple more times to get it probably.

**Comment by McJty** [comment]
The 3D preview is working but depending on your screen size and gui size it ends up at the wrong spot. Try using shift-mouse to scroll the preview until you can find it. I just found this out myself and will fix the correct location tomorrow.

I will make a tutorial video tomorrow

**Comment by winsrp** [comment]
oh yeah I found it, using a 4k monitor really put it waaaaay hidden, lol

**Comment by winsrp** [comment]
also now that I'm looking at it, doesn't the 3d render in the scanner looks like flipped on the red axis ?? something that is on the right shows up on the left

**Comment by winsrp** [comment]
and glass shows as black blocks, looks weird, it could be white blocks instead

**Comment by winsrp** [comment]
the projector shows the image without the flip, but the scanner does flip it

**Comment by McJty** [comment]
Hmm it shouldn't flip. I'll check it out tomorrow

**Comment by winsrp** [comment]
also if you scan something in your shape card and then you take it out and try to change it's size to make it bigger for example, the 3d preview really screws up

**Comment by McJty** [comment]
yes that's normal. The scan data must match for the size. You have to make a new scan if you change size

**Comment by winsrp** [comment]
if it were me, I'll reset the preview to a square shape if you change size.. just saying, think about it

**Comment by winsrp** [comment]
or add a blank space at the sides if you make it bigger, and just shrink the preview if you make it smaller

**Comment by McJty** [comment]
It is not that easy :-)  The scan is just a series of bytes. If the dimension is changed I have no easy way to find out what the dimension was before and how to correct the data

**Comment by winsrp** [comment]
hmmm... so you store the thing as large array of bites instead of a matrix... and you have no lenghts for axis... complicated... or you could like... store the size value when you open the shape card and use that as reference.. to be compared to what the user puts as new values...

**Comment by winsrp** [comment]
tried the new 01 version and now I can no longer see any of the previews... even with shift mouse I cannot find the preview on any of the machines or the shape card... placing the card on the project still works, but the preview is also gone in the GUI

**Comment by McJty** [comment]
Um that's weird... It should be there somewhere. I need to find a better way to position it. Did you try other gui scales?

**Comment by winsrp** [comment]
with GUI scale normal it now shows on the other side of where it was before, (before it was on the upper left corner, now it shows on the lower right corner, but I can only see like a small corner of it), on gui small... it is not there, and on gui large, which is what I use because 40" 4k monitor, it is nowhere to be found.

**Comment by McJty** [comment]
I just tried and the preview is always somewhere. But it is *extremely* hard to find in some cases. I'm thinking of a more robust solution

**Comment by winsrp** [comment]
cool, I'll give it a try when you upload an update to the curseforge site!, great work!

**Comment by McJty** [comment]
Ok. I found the perfect formula now. No matter what gui scale and resolution I pick the preview is now perfectly centered. I will release this tomorrow

**Comment by winsrp** [comment]
the preview works just fine now!! YAY, and none of the images are flipped!.. everything seems to work fine, I just need a video to know what to use it for! XD

**Comment by winsrp** [comment]
nope nope... scanner image is still flipped...

**Comment by McJty** [comment]
The flip bug is fixed next release
