### ISSUE TITLE
[1.12.2] Error on server after upgrading to rftools 7.00

### ISSUE THREAD

**Issue by twoworlds** [McJty/RFTools#1399]
I updated rftools on our 1.12.2 server today.

After starting the server, i got this message:

https://pastebin.com/tpxeyXDF

and

[08:59:22] [Server thread/WARN] [FML]: Registry Block: Object did not get ID it asked for. Name: rftools:locator Expected: 2607 Got: 4095
[08:59:22] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

If I confirm this with /fml confirm, i get this crash:

https://pastebin.com/BvRrD9ke

Which is related to Applied Energistics 2, but the only thing I changed was the Version of rftools.

I changed back the version of rftools and uploaded a backup of my world the server starts without a problem.

mc 1.12.2
Forge 14.23.0.2512

**Comment by McJty** [comment]
You have too many blocks/items. There is a maximum of 4096. Remove mods or else add the NotEnoughIds mod
