### ISSUE TITLE
[Issue] Server Crash Whilst Building Dimensions

### ISSUE THREAD

**Issue by CuddleFish123** [McJty/RFTools#1401]
Okay, so one this server that I love to play on in the All The Mods Lite Pack, sometimes whilst at 99% the server will do a hard crash, and we'll be forced to reset at the last auto-save. I don't know if this is certain Dimlets that are doing this or what, but if you could please help.
Only Pic the server has provided:
![image](https://user-images.githubusercontent.com/32754604/31525917-7a0e99d6-af78-11e7-9413-a25e73f8fd8f.png)

Minecraft Version: 1.10

**Comment by McJty** [comment]
What version of RFTools dimensions?

**Comment by CuddleFish123** [comment]
1.1x-5.04, I do believe.

**Comment by McJty** [comment]
Does this happen for all dimensions?

**Comment by CuddleFish123** [comment]
No, it only happens for certain dimensions. I am unable to test which ones though, because the server admins have shut down the use of dimensions. Is there any problem dimlets for this version, or perhaps a certain order that needs to be followed or else it won't work?

**Comment by McJty** [comment]
In your version 'scattered orbs' cause crashes. That's the only thing I know

**Comment by CuddleFish123** [comment]
Would you be able to understand more with a full crash report? I might be able to get that.

**Comment by McJty** [comment]
perhaps yes

**Comment by josephcsible** [comment]
@CuddleFish123 any update on this?
