### ISSUE TITLE
Syringe suggestions

### ISSUE THREAD

**Issue by josephcsible** [McJty/RFTools#1402]
Two suggestions for syringes:
1. Have the creative inventory and/or JEI contain all valid filled syringes in addition to the empty one
2. ~~Have their tooltips show their required resources~~

**Comment by McJty** [comment]
2. What required resources do you mean?

**Comment by josephcsible** [comment]
The key, block, and living material required to actually do the spawning.

**Comment by McJty** [comment]
You can see that in the spawner. Note that the syring is not only for spawning so it wouldn't fit there really

**Comment by josephcsible** [comment]
True. I was only thinking about its use in the spawner and not its other uses. I guess I really only want the JEI suggestion then.
