### ISSUE TITLE
asking about scan 

### ISSUE THREAD

**Issue by ARatfat** [McJty/RFTools#1403]
Hi,

Using : 
- forge :  14.25.0.2512 1.12.2
- RFTool : 1.12.7.10

I notice, whene ou make a scann, rftool create (folder, scan file). I want some info on what kind of fomat is it et can It be modify off game.

Best regards !

**Comment by McJty** [comment]
Those scans are internal format. I wouldn't depend on it really. But basically it is a save of the NBT for the scan data.

It is much better to use the /rftshape save <file> and /rftshape load <file> commands to save and load scan information

**Comment by ARatfat** [comment]
are you think is it possible. export this format to .bo3 ? but well I try make something with it. 

thx you so much !

**Comment by McJty** [comment]
What is .bo3?

**Comment by ARatfat** [comment]
bo3 is format US in Open Terrain generator to create structure. 
But thx you I now try importe scan file from one instance to another
