### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by darkshadow543** [McJty/RFTools#1406]
The game crashes when I change a shape card to a hollow scan.
MC: 1.12.2
Forge:14.23.0.2512
RFTools:7.10

**Comment by McJty** [comment]
Crashlog please

**Comment by mrdeadlocked** [comment]
I had this crash flipping thru the shape card. I dont know what was the next option.

https://pastebin.com/AiLt40vn

**Comment by McJty** [comment]
I can't reproduce this exactly. Do you have some more exact steps on how to do this?

**Comment by mrdeadlocked** [comment]
Pull out shape card. Set to hollow. Quickly flip through the options on the left last one I saw was 'Top Dome' then server crashed.

https://pastebin.com/TjWjJNXt

**Comment by McJty** [comment]
Yes but what kind of shapecard? How was that shapecard made in the first place?

**Comment by mrdeadlocked** [comment]
![image](https://user-images.githubusercontent.com/461352/31581502-a6824e26-b13b-11e7-914d-393e812b18b9.png)

It was crafted like any other shaprecard.

**Comment by McJty** [comment]
And it started like that? This has never been in a scanner or composer?

**Comment by McJty** [comment]
Fixed
