### ISSUE TITLE
[1.12.2] Client-only crash upon scan in Scanner

### ISSUE THREAD

**Issue by DeadSix27** [McJty/RFTools#1407]
Hey mcjty :)

Client crashes with `java.lang.NullPointerException: Rendering screen` exception when hitting "Scan" in the Scanner with a shape card inserted and set to 200x200x200

Crashdump: https://gist.github.com/DeadSix27/e530584ca16089a3d4f2347ade4bedb8

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Btw it is a bed causing the crash

**Comment by DeadSix27** [comment]
@McJty Strange, I have no special modded beds or so, ( I don't think so ), I think Quark used to mod them in 1.10 but since this is 1.12 there should be vanilla beds in all colors and thus no special beds?

**Comment by McJty** [comment]
Fixed next release. It is a 1.12 specific bug

**Comment by DeadSix27** [comment]
@McJty Thank you :)
