### ISSUE TITLE
Builder uses excessive CPU

### ISSUE THREAD

**Issue by ouroborus** [McJty/RFTools#1416]
I have a Builder I've been running in quarry mode (Shape Card (Clearing Quarry)). When it runs (2520RF/t), server CPU jumps from ~13% to ~75%. After turning off the builder, it takes a while (up to ~60s) for CPU to fall to normal levels.

Minecraft 1.12.2
All The Mods 3 4.0
RFTools 1.12-7.00alpha1

**Comment by McJty** [comment]
Well that's hardly surprising is it? It does a lot of work. A Builder is bound to cause a lot of calculations. This will be the same for any other quarry. But the Builder is very fast so it causing a bit more work.

**Comment by ouroborus** [comment]
Sure. However, it didn't seem have this kind of impact in 1.10.

**Comment by ouroborus** [comment]
I switched to a clearing silk quarry and it performs worse (~80%) despite seemingly needing less computing resources to run (not processing drops beyond the original block, not having enough RF to run it at the same speed as before).

**Comment by McJty** [comment]
Note that you are using an alpha and outdated version of rftools

**Comment by ouroborus** [comment]
I'm aware and apologize for that. I'll re-check it once I can get access to the latest version.

**Comment by ouroborus** [comment]
I've checked in version 7.01 (though I'm aware 7.12 was uploaded today) and the behavior is the same.

**Comment by ouroborus** [comment]
I guess something got fixed at some point. I'm unable to reproduce this in 7.12.
