### ISSUE TITLE
[1.12.2] things with the coal generator

### ISSUE THREAD

**Issue by TheSnowyChickens** [McJty/RFTools#1420]
Hello,
I found some issues with the coal generator:

1. The internal energy cell is full, but the generator absorb coal to produce wasted energy. 
(No Item is in the Item slot and no cable/machine is connected)

2.Wrong tooltips (Power gen 80 <-> 60 ?)
![coal gen](https://user-images.githubusercontent.com/29357962/31902333-ccbbea76-b824-11e7-843d-ff8c5100391e.png)

MC 1.12.2
Forge 2515
RF Tools 7.12
RF Tools Dim 5.05

**Comment by McJty** [comment]
yes that's intended. You have to make sure you stop feeding charcoal/coal or make sure to pump the power out
