### ISSUE TITLE
Syringe not correct?

### ISSUE THREAD

**Issue by emmakul** [McJty/RFTools#1422]
I have SF3 3.0.13 on minecraft 1.10.2. 

I have filled a syringe with ender dragon essence and am trying to create a Ender Dragon dimlet. I have all of the necessary parts to create the dimlet, yet it wont let me craft it.

Does the essence i extract have to be from a hostile ender dragon? or can it be from a friendly ender dragon? because thats the only thing i can think of that is messing with me making the dimlet.

thanks

**Comment by McJty** [comment]
A friendly ender dragon? Where do you get those?

**Comment by emmakul** [comment]
In all honesty idk. Person on our sever hatched 3 ender dragons and they are non hostile. He said he golden lassoed the ender dragon egg and brought it back to the overworld. Then plopped it down and somehow made it hatch. My guess is that the ender dragons we have chilling in our base aren’t coded the same as the end ender dragon and thus the workbench not accepting the full syringe of this ender dragon

**Comment by emmakul** [comment]
I can get more info on mods and what not in the morning

**Comment by McJty** [comment]
If this 'friendly dragon' belongs to another mod then that's the reason it doesn't work. It has to be from the real vanilla ender dragon

**Comment by emmakul** [comment]
Yeah its from the mod Dragon Mounts apparently. No biggie i was just seeing if it would work or not. Thanks for the quick reply
