### ISSUE TITLE
[Suggestion]Timer can Stop/Pause

### ISSUE THREAD

**Issue by Flithor** [McJty/RFTools#1426]
At present, Timer can only reset by redstone signal, but can't stop it.
- Redstone Reset(keep running, get a redstone signal to reset, keep redstone signal will ignore)
- Redstone Start(not running, get a redstone signal to start, keep redstone signal to keep running, not redstone will stop and reset)
- Redstone Continue(keep redstone signal to start/continue, not redstone will pause, 1 tick redstone signal to reset)

**Comment by josephcsible** [comment]
Fixed by 59d51f5, which will be in the next release.
