### ISSUE TITLE
Shield Projector Not Letting Players Through v1.11.2

### ISSUE THREAD

**Issue by TheLazyOne001** [McJty/RFTools#1430]
Shield Projector Settings:
Rules
   hostile        -               SolDmg
   players        -               Pass
   default        -               Pass
   players   lazyboy91      Pass

Transparent
Red
Redstone Mode: On to Activate

SolDmg works as expected but plain damage mode still wont let players pass
tried different shield modes and still nothing

if you need more info let me know what you need and how to acquire them
running on server if you need to see with own eyes ask for ip

**Comment by McJty** [comment]
Exact version (not just MC version) and also a few screenshots would help. i.e. a screenshot of your shield GUI

**Comment by TheLazyOne001** [comment]
rftools-1.1x-5.87
forge-1.11.2-13.20.1.2386-universal

**Comment by McJty** [comment]
Screenshot of shield GUI?

**Comment by TheLazyOne001** [comment]
![2017-10-30_15 44 30](https://user-images.githubusercontent.com/33212406/32155104-5e6c06ea-bd89-11e7-8fe1-f3c814a16b1b.png)

**Comment by McJty** [comment]
I think you better remove 'player lazyboy9' pass because that one will block all other players I think

**Comment by TheLazyOne001** [comment]
yep removed still no pass, seems as though server is treating the shield block as a solid block regardless of setting

**Comment by TheLazyOne001** [comment]
there wouldnt be a config file that im missing would there?

**Comment by McJty** [comment]
ah I remember
You have to switch off/on (with the wrench) the shield after making changes to the settings. Try that

**Comment by TheLazyOne001** [comment]
tried just now a few combinations of using lever and rftools wrench

**Comment by TheLazyOne001** [comment]
still nothing

**Comment by McJty** [comment]
Well this works for me so not sure what to say...
With the rftools wrench I mean that the shield goes back to the 'template blocks' form.

**Comment by TheLazyOne001** [comment]
i know yeah its really weird i might have to do some debugging trial and error and see if its another mod doing it, mod list is:
armorplus 1.11.2-10.0.3.4
bdlib-1.13.2.7-mc1.11.2
chiselandbits-13.10
compatlayer-1.11-0.1.7
currency-1.11.2-1.0.5-beta
dynmap-2.4-forge-1.11.2
extrautils2-1.11.2-1.3.3
forestry_1.11.2-5.3.4.101
Forgelin-1.4.2
infinitefluids-1.11-1.1.0
jei_1.11.2-4.5.0.287
Lumberjack-mod-by-doubledoor-1.11.2
Mantle-1.11.2-1.2.0.26
mcjtylib-1.1x-2.3.7
Mekanism-Mod-Core-1.11.2
Mekanism-Mod-Generators-1.11.2
Pressure-Pipes-Mod-1.11.2
rftools-1.1x-5.87
TConstruct-1.11.2-2.7.0.26
thedragonlib-1.11.2-3.0.0
TinkerToolLeveling-1.11.2-1.0.1
VeinMiner-1.11-0.35.3.605+dad98e1
Xaeros_Minimap_1.12.3_Forge_1.11

gonna be a while, if i find the problem i will be sure to let you know so that fixes or warnings can be made

**Comment by TheLazyOne001** [comment]
okay so firstly sorry about the long delay. been off my feet lately.
i loaded just plain rftools-1.1x-5.87, compatlayer-1.11-0.1.7, and mcjtylib-1.1x-2.3.7 and the sheild will not let anything pass still, im wondering if the version of forge i am using may be causing this trouble, either that or there is a setting i am unaware of.
just in case the files i downloaded are corrupt i shall upload the files in case it may shed some light on the matter



[mod files.zip](https://github.com/McJty/RFTools/files/1453733/mod.files.zip)

**Comment by McJty** [comment]
Well you are using really ancient version of rftools. Please upgrade to latest (7.13)

**Comment by TheLazyOne001** [comment]
aha okay will do then ^~^.

**Comment by TheLazyOne001** [comment]
yep that did it. and learned new thing too, when downloading from curseforge make sure to hit grey button not green otherwise it will install latest version and in my case green was 1.12 and grey was 1.11.2.
also i am truly thankful for how fast you replied. now to enforce an update to all of my players mod set ^~^
