### ISSUE TITLE
Builder Block Quarries not working on servers. Working only in single player.

### ISSUE THREAD

**Issue by Nerdtality** [McJty/RFTools#1431]
rftools-1.1x-6.01.jar
rftoolsctrl-1.1x-1.6.8.jar
rftoolsdim-1.1x-5.02.jar

Are used on the server side. Using FTB Beyond Server with FTB Beyond Client.
Forge Version 1.10.2-12.18.3.2316
FTB Beyond 1.10.2-1.10.0

[rftools.cfg.txt](https://github.com/McJty/RFTools/files/1426045/rftools.cfg.txt)

**Comment by McJty** [comment]
You need to be more specific. What is not working? RFTools Builder is used a LOT by many many peoples on servers (including me yesterday even) and it works fine. So if it is not working for you something else must be going on. I need more details. Logs, your setup and what is not working about it

**Comment by Nerdtality** [comment]
RFTools Builder as Quarry not working on server. Looks like it scans 1 Y value and immediately quits

**Comment by Nerdtality** [comment]
[fml-server-latest.log](https://github.com/McJty/RFTools/files/1426057/fml-server-latest.log)
[latest.log](https://github.com/McJty/RFTools/files/1426058/latest.log)

**Comment by McJty** [comment]
Ah, are the chunks claimed? This is a problem in FTB Utilities where it doesn't allow fake players to work

**Comment by Nerdtality** [comment]
Nope, area is unclaimed.

**Comment by McJty** [comment]
Can you show screenshots of the setup and gui?

**Comment by Nerdtality** [comment]
I'll do one better, a GIF

https://i.imgur.com/nEjkvwL.gifv

**Comment by winsrp** [comment]
I just talked to the guys on Minecolonies about the same issue, they told me the following:

"If you're on a server you'll have to tell RFtool to give the machine the players UUID as own UUID.
Because that's how forge intended it. (That's what Lex told us)"

**Comment by McJty** [comment]
That doesn't make any sense. A Builder should be able to work even if a player didn't place it (if placed with some automatic block placer for example). Also many people are using this on servers with no problems. The Builder is one of the most widely used quarries atm

**Comment by winsrp** [comment]
Don't shoot the messenger XD... I'm just copy pasting.

**Comment by Nerdtality** [comment]
How would I go about doing this?

**Comment by Nerdtality** [comment]
Updated to latest version and still nothing is working.

**Comment by McJty** [comment]
Latest version of what?

**Comment by McJty** [comment]
As far as I know this is a bug in Minecolonies. Please report to them

**Comment by Nerdtality** [comment]
After some further research, RFTools Builder ~ Quarry is not working because the server is in offline mode. The server must be in offline mode for Bungeecord to work.

**Comment by Nerdtality** [comment]
Issue is fixed, looks like an incorrect NBT value.

**Comment by CommanderLemon** [comment]
what?.. how do i fix a incorrect NBT value?
