### ISSUE TITLE
Control Elevator Speed?

### ISSUE THREAD

**Issue by ResqDiver1317** [McJty/RFTools#1436]
I was wondering if it was possible to force the elevator to stay at the slow speed it has when it first starts moving? When it starts going faster, it's like the client gets out of sync with the elevator. You see the platform take off and the player starts "bouncing" down or up to where the elevator stopped at (which seems to take anywhere from 5-30 seconds. We are running RFTools 1.1x-7.12 on an MC1.10.2 server with a custom built modpack. We had the same issue on our FTB Beyond server as well.

**Comment by filikun** [comment]
I found in the rftool config

    # Distance from the end at which speed will start going down again
    D:maxSpeedDistanceEnd=2.0

    # Distance from the start at which maximum speed is reached
    D:maxSpeedDistanceStart=5.0

    # Maximum elevator speed
    D:maximumSpeed=0.3

    # Mimumum elevator speed
    D:minimumSpeed=0.1

**Comment by filikun** [comment]
Changing them broke my elevator though :/ The elevator floor moves as fast as it did from the beginning but the player standing on it going down slower. Anything to do about that?

**Comment by josephcsible** [comment]
Did you change the config settings on both the client and the server?
