### ISSUE TITLE
[issue/improvement] Scanner crippling server

### ISSUE THREAD

**Issue by XDjackieXD** [McJty/RFTools#1438]
A single scanner set to (I think) maximum size (512x512 blocks) scanning continuously uses around 34ms per tick on the BTM server. As there probably isn't a lot of potential to speed up the scan as world access is pretty slow, I'd suggest artificially slowing down a scan.
We are running RFTools Version 1.12-7.12.
Should you need/want the sampler report, please tell me.

**Comment by McJty** [comment]
The scanner should not constantly scan. Why is it setup like that? Best to only scan when enough has changed.  Btw the scanner already slows itself down and in the configs you can make it even slower
