### ISSUE TITLE
RF Dimensions

### ISSUE THREAD

**Issue by 3DWafflee** [McJty/RFTools#1439]
I made a dimension on other server so i can pregen it so the server wont lag when player fly around. But when i transferred it and gave it all the permissions needed i doesn't appear to be there. I can see it with ./rftoolsdim:rftdim info 5. But when am use the probe to teleport to it or command doesn't work. I also tried ./world load rftools5 and /world load 5. (We already transferred 3 rftools dimensions and this is the only one that didn't work)

**Comment by McJty** [comment]
Logs and version

**Comment by 3DWafflee** [comment]
[fml-server-latest.log](https://github.com/McJty/RFTools/files/1443921/fml-server-latest.log)
And am using Beyond 1.11.0 [![Screenshot from Gyazo](https://gyazo.com/14d4452d6b29603c3e27323a397f36d8/raw)](https://gyazo.com/14d4452d6b29603c3e27323a397f36d8)

**Comment by McJty** [comment]
Those are really old versions. It is likely all of this has been fixed

**Comment by josephcsible** [comment]
Can you see if this still occurs on the latest versions?
