### ISSUE TITLE
1.12.2] ATM3 Inferium Ore

### ISSUE THREAD

**Issue by JackGrey** [McJty/RFTools#1450]
When I make an Inferium Ore (from Mystical Agriculture) Dimlit and it generates Chorus Flowers instead. I tried changing it around to see if it was a bug with the features I was using but no such luck. 

I tried searching first to make sure this was not a duplicate but I did not see anything. I also apologize if i need to be posting somewhere else. This is my first time writing a thing like this.

**Comment by McJty** [comment]
Show me the rest of the dimension info. i.e. what dimlets and what does right clicking the tablet say

**Comment by josephcsible** [comment]
This sounds like it might be the same as #1563, which is fixed as of RFTools Dimensions 5.51. Can you see if updating fixes it?
