### ISSUE TITLE
[1.12-7.12] Infused Advanced Powercell transferring too much?

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#1451]
Hi McJty,

I infused to 100% and linked some advanced powercells then used them to connect a Nuclearcraft fusion reactor to a Draconic Evolution powerball.  I have one powercell transmitting and four powercells receiving.

It would seem that the single transmitting powercell is able to transmit enough to feed all four receiving powercells. 

Have I derped or is a check not being done at the transmitting end?

Cheers!

Forge 14.23.0.2517
RFTools 1.12-7.12
mcjtylib 1.12-2.4.4 (incidentally, this doesn't seem to appear in the mod options list, in-game)

**Comment by McJty** [comment]
Why wouldn't that be possible? I mean what's the actual problem here? There is no limit to the speed that powercells transmit energy over their internal network (i.e. connected powercells)

**Comment by xenoflot** [comment]
I expected the input for the cell to be the same as the output. If not, then no problem :)

**Comment by McJty** [comment]
Hmm... Well maybe explain your setup a bit better. It can be that I'm not understanding what you are actually doing. Maybe some screenshots?

**Comment by xenoflot** [comment]
https://i.imgur.com/r8b19qs.png

I think a simple diagram is easier to follow.  Reactor on the left with a single powercell on it.  Four powercells feeding the DE powerball.  All powercells are linked on a single channel.

So far as I can tell, the receiving powercells are outputting at 30KRF/t max as expected. Whether by design or technical reasons, the network is receiving the full output of the reactor via a single powercell. 

My expectation was that the network input would be capped at the max xfer rate of the powercell (in this case 30KRF/t).

**Comment by McJty** [comment]
Network input should indeed be capped. What makes you think the cap isn't working? Are the four output cells actually really doing 30KRF/t output? I mean is something consuming energy?

**Comment by xenoflot** [comment]
Hello again,

The DracEvo powerball is a big capacitor that will hold about 2TRF and is only 25% full. The input points for it have no xfer limit, so it will suck up all the RF that I can throw at it. I have just done some more testing to ensure I'm not giving you a bum steer. 

* My reactor is producing around 202KRF/t and the powerball is only 25% full. 
* I disabled/disconnected all other connections from the powerball to ensure an accurate reading on xfer rates. 
* The test powercell network has a unique ID, not shared by any other systems.

Terminology: "input/output" powercells are from the perspective of the RFTools linked powercell network.

* With 8 output powercells and a single input powercell, the reactor's buffer remains empty and the DE powerball correctly reports ~202KRF/t incoming. 
* With a single output powercell, the DE powerball reports 30KRF/t incoming.
* With two output powercells, the DE powerball reports 60KRF/t incoming.
* Toggling the _input_ powercell to "all out" results in the reactor's internal buffer filling up.
* Toggling back to "all in" results in the reactor's internal buffer draining again.

This suggests to me that either the input powercell is not enforcing the 30K limit, or the NuclearCraft reactor is bypassing that check by supplying the RF in a non-compliant way.

**Comment by McJty** [comment]
Weird. I will check it out

**Comment by McJty** [comment]
Ok, I found the problem. Will be fixed next release
