### ISSUE TITLE
[1.12.2] Wither projectiles pass through shield when shield texture is set to Invisible

### ISSUE THREAD

**Issue by Fatmice** [McJty/RFTools#1452]
rftools-1.12-7.13
Per title.  The projectiles (usually blue skulls) will then wreck havoc as usual.  There is also the client-side errors that's emitted right click to open the shield block.
https://gist.github.com/Fatmice/da7fb203bfa423366bc756cf9db97339
![2017-11-12_02 56 24](https://user-images.githubusercontent.com/8956281/32697455-564b81d0-c756-11e7-9e40-5bb6c345febb.png)
![2017-11-12_02 56 42](https://user-images.githubusercontent.com/8956281/32697456-565db1b6-c756-11e7-8bac-16051adb4b88.png)
![2017-11-12_02 56 43](https://user-images.githubusercontent.com/8956281/32697457-566f8878-c756-11e7-9844-8bd13adecb41.png)
![2017-11-12_02 56 44](https://user-images.githubusercontent.com/8956281/32697458-5681e522-c756-11e7-8e92-ccd973b6592b.png)
![2017-11-12_02 56 46](https://user-images.githubusercontent.com/8956281/32697459-5693a5aa-c756-11e7-8c8d-98d0c9a5dd8b.png)
![2017-11-12_02 56 50](https://user-images.githubusercontent.com/8956281/32697460-56a9d2da-c756-11e7-832a-0c256e95aebb.png)
![2017-11-12_02 56 53](https://user-images.githubusercontent.com/8956281/32697461-56cf8606-c756-11e7-94d0-81cf96074c84.png)
![2017-11-12_02 56 54](https://user-images.githubusercontent.com/8956281/32697462-5710e150-c756-11e7-8942-825b32054f36.png)

**Comment by McJty** [comment]
Thanks for the report. I will check it out soon

**Comment by McJty** [comment]
Actually there may not be anything I can do about this. Apparently the Wither uses the same function to check for projectile trajectory that I use to make sure players cannot notice the invisible shield blocks. So I guess this is just a limitation that will probably stay

**Comment by Fatmice** [comment]
Okay.
