### ISSUE TITLE
[1.12.2] Builder can not change mode [1.12-7.13]

### ISSUE THREAD

**Issue by lugiaf** [McJty/RFTools#1453]
( It resembles here #1409 )
" I want to move a building, but when I set the builder to move and close the GUI. the setting stays on copy mode."

same issues ?

*already tested : 
/ My modpack ( list: https://pastebin.com/tSs6VuJH )  / Forge: 14.23.0.2512
/ FTB Presents Direwolf20 1.12 by FTB ( https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12 )
/ RFTools standalone (McJtyLib and RFTools only) / Forge: 14.23.0.2545
                           

![2017-11-18_10 31 26](https://user-images.githubusercontent.com/32650275/32975614-593b0cee-cc4c-11e7-834e-de376547592c.png)
![2017-11-18_10 31 36](https://user-images.githubusercontent.com/32650275/32975616-5fd965a0-cc4c-11e7-83f8-ff0301e86d61.png)
![2017-11-18_10 36 11](https://user-images.githubusercontent.com/32650275/32975627-77e4db8e-cc4c-11e7-9b33-2a8168434842.png)

**Comment by McJty** [comment]
Already reported and fixed for next release (soon)
