### ISSUE TITLE
[1.12.2] RFTools Config and Non-Vanilla items?

### ISSUE THREAD

**Issue by 666lumberjack** [McJty/RFTools#1456]
I'm trying to specify material requirements in the config for the Spawner to require non-vanilla items but it doesn't seem to work? It seems like it's intended to be since all the defaults list 'minecraft:[item]' rather than just a specific item, but I haven't been able to get any modded items to work - they just show as living material. Similarly, I tried to add the Cellular Block from Botania as a source of Living Material but it hasn't worked. I'm guess it may just be a syntax issue, but I can't find anywhere the correct syntax is documented. 

My config file is here: https://www.dropbox.com/s/ou9gxqnrj0f4m30/rftools.cfg?dl=0
And a paste of the relevant portions: https://paste.ee/p/xalh6

Let me know if I can provide any other details.

**Comment by McJty** [comment]
Your botania block is using living.10 which is already used earlier in the config. Use a unique number there

**Comment by 666lumberjack** [comment]
I have resolved that conflict, but I still can't use cellular blocks as a source of living material (and the other issue also remains). 
New living material / spawner config: https://paste.ee/p/hiuRx
