### ISSUE TITLE
Do you want to add a function for builder？

### ISSUE THREAD

**Issue by forestbat** [McJty/RFTools#1462]
@McJty We all want to save our buildings to files like BC and share them to our friends，will you add the function？

**Comment by McJty** [comment]
You can already do this with the RFTools Builder. No need for export to BC builder

**Comment by forestbat** [comment]
@McJty How to export to RFtools Builder？I didn't find how to do this in the manual。

**Comment by NH4HCr2O7** [comment]
It should be in the "rftoolsscans" folder
