### ISSUE TITLE
[Dupe Bug] Dislocation Focus

### ISSUE THREAD

**Issue by ProRedHD** [McJty/RFTools#147]
When using the Dislocation Focus from Thaumic Tinkerer the machine drops and the focus has the machine in its buffer, I tested it with the Dimension machines.

**Comment by McJty** [comment]
I will see if I can fix this

**Comment by McJty** [comment]
Hopefully fixed next release.

**Comment by SammieBanks** [comment]
https://www.youtube.com/watch?v=_xsnZTiK70E

**Comment by McJty** [comment]
What has this video to do with rftools
