### ISSUE TITLE
[1.12.2] No Teleport module doesn't work at all

### ISSUE THREAD

**Issue by L0ST5ILVER** [McJty/RFTools#1470]
I've been playing with rftools for a bit and the No Teleport module just doesn't work at all.
The environmental controller is full on RF, radius set to 100 and height set to 90, 210
Screenshot: http://prntscr.com/hhv8u9
And here are the Enderman that are meant to be affected: http://prntscr.com/hhvai8
They should be within radius. But I look at them and they just swarm towards me.

Am I doing something wrong?

EDIT: This is actually the case for all effect modules

**Comment by L0ST5ILVER** [comment]
Anyone??

**Comment by L0ST5ILVER** [comment]
Can someone please help?

**Comment by McJty** [comment]
That's a huge area you're affecting. Check out how much RF/t that needs but I think you are exceeding the maximum allowed

**Comment by McJty** [comment]
you can see the RF/t in the TOP tooltip btw (look at the block)

**Comment by L0ST5ILVER** [comment]
I can't try that now, but I've never seen that tooltip appear before. But I should have enough RF considering the machine I use to generate the RF is supposed to generate 36k RF/t
I also tried this with the shortest range, I tried it on default settings, height 30, 70 radius set to very low, tried 5, tried twenty. I have Enderman near me to teleport but they were still able to teleport around.

I think this might be obvious but I'm doing this in the end. Just in case that affects anything, at a very low Y level.

**Comment by McJty** [comment]
I mean the WAILA/TOP tooltip that you see when looking at a block in the world. You have either of those mods yes?

36k RF/t is *not* going to be enough for such a huge area that you're trying to affect with this. Also note that every side of the environmental controller can only receive 20000 RF/t. So if you need more power input you will need to input from multiple sides.

**Comment by L0ST5ILVER** [comment]
But I tried it with the smallest possible range as well and it still didn't work, I tried it with potion modules too and got 0 effects while standing within range. I had everything checked multiple times.

**Comment by L0ST5ILVER** [comment]
This is a screenshot of an Enderman literally less than 5 blocks away from the active controller: http://prntscr.com/hj37fi And he was still able to teleport around, there were actually two in the area but the first one teleported before I could take the screenshot.

Here is what the inside of the controller looks like: http://prntscr.com/hj38dw
(I made no changes from when the first screenshot was taken with the enderman)

And I do not have Waila.

**Comment by McJty** [comment]
I recommend you add TOP or waila. It really helps to debug this problem

**Comment by L0ST5ILVER** [comment]
Can I have a link to one of those for 1.12.2 please?

**Comment by McJty** [comment]
I am on phone but just search for The One Probe

**Comment by L0ST5ILVER** [comment]
Got it! I'll try it later I have other stuff to do now.

**Comment by L0ST5ILVER** [comment]
Here is what TOP says when I look at the controller: http://prntscr.com/hjhojp

**Comment by superfluke** [comment]
I think it might have to do with being in the end. Just tested in my world and no teleport works fine in the overworld but doesn't seem to effect endermen in the end. Tested the saturation module as well, which worked fine in both the overworld and the end. 
![2017-12-05_20 54 39](https://user-images.githubusercontent.com/20022336/33640434-a412c1b6-d9fe-11e7-9892-2308d7934888.png)

rftools-1.12-7.14
mcjtylib-1.12-2.5.0
forge-1.12.2-14.23.1.2556

**Comment by McJty** [comment]
I will try to figure out why it doesn't work in the end

**Comment by L0ST5ILVER** [comment]
Any idea why the potion effects could not work as well?

**Comment by McJty** [comment]
Might be the same problem. I'll check it out

**Comment by L0ST5ILVER** [comment]
Was a solution found?

**Comment by McJty** [comment]
Sorry, haven't checked yet. Was busy with other mods. Will try it out soon

**Comment by L0ST5ILVER** [comment]
Okay, thanks.

**Comment by BrisingrAerowing** [comment]
I just noticed this myself, although it isn't working in the overworld for me. I am spawning in the endermen using an Industrial Foregoing mob duplicator, FWIW.

**Comment by josephcsible** [comment]
Can you try to reproduce this in a clean instance with just McJtyLib and RFTools? If it works there, can you try to figure out exactly which other mod is causing it?

**Comment by BrisingrAerowing** [comment]
I'll take a look and see what's what.

**Comment by BrisingrAerowing** [comment]
Yup, it's broken even with just McJtyLib and RFTools.

**Comment by josephcsible** [comment]
Works fine for me in both the Overworld and the End. What version of McJtyLib, RFTools, and Forge are you on? Are you sure the environmental controller is getting enough power? What do you have it set to effect? If you set it to effect "All", do you get the "No Teleport" icon in the corner, and do ender pearls not teleport you?

**Comment by BrisingrAerowing** [comment]
I just upgraded Forge and it now works in my testing instance, I am going to check it in my main instance when that starts up (it takes a few minutes as it has a lot of mods).

**Comment by BrisingrAerowing** [comment]
It seems to work with the new Forge version. I'll reply again if I find anything else. Although, I did have a lot of Endermen from an Industrial Foregoing mob duplicator (around 15 or so), so the number of them may have something to do with it.

**Comment by josephcsible** [comment]
Okay, I'll close this for now then. If you it see it again, let me know and I'll reopen it.
