### ISSUE TITLE
1.12.2 Sequencer not powering blocks.

### ISSUE THREAD

**Issue by MrPryor** [McJty/RFTools#1472]
![xu6dvqz](https://user-images.githubusercontent.com/1627964/33640930-611a8418-da01-11e7-9a24-1c1ab773f1dd.png)

**Comment by McJty** [comment]
No it will not power blocks. Put a redstone wire after it or a machine. Not a stone block

**Comment by Henness0666** [comment]
I personally think it should work this way, that is how almost any other redstone object works. Even Vanilla minecraft uses it with the comparator or the repeater.

**Comment by McJty** [comment]
The reason that I don't do it like that is that it then becomes impossible to control just a single machine if you have multiple adjacent to each other
