### ISSUE TITLE
Item Filter issue with passive mobs

### ISSUE THREAD

**Issue by tjsd** [McJty/RFTools#1473]
Hello!
I have placed a grid of 3x3 item filters all setup like this:
![image](https://user-images.githubusercontent.com/7138125/33688735-bedc8be2-dadc-11e7-984c-40fe6ae7abdf.png)
I wanted cows and chikens to fall trough the blocks when placed on top. But it does nothing. Also I dont know what item to represent the different animals, but I guess those should work. Does it also know if the animal is adult or not?

rftools-1.12-7.14

**Comment by McJty** [comment]
That's not what the filter does. It filters items. Not entities. i.e. items that are piped in with conduits from nearby chests
