### ISSUE TITLE
Possible Powercell channel bug?

### ISSUE THREAD

**Issue by Selway00** [McJty/RFTools#1476]
One of the channels in my Powercell network appears to be bugged.  It is not drawing or sending power.  When I insert the troubled channel card into any powercell, the power indicator disappears and shows a fantastically negative number.  When I remove the card, the power bar returns to normal.   

Other things I have tried:
My powercells and other channels appear to be operating normally.   
I have also borken and replaced them multiple times.  
I have tried relogging completely.  
I have plenty of power available.
I have tested it on another isolated system and the channel is still bugged.

I am running the latest version of Age of Engineering. 
RFtools 1.1x-1.6.8
Rftools dimensions 1.1x-5.05

Here are some pictures if it helps.  

https://imgur.com/gallery/6Zyaa

Incredible mods! Thanks for them!

**Comment by McJty** [comment]
That's an old version of rftools. This overflow bug has been fixed since. You exceeded 2 billion RF

**Comment by Selway00** [comment]
Ahhh.  OK.  Hey thanks for the quick reply.  Cheers

**Comment by Selway00** [comment]
Are you saying that if I exceed 2 billion accumulated RF transmitted it will bug out?  Or if it tries to remove or add power from a storage source greater than 2billion?

**Comment by ktole1999** [comment]
sounds like there was a bug when you exceeded 2billion rf using that old version.

**Comment by McJty** [comment]
yes and even in the latest version you cannot put more then 2 billion rf in

**Comment by Selway00** [comment]
So the work around is not to have any power STORAGE greater than 2Billion RF?

**Comment by McJty** [comment]
Yes

**Comment by Selway00** [comment]
Gotcha.  Thank you!
