### ISSUE TITLE
Client crash.

### ISSUE THREAD

**Issue by SlothKing16** [McJty/RFTools#1479]
New RFTools crashes before I get to the main menu. With no other mods it works fine, but with my current batch it crashes.

Log: https://pastebin.com/vyD2m8Xh

**Comment by McJty** [comment]
Can you upgrade Open Computers?

**Comment by SlothKing16** [comment]
Forgot to say i'm on 1.10.2, - 124 is the latest for Opencomputers on 1.10.2 on curseforge.

**Comment by SlothKing16** [comment]
With Opencomputers disabled it loads up, and the Screen Controller crash from my previous thread is fixed on the latest. Should I be bringing this issue up to them then?

**Comment by josephcsible** [comment]
Same cause as #1466 and #1478, and same solution: use [this experimental build](http://ci.cil.li/job/OpenComputers-MC1.10/146/) of OpenComputers until they create a new official release.

**Comment by SlothKing16** [comment]
Thank you!
