### ISSUE TITLE
[Suggestion] Bigger Storage Modules 400, 500, 600, 1000

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJty/RFTools#1481]
300 Stacks if fine and dandy, but more is better :)

**Comment by McJty** [comment]
And more likely to crash your client.  There is a pretty small limit to the size of an item and the 300 stack modules are already pretty near that limit

**Comment by Unrepentant-Atheist** [comment]
Oh, okay. Didn't know that. But then again, not necessary anymore once I got the hang of using Storage Scanner with Storage Drawers.

**Comment by McJty** [comment]
Indeed. That's a better way to go :-)
