### ISSUE TITLE
[1.10.2] Crashing whilst opening interfaces

### ISSUE THREAD

**Issue by Byakuun** [McJty/RFTools#1482]
So I own a server and after working on a builder block I tried to open the manual which crashed my game, as well as the quarry shape card. The shape card crashes when you click on anything in its interface and give this message : https://pastebin.com/PnEFKyiT

I've tried getting a new version of rftools and getting rid of optifine. Any help would be greatly appreciated.

**Comment by McJty** [comment]
This is an ancient version of rftools that you're using. Updating to latest should fix it

**Comment by Byakuun** [comment]
Updating it gave this error while starting up 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)

**Comment by McJty** [comment]
Updating to what exactly. More details please

**Comment by Byakuun** [comment]
forgot pastebin https://pastebin.com/M2ei1REj

The RFtools version to the 7.15

**Comment by McJty** [comment]
Ah you need to update Open Computers. @josephcsible can tell you where you can find that
Or else update to 7.14 which doesn't have that issue

**Comment by josephcsible** [comment]
Use the experimental build of OC that I linked in #1466.

**Comment by McJty** [comment]
To @josephcsible . How long before they release? If it takes too long we might need to rollback the changes to rftools because this is giving a lot of issues

**Comment by josephcsible** [comment]
I just asked them to do one. In the meantime, would it be worth putting a note about this on the mod's description page?

**Comment by josephcsible** [comment]
Okay, they did one (1.7.1.150).

**Comment by Byakuun** [comment]
Wow thanks you guys, that's insane I get to download a mod minutes after being updated (to me at least). I appreciate the work boyos. Keep em comin'
