### ISSUE TITLE
Simple Dialer does not interrupt a link

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#1484]
Possibly related to https://github.com/McJty/RFTools/issues/1262

Forge 14.23.1.2555
RFTools 1.12-7.15
mcjtylib 1.12.2.5.0

Simple Dialer will establish a link when given a redstone pulse, but subsequent pulses do not interrupt the link. According to the tooltip, it should do so.

Cheers

**Comment by McJty** [comment]
Hmm no. What part of the tooltip indicates that it does that ?

**Comment by McJty** [comment]
You can setup a different dialer dialed to nothing which can be used to interrupt a connection

**Comment by xenoflot** [comment]
The tooltip reads, "When this block gets a redstone signal it dials or interrupts a transmitter." To me, that implies it toggles the link state.

Since apparently that isn't the case, you might want to reword it as "When this block gets a redstone signal it dials a transmitter, overriding any existing link."

Personally though, I think toggling the state is a more intuitive way.

**Comment by McJty** [comment]
Well the tooltip is accurate. It dials or interrupts a transmitter depending on how the simple dialer is set up. That's really what it does. And it cannot be a toggle. That's not how this works

**Comment by xenoflot** [comment]
Fair enough. Thanks for the quick reply.
