### ISSUE TITLE
[MC1.11.2] Crash on startup (with OpenComputers)

### ISSUE THREAD

**Issue by YswMusician** [McJty/RFTools#1487]
Minecraft crashes.
Minecraft Version : 1.11.2 / Forge Version : 13.20.1.2563
All Mods :
 CompatLayer 0.2.9
 McJtyLib 2.5.0
 RFTools 7.15
 OpenComputers 1.7.1.79
(All mods and forge are the newest stable version)
Crash Report : [crash-2017-12-16_13.46.05-client.txt](https://github.com/McJty/RFTools/files/1564510/crash-2017-12-16_13.46.05-client.txt)

I also ran another test with RFTools 7.14. RFTools 7.14 didn't cause problem but RFTools 7.15 did.

**Comment by McJty** [comment]
@josephcsible Any idea?

**Comment by josephcsible** [comment]
#1489
