### ISSUE TITLE
CTD's with new dimensions.

### ISSUE THREAD

**Issue by connorhaganNecc** [McJty/RFTools#149]
Upon updating to Infinity 1.4, which is using rftools-2.75, I've discovered a serious issue with new worlds I'm creating in RF Tools. When I make a new void world it works for a while, but upon either using a Draconic Evolution teleporter in that dimension or restarting the server and entering/existing in that dimension I get a CTD, making it impossible to ever enter that world again and requiring me to use NBTedit to change my dimension. I can't even remove the dimensions from the Draconic Evolution teleporter because attempting to do so also causes CTD.

This is the specific error:
java.lang.IllegalArgumentException: Could not get provider type for dimension 137, does not exist

where dimension 137 is a void world I started building in yesterday. Another detail is that it only affects my client and not the server, the server keeps on running fine.

By the way thanks for this mod, it's amazing, and if you need any more details let me know.

**Comment by connorhaganNecc** [comment]
Full crashlog: http://pastebin.com/0XNSZ4cG

**Comment by McJty** [comment]
This is a known problem but not something I can solve. Minecraft is limited to 128 dimensions (one byte only). You can make dimensions above that number but you cannot login to them and there might be other problems. RFTools cannot solve this. However, the latest release of Forge fixes this issue. If you have the option to update Forge then that would be the best way to proceed.

**Comment by connorhaganNecc** [comment]
If I delete old, unused dimensions will that work? I've tried to remove a bunch but it isn't working. Thanks for your time!

**Comment by McJty** [comment]
You will have to delete old dimensions with /rftdim savedel <id>
That way new id's will be made available (below 128 hopefully) and new dimensions will use those.
