### ISSUE TITLE
Feature Request: AE2 & Refined Storage inventories

### ISSUE THREAD

**Issue by GGearZZ** [McJty/RFTools#1491]
Hello. Would it be possible to add an upgrade module to the RFtools Storage scanner that would allow you to read the disk contents of AE2 & Refined Storage systems? Thank you for your time.

**Comment by josephcsible** [comment]
This is already possible. Just put an Interface on your Refined Storage network (or do the AE2 equivalent of that).

**Comment by GGearZZ** [comment]
Strange. I tried it again & it worked. Perhaps before I hooked it up wrong. Thank you for that :)
