### ISSUE TITLE
Can't set redstone receivers to transmitters.

### ISSUE THREAD

**Issue by uehlbran** [McJty/RFTools#1492]
I'm sneaking + right clicking on a transmitter, with a receiver and it will not set the channel. However, if you do it 20-30 times and somehow get lucky it works. It never works the first time. Buggy as hell for me.

Version: 1.12-7.14

**Comment by McJty** [comment]
Hmm never got this reported before. It always works flawlessly for me. Can you describe exactly what you're doing?

**Comment by uehlbran** [comment]
Honestly, nothing special. I spawned in the items using creative mode. Then went back to survival mode, placed the transmitted block, sneak + right clicked with the receiver block on the transmitter and it rarely works. Well, intermittently works.

**Comment by itstwoam** [comment]
Had the same problem but managed to figure out how to get it to work 100% of the time.  There has to be at least a blocks distance between you and the transmitter and you can only right click on the side never the top.

**Comment by josephcsible** [comment]
Pairing transmitters and receivers works for me the first time, every time, with RFTools 7.33, McJtyLib 2.6.7, Forge 2654, and no other mods installed, even when there's no distance between me and the block and I right-click on the top. Please try with this setup and see if the problem ever occurs. If so, please record a video of the problem, and upload it, the saved game that it occurs in, and the full log. If not, gradually add your other mods back until you figure out which one is breaking it, and let us know which one that is.
