### ISSUE TITLE
Need Simpler Way to Remove Dimensions from Dialer List

### ISSUE THREAD

**Issue by IAmVensey** [McJty/RFTools#1495]
Recently started RFTools Dimensions. Created most basic dimension (which became ID 2) with no additional dimlets (so just the basic random dimension).

Wanted to clean up the Dialer, so searched for a way to do so. Was unable to find any way aside from using /rftdim safedel <dimension> command. Used command.

Later decided I wanted the basic random dimension back. Created a new blank dimension tab (same ID: 2). ID 2 is back into dialer, but now I can't travel to the dimension (Getting error: "There is a problem with the destination.")

Tried to use both /rftdim reclaim <dimension> and /rftdim recover [<dimension>] commands. Getting error that both are unrecognized commands. 

Now my most basic dimension is missing and I have no way to get it back. It is the only one I can create using no additional dimlets. 

So now what am I supposed to do?

**Comment by McJty** [comment]
You can use digit dimlets to get another random dimension. Why do you specifically need one with no dimlets?

**Comment by IAmVensey** [comment]
I'm looking into those now. I was having issues with loading it. I ended up playing with some things in my world and things seem to be working as needed now. Thank you.

**Comment by josephcsible** [comment]
What happened to you does sound like a legitimate bug, but when I tried to reproduce it on 1.12.2, it worked fine for me. What version did it happen to you on?
