### ISSUE TITLE
Duplication bug with Extra utilities and auto crafter

### ISSUE THREAD

**Issue by Minecraftdaboss** [McJty/RFTools#150]
When using the Auto crafter with a inactivated signal to produce iron, the signal isn't used up and can be used to duplicate 4 iron for every use inside the machine.

**Comment by McJty** [comment]
Sorry I don't get this. Can you describe better what you're doing?

**Comment by Minecraftdaboss** [comment]
Alright, if you place a inactivated division signal in a crafting bench normal it would give you some iron. If you add the recipe to the autocrafter to transfer it into iron, it will make the iron and retain the signal, allowing you to keep putting it in the crafter and duplicate iron.

**Comment by Divineaspect** [comment]
sigil, he means division sigil.

**Comment by Minecraftdaboss** [comment]
^ Yeah lol sorry

**Comment by McJty** [comment]
Should be fixed in next version
