### ISSUE TITLE
[Bug] Experience glitched following teleport

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#151]
Hi Mr McJ,

I'm running Infinity 1.3.4 (RFTools 2.71). I noticed last night that following a dimensional teleport, my XP level is not displayed (suggesting I have zero accumulated experience). Indeed attempting to enchant something, says I have insufficient XP.  A quick sip from the XP tank and my XP is correctly restored (when I was testing, over level 100 IIRC).

XP is not being drained, it's just some kind of temporary glitch following a teleport, that is corrected when XP is updated (e.g. kill a mob, sip from an XP tank) (An XP BUD switch!)

This glitch doesn't occur following a JourneyMap teleport, nor a Nether transition. I don't have any mystcraft stuff set up to test with that, sorry.

Apols if this is a dupe. I searched Closed issues for "xp" and "experience" and didn't come up with any matches.

**Comment by McJty** [comment]
I could reproduce this. Trying to see if I can fix it.

**Comment by McJty** [comment]
Fixed in next release.
