### ISSUE TITLE
[1.12-7.21] Client side Illegal Argument Exception

### ISSUE THREAD

**Issue by kreezxil** [McJty/RFTools#1528]
we were facing an elevator that was being setup in rftools and opened a chest and the following client side crash happened.

*note: turns out this is happening randomly to lots of my players. I've got multiple crash reports for the same thing. If you want all of them I can attach them.

client crash report: https://pastebin.com/rwEEh6M8

dedicated server is unnaffected.

**Comment by Chunkey** [comment]
Just gonna post my crash report here. 
https://pastebin.com/QQTe9jZt
Repeatable. Happens when I try to pick up my builder with the smart wrench.

**Comment by McJty** [comment]
Both problems will be fixed next release
