### ISSUE TITLE
Ender Dragon Dimension - Bedrock Dimlet Problem

### ISSUE THREAD

**Issue by IAmVensey** [McJty/RFTools#1530]
Not sure if it's supposed to be this way or not, but Ender Dragons do not spawn in the dimension with a bedrock material dimlet.

**Comment by McJty** [comment]
Why would a bedrock material dimlet cause ender dragons to spawn? I don't see the connection?

**Comment by IAmVensey** [comment]
Sorry, I forgot to specify. I am creating the Ender Dragon dimension and using the Bedrock material dimlet seems to prevent them from spawning. I was on normal mode in Survival, and after waiting for up to ten minutes, I decided to fly around for another ten, but the Dragons still wouldn't spawn.

**Comment by masterX244** [comment]
is the world entirely out of bedrock?
If RFTdim uses the normal spawning logic of mobs and the only surface blocks are bedrock then no mob will spawn ever (bedrock is like a bottom half slab in that case)

**Comment by IAmVensey** [comment]
Ah, that might be why. I had only put in the bedrock. I'll try it again with more than one material dimlet then and see how it goes. I didn't know that about the spawning logic, so thank you!

**Comment by josephcsible** [comment]
@IAmVensey Can this be closed now?

**Comment by IAmVensey** [comment]
Whoops! Though I had! Sorry; yes, it can.
