### ISSUE TITLE
Shield doesn't stop all entities some pass/fall through

### ISSUE THREAD

**Issue by Varg95** [McJty/RFTools#1531]
i used the newest version of rftools (1.12-7.22) and mcjtylib (1.12-2.6.1). 
So some mobs fall and go through the shield blocks. Examples are npc's from custom npc's, fox from drp medieval and some mobs from the avatar out of the iceberg mod (the fire and airbenders and skybison. The OtterPenguin does work as normal) mowziesmobs also but this was on 1.11.2 . i hope this examples can give you an idea what could cause this. 

Anyways thanks for the time. I hope you can fix this.

**Comment by McJty** [comment]
Can you show me the configuration of your shield? Are you sure you set it to affect passive mobs?

**Comment by Varg95** [comment]
its set to stop all entities

**Comment by McJty** [comment]
Screenshot of your shield config please

**Comment by Varg95** [comment]
![2017-12-29_20 10 57](https://user-images.githubusercontent.com/23167416/34445579-fda941bc-ecd4-11e7-8cca-4a4053f0fbfa.png)
![2017-12-29_20 11 35](https://user-images.githubusercontent.com/23167416/34445581-fdcd1452-ecd4-11e7-83e4-74d5c56b048c.png)
![2017-12-29_20 12 33](https://user-images.githubusercontent.com/23167416/34445582-fde93a2e-ecd4-11e7-985e-8ba84844aeea.png)

**Comment by McJty** [comment]
Hmm weird. I'll check it out

**Comment by josephcsible** [comment]
Can you post your whole mod list with versions? Are you using Sponge?
