### ISSUE TITLE
RFTools spawner/matter beamers not working.

### ISSUE THREAD

**Issue by uehlbran** [McJty/RFTools#1536]
I have 3 matter beamers, and 1 spawner. The matter beamers have a full stack of the correct item (one has pork chops uncooked, the other has a nether star, and the last one has soul sand), the spawner has a syringe full of wither essence, they are all linked, and have power. However, the spawner does nothing. Tried applying redstone signal to spawner and it didn't help. The matter beamers are not sending items either. They do have glass between them and the spawner though. Is that the cause? Will test this and see.

McJtyLib: 2.61
RfTools: 7.22
Forge: 2555
MC: 1.12.2
Pack: Direwold20 1.12.2

**Comment by McJty** [comment]
Can you show me screenshots of the gui's (of spawner + beamer)?

**Comment by uehlbran** [comment]
I'm just an idiot on this one, lol. I wasn't aware matter beamers required a redstone signal...

**Comment by uehlbran** [comment]
I'm just an idiot on this one, lol. I wasn't aware matter beamers required a redstone signal...
