### ISSUE TITLE
Feature Request: Logic Gates

### ISSUE THREAD

**Issue by Keridos** [McJty/RFTools#154]
As I asked in IRC. This is just an official issue regarding that. Can you please add in AND, NAND, OR, NOR, NOT and XOR gate? The Project:Red ones are pretty weird, they need 2 tick signals and have a delay.

This would also allow advanced users to build compact setups with your mod and maybe one that provides wiring for the endergenic generator.

**Comment by McJty** [comment]
Implemented through the generic logic gate

**Comment by drrk** [comment]
Sorry, you say this is implemented - but I don't see any of the blocks that take two inputs, and thus allow creation of an NAND gate, which is the basis of all logic.  Am I missing something obvious?

**Comment by McJty** [comment]
The logic gate has three inputs and can combine those in any possible manner. It is for 1.10.2 only though

**Comment by drrk** [comment]
Hmm, we are running on a 1.10 server, which version of the mod was it introduced in?

**Comment by drrk** [comment]
No worries, I found it - just doesn't seem to appear on the docs I was looking at, Thanks :)
