### ISSUE TITLE
(Crash) Moving blocks with Builder

### ISSUE THREAD

**Issue by mouro001** [McJty/RFTools#1540]
I'm trying to move a build from one position to another.
The game its crashing way to often.
Crash Report: https://gist.github.com/mouro001/c26e1fdbe7c6d63e5f262e1aa8a32c7b
I'm trying to move a couple chisel blocks and i think thats about it.

**Comment by josephcsible** [comment]
Can you reproduce this with just McJtyLib and RFTools installed?

**Comment by andre-paulo98** [comment]
How about the mods that add the blocks i was trying to move?
________________________________
De: Joseph C. Sible <notifications@github.com>
Enviado: 1 de janeiro de 2018 23:34
Para: McJty/RFTools
Cc: André Paulo; Manual
Assunto: Re: [McJty/RFTools] (Crash) Moving blocks with Builder (#1540)


Can you reproduce this with just McJtyLib and RFTools installed?

**Comment by mouro001** [comment]
How about the modded blocks i was trying to move?

**Comment by josephcsible** [comment]
Yes, that's fine.

**Comment by josephcsible** [comment]
Any update on this?
