### ISSUE TITLE
died in collapsing world

### ISSUE THREAD

**Issue by jiuribu** [McJty/RFTools#1542]
can you change @killplayer to damage taken over time pls ?

its annoying when  you die for what ever reason game failed to load charge on dimmlet BEFORE it did check on something else and just throw @killplayer at player.

at least when this issue occurs player could use quick portal or gate or what ever to survive but if he gets insta killed even with extra healths it drives srsly nuts.

i checked many times if my dimplet is full of energy but game code , seems not do same thing.

**Comment by josephcsible** [comment]
I don't really understand the problem. Does the dimension you're going into have power but killed you anyway? If so, then you've found a serious bug and you should explain detailed reproduction steps. If not, then I fail to see anything wrong. Also, dimlets don't have a concept of energy, only dimensions do.
