### ISSUE TITLE
DialingDeviceDriver Transmitter List Dialed Always true

### ISSUE THREAD

**Issue by jobe1986** [McJty/RFTools#1544]
Simply put in the OpenComputers DialingDeviceDriver the "dialed" value for all listed transmitters is always "true" meaning the only way to get the true "dialed" state of the matter transmitter is using the MatterTransmitterDriver instead.

Also it would be nice to be able to determine (through MatterTransmitterDriver) what receiver the transmitter is dialed to.

**Comment by josephcsible** [comment]
Will be fixed in the next release.
