### ISSUE TITLE
rf monitor

### ISSUE THREAD

**Issue by closeshot** [McJty/RFTools#1548]
Is it possible to make the rftools monitor output a signal only when it reaches a % to have a block turned off like generator controller from deep resonance. I have it set at 95% and w/e it reaches it turns on and off repeatedly instead of letting the generator drain, say to 25%. This is for 1.12 ftb revelations 1.0.0

**Comment by McJty** [comment]
That's intentional. To do this correctly you need to use two power monitors. One to monitor > 95% and one to monitor < 25%. And then you can use (for example) the logic gate from rftools to combine the outputs
