### ISSUE TITLE
Builder only works facing east or west direction and modular storage only face north or south...1.12.2

### ISSUE THREAD

**Issue by jonabrv1965** [McJty/RFTools#1549]
rftools-1.12-7.23
mcjtylib-1.12-2.6.2
Forge 2582

I test in a creative world and can recreate this behavior. 

The modular storage, when placed points to south, and when rotated with a wrench only rotate to north.

**Comment by McJty** [comment]
I can't reproduce this. What other mods are present?

**Comment by jonabrv1965** [comment]
Here, but don't worry McJty, I know you are very busy, let me check (and detect) the offender mod and I let you know : 
[mods.txt](https://github.com/McJty/RFTools/files/1609029/mods.txt)

**Comment by jonabrv1965** [comment]
Ah.. I'm using forge 2582.

**Comment by jonabrv1965** [comment]
Gotcha... Forge 2582 is the guilty... testing with forge 2584...wait a minute...

**Comment by jonabrv1965** [comment]
Ok, my findings so far : 2582 makes the builder works bad, and the storage face south, as reported. 

With forge 2555 all works fine, with  2584 (the latest as of today) the builder works fine, but the storage still just face south or north only.... This was tested in a creative world with just rftools, xnet, mcjtylib.

I'm going to test with my main world. I'll let you know.

**Comment by jonabrv1965** [comment]
Confirmed, with forge 2555 in my survival world the builder and storage works ok... So. Should I report this in the forge issue tracker?

**Comment by josephcsible** [comment]
Not yet. It might be a bug in our mod that was revealed by an optimization they made; let me check that first.

**Comment by jonabrv1965** [comment]
Oki, let me know, :-)

**Comment by josephcsible** [comment]
I just tried Forge 2582, and I can reproduce the problem with the modular storage, but not with the builder. Looking into it now.

**Comment by jonabrv1965** [comment]
With the builder I'm using it in quarry mod with a clear, fortune card...

**Comment by josephcsible** [comment]
I narrowed down the Forge version that broke it. It works fine in 2575 but not 2576.

**Comment by josephcsible** [comment]
I don't see anything we're doing wrong, so I opened MinecraftForge/MinecraftForge#4659 explaining exactly what I think the problem is.

**Comment by josephcsible** [comment]
[This PR](MinecraftForge/MinecraftForge#4629) will fix it. If the looks don't bother you, you can ignore it, a it doesn't affect gameplay at all. If they do, just use 2575 until it merges, then update to whatever version it may be on.

**Comment by jonabrv1965** [comment]
Oki, I'll use 2575. Thank you Joseph!

**Comment by josephcsible** [comment]
@jonabrv1965 The fix was just merged, so you can update to 2585 now.

**Comment by jonabrv1965** [comment]
Excellent Joseph, McJty, thanks for the promptly support. Keep the great work and the great mods you made!
