### ISSUE TITLE
Add the ability for Dimension Enscriber to rename whats shown in RFTDIM LIST command.

### ISSUE THREAD

**Issue by mrdeadlocked** [McJty/RFTools#155]
When you rename a dimension tab to a better suited name it does not update in the rftdim list command. If this was implemented it would allow for a USER who has created dimensions to then 'sort' them out through naming. Then an ADMIN could come in look at RFTDIM LIST and be able to delete dimensions based off an informed decision. 

Example: Created DIM 'MDLTEST1'

Go into the DIM and notice its crap and I'm dieing from negative effects. Rename the DIM to 'DEATHPLZDEL'.

Admin comes on runs /rftdim list, they still see MDLTEST1 as the name of the dimension. If they'd be able to see the updated name, they could then know to delete that dimension.

**Comment by McJty** [comment]
Done and ready for next release.

**Comment by mrdeadlocked** [comment]
I love you. ^_^
