### ISSUE TITLE
Scanner modifier drop-downs don't do anything

### ISSUE THREAD

**Issue by etnpce** [McJty/RFTools#1552]
If I make a modifier, no matter what the drop-downs are set to, clicking "add" adds a slot->slot type.
This means I can't choose TE or liquid filters, and I can't remove things from the scan.

Seperate issues to avoid spamming: there doesn't seem to be any way to add liquid blocks to a filter, and any filter will not match liquid blocks in the scanner

**Comment by McJty** [comment]
Show me a screenshot of what you're trying to do?

**Comment by etnpce** [comment]
![image](https://user-images.githubusercontent.com/7939703/34647175-cc49cfe6-f338-11e7-80fc-d0c685149910.png)
![image](https://user-images.githubusercontent.com/7939703/34647182-f6c0c52c-f338-11e7-9c40-8b409a5ebde9.png)

No Matter what those two boxes say, the add creates a slot -> slot

**Comment by McJty** [comment]
And version of rftools?

Also what if you actually put a liquid in the slot before pressing add?

**Comment by etnpce** [comment]
I'm using the FTB Direwolf20 1.12 pack. It has version 7.15 of rftools.

How do you put a liquid into the slot?  A bucket does not work

**Comment by McJty** [comment]
Um it should. What happens if you try to put in a bucket?

**Comment by etnpce** [comment]
It creates a slot->slot with the bucket on the left, which never matches any blocks.
Note that this is an issue with the other settings (TE,Ore, and Void) as well

**Comment by McJty** [comment]
Hmm ok you are right. This got broken somehow. I'll fix

**Comment by McJty** [comment]
Ok, stupid error. Will be fixed next release
