### ISSUE TITLE
Config option for builder quarry

### ISSUE THREAD

**Issue by 2001zhaozhao** [McJty/RFTools#1556]
Hi, currently you can use an item filter in a builder quarry to filter the mining by type of block, which can be abused to make the builder mine ores only and produce insane amounts of ores for the price. However, if I increase energy costs, people not using the filters would suffer too much. I looked in the config and there is no way to block the player from using a filter only when they use the quarry shape card (or even when they use a builder in general). Can you add such a config option?

**Comment by McJty** [comment]
I think you overlooped this option:

    # RF per block that is skipped (used when a filter is added to the builder)
    I:builderRfPerSkipped=50

By raising that config you can make it so that scanning blocks (but not doing anything with them) costs more. That way the cost of a filtered quarry can be made to match the cost of a normal builder operation
