### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by YeahChloe06** [McJty/RFTools#1557]
Please Help I would like to use these mods together but my minecraft crashes after loading the mods :/ Here is the Minecraft Crash Report: (Note: I use Minecraft Forge-1.10.2-12.18.3.2511 win)
--- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/12/18 8:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
Caused by: java.lang.NoSuchMethodError: mcjty.lib.container.BaseBlock.setRegistryName(Ljava/lang/String;)Lnet/minecraftforge/registries/IForgeRegistryEntry;
	at mcjty.lib.container.BaseBlock.<init>(BaseBlock.java:56)
	at mcjty.lib.container.GenericBlock.<init>(GenericBlock.java:71)
	at mcjty.rftools.blocks.GenericRFToolsBlock.<init>(GenericRFToolsBlock.java:32)
	at mcjty.rftools.blocks.generator.CoalGeneratorBlock.<init>(CoalGeneratorBlock.java:38)
	at mcjty.rftools.blocks.generator.CoalGeneratorSetup.init(CoalGeneratorSetup.java:16)
	at mcjty.rftools.blocks.ModBlocks.init(ModBlocks.java:37)
	at mcjty.rftools.proxy.CommonProxy.preInit(CommonProxy.java:113)
	at mcjty.rftools.proxy.ClientProxy.preInit(ClientProxy.java:49)
	at mcjty.rftools.RFTools.preInit(RFTools.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 295005240 bytes (281 MB) / 745775104 bytes (711 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_D7 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.1.3.201} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.201-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	alt{1.06} [Additional Loot Tables] (AdditionalLootTables_1.10.2-1.06.jar) 
	UCH	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCH	betterquesting{2.3.234} [Better Questing] (BetterQuesting-2.3.234.jar) 
	UCH	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCH	chancecubes{1.10.2-3.0.1.207} [Chance Cubes] (ChanceCubes-1.10.2-3.0.1.207.jar) 
	UCH	ChestTransporter{2.5.18} [Chest Transporter] (ChestTransporter-1.10.2-2.5.18.jar) 
	UCH	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UCH	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCH	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCH	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCH	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCH	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCH	dbrownutil{1.1} [Dbrown55 Util Mod] (dbrownutil-1.1.jar) 
	UCH	concrete{1.2} [1.12 Concrete] (concreteMod-1.2.jar) 
	UCH	modcurrency{1.10.2-1.2.2} [Good Ol' Currency Mod] (Currency-1.10.2-1.2.2.jar) 
	UCH	duckcraft{1.0.3} [DuckCraft] (duckcraft-1.10.2-1.0.3.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCH	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.2.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UCH	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCH	hatchery{0.2.10} [Hatchery] (hatchery-1.10.2-0.2.10.jar) 
	UCH	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCH	hats{6.0.0} [Hats] (Hats-1.10.2-6.0.0.jar) 
	UCH	hermitron{0.2.18} [Hermitron] (hermitron-1.10.2-0.2.18.jar) 
	UCH	hopperducts{1.4.8.1} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.1.jar) 
	UCH	InventoryPets{1.4.9.9} [Inventory Pets] (inventorypets-1.10-1.4.9.9.jar) 
	UCH	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCH	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCH	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCH	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCH	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCH	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCH	mob_grinding_utils{0.1.8.22} [mob_grinding_utils] (MobGrindingUtils-0.1.8.22.jar) 
	UCH	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCH	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCH	morechickens{1.1.6} [More Chickens] (MoreChickens-1.10.2-1.0.11.jar) 
	UCH	mysticalagriculture{1.5.9} [Mystical Agriculture] (mysticalagriculture-1.10.2-1.5.9.jar) 
	UCH	oreexcavation{1.2.84} [OreExcavation] (OreExcavation-1.2.84.jar) 
	UCH	ProjectE{1.10.2-PE1.3.1} [ProjectE] (ProjectE-1.10.2-PE1.3.1.jar) 
	UCH	ranchablefluidcows{1.10.2-1.2.0B1} [Ranchable Fluid Cows] (RanchableFluidCows-1.10.2-1.2.0B1.jar) 
	UCH	bq_rf{2.3.26} [RF Expansion] (RFExpansion-2.3.26.jar) 
	UCE	rftools{7.16} [RFTools] (rftools-1.1x-7.16.jar) 
	UCH	bq_standard{2.3.131} [Standard Expansion] (StandardExpansion-2.3.131.jar) 
	UCH	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCH	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UCH	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.28-universal.jar) 
	UCH	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.17-universal.jar) 
	UCH	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCH	usefulnullifiers{1.2.1} [Useful Nullifiers] (usefulnullifiers-1.2.1.jar) 
	UCH	ViewEMC{v5} [View EMC] (ViewEMC-1.10.2-v5.jar) 
	UCH	wailafeatures{0.3.1.13} [WAILA Features] (WAILA-features-1.10.2-0.3.1.13.jar) 
	UCH	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCH	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCH	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCH	moofluids{1.10.2-1.7.02.12b} [Moo Fluids] (MooFluids-1.10.2-1.7.02.12b.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  codechicken.nei.asm.NEITransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.66' Renderer: 'GeForce GT 705/PCIe/SSE2'
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	minefactoryreloaded: -[1.10.2]2.9.0B1-226
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                  * An unsupportted RF API is installed (1.7.0 from (guessing) jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/sjac2_000/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 10
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.66
	OpenGlRenderer: GeForce GT 705/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by McJty** [comment]
Do you have compatlayer and McJtyLib and if so what versoins?

**Comment by YeahChloe06** [comment]
I have mcjtylib-1.1x-2.5.1 and compatlayer-1.1-0.3.0

**Comment by McJty** [comment]
That version number for compatlayer is invalid. Can I get the correct one? It is rather important

**Comment by YeahChloe06** [comment]
that is the version it says in my mods folder

**Comment by McJty** [comment]
You made a typo because that version does not exist. Please give me the full version (screenshot or copy/paste if neeeded)

**Comment by YeahChloe06** [comment]
![image](https://user-images.githubusercontent.com/35367930/34871486-ef6227a0-f7e1-11e7-8734-0d0944bd45b1.png)
and
![image](https://user-images.githubusercontent.com/35367930/34871517-0b9901fa-f7e2-11e7-935a-be51bd9ff0cd.png)

**Comment by McJty** [comment]
Hmm ok. That's the correct version. I need to see the full modlist btw. Can you do a copy/paste to bpaste.net and give me that? Thanks

**Comment by YeahChloe06** [comment]
Here is this good?
https://bpaste.net/show/eec60302cd49

**Comment by YeahChloe06** [comment]
Also here are the forge version (from Launcher)
FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar)

**Comment by McJty** [comment]
Hmm. That list is not complete. I don't see compatlayer and mcjtylib there. Can you just post a directory listing of your entire mods folder?

**Comment by YeahChloe06** [comment]
sorry that was my fault i copied and pasted from launcher and probably forgot the core mods and such

**Comment by josephcsible** [comment]
Last time I saw a crash like this, it was because there were multiple versions of McJtyLib or CompatLayer installed. Can you make sure that you only have one of each of them?

**Comment by McJty** [comment]
That's why I was asking for the full list (which I have still not seen)

**Comment by YeahChloe06** [comment]
there is only one version of each

**Comment by McJty** [comment]
I'm still interested in a complete list. Also to see other core mods and such

**Comment by YeahChloe06** [comment]
you should be able to see all the mods in the crash report

**Comment by YeahChloe06** [comment]
![image](https://user-images.githubusercontent.com/35367930/34875921-6796a0aa-f7f3-11e7-9615-07151df32781.png)

**Comment by josephcsible** [comment]
You can't. Not every file has an @Mod annotation. In particular, you can't see McJtyLib or CompatLayer.

**Comment by McJty** [comment]
I have no clue what's wrong though

**Comment by YeahChloe06** [comment]
i have deleted some mods and now it is a java heap space error

**Comment by josephcsible** [comment]
Can you try creating a new instance with just McJtyLib, RFTools, and CompatLayer, and see if it works? If so, keep adding your other mods until you find which one breaks it.

**Comment by josephcsible** [comment]
Please post the new full crash report.

**Comment by McJty** [comment]
how much memory are you allocating for Minecraft? Also are you using 64-bit java?

**Comment by YeahChloe06** [comment]
yeah i am using 64-bit

**Comment by YeahChloe06** [comment]
New Crash Report
https://bpaste.net/show/9e6ac82a8465

**Comment by YeahChloe06** [comment]
i am allocating 1GB

**Comment by josephcsible** [comment]
Yeah, that error just means you aren't allocating enough. Add more.

**Comment by McJty** [comment]
That's probably the reason. 1GB is not enough memory for 1.10. You'll need at least 3GB to get things working properly with the mods you have listed

**Comment by YeahChloe06** [comment]
i cant, i have tried but this computer cant allocate enough

**Comment by YeahChloe06** [comment]
with deleting mods the launcher loads fine but it crashes when trying to create a world

**Comment by McJty** [comment]
Then you can't run 1.10 with these mods. 1.10 is memory hungry. Not much that can be done about that.

FoamFix helps a little but it will still not be enough

**Comment by YeahChloe06** [comment]
okay
thanks anyway...

**Comment by josephcsible** [comment]
Either buy more RAM, add more swap space (this will be slow though), close the rest of your programs so there's more for Minecraft, or cut back your mod list.

**Comment by YeahChloe06** [comment]
thats what i usually have to do. cut em back
