### ISSUE TITLE
1.12.2 RFTools Dimensions Dimensional shard ore dimlet generating stairs from forestry instead

### ISSUE THREAD

**Issue by aerde** [McJty/RFTools#1563]
I've found dimlet for Dimensional shard ore, and tried to combine it with terrain dimlet. Used flat terrain dimlet, islands, solid, and every single time i get worlds, made of forestry's wenge stairs. Tab with only dim. shards ore seems not use this dimlet at all.
Here is what this dimlet is, as crafttweaker says:
 <rftoolsdim:known_dimlet:2>.withTag({dkey: "rftools:dimensional_shard_ore@1"})
I'm running LAN singleplayer on Modern Skyblock 2 modpack.
mcjtylib-1.12-2.6.2
rftools-1.12-7.23
rftoolsdim-1.12-5.50
forestry_1.12.2-5.7.0.234
forge 14.23.1.2587

**Comment by aerde** [comment]
I've just checked without forestry, and it just replaces orbs or tendrils with air or some other block, like dirt, prismarine, etc. With only RFTools and COFH mods, it works as intended. Seems some weird id conflict is happening. But it's over 100 mods, so I even don't know where to look first to find conflict =(

**Comment by josephcsible** [comment]
Try doing a binary search. It'll only take 7 or 8 tries to find which one it is.

**Comment by aerde** [comment]
Ok, I've done search, and found 16 mods either replacing dimension shard ore with other vanilla or modded block, or replacing it with air. And now the point, where I don't know how to fix it not deleting mods, cause modpack does have quest progression. Here are the list:
EnergeticSheep-1.12.2-1.1.1
environmentalmaterials-1.12.2-1.0.6a
environmentaltech-1.12.2-2.0.6b
etlunar-1.12.2-2.0.6a
EvilCraft-1.12.2-0.10.44
extendedcrafting-1.12-1.1.3
ExtremeReactors-1.12.2-0.4.5.45
generators-0.9.20.12-mc1.12.2
Immersive HempCraft-1.12-0.0.4.0
industrialforegoing-1.12.2-1.7.0-114
industrialmeat-1.12-1.0.2
IntegratedDynamics-1.12.2-0.10.1
IntegratedTunnels-1.12.2-1.4.1
IntegrationForegoing-1.12-1.4
ironchest-1.12.2-7.0.34.820
valkyrielib-1.12.2-2.0.6b

**Comment by josephcsible** [comment]
Just forget the progression for now, for the sake of figuring out which mod is at fault. Once you get it down to one mod that causes it, we should be able to easily fix it.

**Comment by aerde** [comment]
I'll try to make completely clear copy of modpack in the morning, without crafttweaker scripts, and maybe, catch problem mod. I have a slight suspicion that it could be the progression, that messes it all up.

**Comment by aerde** [comment]
I did it!
It was RebornTeam mods, probably their coremod, RebornCore. There are 3 mods, dependant on this coremod in pack I'm playing, so I can't check if it is coremod or actual mods. Here are names and versions of mods, causing problem:
RebornCore-1.12.2-3.6.2.187-universal
SolarFluxReborn_1.12.2-3.42r
StevesCarts-1.12.2-2.4.16.81
TechReborn-1.12.2-2.11.1.420-universal

**Comment by josephcsible** [comment]
Awesome that you got it that far! We should be able to figure it out from there.

**Comment by aerde** [comment]
Thanks! Will be waiting for fix =)

**Comment by josephcsible** [comment]
Note that Solar Flux Reborn is actually a HammerCore mod, not a RebornCore mod. What version of HammerCore did you experience this on?

**Comment by josephcsible** [comment]
Also, I can reproduce this with all of Modern Skyblock 2, but not when I disable all mods except the ones you listed. Can you post a mod list of everything that you left enabled?

**Comment by aerde** [comment]
Here is list of mods when problem is present: https://gist.github.com/aerde/08b944b30c9af29f20c917a230475c9d

It's been a while, since I've began testing, so some mods got updated. And probably, I messed up, and in the list are couple of mods I didn't include in testing... I'll check this tomorrow.

I've blamed NotEnoughIDs too, but without it, modpack doesn't work. And it doesn't seems to have a config file.

**Comment by josephcsible** [comment]
That's a lot of mods still. How did you narrow it down to a *Reborn mod with all of those still present?

**Comment by josephcsible** [comment]
I think it is a NEID problem. It should be fixed in the next release of RFTools Dimensions.

**Comment by aerde** [comment]
Cool! Thanks a lot) This problem was draining my powers))
