### ISSUE TITLE
Missing crafting recipes for terrain dimlets in SF3

### ISSUE THREAD

**Issue by Maverik7773** [McJty/RFTools#1566]
As the title says, I'm playing Sky Factroy 3 and I cannot make anything other than a "void" terrain dimlet in the workbench. I have already changed the cfg file so that new dimensions actually generate land, so that's not the problem. I've also recovered several other types of terrain dimlets from exploring random dimensions, like solid, nearlands, invertigo, etc. But the recipes to _make_ new terrain dimlets simply aren't in the workbench. Is there a setting somewhere in a some other file that I need to change?

**Comment by McJty** [comment]
Hmm are you sure? Can you show a screenshot of the dimlet workbench with you hovering over one of the terrain dimlets?

**Comment by Maverik7773** [comment]
This is all I can find in the workbench.
![image](https://user-images.githubusercontent.com/17849796/35031965-b5f1f6ac-fb2a-11e7-8308-49ba67f36c84.png)

Also, I just found out that there is a separate section for RFTools Dimensions. Sorry about that. I can move this post if necessary.

**Comment by McJty** [comment]
It's ok. But you said you have found some other terrain dimlets? Can you show these in a screenshot?

**Comment by Maverik7773** [comment]
Kinda hard to show you all the different types without gobs of screen shots; let me know if you need more though. 

![image](https://user-images.githubusercontent.com/17849796/35032491-ba1f4106-fb2c-11e7-9e1e-f0e8490264ab.png)

They say that they are all black-listed. All except void anyway. I tried looking through mod files, starting with RFTools, but I couldn't find anything that way either.

**Comment by McJty** [comment]
They will be blacklisted in the config file dimlets.json

**Comment by Maverik7773** [comment]
I don't entirely know what I'm looking at in this file... or what to change. I can't find anything in the file with any of the blacklisted dimlet names. Could it be that they were deleted from the file by BaconDonut? What am I looking for? Also, thank you so much for the help so far!

**Comment by McJty** [comment]
Can you show me the file?

**Comment by Maverik7773** [comment]
I can zip it; Github says I can't attach a .json. 
[dimlets.zip](https://github.com/McJty/RFTools/files/1638192/dimlets.zip)

**Comment by Maverik7773** [comment]
Unless you want me to post the contents of the file in the chat, but that's a little long...

**Comment by McJty** [comment]
Hmm there is no blacklisting in this. Is this single player? Not sure how SF3 actually disables these dimlets then. Very weird

**Comment by Maverik7773** [comment]
No, It's multiplayer. That is the file from the server I run. Could the blacklisting be client-side? I wouldn't think so, but I'll check anyway.

**Comment by Maverik7773** [comment]
Nope. Well, thanks for helping me anyway. I guess I'll just have to keep finding dimlet buildings and hope to get a terrain dimlet that I want.

**Comment by McJty** [comment]
Ah in that case. You have to update the configs on both sides. Are you doing that?

**Comment by McJty** [comment]
Dimlets you find that are blacklisted will most likely not work

**Comment by Maverik7773** [comment]
Hm. Alrighty, let me update my client then. Hang on...

**Comment by Maverik7773** [comment]
Aaaaaand they're showing up now. _sigh_ Thank you again for all the help. I hate it when the solution is something simple.
