### ISSUE TITLE
RFTools teleport out of The End semi-fails

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#157]
Hi McJty,

My friend and I popped into the End today and slew the dragon most mightily. I then set up an RFTools teleporter (tx, rx, dial) powered by a tessie. We've been using RFT happily for some time.

I dialled my home base, it reported OK so I stepped through. Minimap reported my location around x2z39y64 which is a place about 100 blocks from world spawn and 4 blocks underground. It's also about 1200 blocks from the intended destination. No world render, just sky and abyss. I waited about 2 mins for my client to catch up with the server (on my LAN) but nothing came through. I used the minimap teleport to go home and after waiting another 20 secs or so, it hadn't improved so I relogged.

I went back to the end and tried again with the same results, requiring another relog. I hadn't teleported after the second time so I was immediately suffocating in stone. The attached log covers the period between the first and second relogs. http://pastebin.com/RRRyCzve

Bug or just MC borking?

Cheers

FTB Infinity 1.3.4
RFT 2.71

**Comment by McJty** [comment]
This has been reported before but I haven't yet had a chance to investigate. Apparently teleporting from the end seems problematic for some reason. I will check this out.

**Comment by xenoflot** [comment]
Ah ok. Close this ticket if you already have one open then.

Thanks for the quick reply!

**Comment by McJty** [comment]
Fixed in 2.83

**Comment by xenoflot** [comment]
Bravo!
