### ISSUE TITLE
Rftools requiring a mod called forge that doesn't seem to exist

### ISSUE THREAD

**Issue by treeninja222** [McJty/RFTools#1570]
my minecraft keeps saying i need a mod called forge but i can't find it anywhere

**Comment by josephcsible** [comment]
"forge" is just Minecraft Forge, not its own mod. My best guess is that you have a mismatch between the mod is version and Minecraft's version. Check that. If it's not that, please post a full log.

**Comment by ktole1999** [comment]
download and install minecraft forge based on the version its requesting.

**Comment by josephcsible** [comment]
He already has Forge. It's actually the thing that's giving him the message that "forge" is missing.

**Comment by ktole1999** [comment]
i believe thats what i said  *shrug*
