### ISSUE TITLE
[1.12.2] Crash at login to server.

### ISSUE THREAD

**Issue by xannor** [McJty/RFTools#1574]
I recently placed a random things advanced redstone interface behind an rftools elevator block (to open some trapdoors when the elevator is on that floor) and after logging out I cannot log back in. My client crashes with the following crash report:
https://gist.github.com/xannor/c4c07055867b72a949c0e6b612c3cfe7

The server does not see nor log any exception other than my sudden disconnect.

Custom ModPack --
Forge: 2585
McJTyLib: 2.6.2
RFTools: 7.23
RandomThings: 4.1.2

Update:
I could MCEdit and remove (could not get copy/paste to work) the advanced redstone interface to log back in.

**Comment by josephcsible** [comment]
Same as #1588. Will be fixed in the next release.
