### ISSUE TITLE
ConcurrentModificationException with Crafters

### ISSUE THREAD

**Issue by MaPePeR** [McJty/RFTools#158]
https://gist.github.com/MaPePeR/e1d92741f2635cdab1f5

This happens when i teleport to the Pathfinder-Dimension, that has some Crafters Placed.

The Crafters are Tier3, but should NOT be running! They have no automation!

The first one has ProjectE Philosopher-Stone Recipes to craft from Emerald->Diamond->Gold->Iron->Iron Blocks and the second one has Basic Capacitors, Double Layer Capacitors, Octadic Capacitors and Gold->Gold Nuggets.

After restarting the pack and loading the world i'm in the dimension just fine.

The Pack is Pathfinder with RFtools updated to 2.76

EDIT: when i tried to Yeta-Wrench them they disappeared.

**Comment by McJty** [comment]
The bug with the disappearing crafter after wrenching has been fixed in 2.77. The other exception is weird. I see no reason why that could even happen.

**Comment by McJty** [comment]
Closing for now
