### ISSUE TITLE
Material Absorber bug

### ISSUE THREAD

**Issue by jmac460** [McJty/RFTools#1580]
When placed on top of the minecraft ore, it refuses to pick up and absorb the redstone blocks. however, if i log out and log in, and place the block again it will pick up only a few, then stops again. This is for 1.10.2 and Project Ozone Lite.

**Comment by josephcsible** [comment]
Single-player or server? Does it just happen for redstone ore (remember, they're special since they have a lit and an unlit version), or does it happen for other blocks too? What version of Project Ozone Lite are you on? Have you made any changes to the pack?
