### ISSUE TITLE
Cannot place wireless transmitter and receiver on the wall  

### ISSUE THREAD

**Issue by abdullamu** [McJty/RFTools#1581]
As the title says after recent update, the block always sit on air when I want to place it on wall.

**Comment by josephcsible** [comment]
I assume you mean RFTools 7.24. What version of McJtyLib are you on? If not 2.6.3, try updating.

**Comment by abdullamu** [comment]
Its 2.6.3 , i always update to the latest through twitch client.
Its annoying this problem bcz you cannot use it with blocks above the receiver or below, The same for the transmitter.

**Comment by josephcsible** [comment]
Will be fixed in the next release of RFTools.

**Comment by abdullamu** [comment]
Thank you for the fix it helped but not every time I log in it reset to the sitting position.

**Comment by josephcsible** [comment]
Okay, it should be fixed for real this time.
