### ISSUE TITLE
1.12.2 Powercell linking card not working

### ISSUE THREAD

**Issue by Nickiel12** [McJty/RFTools#1589]
I am in the 1.12.2 modpack called "Flameforged" and i tried to link 2 basic powercells and I had the same problem as [this guy](https://github.com/McJty/RFTools/issues/1031). The rftools version is 7.23

**Comment by Nickiel12** [comment]
also when I do what 'Optimoos' said he did in that string, the link didn't work. there was a card with link id 11 in both of the upper right slots, and no energy was being transmitted

**Comment by josephcsible** [comment]
Can you post a video or GIF of exactly what you're doing? Start by taking fresh powercells and linking cards out of the creative inventory, or crafting them.

**Comment by Nickiel12** [comment]
https://youtu.be/cqwHv2CrK9U

and if you say 'why didn't you put it in the link slot' that makes it "[UNLINKED}"

**Comment by McJty** [comment]
You are using the wrong slot for the powercard. The top right slot is for charging items that use RF. Put the link card in the top left slot to assing an ID. Put it in the bottom right slot to copy an ID.
