### ISSUE TITLE
Crash when creating dimension

### ISSUE THREAD

**Issue by KufrA** [McJty/RFTools#1598]
Tried to create a dimension with Flat+RedstoneBlock Dimlets. Crashes client not server.

[crash-2018-01-30_21.26.19-client.txt](https://github.com/McJty/RFTools/files/1679251/crash-2018-01-30_21.26.19-client.txt)
Could be some crossmod issue, cannot tell myself. Think it was when naming the DIM that the crash occured. Tried writing "Redstone" crashes on "t".

**Comment by josephcsible** [comment]
That fix will make it not crash, but something else is wrong if the thing that was null was able to be null. The next release will logspam (but not crash) if it detects that problem.
