### ISSUE TITLE
Issue with syringes.

### ISSUE THREAD

**Issue by bigdogdk** [McJty/RFTools#160]
If you attempt to collect wither skeletons with a syringe it gives skeleton instead.

**Comment by McJty** [comment]
Yes I know. Skeletons are very special in Minecraft. A Wither skeleton is actually a normal skeleton. It just becomes a wither skeleton if you spawn it in the nether. I don't know yet how to solve this problem.

**Comment by SirKastros** [comment]
talk to skyboy he might be able help you with that because he maintains MFR and there is code in the mod that allows spawning of wither skeletons using the auto spawner and safari nets to collect them in to use with the auto spawner.

**Comment by ShadwDrgn** [comment]
This being still open I assume you haven't quite resolved this yet, and I love your mod. There's a method in skeleton to check to see if the skeleton is a wither skeleton. I suggest doing a one-off whenever the syringe is used to check for that. If it is, you'll have to write one-off checking in each tool that uses the syringes :( it's annoying and complicated, but that's the way of minecraft!

**Comment by zack11111111** [comment]
If its any help, Wither skeletons have the NBT data "SkeletonType" set to 1

**Comment by McJty** [comment]
Should work fine in 1.10.2
