### ISSUE TITLE
Regen 3 consuming 0 rf/t

### ISSUE THREAD

**Issue by dahjin** [McJty/RFTools#161]
is this suppost to happen and is there a way to change the amount of rf modules consume?
![2015-04-22_19 34 47](https://cloud.githubusercontent.com/assets/8744819/7287779/c5772f2a-e926-11e4-9b0d-90bb717f76fa.png)

**Comment by McJty** [comment]
The reason it is consuming 0 RF/tick is that it is not working. You are not getting the buff because it is too expensive. i.e. the machine can't actually get enough power to give you the effect. Try giving more power.

**Comment by dahjin** [comment]
no im getting the effect if i sit on topof it i get regen 3 and saturation

**Comment by dahjin** [comment]
![2015-04-22_23 10 26](https://cloud.githubusercontent.com/assets/8744819/7289919/f2a415bc-e944-11e4-8d39-b065bf7e1b62.png)
![2015-04-22_23 10 34](https://cloud.githubusercontent.com/assets/8744819/7289920/f5385054-e944-11e4-937e-8ebded4c7f84.png)

**Comment by McJty** [comment]
Ah, well I see. You set the range and area VERY low so it is actually consuming 0 RF/tick because the RF consumption depends on the area that is covered. I'll change it to add a small offset so it can never go below some low value.

**Comment by McJty** [comment]
2.80 fixes this
