### ISSUE TITLE
Crashing while building a server (loading world)

### ISSUE THREAD

**Issue by flayner2** [McJty/RFTools#1610]
[crash_log](https://gist.github.com/flayner2/f29f7aa824374b474959f283b40dea18)

This is the crash log of my server. I try to start the server on a private host and, before building the world, it crashes with this log. The log suggests that McjtyLib and RFTools may be involved and, when I remove both and all dependents (Dimensions and Control), it works perfectly. Any idea of why it is crashing? Would downgrading everything for 1 version work?

**Comment by josephcsible** [comment]
That's an OutOfMemoryError. See if allocating more RAM fixes it.
