### ISSUE TITLE
Monsters from mob dimlets not spawning

### ISSUE THREAD

**Issue by IN5ANE** [McJty/RFTools#1618]
Hi there,

I am playing on minecraft version 1.7.10,  Forge version 1.7.10-10.13.4.1614, RFTools version 4.23.
I tried creating worlds with certain mobs in them. Most favorably the ender dragon ofc. But all of these worlds didn't spawn the dragon at all. I also tried it with different mob types, like Blizz, Slimes etc. with no success. I tried this with relatively specified worlds like "no effect, always noon, material end stone /obsidian/clay, special peaceful / no peaceful ...." aswell as random worlds with just the mob dimlet of the dragon inside. Also I tried void worlds to see if it was a problem with the height of the dragons spawning.

So far I couldnt get any specified mob to spawn in the rftools worlds. I am playing on my own server with the after humans modpack and some extra mods. Idk if mods like Mho's creatures could cause these issues or if its a problem with the config settings. If you guys have any ideas please let me know :)

**Comment by josephcsible** [comment]
Minecraft 1.7.10 is no longer supported.
