### ISSUE TITLE
Shape card (Place liquids) doesn't work

### ISSUE THREAD

**Issue by Jason1122** [McJty/RFTools#1620]
I am running FTB Revelation with rftools-1.12-7.27.

First, there seems to be no recipe for Shape card (Place liquids), when I click on it in JEI it doesn't show me anything. I couldn't find any recipe for shape_card with id 10 in src/main/resources/assets/rftools/recipes, maybe this is the problem.

Second, it doesn't work. I place power source, a builder with a tank (tried different tanks, icl. quartz and deepresonanse tank) filled with water on top of it, configure the card, as usual, place it inside, pull the lever but nothing happens. The guide shows me correct blue outline, but nothing gets placed anywhere.

**Comment by McJty** [comment]
Show me some screenshots

**Comment by Jason1122** [comment]
https://imgur.com/a/Sn2eP
When I turn it on it shows "Progress" for a moment, but nothing happens.

**Comment by McJty** [comment]
You have FTB Utilities? Make sure the 'fake player' option is enabled

**Comment by Jason1122** [comment]
https://imgur.com/a/nBl2X
Do you mean "Fake Player Status" option? I've tried to change it, still nothing.

**Comment by Jason1122** [comment]
I have removed all mods, except DeepResonance (for tank), JEI and OneProbe and reset configuration. Still doesn't work. Here is the full list of mods:
deepresonance-1.12-1.6.0.jar
ElecCore-1.12.2-1.8.434.jar
jei_1.12.2-4.8.5.138.jar
mcjtylib-1.12-2.6.3.jar
rftools-1.12-7.27.jar
theoneprobe-1.12-1.4.19.jar

Forge ver. 14.23.1.2601

**Comment by Naddox** [comment]
Can confirm this is not working for ver1.12.7.27. Tried multiple tanks and nothing. Build acts like its placing the fluids but nothing actually gets placed. Fake player is enabled. Even tried unclaiming the chunks to see if that was the issue.
Running forge 14.23.1.2590

**Comment by josephcsible** [comment]
For some reason, this if statement never seems to be true when using a fluid placer but not support/preview mode:
https://github.com/McJty/RFTools/blob/a8566ce5d44d2a1275b07ed9d235834449309573/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java#L910
I'm going to start looking into why not.

**Comment by josephcsible** [comment]
Ah, this is why:
https://github.com/McJty/RFTools/blob/a8566ce5d44d2a1275b07ed9d235834449309573/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java#L897
https://github.com/McJty/RFTools/blob/a8566ce5d44d2a1275b07ed9d235834449309573/src/main/java/mcjty/rftools/items/builder/ShapeCardItem.java#L633-L635
The fluid placer isn't a quarry card, but it also isn't a "normal" shape card. That check should be changed to more like this one:
https://github.com/McJty/RFTools/blob/a8566ce5d44d2a1275b07ed9d235834449309573/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java#L946
Fix coming right up.

**Comment by josephcsible** [comment]
This will be fixed in the next release. As a workaround until then, just enable support/preview mode while using the fluid placer.
