### ISSUE TITLE
[Bug] 1.12.2 SMP Elevator stops recognizing or moving platform

### ISSUE THREAD

**Issue by Darklordiablo** [McJty/RFTools#1623]
Hi,

I built an elevator shaft which was working fine, but after a server reboot, the platform refused to move (the bottom elevator was powered)
So I rebuilt the platform at the bottom, and now the screens don't show where the platform is (but still show what elevator levels are in the shaft) and all elevators on the server refuse to move anything.

Several server reboots and several attempts at rebuilding the elevator have done nothing to remedy the problem.

**Comment by josephcsible** [comment]
What version of RFTools? Anything relevant in the log?

**Comment by Darklordiablo** [comment]
We're using 7.23; it's part of the Revelation FTB pack.
I thought that that may have been the case, but I couldn't find reference to it.

Thanks!
