### ISSUE TITLE
Endergenic Generators are processed starting from injector instead of last pearl

### ISSUE THREAD

**Issue by romanticjo** [McJty/RFTools#1625]
The list of TE to process is built starting with the injector.  Building the list in this manner makes it impossible to consistently process all `pearl arrived` events on the same tick if a pearl reaches the endergenic generator selected as the head of the todoEndergenics.  In practice, this makes it necessary to set the timings for that generator off-by-one.

**Comment by josephcsible** [comment]
d640206 and 00aff56
