### ISSUE TITLE
RF Network Monitor doesn't display after update

### ISSUE THREAD

**Issue by Rixxaw** [McJty/RFTools#1628]
After I updated FTB Revelation from 1.3 to 1.5 (RFTools version 7.23 - 7.27)   the RF Network Monitor no longer displays power grid, and sometimes will not pull any info from machines.  Blank UI when right clicking on Machines inconsistent sometimes it works, and sometimes it doesn't.

As a side not it also causes lots of graphics glitches all over the base while in your hand.  It will occasionally work for a few blocks / part of your network.

I looked through change logs and in version 7.24 you you / Joseph mentions Refactoring, also there is a commit about compressing PNG files?   It could be an issue with my world, I'd have to go creative and spawn in some stuff, which I'll do after I get this posted up. (Takes about 30-45 minutes to load FTB modpack so if you will tell me what info you want me to gather I can snag it for you all at once instead of spending all weekend popping back and forth.

I just loaded my Previous world Version ( Revelation 1.3 / RFTools 1.12-7.23)  and Took a Screenshot of the RF Monitor at work  (it works perfectly in this version )

![2018-02-09_18 11 40](https://user-images.githubusercontent.com/17864718/36055823-d78c0eea-0dc4-11e8-9240-eb84d98c7569.png)

And on my new World updated to ( Revelation 1.5 / RFTools 1.12-7.27)  Here is the same screenshot roughly : 

FML   8.0.99.99

RFTools 1.12-727

Minecraft 1.12.2

![2018-02-09_18 26 32](https://user-images.githubusercontent.com/17864718/36056098-3143cdf4-0dc7-11e8-8a6a-ce7b72fe2668.png)

**Comment by Rixxaw** [comment]
I removed my Draconic Energizer and it helped some, but I checked the logs and its rather full of stuff about RFTools throwing null pointers, and having GL rendering issues.

[https://pastebin.com/QQrsiUS1](url)

**Comment by Rixxaw** [comment]
Just to clarify I did try removing the resource pack and restarting the game and it didn't help.

**Comment by josephcsible** [comment]
I think this is actually Extra Utilities' fault. Did Revelation update Extra Utilities between your two versions? I'm any case, here's some things to try (back up your world before doing any of it):
1. If they updated Extra Utilities, put it back to its old version. If this fixes the problem, it's their fault. If not, keep going.
2. Remove Extra Utilities entirely. If this fixes the problem, it's their fault. If not, keep going.
3. Downgrade the pack, then update just McJty and RFTools. If this fixes the problem, some other mod is at fault. Try a binary search to figure out which one.

Let me know what you find out.

**Comment by Rixxaw** [comment]
Yeah I tend to agree it appears Extra- Utilities is doing some strange things.

**Comment by josephcsible** [comment]
What were the result of those tests?

**Comment by Rixxaw** [comment]
So yes they did update Extra Utilities from 1.7.2 to 1.7.3  And so I rolled XUtils2 back to 1.7.2 and it resolved the issue.


![2018-02-10_07 59 23](https://user-images.githubusercontent.com/17864718/36062776-9885279e-0e38-11e8-8113-9a1afa7858d5.png)

**Comment by josephcsible** [comment]
Yeah, there's nothing we can do about this. Just report it to their tracker.
