### ISSUE TITLE
Builder will not place Redstone dust when copying a space card.

### ISSUE THREAD

**Issue by IMarvinTPA** [McJty/RFTools#1638]
Issue description:  Redstone dust placed in the area copied by a space card does not get placed when copying.

Steps to reproduce: 

Place a block of iron.  Put a speck of redstone dust on it.  Do the stuff to put that in a space chamber, set up a card, do all the things, let the builder try to build the thing.  (Attempting to automate compact machines.)

Versions:
* Minecraft: 1.12.2
* Forge: 2607
* McJtyLib: 2.6.3
* RFTools:  1.12-7.28

Possibly incompatible mods: Not sure.

**Comment by josephcsible** [comment]
Will be fixed in the next release (by 5ad7ad5).
