### ISSUE TITLE
RFtools 7.28 elevator crash client only

### ISSUE THREAD

**Issue by mcdodge34** [McJty/RFTools#1639]
After updating to latest version of rftools (7.28) when I try to use my elevator, I get a crash to desktop, all mods are obviously up to date along with Forge, the server doesn't crash and seems to be fine, but the client insta crash to desktop, here's the crash report I get, when I downgrade to Rftools 7.27, everything works fine.

https://pastebin.com/rvhhv0FN

**Comment by josephcsible** [comment]
Duplicate of #1633. Will be fixed in the next release.

**Comment by mcdodge34** [comment]
Sorry, I tried to find an issue that was relevant, turns out I was blind and didn't see it.
