### ISSUE TITLE
Dimensional Shard Ore not registered in OreDictionary

### ISSUE THREAD

**Issue by Saklad5** [McJty/RFTools#1641]
Issue description: 
Dimensional Shard Ore does not have an OreDictionary entry. This is particularly annoying with mods that filter for ores, such as Industrial Foregoing and its Ore Processor.
Steps to reproduce: 
N/A

Versions:
* Minecraft: 1.12.2 (1.12.2)
* Forge: 14.23.1.2587 (14.23.1.2587)
* McJtyLib: 1.12-2.6.2 (2.6.2)
* RFTools: 1.12-7.23 (7.23)

Possibly incompatible mods: 

FoamFix

Relevant logs, if any: 
N/A

**Comment by josephcsible** [comment]
For reference, the code in question: https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/utils/ItemStackUtils.java#L159-L164

We need to give it an oredict name that starts with `ore`.

**Comment by Saklad5** [comment]
`oreDimensionalShard` would be fine.

**Comment by josephcsible** [comment]
Will be fixed in the next release.
