### ISSUE TITLE
Client crash when breaking shield projector

### ISSUE THREAD

**Issue by 016Nojr** [McJty/RFTools#1645]
Issue description: When you try to break a shield projector with a pickaxe, the game crashes just before it's supposed to break. Tested with Tinkers and Minecraft pickaxes. Removing it with a wrench works.

Steps to reproduce: Place any shield projector, get a pickaxe, break the shield projector

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2618
* McJtyLib: 2.6.4
* RFTools: 7.29

Relevant logs: [Crash log](https://gist.github.com/016Nojr/fb7ea3eed630b61807837b1648cd46ab)

**Comment by josephcsible** [comment]
I think I know what happened. Did you try to compose the shield without having a shape card in it or any shield template blocks around it?

**Comment by 016Nojr** [comment]
The shield projector was just placed, no configurations were changed in it

**Comment by josephcsible** [comment]
Will be fixed in the next release.
