### ISSUE TITLE
Shield size again

### ISSUE THREAD

**Issue by battlekruiser** [McJty/RFTools#1646]
Issue description: 
Setting up a large (~15k blocks) shield with T4 projector on a server causes internal exception when the block is loaded (approaching that area or logging into it). Issue appears to disappear when the shield is assembled gradually (i.e. build a piece of shield, activate it with wrench, deactivate, add more shield...). 

Steps to reproduce:
I built a 100x100x48 ellipsoid dome (Builder's guide totalled at 18.6k blocks, my estimate is ~15k).
Then I placed T4 projector under the top center block and right-clicked with a smart wrench. Immediate "forced logout" telling me the packet was too big.

Versions:
* Minecraft: 1.7.10
* Forge: 10.13.4.1558
* McJtyLib: 1.8.1
* RFTools: 4.23

Possibly incompatible mods: 
Optifine
Fastcraft
OPIS

Relevant logs, if any: 
https://pastebin.com/K9hJZib1

**Comment by McJty** [comment]
This is a known limitation on 1.7.10. Avoid making shields that are too big. I can't easily solve this on 1.7.10
