### ISSUE TITLE
[Crash] RFTools Dimension

### ISSUE THREAD

**Issue by CrispyLips** [McJty/RFTools#1648]
Issue description:  Creation of a RFTools Dimension using just sand as a world descriptor.

Steps to reproduce:

1. Create an empty dimension tablet
2. Place just a dimlet of (Material Sand)
3. Store and place realized dimension tablet inside of a Dimension builder.

Versions:
* Minecraft: 1.10.2
* Forge: 2316
* CompatLayer (only if on Minecraft 1.10 or 1.11): compatlayer-1.10-0.2.9
* McJtyLib: mcjtylib-1.1x-2.4.3
* RFTools: rftools-1.1x-6.13

Possibly incompatible mods: 
SpongeForge
The crash report detailed that the issue of crashing was due to SpongeForge chunk loading.
https://i.imgur.com/oXFAeAw.png

Relevant logs, if any: 
https://pastebin.com/WHggXbk6

**Comment by josephcsible** [comment]
What version of RFTools Dimensions?

**Comment by josephcsible** [comment]
Never mind, I see you're on 5.04. This problem was fixed in 5.05, so just update and it should work: 5a2fbc5
