### ISSUE TITLE
When i'm not online other people can't teleport to my receivers on server.

### ISSUE THREAD

**Issue by acanady** [McJty/RFTools#1649]
I suppose this is more of a question than anything.
Is this supposed to happen, is it to like reduce lag or something? 
As the question says when i'm not online other people can't teleport to my receivers, they're all public and it works when i'm online.

**Comment by McJty** [comment]
Hmm that's strange. What happens if they try to teleport to them?

**Comment by josephcsible** [comment]
Versions? Are you running Sponge or any other highly-invasive coremods? And is there anything relevant in the log on either their client or the server?

**Comment by acanady** [comment]
Thanks for replying, it's kinda hard to get valid information since it's not coming from me directly. Turns out that the people trying to teleport to my receivers were new to the mod and were doing it incorrectly. It actually works fine, sorry for wasting your time.

I'm gonna closed the thread, thanks again.

**Comment by josephcsible** [comment]
Did you mean to reopen this?

**Comment by acanady** [comment]
oh no, lol
