### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by sambaz** [McJty/RFTools#165]
I can create unlimited blocks using the Crafter (RFTools 2.80) and Black Hole Talisman (Botania r1.6-184). I'm not sure which mod causes this.

To recreate:
1) Store any block in Black Hole Talisman (In my tests it seems that you need more that 1 stack for this to work)
2) Put crafting recipe in crafter
3) Insert Talisman in buffer
4) Crafter keeps pulling blocks

![2015-04-29_20 34 10](https://cloud.githubusercontent.com/assets/1927123/7404384/ca07569e-eeaf-11e4-897f-66bf6e551036.png)

Thanks for creating such a great mod!

**Comment by McJty** [comment]
Related to #150

**Comment by valveo** [comment]
I have problems with this too. I have 2 Black Hole Talismans. I have stored soul sand to one, netherrack to other. When I put them to crafter and make recipe for both of them, one pulling netherrack out and another pull soulsand. It doesnt care which talisman is inside crafter, it will pull both from talisman, like putting talisman containing soul sand, it will give me stack of soul sand and netherrack.

**Comment by McJty** [comment]
I'll have to look at this soon. First need to be able to reproduce this. Will look at this later

**Comment by McJty** [comment]
Should be fixed in next version
