### ISSUE TITLE
Enderdragon Dimension won't work

### ISSUE THREAD

**Issue by EscolarProgramming** [McJty/RFTools#1650]
Issue description: 
I've tried many times to create a Dimension with Ender Dragon in it, but it won't work. They don't spawn. I've tried both in singeplayer as in multiplayer, but it's in both modes the same issue. 
I create the Mob-Dimlet minecraft:ender_dragon, combine it with a terrain dimlet (I've tried flat, void and normal world type). But when I enter the map, there are no enderdragons, even I've waited a bit.

Steps to reproduce: 
See above

Versions:
* Minecraft: 1.12.2
* Forge: 2611
* McJtyLib: 1.12-2.6.2
* RFTools: 1.12-7.23

Possibly incompatible mods: OptiFine,

**Comment by josephcsible** [comment]
sp614x/optifine#1212

tl;dr: Downgrade Forge to 2595, switch to the preview build of OptiFine, or just uninstall OptiFine. Also, in the future, RFTools Dimensions bugs go in McJty/RFToolsDimensions, not here.
