### ISSUE TITLE
game crashing when opening shield projector

### ISSUE THREAD

**Issue by DerpyNinja476** [McJty/RFTools#1651]
Issue description: 
Hi, i asked on the forge forums about a crash, I am making a modpack. could someone please tell me the cause of the crash and how I might fix it. if it helps, I opened the GUI of a shield projector from.

Steps to reproduce: 
1. place down rftools shield projector
2. open gui for it
3. game crashes

Versions:
* Minecraft: 1.10.2
* Forge: 1.10.2-12.18.3.2511
* CompatLayer (only if on Minecraft 1.10 or 1.11): 1.10-0.3.0
* McJtyLib: 1.1x-2.5.1 and 1.10-1.9.9
* RFTools: 1.1x-7.16

Possibly incompatible mods and versions: 

Relevant logs, if any: 
[crash-2018-02-22_17.05.54-server.txt](https://github.com/McJty/RFTools/files/1753324/crash-2018-02-22_17.05.54-server.txt)

[latest.log](https://github.com/McJty/RFTools/files/1753329/latest.log)

**Comment by josephcsible** [comment]
> McJtyLib: 1.1x-2.5.1 and 1.10-1.9.9

You're not supposed to have more than one of McJtyLib at once. Remove 1.10-1.9.9.

**Comment by DerpyNinja476** [comment]
if i dont have both it says that it cant run
one it the _ng version

**Comment by josephcsible** [comment]
You most assuredly don't need 1.10-1.9.9. Whichever mod says it needs it is out of date.

**Comment by DerpyNinja476** [comment]
but is that the reason of the crash?

**Comment by josephcsible** [comment]
Most likely. Which mod needs the old McJtyLib?

**Comment by DerpyNinja476** [comment]
it still says that i need the old one
![untitled](https://user-images.githubusercontent.com/29805988/36623656-888b5c5e-18d4-11e8-91dc-6b6e0a93ed41.png)

**Comment by josephcsible** [comment]
RFTools Dimensions and RFTools are different mods. Update the former to 1.1x-5.05 and that error will go away.

**Comment by DerpyNinja476** [comment]
what do you mean by 1.1x-5.05

**Comment by josephcsible** [comment]
[rftoolsdim-1.1x-5.05.jar](https://minecraft.curseforge.com/projects/rftools-dimensions/files/2478236)

**Comment by DerpyNinja476** [comment]
oh thank you

**Comment by DerpyNinja476** [comment]
sorry but this error didnt go away, the game still crashes.

**Comment by josephcsible** [comment]
Can you post a new crash report and full mod list? (And make sure that the other McJtyLib really is gone)

**Comment by DerpyNinja476** [comment]
i have 135 mods, is there a fast way to do it?

**Comment by josephcsible** [comment]
Just go into your mods folder and take a screenshot.

**Comment by DerpyNinja476** [comment]
ok

**Comment by DerpyNinja476** [comment]
![image](https://user-images.githubusercontent.com/29805988/36623975-fb631872-18d7-11e8-8e50-e2363d7f245c.png)
![image](https://user-images.githubusercontent.com/29805988/36623979-06f2f7d4-18d8-11e8-86e8-b2537ee416a7.png)
![image](https://user-images.githubusercontent.com/29805988/36623983-1377b166-18d8-11e8-8b14-41ebbd33861b.png)
![image](https://user-images.githubusercontent.com/29805988/36623990-1e886e06-18d8-11e8-86d4-e81bd4326c84.png)
![image](https://user-images.githubusercontent.com/29805988/36623998-2bec5d6e-18d8-11e8-828b-aacb88fcb223.png)
![image](https://user-images.githubusercontent.com/29805988/36624002-321f399a-18d8-11e8-9712-d1756091b588.png)
these are all the mods i use

**Comment by DerpyNinja476** [comment]
before you look through all of them, i realized that i left the old version in my mods folder and just deleted it

**Comment by DerpyNinja476** [comment]
sorry

**Comment by josephcsible** [comment]
Can you also post a new crash report now that the old McJtyLib isn't there?

**Comment by DerpyNinja476** [comment]
ok when and if it crashes, i will post the crash

**Comment by DerpyNinja476** [comment]
thank you for your help so far

**Comment by DerpyNinja476** [comment]
ok thank you so much for the help it worked :)

**Comment by DerpyNinja476** [comment]
it didnt crash

**Comment by josephcsible** [comment]
You're welcome!
