### ISSUE TITLE
Crash - Linking Template to shield Project

### ISSUE THREAD

**Issue by Tydesson** [McJty/RFTools#1653]
Issue description: 
Crash occurs when trying to link Projector Templates to Tier 4 shield Projector

Steps to reproduce: 
Place a Shield projector T4
Place templates (Mine was 13x13 on 2 layers, flat)
Templates are touching the projector
Link Templates to Projector
It worked, shield is ok
Remove the second layer
Templates are NOT touching the projector now
Link Templates to Projector
Crash

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2618
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.4
* RFTools: 1.12-7.29

Relevant logs, if any: 
https://pastebin.com/jWMYFVVS
https://pastebin.com/Jc7ew4By

Both logs, same crash.
Ping me if you need more informations

**Comment by josephcsible** [comment]
Same underlying problem as #1645. Already fixed in git; will be fixed in the next release.
