### ISSUE TITLE
Client crash when a block loads.

### ISSUE THREAD

**Issue by Zanzoman** [McJty/RFTools#1659]
Issue description: 
When anyone on my server loads at spawn, they crash never to be able to rejoin (including myself) because of the block. I have gone over with mcedit but it seems like it a common block yet im unable to know which one it is. Please help so i can get my server back up

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.2.2611
* McJtyLib: 1.12 - 2.6.4
* RFTools: 1.12 - 7.29

[crash-2018-03-02_22.05.27-client.txt](https://github.com/McJty/RFTools/files/1775054/crash-2018-03-02_22.05.27-client.txt)

**Comment by McJty** [comment]
There is an option in forge.cfg that will automatically delete tile entities that cause crashes. That might get your server back and running but your elevator block will be gone. We will investigate the crash though

**Comment by Zanzoman** [comment]
Thats the problem. there was no elevator blocks in the first place

**Comment by McJty** [comment]
That's not possible. There has to be an elevator block because it is crashing in an elevator block. Either way. That option in forge.cfg might fix it

**Comment by Zanzoman** [comment]
Alright i'll look into it. Thanks =D

**Comment by josephcsible** [comment]
Try updating to RFTools 7.30.

**Comment by josephcsible** [comment]
Also, can you upload your world save?
