### ISSUE TITLE
Crash (Somewhat expected *something* to break)

### ISSUE THREAD

**Issue by Zoryn4163** [McJty/RFTools#166]
Server log: http://pastebin.com/1ZBdDNaa
Client didn't crash

Summary of what I was doing and the results:

So I have a digger age made by Mystcraft (haven't looked into DimLets as of yet) and made a FunkyLocomotion FrameQuarry (just a moving set of BuildCraft Mining Wells) and I decided I'd like to be able to freely teleport to/from this moving monster. So I made 2 dialing devices, matter receivers and transmitters, and set them up in my base and on the moving quarry. I initially ran into a problem with the frame and chunk loading because of how they handle one-another, but managed to resolve that as far as I'm aware (could be a cause of this, maybe?). After that was resolved I dialed a link to my base and tested it a few times with moving and it worked fine, so I decided it was time to let it auto-run while I left the dimension. This is when strange things started happening. First up was that the client got kicked by the server for an internal exception, but neither crashed, when I tried using the transmitter to teleport back to my base. So I rejoined, everything seemed fine, but only *half* the quarry had moved, so I placed *more* chunk loaders to keep all 4 chunks loaded at all times regardless. After that I set the quarry to run automatically again, and left the dimension - successfully this time - but when I loaded into my base (Another MystCraft age, one that had Bright Lighting so that everything is lit up even if it's dark) and it was almost completely darkened out, so I knew *something* was up. The server crashed seconds later.

I'll provide any further information upon request, but just a heads up about this. 
Using:
RFTools v2.80
CoFH Core 3.0.0RC7-211
Thermal Dynamics 1.0.0RC7-98

It appears to be a problem regarding your transmitter and a ThermalDynamics conduit, so I can go bug CoFH about it if you think it's all on them.
Edit: Server now crashes on startup, goodbye to that dimension.

**Comment by McJty** [comment]
Um. This is a bit confusing. Maybe I don't 100% understand what is going on but how do you conclude this is a problem with the transmitter and the conduit? Could just as well be an issue with the funkylocomotion thing I would say. Crashlogs would be useful in any case if you still have those.

**Comment by Zoryn4163** [comment]
I did include a crash log?
> Server log: http://pastebin.com/1ZBdDNaa
Apologies for calling it the server log, I realize that they are 2 separate things.

**Comment by McJty** [comment]
The problem is most likely caused by ThermalDynamics being confused by being moved and trying to get information from the old location. Sounds more like a problem with ThermalDynamics here.

**Comment by Zoryn4163** [comment]
Alrighty.

**Comment by KingLemming** [comment]
Just a heads up, this probably isn't fixable. We are already doing cast checks everywhere possible. But I concur that it's not on RFTools, just vanilla MC and how tile entities are tracked.
