### ISSUE TITLE
Quarry card and Shape card Discrepency

### ISSUE THREAD

**Issue by Bimahi** [McJty/RFTools#1662]
Issue description:  Using a shield generator to build a torus shape with clearing quarry to allow shield blocks to fill results in two different results

Steps to reproduce: 
1: Configure shape card and quarry card exactly the same
2: Attempt to use quarry to dig out shield hole
3: Shield and holes do not match

Versions:
* Minecraft: 1.12
* Forge: FTBserver-1.12.2-14.23.2.2613
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-2.6.3
* RFTools: rftools-1.12-7.27

Possibly incompatible mods and versions: 

Relevant logs, if any: 
https://imgur.com/a/5PBT9

**Comment by josephcsible** [comment]
Did you put the shield generator in the same block that the clearing quarry was in? If not, did you adjust the shape card's offset for the difference in position between the two blocks?

**Comment by Bimahi** [comment]
Close this, PEBKAC
