### ISSUE TITLE
Sky Factory 3 - Modular Storage in Inventory Causing Crash/Corrupting World

### ISSUE THREAD

**Issue by IAmVensey** [McJty/RFTools#1667]
Issue description: 

*Note: This is solely related to the mod's performance in Sky Factory 3. If there have since been updates to the mod and its version, then I understand that this issue may be moot.*

Whenever I have either the storage module block or the storage module card in my inventory, the world will crash with a timeout exception. Placing the block and interacting with it in the world does not cause an issue. Items placed onto the storage module's cards include chicken eggs, almost every type of chicken (from chickens mod), and dimlets/dimlet parts from RFTools dimensions. Also, each of these sets of items were placed onto its own storage card, and place within its own storage module, so the amount of items that could be stored was not maxed out on any of them.

I've kept a clean save of my backup, and all of the other interactions in my world are fine. I played for a while, ignoring the task I was doing when the crash first happened to see if it was a timeout error. After being able to play for a much longer period, I deduced it had to be something else. Placing certain items into my inventory, I was able to reproduce a common problem: the RFTools modular storage, when in my inventory, was crashing and corrupting my world.

The crash does not occur immediately, but does occur soon after dealing with the RFTools items mentioned. Additionally, upon trying to transfer RFTools modular items to regular storage (such as Refined Storage or simply a bunch of chests), I got a crash after putting the modular storage parts (which were empty) into a storage disk from Refined Storage. The other RFTools items I'd had in a Refined Storage disk were fine long before I put the modular storage parts in, which leads me to believe that it is very specifically

Steps to reproduce: 
1) Loaded a clean backup save of my world
2) Put the storage module block (containing storage card with items) into inventory
3) Simply left it in inventory
4) Crash occurs

Other instances of the crash:
- Put only storage card (still containing items) into inventory
- Put modular storage parts (both the block and the cards, which were completely emptied of items) in inventory
- Repeat of above, except this time, put them in some type of storage (such as the disk from Refined Storage)

Versions:
* Minecraft: 1.10.2
* Forge: 12.18.3.2477
* CompatLayer (only if on Minecraft 1.10 or 1.11): 1.10-0.2.9
* McJtyLib: 1.1x-2.4.3
* RFTools: 1.1x-6.13

Possibly incompatible mods and versions: As I've said, this is with the other Sky Factory 3 mods. I will mention that prior to 2/27/18, I had not had the issue with moving or holding RFTools' modular storage in my inventory.

Relevant logs, if any: 
This is the most recent crash log my computer has given me for Sky Factory: http://paste.feed-the-beast.com/view/0f14010b

**Comment by josephcsible** [comment]
Can you try temporarily removing NEI (just NEI, not JEI) and see if that makes it stop crashing? if so, can you report this to [their issue tracker](https://github.com/TheCBProject/NotEnoughItems/issues)?
