### ISSUE TITLE
Crash with Blood Magic's energy blaster

### ISSUE THREAD

**Issue by ykmukqph** [McJty/RFTools#167]
RFTools 2.81 causes a crash when used with BM's energy blaster or energy bazooka. Crash does not occur with RFT 2.80

Steps:
- create flat test world with mods listed below
- give self energy blaster or bazooka and test blood orb
- use orb to gain LP
- fire weapon
- crash occurs on projectile impact

Crash log: https://privatepaste.com/bfa8c92b8a

rftools 2.81
bloodmagic 1.3.2-1
cofhcore 3.0.2-262
forge 1291

**Comment by McJty** [comment]
Could you repaste the error on another pastesite (like bpaste.net). For some reason I cannot access privatepaste.com. Thanks

**Comment by ykmukqph** [comment]
https://bpaste.net/show/3a542ecf6f00

**Comment by McJty** [comment]
Ok thanks a lot. Someone else reported a similar bug and I have a fix ready. I will release 2.82 in a moment.

**Comment by McJty** [comment]
Fixed in 2.82
