### ISSUE TITLE
[Bug] Builder shows more chunks than are selected when at chunk boundaries.

### ISSUE THREAD

**Issue by MindCaged** [McJty/RFTools#1670]
Issue description: 
I've noticed this for a while, if you turn on chunk boundaries and select a chunk/multiple chunks lining it up with the inside of the chunks, say select a 5x5 chunk area. When you run it in the builder it'll show it as running # out of 36 chunks instead of 25. I'm guessing the math for calculating how many chunks there are is offset by 1 block perhaps? It's more annoyance than actual problem.

Steps to reproduce: 
1. Turn on chunk border display and select entire chunks without going outside the border with shape card.
2. Put shape card in builder.
3. Turn on and look at status display.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2619
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.12-2.6.5
* RFTools: 1.12-7.30

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
It counts actual chunks touching. So even if you only mine a 16x16 area it can be 4 chunks if that 16x16 area happens to go over chunk boundaries. So this is normal and not a bug

**Comment by MindCaged** [comment]
But I'm not going over chunk boundaries, does it just count extra just to be on the safe side?

**Comment by josephcsible** [comment]
What are the exact coordinates you're selecting?

**Comment by MindCaged** [comment]
For instance I select a 16x16 area, when the area is shown it does not cross the chunk borders as indicated by F3+G. Instead of showing as 1 chunk it shows up as 4. I don't know if it overestimates on purpose for the situations where it most likely would cross chunk borders unless you were specifically trying not to.

**Comment by josephcsible** [comment]
Can you post the exact coordinates, and also a screenshot of your setup?
