### ISSUE TITLE
Modular Storage + JEI and missing items

### ISSUE THREAD

**Issue by borg286** [McJty/RFTools#1672]
Other crafting grids integrate with JEI so that when the recipe is pulled up and the mouse is over the + sign JEI highlights missing items. In Modular Storage it seems all recipes are acceptable and are put in this "template" crafting grid for modular storage. you only know if you're missing an item when you hover your mouse over the "craft 1" button. It would be nice if these missing items are piped through to JEI. Doing this will reduce clicks.

**Comment by borg286** [comment]
This shortcut is one of the largest stumbling blocks me from being satisfied with RFTools modular storage. As it stands I view {(Crafting Station + crate), ME system} as superior. Adding this feature brings your storage up a tier.

**Comment by McJty** [comment]
I don't want it like that. I regularly set up recipes in that grid without having the ingredients for it. I would hate it if that stopped working. So I'm not going to change that. This is done on purpose like this

**Comment by McJty** [comment]
Note that in contrast with regular crafting grids the items in that grid aren't actually real items. They are ghost items. It is (for example) perfectly possible to fill the entire 3x3 grid with cobblestone even if you have only one cobblestone in your inventory by dragging it on that grid. This follows the same principle

**Comment by borg286** [comment]
I can appreciate the clickable recipes you have on the left hand-side and the ghost crafting.
Is your desire that (1) within JEI you are able to search a recipe, click the + button, have the recipe populate the crafting grid, and then store this in your recipe list in the UI?
Or does your main user story not require this path but is instead (2) manually creating the ghost recipe from held items? If you are ok with JEI highlighting missing items then consider using IRecipeTransferHandlerHelper.createUserErrorForSlots(). I don't know if throwing this error would result in the + button being disabled (which would ruin the steps in (1) but not (2)). Even if we downgraded the story in (1) to requiring the user to have at least 1 item in the recipe before he can create a ghost recipe seems like an acceptable compromise in order to align integration with JEI, w.r.t. missing recipe items.

Most of my time is spent 
0: searching for the high level item I want, 
1: hovering my mouse over the + button, 
2: if the + button is avaliable click on it and craft it.
3: else seeing which items are missing, 
4: moving my mouse to those missing items and 
5: clicking through and go to step 1

With your crafting grid taking full control we do get ghost recipes that we can store for a quick list, but this adds 3 more steps

0: searching for the high level item I want, 
1: hovering my mouse over the + button, 
2: The + button is available click on it.
3: Hover my mouse over the '1' button
4: If there are no reds then craft it
5: else Open JEI and click on the item again
6: Remember which item was missing and click on it to load its recipe
7: go to step 2
