### ISSUE TITLE
Unable to remove storage control screen module from storage tablet

### ISSUE THREAD

**Issue by superfluke** [McJty/RFTools#1673]
Issue description: Storage control module is in table. I want it to not be in tablet. 
![2018-03-13_23 30 51](https://user-images.githubusercontent.com/20022336/37382057-eece02aa-2716-11e8-849e-6d6ba88d054b.png)

Steps to reproduce: 
First noticed this in a world where I could remove the module normally. Changed to a LAN world and could no longer remove the module. Tried loading up a different world and creating a new world and could not remove the module in either of those worlds. 
So my best guess is try opening to LAN and see if that's what breaks it. Hard to reproduce because I've only had 1 world where it worked normally to begin with.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2611
* McJtyLib: 1.12-2.6.5
* RFTools: 1.12-7.30

Possibly incompatible mods and versions: 
FastWorkbench-1.12.2-1.2.1
FoamFix-1.12.2-0.9.4-Anarchy
From what I understand, the edits these mods use to make crafting faster only work on the vanilla work table. I tried uncrafting the module in the player grid, vanilla table, forestry workbench, and ae crafting terminal. None would let me extract the module. 

Relevant logs, if any: couldn't see anything in the logs when trying to uncraft the module

**Comment by josephcsible** [comment]
Can't reproduce this in a clean instance, even when opened to LAN. Can you try temporarily removing the rest of your mods to see if one of them is causing it? If so, can you try to narrow down which one it is?
