### ISSUE TITLE
Automate powercell and linking card configuration

### ISSUE THREAD

**Issue by ouroborus** [McJty/RFTools#1678]
Any chance we can get a way to automate powercell and linking card configurations?

I'm thinking that putting a couple powercells or linking cards into a crafting grid could copy the first one's configuration to the second one. (Logically, this could be extended to most RFTools items as they tend to keep their configurations.)

I'd really like to automate the configuration and linking of the powercells.

**Comment by McJty** [comment]
You can put multiple link cards in the powercells linking slot at once. So that should work. With RFTools Control you should be able to automate that even

**Comment by ouroborus** [comment]
RFTool Control sounds promising. I'll look into that.

**Comment by ouroborus** [comment]
So I can place the cards which allows me to configure them, but there doesn't appear to be a way to automatically set the input/output mode of the powercell faces

**Comment by McJty** [comment]
No. That would also be pretty hard to do. For what do you need that?

**Comment by ouroborus** [comment]
I plan to set up automation to continuously build and link powercells. (I think I can use AE2 to push them into another dimension dynamically without having to worry about where to place them. Not sure if I'm going to need a chunk loader.) I guess I can probably leave them at their default face setting since they're just for the shared storage so maybe being able to auto-config the faces isn't necessary.

**Comment by josephcsible** [comment]
Can you use some kind of auto-clicker block, like the Player Simulator from Integrated Tunnels, to simulate using a wrench on the sides?

**Comment by ouroborus** [comment]
@josephcsible  That does the trick. Thank you much
