### ISSUE TITLE
[feature request] Make space chamber use 2 blocks to specify an area

### ISSUE THREAD

**Issue by Frefreak** [McJty/RFTools#1679]
Currently If I need to mark a cube area to copy or move later I need to use 8 chambers block with a chamber card. Can we make it only need 2 on the diagonal of the cube? or something similar to shape card (which only needs to click the 2 diagonal block). The cost of the chamber block can be higher than it is now to compensate the number, but result in way better experience.

**Comment by McJty** [comment]
Hmm not sure about this. I actually think it makes sense to have a full cube here

**Comment by Frefreak** [comment]
OK, then... Hopefully you will change your mind in the future. Anyways thanks for your awesome mods!

**Comment by tyler489** [comment]
how about 4 blocks for 1 wide builds?
