### ISSUE TITLE
Builder with shape card builds shape without consuming items from chest

### ISSUE THREAD

**Issue by nebularazer** [McJty/RFTools#1681]
Issue description: 

The Builder does not use items from an inventory below or above to rebuild a scanned shape.
It requires only one of the blocks to be available in the inventory to rebuild and does not consume items from this inventory.

Steps to reproduce: 

- Build a simple structure with 10 (ten) diamond blocks
- Use the Scanner to create a shape card with this structure
- Use the builder and insert the created shape card
- Place a chest on top of the builder with 1 (one) diamond block
- Hit start to build the shape
- All 10 blocks are placed and the one block in the chest remains

Versions:
* Minecraft:  1.12.2
* Forge: 14.23.2.2629
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: 1.12-2.6.6-SNAPSHOT
* RFTools: 1.12-7.31

Possibly incompatible mods and versions: 
- this was a plain install with only rftools, jei and required libs

Relevant logs, if any: 
n/a

**Comment by tyler489** [comment]
Is the quarry set to move mode or copy.

**Comment by nebularazer** [comment]
This setup only allows copy mode.

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib.
