### ISSUE TITLE
Internal Exception - "packet was larger than I expected" forming shield template

### ISSUE THREAD

**Issue by hjoyn** [McJty/RFTools#1683]
Issue description: When attempting to bind a large amount of shield templates to a shield generator on a server, you get disconnected with the message `Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet was larger than I expected, found x bytes extra whist reading packet 53`. The number of bytes x seems to vary, I got around 30-50 kb. This error also occurs if you try to connect to that server again, persisting through server and client restarts. It can be remedied by reverting the save file. Note that this occurred while using a Shield Generator Tier 4, which claims to have a max limit of 32768 shield blocks, greater than the amount of shield blocks the error occurred with. 

Steps to reproduce: Right click on a shield generator with the smart wrench with a large amount of shield templates attached. This amount seems to vary based on what else is in the world, as it first occurred with an estimated 6000 shield template blocks, but can be reliable reproduced in a void world with 20000 shield template blocks. 

Versions:
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.8.1 - SNAPSHOT
* RFTools: 4.23

Possibly incompatible mods and versions: None

Relevant logs, if any:

**Comment by McJty** [comment]
Known issue in the 1.7.10 version of RFTools. Solution: avoid large shields like these

**Comment by hjoyn** [comment]
Is there a way to allow the client to log back into the server? Further attempts still yield the packet size error after removing the shields in singleplayer.

**Comment by nightgod0** [comment]
Yes pls help me to i want to join hypixel

**Comment by nightgod0** [comment]
It is the same

**Comment by nightgod0** [comment]
It is the same

**Comment by Riyanshoi** [comment]
Same
