### ISSUE TITLE
RFTools builder can place water in the Nether

### ISSUE THREAD

**Issue by qrss** [McJty/RFTools#1684]
Issue description: 
RFTools builder can place water in the Nether.

Steps to reproduce: 

1. Try to place water in a Nether biome with a RFTools builder containing "Shape Card (placing Liquids)"
2. ???
3. Profit!

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2632
* McJtyLib: 2.6.7
* RFTools: 7.31

**Comment by McJty** [comment]
Is this actually a problem? I believe other modded block placers that can place water can also do this as far as I know

**Comment by qrss** [comment]
Some do, some don't. For example the fluid placer from Cyclic can place water in the nether, while the one from Actually Additions can not.

It is not really a problem, but affects how some modpacks, for example Lost Souls, play out.

If this is not unintended behavior, then I won't feel guilty about using it. Thanks for answering.

**Comment by josephcsible** [comment]
Will be fixed in the next release.

IMO, the other modded block placers are buggy if they let you do this. (And I don't think most actually do.)
