### ISSUE TITLE
rftools power latest.log spam

### ISSUE THREAD

**Issue by MasterSloth1** [McJty/RFTools#1690]
Issue description: 
sorry if this doesnt belong here but i dont know where rftools power is :D

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.2.2635
* Sponge: 7.1.0-SNAPSHOT-a75bd9b
* McJtyLib:Mcjtylib-1.12-2.6.7.jar
* RFTools:rftools-1.12-7.31.jar
* RFToolsPower: rftoolspower-1.12-0.1.0

Relevant logs, if any:
https://gist.github.com/MasterSloth1/fb77cc6ee41c6ca8aa9d58d503e613f6

**Comment by McJty** [comment]
Well all my projects are on gitub: Just use https://github.com/McJty/RFToolsPower

Anyway how did you reproduce this? Can you describe your setup?

**Comment by josephcsible** [comment]
Can you try temporarily removing Sponge and see if the problem still occurs? Also, screens expand via the wrench, not with other screens.
