### ISSUE TITLE
Error Textures [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [McJty/RFTools#1691]
Versions:
* Minecraft: 1.12.2
* Forge: all (last 14.23.2.2637)
* McJtyLib: 2.6.7
* RFTools: 7.32
Error Textures. Lines: 10733-10738.
Debug Log - https://drive.google.com/open?id=17dCrv1l_taOd9Js8wWa6RZbId6PPamuF

**Comment by McJty** [comment]
Not harmful. You can safely ignore that

**Comment by kellixon** [comment]
Good. Thank you very much!
