### ISSUE TITLE
Builder Highlight Postion Frame won't disappear.

### ISSUE THREAD

**Issue by timozel** [McJty/RFTools#1695]
Issue description: 
![2018-03-27_21 50 19](https://user-images.githubusercontent.com/20260242/38006024-eff67886-3208-11e8-87bc-0d9fa2a2484d.png)
Used the builder to quarry out a place to build. I assumed the highlighting would go away after a server restart, but it didn't. I can't place the builder down again to clear the visual.

Steps to reproduce: I've tried multiple things in another location where I don't care about having this visual bug, but I can't reproduce it.

Versions:
* Minecraft: 1.12
* Forge: Whatever version FTB Revelation 1.6.0 is on. Couldn't find it.
* McJtyLib: 1.12-2.6.4
* RFTools: 1.12-7.29

**Comment by McJty** [comment]
You mean that this visual shows even if the builder is not placed? Or what?

**Comment by timozel** [comment]
Yeah, the visual is always there. I broke the builder and it never went away.
