### ISSUE TITLE
Is it possible to disable some of the syringes

### ISSUE THREAD

**Issue by Explosivee** [McJty/RFTools#1697]
Issue description: Hello, i own a FTB Revelation server and some of the syringes are kinda scary such as Ender Dragon, Chaos Guardian syringes. I tried to ban those items but the plugin i use ban all the syringes than only Ender Dragon so i'm curious is there any way that i can disable Ender Dragon or any other syringes?

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2627
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-2.6.7
* RFTools: rftools-1.12-7.32

Possibly incompatible mods and versions: Sponge 1.12.2-2611-7.1.0-BETA-2990

**Comment by josephcsible** [comment]
Syringes have a lot of uses. Which use of them do you care about banning? If just the Spawner, then just remove the mobs in question from the Spawner sections of rftools.cfg.

**Comment by Explosivee** [comment]
I tried it before ask in here. i delete ender dragon from configs and it didnt work

**Comment by josephcsible** [comment]
There's two Spawner config sections. Did you delete it from both? If so, can you confirm that Ender Dragons will still actually spawn, and can you pastebin your whole config?

**Comment by Explosivee** [comment]
Sure once i have time.

**Comment by Explosivee** [comment]
https://paste.feed-the-beast.com/view/286baed8

**Comment by josephcsible** [comment]
The Ender Dragon definitely shouldn't be spawnable with that config. Can you make a short video of spawning one in the Spawner, with the F3 screen open throughout? Also, can you see whether it works right in a clean instance with just RFTools?
