### ISSUE TITLE
Night Vision module flashes

### ISSUE THREAD

**Issue by Grim-Ascensions** [McJty/RFTools#170]
As the title says, the Night Vision module for the Enviromental Controller flashes on and off. I think this is due to the "warning" given for being almost out of time by the vanilla "Night Vision" affect since the timer repeats a countdown of 5 seconds.

Any way you can set the timer to a 20 second countdown that refreshes back to 20 every 5 seconds. This should remove the warning flash.

**Comment by McJty** [comment]
Ah I did notice the flashing but didn't know why it was. I'll see what I can do to fix that.

**Comment by McJty** [comment]
Fixed in next release

**Comment by Grim-Ascensions** [comment]
You sir, are awesome. Thank you.
