### ISSUE TITLE
RFTools Power − The game crashed whilst tesselating block model

### ISSUE THREAD

**Issue by Warrock3280** [McJty/RFTools#1700]
Issue description: 
The game crashes at the moment of rendering chunk with RFTP multiblock powercell.
P.S. I put it here because there is no RFTools Power repository:
![RFTPCF](https://i.gyazo.com/60ac63c2ad094517a042548578b78530.png)

Steps to reproduce: 
Load world and turn head to place where Powercell is deployed.

Versions:
* Minecraft: 1.12.2
* Forge: 2624
* McJtyLib: 2.6.7
* RFTools: 7.32
* RFToolsPower: 0.1.1

Possibly incompatible mods and versions:
Uninstalled OptiFine (yes, it goes wrong only if OptiFine is getting removed)

[Crashlog](https://gist.github.com/Warrock3280/3e0a402cfce93f7ed18947d74b09c1c4)

**Comment by josephcsible** [comment]
> P.S. I put it here because there is no RFTools Power repository:

https://github.com/McJty/RFToolsPower

**Comment by Warrock3280** [comment]
That's weird, i couldn't find it even through profile.
