### ISSUE TITLE
Feature request: Setting to limit teleporters to players only, blocking all other entities

### ISSUE THREAD

**Issue by TheDeviantCrafter** [McJty/RFTools#1706]
Issue description: 

I'm working on a modpack that aims to make automation interesting and complex. To reach that goal, I've decided to eliminate all forms of automatic item teleportation except for a few options that I think are the most unique. This forced the player to get creative and use options that they normally wouldn't consider.

That said, I don't want to limit manual teleportation. The RFTools teleporter is fantastic for servers, and if it's just the player moving from place to place I see no reason to limit that.

I'd like to prevent the RFTools teleporter from teleporting items. I don't see a setting to control that, so I'd like to request one.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.8.2627
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 2.6.6
* RFTools: 7.31

**Comment by josephcsible** [comment]
Doesn't it already only teleport players? Do you want it to make players drop their inventory when it teleports them?

**Comment by TheDeviantCrafter** [comment]
Looks like you're correct. My mistake.
