### ISSUE TITLE
CTD with RFTools Elevator

### ISSUE THREAD

**Issue by BottenRasterd** [McJty/RFTools#1707]
Issue description: 
CTD with Elevator. Doesn't matter if I try to use the elevator button w/screen or a redstone signal (using a stone button). As soon as an elevator is called, the game closes down with the following error in the crash log:
java.lang.NullPointerException: Rendering Block Entity at mcjty.rftools.blocks.elevator.ElevatorTileEntity.getAABBAboveElevator(ElevatorTileEntity.java:515)

When I restart the game, the elevator platform is at the new position I was trying to call it to when the game crashed.

Steps to reproduce: 
This problem persists despite everything I've tried. As mentioned above, I've tried using an elevator button module with a screen as well as with a redstone signal via a stone button.

My design calls for using 7 floors/elevators and I've tried placing all 7, 5, 3, and 2 elevators in place and got a crash each time.

I've tried using different materials for the elevator platform. CTD each time.

At one point, I scrapped all the elevators, screens and modules I had crafted and cheated in new ones in creative mode and still had a CTD when trying to call an elevator.

Since it mentioned rendering in the crash log, I removed all elements for RFTools from my resource pack (Faithful 32). Still CTD when trying to call an elevator.

In all, I've probably reproduced this error 20ish times, each time trying to change one element or another as mentioned above.

One thing I have not done is to create a new world with only RFTools installed to try to replicate the crash. I'm at work now, but I will try to do that this evening if you don't have any suggestions for what I can do to fix this (most likely something I screwed up).

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2617
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 2.6.6
* RFTools: 7.28

Possibly incompatible mods and versions: 
No Optifine or SpongeForge. I do use FoamFix 0.9.5 anarchy.

Relevant logs, if any: 
Here are 4 of the most recent crash logs:
https://pastebin.com/Zuwqxanr
https://pastebin.com/VGPAmJQs
https://pastebin.com/ngMXtMhG
https://pastebin.com/24ZsZTx7

Thanks for your help!

**Comment by josephcsible** [comment]
Your RFTools version is really outdated, and lots of elevator bug fixes have been made recently. Please try to reproduce this on 7.33; if you can't reproduce it there, I'll assume it's been fixed.

**Comment by BottenRasterd** [comment]
Oh wow! I try to stay on top of those things, but obviously I dropped the ball on this one. I didn't even realize I was several versions behind. Should have been one of the first things I checked.  

I'll do that later this evening and report back. Thanks for your help! Hope this works.

**Comment by BottenRasterd** [comment]
That did the trick! Thanks so much for your help and quick response!
