### ISSUE TITLE
Dimensions not loading

### ISSUE THREAD

**Issue by Dylaned** [McJty/RFTools#171]
I'm currently running a server through nitropanel. While I'm attempting to go into a dimlet world, I'm stuck floating in midair with nothing around me. The dimension is getting more than sufficient power. This happens with randomly creating dimlet worlds. I'm also unable to go into mystcraft worlds after they're made, so maybe there's something wrong with dimensions on my server? I'd just really like to get them working, please help! :D

**Comment by McJty** [comment]
Building dimensions is heavy for a server. Perhaps that's the problem. What happens if you reconnect? Does the dimension keep giving troubles or is it ok then?

**Comment by Dylaned** [comment]
I've restarted the server several times, as well as /kill myself then trying to go back into the dimension. I just did it in a single player world and it worked after using the spawn and shelter dimlets. Pure random dimensions weren't even loading in the dialer's menu. I'm about to try recreating one with those dimlets on the server and see if that fixes it.

**Comment by Dylaned** [comment]
Nope, didn't work. Still blank :/

**Comment by McJty** [comment]
A few things. Make sure you have a recent java (7 or 8). Install fastcraft on server and client. Make sure you allocate enough but not too much memory for MC and server (2.5-3gig should be good)

**Comment by Dylaned** [comment]
My server is running the "newest" version of cauldron, could that be the problem  you think?

**Comment by Dylaned** [comment]
Removed cauldron. Dimensions are working now.

**Comment by McJty** [comment]
Oh. That's interesting to know but I did know that Mystcraft had issues with Cauldron.

**Comment by McJty** [comment]
Closing because this is not really an rftools issue
