### ISSUE TITLE
Peaceful Essence Uncraftable!

### ISSUE THREAD

**Issue by cherob** [McJty/RFTools#1718]
Issue description:
Peaceful Essence is just Uncraftable.
Different Mob names...

Steps to reproduce: 

![JEI](https://user-images.githubusercontent.com/15168847/39192548-b3639e9e-47d9-11e8-9128-e3943968b99d.PNG)

![Craftingtable](https://user-images.githubusercontent.com/15168847/39192559-b7a7d6a0-47d9-11e8-88d9-bf9cccde6eb8.PNG)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2627
* McJtyLib: mcjtylib-1.12-2.6.5
* RFTools: rftools-1.12-7.30
* OptiFine: 1.12.2_HD_U_C8
* Modpack: FTB Presents Direwolf20 1.12

**Comment by josephcsible** [comment]
Your RFTools version is outdated, and a similar bug has been fixed since the version you're on was released. See if updating (and getting new syringes) makes it work.
