### ISSUE TITLE
Shield Projector blocks allowing light through

### ISSUE THREAD

**Issue by suprra** [McJty/RFTools#1722]
Issue description: Shield projector blocks remain transparent

Steps to reproduce: Create darkroom, place down shield blocks, note light levels with solid blocks compared to shield blocks, change projector mimicry to any block you like, note light levels remain the same as original projector blocks

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2618
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: couldn't find it
* RFTools: 1.12-7.29

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
I will add a new option for this as some people may depend on the current functionality
