### ISSUE TITLE
[1.12.2] Quarry Builder dropping Chisel blocks in-world

### ISSUE THREAD

**Issue by NillerMedDild** [McJty/RFTools#1726]
Issue description: 
When mining an area with the Builder, with a Quarry Card, all blocks from the Chisel mod are dropped in-world, instead of being put in the inventory on top of the builder.

Steps to reproduce: 
Place Chisel Marble, I used a 7x7x7, but that shouldn't matter.
Place Builder.
Use Quarry Card on builder, and set the area to the Marble cube.
Supply the Builder with power, and put a chest above it.
Run the Builder
-> Bug

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.3.2673
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.7
* RFTools:1.12-7.33

Possibly incompatible mods and versions: 

Relevant logs, if any: 
The latest.log has no information relating to RFTools.

First reported in https://github.com/NillerMedDild/Enigmatica2Expert/issues/43

**Comment by McJty** [comment]
Please report to chisel too. It may just as well be a bug on their side. I'm also pretty sure this didn't happen in the past and the Builder hasn't changed recently

**Comment by NillerMedDild** [comment]
Good point, will do.

**Comment by NillerMedDild** [comment]
Hm, it might be unique to my modpack then. Can I have your modlist for comparison?

**Comment by Morpheus1101** [comment]
Im afraid not, since this pack is private with mods form Authors who don tiwsh information out, im not able to.  But it has the most common things, Chisel Nucelearcraft, rftools, thermal*, DE, EnderIO, thaumcraft, tinkers, aroma*

**Comment by NillerMedDild** [comment]
Fair enough, thanks anyway.
Since the issue seems to be on my end, I'll close the issue.

**Comment by josephcsible** [comment]
For anyone who's looking at this report in the future, the actual problem was caused by Tool Progression.
