### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Yolt97** [McJty/RFTools#1729]
Issue description: Minecraft crashes on startup (at about step 4). To make sure it was RFTools, I made a fresh .minecraft and only installed RFTools (and McJtyLib, RFTools Dimensions and RFTools Power). It crashes in the same manner as when I had all my mods. 

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.3.2678
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-2.6.7
* RFTools: rftools-1.12-7.33

Possibly incompatible mods and versions: 

Relevant logs, if any: https://pastebin.com/KYwsmZC6

**Comment by McJty** [comment]
There is no crash in that log. Please submit a log that contains an actual crash

**Comment by Yolt97** [comment]
https://pastebin.com/0RX0VemQ

**Comment by McJty** [comment]
I still see no crash in that log. Why do you think it is crashing?

**Comment by Yolt97** [comment]
I'm not sure. That is the log that comes up after the crash. There are 3 sections highlighted in red.
Here's one of the sections:
"Apache Maven library folder was not in the format expected: C:\Users\Joshua\Documents\Curse\Minecraft\Install\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar. Using default libraries directory."

**Comment by McJty** [comment]
But why do you think rftools is the problem? There is nothing in the logs that indicates rftools is causing an issue. And btw rftools is widely used in many modpacks so it certainly works

**Comment by Yolt97** [comment]
Previously when I added RFTools to my mod list it crashed on startup. When I removed RFTools Minecraft worked fine. Now I've made a fresh .minecraft with solely RFTools as the only mod. It is crashing the same way on startup.

**Comment by McJty** [comment]
Well without a better log I cannot do anything. RFTools is known to work well with practically all mods so I doubt it is a problem on this side

**Comment by Yolt97** [comment]
I don't have any other mods installed, only RFTools. Is there a different log that I'm not seeing? Because what I pasted was the live log at the time of the crash. Could this be an NVidia thing?

**Comment by McJty** [comment]
And McJtyLib I hope? That one is required for RFTools

**Comment by Yolt97** [comment]
Yes, McJtyLib, RFTools, RFTools Dimensions, RFTools control. I also tried this without the add-ons, so McJtyLib and RFTools with the same issue. I'm using Twitch and the versions available on Twitch. Now I'm going to try a manual install outside of Twitch and see if that helps.

**Comment by Yolt97** [comment]
Nothing changed. Same problem. When it gets to initialization it says Java is not responding when it gets to RFTools.

**Comment by McJty** [comment]
Yes but you also have to make sure twitch is actually using that update. From your log it wasn't (it was using update 25). Not sure exactly how to do that though. I don't use twitch

**Comment by Yolt97** [comment]
Make sure Twitch is using what update? Nvidia?

**Comment by McJty** [comment]
Java

**Comment by McJty** [comment]
Aha good to know!
