### ISSUE TITLE
rftools a fatal error

### ISSUE THREAD

**Issue by FrameFMP** [McJty/RFTools#174]
I have the problem that I always when I go to an unregistered dimension I'm from the server geckit and there is a dan fatal errror has ...

**Comment by McJty** [comment]
I need more information. Like what version of RFTools. A crashlog and so on.

**Comment by FrameFMP** [comment]
2.83 version and log [B#301]  [20:21:55] [Client thread/WARN] [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87)
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47)
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22)
[B#301]  [20:21:55] [Client thread/WARN] [FML]: *  at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77)...
[B#301]  [20:21:55] [Client thread/WARN] [FML]: ****************************************
[B#301]  [20:21:55] [Client thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
[B#301]  io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#301]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#301]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#301]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#301]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#301]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0]
[B#301]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0]
[B#301]  	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0]
[B#301]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#301]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#301]  Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
[B#301]  	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[B#301]  	... 18 more
[B#301]  [20:21:55] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel BC-TRANSPORT
[B#301]  io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[B#301]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[B#301]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#301]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#301]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#301]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0]
[B#301]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0]
[B#301]  	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0]
[B#301]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#301]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#301]  Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
[B#301]  	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[B#301]  	... 18 more
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [THAUMCRAFT]: Restoring client configs.
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [simplyjetpacks]: Loading configuration files
[B#301]  [20:21:55] [Client thread/INFO] [Draconic Evolution]: Server speed is set to 20.0
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]: Disconnect from server: Unregistering RFTools dimensions
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 2
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 3
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 4
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 5
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 6
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 8
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 9
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 10
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 11
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 12
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 13
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 14
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 15
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 16
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 17
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [mcjty.rftools.RFTools]:     Unregister dimension: 18
[B#301]  [20:21:55] [Netty Client IO #1/INFO] [OpenMods]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
[B#301]  [20:21:55] [Client thread/INFO] [journeymap]: Mapping halted in C:\Users\jeremiasstoll\AppData\Roaming\.technic\modpacks\donnay-pack-hardcore\journeymap\data\mp\Minecraft~Server\DIM8
[B#301]  [20:21:55] [Client thread/INFO] [FML]: Applying holder lookups
[B#301]  [20:21:55] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[B#301]  [20:21:55] [Client thread/INFO] [FML]: Holder lookups applied

**Comment by McJty** [comment]
That looks like a problem with Buildcraft. It is crashing in Buildcraft code. Not rftools.

**Comment by FrameFMP** [comment]
In this world there are no buldcraft stuff

**Comment by McJty** [comment]
Well I don't know why but the crash is inside Buildcraft code: BuildCraftChannelHandler
I recommend either reporting it to them or else updating the mod. It can be that the dimension you're using has some buildcraft fluids (like oil) in them.

**Comment by FrameFMP** [comment]
ok i check it thanks

**Comment by FrameFMP** [comment]
it worked thank you

**Comment by McJty** [comment]
Ok, glad you resolved it.
