### ISSUE TITLE
Syringe issue?

### ISSUE THREAD

**Issue by dahjin** [McJty/RFTools#175]
everytime i use a syringe to craft no matter which syringe i use i get feather falling evertime

**Comment by McJty** [comment]
Do you have RotaryCraft in your pack?

**Comment by dahjin** [comment]
yes sir

**Comment by McJty** [comment]
This is related to #91 which is in turn related to https://github.com/rwtema/extrautilities/issues/525
So unfortunately we don't know what is going on but RFTools isn't the only mod that suffers from some kind of weird mod incompatibility.
