### ISSUE TITLE
Crashed a server [BUG]

### ISSUE THREAD

**Issue by fxstriker** [McJty/RFTools#176]
While playing on the feed the beast Infinity mod pack i was able to crash a server (unintentionally)
The Shield projector and Shield template blocks where formed into a force field using the following settings:
Allow player <Name> (me)
block player all 
dmgSol Hostile
sol passive
item Sol
not sure if this maters but for completeness the shield was red.

i then shot the field with a bow of the wyvrern from dragonic evolution
the bow was enchanted with 
Infinity 
power 5
Withering 1

from this point onward when the chunk was loaded the server crashed.
hopefully this is enough information to replicate the issue and resolve / fix it 
awesome mod from what i have looked at :)

sorry i cannot give more details or do more testing as they admins of the server where not very happy with me killing there server by logging in.

**Comment by fxstriker** [comment]
Just noticed same sort of bug as #173

**Comment by McJty** [comment]
Well I need a crash log first. And as you can see from the other ticket I'm not sure this is a bug in rftools. The crash in that crashlog seemed to indicate it was Draconic Evolution code that is causing the crash. Perhaps report to them as well. But make sure you have a crashlog. That's going to be needed to do anything.

**Comment by fxstriker** [comment]
I don't have access to the server logs best i can do is details to replicate the issue sorry.

the issue only seams to appear when the arrows hit the Shield would it be possible to delete any arrow entity the second they touch the shield, not ideal but better then dead servers and crashed clients.

**Comment by McJty** [comment]
I think this will have to be fixed in Draconic Evolution in the first place (if the bug is in that mod that is). I have no control over their code and I also cannot really prevent this from happening.

**Comment by fxstriker** [comment]
I understand that what i was saying is that the entity left behind on the shield causes the issue if you'r mod checked for that entity and deleted it it may stop the crash or at least keep the chunk accessible afterwards without using 3rd party tools to recover the area.

If it is Draconic evolution then it is indeed there issue to fix.
and i do believe someone else has already made a bug report for them.

thanks for taking a look into this :)

**Comment by McJty** [comment]
Issue is fixed on Draconic Evolution's side
