### ISSUE TITLE
Crafter Crafts Extras

### ISSUE THREAD

**Issue by SamuelFoster** [McJty/RFTools#178]
In RFTools 2.80, the Crafter (Tier 3) regularly crafts extra "nuggets".

In the examples below, the Crafter crafts:

329 Lapis Shards from 36 Lapis (expected 324)
146 Lead Nuggets from 16 Lead (expected 144)
292 Gold Nuggets from 32 Gold (expected 288)
585 Iron Nuggets from 64 Iron (expected 576)

(This is using the Infinity 1.5.1 modpack with Compact Machines added.)

![2015-05-16_22 00 26](https://cloud.githubusercontent.com/assets/5395381/7669165/72e7a1c2-fc18-11e4-8d58-af29751c0529.png)
![2015-05-16_22 00 30](https://cloud.githubusercontent.com/assets/5395381/7669166/77aff61e-fc18-11e4-8d79-9afee203db4a.png)
![2015-05-16_22 00 37](https://cloud.githubusercontent.com/assets/5395381/7669167/78cb5296-fc18-11e4-934e-629e117671ee.png)
![2015-05-16_22 01 00](https://cloud.githubusercontent.com/assets/5395381/7669168/7a1aa106-fc18-11e4-80ce-0620e4bdc6d8.png)
![2015-05-16_22 01 21](https://cloud.githubusercontent.com/assets/5395381/7669169/7b624c12-fc18-11e4-8478-fef89832866a.png)
![2015-05-16_22 01 23](https://cloud.githubusercontent.com/assets/5395381/7669170/7cc95e56-fc18-11e4-9663-99880f3eaf07.png)
![2015-05-16_22 04 04](https://cloud.githubusercontent.com/assets/5395381/7669171/7e280d06-fc18-11e4-8d23-00ed25a212cf.png)
![2015-05-16_22 04 08](https://cloud.githubusercontent.com/assets/5395381/7669173/7f6df568-fc18-11e4-90aa-edcac8fab963.png)
![2015-05-16_22 04 25](https://cloud.githubusercontent.com/assets/5395381/7669174/80b6a32a-fc18-11e4-919c-3f59a7e9bf11.png)
![2015-05-16_22 08 16](https://cloud.githubusercontent.com/assets/5395381/7669176/820ada3e-fc18-11e4-9d12-c21d0e8db75b.png)
![2015-05-16_22 08 22](https://cloud.githubusercontent.com/assets/5395381/7669177/8423a4b8-fc18-11e4-9020-360772358ac7.png)
![2015-05-16_22 08 45](https://cloud.githubusercontent.com/assets/5395381/7669178/852a7e4a-fc18-11e4-890d-e9ea4a75482b.png)

**Comment by McJty** [comment]
Hmm, perhaps that's why everyone likes my crafter so much :-)
I'll check it out to see where this duping comes from.

**Comment by McJty** [comment]
Fixed in next release
