### ISSUE TITLE
Crafter pulls in items that it can't use.

### ISSUE THREAD

**Issue by Lodran** [McJty/RFTools#180]
The crafter accepts items into its inventory which it cannot use, resulting in clogged inventory slots, and wasted materials.

**Comment by McJty** [comment]
That's not really a bug. It is up to the conduits putting things into the crafter to avoid this problem. The crafter does not automatically pull from nearby inventories. You should make sure the conduits feeding the crafter only send items into the crafter that it needs.

**Comment by Lodran** [comment]
Other crafter's (and most other machines for that matter) don't operate this way, and are far easier to manage and configure as a result.

As an example, a pulverizer will not accept items that it cannot process.

Even though they're slower, I'm using EnderIO crafters instead of yours because of this and because you can configure them to better manage input materials.

**Comment by McJty** [comment]
In 2.92 there will be a new item filter that you can insert in a crafter. In this filter you will be able to configure what goes in the inventory. So it is not automatic but at the very least it is now possible to restrict items to that inventory more easily.
