### ISSUE TITLE
Dimlet Oredictionary

### ISSUE THREAD

**Issue by Keridos** [McJty/RFTools#182]
Can you please add an oredictionary entry for known dimlets so we can easily sort them via Oredictionary based stuff? In AE we currently have to add ALL dimlets to an export bus or storage bus in order to sort them into a subnet etc. Fuzzy Cards do not work there.

**Comment by McJty** [comment]
That's a nice suggestion. I'll add that for 2.91

**Comment by Keridos** [comment]
You added this in?

**Comment by McJty** [comment]
No not yet. But one question first. Is this actually needed? All known dimlets are a single item with different damage value. Usually you can also filter on 'ignore damage' or something like that. Doesn't that also solve your filter problem?

**Comment by Keridos** [comment]
There is no such function in AE, for example.

**Comment by McJty** [comment]
Ok. Then I'll add oredict support for next version

**Comment by McJty** [comment]
Implemented in next release

**Comment by McJty** [comment]
I had to remove this feature because it allows you to unify 'void' dimlets into (for example) 'efficiency' dimlets with a JABBA barrel. So unfortunatelly it is not possible to register dimlets to the same ore dictionary entry as that allows for cheating with all unifier type blocks. Sorry :-/

**Comment by Keridos** [comment]
Mmh, that is bad, lets see if I manage to make dimlets work with AE systems.

**Comment by thiakil** [comment]
Apologies for necroposting;

Were they implemented as the one entry? e.g. just as 'dimlet'?
Could they be done as e.g. 'dimletVoid', 'dimletEfficiency' type ones and avoid the JABBA issue? (just using the names in you comment as I'm not too familiar with the names)

This would be rather helpful as Extra Cells 2 has an Ore Dictionary Export Bus that supports wildcards - so one could just export as 'dimlet*' for example

**Comment by McJty** [comment]
The problem is that even within the same type (like all dimletMaterial) there are different costs. You don't want to be able to convert a common dimlet into a rare one automatically. So oredictionary support is simply not possible. Different dimlets are not equivalent and ore dictionary means equivalent

**Comment by thiakil** [comment]
Oh for sure. Is it not possible to have entries further specified? e.g. 'dimletMaterialBlah' (for instance because of how your classes are structured)

To me it doesn't really matter if there's only one item type under each entry, just needs to have AN entry with a common prefix for it to work

**Comment by McJty** [comment]
No because it would still convert items that have the same ore dictionary entry to each other and that's what you don't want. i.e. if all copper ore variants are ore dictionaried you can convert one into the other with a barrel. This is something that you don't want to happen with dimlets. Never. i.e. even two material dimlets with the same rarity and cost should not be convertable into each other

**Comment by thiakil** [comment]
Which is why the question about adding more named. So that the entry would be specific to the material/rarity/cost combination

**Comment by McJty** [comment]
Well that would mean thousands of ore dictionary entries and what's the point of that actually? Then you still have to filter on each individual entry (i.e. dimlet)

**Comment by thiakil** [comment]
> This would be rather helpful as Extra Cells 2 has an Ore Dictionary Export Bus that supports wildcards - so one could just export as 'dimlet*' for example

**Comment by thiakil** [comment]
Export in that context is within the AE Network, to be clear
