### ISSUE TITLE
[request] sort-of creative dimension generation?

### ISSUE THREAD

**Issue by mkire** [McJty/RFTools#183]
I'd like a dimension builder that charges RF for building dimensions, but afterwords the dimension is built and will sustain itself, maybe call it an adventure dimension builder?

Thank you for your time.

**Comment by Entoarox** [comment]
Couldnt this simply be done with a creative-only dimlet that forces the dimensions maintenance cost to be 0rf/tick?

**Comment by McJty** [comment]
Implemented in 1.10.2
