### ISSUE TITLE
Keep getting same random dimension

### ISSUE THREAD

**Issue by jforr** [McJty/RFTools#184]
Version 2.80.

Steps:
1. Put empty dimension tab into the enscriber with no dimlets to create a completely random dimension.
2. Hit Store to store the random dimension.
3. Retrieve the dimension.
4. Insert a second empty dimension tab into the enscriber.
5. Hit store.

The second dimension created has all the exact same random attributes as the first.  Using a digit dimlet will still give you a new random dimension, but then you're still limited to a small number of totally random dimensions.

I understand the mechanic behind using the exact same copy of dimlets will give you the exact same dimension, and I think what's going on here is without any dimlets it's just doing that same thing.  This might be more of a feature request, but I'd like a special case scenario where if no dimlets are used, you really truly get a new dimension each time.

**Comment by McJty** [comment]
This is actually as designed. The good way to solve this is to use digit dimlets. These are made specifically for this purpose. Digit dimlets are easy to craft (you don't have to find them) and you can insert as many as you want in a dimension. They also don't add a cost to a dimension.
