### ISSUE TITLE
Crash loading items into modular storage block

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#186]
The following crash occurred when transferring items into a modular storage block:

http://pastebin.com/MRqDeEa4

As of yet no idea if it is reproducible or not. Will test further as soon as I have access to the system again.

**Comment by sciguyryan** [comment]
Further testing reveals that I can no longer access the contents of the modular storage block at all. Attempting to access it crashes each time with the same error.

I may need to roll my world back in order to ensure the dimlets stored were not lost.

**Comment by McJty** [comment]
I will check this out.

**Comment by McJty** [comment]
This is actually easy to fix. You don't have to rollback but you can use the next dev build and access your chest again. Hold on.

**Comment by McJty** [comment]
The issue should be fixed and you can restore your contents by using the latest version here:

https://drone.io/github.com/McJty/RFTools/files

Let me know if that helps and then I can close this.

**Comment by sciguyryan** [comment]
Hey man.

Thanks for the quick response and fix. It does indeed appear to have fixed it!
