### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by chrizfilmz** [McJty/RFTools#1896]
17.01 09:34:50 [Server] Server thread/WARN [FML]: RFTools loaded a new chunk [-4, 35] in dimension -1 (the_nether) while populating chunk [-4, 36], causing cascading worldgen lag.
17.01 09:34:50 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
17.01 09:35:12 [Server] Server thread/INFO [railcraft]: Saving 269 Trains...
17.01 09:35:31 [Server] Server thread/WARN [FML]: RFTools loaded a new chunk [47, 4] in dimension -1 (the_nether) while populating chunk [48, 5], causing cascading worldgen lag.
17.01 09:35:31 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
17.01 09:35:31 [Server] Server thread/WARN [FML]: RFTools loaded a new chunk [47, 5] in dimension -1 (the_nether) while populating chunk [48, 6], causing cascading worldgen lag.
17.01 09:35:31 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by josephcsible** [comment]
Probably not actually caused by RFTools. See if you can reproduce the problem with no other mods installed.
