### ISSUE TITLE
[DUPE] You can dupe any item in a Shield projector

### ISSUE THREAD

**Issue by Moumix3** [McJty/RFTools#190]
If you put an item in the camouflage slot of a Shield projector (any tier), then break the Shield projector, this item will drop on the ground along with the Shield projector. If you place the Shield projector again, the item will still be inside it, and you'll have 2 copies of that item.

This can be used to duplicate any item, enchants included, and bag content included too.

**Comment by McJty** [comment]
Oops. I will fix that :-)

**Comment by McJty** [comment]
Fixed in next version
