### ISSUE TITLE
Crash when using charged porter

### ISSUE THREAD

**Issue by bonnedav** [McJty/RFTools#1905]
Issue description: I used charged porter and it crashed.

Steps to reproduce: Use charge porter. idk.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2811
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.1.1
* RFTools: 7.60

Possibly incompatible mods and versions: OptiFine HD_U_E3 in use. was working fine.

Relevant logs, if any: https://paste.dimdev.org/uhakoserar.mccrash

**Comment by josephcsible** [comment]
The charged porter doesn't always crash the game, so that's not a sufficient reproduction step. Under what circumstances exactly did you use it? What dimension were you trying to teleport to with it?

**Comment by McJty** [comment]
As far as I can see this can only happen if the charged porter was linked to something in a dimension that has since been removed. I can add protection for that situation but it would indeed be nice to know exactly when you had this issue

**Comment by bonnedav** [comment]
was trying to go to mineing dimension.

**Comment by bonnedav** [comment]
i wish i could rember. i i know is i teleported and i usily works but this time it just crashed for some reason.

**Comment by bonnedav** [comment]
ok. turns out, an update to the mod caused the dimension to be reset. so the destination was missing. Thank you. Maby go ahead and add that protection so stuff like that does not make it crash anymore.
