### ISSUE TITLE
core of dimensional transceiver visible trough partly transparant blocks

### ISSUE THREAD

**Issue by cheesehead544** [McJty/RFTools#1912]
Issue description:
the green core thing inside dimensional transceivers is visible trough partly transparant block(borders of some glass, etc). i'm not entirely sure if this is a problem of those blocks or this mod and it's not really a big deal, so if it's too much trouble you can just leave it as it's only a minor graphical glitch.
 
![2019-02-28_16 07 56](https://user-images.githubusercontent.com/32103720/53572176-ef5e0800-3b6a-11e9-8ddc-56c9cbf13712.png)

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.7
* RFTools: 7.59

Possibly incompatible mods and versions: 
optifine, tested without and with fast math and fast rendering(and all combinations) and foamfix

Relevant logs, if any:

**Comment by McJty** [comment]
Dimensional Transceiver is not from RFTools

**Comment by cheesehead544** [comment]
derp, sorry
