### ISSUE TITLE
Mass Transmitter and Charged Porter not working

### ISSUE THREAD

**Issue by jefferyrlc** [McJty/RFTools#1914]
Issue description: When environmental controller is placed in the world, trying to use a charged porter or mass transmitter does nothing. Breaking the environmental controller and trying to use these works, then immediately stops when the environmental controller is placed again.

Steps to reproduce: Build a teleport network using Mass Transmitters/Mass Receivers. Place an environmental controller. Attempt teleportation with the Mass Transmitter.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2815
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.1.1
* RFTools: 7.61

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Um, that is extremely weird. These blocks don't have anything to do with each other. Unless... Are there any modules in the environmental controller? Can you show the gui of that one?

**Comment by jefferyrlc** [comment]
yes here you go
![screenshot_3](https://user-images.githubusercontent.com/18264856/53893470-3f6e1c00-3ffc-11e9-981f-151e2cd480ef.png)

**Comment by jefferyrlc** [comment]
It appears to be the no teleport module causing it. I tried adding and removing modules, and I think I isolated it down to that.

**Comment by McJty** [comment]
Yes, that's normal. That's exactly what that module does.
