### ISSUE TITLE
Modular Storage Scroll Wheel Issues

### ISSUE THREAD

**Issue by Kyle873** [McJty/RFTools#192]
When using the Modular Storage in item grid mode and you scroll up or down with your mouse inside the storage window while it is highlighting any item, it will pull items into your inventory while also scrolling the window up and down. This is quite annoying and I assume it's not intentional behavior.

**Comment by McJty** [comment]
Yes I know. This is actually NEI doing that. Try using the scrollwheel in a normal chest. The same happens. I have to find a way to disable this.

**Comment by Kyle873** [comment]
In a normal chest it's not such an issue though, since there's never actually any scrolling.

**Comment by McJty** [comment]
I know. That's why I would like to disable it in my storage system.

**Comment by savagealien** [comment]
AE2 uses Shift+scroll (or RClick) to allow +1/-1 item increments, or how about a thicker scroll bar and allow scrolling only when the mouse is over that area.

**Comment by McJty** [comment]
Yes, adding my own functionality is not a problem. The problem is having NEI *not* doing that scrollwheel thing anymore.
