### ISSUE TITLE
No connection between RFTools Dialing Devicec / Matter Transmitter and OpenComputers 

### ISSUE THREAD

**Issue by ZyorTaelon** [McJty/RFTools#1924]
Issue description: RFTools Dialer / Matter Transmitter won't connect to OpenComputers.

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 12.23.5.2808 (also tried 14.23.5.1823 same results)
* McJtyLib: 1.12-3.1.1
* RFTools: 1.12-7.61

OptiFine: 1.12.2_HD_U_E3

Also tried without any other mods. Same results.

Relevant logs, if any: 
I've setup a Matter Transmitter / Receiver / Dialing Device combo and an OpenComputers computer.
![image](https://user-images.githubusercontent.com/1486566/54908505-595a9a80-4ee8-11e9-9b1f-90b6ff880533.png)

No matter how I connect the computer (sides touching, OpenComputers cable) no rftools opencomputers API show up in the components listing.
![image](https://user-images.githubusercontent.com/1486566/54908602-932ba100-4ee8-11e9-80f3-10704dfe6d11.png)

**Comment by josephcsible** [comment]
You're missing the OpenComputers Adapter block. Add it between the computer and the RFTools stuff, and the components should appear.

**Comment by ZyorTaelon** [comment]
Thank you! That was the missing piece of informationI couldn't find anywhere :)
