### ISSUE TITLE
Client crash when interacting with storage scanner

### ISSUE THREAD

**Issue by Nsixtyfour** [McJty/RFTools#1929]
Issue description: 
Client keeps crashing when interacting with Storage Scanner or Storage Tablet connected to it.

I'm playing Enigmatica2Expert-1.59a and was crafting some Arcane Stone in the Storage Table connected to a Storage Scanner. It crafted a bunch, but when I started removing the recipe out of the crafting grid, after clicking some of the stone to remove it this started.

I have restarted both server and client, picked up the storage scanner and placed it back down in a different spot away from the storage modules, but neither helps. I can still interact with the storage modules themselves just fine. Just interacting with the storage scanner or the table connected to it causes the client to crash.

Steps to reproduce: 
Try the above?

Versions:
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2781
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.1.1
* RFTools: rftools-1.12-7.61

Possibly incompatible mods and versions: 

Can't really remove mods, it will break the pack.

Relevant logs, if any: 
https://pastebin.com/aiK8Aje0

**Comment by McJty** [comment]
It is crashing in Thaumcraft so you better report it to them

**Comment by Nsixtyfour** [comment]
Ok, I submitted the issue with them, thank you for the quick response.
