### ISSUE TITLE
[Redstone Transmitter/Receiver Bug]

### ISSUE THREAD

**Issue by whitestarx0312** [McJty/RFTools#193]
Forge: forge-10.13.3.1401
RF Tools: 2.93
I am using Fastcraft/Optifine

I crafted both the transmitter and receiver but can't seem to link them together. I placed my Transmitter as shown below and right clicked it with a receiver to link them. The transmitter is set to channel 1 but upon right click it sets my receiver to -1. I crafted a new set and it just does the same thing.

Trans: http://imgur.com/AC1Ptha
Receiv: http://imgur.com/KrSMBij
* I checked my logs, but the only thing coming up upon my attempted linking is inventory tweaks spam.

**Comment by McJty** [comment]
That's weird. I cannot reproduce this. Are you using shift-right click with the receiver on the transmitter?

**Comment by whitestarx0312** [comment]
Yes I am. I should mention that I added RF Tools to my world after having played on it for some time. I'm not sure if this would cause a problem, but it has caused issue with Thermal Dynamics before so just thought I should mention it.

**Comment by McJty** [comment]
Being added later should be no problem. Very weird that you get this. It works perfectly fine for me and I haven't had any reports of this failing before.

**Comment by whitestarx0312** [comment]
Alright. I moved the transmitter away to a different location and it let me correctly sync it with a receiver. Is there anything in the screenshot that would mess up the syncing?  Perhaps being placed down and already receiving a redstone signal before being hooked up to a receiver. 

Not sure what the problem was but it seems to be fixed.

**Comment by McJty** [comment]
Weird. No explanation atm I'm afraid

**Comment by whitestarx0312** [comment]
Alright well all is well now. Thanks for the quick response. :)
