### ISSUE TITLE
Dupe bug with Storage Scanner and Astral Sorcery Ritual Pedestal

### ISSUE THREAD

**Issue by AaronPena1** [McJty/RFTools#1930]
Issue description: I found a bug where you can duplicate items using the Storage Scanner and the Astral Sorcery Ritual Pedestal. It seems to work with any item, regardless of if it can be inserted into the pedestal normally or not. I originally posted this over on the AS GitHub HellFirePvP/AstralSorcery#1061 and was suggested to post here

Steps to reproduce: 
1. Set down a AS Ritual Pedestal, RFTools Storage Scanner, feed the scanner power.
2. In the Storage Scanner UI, increase the scan radius to pick up the pedestal, then scan, then make the pedestal a routable inventory.
3. Insert into the blue slot of the scanner the item you want to dupe (or shift+click)
4. Click the item out of the scanner UI in the upper right.
5. Go to the ritual pedestal and shift right click to remove a duplicated item.

Versions:
* Minecraft: 1.12
* Forge: 14.23.5.2825
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 3.1.1
* RFTools: 7.61
* Astral Sorcery: 1.10.12

* Baubles 1.5.2 (Dependency for AS) 
* JEI 4.15.0.268 (Just for getting items easier, doesn't impact the bug)

Possibly incompatible mods and versions: 
No Sponge or Optifine

Relevant logs, if any: 
No relevant logs I believe.

**Comment by AaronPena1** [comment]
Looks like HellfirePvP did a fix on Astral Sorcery's side. Going to close this out.

**Comment by AaronPena1** [comment]
Alright, sorry to reopen this again. I tested again with the new release and now getting a crash if I try to open the Storage Scanner near a pedestal. Only change from above version wise is Astral is now at release 1.10.13. 

Crash log here:
https://pastebin.com/D3MGukKL

**Comment by McJty** [comment]
Please reopen on Astral Sorcery side. That crash happens there

**Comment by AaronPena1** [comment]
Closing, sorry for the trouble.
