### ISSUE TITLE
[1.10] Builder's preview inside an Advanced Rocketry pressurised area freezes the server

### ISSUE THREAD

**Issue by Mac15001900** [McJty/RFTools#1934]
Issue description: 
When using the builder in an Advanced Rocketry dimension that doesn't have an atmosphere, but inside an area that has been pressurised, enabling the preview freezes the server. Client-side seems to be unaffected.

Steps to reproduce: 
1. Go to an Advanced Rocketry dimension that doesn't have an atmosphere
2. Build an enclosed space and pressurise it
3. Put a builder inside that area and place a shape card inside.
4. Enable support/preview mode.

Versions:
* Minecraft: 1.10
* Forge: 12.18.3.2511
* CompatLayer: 1.10-0.3.1
* McJtyLib: 1.1x-2.5.3
* RFTools: 1.1x-7.16
* Advanced Rocketry: 1.2.5a

No relevant logs; the server freezes completely and doesn't print anything in the console.

I don't know if this is even possible to fix, but it would be nice if the preview just refused to render in this situation rather than causing the server to freeze. This might avoid future players having to restart the game multiple times to diagnose the issue.

**Comment by McJty** [comment]
Without knowing why it is freezes it is hard to detect for this and prevent the preview from forming

**Comment by McJty** [comment]
Also I just notice this is for 1.10. Please upgrade to 1.12. 1.10 is old
