### ISSUE TITLE
[Suggestion] Charged Porter QoL enhancement

### ISSUE THREAD

**Issue by Karmacopper** [McJty/RFTools#1936]
A config option (if it is even possible) to disable shift clicking the porter out of the player's inventory.

Reasoning:

"Oops I accidentally EMC'd my porter !"
"OMG I just Ender Pouched my porter into my RS/AE storage in another dimension !"

**Comment by McJty** [comment]
I don't think that's possible. At least I wouldn't know how

**Comment by MichaelHillcox** [comment]
Hmm, I see where the recommendation would come for but there may be a lot of instances you'd want to shift click the porter into a place. You'd be better off disabling the emc on the item if you have it. Other than that, be careful! haha. It would be a big ask to interfere with every mods Gui events.
