### ISSUE TITLE
Killed when entering dimesion

### ISSUE THREAD

**Issue by TFGlass** [McJty/RFTools#1941]
Issue description: 

Steps to reproduce: 

Versions:
* Minecraft: 1.7.10
* Forge: 10.13.4
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:4.13

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Did the dimension have enough power? What was the kill message? How much RF/t does the dimension consume? More info please!

**Comment by TFGlass** [comment]
> Did the dimension have enough power? What was the kill message? How much RF/t does the dimension consume? More info please!

Death message is killed be magic this is happening to 2 of my dimensions now. The power cost is 18k i have a rector that puts out 150k rf plus another that puts out 50k both charging it.

**Comment by McJty** [comment]
And is the dimension builder chunkloaded? And the dimension tab still in it? Also are your cables capable of actually inputting that much RF/t into the dimension builder?

**Comment by TFGlass** [comment]
> And is the dimension builder chunkloaded? And the dimension tab still in it? Also are your cables capable of actually inputting that much RF/t into the dimension builder?

Yes Yes And Yes

**Comment by McJty** [comment]
Show me a screenshot of the dimension builder GUI. Also show me the tooltip of the realized dimension tab

**Comment by TFGlass** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/50131968/56947832-51e86b80-6afc-11e9-81f8-dcfa11833f87.png)

i dont know what you mean with the builder gui sorry

**Comment by McJty** [comment]
The builder gui is the user interface of the dimension builder. It is what you have open but covered by the big tooltip

**Comment by McJty** [comment]
How are you chunkloading the dimension builder? Can I also show how the cables are connected to the builder?

**Comment by TFGlass** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/50131968/56948017-d1763a80-6afc-11e9-8036-42c242fa6969.png)

**Comment by TFGlass** [comment]
it was working fine for hours then started doing that

**Comment by McJty** [comment]
Ah! I guess the matter receiver in the other dimension ran out of power!

**Comment by McJty** [comment]
You can put a booster next to the matter transmitter in the overworld to get around that problem. But you should make sure the receiver in the other dimension doesn't run out of power

**Comment by TFGlass** [comment]
i just place the booster next to the transmitter?

**Comment by McJty** [comment]
yes

**Comment by McJty** [comment]
I mean the Matter Booster. Not the other one

**Comment by TFGlass** [comment]
wait where do i put the booster i still dies with it next to the transmitter

**Comment by McJty** [comment]
Hmm. I need more screenshots. Show the builder and how it is connected to everything. Show the matter transmitter + booster. Show the dialer and do a 'check' on the destination

**Comment by TFGlass** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/50131968/56948601-a5f44f80-6afe-11e9-8290-5dcff671920a.png)
![Screenshot_24](https://user-images.githubusercontent.com/50131968/56948604-a987d680-6afe-11e9-9a64-c152aed836f3.png)
![Screenshot_25](https://user-images.githubusercontent.com/50131968/56948609-ac82c700-6afe-11e9-8ade-dc792be83fd1.png)

**Comment by McJty** [comment]
The matter booster must *touch* the matter transmitter

**Comment by TFGlass** [comment]
![Screenshot_26](https://user-images.githubusercontent.com/50131968/56949084-f4eeb480-6aff-11e9-9fc1-c442a8fbe885.png)
that work?

**Comment by McJty** [comment]
it should

**Comment by TFGlass** [comment]
it worked thank you i got power to it

**Comment by McJty** [comment]
Glad you got it working
