### ISSUE TITLE
rftools-1.12-7.70 sets maximumBlocks=5000 if a new rftools.cfg is generated

### ISSUE THREAD

**Issue by sandalle** [McJty/RFTools#1944]
Issue description: Default rftools.cfg sets `maximumBlocks=5000`

Steps to reproduce: Delete rftools/rftools.cfg and restart server. New rftools/rftools.cfg is generated with the absurd `maximumBlocks` value of `5000`. :)

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2836
* McJtyLib: mcjtylib-1.12-3.5.0
* RFTools: rftools-1.12-7.70

Possibly incompatible mods and versions: None?

Here's the _diff_ from the rftools.cfg generated by rftools-1.12-7.61 and mcjtylib-1.12-3.1.1:
```
-    # Maximum amount of blocks to show in monitor (do NOT increase above 1800!)
-    I:maximumBlocks=500
+    # Maximum amount of blocks to show in monitor (do NOT increase above 1800!) [range: 0 ~ 1800, default: 5000]
+    I:maximumBlocks=5000
```
I think you intended this to be 500. ;)

**Comment by McJty** [comment]
Fixed next release
