### ISSUE TITLE
[1.12.2] Crash while entering Nether

### ISSUE THREAD

**Issue by Draskh** [McJty/RFTools#1945]
Steps to reproduce: 

Build a portal and enter the nether. The ore spawn crashes. I thought I had disabled it. I'm not able to join the world anymore although I deleted the nether in saves folder.

Versions:
* Minecraft: 1.12.2
* Forge: 2836
* McJtyLib: 3.5.0
* RFTools: 7.70

Relevant logs, if any: 
[crash-2019-05-04_16.12.57-server.txt](https://github.com/McJtyMods/RFTools/files/3144524/crash-2019-05-04_16.12.57-server.txt)
[crash-2019-05-04_16.39.00-server.txt](https://github.com/McJtyMods/RFTools/files/3144525/crash-2019-05-04_16.39.00-server.txt)
[crash-2019-05-04_16.58.46-server.txt](https://github.com/McJtyMods/RFTools/files/3144526/crash-2019-05-04_16.58.46-server.txt)

Here are the configs:
https://pastebin.com/hPR6JtdU RFTools Dimensions
https://pastebin.com/L8mEGVNk RFTools

**Comment by Draskh** [comment]
I can confirm. I graded down to the version before 27 April and this solved the crash,

**Comment by josephcsible** [comment]
I fixed the off-by-one error that's the real cause of the crash. It will take effect in the next version of RFTools. However, you shouldn't have been hitting that; the only reason that you were is that you're using an outdated config file format. Delete your config and let it regenerate (then restore your settings to it).
