### ISSUE TITLE
Storage scanner and tablet issue

### ISSUE THREAD

**Issue by Nila24** [McJty/RFTools#1948]
Issue description: 

Storage scanner "Export to first routable container" setting can not be changed / switched off neither locally neither via tablet remotely. 

Tablet with Storage control screen module is able to retrieve items, but not push any items into inventories connected to storage scanner. The items would just sit in input slot. Depositing items directly on storage scanner works as intended. 

Tablet also works properly (can retrieve and deposit items) with remote storage module or local storage module attached. 

Steps to reproduce: 
Just new world, plop scanner, modular storage, get tablet and module. 

Versions:
* Enigmatica 2 expert mode modpack 1.63a.
* Minecraft: 1.12-7.70
* Forge: 14.23.5.2815
* McJtyLib: 1.12-3.5.0
* RFTools: 1.12-7.70

**Comment by McJty** [comment]
Show some screenshots of the scanner gui and also the tablet

**Comment by Nila24** [comment]
The whole setup
![image](https://user-images.githubusercontent.com/13526129/57630247-edbab280-75a5-11e9-8068-399ae3fd2a57.png)

Storage scanner
![image](https://user-images.githubusercontent.com/13526129/57630330-13e05280-75a6-11e9-8453-b61975bf6115.png)

Storage tablet with item not leaving input slot
![image](https://user-images.githubusercontent.com/13526129/57630407-383c2f00-75a6-11e9-9983-90798d345563.png)

**Comment by McJty** [comment]
Hmm, that's weird. Never seen that before. Does it work with other items?

**Comment by Nila24** [comment]
Also when I extract items via tablet they are not displayed in either output slot or in fact in my inventory. I have to close tablet for them to appear in my inventory. 

If I place anything into the slot where item normally goes when retrieved before I close the tablet then it would allow me as if these slots are empty, but as soon as I close the tablet inventory will revert to the state before I placed anything in "to be occupied" slots. 

It is relatively easy to crash the game while fiddling with tablet - trying to craft or move items around. 
https://pastebin.com/6wL43R77

That said the first mod in crash report is not rftools, but rather quark. Hmmm....

I do realize it is extremely unlikely that error is in rftools feature that has been around forever.

**Comment by Nila24** [comment]
I probably should put a ticket on modpack page and not with rftools. For some reason I did not thought about it. I do watch a lot of youtubers with Enigmatica 2 expert and none that I saw used rftools tablet at all. In fact the last pack I saw people do that probably was still in 1.7

**Comment by Nila24** [comment]
None of the items can be inserted via tablet, but any of them can via storage scanner interface when used directly.

Also crafting, etc works when directly interfacing storage scanner and game does not crash. The only thing that does not work is that "Export to first routable container" star thingy in the bottom.

**Comment by Nila24** [comment]
Registered the issue with Enigmatica 2 at https://github.com/NillerMedDild/Enigmatica2Expert/issues/1187
I will close the issue if NillerMedDild can fix it and vice versa. Sorry to bother both of you guys. Unfortunately my programming experience is not enough to be of any use in MC and Java :-(

**Comment by NielsPilgaard** [comment]
I've been testing the issue, and I was only able to reproduce this:

> Storage scanner "Export to first routable container" setting can not be changed / switched off neither 
> locally neither via tablet remotely.

For some reason, you can only change that setting by pressing both right and left mouse buttons at the same time, which seems like a bug.

Everything else works as it should, as long as the blocks are linked and powered.

**Comment by Nila24** [comment]
It would seem that the tablet problem was with my specific copy of 1.63a instance. Gone after upgrading. I guess bit rot is still a thing. 

Requiring double mouse button is weird, for sure, but as long as I know how to do it I am fine. Might want to fix it on some rainy day though...
