### ISSUE TITLE
[request]make Evoker spawnable with the spawner

### ISSUE THREAD

**Issue by jefferyrlc** [McJty/RFTools#1949]
Issue description: Adding an evoker syringe to the spawner currently spits out nullRF. Please add the ability to spawn the evoker with the spawner system.

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.1.1
* RFTools:  1.12-7.61

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
Can't you just do this by editing the config? If you can't, post your configfile so I can see how you tried to add it.

**Comment by jefferyrlc** [comment]
yeah somehow I didn't do it right, here's my file
[rftools.zip](https://github.com/McJtyMods/RFTools/files/3204886/rftools.zip)

**Comment by josephcsible** [comment]
The Evoker is `minecraft:evocation_illager`, not `minecraft:evoker`.
