### ISSUE TITLE
Server Ticks took 60.00 secondes

### ISSUE THREAD

**Issue by MinoCraft** [McJty/RFTools#1950]
Hello,

Issue description: 
I don't why or Idon't know wich mods but sometimes, when I'm using one of your mods the server crash, you can see the crash report for more information: 
https://www.dropbox.com/s/ev3jyo6uuwuq2ra/crash-2019-05-21_23.15.58-server.txt?dl=0
https://www.dropbox.com/s/7igxsanr62ack36/crash-2019-05-21_23.45.44-server.txt?dl=0

Steps to reproduce: 

When the server crash, I'm using Xnet or RF Tools Control (I think XNet cause this issue) but the crash report shows me that the problem comes from RF Tools.
Since this afternoon, I'm using the old version of your mods and I've not crash until now. 
You can see that ? ^^

Versions:
* Minecraft: 1.122
* Forge: 14.23.5.2836
* McJtyLib: 3.0.6 Also, I've tested with the last version and the crash is faster
* RFTools: 7.56 Also tested with the last version and the crash is faster

I'm using Optifine 1.12.2 HD-U-E3

https://pastebin.com/fasqtZwB
https://pastebin.com/EKk814W5

Thanks in advance !

**Comment by josephcsible** [comment]
Are you sure you didn't get your crash reports mixed up? You say OptiFine was installed, but those are dedicated server crashes. Also, what does "the crash is more speed" mean? Can you post crash reports from the newer versions?

**Comment by MinoCraft** [comment]
I don't know why I gave Optifine version, the crash is on server ^^"
"the crash is more speed" , not speed but faster ^^I forgot the word sorry  
Currently updating client and server with the last mods version to test again.
If I've news, I post crash report again ;)
Posted Crash reports is right one
Thanks

**Comment by MinoCraft** [comment]
I've tested with last mods version (download with Twitch desktop appli) and the same for forge 
Forge: 14.23.5.2838
Mc Jty Lib: 3.5.2
RF Tools: 7.71
RF Tools Ctrl: 2.0.2
XNet: 1.8.1

I don't understand how but I've 2 crash reports in the same time as you can see =S
https://www.dropbox.com/s/7s9yqdx0sfyr0of/crash-2019-05-22_01.50.40-server.txt?dl=0
https://www.dropbox.com/s/g3t9ek4oidwjct5/crash-2019-05-22_01.50.42-server.txt?dl=0

How the crash happens, I really think the problem comes from XNet, but I'm not sure ^^"

Thanks for your help ;)

**Comment by josephcsible** [comment]
I suspect that your actual problem is filesystem corruption. Commit [3ef3e52](https://github.com/josephcsible/RFTools/commit/3ef3e52e4de346848c0bd666b5831b24457bfac0) has some logging for it. Try this build, then upload the log it gives.

[rftools-1.12-7.71+g3ef3e52.jar.zip](https://github.com/McJtyMods/RFTools/files/3205202/rftools-1.12-7.71%2Bg3ef3e52.jar.zip)

**Comment by MinoCraft** [comment]
I've tryed with the rftools version inside the zip file.

On client side, I must disabled FoamFix otherwise client crash as you can see with this report:
https://www.dropbox.com/s/8uqti1lw1bugnpk/hs_err_pid9956%28with%20FoamFix%29.log?dl=0

No error with FoamFix on server side, but I was able to move for 5-10 minutes and I've had this crash:
https://www.dropbox.com/s/q1rvah58wtcvjdg/crash-2019-05-22_10.24.04-server.txt?dl=0

I've tryed again always with Waila to see if I've the same issue when the server crash and with the test 2 I've had this report again:
https://www.dropbox.com/s/kg851g3068ary7l/crash-2019-05-22_10.43.02-server.txt?dl=0

I mustn't disabled Waila ?

**Comment by josephcsible** [comment]
Can you upload the full log (not just the crash report) corresponding to the second and/or third crash from that post?

**Comment by MinoCraft** [comment]
Yeap, you can found this here: https://pastebin.com/akUTKBcf
Normally, there are log for the 2 last crash report 

Thanks for your help ! ;)

**Comment by josephcsible** [comment]
See if deleting or renaming /data/service1145/data/service_item_681184/world/rftoolsscans/scan1 fixes it.

**Comment by MinoCraft** [comment]
How can I do this ? I don't understand ^^"
 Forgot this, after reflection I understand ;) deleting san !
After, Can I use again the regular Curse version ?

**Comment by josephcsible** [comment]
If the problem is fixed, then yes, you can use the regular Curse version again.

**Comment by MinoCraft** [comment]
After testing a few hours, the problem is fixed ! Tested with the "patched version" and with the regular curse version.Also, I picked up scanner remote, I'll play with later ^^

Regular updated version works fine with FoamFix, issue about it is only with the patched version ;)

Thanks for your help and your time ;)
I let you closed this issue ;)
