### ISSUE TITLE
Shield Projector Disconnecting players

### ISSUE THREAD

**Issue by tannermon11** [McJty/RFTools#1956]
Issue description: Other player crashes when getting too close to shield that is being generated from shield projector tier 4. I have tried to use both solid as well as the shield for the texture but the other player that is connected will crash when getting within approximately 100 blocks for the x/z coordinates of the outside of the sphere. The other player gets the Connection lost Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.util.ReportedException: Loading NBT data
and will instantly disconnect if they try to log back in and get the same error.

Steps to reproduce: Running minecraft in singleplayer and open to lan and having player connect to it. I have a shape card with Shape Sphere and Dimension 111,111,111 offset 0,0,0 in a tier 4 shield projector. Have other player that is connected approach from far and get closer to it.

Versions:
* Minecraft:  1.7.10
* Forge: 10.13.4.1614
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.8.1.jar
* RFTools: rftools-4.23.jar

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
That's too large. The 1.7.10 version of RFTools doesn't support shields of that size. You'll have to reduce the size

**Comment by tannermon11** [comment]
Thanks for the quick reply however I'm curious when you say it doesn't support that size. It's able to do it just fine and I don't disconnect; it's other players not being able to get near it. Besides that though is there another way to make it so they would be able to be near it / within it like I can?

**Comment by McJty** [comment]
The problem is that the size of the shield exceeds network limits. There is no way around this. You'll have to reduce the shield size. In later versions of the mod I worked around this problem by doing this differently

**Comment by tannermon11** [comment]
Oh that makes sense, last thing then, what would be the version required for minecraft/rftools that would fix the issue. Thanks again for helping.

**Comment by McJty** [comment]
Best is to go to 1.12.2/latest version. Lots of things have been fixed and changed in that version
