### ISSUE TITLE
[Dirt replacing Grass]

### ISSUE THREAD

**Issue by whitestarx0312** [McJty/RFTools#196]
Upon creating several dimensions (with different terrain types only), it appears that some terrain types do not want to spawn grass. They instead spawn dirt, even with foliage on them. This isn't a huge bug, but it is annoying since there is no grass material modifier.

Screenshots: 
Nearlands WITH grass: http://i.imgur.com/nDYNExO.png
Chaotic WITHOUT grass: http://i.imgur.com/glDbKbU.png

**Comment by McJty** [comment]
This most likely has to do with the biome.

**Comment by McJty** [comment]
Closing due to lack of other information. Reopen if you have some more information like biomes and such.
