### ISSUE TITLE
RFTools Builder Exception Ticking World

### ISSUE THREAD

**Issue by auddie2015** [McJty/RFTools#1961]
Issue description:  Turning on or off the support blocks in the builder causes a ticking world crash

Steps to reproduce:  Place a shape card, click one of the directional corners or enter the dimensions in by hand. enter support preview.

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.12-3.5.3
* RFTools: 1.12-7.71

All that is installed is Minecraft, Forge, JEI, RFTools, Xnet, and mcjtylib,
[crash-2019-06-20_02.19.01-server.txt](https://github.com/McJtyMods/RFTools/files/3309041/crash-2019-06-20_02.19.01-server.txt)

[crash-2019-06-20_02.19.01-server.txt](https://github.com/McJtyMods/RFTools/files/3309045/crash-2019-06-20_02.19.01-server.txt)

(I hope I didn't attach it twice. If so, it's small.

**Comment by AzzBlock** [comment]
I have the same problem. Also the preview blocks are persisting after turning off the preview.

**Comment by TheQuadShot** [comment]
Same, but I think I have a better crash log if you need it.
Minecraft 1.12.2
Forge 14.23.5.2838
rftools 1.12-7.71

Mod List: https://pastebin.com/RT9gtjNJ
Crash log: https://pastebin.com/wSrHqPf6
edit: I'm using the quarry shape card when it occurs.

**Comment by McJty** [comment]
Problem is that neither of these crashlogs including anything of my mods so I have no clue what's going on here

**Comment by TheQuadShot** [comment]
Really? The rftools builder isn't yours?

**Comment by McJty** [comment]
It is. But where is the rftools builder mentioned in that crashlog?

**Comment by TheQuadShot** [comment]
well, I'm not exactly sure what you mean, but on line 
159:  mcjtylib_ng                       | 3.5.3                    | mcjtylib-1.12-3.5.3.jar   
165; rftools                           | 7.71                     | rftools-1.12-7.71.jar    
Not to mention it happens almost immediately after I toggle Support/preview mode
and I tried it twice to make sure.

**Comment by Frikkle** [comment]
We just had a user of the Enigmatica 2 pack report this same issue in Discord. I asked them to post their logs in here as well. Same thing though, no reference to RFTools specifically; but it is a reproducable crash using `rftools-1.12-7.71`.

EDIT: they don't have a GitHub account, so let me post it for them [https://puu.sh/DUqAx/4a116d6782.txt](https://puu.sh/DUqAx/4a116d6782.txt)

EDIT2: I asked them to try and reproduce the issue on a server running just RFTools and let us know the results and provide a crash log.

**Comment by Frikkle** [comment]
After testing (by the reporting user at the Enigmatica 2 pack) with an instance using just RFTools, and McJtyLib it is reproducible. Rendering the first preview goes fine; the second one crashes the game.

Corresponding logs: [here](https://pastebin.com/M5DZA57m)

Mods present:
- `forge 14.23.5.2836`
- `mcjtylib 3.5.3`
- `rftools 7.71`

Additional information provided by the user:
```
extremely small previews don't crash
50x20x50 box worked without problems
but a 90x20x90 caused an immediate crash
```

Steps to reproduce:
1. Place down an RFTools Builder.
2. Insert a Shape card with (at least?) a 90x20x90 solid box inside. 
3. Render a support block preview of the structure.

**Comment by McJty** [comment]
Ok. I was finally able to reproduce it. Now I have to figure out what causes it

**Comment by Frikkle** [comment]
If there's anything we can do on our end in terms of testing, please let me know.

**Comment by McJty** [comment]
Found and fixed for next release (very soon)
