### ISSUE TITLE
Elevator module buttons don't work

### ISSUE THREAD

**Issue by ShadowRocks2** [McJty/RFTools#1962]
Issue description: I can't use elevate module buttons but a regular button module I can on screens

Steps to reproduce: make an elevator

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:latest
* RFTools:latest

Possibly incompatible mods and versions: 
I use optifine, can't play without it

Relevant logs, if any:

**Comment by McJty** [comment]
Is the elevator module linked to the bottom elevator? How are you trying to use it? More details please.

BTW, never use 'latest' as version number. That's a bad idea if I decide to look at this issue in a few weeks or so and 'latest' has changed. Please put the correct version there

**Comment by ShadowRocks2** [comment]
Sorry turns out that the clans mod wasn't working right with rftools after removing problem solved itself case closed
