### ISSUE TITLE
Client crash when placing or breaking Scanner

### ISSUE THREAD

**Issue by drewcassidy** [McJty/RFTools#1968]
Issue description: 
the client crashes when placing or breaking the Scanner (not the storage scanner) in the world

Steps to reproduce: 
place or break the Scanner block

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* McJtyLib: 1.12-3.5.2
* RFTools: 1.12-7.71
* FTB Revelation 3.0.1, with the following added:
  * Optifine
  * ae2Stuff
  * ExtraCells
  * Funky Locomotion
  * Mekanism
  * RFtools Dimensions

Relevant logs, if any: 
[Crash log](https://github.com/McJtyMods/RFTools/files/3413103/2019-07-19-1.log)

**Comment by josephcsible** [comment]
Looks like the problem is that `ScannerTileEntity::writeRestorableToNBT` can be called from client-side code, but it calls `getScanId()`, which if `scanId` is 0, ends up in code that's only supposed to be run server-side.

**Comment by McJty** [comment]
Fixed next release
