### ISSUE TITLE
Workbench doesn't use input buffer

### ISSUE THREAD

**Issue by MuresanSergiu** [McJty/RFTools#1969]
Issue description: 
Workbench doesn't use the input buffer when pumping out the result of a recipe thus ruining the recipe after using all the items in the recipe slots.

Steps to reproduce: 
With Pam's Harvestcraft installed, using the recipe for a scrambled egg (1xegg + 1xsaucepan):
1) Place in the recipe slots 1xegg and 1xsaucepan
2) Place in the input buffer a stack of eggs
3) Pump out through the bottom (using BC wooden pipes in my case) the result.
4) Only one scrambled egg is made and only the egg from the recipe slot is used and the recipe is ruined.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.3
* RFTools: 7.71

**Comment by McJty** [comment]
I'm confused. What do you expect to happen instead of 4?

**Comment by MuresanSergiu** [comment]
To use the stack of eggs from the input buffer (at step 2).

**Comment by McJty** [comment]
That's not how the workbench works. It is a regular crafting table. The input buffer is just a convenience and the workbench is not supposed to automatically pull items from it

**Comment by MuresanSergiu** [comment]
I get it now, sorry about that. It just looked like a bug since it's strange to have inventory for a crafting table if it's not gonna be used in the recipes. Can this become a feature request, then?

**Comment by MichaelHillcox** [comment]
If you'd like this to be a feature request then please create a new issue explaining how you'd expect it to work and what the use case is. Please note that it may not be implemented but it will be considered if the use case seems justified enough.
