### ISSUE TITLE
Switch the angle of a Quarry Cylinder 

### ISSUE THREAD

**Issue by Rams59** [McJty/RFTools#1979]
Issue description: 
Not a real issue, just cant get it right. I want to dig a cylinder into a Mountain, but rotate it by 90° (so its hollow around the x-axix . I can see that there is an Option to rotate the angle, but i cant get it to work. Is there a way to do so?

Steps to reproduce: 

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
What are you doing exactly?
