### ISSUE TITLE
[Dimension RF Maintenance Inconsistency]

### ISSUE THREAD

**Issue by whitestarx0312** [McJty/RFTools#198]
I made my aspired dimension in a creative world first so I could make sure it was perfect before making it in my actual world. The two dimensions are exactly the same, except for a swap in thunder values. However the RF maintenance costs of the two dimensions are completely different, and the one in my actual world just doesn't add up right.

Creative information: http://i.imgur.com/s3xDHvP.png
Cost: 351 RF/T
Survival Information: http://i.imgur.com/xCxN9OT.png
Cost: 1845 RF/T

I traveled to both dimensions and they are identical. Nothing is appearing to me that would add such a huge RF cost. Adding up the dimlet costs that I added in, 351 RF/T should be the correct value.

**Comment by McJty** [comment]
The Liquid None versus Liquid Water is probably what caused this. i.e. you used different dimlets there and it is possible that these cost differently (can't check now) even if the end result is the same.

**Comment by whitestarx0312** [comment]
How strange. Thanks for pointing that out, all is fixed after I swapped the liquid dimlets. The difference in maintenance cost is 299 RF/T. Still not sure why the cost wasn't just 650 Rf/T, but instead was 1945 Rf/T.
