### ISSUE TITLE
RFTools Crashes When Using Tools

### ISSUE THREAD

**Issue by PulseBeat02** [McJty/RFTools#1985]
Issue description: 
Using one of the tools leads to this crash.

https://cdn.discordapp.com/attachments/473675514209501184/619722054538756107/crash-2019-09-01_18.18.24-server.txt

Steps to reproduce: 
Use one of the tools, then crash.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 3.5.4
* RFTools: 7.72

I am also using Optifine!

**Comment by McJty** [comment]
Can you be a bit more precise? What is 'using one of the tools'? What exactly were you doing?

**Comment by MichaelHillcox** [comment]
Looking at the log, there was no mention of RFT causing the crash...

**Comment by PulseBeat02** [comment]
@MichaelHillcox @McJty I created a dimension with the dialing device, matter transmitter, dimensional builder, dimensional editor and I tried to spawn in the new dimension. Then it crashed.

**Comment by MichaelHillcox** [comment]
Are you able to reproduce this crash @PulseBeat02 it may have just been another mod catching an edge case and causing a crash unrelated to RFT

**Comment by PulseBeat02** [comment]
Yes, my client was able to reproduce this crash twice.

**Comment by PulseBeat02** [comment]
Anyone have a solution?
