### ISSUE TITLE
Rftools dimension crashed/ stuck multiplayer server

### ISSUE THREAD

**Issue by Zittla** [McJty/RFTools#199]
Okay soi i made a rftools dimension and it was flat dimlet and lapis, when i entered the world it says loading terrain or something and i let it load for like 1 hour and it was still saying loading terrain or wahtever the message was.
Now when i log on again my client just closes and i cant do anything like each time.
Any other server or singleplayer works, even deleted the user data and still i crash and also there is no crash reports in my ftb folder.
this is on Infinity 1.5.1 and dim 135.
I have no idea on what 2 do to fix this any ideas or tips? we tryed jailing me and killing and unpowering the world but i still cant login.

**Comment by Zittla** [comment]
the client closes each time i connect to the server.

**Comment by McJty** [comment]
This bug is fixed in rftools 2.93 (dimensions above 128 don't work in old versions of rftools)

**Comment by Zittla** [comment]
ah okay thank you the server just updated and now it worked :P
