### ISSUE TITLE
Storage Scanner console spam

### ISSUE THREAD

**Issue by craving-death** [McJty/RFTools#1991]
Issue description: Error in console regarding storage scanner is repeated constantly

Versions:
* Minecraft: 1.12.2
* Forge: 2838
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.72

Possibly incompatible mods and versions: 
SpongeForge 1.12.2-2838-7.1.7-RC3928

Relevant logs, if any: 
https://gist.github.com/craving-death/53e4fbf1d4f539995e5d2f50d405888f

**Comment by McJty** [comment]
The problem seems to be in Immersive Engineering. Please report to them
