### ISSUE TITLE
Custom Dimlets (1.7.10)

### ISSUE THREAD

**Issue by AetherDraco** [McJty/RFTools#1993]
Hi, so im trying to add a dimlet for awakened draconium blocks and the dimlet is actually created ingame however its listed as an unknown dimlet and gives the error "Something is wrong! Dimlet with key mtile.draconicevolution:draconicBlock (id 605) is missing!" and ive tried a few different things but im just not sure what exactly im doing wrong, ```[
	[ "material" , "DraconicEvolution" , "draconicBlock" ,0],
]```
That's my userdimlets.json

https://pastebin.com/YhQyAppY

That's my dimlets.cfg

Thanks for any help! Just unsure what im missing

**Comment by MichaelHillcox** [comment]
Hopefully this is an issue with how the custom dimlet has been made as if it is an issue with the code, it won't be fixed for your version on 1.7.10. Someone with more knowledge on custom dimlets should be able to shed some light onto your situation.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
