### ISSUE TITLE
Builder won't go further than the default dimensions and offset

### ISSUE THREAD

**Issue by leolama** [McJty/RFTools#1994]
Issue description: When trying to quarry further than the default dimensions and offset settings. The builder refuses to go past the default limits, even though I've changed the settings to various things, including the maximum.

Steps to reproduce: Place a builder, get a shape card, try to quarry too far away and it will not go further than the default limits.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* McJtyLib: 3.5.4
* RFTools: 7.72

**Comment by McJty** [comment]
Is FTB Utilities in the pack? If yes then that's probably the reason. In that case there is an option in ftb utilities to allow fake players

**Comment by leolama** [comment]
Can I ask what fake players has to do with the limitations of the builder? And is it possible to fix the issue by disabling it somehow?

**Comment by MichaelHillcox** [comment]
You've not answered the question. Do you have FTB Utils in the pack?

**Comment by McJty** [comment]
The Builder is a fake player because it needs to break blocks. This is something that has to be done on FTB Utilities side. There is a config for it. Just make it allow fake players and it should be ok

**Comment by leolama** [comment]
> You've not answered the question. Do you have FTB Utils in the pack?

I tried to imply that I had it with my follow up questions, sorry. FTB Utilities is indeed in the pack.

> The Builder is a fake player because it needs to break blocks. This is something that has to be done on FTB Utilities side. There is a config for it. Just make it allow fake players and it should be ok

I've searched through the files and I'm pretty certain fake players are enabled. I'm not having an issue with the builder not being able to break blocks. I'm having an issue with the builder not being able to designate an area beyond the defaults. I posted this on reddit a while ago and posted these with it, if they help: https://i.imgur.com/vO5Ap4H.jpg https://gfycat.com/niceshamelessaddax

**Comment by McJty** [comment]
That's the same thing. To be able to mark the area it needs to be able to place those preview blocks

**Comment by leolama** [comment]
Ah, okay, sorry. Can I ask for some help with finding the fake players config? The only thing I've been able to find is enabling/disabling logging for them.

**Comment by McJty** [comment]
Hmm actually not sure myself. I have never tried to use it. Just know from others who encountered the same issue

**Comment by leolama** [comment]
Alright, thanks for the help anyway! I'll keep having a look around

**Comment by josephcsible** [comment]
Can you try to reproduce the problem with just RFTools and its dependencies installed?

**Comment by McJty** [comment]
Joseph, this is a known problem with FTB Utilities. No need to do this
