### ISSUE TITLE
RFTools dimlet researcher not in modpack

### ISSUE THREAD

**Issue by rogiervh** [McJty/RFTools#1999]
Issue description:  The machine dimlet researcher is missing in my modpack i also have the mod rftools dimensions installed and isnt there either,
Im also missing the unkown dimlets.

Steps to reproduce: 

Versions:
* Minecraft: 12.2.2
* Forge: 12.2.2
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools:1.12-7.72

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
The Dimlet Researcher no longer exists. The system to make dimlets has changed. Direwolf has a spotlight on how it works now

**Comment by rogiervh** [comment]
Cant u tell me wich modpack to download now ?
Makes it alot easier for me to figure out.\


________________________________
Van: McJty <notifications@github.com>
Verzonden: zaterdag 16 november 2019 14:53
Aan: McJtyMods/RFTools <RFTools@noreply.github.com>
CC: rogiervh <rogier05@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [McJtyMods/RFTools] RFTools dimlet researcher not in modpack (#1999)


The Dimlet Researcher no longer exists. The system to make dimlets has changed. Direwolf has a spotlight on how it works now

**Comment by McJty** [comment]
What modpack? How can I chose a modpack for you? I don't really understand what modpack has to do with this?

**Comment by rogiervh** [comment]
"The Dimlet Researcher no longer exists. The system to make dimlets has changed. Direwolf has a spotlight on how it works now"
So my question is do i need a modpack called "direwolf"? or what do i need to do im kinda lost...
Do i need a modpack for the dimlet researcher replacement? or a different modpack that has it?

Im sorry if im confusing you,

Rogier

________________________________
Van: McJty <notifications@github.com>
Verzonden: zaterdag 16 november 2019 18:20
Aan: McJtyMods/RFTools <RFTools@noreply.github.com>
CC: rogiervh <rogier05@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [McJtyMods/RFTools] RFTools dimlet researcher not in modpack (#1999)


What modpack? How can I chose a modpack for you? I don't really understand what modpack has to do with this?

**Comment by McJty** [comment]
You don't know Direwolf? Ok. That's pretty rare. Direwolf20 is a famous Minecraft youtuber who has made tons of spotlights on various mods. He also spotlighted my mods. You can check it out to see how it works

**Comment by rogiervh** [comment]
Hmm, ok do you have a link for the video i need ?

________________________________
Van: McJty <notifications@github.com>
Verzonden: zaterdag 16 november 2019 18:57
Aan: McJtyMods/RFTools <RFTools@noreply.github.com>
CC: rogiervh <rogier05@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [McJtyMods/RFTools] RFTools dimlet researcher not in modpack (#1999)


You don't know Direwolf? Ok. That's pretty rare. Direwolf20 is a famous Minecraft youtuber who has made tons of spotlights on various mods. He also spotlighted my mods. You can check it out to see how it works

**Comment by McJty** [comment]
https://www.youtube.com/watch?v=SpP9IwqeDv0

**Comment by rogiervh** [comment]
Okay thanks 🙂 and this "mining world dimension" https://www.curseforge.com/minecraft/mc-mods/rftools-dimensions/screenshots is that still possible to get or ?
[https://media.forgecdn.net/avatars/thumbnails/32/918/120/120/635887877634437341.png]<https://www.curseforge.com/minecraft/mc-mods/rftools-dimensions/screenshots>
Images - RFTools Dimensions - Mods - Minecraft - CurseForge<https://www.curseforge.com/minecraft/mc-mods/rftools-dimensions/screenshots>
Costly Mining World. A very op but costly (RF power) mining world. Rough. This is a rough terrain. Good luck navigating this. Terrible. Lots of baddies fighting each other and you
www.curseforge.com


________________________________
Van: McJty <notifications@github.com>
Verzonden: zaterdag 16 november 2019 19:06
Aan: McJtyMods/RFTools <RFTools@noreply.github.com>
CC: rogiervh <rogier05@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [McJtyMods/RFTools] RFTools dimlet researcher not in modpack (#1999)


https://www.youtube.com/watch?v=SpP9IwqeDv0
