### ISSUE TITLE
[1.12.2] Enderman TP out of Shield despite having E.Controller with TP Blocking

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/RFTools#2002]
Forge:  *.2847
rftools: 7.72
mcjtylib: 3.5.4

Currently(as seen below in pic) i have the Environmental Controller right next to the shield with quite ample power and the No Teleport Environmeantal Module installed, Radius @ 100 Height between 60-100 & a Tier 3 Projector(non infused)....With this setup currently 1 in 2 enderman spawned still manage to TP out of the shield area which is set to hostile solDmg, dmg done as player.

![2019-11-27_18 22 24](https://user-images.githubusercontent.com/10524952/69706568-ba0b3880-1143-11ea-9843-961efe596dd3.png)
![2019-11-27_18 28 48](https://user-images.githubusercontent.com/10524952/69706594-c394a080-1143-11ea-9912-d15a87ede551.png)
![2019-11-27_18 28 59](https://user-images.githubusercontent.com/10524952/69706609-ca231800-1143-11ea-8eba-cacd54132280.png)

**Comment by josephcsible** [comment]
Why did you close this? If you figured out the problem, can you post the solution here for the benefit of other users who search for similar problems?

**Comment by McJty** [comment]
We were discussing this on discord but he forgot to configure the environmental controller to handle mobs as opposed to players

**Comment by Morpheus1101** [comment]
Lack of knowledge on my part not realizing that part was actually toggleable on the controller
