### ISSUE TITLE
[1.12.2] NullPointerException: Exception in server tick loop when trying to create a SP World

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/RFTools#2004]
rftools: 7.72
mcjtylib: 3.5.4
Forge: *.2847

To re-create i go into SMP and attempt to go into a liquid world made of molten ender but die to a collapsing world, i then exit SMP, go into SP and when trying to create a world the client crashes with this crash log https://pastebin.com/XMvtBctT

**Comment by josephcsible** [comment]
Duplicate of McJtyMods/RFToolsDimensions#205
