### ISSUE TITLE
random server crashes

### ISSUE THREAD

**Issue by Nbgreen** [McJty/RFTools#2005]
Issue description: 
random server crashes
Steps to reproduce: 
N/A
Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* McJtyLib: 1.12-3.1.1
* RFTools: 1.12-7.61
* SpongeForge: 1.12.2-2768-7.1.6-RC3616

Relevant logs, if any:  
https://paste.dimdev.org/azumivavop.sql

**Comment by McJty** [comment]
It is crashing in Mekanism. Please report to them

**Comment by josephcsible** [comment]
I don't necessarily agree that this is Mekanism's fault. Looking through the code, it seems that what must have happened is that a BlockPos ended up with one of their blocks, but one of our TEs.

I see Sponge was installed, and that's always my first suspect for odd culprits like this one.
