### ISSUE TITLE
Crash when trying to render rftools utility screen

### ISSUE THREAD

**Issue by phi1ip83** [McJty/RFTools#2009]
Issue description: 
Every time the client trys to render an rftools screen, the client crashes
Steps to reproduce: 
-try to render an rftools screen

Versions:
* Minecraft:  1.14.4
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.16-alpha
* RFToolsUtility: 1.2.13 

[crash-2019-12-17_13.27.52-client.txt](https://github.com/McJtyMods/RFTools/files/3974842/crash-2019-12-17_13.27.52-client.txt)

**Comment by McJty** [comment]
Known bug in forge that is waiting for a fix. Workaround is to disable truetype fonts in the rftools utility config
