### ISSUE TITLE
Can't join my friend server via hamachi get this bug on consle(ftb infinity)

### ISSUE THREAD

**Issue by david1e64** [McJty/RFTools#201]
http://pastebin.com/DKyU6U1Z

**Comment by McJty** [comment]
That has nothing to do with RFTools. See this line:

Attempting connection with missing mods [AromaBackup, CustomMainMenu, FastCraft, journeymap, Mystcraft, notenoughkeys, PortalGun, ResourceLoader, Translocator, TwilightForest] 

There are missing mods. Make sure you both have the same mods.
