### ISSUE TITLE
Craft after updateing mod

### ISSUE THREAD

**Issue by JohnnyWoong** [McJty/RFTools#2015]
Issue description: 
After i try update rftools,server crash
Steps to reproduce: 

mcjtylib:3.1.1=>3.5.4
rftools:7.61=>7,72
rftoolsctrl:1.9.3=>2.0.2
rftoolsdim:5.64=>5.71

Versions:
* Minecraft: 1.12
* Forge: 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:3.5.4
* RFTools:7.72
   OptiFine:HD_U_F5

here is cuash report:https://pastebin.com/Qbywr1L8

**Comment by josephcsible** [comment]
When you update McJtyLib, you often also need to update the mods that use it, and this is one of those times. In this case, you forgot to update NICE. Do that and see if it then works. If not, post the new crash report.

**Comment by JohnnyWoong** [comment]
> When you update McJtyLib, you often also need to update the mods that use it, and this is one of those times. In this case, you forgot to update NICE. Do that and see if it then works. If not, post the new crash report.

Thanks for the help,i forgot about NICE,after update it,its work
