### ISSUE TITLE
Crafter with two options makes the wrong recipe, just need to know how to disable in the mod config settings folder

### ISSUE THREAD

**Issue by grandogarndo** [McJty/RFTools#2016]
Issue description: 
My crafter tier 3 cannot make emeralds with petrotheum dust, instead it makes emerald dust
Steps to reproduce: get a crafter tier 3, put petrotheu, and emeralds in it, and it should make emeralds but it makes dust. 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2185
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.1.1
* RFTools:1.9.3

Possibly incompatible mods and versions:  Industrial craft 2 is the mod causing the problem

**Comment by theosib** [comment]
I'm having a similar problem. There are two possible products from the same recipe due to two different mods. But the crafter won't let me select which one.

**Comment by McJty** [comment]
Not much that I can do about that I'm afraid. I also no longer work on 1.12.2 as it is ancient
