### ISSUE TITLE
Screen not displaying compact or comma view

### ISSUE THREAD

**Issue by Mohawk1025** [McJty/RFTools#2017]
Issue description: I can't seem to get the screen to display the compact or comma view.

Steps to reproduce: I've experienced the problem with both the fluid and fluid+ modules. No matter which view I select, it always displays the full number rather than the compact or comma view. I'm running the FTB Revelation modpack.

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-2.6.2.83
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.72

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
Will be fixed in the next release (along with counter modules, which had the same problem).
