### ISSUE TITLE
Crash shift clicking items into modular storage

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#202]
Hey there.

I get the following crash when attempting to shift-click a dimlet into a modular storage system: http://pastebin.com/w9fWMGV4

I have managed to get this specific crash on two instances now so it was not a fluke.

**Comment by McJty** [comment]
I think I know what's wrong. You probably inserted an empty filter into the device. i.e. you made a filter but didn't configure it. Right? I will make sure that's no longer possible so that this crash can be avoided.

**Comment by McJty** [comment]
Fixed in next release.
