### ISSUE TITLE
Question Regarding Feature Absorbers

### ISSUE THREAD

**Issue by zauberparacelsus** [McJty/RFTools#2022]
Is there anything special that needs to be done in order to get a Feature Absorber to work?

I've set them out on both the overworld and on a generated dimension, but in neither case did they do anything.  In the latter case, I left a bunch of them out on a custom dimension and walked away from the game for 10-15 minutes (leaving it unpaused), and they hadn't absorbed anything.

**Comment by josephcsible** [comment]
* It needs to be in an RFTools dimension, not the overworld. What features does the RFTools dimension it's in have? (Check with `/rftdim info`)
* When you look at the block's description with Hwyla or TOP, what does it show?
* What's `maxFeatureAbsorbtion` set to in your config?

**Comment by zauberparacelsus** [comment]
* The dimension in question shows no features when running `/rftdim info`
* No extra data or percentage meters show in TOP
* `maxFeatureAbsorption` has been left at the default, I haven't touched the configs.

I had to create two more dimensions before the feature absorbers would start absorbing features, but that was only because I explicitly created a dimension with particular feature (oregen).  The `/rftdim info` command shows the following for features:

```
Feature: FEATURE_OREGEN
   Extra ore: Cobblestone, french-1
```

So, based on the above, am I correct in assuming that the feature absorber will *only* absorb a feature if it is explicitly put into a dimension?

**Comment by josephcsible** [comment]
Yes, that's correct. The feature absorber chooses a random feature of the dimension it's in, and if there aren't any, then it can't do anything useful.

**Comment by zauberparacelsus** [comment]
So, in other words, it is only useful for making copies of a feature dimlet that you already have, and you can't use it to make new feature dimlets.

**Comment by josephcsible** [comment]
That's not correct. Dimensions with no feature dimlets can still end up with random features, and the feature absorber can copy them.

**Comment by zauberparacelsus** [comment]
ok then, just needed to double check to make sure.
