### ISSUE TITLE
Energy Screen Module and Induction Matrix

### ISSUE THREAD

**Issue by crafian** [McJty/RFTools#2023]
Issue description:  
I'm trying to show my RF storage with energy screen module from an Induction Matrix from Mekanism and I can't even set the energy module block. It shows 'Energy Module is cleared.'

Steps to reproduce: 
 - Have an Induction Matrix, sneak-rightclick energy module.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.5.4
* RFTools: 7.73
  Mekanism: 9.8.3.390

Possibly incompatible mods and versions: Optifine(?)

**Comment by McJty** [comment]
Does the inducation matrix support RF/FE? Can you (for example) pipe power into it using energy pipes?

**Comment by crafian** [comment]
Yes, I tested ThermalExp and EnderIO cables, and a ComputerCraft program all working with RF/FE... There's an image: https://i.imgur.com/woI3Y4f.png

**Comment by McJty** [comment]
Well that's weird. You tested if the energy module works with other things?

**Comment by crafian** [comment]
Yes, actually working with EnergyCell from ThermalExpansion... I'm very confused

**Comment by StefanTT** [comment]
You have to shift-rightclick an io port of the induction matrix.
Works for me without issues in 1.12.2

**Comment by robertm1771** [comment]
While shift-right click will show you the RF of the IO port max it doesn't show the induction matrix total power. One probe shows total induction matrix power max and current. But if you bind screen to a induction port you are limited by the induction matrix limit per your configuration of the matrix. While working am not sure it is working as you intend it to function.
![image1](https://user-images.githubusercontent.com/6488750/104790386-04df7980-5765-11eb-8c04-8e362ca82316.png)
![image2](https://user-images.githubusercontent.com/6488750/104790391-0741d380-5765-11eb-957a-57e37c4ee433.png)

**Comment by Nidaelie** [comment]
still an issue....

**Comment by McJty** [comment]
And it will remain an issue. FE/RF is limited to 32-bit integer (2 billion). There is not much I can do about this
