### ISSUE TITLE
Rftools Elevators flickering upon landing

### ISSUE THREAD

**Issue by shouxd** [McJty/RFTools#2025]
Issue description: 
When I use the elevator it flickers a millisecond upon landing.

Steps to reproduce: 
Use optifine, an elevator, and then look down when it is being used.

Versions:
* Minecraft: 1.12.2
* Forge: latest
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: latest
* RFTools: latest

Possibly incompatible mods and versions: 
Optifine, since I reproduced the error myself and whenever I added optifine (no matter what version) the visual bug appeared, but I cannot delete Optifine since it helps my old pc a lot

**Comment by McJty** [comment]
That's normal behaviour. The thing is that the rendering changes from TESR rendering (during the movement down) to the actual blocks being placed there. There is not really a way (that I know) to avoid that glitch

**Comment by shouxd** [comment]
Hi. Thank you for replying. However, isnt that weird that the glitch only appears whenever optifine is detected?

Also, couldnt it be possible to emmulate, for example, thuts elevator's behavior? as they do not have the flicker with optifine, as I tested

**Comment by MichaelHillcox** [comment]
Likely more of an optifine issue then if it's not present when Optifine isn't running. It's likely just how ever Optifine has modified chunk rendering / block rendering. When a render (in this case a pretend block that looks like a block but in effect doesn't exist nor does it contain any properties) is moving we're all good as we can control that but when the render turns off and the mod as to tell Minecraft to place the blocks we where rendering into the world. It'll cause updates to the blocks around it and if Optifine is deffering or taking control of this process it could be why you're seeing a visual glitch.
