### ISSUE TITLE
Game crashes when staying in a new dimension for a while

### ISSUE THREAD

**Issue by doomguy81** [McJty/RFTools#2029]
As Title says without any problem I create a new dimension and i teleport to it. all Fine until I stay in it for a while like 10 min or earlier, game freezes and crashes. next time I try to get into my save it crashes in 3 sec. sry for bad English, here is the crash log.
[crash-2020-02-12_16.00.51-server.txt](https://github.com/McJtyMods/RFTools/files/4192102/crash-2020-02-12_16.00.51-server.txt)

**Comment by McJty** [comment]
Hmm it's not crashing in rftools though so not entirely sure that rftools is to blame here. Especially since nobody else has ever reported this. Does it happen in ANY rftools dimension? What about other dimensions?

Also versions please

**Comment by MichaelHillcox** [comment]
This is a super old version by the way: `rftools{4.23} [RFTools] (RfTools 1.7.10.jar)`

**Comment by McJty** [comment]
Oh 1.7.10... Sorry but that version is no longer supported. That's ancient. I don't even have an 1.7.10 mod environment anymore
