### ISSUE TITLE
crash during forge loading

### ISSUE THREAD

**Issue by tjicantdraw** [McJty/RFTools#2032]
## Bug Report
Game Crashes during Forge Loading, Phase 4, while attempting to load RFTools

## Expected Behaviour
Game Start

## Steps to Reproduce (for bugs)
1. Download CrackPack via Twitch Launcher
2. Attempt to start game

## Logs

* Client/Server Log: Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)

* Crash Log: https://pastebin.com/T5wH7GM0

## Client Information

* Java Version: 1.8.0_51, Oracle Corporation
* Launcher Used: Twitch
* Memory Allocated: 2504433288 bytes (2388 MB) / 6212812800 bytes (5925 MB) up to 7874281472 bytes (7509 MB)
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: N/A

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.72

**Comment by McJty** [comment]
Hmm that's a stange error. I do notice that your java version is pretty old though. Can you try updating to a more recent java 8 (has to be have 8!) version?

**Comment by tjicantdraw** [comment]
Java says its updated to the latest version, installed version 8 update 241

**Comment by McJty** [comment]
From your report here:

Java Version: 1.8.0_51, Oracle Corporation

That's not the latest version

**Comment by tjicantdraw** [comment]
That's the info the crash log gave me, not sure why its claiming that, as when i go to about java on my computer it says the current build installed on my pc is 1.8.0_241-b07. Unless there is a new place/way of getting java that I am not aware of. I'll update the report if desired

**Comment by tjicantdraw** [comment]
discovered two issues
1. Twitch is forcing minecraft to use 1.8.0.51 instead of 1.8.0.241
2. My version of 1.8.0.241 is 32bit instead of 64bit, will change this on my end and see if this helps

**Comment by tjicantdraw** [comment]
problem resolved by downloading the correct bit of java, and then forcing twitch to use legacy launcher allowing you to tell twitch what java to use
