### ISSUE TITLE
Come back of the Power Relay, Sequencer, Logic Gate, etc. for Future MC Versions?

### ISSUE THREAD

**Issue by papaworld** [McJty/RFTools#2033]
Thank you for a superior mod... been using rftools since 1.17.10 to present 1.15.2.

Are there plans to bring back other RFtools items for future versions of MineCraft... namely 1.15.2 or 1.16.x? I really miss them.

Thank you

**Comment by McJty** [comment]
yes I plan to port (almost) everything over. Just takes time

**Comment by papaworld** [comment]
That's great! It must be daunting work with all the version changes to MC. Thank you for you efforts and longevity over the past years. Again, super mod that is very helpful especially in custom builds.
