### ISSUE TITLE
Storage Scanner being erratic in 1.15.2 

### ISSUE THREAD

**Issue by WilxGaming** [McJty/RFTools#2034]
Issue description: Storage Scanner being erratic in 1.15.2 

Versions:
* Minecraft: 1.15.2
* Forge: 31.1.14
* McJtyLib: 1.15-4.0.1-alpha.jar
* RFTools: rftoolsbase-1.15-1.0.0-alpha.jar - rftoolsstorage-1.15-1.0.1-alpha.jar

I thought it might have been mod interaction, so I tried it with vanilla double chests and minecraft only items. Sometimes iron bars would show up, sometimes they wouldn't. I would see 2 items, then 6 blanks, then 12 items with wrong quantities. In the next chest 5 blanks then 6 items, wrong quantities.

**Comment by McJty** [comment]
Can you give me a few screenshots where it shows how the storage scanner is not showing you all information?

**Comment by WilxGaming** [comment]
![2020-02-22_00 17 23](https://user-images.githubusercontent.com/35704610/75087139-b13fbe00-550a-11ea-83df-81a0d4b584a4.png)
![2020-02-22_00 17 36](https://user-images.githubusercontent.com/35704610/75087140-b1d85480-550a-11ea-82ea-1d9f8016788f.png)
![2020-02-22_00 21 10](https://user-images.githubusercontent.com/35704610/75087141-b1d85480-550a-11ea-870e-3ed381a737d9.png)

**Comment by WilxGaming** [comment]
The double chests I showed were mostly full with many stacks of each, not the quantities showing. Both had many stacks of redstone, glowstone, lapis, dirt, clay and more.

**Comment by McJty** [comment]
Well in the last screenshot you don't seem to have marked many routable chests but other then that it seems indeed that it isn't working properly. I'll check it out

**Comment by WilxGaming** [comment]
The chests I didn't show had more modded stuff or where modded inventories and I was trying to avoid it.

**Comment by McJty** [comment]
BTW is it only broken with double chests or also single ones?

**Comment by WilxGaming** [comment]
Whats in the single chest on top of a builder:
![2020-02-22_00 49 49](https://user-images.githubusercontent.com/35704610/75087397-99b60480-550d-11ea-8642-47e70f47856a.png)

What the Scanner shows: 
![2020-02-22_00 51 07](https://user-images.githubusercontent.com/35704610/75087401-ae929800-550d-11ea-81b5-0363ed9b90df.png)

**Comment by McJty** [comment]
I can reproduce the problem

**Comment by WilxGaming** [comment]
Sorry I should have responded a week ago. You fixed it in the update right after I reported it. Thank you for the prompt response.
