### ISSUE TITLE
Support Blocks not disapearing

### ISSUE THREAD

**Issue by kgn001** [McJty/RFTools#2035]
Issue description: Support Blocks not disappearing after turning off preview

Steps to reproduce: Turn on preview in builder, Adjust offset, Toggle the preview off and then back on.

Versions:
* Minecraft: 1.12.2
* Forge:  14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.5.4
* RFTools: rftools-1.12-7.73

Possibly incompatible mods and versions: OptiFine_1.12.2_HD_U_F5

Relevant logs, if any:

**Comment by soupcant95** [comment]
Exact same issue here. If I reported, it'd be a dupe

**Comment by McJty** [comment]
This is a known issue and will not be fixed on 1.12. It's easy to get rid of the support blocks by right clicking them
