### ISSUE TITLE
I DIED IN MY COLLAPSING DEMENTION AND CANT RECREATE IT 

### ISSUE THREAD

**Issue by MSC4speed1** [McJty/RFTools#2037]
So i made a demention with a few of my modefiers and then built the demention and went in everything was fine later i changed the modefiers of that demention then started building this new one once it was built and i was ready to enter i went threw the matter transmitter but it was diled to the first demention which was no longer powered and i died instently. i obviously had everything i own just about on me and i really need my stuff back. 
there is no way to recharge this demention  because i no longer have the actual dimention but its still diled and all my stuff is in it

**Comment by McJty** [comment]
Make a Phased Field Generator and put it in your hotbar. It allows you to travel into unpowered dimensions so you can recover your stuff
