### ISSUE TITLE
RFTools Builder does not mine redstone ore

### ISSUE THREAD

**Issue by KirikaAetheria** [McJty/RFTools#2038]
Issue description: Using the RFTools builder with any quarry card, it will fail to mine redstone ore, unless the redstone ore is lit. Incidentally, the process to create a redstone ore dimlet was also iffy, since the material absorber failed to accept lit redstone as material. Perhaps the two issues were related somehow

Tests made in redstone-only worlds:
![1](https://user-images.githubusercontent.com/61053558/76745708-3fa40a00-676e-11ea-89e7-ea9537f0cbfc.png)

![2](https://user-images.githubusercontent.com/61053558/76745719-46cb1800-676e-11ea-95b0-8249ec0186d3.png)

Running around to leave a trail of activated redstone behind caused the builder to recognize and mine it:
![3](https://user-images.githubusercontent.com/61053558/76745855-7548f300-676e-11ea-8369-277f6c225c4c.png)

The builder doesn't appear to have issues mining when in a normal location:
![4](https://user-images.githubusercontent.com/61053558/76745953-9ad5fc80-676e-11ea-9983-d3db7e9ad0f9.png)

Feel free to let me know if you need any further info on my end, I'll be happy to help out

Steps to reproduce:
-Create a dimension with a redstone ore material dimlet to easily see what is happening
-Setup your builder like normal
-When you start the builder, you should notice next to no redstone is coming in, and the designated mining area is mostly/completely unchanged

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73
RFToolsDim 1.12-5.71

Possibly incompatible mods and versions: Optifine

Relevant logs, if any: N/A

**Comment by McJty** [comment]
Hmm that's strange. I cannot reproduce this at all (I have mined tons of redstone in my Lets Play using the builder). Must be some mod interaction...

**Comment by KirikaAetheria** [comment]
I did find it very strange that no one had made a report on this, so that's very likely. I can't imagine just posting a list of mods would help in narrowing it down either. are there any steps I can take that will give you useful information? or I could also upload the server folder and post a link, if you'd like to take a look for yourself

**Comment by McJty** [comment]
What would help (but that's time consuming to do) is if you can narrow down the problem with less mods until you find the other mod that might be causing this

**Comment by KirikaAetheria** [comment]
ah, I thought there could be some form of tracing utility to find out which mod was causing these changes. sorry, I'm not very well-versed in the tools modders have at their disposal

but if just finding the responsible mod is enough help, then I'll go and try to do that. will be back when I have news

**Comment by KirikaAetheria** [comment]
alright, found the offending mod. it's Reskillable. Currently using the latest version, 1.12.2-1.13.0. Upon removing it from the mods folder and loading the game back up, there are no more issues as far as mining redstone is concerned

![5](https://user-images.githubusercontent.com/61053558/76765600-8f92c900-678e-11ea-9314-197e848f6ef3.png)

hopefully this will be helpful, let me know if there's something else I can do on my end

**Comment by McJty** [comment]
Ok, then that's not a bug in RFTools. Reskillable requires the player to have the right skills in order to mine something. The Builder does not have any skills so it is not able to mine it. To fix this a kind of blacklist to certain blocks/fake players would be required in reskillable. Not something I can fix on my end

**Comment by KirikaAetheria** [comment]
ah, I see. in that case I'll report this on their tracker and link to this page. sorry for the bother and thank you very much for your time
