### ISSUE TITLE
Crafter Filter upgrade slot accepts all items when piped in.

### ISSUE THREAD

**Issue by Malus-Lupo** [McJty/RFTools#2039]
Issue description: Tested only with mekanism pipes.

Steps to reproduce: 

Versions:
* Minecraft: 1.15.2
* Forge: 21.1.16
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools: 1.0.0 alpha

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Will be fixed next release
