### ISSUE TITLE
Please add sorting to storage scanner! (1.12.2)

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#2044]
Inventory scanner is awesome except it cannot sort the items, it will be a godsend if this feature can be added!

Please!

Thanks

**Comment by McJty** [comment]
Yes I want this too. I'm certainly going to add it at some point.

**Comment by LordHellscream** [comment]
hey @McJty I finished DDSS recently, AMA if you have any questions :)
Thanks for considering the enhancement!

**Comment by fwcd** [comment]
Please see #2031, which implements this feature.

**Comment by LordHellscream** [comment]
@McJty please CR the change and approve it :) thanks @fwcd

**Comment by McJty** [comment]
That's for 1.12 though

**Comment by LordHellscream** [comment]
@McJty Is 1.12 different from 1.12.2?

**Comment by McJty** [comment]
No. That's what I mean. But i no longer develop on 1.12. my focus is on 1.15

**Comment by MichaelHillcox** [comment]
We also have this issue open somewhere else. Greatly requested. No work is being done on 1.12 though par from possible bug fixes. Closing due to that.
