### ISSUE TITLE
[Feature Request] Ender IO Redstone Conduit to work with Shield Projector

### ISSUE THREAD

**Issue by BrandonGamesYT** [McJty/RFTools#2045]
I would love to leave a request for a feature so i got rid of the issue template as this is not a issue at all

I would love to see RF Tools Shield Projectors for 1.12.2 if it's still being worked on or just some of the newer versions work with Redstone conduits from ender io for setting up awesome Shield doors without having to use something like a Redstone lamp as that's the only way I see it working right now cause I tried the conduit and it doesn't connect to the machine

If this is already a feature and I'm just miss understanding something this request could be closed immediately, but from what I tried it doesn't seem to be

P.S. This is because I want to run a lever from a different area to turn it on and off using just the conduits

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer shipping feature updates to 1.12
