### ISSUE TITLE
Mispelling in wiki

### ISSUE THREAD

**Issue by b-chu** [McJty/RFTools#2057]
Issue description: 
Mispelling in wiki

Steps to reproduce: 
https://github.com/McJtyMods/RFTools/wiki/RFTools-Remote-Storage

Change "These need to be linked first to **de** right storage item." to "These need to be linked first to **the** right storage item."

**Comment by MichaelHillcox** [comment]
Sorted although I will note, the wiki is never as up to date as the in-game wiki :D

**Comment by McJty** [comment]
Also that wiki is for 1.7.10 and is ancient. It is not up-to-date for modern RFTools
