### ISSUE TITLE
[1.15.2] server crash

### ISSUE THREAD

**Issue by IchigoGames** [McJty/RFTools#2058]
server crash from rftools crafter not sure why

Steps to reproduce: 
bit sure its one of my member on server 

Versions:
* Minecraft: 1,15,2
* Forge:31.1.77 
* McJtyLib:mcjtylib-1.15-4.1.0-beta
* RFTools:1.15-2.1.1-beta

crash report https://pastebin.com/Y7wSFMVw

**Comment by McJty** [comment]
Will be fixed in the next release
