### ISSUE TITLE
Bizarre issues with rfTools that showed up after removing Buildcraft and Buildcraft Compat

### ISSUE THREAD

**Issue by utoc** [McJty/RFTools#206]
Having a client/server issue, currently running rftools-2.93

Have tried with FML 1408, 1424 and 1448 (Recommended) and both seem to present the same issue.

Server says: http://pastebin.com/TGKS5Sr1 when each user connects.

Client gets kicked with "A Fatal Error has occured, the connection is terminated"

Opening a dialer, looking at a transmitter and the client is immediately kicked: http://pastebin.com/78izKSSh

No server or client crash, just a dropped connection

**Comment by McJty** [comment]
I'll check it out. Perhaps that world was generated with some buildcraft stuff which is no longer available (like oil)

**Comment by utoc** [comment]
It was generated with BC, we removed it while waiting on Asie to fix https://github.com/BuildCraft/BuildCraft/issues/2782

Incidentally, adding BC back in to the server just to verify the issue caused the issue to go away.  I am totally confused.

**Comment by McJty** [comment]
MC yes, but I guess that RFTools itself does not properly handle the removal of a mod. I'll check out if I can solve this somehow.

**Comment by McJty** [comment]
Would it be possible to give me the entire server log? The crash alone is not enough for me to see how I can fix this.

**Comment by utoc** [comment]
Here: http://bbqsauce.terron.com/bbqlog/rftools.log

**Comment by McJty** [comment]
I think I know what's wrong. You probably have a dimension that generated with one of the Buildcraft biomes (oil field or something). RFTools can't handle the removal of biomes yet. I'll fix this for 3.00 (out later today)

**Comment by utoc** [comment]
I'll test it, beta 2?

**Comment by McJty** [comment]
No, it is not in that version. But you can get a test version from here: https://drone.io/github.com/McJty/RFTools/files

**Comment by utoc** [comment]
Confirmed!  Thanks for handling that so quickly.
