### ISSUE TITLE
1.12.2 Immersive Mods (Engineering, Tech, etc) support

### ISSUE THREAD

**Issue by hypherionmc** [McJty/RFTools#2060]
Issue description: RFTools Fluid screen module and Liquid monitor don't pick up any of the tanks from Immersive engineering any of the addon mods. I don't know if I'm doing something wrong, but I can't get it to work at all.

Steps to reproduce: 

1) Build a IE fluid tank and fill it up with any liquid.
2) Try to link fluid screen module or placing a Liquid monitor anywhere on the tank

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73

Possibly incompatible mods and versions: 
Immersive Engineering 0.12-92
Immersive Tech 1.12.2-1.1.9

Relevant logs, if any: No errors so no logs

**Comment by McJty** [comment]
That's up to those mods to fix. RFTools simply uses the standard fluid capability system
