### ISSUE TITLE
Filter extracted in Crafter tier 3

### ISSUE THREAD

**Issue by acokeaday** [McJty/RFTools#2061]
Issue description:  Crafter Tier 3, Filter gets extracted into hopper or pipes when no other items are aviable to be extracted

Steps to reproduce:  
1. place a crafter Tier 3
2. insert a filter in filter slot, 
3. place a hopper below. 

Filter will be extracted if no other items in the extract slots. 

Versions:
* Minecraft: 1.15, ATM5 1.24
* Forge:  31.1.88
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.15-4.1.0-beta
* RFTools: rftoolsutility-1.15-2.1.2-beta

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Will be fixed next release
