### ISSUE TITLE
[1.12] [FTB Continuum] Contents of Modular Storage Disappeared

### ISSUE THREAD

**Issue by SmirkyCat** [McJty/RFTools#2077]
sorry. issue is not relevant anymore.

i realized my mistake, to just clear the search in it.

on a side note, if you have time, please do have a text indicator that search items not found if you have time, i did not spot it until now

**Comment by Danc3R4ve** [comment]
do note, every time i open the machine, contents do appear for 1 tick, then it all disappears again, I cannot use it fast enough to retrieve its contents before it vanishes
