### ISSUE TITLE
[1.15.2] Crashed using RFTools Dialing Device 

### ISSUE THREAD

**Issue by IchigoGames** [McJty/RFTools#2078]
Crashed and then crashed again after restarting, both times when using RFTools Dialing Device (not used in this game before). Crash report follows: https://pastebin.com/vHW7JT0BIssue 

Steps to reproduce: 

Versions:
* Minecraft: 1.15.2
* Forge: 31.2.0
* McJtyLib:mcjtylib-1.15-4.1.1-beta
* RFTools:rftoolsbase-1.15-1.1.1-beta

https://pastebin.com/vHW7JT0BIssue

**Comment by McJty** [comment]
The pastebin doesn't work (has been removed). Can you post it again?

**Comment by IchigoGames** [comment]
https://pastebin.com/vHW7JT0B sorry about that

**Comment by McJty** [comment]
Were there matter transmitters near the dialing device? Where they dialed to something?

**Comment by IchigoGames** [comment]
Yes, I had the usual setup of a receiver, a transmitter and a dialling device in proximity to one another.
[5:12 AM]
Also a matter booster.

**Comment by IchigoGames** [comment]
Re the error above - I was in OW and had a destination to Midnight selected - IDK if that makes a difference.

**Comment by McJty** [comment]
I guess a dimension got removed or something. In any case I added a protection for this so that in the next version it will no longer crash
