### ISSUE TITLE
RFTools Builder Card GUI Bug

### ISSUE THREAD

**Issue by Madmosh** [McJty/RFTools#2079]
Issue description: 
This issue occurs on an ATM5 verion 2.1 server.
Every time I press the card GUI, the GUI disappears, I cannot do anything including access the main menu. The only way for me to leave that state is to kick my self from the server. I have provided a photo below. I have tested with the void card and a normal shape card, all produce the same issue. My friend does not have any issue with accessing the card GUI, we have tried to reproduce the issue but to an avail. When there is no card in the slot, pressing the "?" does not do anything. The only thing that worked was for me to restart my whole game, this only worked once though and has not worked following times. We attempted to reproduce that but were unable.
Things we have tried:
- changing location
-removing items from inventory and armour
-activating or deactivating the other settings in the main gui.

I also did some brief testing in a single player world with the same results, except the very first time where it did work, but subsequent times were a failure and I had to force close my game.

Versions:
* Minecraft: 1.15.2
* Forge: forge-31.2.9
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.15-4.1.1-beta
* RFTools: rftoolsbuilder-1.15-2.1.3-beta
*All the Mods 5 client: version 2.1
*All the Mods 5 server: Version 2.1

Relevant logs, if any: 
As there is no crash there are no logs. There is also nothing on the server CMD.
This picture is what happens immeditaly after pressing the "?" button or "card GUI" while there is a card in the slot. This state is maintained and cannot be exited with being kicked from the server or the game is restarted.

![rftools builder](https://user-images.githubusercontent.com/21049842/85126084-19f83680-b270-11ea-9eb8-8de0a14eb9e3.PNG)

**Comment by mtbrenner** [comment]
Same problem, in Q-tech modpack:
modpack version 0.4b (1.15.2)
RFToolsBuilder 1.15-2.1.4-beta
McJtyLib 1.15-4.1.2-beta
Forge 31.2.31

**Comment by Simba127** [comment]
Same Exact issue using valhelsia 2 pack

**Comment by McJty** [comment]
People, it's not useful to keep repeating this. I know that there is a bug there (unfortunatelly I don't know how to fix it yet)

**Comment by McJty** [comment]
Will be fixed next release. I finally found it

**Comment by rendragnet** [comment]
_Sorry, in the meantime, how do we access the shape card gui?  Or can we just not use the builder to quarry for now?  Thanks :)_

Nevermind, just realised you can pull the card out and shift-click with it :)

**Comment by McJty** [comment]
Also the bug is fixed
