### ISSUE TITLE
possible issue with cohf mods

### ISSUE THREAD

**Issue by Frontrider** [McJty/RFTools#208]
https://github.com/CoFH/Feedback/issues/603#issuecomment-111741591

You'rs were the last mod added.

**Comment by KingLemming** [comment]
I'm still waiting to hear if this is a consistent occurrence.

**Comment by McJty** [comment]
RFTools may have been the last mods added but I see no mention of RFTools in the crash log. So I don't think this is related to RFTools.

**Comment by KingLemming** [comment]
Well, the issue is that something is screwing up the render context, and then our duct happen to catch it when it had been derped.

I don't think it's RFTools either, but we know it isn't the duct code or it'd happen consistently.

**Comment by McJty** [comment]
Closing due to lack of info
