### ISSUE TITLE
RF Tools Builder not pulling/requesting more than 20k RF/t

### ISSUE THREAD

**Issue by DnrKtz167** [McJty/RFTools#2082]
Issue description: RF Tools Builder not pulling/requesting more than 20k RF/t. Stays at the same buffer height. The screenshot shows that the buffer won't fill. In the screenshoti used a Flux Point from Flux Networks but I tried creative energy sources directly next to it.

Steps to reproduce: Take a Builder with a Clearing Fortune Quarry, area is 512 256 512 no offset. Machine fully infused. Just place some kind of creative energy force down to it. Machine will state: "Not enough power!" and won`t fill buffer. ( I used creative energy cells from Mekanism, AE2 and EnderIO)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 3.5.4
* RFTools: 7.73
![Screenshot_1](https://user-images.githubusercontent.com/44646000/85962712-6d762d00-b9b2-11ea-91ea-a25683b4d58d.png)

**Comment by McJty** [comment]
yes, 20Krf/t is the maximum per side. If you want to give more power insert power from multiple sides
