### ISSUE TITLE
Duplication bug - Storage Scanner and Crafter

### ISSUE THREAD

**Issue by jeramyreid** [McJty/RFTools#2083]
Issue description:  Item duplication using only Storage Scanner and Crafter

Steps to reproduce: 
1) Place a Crafter, any tier. Put an item in the inventory and hit the Remember button.
2) Place a Storage Scanner and have its radius reach the Crafter. This can even be side by side with range 1.
3) Craft an item in the Storage Scanner, which uses that item. The item will not be consumed. You can use this to turn a single piece of wood into stacks of doors, or a single piece of charcoal into inventories full of charcoal blocks. If you do not have the other components, you cannot craft.

If the item is removed from the Crafter and/or the remember function disabled on that block/inventory slot, the item will be consumed as expected, and will be unable to craft from duplication.

Versions:
* Minecraft:  1.12.2
* Forge: 14.23.5.2854
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.7.3

Possibly incompatible mods and versions:  No other mods. Raw Forge, Minecraft, RFTools, McJtyLib.

Relevant logs, if any:  No logs

**Comment by McJty** [comment]
This is now fixed in 1.16 and 1.18
