### ISSUE TITLE
Can extract but cannot insert across dimensions in Tablet

### ISSUE THREAD

**Issue by Rithenar** [McJty/RFTools#2086]
Issue description: When trying to insert items into the Storage network across dimensions using a Tablet with a card bound to a Storage Scanner, items are not accepted by the system. Extraction of items works fine. Network has plenty of storage available. Extraction works fine in the overworld.

Steps to reproduce: 

Versions:
Minecraft: 1.15.2
Forge: 31.2.30
CompatLayer (only if on Minecraft 1.10 or 1.11):
McJtyLib: 1.15-4.1.1-beta
RFTools: base-1.15-1.1.1-beta

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
I cannot reproduce this. For me it works perfectly fine in two directions (insert/extract) from another dimension. Are you sure the storage scanner is actually chunkloaded?

**Comment by Rithenar** [comment]
Thank you for looking into this McJty. Apparently it was some kind of hiccup as I went to a different dimension and it worked fine. Went back to the Nether where it was happening and now works perfectly.
