### ISSUE TITLE
Projector projecting blocks blue

### ISSUE THREAD

**Issue by Cazza5** [McJty/RFTools#2087]
Issue description: Projector projects blocks blue (maybe support blocks) a smaller scan of 256x256x256 works fine. You can also see in the image a projection of a smaller area working fine. 

Steps to reproduce: scan an area at max range 512x256x512 and place a linked scan into the projector. 
![A6189E24-286D-4575-AC77-285521DF6E97](https://user-images.githubusercontent.com/69203410/89304306-322be580-d665-11ea-9b63-a239cf031c32.jpeg)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.72 and 1.12-7.73 (both tried)

A point to note is that I different offsets, the projection correctly reflects the buildings but some biomes clearly colour blue incorrectly.

**Comment by McJty** [comment]
The blue color is used whenever it can't determine the color of the block. This is not a bug. For modded blocks this often occurs and my guess is those other biomes are made out of modded blocks

**Comment by Cazza5** [comment]
The white block is concrete, a vanilla block, and while I did think this to be the case other blocks like stone brick slabs, also vanilla will show blue. Upon shifting the the scan offset non vanilla blocks can be corrected. The floating island in the image which I expected to remain blue did also show correctly at an offset nearer the edge of the map.

**Comment by McJty** [comment]
Ok, then the other option is that there is an overflow. The scanner only supports up to 256 different block types in the same scan. Any different block types beyond those 256 will be rendered blue as well

**Comment by Cazza5** [comment]
I see that makes more sense. Is there a way to adjust this in a config anywhere or is it capped to prevent the data being too large?

**Comment by McJty** [comment]
The latter. 256x256x256 is a HUGE lot of data to send from the server to the client

**Comment by Cazza5** [comment]
Ok, well thank you for responding to the thread. If a way to increase the scan data is ever implemented, I look forward to it. Hopefully I’ll survive with blue scans :’). Thanks again 👍
