### ISSUE TITLE
Builder Quarry preview causes major delay in 1.15.2

### ISSUE THREAD

**Issue by scialt61** [McJty/RFTools#2091]
Issue description: 

Steps to reproduce: 

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:

Possibly incompatible mods and versions: 

Relevant logs, if any: 

So I was playing QTech (1.15.2). I made a Builder with a Quarry card. The card was set to 512x50x512 and offset. While I was using the preview feature to attempt to configure my quarry properly, the game began lagging a lot. It lagged in such a way that, although I could move, I couldn't interact with the Builder, run commands, or change the modes of my items from Mekanism.

**Comment by McJty** [comment]
That's really unavoidable. The builder has to place all those preview blocks and with such a massive area that is going to take a long time. I don't see a way to avoid this really
