### ISSUE TITLE
1.16.3 builder doesnt use up blocks

### ISSUE THREAD

**Issue by tindin** [McJty/RFTools#2092]
Issue description: 
when using the builder it doesnt use up blocks from the chest 

Steps to reproduce: 

every time you use the builder
Versions:
* Minecraft: 1.16.3
* Forge: forge-1.16.3-34.0.9.jar
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.0.6.jar
* RFTools: rftoolsbuilder-1.16-3.0.4-beta.jar

Relevant logs, if any: 
n/a

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
I can reproduce it. Investigating

**Comment by McJty** [comment]
I found the bug. Will release a fix later today

**Comment by McJty** [comment]
Fixed. Note that you posted it in the wrong github. RFToolsBuilder has its own github

**Comment by tindin** [comment]
i know this is closed but https://www.curseforge.com/minecraft/mc-mods/rftools-builder does not have any links to github
