### ISSUE TITLE
RFToolsUtility1.16-3.0.12 Screen Truetype Render Crash

### ISSUE THREAD

**Issue by monsay123** [McJty/RFTools#2101]
Issue description: 

RFTools Utility Screen causing a render crash with Truetype text selected.

Steps to reproduce: 
Place Screen, then change text in the GUI to Truetype. Proceed to render crash.

Versions:
* Minecraft: 1.16.3
* Forge: 34.1.25
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:  1.16-5.0.12
* RFTools: rftoolsutility- 1.16-3.0.12

Possibly incompatible mods and versions: 

 

https://pastebin.com/0pWVbREx

I am aware this was an issue about a year ago but have not played since. Setting the config to Truetype false does not resolve the crash on a server or in a single player game as the specific setting in the Screen block is still set to Truetype. Is there any other way to stop this? I tried to look for the RFTUtils config but there was not one generated for the server if that helps at all. Thank you for your time!

**Comment by monsay123** [comment]
I found this: https://github.com/McJtyMods/RFTools/issues/1263 from a year ago and seems to be a similar issue if that helps

**Comment by Peach774** [comment]
I also have this issue

**Comment by McJty** [comment]
Looking at this right now

**Comment by McJty** [comment]
BTW, this was posted to the wrong issue tracker. Use the one for RFTools Utility next time. But the bug is fixed
