### ISSUE TITLE
[1.16.3] Shield Projector Mimic, Solid, and Shield Modes not working

### ISSUE THREAD

**Issue by ZapDragon** [McJty/RFTools#2103]
RFTools-base 2.0.7
RFTools-Builder 3.08
RFTools-Control 4.0.5
RFTools-Utility 3.0.11
RFTools-Power 3.0.8
Minecraft 1.16.3
Forge 34.1.25

Changing the shield mode (Mimic, Solid, and Shield) all results in a Transparent mode shield.
Invisible and Transparent modes work.

I've tried this on a server and in a single player game in a custom pack.

**Comment by McJty** [comment]
Please try again with a proper report. No version, no description. Nothing

**Comment by ZapDragon** [comment]
> Please try again with a proper report. No version, no description. Nothing

My apologies. Miss-clicked and submitted it before I had even started typing.
