### ISSUE TITLE
[BUG] RFTools SimpleChannelHandlerWrapper exception

### ISSUE THREAD

**Issue by spannerman79** [McJty/RFTools#211]
[Forge 1448](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html)  ( recommended stable for MC 1.7.10 )

[RF Tools 3.01](http://minecraft.curseforge.com/mc-mods/224641-rftools/files/2242548)

Either single player or connecting via SMP the following message is spammed then "Fatal Error" message on client

http://hastebin.com/opicilocel.avrasm

**Comment by McJty** [comment]
Do you have some kind of mod that does something special with mossy cobblestone? RFTools is crashing while trying to generate a dimlet for mossy cobblestone.

**Comment by McJty** [comment]
Can I see the full log

**Comment by spannerman79** [comment]
Complete client log https://paste.ee/p/qI2zd
From startup, creating/starting new single player instance to client crash

**Comment by McJty** [comment]
I just did a blind fix for this. Can you try the development version of rftools from here and see if that helps:

https://drone.io/github.com/McJty/RFTools/files

Thanks

**Comment by spannerman79** [comment]
Single Player - No issue.
SMP/Server - No issue.

I'll close this as I consider this issue resolved

Although I am curious as to why this issue happened.
Was it in fact a mod that i was running? The logfile i provided before has a complete list of mods from line 73 - 328

**Comment by McJty** [comment]
It is probably a mod that you're using but I don't know which one. I protected against this by simply checking for this and not generating that dimlet (in this case mossy cobblestone).
