### ISSUE TITLE
Builder Not Functioning Properly DW1.16 (RFtools Builder1.16-3.0.13)

### ISSUE THREAD

**Issue by CLASIX** [McJty/RFTools#2111]
Hello. I am playing DireWolf20's 1.16 Modpack. I just tried to use the builder with a void card. Everything is set up just as i always do. Unclaimed chunks, sufficient power, properly configured shape card, strong constant redstone signal and builder outside of operation area. I have tried both the clearing quarry and void shape cards with chest on and off both of them. It scans the 6 chunks and then just stops. Doesnt consume any power. Wont do anything until i adjust the redstone settings within the builder or pulse the redstone signal off and on once. Where it just keeps scanning and shutting down. 

https://imgur.com/a/2YkmOcy

**Comment by CLASIX** [comment]
Versions:
Minecraft: 1.16.4
forge-1.16.4-geckolib-3.0.0
mcjtylib-1.16-5.0.15
rftoolsbase-1.16-2.0.9
rftoolsbuilder-1.16-3.0.12
rftoolscontrol-1.16-4.0.6
rftoolspower-1.16-3.0.8
rftoolsutility-1.16-3.0.19


I am using Optifine HD U G5

**Comment by VoidFletcher** [comment]
I'm having the same issue. 

Also using Optifine HD U G5, other than that, it's a standard install.

Quarry cards won't work either, managed to get it to mine 28 dirt, then it just didn't work again.

EDIT: Certain chunk areas seem to work as intended.

**Comment by McJty** [comment]
Are there claimed areas (by whatever plugin/mod available for that)?

**Comment by VoidFletcher** [comment]
There are some claimed chunks (by me) a few chunks away. However, I tried unclaiming these chunks - didn't seem to have an effect.

I also accepted the builder's ally invite.

**Comment by CLASIX** [comment]
So i was actually not aware that minecolonies claims chunks. I was hanging out in my colony, dreading the huge dig job ahead of me when i heard Hsssssssss right behind me. There was no explosion. No damage. Then it hit me. Chunks must be claimed. Im officially a dummy.

**Comment by VoidFletcher** [comment]
Ahhh, I wasn't aware of this either. I do have a colony running that my friend set up. I'll have a look to see if that's what's causing the builder to have a heart attack. It wasn't set up particularly close to the colony, but within render range (10 chunks)

**Comment by VoidFletcher** [comment]
Why was this issue marked as closed?

Cannot confirm if it's minecolonies interfering or not. Builder is also giving other issues like weird offset when preview is used vs when it's not. But I'll open a seperate issue for that.

**Comment by CLASIX** [comment]
it is minecolonies for this current issue. and its not just the builder that doesnt quarry. Most quarrys will not quarry a claimed chunk. its not McJity's issue. Its been like this for years. I dont think anyone can really get around it.
