### ISSUE TITLE
No builder recipe

### ISSUE THREAD

**Issue by AdnanuReeves** [McJty/RFTools#2112]
For some reason the builder doesn't have a recipe for me, nothing happens when i try to click on it? And it doesn't show up in JEI unless I search for it.

I got the latest version of all the rf mods and forge.

**Comment by McJty** [comment]
What version?

**Comment by AdnanuReeves** [comment]
mcjtylib-1.16-5.0.15
https://gyazo.com/7693ca61c119220a44e09c635215ddcb

**Comment by AdnanuReeves** [comment]
1.16.4

**Comment by AdnanuReeves** [comment]
Nvm I'm an idiot, it was in the kubejs from atm6. Fixed it now, sorry.
