### ISSUE TITLE
Crafter instant kicks everyone

### ISSUE THREAD

**Issue by nuked44** [McJty/RFTools#2116]
Issue description: 
The server kicks every one who wants to join, the console gest spammed with errors that items are missing,
Crafter is used to craft induction cells from mekanism
Steps to reproduce: 
happens randomly

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 1.12-5.3.4
* RFTools: 1.12-7.73

Possibly incompatible mods and versions: 
Mekanism-1.12.2-9.8.3.390

Relevant logs, if any:

**Comment by McJty** [comment]
I need to see the log

**Comment by nuked44** [comment]
https://pastebin.com/gTPWZswQ

this gets spammed over and over

**Comment by McJty** [comment]
All of it please

**Comment by nuked44** [comment]
the server doesn't crash just looks like this:
https://pastebin.com/rYhX4bdJ
and trying to join results in an instant kick

**Comment by McJty** [comment]
It's not because there is no crash that I don't want to see the entire log. The important information is still missing. I *really* need the entire log. Crash or no crash

**Comment by nuked44** [comment]
https://pastebin.com/1Zs1LxLG
thats the latest.log if thats what you need

**Comment by McJty** [comment]
I need the full text where 'Using CraftingManager fallback' in appears. i.e. the log spawn that you were complaining about. The latest.log you posted doesn't contain that

**Comment by nuked44** [comment]
is there any part you need in particular because the file is over 200mb and pastebin doesnt like that

**Comment by McJty** [comment]
Hmm. I think you can attach it directly to this github ticket. If that doesn't work then I need about a hundred lines before it starts log spamming and then a few entries of the log spawm

**Comment by nuked44** [comment]
https://pastebin.com/MNiqA8uw

those are the first 250 lines

**Comment by McJty** [comment]
I meant I need the a few hundred lines from BEFORE it starts log spamming. I need to see what happens before the spam

**Comment by nuked44** [comment]
https://pastebin.com/0XVdZtWz

the thaumcraft stuff is directly afer starting the server

**Comment by McJty** [comment]
It seems to be a problem with the Mekanism recipe. Not sure why it's doing that though. Try to get rid of that recipe in the crafter to see if that helps

**Comment by nuked44** [comment]
i'll do that thanks

**Comment by oliverab** [comment]
Interesting it is crafting induction cells, some time ago and I don't know how many revisions back I tried using a crafter to make induction cells and found it didn't distinguish between the different tiers of cells for some reason. Obviously that's old news now but is there something funny about how the induction cell tiers are implemented?
