### ISSUE TITLE
Dimensional numbers +/-128 issue

### ISSUE THREAD

**Issue by Prophious** [McJty/RFTools#212]
it seems that when the dimensions numbers go past +/-128 client crashes and it seems that if there was a player inside at the time, the player data has to be reset, not just moved out

i do believe that it is a problem with how minecraft reads dimensions, and a suggestion is to assign dims the same way as mystcraft, by putting in front of the dim number "RFT" or "RFTools" and should start out at -128 and go to +128 and have the mod find an empty(or unclaimed by other mods) dim number when a new dim is created

granted sometimes it works and sometimes minecraft is just a pain about dim numbers, so its just a hit and miss type of problem

i do believe that the RF tools being used is in FTB infinity pack 1.6.2(not 100% on this tho), i will get the  mod version for you as soon as i have the info, but i assume its in the latest

**Comment by McJty** [comment]
This bug was fixed in RFTools 2.92. Would be nice to know what version you have.

**Comment by Prophious** [comment]
tbh i think its something lower, but it has to be updated in the FTB infinity modpack.... which i just checked in v1.62 its only v2.91 of RFTools

**Comment by McJty** [comment]
Yes, 2.91 still has that bug
