### ISSUE TITLE
Dialing Device Doesn't Show Receivers

### ISSUE THREAD

**Issue by Camohunter7t** [McJty/RFTools#2123]
Issue description: When creating a new dimension with no dimlets, Dialing Device does not show generated receiver in the dimension. After teleporting into the dimension with commands and tping to 0 69 0, receiver is there with full power and is public. 

Steps to reproduce: Create empty dimension and look at dialing device.

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.45
* McJtyLib: 5.0.17
* RFToolsBase: 2.0.10
* RFToolsDim: 1.16-7.0.4-beta

I am using Optifine.

**Comment by McJty** [comment]
Hmm weird. This is working fine for other people. Does this happen with every new dimension? Note that you need digit dimlets to actually create new dimensions. Using no dimlets will always go back to the same dimension

**Comment by Camohunter7t** [comment]
So far I have created 4 dimensions and have not had a receiver appear for any of them.

**Comment by McJty** [comment]
What were the dimlets for each of these 4 dimensions?

**Comment by Camohunter7t** [comment]
I did three empty dimensions, each time using the forget command. I then made one with a digit 2 dimlet. The current one I am on has feature spheres and uranium ore block dimlet.

**Comment by McJty** [comment]
The three empty dimensions will be the same dimension (even with forget). You need digit dimlets. Ok, so can you create another unique dimension and give me the log?

Also try without optifine to be sure

**Comment by Camohunter7t** [comment]
I should mention I am on a server. So I doubt Optifine is the issue. Which log can I give you?

**Comment by McJty** [comment]
The server log

**Comment by McJty** [comment]
BTW, I just notice you are using a very old vesion of RFTools Dimensions. That could very well be the reason. Updating is recommended

**Comment by Camohunter7t** [comment]
I am running the latest Direwolf20 pack and the dimension were working for dire on the same version I believe.

**Comment by McJty** [comment]
Well Direwolf is running single player. There was a server problem which more recent versions of my mods (rftools dimensions + rftools utility + mcjtylib) fix. I look at the log and it seems you're hitting these problems

**Comment by McJty** [comment]
So in summary, update and I believe this will be fixed. If not then feel free to reopen
