### ISSUE TITLE
Shield projector is not blocking villagers

### ISSUE THREAD

**Issue by winterSteve25** [McJty/RFTools#2125]
Issue description: 
Shield projector doesn't block villagers when all creatures are set to solid
Steps to reproduce: 
1. Program the projector that allows players to pass
2. Program the projector that blocks all creatures
3. Activate the projector

When the block all creatures is on the top of the filter list players get blocked but villagers can still pass through

Versions:
* Minecraft:  1.16.5
* Forge: 36.1.2
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.0.19
* RFTools: RftoolsBuilder 3.0.16

Possibly incompatible mods and versions: 

I am using chlorine but I doubt if that's the problem
Also the villagers are villagers spawned in with industrial foregoing mob duplicator

Relevant logs, if any: 
N/A

**Comment by CodeGordon** [comment]
Still an issue with current version of RFTools. A shield set up for "default solid" with no other rules still allows villagers to pass. Also using mob duplicator from IF to spawn villagers. A villager captured using the imprisonment tool can also pass the shield, so it's not likely to be a byproduct of the duplicator process.

Minecraft 1.16.5
Forge 36.2.2
McJty Lib 5.0.22
RFTools Base 2.0.11
RFTools Builder 3.1.1
Industrial Foregoing 3.2.14.3

**Comment by McJty** [comment]
Will be fixed next release. BTW, try to submit github issues to the right tracker. This belonged in the RFToolsUtility tracker

**Comment by CodeGordon** [comment]
Thanks for the fix. Odd, though, because the shields are listed as being part of Builder. Is there some cross-mod interaction with Utils?

**Comment by McJty** [comment]
Whoops. I meant RFTools Builder. Sorry
