### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by eyeofgafeeney** [McJty/RFTools#2126]
I need help with RF Power i'm not sure how it works the power cells everything so please i want help.

**Comment by McJty** [comment]
Version?

**Comment by eyeofgafeeney** [comment]
The 1.12.2 Verson

**Comment by McJty** [comment]
Direwolf20 has a spotlight on rftools (on youtube). You can check out how they work there

**Comment by eyeofgafeeney** [comment]
Ok Thanks
