### ISSUE TITLE
Suggestion:Modular Storage Crafting

### ISSUE THREAD

**Issue by blockbreaker1361** [McJty/RFTools#213]
It would be extremely nice if the Modular Storage block had a crafting grid built into it. That way, we could craft whatever from what is inside the block instead of having to craft at an outside crafting table. It would also be nice if the MS block had more than one upgrade slot for storage upgrades and the upgrades worked like storage modules from AE2 and stored more than one stack per space.

**Comment by McJty** [comment]
Yes, this has been requested before. Just not sure where to put that grid since the window is already full.

**Comment by catzs** [comment]
Add a sidebar that opens up a crafting grid on the side?

**Comment by s0uthw3st** [comment]
What catzs said - perhaps something visually similar to Thermal Expansion's Cyclic Assembler schematic grid, but functional for crafting.

**Comment by McJty** [comment]
Fixed in 1.10.2
