### ISSUE TITLE
Dial Once? Can I go back?

### ISSUE THREAD

**Issue by Lord-Volkner** [McJty/RFTools#2133]
I'm playing FTB:IE 1.7.10

First time messing with dimensions, so unsure what I'm doing. Built a random dimension, put it in the Dimension Builder, and hit dial once.

Upon arrival I set up my quarry, chunk loader, etc, and then teleported back to my base with the Charged Porter to make sure that items were coming through from the quarry. All seemed well until I tried to return to the dimension. It's no longer a dialable location.

Can I go back? How? Is my quarry and stuff just lost?

**Comment by McJty** [comment]
Did you perhaps set up your quarry so that it harvested the matter receiver there?
You can use the dimension editor to send a fully charged matter receiver to that dimension
