### ISSUE TITLE
Items are not consumed when crafting with storage tablet

### ISSUE THREAD

**Issue by lloxis** [McJty/RFTools#2135]
Issue description: 
When I craft with my tablet I can see that the items are been consumed in my storage but when I close it and reopen it again, the items (for the recipe) are back but I have the crafted item.

Steps to reproduce:
-  open a tablet linked to a storage module (tier 3 in my case)
- place for exemple an oak wood in the crafting on the left of the gui (you must only have the oak wood in you tablet storage)
- clic on "craft one" button to craft 4 oak wood planks. You can see that an oak wood has been consumed in the tablet storage
- press escape to closed the tablet 
- open the tablet again, you now have the same amount of oak wood in your tablet storage than you had before crafting but you now have the planks you crafted

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* McJtyLib: 1.12-3.5.4
* RFTools: 1.12-7.73

Possibly incompatible mods and versions: OptiFine 1.12.2

**Comment by McJty** [comment]
That's not a bug. This is how the crafting terminal works. Notice how you can't actually take out those items from there. The item is not really there. You're just marking it. There is no way to use this to duplicate stuff

**Comment by lloxis** [comment]
That's not what I meant, after putting the items in the crafting terminal, I clic on "craft one" and it cratfs it but after closing and reopening the tablet the items used for the craft are back. So I can duplicate stuff.

**Comment by HoshinoTented** [comment]
I got the same problem.

0. I put 9 Wood Planks into the storage tablet.
![image](https://user-images.githubusercontent.com/25280943/122805371-9ac29600-d2fb-11eb-9929-af51677e733d.png)

1. Then using the "craft one" button to craft a chest.
![image](https://user-images.githubusercontent.com/25280943/122805546-d3626f80-d2fb-11eb-81f6-bfe369f97595.png)

2. When I reopen the tablet, the count of Wood Planks came back to 9.
![image](https://user-images.githubusercontent.com/25280943/122805736-0c024900-d2fc-11eb-8d3c-d9a3349ad150.png)

3. Also I can take it out.
![image](https://user-images.githubusercontent.com/25280943/122805803-21777300-d2fc-11eb-8a30-9b9656f11707.png)

**Comment by HoshinoTented** [comment]
Version: 1.12-7.73
