### ISSUE TITLE
Crafter Duplication Bug

### ISSUE THREAD

**Issue by iceboundglaceon** [McJty/RFTools#2145]
Issue description: 
Noticed there's a duplication bug with rftools for mc versions 1.10.2 - 1.12.2 - 1.16.5

Steps to reproduce: 
If you place an item in the internal buffer of an rftools crafter while a storage scanner has it as routable. it can craft an infinite amount of items.

Versions:
* Minecraft: 1.10.2 - 1.12.2 - 1.16.5
* Forge: 12.18.3.2254 - 14.23.5.2838 - 36.2.0
* CompatLayer (only if on Minecraft 1.10 or 1.11): 0.3.1
* McJtyLib: 2.3.9 - 3.5.4 - 5.0.22
* RFTools: 5.87 - 7.73 - (base 2.0.11 - storage 2.0.13 - utility 3.1.2)

Possibly incompatible mods and versions: 
dupe occurs even if rftools is isolated into it's own pack

https://user-images.githubusercontent.com/25551703/133685227-31ade09e-4528-4c4e-b5d4-b5c3f7f17368.mp4

**Comment by McJty** [comment]
Sorry for the slow reply but this is now fixed in 1.16 and 1.18
