### ISSUE TITLE
Issue with RF Tools Storage Scanner

### ISSUE THREAD

**Issue by jgyori29** [McJty/RFTools#2149]
I'm having issues with my storage scanner I can deposit items and craft them but I cant withdraw them :/

I'm running:

 RF Tools V1.12-7.73
&
mcjtylib-1.12-3.5.4

with the Sbeev's Nuclear Age & Beyond Modpack

Really love this mod would love to be able to get it to function properly

Issue description: 

Steps to reproduce: 

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
That's a bit vague. What exactly happens if you try to withdraw stuff? Can you give more details? Screenshots perhaps?

**Comment by jgyori29** [comment]
Sorry user error I realised that i had an item in that orange box at the bottom which prevented me for taking anything out.

**Comment by jgyori29** [comment]
-
