### ISSUE TITLE
All The Mods 6 server crash if player accesses Matter Transceiver 

### ISSUE THREAD

**Issue by JinxSwift** [McJty/RFTools#2152]
Issue description: AllTheMods 6-1.8.14 server crashes the moment a player opens up the Matter Transceiver UI.

Versions:
* Minecraft: 1.16.5
* ATM6 1.8.14
* Forge: 36.2.20
* McJtyLib: 5.1.0
* RFTools: 2.1.0

Relevant logs, if any:  https://pastebin.com/cmBZ2byW

**Comment by McJty** [comment]
Mods need updating
