### ISSUE TITLE
Server crashing because of rftoolsbuilder.modules.

### ISSUE THREAD

**Issue by Krusse53** [McJty/RFTools#2157]
Issue description: 
I have problems with tthe server thread being held up for up to 60 seconds and then just crashing my server. After I restart the server it runs for a couple of minutes and then just repeats this process. I have a server on pebblehost where I have All the Mods 7 installed. I have contacted support there and they redirected me to here. I believe the issue is caused by something called mcjty.rftoolsbuilder.modules but I have no clue myself on what this means and how to fix it.

Steps to reproduce: 
1. Load into server.
2. Play for 3 - 10 minutes.
3. Server freezes and it says "Waiting for Server" in the top left.
4. Server kicks you with the message "Timed Out" and server goes offline.
5. Reboot the server.
6. Join back and repeat.

I'm very unsure on what is actually the cause of this so not really sure how to properly reproduce it.

Versions:
* Minecraft: 1.18.1
* Forge: 0.192.1.5
* McJtyLib: 6.0.9
* RFTools: 4.0.5

Possibly incompatible mods and versions: 
I use the latest version of Optifine.

Relevant logs, if any: 
Latest crash report containing the error which has apeared three more times.
[crash-2022-02-20_20.50.49-server.txt](https://github.com/McJtyMods/RFTools/files/8127951/crash-2022-02-20_20.50.49-server.txt)

**Comment by McJty** [comment]
Seems to be a problem with the lootr mod. Try reporting to them
