### ISSUE TITLE
Crash - Remote Storage

### ISSUE THREAD

**Issue by Crumbology** [McJty/RFTools#216]
Placed a remote storage module into it's own gui, derp.

http://pastebin.com/3aVRxRwi

**Comment by McJty** [comment]
Already fixed in 3.02

**Comment by McJty** [comment]
Or hmm. What did you do exactly?

**Comment by Crumbology** [comment]
ah thx, sorry thought we were up to date

**Comment by Crumbology** [comment]
had the remote inventory open with the module, dumping stuff in and put the module in the storage

**Comment by McJty** [comment]
Oh, seems I missed a case there. I will fix this too for next version.
