### ISSUE TITLE
Missing Dependency 1.18 beta

### ISSUE THREAD

**Issue by Lou34964** [McJty/RFTools#2161]
Patchouli should be an automatic dependency for rftools base in the curse forge library as the ingame manual will not work without it.
minecraft: 1.18.2
rftools base: 1.18-3.0.7
forge: 40.0.32

**Comment by McJty** [comment]
Automatic dependency? What do you mean by that? Patchouli is optional. I can't mark it as required because not everyone wants to have patchouli

**Comment by Lou34964** [comment]
so when i loaded rftools base into 1.18.2 i got an error when trying to open the ingame manual saying that the patchouli missing manual doesn't exist. it might be possible that there is something else missing that makes patchouli unnecessary.

here is a screenshot of my mod list.
![Capture2](https://user-images.githubusercontent.com/55504221/160883175-876eb54f-d038-40d0-ad32-f816c66de9ef.PNG)

maybe you can see something I don't.

**Comment by McJty** [comment]
yes that error is normal. If Patchouli is not present then the manual will not work. That's intentional. The manual needs patchouli. But not everyone needs the manual so Patchouli is optional
