### ISSUE TITLE
Can't directly put machines into the machine infuser.

### ISSUE THREAD

**Issue by aziel13** [McJty/RFTools#2172]
Issue description: 
Cannot drag and drop infusible machine item's into the machine infuser's right slot, but you can shift click them in

Steps to reproduce: 
1. open machine infuser
2. drag a machine that can be infused over the machine infusers right slot.
3. try to drop the machine into the right slot. it will not let you put it in. 

Minecraft: 1.18.2
Forge: 40.1.47
CompatLayer (only if on Minecraft 1.10 or 1.11):
McJtyLib: 1.18-6.0.14
RFTools: Builder 1.18-4.0.12
RFTools: Base 1.18-3.0.8

Possibly incompatible mods and versions: 
rubidium 0.5.2a
oculus 1.2.5

**Comment by McJty** [comment]
Update my mods. This has been fixed a few weeks ago

Op ma 20 jun. 2022 21:23 schreef aziel13 ***@***.***>:

**Comment by aziel13** [comment]
Ah. okay. then Il close this issue.
