### ISSUE TITLE
[Bug] RFtools Modular Storage crashes upon locking Storage module

### ISSUE THREAD

**Issue by TheonlyTazz** [McJty/RFTools#2173]
**NOTE**
Coming from the FTB-Modpack Issue tracker, forwarding because i could not replicate it but the crashlog cleary states its RFtools related
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/981

Issue description: 
Player placed Storage Module inside Modular Storage and locked it, crashed.

Steps to reproduce: 
see above

Versions:
* Minecraft: 1.18.2
* Forge: 40.1.47
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.18-6.0.15
* RFTools Storage:  1.18-3.0.8

Possibly incompatible mods and versions: 

Relevant logs, if any: 
https://github.com/FTBTeam/FTB-Modpack-Issues/files/8934383/crash-2022-06-18_21.46.28-server.txt

**Comment by McJty** [comment]
The Remote Storage Module is not yet ported to 1.16. Don't use it
