### ISSUE TITLE
Server crashes while launch,i am new to server things can you help pls..

### ISSUE THREAD

**Issue by tadashidesu13** [McJty/RFTools#2181]
Issue description: Exception in server tick loop crash 
modpack : Roguelike adventures & dungeons ,
forge-1.12.2-14.23.5.2860 version
crash report is here -> https://pastebin.com/KuS5JHEn

**Comment by McJty** [comment]
No idea why you report this to me? The crash is in the 'Bigger Crafting Tables' mod

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bigger Crafting Tables (biggercraftingtables)
