### ISSUE TITLE
Game crashes when interacting with Storage scanner and or Tablet

### ISSUE THREAD

**Issue by ellisellisellis** [McJty/RFTools#2185]
Hello,
Im playing All The Mods 8 and have been using the Storage Scanner and Tablet for several days with no problems, but as of yesterday every time i interact with either the scanner or the tablet the game hangs and then crashes to desktop. 

Im on 1.19 i believe, not sure of the forge version.

I have attached my crash report as i cant make sense of it but im sure you can :+1: 
Love your mods by the way!

https://pastebin.com/e9NtiCeK

**Comment by McJty** [comment]
It's crashing in Immersive Engineering. Please report to them

**Comment by ellisellisellis** [comment]
Consider it done! thanks for the rapid response <3
