### ISSUE TITLE
Shape card malfunction

### ISSUE THREAD

**Issue by Wraithypooo** [McJty/RFTools#2186]
Issue description: Shape card malfunction

Steps to reproduce: Right click shape card in air or press the the card gui tab in builder (With or without the card in it)

Versions:
* Minecraft: 1.19.3
* Forge: 44.1.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.1.1
* RFTools: Base 1.19.1-4.1.1 - Buillder 1.19.1-5.2.0

Possibly incompatible mods and versions: 

Relevant logs, if any: 
![mod list](https://user-images.githubusercontent.com/59403672/214344836-4f71c890-723f-4a73-aa9c-b1f05774eb1a.jpg)

**Comment by McJty** [comment]
yes? And what happens then?

**Comment by Wraithypooo** [comment]
Pressing the button in the Builder freezes the screen... Making escape button the only way (That i've found) to get to normal. I can make the builder quarry, but i have no way into the gui to black/whitelist

**Comment by Wraithypooo** [comment]
Side question.... Any way to re infuse an existing world with ores from rftools and deepresonance?

**Comment by McJty** [comment]
I'll check it out soon. And no, you can't infuse an existing world. However, the ores will generate in new chunks

**Comment by McJty** [comment]
I cannot reproduce this. Works fine for me... Weird. I need to see logs

**Comment by Wraithypooo** [comment]
Can we hook up on Discord, then i can show you if you have time. ( I am in your "place")
What logs you need?

**Comment by McJty** [comment]
Here is my channel: https://discord.gg/jaPZzxXY5Z

I need latest.log and/or debug.log

**Comment by Wraithypooo** [comment]
[latest.log](https://github.com/McJtyMods/RFTools/files/10509213/latest.log)

**Comment by Wraithypooo** [comment]
Now i setup a clean singleplayer game. only running your mods (Deepresonance, xnet and RFTools) on forge 44.1.0 and MC 1.19.3
I am still not able to open the shapecard gui on the quarryfortune card.

**Comment by McJty** [comment]
Oh that forge is not the latest. Try updating forge. Otherwise I have no clue

**Comment by Wraithypooo** [comment]
Changed to latest forge, crash. I give up

**Comment by Wraithypooo** [comment]
What java version are you running client/server?

**Comment by McJty** [comment]
Must be Java 17

**Comment by Wraithypooo** [comment]
I'm running the normal 64bit from java, but the server needed 18 from some other source. (I think it's an ATLauncher thing)
In a couple of minutes i'm going to try a fresh install of latest forge 1.4.8 and mc 1.9.3 and only the rftools mods

**Comment by Wraithypooo** [comment]
![image](https://user-images.githubusercontent.com/59403672/215275128-a971e0ab-c4c0-42d3-907e-d77ef771afbc.png)

No GUI on the card

**Comment by McJty** [comment]
With Java 17?

**Comment by Wraithypooo** [comment]
Now with java 17, no luck

**Comment by McJty** [comment]
Was fixed some time ago
