### ISSUE TITLE
Crafter Lvl 1 crash on completing recipe in 1.19.4 Forge 45.0.40

### ISSUE THREAD

**Issue by Knito58** [McJty/RFTools#2188]
Issue description: Game crash to loader after recipe is complete

Steps to reproduce: 

- MC 1.19.4
- Try to make a modpack and have about 130 mods loaded
- Newest Forge 45.0.40

* Minecraft: 1.19.4
* Forge:  45.0.40
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.19.4-7.2.1
* RFTools:  utility = 5.1.5, base = 4.1.6

Possibly incompatible mods and versions: Optifine

Relevant logs, if any: 

[https://pastebin.com/47zDG9h0](https://pastebin.com/47zDG9h0)

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed

**Comment by Knito58** [comment]
Yes it works. All items in the crafter's GUI are still red but it works. The RFTools Crafters simply are the best.
