### ISSUE TITLE
Unexpected Results Creating Dimension

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#219]
Hey there.

Attempting to create a dimension with the following dimlets gives unexpected results:

Material Default
Liquid Default
Terrain Flat
Controller Single
Biome Plains
Sky Normal
Sky Normal Day
Sky Normal Fog
Sky Body None
Mob Default
Effect None
Material Glowstone
Material Obsidian
Material Nether Quartz
Feature (small) Orbs
Structure Dungeon
Structure Mineshaft
Time Noon
Special Efficiency (x5)
Weather No Rain

Unexpectedly the controller seems to something other than a single controller, giving an ocean and heathland biome combination instead of the single expected plains biome. I have ensured the dimension cleanup command is run on the correct dimension and deleted any files. I have done this a few times with different names and whatnot with no difference in results.

I will note that this dimension configuration is identical to one I used a few weeks back with no issue.

I am also using the latest RFtools beta release (3.1 beta 2 at the time of writing).

Any advice regarding this would be much appreciated!

**Comment by McJty** [comment]
I will try this out and see if I can find a bug here.

**Comment by McJty** [comment]
Ok. I can confirm the bug. Going to fix this.

**Comment by McJty** [comment]
Fixed and will be in next release. I'm about to release 3.10beta3 in a moment. You can fix your dimension by deleting the DIM<x> folder and then let Minecraft generate it again. It should be fine then.
