### ISSUE TITLE
Storage scanner shows more items than available

### ISSUE THREAD

**Issue by TRC-Loop** [McJty/RFTools#2191]
For example I put one diamond sword into the storage scanner (it is using chests, vanilla) but it shows that I have two diamond swords in but in reality there is only one, also it seems like the display number multiplies by 2 one stack cobblestone is displayed as 128 cobblestone. I use 1.19.2 and the ATM8 Modpack but I had this issue in other versions.

**Comment by McJty** [comment]
Show me some screenshots, your setup, the user interface

**Comment by TRC-Loop** [comment]
> Show me some screenshots, your setup, the user interface

ATM8 Modpack Curseforge Latest version. For example I put 64 Cobblestone in there it is displayed as 128 but when I take it out it is still 64. screenshots:
https://github.com/McJtyMods/RFTools/assets/96308166/bf812655-e426-4e97-ab3c-332f00b79130
![image](https://github.com/McJtyMods/RFTools/assets/96308166/3040c98a-250c-49e2-be03-60d13bcc5930)

**Comment by McJty** [comment]
Oh, probably related to it being a double chest. I need to check how I can fix that

**Comment by McJty** [comment]
First, you posted this in the wrong github. This is for RFTools which is the old mod. 
Secondly I can't really fix this. You just have to make sure not to include both sides of the same double chest in the scan
