### ISSUE TITLE
How in the actual hell do you make a dimlet using block absorber??? 

### ISSUE THREAD

**Issue by noobio3** [McJty/RFTools#2196]
Issue description: It does not work, how the hell do i craft a god damn dimlet? (Coal ore specifically), (THE BLOCK ABSORBER IS 100% FILLED WITH MINECRAFT, COAL ORE, NOTHING ELSE)

Steps to reproduce: Step 1: Get dimlet workbench
Step 2: get everything needed for the dimlet
Step 3: ...You cannot craft it even when you put everything in place or use autocraft on the dimlet recipe

Versions:
* Minecraft: 1.18.2
* Forge: 4.2.10
* McJtyLib:  1.18 6.0.20
* RFTools: Rftools Dimensions

Possibly incompatible mods and versions: None
![image](https://github.com/McJtyMods/RFTools/assets/67901518/506ec949-b875-454f-8b34-122aa473ba7d)

**Comment by McJty** [comment]
You're missing the Empty Block Dimlet
