### ISSUE TITLE
(1.20.1) RF Tools Builder is using the space chamber with the copy command with preview on to duplicate blocks. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [McJty/RFTools#2199]
This was found via Reddit:

Issue description: 
Build a space chamber any size but only one high. (Height doesn't matter but more that 1 is unnecessary)
Set the RFTools Builder to copy and USE THE PREVIEW (red circle). This is what makes this possible.
Place all necessary items in a chest/barrel above the builder. Since I am using a 5x5x1 space chamber I need 25 blocks.
Once powered the builder will place a second row on top of the first one.
But only use the first 25 blocks. All of them can be mined normally. Since I place 26 in the chest, only one remains.
Steps to reproduce: 

Versions:
* Minecraft:  1.20.1
* Forge:  47.1.3
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: mcjtylib-1.20-8.0.3
* RFTools: rftoolsbuilder-1.20-6.0.1

Possibly incompatible mods and versions: n/a

Relevant logs, if any: 
Nope, we were made aware via reddit. 
https://www.reddit.com/r/allthemods/comments/17y7ak9/found_a_funny_way_to_duplicate_any_block_in_atm9

**Comment by McJty** [comment]
I can reproduce. I will investigate

**Comment by McJty** [comment]
Fixed in 6.0.2
