### ISSUE TITLE
[Crash] rendering charged porter on the the modular socket

### ISSUE THREAD

**Issue by Frontrider** [McJty/RFTools#220]
http://pastebin.com/uDnrPEhB

I tried to charge the thing with the engineer's toolbox charging module.(at the time it was easier than making an energetic infuser).

Not sure, whitch side is the source.
https://github.com/Emasher/EmashersMods/issues/135

**Comment by McJty** [comment]
Hmm. It seems to be crashing in emasher's code so I'm first going to see what they say about this.
