### ISSUE TITLE
Plugins teleport commands like /home /back redirecting to rftools dim instead of overworld

### ISSUE THREAD

**Issue by Enterprise12nx01** [McJty/RFTools#2202]
Issue description: 
Using EssentialsX on 1.16.5 when a new rftools dim is made, any existing essentials teleports (using /home for a /sethome or using /back) redirects to the rftools dimension.  Restarting the server and making a new /sethome is needed every time a new dimension is made.
EssentialsX wont do anything as they dont support mods, but figured i would try asking here for any input

Steps to reproduce: 

Versions:
* Minecraft:  1.16.5
* Forge: 36.2.39
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 5.1.8
* RFTools Base: 2.1.5
* Builder: 3.1.11
* Dimensions: 7.0.21
* Storage: 2.0.19
* Utility: 3.1.16

Possibly incompatible mods and versions: 
Mohist is being used

Relevant logs, if any: 
Logs didnt say anything but if needed ill provide them

**Comment by McJty** [comment]
That's a bug in the plugin. At least there is nothing that I can do about it from my mod. It's the plugin that is doing the wrong teleport
