### ISSUE TITLE
"Chunk not available!" in Clearing Quarry Builder

### ISSUE THREAD

**Issue by Yijare** [McJty/RFTools#2203]
Issue description: 

Playing the old SkyFactory 3 Modpack
I have set up an max size clearing quarry in the beneath Dimension, the chunk the builder is in is (force-)chunkloaded, after I exit back to the overworld, the builder stops working.

Steps to reproduce: 
Let it run for a few minutes

Versions:
* Minecraft: 1.10.2 (i know ooooooold)
* Forge: 12.18.3.2511
* CompatLayer: 1.10-0.3.1
* McJtyLib: 2.5.3
* RFTools: 7.16

![2024-01-18_17 56 25](https://github.com/McJtyMods/RFTools/assets/5788141/1d2add06-f47e-4ad3-b50a-a0ce6561ea2c)

**Comment by McJty** [comment]
Hmm weird. No idea what would cause that. Anyway. I no longer work on such old versions so not much I can do about it

**Comment by Yijare** [comment]
No problem, I was just wondering IF there was a fix to it.

I have yet to replicate that in newer modpacks/minecraft versions.

So I will close this myself, because of wontfix ;-)
