### ISSUE TITLE
Have you thought of renaming the mod?

### ISSUE THREAD

**Issue by TheDoctorSoda** [McJty/RFTools#222]
Yes, RFTools is still a descriptive name, but what about a more descriptive name? It's much more than simply "RF Tools" now.

**Comment by McJty** [comment]
I have thought about it but the problem is that this isn't easy without breaking worlds. At least the modid would have to stay 'rftools' for now. When I port rftools to 1.8/1.9 I will modularize it (dimension builder separate) as well as give it a more sensible name most lkely.

**Comment by TheDoctorSoda** [comment]
Hm, yes. That would be pretty problematic. Plus all the tutorials and spotlights are all in the name of RFTools.

**Comment by warlordjones** [comment]
FYI It is possible to change your modid without breaking worlds - I did it when merging enderglove into Brassutils - you can use the FMLMissingMappingsEvent to handle blocks/items.
