### ISSUE TITLE
Destination receivers showing up on dialer for dimensions that have been deleted

### ISSUE THREAD

**Issue by utoc** [McJty/RFTools#223]
Hello!

I have an issue I stumbled upon today where I had done some basic housekeeping and removed a half dozen dimensions using /rftdim deldim X.  After going through the dimensions I didn't need, I shut down the server, rm -rf'ed the world/DIMX directories and restarted the server.

After restarting, there are still several dialer entries for dimensions that aren't listed anymore.  When trying to select them, the console outputs the following:

    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 4, does not exist
    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 4, does not exist
    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 5, does not exist
    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 5, does not exist
    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 8, does not exist
    [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 8, does not exist

Have I made a mistake somewhere along the way?  Is this a bug?  I'm still running 2.93; haven't updated to 3.10 just yet.  FML 1448.

**Comment by McJty** [comment]
You should do /rftdim safedel X and not deldim. Anyway, you can now do /rftp cleanup to get rid of the invalid destinations.
