### ISSUE TITLE
OpenComputer can't boot with Screen Controller

### ISSUE THREAD

**Issue by feldim2425** [McJty/RFTools#224]
I don't know if it is a Issue in RFTools or OC but if I start a Computer from OC with a Screen Controller it says "Unrecoerable Error machine:1146: no such method" on the Computer Screen.
If I first start the Computer and then connect the Controller it works fine.

RFTools. 3.10
OC 1.5.13

**Comment by McJty** [comment]
Did you also report this to the OC guys? If so you can cross-link the ticket by adding the ticket link here.

**Comment by feldim2425** [comment]
https://github.com/MightyPirates/OpenComputers/issues/1255
