### ISSUE TITLE
Issue: Dimension names not updating in Dialer

### ISSUE THREAD

**Issue by OCPik4chu** [McJty/RFTools#226]
So we have a lot of worlds on my server and as one of the admins Ive been trying to clean it up.  This includes removing dead worlds and fixing names of dimensions so everything is easier.  I noticed today that when you rename a dimension, the dimension tab has the correct name and the /rfttp list command shows the updated names but the dialing devices are not updated.  IS there a way to manually fix this or can this be fixed?  thanks!

**Comment by McJty** [comment]
One thing to keep in mind is that the teleportation system and the dimension system are actually two independent units in RFTools. What the dialer shows is the name of the receiver. If you go to the dimension and right click the receiver you can change the name there. This name is unrelated to the name of the dimension (except that when the dimension is first created it gets the same name as the dimension).

**Comment by OCPik4chu** [comment]
ohhhh,  so then that will make for an easy just slightly tedious fix.  thanks.  I didn't know the systems operated independently but I guess that makes sense
