### ISSUE TITLE
Crash after updating mod.

### ISSUE THREAD

**Issue by anishin** [McJty/RFTools#227]
I have crash after updating RFTools from 3.10 to 3.11. Version 3.11 is incompatible with AgriCraft (v1.3.1/1.4-alpha).

Crash report: http://pastebin.com/78zpYRDh

I reported about this crash to author of AgriCraft.

**Comment by McJty** [comment]
This is just an id conflict. You need to change the villager ID in either RFTools or Agricraft. Not exactly a bug.
