### ISSUE TITLE
Feature Request: Rftools screens and Advanced Generators 

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#228]
I see Advanced Generators latest version has added more information to the RF API (or something like that).  I tried that version and it shows nothing still, does this mean you have something that needs changing on your end?  In older versions of AG it still shows nothing on your rftools screens.

bdew made this change specifically with rftools screens in mind, can you have a look please :)

bdew: Added support for flux generators current/maximum stored power query via RF api

**Comment by McJty** [comment]
Hmm. Are you using it on the right block? If the right API is implemented it should work but you need to make sure you let the energy module connect to the same block where you connect the energy cables from.

**Comment by b0bst3r** [comment]
Yeah that's what I did, I'll try it again and let you know.

**Comment by b0bst3r** [comment]
Yeah it does work I think I forgot to click scan lol oh well :dancers:
