### ISSUE TITLE
Suggestion: NEI [?] button support for crafter

### ISSUE THREAD

**Issue by BBoldt** [McJty/RFTools#23]
Would be nice to be able to predefine crafting recipes without actually having items. You could also support NEI's click and drag ghost items if you wanted to.

**Comment by BBoldt** [comment]
Also, when you search a recipe in NEI, what you have selected in the crafter GUI gets deselected.

**Comment by McJty** [comment]
Yes, NEI support would be nice. It is on my todo

**Comment by McJty** [comment]
Implemented in 1.10.2 but with JEI

**Comment by BBoldt** [comment]
Wow! Dusting off the old issues I see. :smile:

**Comment by McJty** [comment]
yep. Still a lot to go through. Will be for later
