### ISSUE TITLE
Chunk Loaders & Dimensions

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#233]
Similar to the report here: https://www.reddit.com/r/feedthebeast/comments/3a2hur/infinityrftools_dimensions_chunk_loader_not/

I am also having some issues with chunk loaders, frame quarries and RFTools dimensions. It doesn't seem to matter what I do - nothing on will keep the chunks loaded in the dimension if I am not there. So far I have tried several different chunk loaders with no success.

Could it be something specific with the dimensions, chunk loaders and Funky Locomotion frames?

**Comment by McJty** [comment]
Hmm, Chicken Chunks chunkloaders have always worked for me. Do they also not work?

**Comment by sciguyryan** [comment]
I've just done a little bit of testing and if I leave one somewhere normal (e.g. not attached to a frame) then they work fine. Testing with wireless redstone sending a signal back and forth.

**Comment by McJty** [comment]
What happens if you put one a frame in another type of dimension (like the nether, a mystcraft dimension or the deep dark)?

**Comment by sciguyryan** [comment]
Hard to say. I'll have to replicate the setup and that could take a bit of time for me.

Will attempt it tomorrow, currently not at home to test it.

**Comment by McJty** [comment]
Did you manage to test this?

**Comment by sciguyryan** [comment]
Sorry. I have been away from home for longer than I expected. It may be a little while before I can test this in a live world.

**Comment by prozacgod** [comment]
I too noticed issues with chunk loaders on my frames,  I used "Spot loaders" first and then "Dimensional Anchors"

It's too late for me tonight to go back and test - but I did notice that when it was mid cycle, with mining wells devouring stuff, things were being delivered back to the base station just fine, it seems like it never started the next cycle.

I'm using Wireless Redstone Chicken Bones Edition, to signal my world eater, and the signals are showing up in my bases's world (Millennium)

From this cursory examination, I'd be more likely to suspect chunk loaders not properly working on the frames before I'd suspect RFTools.

I'll compare it to other worlds generated/managed by different mods  (nether, aroma, Millennium)
