### ISSUE TITLE
Question: Crafter with multiple "ext" outputs?

### ISSUE THREAD

**Issue by desht** [McJty/RFTools#239]
Trying to understand how the crafter functions with multiple "ext" outputs - it seems to be random, but perhaps there's a pattern I don't understand?

What I'm trying to do is set up a crafter to make both wooden axes and wooden hoes to feed a couple of Ender IO farming stations, feeding the crafter with wood from a tree farm.  The recipes:

1) Int: Wood => 4 planks
2) Int: Plank => 2 sticks
3) Ext: Wooden Axe
4) Ext: Wooden Hoe

But the 4 output slots get filled with an apparently random set of the two tools, frequently ending up with either all axes or all hoes, which isn't going to work too well if a farming station needs a tool that isn't in the crafter's output buffer.  Is there a way to control which of recipes (3) and (4) actually get made, or is it just random/arbitrary?

Not a show-stopper since I can always use 2 crafters each making one tool, but interested to know if it can be done with a single crafter.  It's already tidier than using 3 cyclic assemblers :)

**Comment by McJty** [comment]
The problem is that axe's and hoe's don't stack so the four slots will get filled up very quickly. I think using two crafters for this situation is probably best.
