### ISSUE TITLE
[Suggestion] Tracking creators/owners of dimensions

### ISSUE THREAD

**Issue by RoyCurtis** [McJty/RFTools#241]
As a server owner, I would like to keep track of who is creating dimensions. This would help with asking them if they are still using their dimensions, for maintenance sake. As an example; with Mystcraft, I am able to walk through `agedata_XX.dat` and use the `Authors` tag to determine who is responsible for a given age.

Tracking dimension creators may also bring future benefits for administrators. For example; limiting players to a specific number of dimensions, where they will need to delete (either via an in-game mechanic or by admin intervention) old or unused dimensions before proceeding to create more.

## Proposals

In `RFToolsDimensionManager.dat`, I propose the addition of [two new NBT fields for dimension entries](http://i.imgur.com/HRu3lCo.png):

* `owner` - Minecraft name of the creator/owner of a given dimension. With name changes a possibility, this field should only be used to help administrators quickly identify owners. The mod should not use it to verify an owner, but should try to keep the name up-to-date (perhaps every time the dimension is loaded?)
* `ownerUUID` - Trimmed (dashless) UUID of the creator/owner of a given dimension. This is immutable per player and would be safe to use for verifying who owns a dimension. Tracking this data has potential for more administrative features.

Additionally, I propose that `/rftdim list` should list the owner along side each dimension entry, for a quick overview of who owns how many dimensions.

**Comment by MyDeloreanWontStart** [comment]
By who created the dimension, what do you mean? The person who placed the builder? Who inserted the Dimlet?

**Comment by McJty** [comment]
Since latest releases rftools keeps track of ownership of machines (the builder) so we could use that owner to tag the dimension when it is created by that builder

**Comment by RoyCurtis** [comment]
Sorry; admittedly I had not yet gotten into RFTools, so I did not realize dimensions could be created by those using somebody elses' dimlets/tabs. I think McJty's suggestion of using the Builder owner tag is a good idea. From an admin perspective, we can always double-check with the player if somebody else has been using their Builder, for example.

**Comment by McJty** [comment]
In next version of rftools I will implement dimension owner ship as well as the option (with a command for now) to let players delete their own dimensions.

**Comment by RoyCurtis** [comment]
Awesome! Thank you for the update
