### ISSUE TITLE
RFTools, Forestry multi farm, block particals.

### ISSUE THREAD

**Issue by Deckee** [McJty/RFTools#243]
This is a good pic of the strange partcials from one rftools dim showing up in a different dim.
Dim 3
![2015-07-11_00 35 31](https://cloud.githubusercontent.com/assets/8199121/8632542/5d9984c0-2765-11e5-885c-689c3e8d9fa4.png)
dim 7
![2015-07-11_00 39 56](https://cloud.githubusercontent.com/assets/8199121/8632544/63068426-2765-11e5-9404-7645f9f075c9.png)
Dim 7 has the farm 
Any other rftools dims show the particals if you are in the same area.

**Comment by McJty** [comment]
Looks like a bug in forestry to me. Did you check with them?

**Comment by Deckee** [comment]
I will check.
