### ISSUE TITLE
My dialer favorites list seems to be emptied when I die

### ISSUE THREAD

**Issue by utoc** [McJty/RFTools#244]
This one is rather odd and I only noticed it in about version 3.10.  When you die, your dialer favorites will be emptied out.  I've got three users on my server that can verify this.  Just die.  That's really all it takes.

We're running rfTools 3.11 and FML 1448.  Mod list here: https://www.reddit.com/r/BBQSauce/wiki/modlist

**Comment by McJty** [comment]
I can reproduce this.
