### ISSUE TITLE
Request to make RFTools Resourcepack friendly

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#246]
Texturing Rftools for BDCraft/Sphax and i came across an issue I cannot seem to resolve so it maybe based in the code or maybe something I am doing wrong.  

The issue is with the Modular Storage GUI.  I have textured modularstorage.png & modularstorageTop.png however the GUI icons seem to have a static background rather than a transparent one?

This means the end result is http://postimg.org/image/klne7bb2h/ or am I missing something?

**Comment by McJty** [comment]
The background is indeed rendered in code and not with a texture. Not sure how to solve that easily since this background is configurable.  BTW also make sure your layout works for the alternative rftools style too (little button on the right)

**Comment by b0bst3r** [comment]
Yeah I didn't get as far as polishing it up, didn't see there was much point when it looked like the above, can't the icons have transparent backgrounds?

**Comment by McJty** [comment]
Yes but then the colored background would be gone which is not good

**Comment by b0bst3r** [comment]
Surely modularstorageTop.png is the background?

**Comment by McJty** [comment]
Not exactly. The background is configurable in rftools config and is rendered on top of modularstorageTop and below the icons.

**Comment by Rasmun** [comment]
Huge bummer.  I was really hoping for a BDCraft/Sphax texture pack for RFTools.  :(
