### ISSUE TITLE
Thunder Dimlet not working.

### ISSUE THREAD

**Issue by unpure** [McJty/RFTools#249]
Hey there.
I just tried to create a dimension with thunder.
If i understand the dimlets correct the thunder dimlet should be thunder only right?
This is my dimlet:
http://fs1.directupload.net/images/150720/ngnz45me.jpg
This is how my dimension looks:
http://fs2.directupload.net/images/150720/rdsvcajj.png

Seems like the thunder dimlet is not working. :(

Using the latest version of RFtools and forge 10.13.4.1481

**Comment by McJty** [comment]
Note that thunder only works if it is also raining. So you probably also want to add rain dimlet to it. That's not an rftools thing but a minecraft limitation.

**Comment by unpure** [comment]
Ah i thought
rain dimlet = rain only
thunder dimlet = rain + thunder
I added the rain dimlet and its working now. Thank you! :)
Maybe there is a way to automaticly add rain if the thunder dimlet is added?
I think this would be the most logic way. :/

**Comment by McJty** [comment]
Well the thunder dimlet on its own is still useful in case you want it to always thunder in case there also happens to be rain. So it really is a distinct thing.

**Comment by unpure** [comment]
Ah ok, that makes sense.
Anyways, problem is solved, thank you! :)
