### ISSUE TITLE
"Effect None" dimlet doesn't work in dimension editor

### ISSUE THREAD

**Issue by flarn2006** [McJty/RFTools#250]
I asked about this [on Reddit](https://www.reddit.com/r/feedthebeast/comments/3dq2kg/rftools_effect_none_dimlet_not_working/), and McJty responded, but I figured I'd post it here, mainly as a reminder, but also so it will be listed with the other issues.

If you create a dimension and do not define any effects, there is a chance you will get some effects while in the dimension (blindness, etc.) This is, of course, supposed to happen--if you want to make sure it doesn't, you can use an Effect None dimlet when creating the dimension.

However, if you do *not* use said dimlet, and the dimension *does* generate with effects, trying to add an Effect None dimlet using the Dimension Editor doesn't get rid of the effects. Looking at a saved dump of the dimension information created using `/rftdim savedim`, it appears that it adds effect 0 (i.e. no effect) to the list of effects for the dimension, but it doesn't remove effects that are already there.

**To reproduce:**
1. Create dimensions, without specifying any Effect dimlets, until you find one that gives you some type of effect.
2. Add an Effect None dimlet to that dimension using a Dimension Editor.
3. Return to the dimension, and find that the effects still exist.

**Workaround:**
After adding an Effect None dimlet to a dimension using a dimension editor, you can use the `/rftdim effectlist` and `/rftdim effectdel` commands to remove all effects from the dimension manually, or have an op do so if you don't have the correct permissions.

**Comment by McJty** [comment]
Thanks for making this a ticket

**Comment by flarn2006** [comment]
No problem.

**Comment by McJty** [comment]
Fixed in next version (3.12)
