### ISSUE TITLE
villager ID

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#252]
The Villager ID of 10 is taken by Agricraft already. 

Both with default configs crashes client to desktop while loading. 

I changed the ID of the RFtools villager to 0, however this produced the same result. 

I changed the agricraft villager ID to 56, and it started up fine.

**Comment by McJty** [comment]
This is not really a bug. No matter what ID I make default in rftools there is always a chance of conflict. So just a matter of configuration

**Comment by Divineaspect** [comment]
Or you know, it could be a feature request, auto assigning IDs?

**Comment by McJty** [comment]
Actually RFTools automatically scans for the first available ID by default. Problem is that Agricraft doesn't and apparently takes its villager after RFTools does.

**Comment by Divineaspect** [comment]
They actually added that a day or so ago.
