### ISSUE TITLE
dimlets.cfg

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#253]
As the subject states - rftools 3.1.1 is currently not creating the dimlets.cfg file in the rftools folder on load, Only when logging into a world for the first time. I'm not sure if this is an issue or not, however as i am making a modpack, generally speaking i add a mod, load and unload minecraft then edit / play with configs.

**Comment by McJty** [comment]
dimlets.cfg is no longer created automatically. It is something you as a user can create to reconfigure dimlets.
