### ISSUE TITLE
Dimension Builder only accepts 50K RF/t total

### ISSUE THREAD

**Issue by sickhippie** [McJty/RFTools#263]
According to the wiki and the in-game documentation, the dimension builder should accept 50K RF/t per side for a total of 300K RF/t.  However, the default configuration seems to be set to 50K RF/t total - DimletConfiguration.java:16 and DimletConfiguration.java:107.

In FTB Infinity 1.8.1, I can only get the dimension builder to accept 50K RF/t total, with one exception: adding tesseracts can increases it another 50K RF/t total (regardless of the number of tesseracts added - 1 tesseract adds 50K total, 5 tesseracts adds 50K total).

**Comment by McJty** [comment]
Can you show me your setup because I have people using this correclty with cryoducts so I'm interested to see how you set it up.

**Comment by sickhippie** [comment]
Just found my problem - user error.  Sorry to bug you!
