### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by AlexPlus117** [McJty/RFTools#264]
I've installed the latest version of RFTools (3.20) and the game crashes. Here is the crash-report:
http://pastebin.com/4ax3jSpe

**Comment by McJty** [comment]
Did you install the new dependency (McJtyLib) as instructed?

**Comment by AlexPlus117** [comment]
Oh, I didn't know there was a new dependency. I installed it and the game works now, thank you. I'm sorry for the inconvenience.
