### ISSUE TITLE
Modular Storage Search Box Problem

### ISSUE THREAD

**Issue by expl0s1ve** [McJty/RFTools#266]
When I search something in the modular storage UI and close it, the text remains when I reopen it. It also remains if I right click to clear the text, the only way I can make it disappear is using backspace to delete the text, which makes searching a nusiance.

**Comment by McJty** [comment]
The fact that it remains when you reopen the UI is actually a feature. I might make this optional though in the future. Right clicking to clear the text should work however. Where are you right clicking exactly?

**Comment by McJty** [comment]
Found and fixed for next release of rftools 3.31
