### ISSUE TITLE
Dimlet with key BDungeons is missing after researching a bunch of dimlets.

### ISSUE THREAD

**Issue by epilimic** [McJty/RFTools#267]
Ran a bunch of dimlets through a researcher, went to see what I got and I see this.

http://i.imgur.com/E3aXwZv.png

**Comment by McJty** [comment]
This was a biome dimlet for the biome Dungeons. Can it be that this dimlet was generated at a time that you still had such a biome but that mods have changed/been updated since then? That would be my only explanation.

**Comment by McJty** [comment]
Closing due to lack of information. Please reopen if you have further info

**Comment by epilimic** [comment]
I have not seen a Dungeons biome. The only dungeon mod I run is Runic Dungeons but I haven't found or gone into one yet.
