### ISSUE TITLE
Crash with mcjtylib-1.1.0, CoFHCore-[1.7.10]3.0.3-303, rftools-3.20, and forge-1.7.10-10.13.4.1492

### ISSUE THREAD

**Issue by zwof03** [McJty/RFTools#273]
Tested mcjtylib-1.0.0 with CoFHCore-[1.7.10]3.0.3-303, rftools-3.20, and forge-1.7.10-10.13.4.1492, which works correctly.
Change to mcjtylib-1.1.0 and this crash occurs. Also occurs with rftools-3.21 instead of rftools-3.20.
http://pastebin.com/Rgrk7Cdp

**Comment by McJty** [comment]
Can you give me the crash with mcjtylib-1.1.0 and rftools 3.21? 1.1.0 is for 3.21. 3.20 is not supposed to work.

**Comment by zwof03** [comment]
Forgot to mention AgriCraft-1.7.10-1.3.1 in the original post.
mcjtylib-1.0.0 with CoFHCore-[1.7.10]3.0.3-303, rftools-3.20, AgriCraft-1.7.10-1.3.1, and forge-1.7.10-10.13.4.1492 work. 
But mcjtylib-1.1.0, rftools-3.21 and AgriCraft-1.7.10-1.3.1 does not work, with the following crash.
http://pastebin.com/hnA6J2kK
Have posted this over on Agricraft too.

**Comment by McJty** [comment]
You need to change the villager id of either rftools or AgriCraft. They both try to access the same villager. In rftools you can change this in the config. Most likely in agricraft too.
