### ISSUE TITLE
Crafter's cheaty trick

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#275]
Take a Crafter, define recipe with 1 damaged Tinker's Construct high-leveled tool and corresponding ingot to make a recipe of repaired tool. Then support that ingot and tool from same material and with same id:meta value, but low-leveled. We gets repaired, high-leveled (full of bonuses) tool from low-leveled tool!
Maybe ignoring NBT-data when crafting is universal, but it allow bad people to do bad things...

Version: 3.21.

**Comment by McJty** [comment]
Not sure I fully understand what you mean here. Do you have a screenshot perhaps to clarify what exactly that you are doing?

**Comment by NoX-programer** [comment]
https://youtu.be/eGtE48fysWk

**Comment by McJty** [comment]
Thanks for this video. Very weird. I have to see what is going on there.

**Comment by NoX-programer** [comment]
I'll try to describe: first you set up recipe, and Crafter remembers the final result with all NBT-data of result. But it is not check NBT of items we supply for craft, so we can trick it - to supply a cheaper items.

**Comment by McJty** [comment]
I could reproduce it and will fix in the next release
