### ISSUE TITLE
Client kicked/crashed when changing gui style in the Inscriber ui

### ISSUE THREAD

**Issue by TheQuadShot** [McJty/RFTools#277]
I click on the change gui style (from flat) and I get kicked from the server with "fatal error has occured, This connection terminated". I don't get a log file on the client, but here's what the server caught (I cut it down to just the crash, if you need/want more of the log, let me know):
Forge version .1492
RFTools version 3.21
mcjtylib version 1.1.0
http://pastebin.com/0bP4imQ6

**Comment by McJty** [comment]
Known bug and already fixed for the next release (probably 3.30)

**Comment by TheQuadShot** [comment]
oops, sorry, I only checked for open issues. Thanks
