### ISSUE TITLE
Crash with extratic mod using rftools-2.30.n51

### ISSUE THREAD

**Issue by crunkazcanbe** [McJty/RFTools#28]
Like the title says man . :)

The crash is http://pastebin.com/FrvL5wLq

This crash stops when going back to rftools-2.21.n45 and crashes with any version up to rftools-2.30.n51 from rftools-2.21.n45. Thanx

-Crunk

**Comment by McJty** [comment]
Ok thanks for the report and the effort of finding exactly from which version it starts failing. Much appreciated!

**Comment by McJty** [comment]
Strange that it doesn't crash in RFTools code however...

**Comment by crunkazcanbe** [comment]
Lol yeah that is a bit strange . Took me awhile to find the mod causing it because when i update mods its usually quit a few at a time . Like i said i had to go all the way back to n45 of your mod before the crash went away . It might be extra tic needs to add support to your nod

**Comment by McJty** [comment]
Should be fixed now

**Comment by crunkazcanbe** [comment]
Thanks man it is. :) I really appreciate it .
