### ISSUE TITLE
[Feature Request] Config to disable same Dimension teleportation.

### ISSUE THREAD

**Issue by GustoniaEagle** [McJty/RFTools#282]
Hello!

Can you please add a config to the Matter Transmitters / Receivers to disable teleporting to the dimension you are currently in?
ie. Matter Transmitter in Overworld cannot connect to Matter Receiver in Overworld, but can connect to Matter Receiver in Nether.

  Thanks,
    -Eagle

**Comment by McJty** [comment]
That's not hard to do and I will put it on my todo but I'm curious as to why you need this?

**Comment by GustoniaEagle** [comment]
Working on a new modpack, disabling all forms of "creative mode" flight and long range teleportation in order to create a challenging of living in a world that is made up of islands that are floating above the void.

Thanks!

**Comment by McJty** [comment]
How soon do you need this? I'm currently working on my other mod so I need to schedule time for this.

**Comment by GustoniaEagle** [comment]
Hoping to have the pack done and released by the end of August, so by around the 20th - 25th?

**Comment by McJty** [comment]
That's fine. That should work.

**Comment by GustoniaEagle** [comment]
Thanks. Good luck with Deep Resonance by the way, looking really good so far.

**Comment by McJty** [comment]
Implemented for next release (3.31) for both the matter transmitter as well as the charged porter. Note that it does allow you to dial to a receiver in the same dimension. It will just not do the teleportation (and also gives an error).

**Comment by GustoniaEagle** [comment]
Thank you!
