### ISSUE TITLE
Glowstone dust rotates machines

### ISSUE THREAD

**Issue by flarn2006** [McJty/RFTools#283]
I wanted to scan glowstone dust with my Thaumometer, only to find the latter had gone missing from my inventory. So I right-clicked the storage scanner to see if I put it in a chest, only to find it rotated instead of opening the GUI. I was confused, as I was holding the glowstone dust I wanted to scan, not a wrench or anything. I don't see why glowstone dust of all things would have this effect, so I'm assuming it's a bug.

**Comment by McJty** [comment]
Yes, known bug and already reported. Closing this as a duplicate.

**Comment by flarn2006** [comment]
Wow, that was fast. I actually saw your comment appear. Didn't know Github did that.

I searched for "glowstone" in the issue tracker by the way, and I didn't see that issue reported. If that issue is known but not in the bug tracker except for this particular report, shouldn't it be reopened since it's not really a duplicate?

**Comment by McJty** [comment]
Yep
