### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by redgoblin88** [McJty/RFTools#284]
i was messing with the space chamber card and saw the tooltip said "right click in the air to show contents. upon doing so it crashed me.

at the time i was testing if microparts worked (redstone tortch+alloy wire in same space, and redstone alloy wire on redstone lamp blocks, with every possible orientation.)

YES it is 3.11 beta BUT looking at the changelogs of the later versions they do not say anything about space chabers beimng fixed nor multiparts.

crashlog:
http://pastebin.com/a7jkVdJ5

**Comment by McJty** [comment]
This was fixed in the real (non-beta) 3.11: See this changelog entry:

Added a safety test to prevent the space chamber item from crashing in case the area contains blocks with no corresponding item.
