### ISSUE TITLE
GUI textures and other text visuals.

### ISSUE THREAD

**Issue by Fortist** [McJty/RFTools#288]
I am in the midst of re-texturing everything I can get my hands on, but the few things I cant texture or at least I dont know if I can change, are the power bars and the text around various parts of the GUIs.

Text has a lot of problems, overlaps with themselves or visual textures like power bars in the screen. (Also the screen needs more dimensions). Speaking of screens, for liquids they should at least take the color of the liquid. Also, for most if not ALL guis with power, the written text indicator shows both the cap and the current charge, when not only the cap is somewhat redundant in most cases but the text sits on top of the visual charge bar texture, with black text.

The Charge bar texture is basic and ugly, and there is no where that I can change it physically in the texture files, so I assume it's coded in. Which is pretty bad.
Want to make it like TE's charge bar design, but alas.

Also, FYI, using aliased text in the GUI textures without proper measuring is bad.

**Comment by McJty** [comment]
The RF bars use DrawGradientRect in code indeed.

What do you mean about aliased text? I'm just using basic text writing in MC with the default font. I certainly don't specify any aliasing (wouldn't even know how)
