### ISSUE TITLE
CoFHCore is required

### ISSUE THREAD

**Issue by spannerman79** [McJty/RFTools#290]
Forge: 1448
RFTools 3.31
McJtyLib 1.3.0

    [Client thread/ERROR] [FML]: The mod rftools (RFTools) requires mods [CoFHCore] to be available

Suggestion:  Edit related projects under [RFTools 3.31](http://minecraft.curseforge.com/mc-mods/224641-rftools/files/2252229) to point to [CoFHCore](http://minecraft.curseforge.com/mc-mods/69162-cofhcore) as a required library like what you have done with McJtyLib

**Comment by McJty** [comment]
Fixed some time ago.
