### ISSUE TITLE
Random Crafter Firework crash - NullPointerException

### ISSUE THREAD

**Issue by deregges** [McJty/RFTools#291]
- Modpack: FTB Daybreaker Horizons
- Setup: Default Firework recipie (Paper+Gunpowder) in Crafter Tier 3
- Crash after putting Gunpowder in by hand (paper is already in it)
- ! Random (worked before and wasn't able to reproduce it...)
- Error log: http://pastebin.com/ZcXvUFz5

**Comment by McJty** [comment]
I cannot reproduce this in rftools 3.31 but I also did fix something there so it is possible this bug is solved

**Comment by deregges** [comment]
Okay was now able to reproduce it.
Have made an instance with only RFtools 3.31, mcjtylib 1.3.0, CoFHCore and ExtraUtilities for PowerGen.

Both times I placed a crafter and set the recipie for the rocket,
When I power it and then put the items in it works.
When I first put the Items in and then Power it it crashes.

Same crash but still here the Crash Report:
http://pastebin.com/cxBiUju9

**Comment by McJty** [comment]
Aha, now I could reproduce this.

**Comment by McJty** [comment]
Next version of RFTools will have a workaround for this. Not sure what causes the crash though but at least the crash will be gone
