### ISSUE TITLE
Server stops when right clicking Shield Block

### ISSUE THREAD

**Issue by Ikabodo** [McJty/RFTools#292]
RFTools Version: 3.31
CoFHCore Version: 3.0.3-303
CoFHLib Version: 1.0.3-175
mcjtylib Version: 1.3.0 

Error log: https://gist.github.com/Ikabodo/21fc6c9371577cf874d8

Some dependency I'm missing?

**Comment by McJty** [comment]
Oops. I'll fix this

**Comment by McJty** [comment]
Will be fixed in next version (3.32)
