### ISSUE TITLE
#291 - Was able to reproduce in RFtools 3.31

### ISSUE THREAD

**Issue by deregges** [McJty/RFTools#293]
Okay was now able to reproduce it.
Have made an instance with only RFtools 3.31, mcjtylib 1.3.0, CoFHCore and ExtraUtilities for PowerGen.

Both times I placed a crafter and set the recipie for the rocket,
When I power it and then put the items in it works.
When I first put the Items in and then Power it it crashes.

Same crash but still here the Crash Report:
http://pastebin.com/cxBiUju9

**Comment by deregges** [comment]
Okay further progress:
It crashes when you put the items in where the Crafter's power hasn't changed since the world is loaded

**Comment by McJty** [comment]
I still cannot reproduce :-/

**Comment by McJty** [comment]
Duplicate
