### ISSUE TITLE
Item Duplication using Shield Projectors

### ISSUE THREAD

**Issue by Dunaka** [McJty/RFTools#294]
Hi there! There is a way to duplicate items using your Shield Projectors, here are the steps to recreate the issue.

1. Place a Shield Projector
2. Open the Shield Projector
3. Place a block or item into the Shield Projector inventory to set forcefield texture
4. Exit the Shield Projector
5. Break the Shield Projector with a wrench or pickaxe
6. The item/block that was inside the Projector drops, as well as the projector itself.
7. Place the Shield Projector back down
8. The item that was inside the Projector when you broke it and dropped will be in the Projector still, as well as your inventory.

Hope that lets you recreate it sufficiently! ;)

**Comment by McJty** [comment]
What version of RFTools?

**Comment by McJty** [comment]
I cannot reproduce this with latest RFTools. This used to be a bug in old versions of RFTools but I fixed that. That's why I asked what version you're using

**Comment by Dunaka** [comment]
Sorry! I forgot to check my mod version, it was 2.8 haha, my bad! Thanks anyways for being awesome and making the mod~
