### ISSUE TITLE
ConcurrentModificationException with Dialing Device

### ISSUE THREAD

**Issue by FatherOwnage** [McJty/RFTools#295]
Modpack - FTB Infinity v1.10.1 - RFTools v3.30
 - Manually added Mods -
 -- Micdoodle/Galacticraft Core & Planets 1.7-3.0.11.333
 -- Mekanism-1.7.10-8.1.7.252 (tools and generators)
 -- Disabled Mystcraft completely

Randomly started getting  this issue when right clicking on the Dialing Device, the server would crash and shutdown.

Managed to track it down to RFToolsDimensionManager.dat
 - something in there causes this crash

Crash Report: http://pastebin.com/xjPVBgRJ

let me know if you need a copy of the RFToolsDimensionManager.dat and related files.

**Comment by McJty** [comment]
Why are you assuming this is related to RFTools? The crash is not in RFTools code at all. I have no idea what is going on but I have strong doubts this is an RFTools issue.

**Comment by FatherOwnage** [comment]
I thought it might have been RFTools because when I try to use the Dialing Device, the server crashes.

A work around has been to replace RFToolsDimensionManager.dat from an earlier backup and turn the server back on. Huzzah, I can use the dialing device again with out crashing the server.

**Comment by McJty** [comment]
hmm. Weird though. One explanation might have been a corrupt dimension or so. Not sure though.

**Comment by FatherOwnage** [comment]
yeah, that's what I thought corrupt dimensions, but just restoring RFToolsDimensionManager.dat fixes the issue and I dont have to touch region files at all. Or maybe RFToolsDimensionManager.dat keeps getting corrupted somehow?

**Comment by McJty** [comment]
RFToolsDimensionManager.dat just keeps track of the dimensions. It doesn't actually hold a lot of dimension information. I think that it is more likely a dimension itself got corrupted and by restoring an older version that dimension is no longer known to RFTools which causes Minecraft to forget about it. And what Minecraft doesn't know can't crash it :-)

**Comment by FatherOwnage** [comment]
Actually, I am the only one making dimensions.
I have not created any new dimensions while this issue has happened. Currently only have 9, including links to the Nether and The End (I do want to note, the The End doesnt resolve to "The End (1)" on the right side of the Dialing Device. It just looks like this "The End  Id 1"

I didn't mention it, but I do restore the 3 files from backups to fix/work around the problem: RFToolsDimensionManager.dat - RFToolsDimensionStorage.dat - RFToolsDimletMapping.dat

Like I said, I dont touch anything regarding the dim folders/region files. Those 3 dat files are the only things I roll back (to keep all data matching, but does not contain a different number of dims compaired to when it crashes)

**Comment by McJty** [comment]
No clue. Never heard of a similar report :-/

**Comment by FatherOwnage** [comment]
Any other idea's, maybe to help figure out where the issue might be really coming from?

Thanks for the help so far, I really love RFTools and I think its amazing. I also think you're awesome for taking a bit of your time to at least give this a bit of attention.

**Comment by McJty** [comment]
Can you do an /rftdim savedims <directory> (with a directory of your choice), then zip that directory and send it to me?

**Comment by FatherOwnage** [comment]
Sure thing.
Here you go: https://drive.google.com/open?id=0BzjTJ2AAhn6MTkpSYkxJZVRfdW8
Let me know if you need any more info, thanks.

**Comment by McJty** [comment]
I need permission to download it.

**Comment by FatherOwnage** [comment]
Updated link, please try again.

**Comment by McJty** [comment]
Is this with a corrupted world or not? If not it would be nice to also have exactly the same zip file but then from the corrupted world. Perhaps I can see the difference then.

**Comment by FatherOwnage** [comment]
Makes sense. When the crash happens again, I wont restore the dat files and just bring the server back up as is with the issue and resave the dims and send them over.

**Comment by FatherOwnage** [comment]
Well that was fast... crashed at 1:20am PST
https://drive.google.com/file/d/0BzjTJ2AAhn6MaGZnUUdvRXo2djQ/view?usp=sharing

I hope this helps *keeping fingures crossed*

**Comment by McJty** [comment]
No difference... What exactly did you do during the time it was ok and the time it crashed? Especially what dimensions did you visit?

**Comment by FatherOwnage** [comment]
Setting up a Wither Farm in Dim4 (Random03) - everything running fine, currently have 1 chunk loader (Radius of 2) in Dim4 to keep the Enderman Farm going (draconic grinder and spawner).

AE2 Quantium Link to access my network from the overworld (powered by magmatic dynamo)

I teleported out of Dim4 (Random03) using Draconic Charm of Dislocation

Was in the overworld for about 10 minutes to make reinforced obsidian.
Got what I needed and tried to go back to Dim4 (Random03) and crashed when I right clicked on the Dialing Device.

**Comment by FatherOwnage** [comment]
Also note, Dim4 (Random03) is self sustained by an Advanced Solar panel, so nothing in Dim4 runs out of RF.

**Comment by McJty** [comment]
At the moment I have no clue what is going on

**Comment by FatherOwnage** [comment]
Not sure if this helps, but the console also shows a couple things when it crashes:

[01:36:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_51]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_51]
        at net.minecraft.world.World.func_72939_s(World.java:1933) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by FatherOwnage** [comment]
Another thing I noticed when this crash happens: https://drive.google.com/file/d/0BzjTJ2AAhn6McEpDX3lDQlF5ZGM/view?usp=sharing

When the server decides to update the dat files, it looks like RFToolsDimensionManager.dat is never updated. As you can see the time stamp still dates from the 15th.

Where as RFToolsDimensionStorage.dat & RFToolsDimletMapping.dat have newer time stamps on them.

**Comment by McJty** [comment]
BTW. Can you try updating forge?

**Comment by McJty** [comment]
Closing with lack of information.
