### ISSUE TITLE
Can't find/create dimlet.

### ISSUE THREAD

**Issue by anishin** [McJty/RFTools#297]
Hello!
Firstly, great thanks for your work!
Secondly, I have a simple issiue: I can't create/find/add (with config file) dimlet for Sky Biome (biome of End world). 
But (and that's strange) Biome Absorber detects this biome. And with this device with Sky Biome Essence I can't create dimlet with Dimlet Workbench (I tried all variants of combination of modules).

I also tried to add config options for Sky biome in "dimlets.cfg" (as I understand, RFTools scan all biomes/liquids/materials and find custom values for its in that config file). But this doesn't work: I haven't this dimlet anywhere (in NEI/creative tab).

Please, fix this problem, or explain me why you disabled this dimlet (if it is made especially).

P. S. Sorry for my English, I'm from Russia.

**Comment by McJty** [comment]
The Sky dimlet is blacklisted by default. The reason is that it can cause problems because it causes the ender dragon to spawn. People have reported crashes with the sky biome as well. It is a special biome that you cannot easily use elsewhere.

**Comment by anishin** [comment]
Thank you for information.
