### ISSUE TITLE
Request Draconic Evolution Energy module support

### ISSUE THREAD

**Issue by Protheus** [McJty/RFTools#30]
Draconic Evolution (http://www.tolkiencraft.com/draconic-evolution/) has a Energy Block (multi structure) and is able to store 2.14T of energy. 

Would love to see that I can link the Energy Module for the screens to this core as the moment It tells me "Energy Module is cleared".

**Comment by McJty** [comment]
Hmm. If it says 'energy module is cleared' that actually means that this block isn't really supporting the CoFH energy api and that makes it harder for me to support that. Does this energy block actually support RF? Can you connect energy cables from (for example) EnderIO or other RF mods to it?

**Comment by Labs4077** [comment]
The block stores energy and supports RF however you don't interact with the storage block directly. Energy is extracted and inserted by connecting rf conduits and the like to Energy Pylons

**Comment by McJty** [comment]
Ok, I guess the only way will be to look up how it works. I'll check this later.

**Comment by McJty** [comment]
Forgot to close this
