### ISSUE TITLE
Dimension Unbuilder

### ISSUE THREAD

**Issue by Ratismal** [McJty/RFTools#300]
Hello,

I'd like to suggest a feature for something like a Dimension Unbuilder. It is like the Dimension Builder, but does the opposite (deletes the world).

The reason I'm asking for something like this is because it makes it easier to experiment with dimlet combinations without bogging the server down with excessive worlds. For example, a couple days ago I was trying to make a dimension, but it kept not letting me enter (Dialing device would say that it's an Invalid Destination). I narrowed it down to one of the patreon dimlets I had installed (Puppeteer), but not before 5 dimensions were created in the process. Being able to delete unwanted dimensions without requiring op privileges would be fantastic, as it would allow players to tinker around with dimlets until they make the one they want, without creating excessive worlds that use server resources to maintain.

I hope you take this into consideration. Thank you for your time,

Ratismal

**Comment by technolem** [comment]
You'd still need op privileges to prevent griefing though. Unless you add dimension security as well... Maybe have creator be an extra attribute, to avoid blocking other people from certain combinations?

**Comment by McJty** [comment]
Yes the potential for dangerous situations and things like that has led me to postpone this feature. Not saying that I will not do it eventually but it needs good thinking

**Comment by Ratismal** [comment]
That sounds fair! Thank you for the consideration!

**Comment by McJty** [comment]
In next version of rftools I will implement dimension owner ship as well as the option (with a command for now) to let players delete their own dimensions.
