### ISSUE TITLE
[Enhancement] Upgrade path is needed to be documented somewhere

### ISSUE THREAD

**Issue by hron84** [McJty/RFTools#305]
I playing with a modpack named Pathfinder that seems like abandoned (it didn't get an update many-many months ago) and since I have ton of bugs with RFTools that already fixed in later versions (according to GH issues), I tried to get latest jar and upgrade. However, after upgrading RFTools from 2.62 to 3.30, I got the following exception:

```
java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268) ~[DimensionManager.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73241_b(ChunkProviderServer.java:70) ~[ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:820) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:241) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

I guess something is changed with dimension building, however, there is no documentation how can you upgrade from older RFTools. Can you help me what could go wrong (if I did anything wrong), and what steps are needed to achieve the upgrade? Also, would it be possible to make a FAQ about it to help other users to do it?

**Comment by McJty** [comment]
Hmm... I must admit that this is a bit complicated. I hope you have a backup of your non-upgraded world? In any case. There are two possible paths that you could follow:

a) Start all over and upgrade in smaller steps.
b) Use the upgraded version and use the /rftdim recover 3 command (or better, /rftdim recover while holding the dimension tab in your hand)

**Comment by hron84** [comment]
Okay, let's complicate this even more: 1) I cannot _load_ the world, this crash is happens during the world load 2) It is a prebuilt world, the pack itself uses Lockdown to prevent creating a completely new world, and you spawn right in the RFTools dimension. Despite these problems, the dimtab is not available for the prebuilt (skyblock) dimension, and also no documentation about its content. 

So first, I have to be able to load my world and second, I should be recover the dimtab somehow before recover the dimension itself. The first problem can be worked around if I teleport myself to the overworld right after the login (technically I can do it via /cofh tpx), but I have doubt about the second problem, as I did not find any command to get a dimtab for an already generated world.

**Comment by McJty** [comment]
Well you can also use /rftdim recover without the dimension tab. It might also work in some cases. You just have to give it the dimension id (3 in your case) then. No guarantees but it is worth a try

**Comment by hron84** [comment]
I'll give a try when I'm at home again, and report the results anyway.

**Comment by hron84** [comment]
I tried to recover the dimension, but It says me I have to hold a realized dimension tab in my hand. So it does not let me use the  command.

**Comment by hron84** [comment]
But... wow. I placed down matter transmitter, matter receiver and a creative cell, and I was able to teleport. It did not work previously with 2.x line. So... the upgrade path is seems easy, some of the 3.x versions are solved all compatibility issues, except if the spawning dimension is an RFTools dimension.

**Comment by McJty** [comment]
Normally the /rftdim recover command should work without a tab in your hand if you manually add the id like this: /rftdim recover 3

The new textures were not done by me but I do like them too :-)

**Comment by hron84** [comment]
I tried that command, but it said the mentioned error in chatbox. However, as I was able to teleport back to my dimension w/o recovering, I'm not really care about it. I just enjoy the result. I'm a simple man, with simple wishes. You fulfilled them.  I'm happy.

**Comment by hron84** [comment]
Also a strange bug popped out: I cannot craft TE4 portable tank anymore. I'll update CoFH mods as well, but it's a strange bug...

A question: is there a way to sleep in a RFT dimension, or beds are still a cool-looking grenades here?

**Comment by McJty** [comment]
Crafting bugs are often caused by MineTweaker. Typing /rt reload can probably fix it (or restarting the game).

And no, you can unfortunatelly not sleep in rftools dimensions. But they will no longer explode.

**Comment by hron84** [comment]
But my character is soo (yawn) sleepy! :smile: 

The crafting issue popped out right after starting the game, but I'll check MT settings anyway, thanks for the pointer.

**Comment by hron84** [comment]
@McJty I'm not able to check w/ FTB Pathfinder anymore as I lost that instance (in a hard disk failure). You can close this ticket if you do not have any pending tasks against it.
