### ISSUE TITLE
Issues with Matter Transmitter/Reciever and frame moving mods

### ISSUE THREAD

**Issue by DrStage** [McJty/RFTools#31]
Hi!

I've encountered an issue with mods that add frames (funky locomotion, framez,...)

Placing a Matter Transmitter on frames and move it allows you to connect to a reciever, the animation shows up, but stepping on it does nothing. Replacing works fine.
A Matter Reciever produces the following issue: only the original position remains in the dialing list, the new one does not appear. The position stays in the list, even if the transmitter is removed. So after a while, your list gets crowded with invalid destinations. If a transmitter was connected during movement, you still can use it and land on the original position without a reciever beeing there.

**Comment by McJty** [comment]
Matter Transmitters and Receivers have internal cached positional information which external block movers cannot update. This is not easy to solve unfortunatelly but for now I will leave this ticket open so that I don't forget about it if I find a solution.

**Comment by DrStage** [comment]
I think the biggest problem is the Matter Reciever remaining in the dialing list. Maybe you could add a refresh button (or auto-refresh) to the list, so it updates the position/remove invalid targets?
Other issues can be solved with replacing the blocks.

**Comment by McJty** [comment]
There is currently an /rfttp cleanup console command that you can use to clean up invalid receivers. That's half of the solution :-)

**Comment by McJty** [comment]
This will be fixed in 2.51
