### ISSUE TITLE
bug with RFTools and EC3

### ISSUE THREAD

**Issue by Eidelmaim** [McJty/RFTools#310]
the bug i have found involves RFtools storage module and Essential Craft 3

Horizons Daybreaker 1.1.0
Essentials Craft 3 4.6.1710.35
RFTools 3.11

https://www.youtube.com/watch?v=Ltp5En3Ae4Q

**Comment by McJty** [comment]
This is not a bug in RFTools. The modular storage block implements ISidedInventory and other mods should follow the restrictions of that api. I specifically return false for extraction attempts for the storage module slot. Other mods should under no circumstances extract items from that slot.
