### ISSUE TITLE
Crashing when opening timer GUI

### ISSUE THREAD

**Issue by Marti2203** [McJty/RFTools#314]
Yesterday I did some stuff in a test world and the Timer was working normally, but after I updated to the newest version, I crash when I try open the GUI. Here is a link to the crash report.

http://pastebin.com/CtGcWRqV

**Comment by McJty** [comment]
Hmm that's weird. There is also no RFTools code in that stacktrace. I will try to see if I can reproduce it

**Comment by Marti2203** [comment]
I will redownload the mod if the file has been corrupted while download.

**Comment by Marti2203** [comment]
Okay, after redownloading the mod, the issue has been fixed. Thank you for the help.

**Comment by McJty** [comment]
Oh, weird that it got corrupted...
