### ISSUE TITLE
Detecting a 'frozen' dimension

### ISSUE THREAD

**Issue by LemADEC** [McJty/RFTools#318]
what would be the preferred way to detect a frozen dimension and prevent players to access it using other mods?
More specifically, in the WarpDrive mod, players can travel with their ships to other dimensions. I would need a way to detect if an RFTools is valid or not and lockout the ship so it doesn't enter it.

**Comment by McJty** [comment]
What exactly do you mean by valid dimension? A dimension out of power?

**Comment by LemADEC** [comment]
Yes, I mean a dimension without power.

**Comment by McJty** [comment]
And you want to know this from a coding perspective or from a player perspective?

BTW, note that even a frozen dimension can be a valid destination. RFTools has an item that allows a player to travel in an unpowered dimension for a limited time (the Phased Field Generator). That gives the player a way to possibly recover stuff there.

**Comment by LemADEC** [comment]
I meant from a coding pespective, I'm transferring a whole ship/base between dimensions, including the players.

**Comment by McJty** [comment]
At the moment I don't have an API to detect that but I suppose I could add something like this. I'll see if I can do this for next release.

**Comment by LemADEC** [comment]
Thank you!

**Comment by McJty** [comment]
Implemented in next version. The API is the interface RFToolsWorldProvider which you can query from the world provider of a dimension.

**Comment by LemADEC** [comment]
Thank you!
