### ISSUE TITLE
Crash when returning from dimension

### ISSUE THREAD

**Issue by Yatekko** [McJty/RFTools#32]
I created a completely random dimension, kept it supplied with power through my main power system throttled via Power Relay, and set up a Transmitter / Receiver system.  I went through, built a small base with Transmitter / Receiver system powered by Tesseract and hopped back to the overworld... and crashed:  http://pastebin.com/GniRp4v7

Please let me know if there is any more information I can provide.

**Comment by McJty** [comment]
I think this bug is fixed in 2.31b. Can you confirm that? Thanks!

**Comment by McJty** [comment]
For now I think this bug is fixed. If someone can reconfirm this with 2.31b or later then please reopen or make a new ticket. Closing this.

**Comment by Yatekko** [comment]
I'm sorry about not responding; we had a family emergency.  I can confirm that this is fixed as of 2.31b.  Thank you for the fast response!
