### ISSUE TITLE
Suggestion - Add info and warning in the case you install a mod with dimensions after RFTools

### ISSUE THREAD

**Issue by nicogranelli** [McJty/RFTools#322]
I installed Twilight Forest after I started playing my world (no idea how could I forgot it), and upon entering its dimension, I died in a "in a collapsing world". Obviusly, that was my fault, I should have checked the dimension id in twilight forest config to look for possible conflicts with existing rftools dimensions. But adding something related to this in the faq would be nice. 

Also, in this case the conflicting dimension wasn't important, so I did a "/rftdim deldim" without "/rftdim reclaim" nor "/rftdim safedel" hoping RFTools wont try to use that id again. Did I do it correctly? it seems to have worked, but I haven't tried to create another dimension in rftools.

**Comment by McJty** [comment]
RFTools will not use any dimension that is already registered by another mod. So if you delete the rftools dimension and then let TF use it then you'll be fine.

**Comment by nicogranelli** [comment]
Thanks you very much.
