### ISSUE TITLE
rftools dim not loading on server restart

### ISSUE THREAD

**Issue by Saereth** [McJty/RFTools#325]
not sure if this is a bug or intended, but we can'i seem to get rftools dimensions to load with the server. Even if we throw an admin anchor on it, we have the dimension powered at spawn so it loads with the world the actual rftools dimension will not load until someone enters it. Is there anyway a player, or even a server administrator can force the dimension to load on server restart?

**Comment by McJty** [comment]
Some chunk loaders have troubles with rftools dimensions. I know that with ChickenChunks it should work.

**Comment by Saereth** [comment]
we used railcraft admin anchors, and immbis dimensional anchors neither were able to, we have mfr that hasnt been tried so we can give that a whirl. Chickenchunks had some pretty serious compatibility issues with our pack, will do some more testing and let you know which did or didnt work for us if nothing else.

**Comment by Saereth** [comment]
disregard, this was a cauldron issue, typical :p
