### ISSUE TITLE
Chunk loader + RFTools dimension = Server thread overloading?

### ISSUE THREAD

**Issue by ringosham** [McJty/RFTools#326]
I was in a single player world. Having a solar evaporation plant from mekanism for my reactor and other things. I decided to chunk load the area with dimensional anchors. Problem is, the log starts spamming with server overloaded warnings and breaking blocks takes AGES when I WASN'T inside the RFTools dimension. I typed "/cofh tps" to see which dimension is having lag issues and it is exactly the flat desert world that I created. It dropped down to 4.16 tick/s (Normally should be 20 tick/s). I don't know what caused it though.

**Comment by McJty** [comment]
Can you see if this also happens with other chunkloaders?

**Comment by ringosham** [comment]
I just tired with MFR's chunk loader. Nope. I think last time I logged off inside a RFTools dimenion and when I came back, the game dropped to 0 fps and I have no clue what happened. Absolute insane lag. I was forced to MCEdit myself back to the overworld. Then, this issue happened. I will try to make another dimension and see if this issue is still happening.

**Comment by ringosham** [comment]
I think I messed up that RFTools dimension beacuse of that crash. It amazingly chunk load ITSELF without a chunk loader in the world.

**Comment by McJty** [comment]
That doesn't seem possible. How do you know that it is chunkloading itself?

**Comment by ringosham** [comment]
I am not 100% sure that it is chunk loading, but here's what the "/cofh tps" output as.

Overall: 0.92 TPS/1084.22MS (4%)
Overworld [0]: 20.00 TPS/11.88MS (100%)
Nether [-1]: 20.00 TPS/0.05MS (100%)
Underdark [-100]: 20.00 TPS/0.08MS (100%)
Spirit World [-37]: 20.00 TPS/0.03MS (100%)
Torment [-38]: 20.00 TPS/0.03MS (100%)
Mirror [-39]: 20.00 TPS/0.02MS (100%)
rftools dimension [11]: 0.97 TPS/1028.87MS (4%)
The Last Millenium [-112]: 20.00 TPS/0.23MS (100%)
Twilight Forest [7]: 20.00 TPS/0.04MS (100%)
Mining World [6]: 20.00 TPS/49.11MS (100%)

I got 5 RFTools (id 11-15) dimensions and only id 11 is on the list, but that was just my assmption.
Should I delete all the data inside that dimension and see if that solves it?

**Comment by McJty** [comment]
Hmm perhaps. What exaclty is in that dimension?

**Comment by ringosham** [comment]
That was just a desert flat world full of marble form chisel.

**Comment by spannerman79** [comment]
> That was just a desert flat world full of marble from chisel

It *might* also be a compatability issue with Chisel as well

> it disappears from the list when I was in the overworld

All that means is that (more then likely) the RFTools dimension you created just got unloaded - which is good server wise.  But if you build all of those Mekanism devices and structures you will need to keep those areas chunk loaded.

**Comment by ringosham** [comment]
The thing is. Whenever I tried to dial my transmitter to that RFTools dimension. Forge automatically chunk load(probably it chunk loaded a bad chunk?) that dimension. I have removed all chunk loaders(I originally used dimensional anchors to chunk load a 5x5 chunk area) in that area. I'm gonna just adbandon that glitched dimension and make a new one, but using cobblestone as the material.

**Comment by spannerman79** [comment]
Whats the CPU speed (and cores), and the amount of ram you have allocated to the forge server instance?

Low TPS (usually) means not enough server resources assigned.

**Comment by ringosham** [comment]
I am pretty sure that was not lag. I abandoned the world and it has no lag at all. But here are the specs.
Intel i3-2130 3.30 GHz
1.5 GB RAM allocated (I only got 4 GB in my computer. That is the maxmium I can put)
Using the lastest version of Java 7.

**Comment by McJty** [comment]
1.5GB ram is really very low for modded MC. Not much that can be done about this from RFTools point of view.
