### ISSUE TITLE
Dimension behavior strangeness with Cauldron

### ISSUE THREAD

**Issue by Saereth** [McJty/RFTools#328]
I understand not alot of mod authors want to deal with cauldron so understand if you dont. Here is the issue we're having though. We setup magnetic containment pipes for reactorcraft, they require a constant charge from another tile entity (van de graff generator). This is in an rftools dimension that is loaded always. On vanilla forge we restart and everything is fine. With cauldron we can do the same setup in the overworld and it's fine. With cauldron+rftools however the pipes loose containment on restart. I've reported the issue to kcauldron development here https://gitlab.prok.pw/Prototik/KCauldron/issues/184

just wanted to keep you in the loop, appreciate all the work on this great mod regardless if you decide to follow up on this or not! :)

**Comment by spannerman79** [comment]
@McJty the user doesn't provide much diagnostic information on the kCauldron issue tracker so its been closed.

I suggest you do the same here

**Comment by McJty** [comment]
Closing due to lack of information
