### ISSUE TITLE
Crafter - recipe result preview slot able to eat item stacks  

### ISSUE THREAD

**Issue by JLBShecky** [McJty/RFTools#329]
![bug](https://cloud.githubusercontent.com/assets/842813/9840214/69a20ba0-5a5c-11e5-8c4a-6f990230d31a.png)

I hope that I can make this clear enough, but I accidentally discovered that you can put items into the recipe out slot in the crafter UI. Once you have an item in the slot you can't remove it and it the Crafter is broken it item disappears.

Ok and I did a few more tests before finishing this report and disconnecting and then rejoining the server keeps the items still in the slot, though I haven't tested stopping and restarting the server, though I think that it would not make a difference. I also have yet to find anything that can pull anything out of the slot, most likely since it is meant to normally not hold anything.

**Comment by McJty** [comment]
Fixed in next release
