### ISSUE TITLE
Crafter shows incorrect information

### ISSUE THREAD

**Issue by SirSpoony** [McJty/RFTools#33]
The craft machine, when holding shift, shows that it is capable of holding 8 recipes on all 3 of the tiers. I'd expect it to show the correct amount, such as 2 for the first tier, though it display 8. In the gui, it shows the ability to only hold two recipes, though, so it is nothing more than a ui bug as far as I can tell.

- spoony

**Comment by McJty** [comment]
Fixed in next release.
