### ISSUE TITLE
problem when busy lot ID

### ISSUE THREAD

**Issue by SvEgiiVEteR** [McJty/RFTools#330]
I do not know much English ... but I hope I can explain.
I have little free ID.
but removed a few mods and released part.
but it does not help. my old map breaks when I add your mod.
that's part of the log when the map is loaded.
http://pastebin.com/C3cdTC2s
then go to the error of different mods, here's one of them.
https://github.com/UnwrittenFun/ImmersiveIntegration/issues/33

on the server it is not clear what the problem is, so I thought that the reason that mod(ImmersiveIntegration).I could understand only to the SSP

if I create a new card is loaded well.
the world works.
that is, the enough of free ID.

mod can not capture all the free ID, ID and interfere with other mods ...
I think so....
if it can be corrected, without creating a new map, please tell me.
really want your mod to add.))

**Comment by McJty** [comment]
Hmm... You probably will have to remove more mods if you run out of id's. Not sure exactly if this will really fix the problem. Make a backup first, remove another mod or two and see if that helps. If not then I'm not sure what can be done about this I'm afraid :-/

**Comment by SvEgiiVEteR** [comment]
I try ... but for me still is strange behavior. because free ID available. a new map is created ....
When I create assembly mods, I added a lot of mods at once.

maybe with other mods have the same problem ... if add them to the map created earlier.
or may be a second mode causes a bug ..

bad that there is no other solution (((

**Comment by SvEgiiVEteR** [comment]
I was able to load the map by turning off the 20 mods.
but when I go to the server, and now such a problem ...
http://pastebin.com/2psGA7hp
Bud is your mod as it breaks the other mods .... blocks that are on the earth.

**Comment by McJty** [comment]
This looks like a problem in Tinkers Construct. The slime code is from that mod. No idea what's going on though

**Comment by SvEgiiVEteR** [comment]
there can be any mistake ... from different mods.
ThermalExpansion- [1.7.10] 4.0.3B1-218.jar
PneumaticCraft-1.7.10-1.11.7-127-universal.jar
and IC2 ....
when I tried to load the game to your mod on the old map.
mistakes were different modes.
and now finally was able to load the game again is another error ... with TC, but on the client
I do not want to make a new map ....

**Comment by SvEgiiVEteR** [comment]
the problem remains.It was 340 mods.
reduced the number to 110.
old map loaded.
I put your mod. not loaded. without the crash.
just hanging ...
not sure, but maybe mod is looking for the first free block ID, and then puts them in order to replace the block ID from other mods without missing them?

**Comment by McJty** [comment]
I just found out that removing a mod does NOT release the ID's that it used. Those are gone forever. Perhaps that's the cause of your problem? If that's the case then there is no solution I'm afraid.

**Comment by SvEgiiVEteR** [comment]
Yes it is possible and reason ....
before it was handy when I myself am writing ID ...
and now even afraid to update mod ... in each map will break. If a lot of mods ...

**Comment by SvEgiiVEteR** [comment]
another reason .... even if you have little mods. not that a new mode, or if the update mode, causing the crash of the world. they seem to break the the original block ID on the map ...
Internet solutions are not found. my friend was faced with the same problem but with another mod.
