### ISSUE TITLE
[REQUEST] Support for advanced generators for energy module

### ISSUE THREAD

**Issue by CrazyCodeUK** [McJty/RFTools#332]
I would like to request support for advanced generators with the energy module.

https://bdew.net/generators/
https://github.com/bdew/generators/

Enjoying the mod :)

**Comment by McJty** [comment]
If those generators properly support the CoFH RF API it should work automatically. Are you really sure it isn't working? You must use the energy module on the actual block where you can also extract the RF from.

**Comment by CrazyCodeUK** [comment]
I had tested it several location of the multi-block but possibly not the output as that was hidden behind. I will test that now.

**Comment by CrazyCodeUK** [comment]
I have tested it and it is indeed "user error" :)

Thanks.
