### ISSUE TITLE
Entity edge of loaded dim. 

### ISSUE THREAD

**Issue by LordIconMC** [McJty/RFTools#333]
RFTools V: 3.30 (in infinity 1.10.0)
Dim info:
World Version 1
Terrain: Terrain_Void
Base Block: Brown Stained Clay
Base fluid: Water
Biome controller: controller_default

Player created this dim to use as a void dim to build in. over time the dim starts to get a high ms even when no one is in the dim.

I ran an opis and found there were 3000 entities witherskulls. 

These could not be found or killed using xu_killitems or purge dim, i could not find them on the ground but when i flew around the dim i could see them they would flash i have included images. 

Not sure if this is RFTools dim related or not and not sure how to trouble shot this. McJ the server is the player.me server if you wanted to see it for yourself.

http://imgur.com/a/9VV07

**Comment by McJty** [comment]
Can you give me more information about that dimension (type /rftdim info while in the dimension). Thanks

**Comment by LordIconMC** [comment]
Description string TVoid,sRed Color,sYellow Fog
Base Seed: -4760532644702665401
World Version 1
Terrain: Terrain_Void
Base Block: Brown Stained Clay
Base fluid: Water
Biome controller: controller_default
sun brightness:1.0
Start brightness:1.0
sky color: 1.0,0.2,0.2
Fog color: 1.0,1.0,0.2
time speed: 2.0

thats all the info

**Comment by LordIconMC** [comment]
I just had to restart the world because the entity count was too high. I will let you know when it returns. Because it will. 
More information the player does have a mob grinder farm of wither skeletons in the dim. So I am guessing some are falling in the void. But they never clear they get stuck like the picture shows

**Comment by LordIconMC** [comment]
Even after restart of server the entities are still there. its like they are in the fog idk

**Comment by McJty** [comment]
If the player has a wither farm there then I doubt this is an rftools issue. RFTools dimensions don't do anything special with regards to spawning/despawning of entities.

**Comment by LordIconMC** [comment]
I have turned off the farm and reloaded the server and the enties are still there

**Comment by LordIconMC** [comment]
Again it looks like it's in the fog. Like when the wither skulls fall in the void they become part of the dim I will drop more items in the dim to test

**Comment by LordIconMC** [comment]
If unrelated to rft I will happily close the ticket just not sure what else to do but rebuild the dim and try and worldedit his build in to it

**Comment by McJty** [comment]
Well I don't know but a) I have no clue how rftools could even be causing this and b) nobody ever reported anything similar to this. So no idea really...

**Comment by LordIconMC** [comment]
Ok, then i will go ahead and try and rebuild the dim and move over his build. 

Thanks

**Comment by McJty** [comment]
Sorry I couldn't be of more help here. These kinds of issues are annoying

**Comment by LordIconMC** [comment]
Understandable. but thanks for the responses.
