### ISSUE TITLE
Clearing channel

### ISSUE THREAD

**Issue by CrazyCodeUK** [McJty/RFTools#334]
I have not found a way to clear a channel from a button module or redstone receiver (presumable transmitter as well). I would be useful to have a way to reset them to channel less (placing in the crafting grid on sneak right clicking on air). Modules like energy modules can easily be set to other devices and dont have the same liking issues as these others. Also if you have a button module set to a channel and then click on a receiver it sets the receiver to the button channel rather than the other way round meaning if you link the receiver to a new transmitter it can changed to a new channel (then you cannot change the transmitter) but if you want to reuse the old button it will set it back to the button channel.

**Comment by McJty** [comment]
Why exactly would you like to have them without channel?

**Comment by CrazyCodeUK** [comment]
In the setup reduced the number of receivers I had (they where all activated by buttons). So i had a bunch of receivers that where set on channels that I could not re-use as I could not give them new channels.

If you use the transmitters to change their channels you are then stuck with transmitters you cannot change.

If you could reset to no channel they could then be re-used and create new channels.

**Comment by McJty** [comment]
Well this will not work in any case as even if you release a channel from a transmitter it cannot be reused for another transmitter. A channel is tied to a transmitter and once created it can't change. If you want to do this you will have to relink the receivers to a new channel. Clearing a channel (and then allowing it to be reused) is not possible.

**Comment by CrazyCodeUK** [comment]
Yes i dont want to reuse a channel .. i want to reuse the device.

**Comment by McJty** [comment]
Why does it  need to have a new channel for it to be reusable? It can work on the channel it already has.

**Comment by CrazyCodeUK** [comment]
![1](https://cloud.githubusercontent.com/assets/3353214/10097057/39038b70-636e-11e5-8fd3-5cf2a0b19e78.png)
In this example I have two receivers set by a button to channel 1.
I then decide I want the two lights to work on different channels.
I now need to set the second receiver and button to channel 2.

My only way to do that at the moment is to create a transmitter and link that to one of the receivers.
Then i have a transmitter that i dont locked to channel 2.

**Comment by McJty** [comment]
Transmitters are the creators of a channel. They cannot be linked to another channel. They 'own' the channel. So what you ask is really not possible. The only way to do that is to relink the receivers and button to that channel.

**Comment by CrazyCodeUK** [comment]
In my setup transmitters are never used. The channels are created by buttons/receivers. I am guessing you have a master list of created channels on the server (for mp) / client (for sp).

In this setup there is no transmitter to own the channel as none have been created.

As per the screen shot above there are only two receivers and two buttons. 0 transmitters.

In this instance what is the owner of the channel?

**Comment by McJty** [comment]
Hmm why did you create that transmitter then? You can use the button module on a receiver. That will also create a new channel.

**Comment by CrazyCodeUK** [comment]
this is just a test world. the transmitter in hotbar was just me clicking on the wrong on in nei

**Comment by instinxx** [comment]
I have the same issue.. I created receivers with button modules. I somehow ended up with three buttons on the same channel which according to your logic should not be. No way to reset them means they are wasted.

**Comment by McJty** [comment]
You can change the channel of a button. Just sneak right click the button on another receiver or transmitter to change the channel

**Comment by instinxx** [comment]
McJty, in a situation like we describe using buttons and receivers with no transmitters what actually owns the channel?

**Comment by McJty** [comment]
Technically the button

**Comment by McJty** [comment]
Will implement this for next version
