### ISSUE TITLE
Modular storage chest keeping last module inserted

### ISSUE THREAD

**Issue by RViper80** [McJty/RFTools#335]
I have put a modular storage chest down with some type of item extraction method on it (hopper, pipe), and then put a remote storage module inside to pull the items out of that module automatically.  This worked fine, however I took that module back out, and put it into a tablet.

Anything I put into that module now gets pulled out of that modular storage chest, even though it no longer has any modular storage cards of any kind inside.   Breaking and replacing the modular storage chest resets the link.

RFTools 3.35, Lib 1.4.0, Forge 1448

**Comment by McJty** [comment]
I can reproduce this. Will try to fix for 3.40

**Comment by McJty** [comment]
Fixed for 3.40
