### ISSUE TITLE
Crash when creating new chunks in Twilight Forest

### ISSUE THREAD

**Issue by artubi** [McJty/RFTools#337]
Hi,
it seems that new version of RFTools cause MC to crash whenever you are trying to generate new chunks in Twilight Forest.

Crash log: http://pastebin.com/fTPXJN8P

Tested with:
Twilight Forest 2.3.7
mcjtylib-1.5.0
RFTools 3.35
mcjtylib-1.5.1
RFTools 3.40

Upon entering Twilight Forest with mcjtylib-1.5.1 and RFTools 3.40, when game tries to generate new chunks, it crashes. This doesn't happen with mcjtylib-1.5.0 and RFTools 3.35, game will generate new chunks without any problem.

It should be noted that you can walk in existing world of Twilight Forest with mcjtylib-1.5.1 and RFTools 3.40, you just can't go near new chunk.

**Comment by McJty** [comment]
Already reported by someone else and fixed. I'm preparing a new release now
