### ISSUE TITLE
Dimlet config modban.Material not taking effect

### ISSUE THREAD

**Issue by Kataiser9** [McJty/RFTools#338]
I've tried to put a few mod bans on liquids and materiaIs in my config; the former works fine, the latter doesn't.

In knownDimlets I have the line "B:"modban.Material.ReactorCraft"=true", and when booting up the game log shows "[20:39:22] [Server thread/INFO] [mcjty.varia.Logging]: Banned dimlet type Material for mod 'ReactorCraft'". However, dimlets for ReC ores still show up in NEI, and the Material Absorber still works on 'em.

**Comment by McJty** [comment]
Is ReactorCraft the actual good name of the mod? Did you use /rftcfg dimletcfg with such a dimlet in your hand to see the actual line?

**Comment by Kataiser9** [comment]
Indeed I did. Besides, there's one mod that I have modban'd for both liquids and materials (ThermalFoundation) and the liquid ban works, while the materials ban doesn't.

Also, forgot to mention - I'm on the latest version of RFTools (3.41).

**Comment by McJty** [comment]
Hmm... I cannot find a bug in RFTools and if your line in the config really is exactly like this:  "B:"modban.Material.ReactorCraft"=true" then you have misplaced a few quotes. Can you give me your exact config file if you still have the problem?
