### ISSUE TITLE
A crash while creating a new world .

### ISSUE THREAD

**Issue by crunkazcanbe** [McJty/RFTools#34]
The crash is here http://pastebin.com/UTiGjMHb

Thanx -Crunk

**Comment by McJty** [comment]
How exactly did this happen? Is this on a server? When starting the game? Was the rftools config unmodified?

**Comment by crunkazcanbe** [comment]
It's in my mod pack and client man no server i just updated to this dev build latest and got this crash while creating a new world . Default config i didnt delete old config after updating though . I updated to forge 1301 i think it is to . So idk if thats the cause

**Comment by McJty** [comment]
And this happens everytime that you create a new world? I will try to see what's wrong.

**Comment by McJty** [comment]
BTW, if possible I'm interested in the entire client log for this crash (i.e. logs/latest.log)

**Comment by crunkazcanbe** [comment]
Hey man! When i get off work i will be happy to get you all the logs. This happens everytime i try to make a new world , but not when getting back into my old already made world.

**Comment by crunkazcanbe** [comment]
Ok this is what I see in the console while it crashes when making a new world http://pastebin.com/NUS8XKGQ . My logs are here https://copy.com/1Ae6ZsP64zRsXeJQ

**Comment by McJty** [comment]
Thanks for this detailed information. I hope I can find the problem now.

**Comment by crunkazcanbe** [comment]
Hey man scratch this report. Sorry I found the mod causing the crash , and it was the InfiniteInvo mod . I am truly sorry to have bothered you . :(

**Comment by McJty** [comment]
I was *just* going to tell you that I doubted it was rftools :-)

Well I'm happy it is not a problem with rftools then. I'll close this now. Thanks for letting me know.

**Comment by crunkazcanbe** [comment]
Your welcome man , and thank you .
