### ISSUE TITLE
Rfttp list command crashing server

### ISSUE THREAD

**Issue by LordIconMC** [McJty/RFTools#341]
I think something happens to one of the rftool dims on my server
Here is the crash log received http://pastebin.com/xFzMz0Rq

The server will no longer start

I have tried removing all rftool dims but the issue still continues. Is there a config file where the list gets stored or other options I should try before a server restore. I loaded the last restore on to a test server. 
Clicking on dialer causes the same crash

**Comment by McJty** [comment]
That's a bug in funky locomotion/thermal expansion and has nothing to do with rftools. The only way to solve this is to use mcedit to fix the offending block or else to use funky locomotion

**Comment by LordIconMC** [comment]
ok Thanks
