### ISSUE TITLE
[SUGGESTION] Config to hide Dimlets in NEI

### ISSUE THREAD

**Issue by Neodark7** [McJty/RFTools#345]
Can you add that too ? :3

**Comment by McJty** [comment]
No longer relevant in 1.10.2

**Comment by Neodark7** [comment]
easy to say that one year later ! :D

**Comment by McJty** [comment]
Well I was a bit sloppy with my issues and I'm trying to clean them up now :-)

**Comment by Neodark7** [comment]
yeah i imagine x) it was a joke don't worry, good luck for all the issues left :D
