### ISSUE TITLE
Jungle Biomes don't generate Matter receiver

### ISSUE THREAD

**Issue by kutschkem** [McJty/RFTools#346]
I created two Jungle dimensions, both of which seem to not generate a starting platform I can teleport to. I can't judge if I am just unlucky or this is a general issue with Jungles. I would expect that at the very least, if the platform can't fit on the ground, I get one in the treetops.

**Comment by McJty** [comment]
This can be an issue of a jungle tree overwriting the platform. Easy to fix however. Just send over a fully charged new matter receiver to that dimension using the Dimension Editor. Then you can dial to it
