### ISSUE TITLE
Server hangs and crashes when loading dimension

### ISSUE THREAD

**Issue by timfennis** [McJty/RFTools#349]
Preface: I am completely new to RF Tools dimension system so please excuse me if I mix up some of the terminology.

Basically I wanted to get started creating new dimensions so I put an Empty Dimension Tab into a Dimension Inscriber without adding any dimlets and put the resulting Realized Dimension Tab in to a Dimension builder. It built properly until 99% when it stopped and I pulled it out (thinking I had to put it in another machine to go there). It seems that at this point the server "crashed" because after about 10 seconds of randomly clicking things I got timed out. I do not have any logs of this happening.

I restarted my server and got back in to the game with a realized dimension tab that had a red tooltip saying somthing like "Dimension information not available". When I put it in the dimension builder it did go to 100% and it started charging my world to about 25 million RF at which point I got curious why my dimension would contain so much RF so I started googling. At this point I was also unable to dial my dimension and I stumbled upon an FAQ entry that suggested I should use 'Teleporter Probe' to access my dimension because the receiver could have been invalidated by a meteor. https://github.com/McJty/RFTools/wiki/RFTools-FAQ

I spawned the Teleporter Probe using OP and teleported myself to dimension 3 (which I'm quite sure is the dimension that I've just created). And my server crashed again (it actually hangs since I have to manually kill the process). The following pastebin shows me giving myself the probe and crashing the server http://pastebin.com/bYpTv9YA

It seems the probe did move me to the new dimension because now the server instantly crashes when I try to log in. The next  pastebin contains part of the console output I've captured during the crash http://pastebin.com/05Vd7BPh

Unfortunately my crash report directory is empty. I could provide you with a copy of my world if this issue is serious. Eitherway please let me know if I can provide anymore useful information.

UPDATE: I did found some crash reports in .json format. This is an example of one http://pastebin.com/tLLADxFz

UPDATE: Like I said in my comment, I fixed my world. I've now also generated a new dimension (plain with a different digit) and everything seems to work fine.

**Comment by timfennis** [comment]
As an aside question is there any way to get my character back to the overworld because currently I cannot play the game anymore. I've tried moving my character in MCedit but I'm not sure I'm doing it correctly :cry: 

This is part of the log in my client after I attempt to connect to my server.
http://pastebin.com/H1PdJFpq

I get timed out after a few seconds of 'Downloading terrain...'

**Comment by McJty** [comment]
Seems the original crash was caused by bluepower. Not sure exactly why though.

**Comment by timfennis** [comment]
I presume it's related to the worldgen bluepower adds then. While I was moving my character out of the corrupt dimension I attempted to have a peek at what's inside but it seems non of the chunks were able to be saved. 

I can consistently reproduce the issue in the backup I have with the dimlet that created the corrupted dimension. Outside of that like I mentioned other new dimensions seem to be fine. I could upload the backup of my server/world if you think it would help you track down the issue but I guess it's better to report the problem over at bluepower?

**Comment by McJty** [comment]
I would start by reporting to bluepower. Let's see how it goes from there

**Comment by Quetzi** [comment]
Not sure why `[06/10/2015 23:37:34 PM] [Client thread/INFO] [mcjty.varia.Logging]: Dimension information for dimension 3 is missing!` would be anything to do with BluePower. It seems clear that there was a crash partway through dimension creation. The appearance of Bluepower in a stacktrace is purely the result of normal world generation. I also note that so far there hasn't been a full log posted, this would be insanely useful, if only to rule out Cauldron as a factor.

**Comment by McJty** [comment]
Well the dimension information is missing because something went wrong during chunk generation (that was when the bluepower related crash occured) which causes rftools to fail proper creation of the dimension. I should note that bluepower and rftools have worked together in various modpacks already so I'm not sure why this would come up now. A full log would indeed be useful.

**Comment by timfennis** [comment]
Copy of what I posted on the other issue. It seems only one of the logs mentions bluepower in the stacktrace. 

> Alright I've opened up my log directory and the relevant data seems to be in 3 different files:

> `fml-server2.log` 49,877KB
`fml-server3.log`  2,744KB
`fml-server-latest.log` 2,743KB

> The 2nd file seems to contain the first crash with no information related to bluepower. The 3rd file contains another crash also without information related to bluepower and the `fml-server-latest.log` file contains the stacktrace with bluepower in it.

> Becase all of these files exceed the maximum filesize allowed on pastebin I've compressed my whole log directory and uploaded it here http://www.timfennis.com/logs.7z and here http://www.timfennis.com/logs.zip
