### ISSUE TITLE
Syringe Enhancement Minetweaker Compatability

### ISSUE THREAD

**Issue by mrdeadlocked** [McJty/RFTools#350]
Could we get the syringe's reworked so that they can be used inside of minetweaker recipes. RIght now all of the different mob types show as one item. I'd like to be able to use them in custom recipes but the results show below. Thanks.

http://imgur.com/s3l41Fu

**Comment by McJty** [comment]
That's extremely hard to do since the syringes are based on the mob dimlets which are created very late in the setup process because it has to know what mobs are available and what not. You'll most likely have the same issue with the dimlets. I have no idea how to solve this problem.

**Comment by mrdeadlocked** [comment]
This was my fault. I missed something in the .zs. Syringe's work fine with minetweaker.

http://pastebin.com/b10sDh4w 

http://i.imgur.com/tHKUV3p.png
