### ISSUE TITLE
Require CoFHLib instead of CoFHCore

### ISSUE THREAD

**Issue by Rukachan** [McJty/RFTools#351]
Right now RFTools uses CoFHCore, a mod under a non-free license while all the functionality that RFTools uses exists in CoFHLib, a mod under a free license.
While trying to figure out if it is possible to make RFTools use CoFHLib instead I created this repository https://github.com/Rukachan/RFTools-free and I noticed that:
1: RFTools does not make use of CoFHCore-specific functionality that does not exist in CoFHLib.
2: By simply requiring CoFHLib, it will be able to use CoFHCore if found instead without the need to copy additional jar files.
3: Only about 5 lines will have to be changed.

This will be not only helpful for people like me who try to avoid non-free mods as much as possible, but it will also free RFTools from depending on a non-free mod.

**Comment by McJty** [comment]
Fixed in next release. Thanks for taking the time to go over this.
