### ISSUE TITLE
Add config option to disable or hide security ("Owned by")

### ISSUE THREAD

**Issue by Ricket** [McJty/RFTools#352]
I would like the ability to disable an item being "owned by" someone in the config file, or hide it from showing in tooltips and waila (which would effectively be the same thing). Our server is myself and a couple friends, and we share everything, there's no concept or need for ownership.

**Comment by McJty** [comment]
Sounds reasonable. I will implement it

**Comment by McJty** [comment]
Will be implemented in next version of RFTools.

**Comment by Ricket** [comment]
Thanks! :)

**Comment by Ricket** [comment]
What is the config option name for this? Sorry, I don't see it in my config files (4.23 and 1.10-5.02).

**Comment by McJty** [comment]
Security is implemented in McJtyLib so look in mcjtylib.cfg
