### ISSUE TITLE
Bug or/and corruption !?

### ISSUE THREAD

**Issue by Maxoumi** [McJty/RFTools#356]
Firstly sorry for my English. I am french ^^

Here I have a big problem with rftool! I create a world rftool but after some minutes the world that "coromp". The sun is at its highest but it does not update. The energy circulates more. There is little scoop up objects from the ground and thrown object falls infinitely. It's strange because before his minutes everything goes well in the world: o

Thank you in advance for your assistance ! =)

**Comment by McJty** [comment]
I need more information. Does the dimension have power? Can you show some screenshots?

**Comment by Maxoumi** [comment]
Dimension have all normal/default dimlet. The most strange thing is that some second before the bug world. There are slowness of effect and other negative effects.

Little vidéo MP4 : https://www.dropbox.com/s/skyhxl3jjh94g1d/2015-10-16_093352572.mp4?dl=1

In the logs there with not much to this point it's just strange = /

**Comment by McJty** [comment]
It is because your dimension is out of power. When a dimension runs out of power nothing works in it. It goes dark and entities stop working. That's why your machines aren't getting power. So this is normal. Just make sure your dimension has power.

**Comment by Maxoumi** [comment]
Oh fuck x) Thank you very much I'm just a fool I did not know he had to continually allimenté! Sorry for the inconvenience ^^ '

Thank you =)
