### ISSUE TITLE
Builder/Space Chamber Issues

### ISSUE THREAD

**Issue by TheDieselPunk** [McJty/RFTools#357]
I was doing some testing on a server with a friend of mine. We found that:
* You can move bedrock with the builder. I don't know if this was intended.
* You can move the End Crystals that heal the Ender Dragon. Not really an issue I suppose but I don't know if it's intended.
* You CANNOT move the End Portal inside of The End. If you try, it will crash the server. It moves the bedrock blocks but I believe in it's attempt to move the portal blocks it causes the crash.

**Comment by McJty** [comment]
I need to protect this. Thanks for reminding me :-)

**Comment by McJty** [comment]
Fixed in next release
