### ISSUE TITLE
dungeon chests are full of dimlets

### ISSUE THREAD

**Issue by skydark** [McJty/RFTools#359]
After I create and reload worlds many times without closing the game, all new generated dungeon chests are full of unknown dimlets. Then I execute `/minetweaker loot` and check minetweaker.log, this line occurs many times:

    <rftools:unknownDimlet> (weight 50, 1-3)

The problem seems that rftools always try to add loots while a new world is loading. (`setupChestLoot` in `items/dimlets/KnownDimletConfiguration.java`).

**Comment by McJty** [comment]
Hmm indeed. I will fix this

**Comment by McJty** [comment]
Fixed in next release
