### ISSUE TITLE
[issue] cannot delete invalid destinations from dialer list 

### ISSUE THREAD

**Issue by mikeloeven** [McJty/RFTools#362]
A receiver was deleted during a scheduled reset of the servers mining dimension. currently i am unable to delete invalid destinations from the dialer and as this has happened multiple times there are several identical but invalid destinations listed in the dialer. there needs to be a method of deleting missing destinations from the dialer list 

perhaps this should be accomplished by analyzer providing a dialogue to remove the destination if it cannot find the reciever

**Comment by McJty** [comment]
RFTools dimensions should preferably be deleted with /rftdim safedel and after that removing the dimension folder. Otherwise RFTools can get confused. But you can use /rfttp cleanup to clean up all invalid matter receivers from the dialer list to fix this issue now.

**Comment by mikeloeven** [comment]
the dimensions where this occurs are the nether and the deep dark these are not dimensions managed by RF tools. but again the ability to delete invalid destinations is something that needs to be added

**Comment by McJty** [comment]
It exists like I told you in previous comment: /rfttp cleanup

**Comment by mikeloeven** [comment]
/rfttp is a admin command there needs to be a public command to perform this function per dialer

**Comment by McJty** [comment]
Well for un oped players the way to do is is to manually remove the receiver. There is no need for a command to do this.

**Comment by mikeloeven** [comment]
unless the receiver has been destroyed ... XD

**Comment by McJty** [comment]
Well if the receiver is destroyed in game (by breaking or explosion) it should normally be removed from the list. If the receiver is destroyed out of game by removing a dimension (dimension reset or something) then it is up to the person who does that (presumably an admin) to run the needed cleanup commands.

**Comment by mikeloeven** [comment]
why not solve the issue completely by running cleanup each time the server restarts ?

**Comment by McJty** [comment]
Well the cleanup command has to load all dimensions that have (or had) a receiver in them so that could add a bit to startup time. Also if a dimension was corrupt but only triggered a crash on visiting/loading it then it would now crash all the time.

**Comment by mikeloeven** [comment]
so coming full circle it should be fairly simply to add a dialogue when checking with a destination anylizer to delete invalid destinations after the check button has been pressed

**Comment by McJty** [comment]
In theory yes but I still feel this is not the responsibility of the player. It is the admin that should worry about this

**Comment by Divineaspect** [comment]
As a frequent Admin, I have a LOT of stupid players who can't be bothered
to tell me when they're doing things like crash the server, let alone
spamming bad dimensions.
This feature would be really nice.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by mikeloeven** [comment]
But its the player who ultimately has to deal with many bad destinations on their dialing device

**Comment by McJty** [comment]
Fixed in next release. Doing 'check' on an invalid destination will clean up all invalid destinations (not only the one that you were checking)
