### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by zed-hex** [McJty/RFTools#363]
It is possible to duplicate items with any block from this mod that has an inventory. This bug happens when a play pulls an item out of any inventory after it has been broken this is since the inventory does not force close. 
Version of the mod 3.50 
(If you need to replicate it just get a player to break any block when you are in the inventory of the block, after it is broken pull an item out of the invrntory and it will be duplicated)

**Comment by McJty** [comment]
Will be fixed next version
