### ISSUE TITLE
Crash on loading a world

### ISSUE THREAD

**Issue by DestinyPlayer** [McJty/RFTools#366]
I... Am not really sure what the hell happened. I just updated RFTools and Deep Resonance with everything that's needed for them, and now I can't load the world I play in, the game simply crashes.

Crash-log:
http://pastebin.com/XSADTXSu

Modlist:
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-10-29%2016.17.17.png

**Comment by McJty** [comment]
Could you provide the entire log? Maybe there is more information there

**Comment by DestinyPlayer** [comment]
Here it is.
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/World-crash.log

**Comment by McJty** [comment]
I see several problems in that log not related to RFTools. Like for example:

[16:14:46] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@1ffc1886:
java.lang.NullPointerException
	at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:804) ~[EnergyValueRegistry.class:?]
	at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:27) ~[EnergyValueRegistry.class:?]


Not sure what is going on though. I see nothing in that log indicating anything from RFTools or Deep Resonance though.

**Comment by DestinyPlayer** [comment]
Well, the only reason I posted it to here is because I updated RFTools and Deep Resonance, and only after that it started happening. Could it be because of a wrong Forge version or something?

**Comment by McJty** [comment]
I don't see why. I develop with a very old version of Forge and in my own On The Edge modpack I have a very recent version and I don't have this problem... No idea really

**Comment by DestinyPlayer** [comment]
Welp, updated Forge, nothing, but it said that there was some conflict with MineChem. Removed MineChem - still crashing. I guess the game doesn't want me to use the newest RFTools and Deep Resonance toys.

**Comment by McJty** [comment]
It is most likely some conflict with a mod or so but it will be hard finding out what mod

**Comment by XFactHD** [comment]
@McJty The stacktrace you found is a known bug in EE3s dynEMC system and can temporarily be fixed by switching from pre calculated to post calculated values (don't ask me how).

**Comment by McJty** [comment]
Why does this only trigger when RFTools/DR is updated then? That's strange

**Comment by DestinyPlayer** [comment]
Welp, it seems like there's something wrong with the world, not with any of the mods. Created a new world - it works. Tried to load the old world again - CRASH. Still don't know what mod's the culprit. Tried to remove ChromatiCraft, but it's useless because I'm literally living in a biome that it adds, and so the world gets corrupted.

**Comment by XFactHD** [comment]
My guess is that some item IDs might have changed.

**Comment by XFactHD** [comment]
@DestinyPlayer item IDs are different between worlds. Try out what I wrote before, if you can figure out how to do it.

**Comment by DestinyPlayer** [comment]
Nope, can neither figure out how to switch EE3 nor downgrade. The world's bust, completely and totally, downgrade fixes nothing.

**Comment by NoX-programer** [comment]
@DestinyPlayer, if world is corrupted - that's sad, but for the future: don't forget to backup world often, especially before mod adding/update (better also with config folder).

**Comment by DestinyPlayer** [comment]
Yeah. But it still turned out for the great, because it gave me a reason to build something pretty with stuff that I had in the old world while rebuilding in the new one, and not remain in the organically grown mess that I was.

**Comment by DestinyPlayer** [comment]
I've managed to bring the world back (kinda) by removing everything about EE3 from it. Only kinda, because something still glitched out and it was lagging way more than it used to.
