### ISSUE TITLE
Super awesome quarry devours machines

### ISSUE THREAD

**Issue by Shykel** [McJty/RFTools#367]
I've started to compare the quarry from rftools to other mods. It's by far the best (other than the digital miner which is expensive) but I've noticed that if it quarries away a machine from other mods (like mekanism) the machine is gone from existence and isn't even stored. It's quite a big issue for noobs like me who pile RF generating machines around a quarry then get super confused when half of them are gone. thanks!

**Comment by McJty** [comment]
I will fix this

**Comment by McJty** [comment]
Fixed for next release. The builder will leave tile entities alone
