### ISSUE TITLE
weather dimlets issue

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#368]
Dimlet Workbench -> Open manual - still haven't information about how to craft a wheather dimlets, and weather type controller component still hasn't proper localized name (it is: item.DimletTypeControllerWeather.name).

Version: RFTools-4.01.

**Comment by McJty** [comment]
Weather dimlets cannot yet be crafted. Need to make the necessary essence items for that. I'll fix the localized name

**Comment by McJty** [comment]
Fixed next release
