### ISSUE TITLE
Efficiency Essence crafting problem

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#369]
That essens is crafting only when I have pickaxe with exactly 3 level of efficiency, but it is often even freshly enchanted pickaxe have not only efficiency, but also some other enchantments, for example: Efficiency III, Unbreaking III. I can have a pickaxe even with Efficiency IV or V and it will be really flexible if Essence will craft in such cases.

Version: RFTools-4.01.

**Comment by McJty** [comment]
Well this is on purpose. It is possible to get exactly the right enchantment on a pickaxe by first enchanting books and using an anvil (vanilla mechanic). Or you can use enderio which has a machine to add specific enchants.
