### ISSUE TITLE
Fail to complete the time absorber

### ISSUE THREAD

**Issue by NoX-programer** [McJty/RFTools#374]
For example, I targeting "Time noon", so I wait for the sun at its zenith, then I make a red-signal with lever and... nothing happens. I already tried to do this a little time before and after - and nothing! And I've looked at code and noticed there is timeout after red-signal. And still, can't get progression with that absorber. So, I suggest a notice to Waila description ("Now: noon (or whatever)") and, maybe effect or color pointing the right time.
Difficulty insane: I want evening! So where sun mus be at evening? :-D
Maybe even go further? Maybe better to allow to click button once, and time will be recorded "as is"? If you are not want to change current mechanics, maybe to realize such behavior with config option, say, EZmode...

Version: RFTools-4.01.

**Comment by McJty** [comment]
Was this with a fresh time absorber? When it is already set to a certain time you cannot change it anymore.

**Comment by NoX-programer** [comment]
It wasn't fresh, it was started when version was 3.33, then, after version upgrage, I cannot make a progress even a bit. Ok, I will test fresh. Btw, what time absorber get? Time of local dim where it is or time of overworld?

**Comment by McJty** [comment]
It gets the local time. If you use it on an eternal day dimension you will get a noon time absorber

**Comment by NoX-programer** [comment]
Nope, didn't work at all. Freshly crafted time absorber is not even starting charging in overworld when sun is at zenith, nor in that dim where sun always there. Did something broken in 4.01?

**Comment by McJty** [comment]
And you gave it a redstone signal? How exactly did you do that? The block is pretty pick of where the redstone goes in. A lever on it should work

**Comment by NoX-programer** [comment]
Redsignal is given, ofcourse, by 2 ways: lever at the ground near, and lever on adjacent block - still none.

**Comment by McJty** [comment]
Try it like this (also remember that the redstone signal should be on and then off, it cannot stay on. That doesn't work): http://i.imgur.com/Nvwfx2A.png

**Comment by NoX-programer** [comment]
Yep, it's worked! Seems that in addition to the existing difficulties the redstone must be given in exact conditions... Great thanks for resolving this, and, what about suggested ways to indicate proper time?

**Comment by McJty** [comment]
Hmm, for me the waila tooltip already shows the time. Doesn't it for you?

**Comment by NoX-programer** [comment]
It's displaying info about absorber which already have fill progression, but I mean absorber which haven't. How to guess when I need to emit signal for not such obvious cases like midnight/noon, but for morning/evening?

**Comment by McJty** [comment]
Ok, I'll add a more appropriate waila tooltip

**Comment by NoX-programer** [comment]
Thanks a lot!
