### ISSUE TITLE
BigReactors Liquid Yellorium, Cyanite and Blutonium should be unobtainable

### ISSUE THREAD

**Issue by XFactHD** [McJty/RFTools#378]
As the title sais those three liquids should be unobtainable. They are not intended to be used by the player, they are only for internal use in BigReactors. They are causing bugs in other mods because they are not fully implemented as it is not needed.

**Comment by McJty** [comment]
Actually that's not entirely true. You can melt the liquids (I believe you might need some addon for it) to ingots using Tinkers Construct. I've seen people do exactly that

**Comment by XFactHD** [comment]
ExtraTiC does that but shouldn't. It is one mod I know of that can cause crashes with those fluids.

**Comment by Dijkstra1** [comment]
If you are using ExtraTiC does that not add motel Yellorium, and not use the actual liquid Yellorium, just as a point of interest

**Comment by XFactHD** [comment]
It uses the original fluid.

**Comment by XFactHD** [comment]
Take a look at this issue, the developer himself explained it #erogenousbeef/BigReactors/475
