### ISSUE TITLE
Crash on loading into a dimension

### ISSUE THREAD

**Issue by fox945** [McJty/RFTools#379]
I was using FTB Infinity Evolved 2.0.2 and just out of the blue one day I started crashing every time I try and load into a dimension.  Other players on the server can load in the same dimension w/out a problem.  I updated to 2.1.2 last night and still experience the same problem.  Here is a copy of my crash log. http://pastebin.com/nYVb6bNH

Please let me know if you need anything else from me to assist with narrowing down what is causing the crashes.

**Comment by McJty** [comment]
That's weird... If other players can go to that dimension without problems then I don't see how this could be rftools related. On the other hand I have no clue what else could be wrong. Can you perhaps give me the full log?
