### ISSUE TITLE
[Question] Why do you use Fortune II instead of Fortune III with quarry?

### ISSUE THREAD

**Issue by OneEyeMaker** [McJty/RFTools#381]
The title says it all. Why does quarry mine blocks with Fotune II instead of Forune III (with any Fortune card)? AFAIK, maximum level of Fortune enchantment is third level.
I noticed that, when builder with fortune card became mine gravel instead of flint (=> level of Fortune enchantment isn't maximal).

Code: https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/blocks/spaceprojector/BuilderTileEntity.java#L924

Please, explain me - is that made especially or is it mistake (typo)?

P. S. Sorry for my English, I'm from Russia.

**Comment by McJty** [comment]
Fixed in next release
