### ISSUE TITLE
Existing or new void worlds not loading

### ISSUE THREAD

**Issue by jermangarc** [McJty/RFTools#382]
I have been having this problem for a couple of months now without any resolution yet. All other RFTools worlds load just fine. Only when we try to go in to any existing or newly created void worlds does it freeze up the server upon entry, console will stop responding as well, so a crash report is non-existent, I have to do a cold restart. It wasn't doing this before, I have a player who built a whole StarTrek starship with all kinds of machines in it, really cool build but he cannot get back in anymore. We also have MystCraft installed and the issue also happens there as well. I am working on getting a startup log but would like to poke your brain a little as to what might be causing this issue, or what to look for. Thanks for your help.

**Comment by McJty** [comment]
A full log would be useful. Do you have cauldron or similar software? This has been known to cause issues.

**Comment by jermangarc** [comment]
No, no Cauldron YET! lol. I found that MystCraft is not the culprit. Now I just need to figure out which of the other 322 mods could be causing it. Xcomp thinks another mod is causing it, which I agree. So I'm going to close this and comment in my findings later. Thanks for your help.
