### ISSUE TITLE
Automatically close client while entering world for first time

### ISSUE THREAD

**Issue by mikekleckner** [McJty/RFTools#383]
Hello thanks a bunch for taking the time to look at this,

The first dimension I opened and went to worked perfectly but didn't have all the modifiers that I wanted so I quickly added the new dimlets and upon entering the portal the game force closed on its own and now wont load into the world anymore. This is the log from ftb please let me know if there is anything else I can give you to help out this problem.

http://paste.feed-the-beast.com/view/28853e1a

Thanks

**Comment by McJty** [comment]
Not sure what is wrong but it is the wireless redstone mod that is crashing. Maybe you could try disabling that? Also strangely enough Mystcraft is also in the crashlog.

**Comment by mikekleckner** [comment]
Hey man I just wanted to say thank you for the amazingly fast reply I disabled WR and it loaded world however i was underground at original spawn point which was strange. Anyways thank you again you are awesome
