### ISSUE TITLE
Crash upon logging into a server

### ISSUE THREAD

**Issue by bvcderrttyyhjjjk** [McJty/RFTools#385]
Here's what's happening: I have a server, and the other day I logged out while inside a dimension. Now every time I try log in my client crashes and my server gives me a NetworkDispatcher Exception.

I have read about people having similar problems with other dimension mods saying it could be dimensions trying to send too big packets/overflowing packets.

Since the server itself is fine I don't have an actual crash log; my friend who last logged out form the main world is able to log in no problem.

For reference, the dimension was build by putting Fuel Cavern dimlets in it.

I need help because I am at risk of having to throw away a world with hundreds of hours into it, for both me and my friend...

**Comment by McJty** [comment]
You should have a crash log from your client side. Your client also keeps crash logs. Without a log there is literally nothing that I can do

**Comment by bvcderrttyyhjjjk** [comment]
[crash-2015-11-16_18.42.55-client.txt](https://github.com/McJty/RFTools/files/35807/crash-2015-11-16_18.42.55-client.txt)

Found it. Hope it helps... Thanks for checking it.

**Comment by McJty** [comment]
Hmm you're still using RFTools 3.30. That's pretty old and also I cannot fix bugs in that version anymore.

Not sure what is wrong though. There are tools to edit your player so you end up back in the overworld. Not sure exactly how that works but I recommend you do that.

I don't know how much is in that dimension but you could also try deleting the dimension folder for that dimension and let it regenerate again.

In any case, make a backup first before you start doing any experimentation.

**Comment by bvcderrttyyhjjjk** [comment]
I tried switching to the latest version of RFTools and the framework mod earlier today, but nothing changed so I reverted it, trying to isolate the problematic factor. 

This morning I was able to log in again after deleting a different dimension folder for some reason, and thought it was ok. Logged back out, next time i try log in the problem is back. I did try deleting all the dimensions individually with no apparent change.

If this information is no use, could you direct  me to player editing stuff?

Thanks.

**Comment by McJty** [comment]
Perhaps with NBT Explorer: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

Or maybe this works better: http://www.akliz.net/manage/knowledgebase/48/How-to-Reset-a-Playerandsharp039s-Location-and-Inventory-on-a-Minecraft-Server.html
