### ISSUE TITLE
[Suggestion] 'Do not flood' button on Crafter

### ISSUE THREAD

**Issue by cgmtaus** [McJty/RFTools#387]
Pretty much what title says. Whenever I configure the crafter to make some elaborated crafting (i.e. advanced solar panels), the first crafting I set floods the whole inventory of the crafter. It would be awesome if you could put an option that makes no craftable item set as 'In' to use more than one slot of the machine. Thanks!

**Comment by boatrite** [comment]
You can solve this by putting a dummy block in any extra slots and using Keep mode on all recipes. This ensures there will only be as many items as there are spaces with that item.

![crafter](https://cloud.githubusercontent.com/assets/5781611/11444982/1937d056-94ee-11e5-8935-5f20298f863f.png)

**Comment by cgmtaus** [comment]
Yeah that's what I do, but it still bothers me that I have to craft 1 extra of everything in order to keep the slot reserved for that item. And it just looks ugly to me :(

**Comment by McJty** [comment]
I have a solution ready for next version
