### ISSUE TITLE
Shield Texture Cloak causes crash and unloadable world

### ISSUE THREAD

**Issue by Aedda** [McJty/RFTools#39]
I decided to see what would happen if I put an item into the cloak block slot and hit set. The game immediately terminated and was unable to load the world again.

To reproduce place a ladder, torch, lever,etc. into the Cloak Block slot of the Shield Generator and hit Set. Also crashes on some blocks, tested TE Energy Cells.

[Crash log](https://gist.github.com/Aedda/3928b7b5ac3acb764af6)

**Comment by McJty** [comment]
Should be fixed in 2.42
