### ISSUE TITLE
[Bug] Clearing Fortune quarry doesn't use Fortune at all.

### ISSUE THREAD

**Issue by OneEyeMaker** [McJty/RFTools#391]
The title says it all.
Builder with Clearing Fortune Quarry card mines block without fortune at all.
You can check it simply:
 - Builder with ('Dirty') Fortune Quarry card mines flint from gravel.
 - Builder with Clearing Fortune Quarry card mines gravel.

You should add only one 'or' statement here:
https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/blocks/spaceprojector/BuilderTileEntity.java#L1009

**Comment by OneEyeMaker** [comment]
Change string from:
```List<ItemStack> drops = block.getDrops(worldObj, sx, sy, sz, meta, getCardType() == ShapeCardItem.CARD_QUARRY_FORTUNE ? 3 : 0);```
to
```List<ItemStack> drops = block.getDrops(worldObj, sx, sy, sz, meta, (getCardType() == ShapeCardItem.CARD_QUARRY_FORTUNE || getCardType() == ShapeCardItem.CARD_QUARRY_CLEAR_FORTUNE) ? 3 : 0);```

Or should I create pull request for that?)

**Comment by McJty** [comment]
No this is fine. I can manage with this. Thanks

**Comment by McJty** [comment]
Fixed in next release
