### ISSUE TITLE
Server crashs when I logging into!

### ISSUE THREAD

**Issue by nexushp** [McJty/RFTools#392]
I don't know what is happening, I've downloaded the v4.12 and your lib. Help!
[crash-2015-11-23_01.28.26-server.txt](https://github.com/McJty/RFTools/files/41239/crash-2015-11-23_01.28.26-server.txt)

**Comment by McJty** [comment]
Why do you think this is related to RFTools? The crash happens in the 'spacore' mod.

**Comment by nexushp** [comment]
Thanks man! but before I install RFTools, worked perfectly.

**Comment by McJty** [comment]
Well not sure what to say about that. The crash is obviously in spacore. I don't know how rftools could influence that and there is no code from rftools involved in the crash you mentioned above. So I'm afraid I cannot really help. I recommend talking to the people from spacore. Perhaps they know what could cause this incompatibility.

**Comment by nexushp** [comment]
I think spacore is outdated... But anyway thanks for help, and congratz for this awesome mod! =)
