### ISSUE TITLE
feature request: ability to toggle off rftools village house

### ISSUE THREAD

**Issue by Divineaspect** [McJty/RFTools#393]
This may sound minor, but I've done a bit of recipe tweaking on the presumption that dimensional shards would be unavailible in the overworld, and would really appreciate the option to have that stay true.

**Comment by McJty** [comment]
Dimensional shards are not available in the overworld. You cannot create dimensional shards from the blocks you get in the village house.

**Comment by jcettison** [comment]
You can using a Twilight Forest uncrafting table.
