### ISSUE TITLE
[Question] Is there a way to have a dim load on server startup?

### ISSUE THREAD

**Issue by Alaberti** [McJty/RFTools#395]
I have a dimension that runs a tree farm, and it is chunk loaded, but it doesn't load with the server start so it doesn't do anything until someone enters it. Is there a way to have it load on server startup? Thanks!

**Comment by McJty** [comment]
It depends on the chunk loader. I believe Chicken Chunks works fine but some others don't. Also it can depend on how the chunkloader is configured.

**Comment by XFactHD** [comment]
ChickenChunks chunkloaders are only working because they don't use the ticket system from forge.
This behaviour comes from vanilla Minecraft and also happens if you log out in an RFTools dim: The overworld will be unloaded when logging in.

**Comment by Alaberti** [comment]
Would it be possible to have an admin command to add a specified dim to be loaded during server startup?
