### ISSUE TITLE
Builder/Quarry doesn't work on Gregtech ores

### ISSUE THREAD

**Issue by permdaddy** [McJty/RFTools#396]
Probably because this:

> GregTech ore blocks do not work exactly like other ore blocks. Most mods treat their ores as single 
> blocks, with nothing special to them except for the few that must be silktouched or can be fortune 
> mined. All GregTech are non-ticking MetaTileEntities, defined not by block ID or metadata but by 
> TileEntity data. Each of these TEs contains only two variables: the internal ID of the ore, and a
> True/False boolean denoting whether the ore block was placed by world generation or by other
> means. This is mainly used to determine whether or not a Small Ore's drops can be enhanced by a 
> Fortune pick. Their being TEs though has some unfortunate consequences: not all mods are 
> prepared to deal with TE ore blocks, and so GregTech ores are not always mined by other mods' 
> automated mining systems. 

from http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing

**Comment by imbrucy** [comment]
Also does the same with Draconium ore.

**Comment by McJty** [comment]
Next version of rftools will allow you to enable the ability to mine tile entities. It is still disabled by default due to the possible risks
