### ISSUE TITLE
Over sized packet

### ISSUE THREAD

**Issue by BigD999** [McJty/RFTools#401]
I was building a T4 shield and when I turned it on with  6k+ blocks, I was kick with
Internal Exception: io.netty.handler.codec.DecoderException: java.IOException: Packet was larger than I expected,found 41939 bytes extra whilst reading packet 53

**Comment by McJty** [comment]
Was this on a server?

**Comment by BigD999** [comment]
Yes it was.

**Comment by McJty** [comment]
This will probably be fixed in next version
