### ISSUE TITLE
[Enhancement] Ability to disable certain dimlets?

### ISSUE THREAD

**Issue by iKaneki-Ken** [McJty/RFTools#402]
Hello, firstly I want to say that I love the amount of customization you add to the config already, one thing I would like to see is the ability to outright disable certain dimlets, I've tried this by simply setting the rarity ridiculously high, but in the end, some players are still able to obtain them. So would this be a possible feature addition?

**Comment by McJty** [comment]
This is already possible. To see how, just hold the dimlet in your hand (in game) and type /rftcfg dimletcfg
That will show you various config options you can set for the dimlet. One of them is a way to blacklist dimlets. Let me know if you need more help on this.
