### ISSUE TITLE
Teleporter effect glitch with textures

### ISSUE THREAD

**Issue by Keridos** [McJty/RFTools#403]
Can you change the rendering for the effect of the matter transporter to be a little bit less than exactly one block in diameter? For me the texture have weird glitches when another block is placed next to it.
At least happens when using optifine, but I disabled the setting that usually causes z layer conflicts. Using RFTools v4.13

**Comment by wlhlm** [comment]
Can you verify this by not using Optifine at all?

While you may have disabled a specific setting, there may be some other method (from Optifine) that can cause your issue.

**Comment by McJty** [comment]
Can you show me a screenshot? I'm using optifine myself and did not notice any problems.

**Comment by Keridos** [comment]
Ok this is super weird, it seems to have fixed itself. It looked ugly when I placed the teleporter but apparently after a relogin on the server / client restart it looks fine now.

**Comment by Keridos** [comment]
Ok, got this now, this is really weird:
![2015-12-09_01 30 19](https://cloud.githubusercontent.com/assets/2742845/11672896/9865caf2-9e14-11e5-9510-7b29d8616f59.png)

**Comment by McJty** [comment]
Fixed in next release
