### ISSUE TITLE
CRITICAL: ServerCrash when trying to use rf builder with JABBA barrel

### ISSUE THREAD

**Issue by Keridos** [McJty/RFTools#404]
Happened with RFTools v4.13: https://paste.ee/p/TcgVu

This crashes the server on startup.

Barrel was placed on top of the builder. To the side there was an interdimensional transceiver from EnderIO supplying power.

**Comment by McJty** [comment]
I cannot reproduce this crash. Works perfectly fine for me with a Jabba barrel on top of the builder. Can you still reproduce this problem? What version of jabba?

**Comment by imbrucy** [comment]
I've had a similar crash when placing a tesseract directly on top of the builder. I'm running a server with Infinity Evolved 2.1.3.

**Comment by McJty** [comment]
Do you have a crashlog for that?

**Comment by imbrucy** [comment]
[crash-2016-01-04_18.47.10-server.txt](https://github.com/McJty/RFTools/files/81336/crash-2016-01-04_18.47.10-server.txt)

I have the minecraft crash report but my forge log file is gone. I can cause the crash again if you need that log file.

**Comment by McJty** [comment]
This should be fixed in 4.21

**Comment by Grygon** [comment]
Just experienced this in 4.23. [Crashlog here](http://pastebin.com/YbGnte4S)
