### ISSUE TITLE
Update Wiki Regarding 'Nuking' dimensions

### ISSUE THREAD

**Issue by JayWood** [McJty/RFTools#410]
According to the [code](https://github.com/McJty/RFTools/blob/af45d962d730758f6359ace8d66851d52edd31c6/src/main/java/mcjty/rftools/blocks/dimlets/DimensionEditorTileEntity.java#L211) there are multiple checks in place, two of which are config-based.

The ['Nuking' Dimensions](https://github.com/McJty/RFTools/wiki/RFTools-Servers#nuking-dimensions) section of the wiki only states that you must enable the `editorCanDeleteDimensions` setting, not that you must ALSO enable the `playerCanDeleteDimensions` setting as well.

I might add that it is indeed stated in the above section, but it's not apparent that one setting relies on the other.  A nifty blockquote would be nice!

**Comment by McJty** [comment]
Fixed
