### ISSUE TITLE
Quarry does not harvest draconic evolution ores

### ISSUE THREAD

**Issue by blarghhh** [McJty/RFTools#413]
^ above.

P.s.  Love the quarry. Only problem is too many ores to process.

**Comment by McJty** [comment]
Yes this is a known problem. It also doesn't harvest gregtech ores. i.e. it doesn't harvest ores that are tile entities

**Comment by Balrog994** [comment]
Hi McJty,
are you planning on fixing this behaviour or it's "by design"? 
Can you give us some news?
Thanks

**Comment by McJty** [comment]
I haven't had time to look into this I'm afraid (and I kinda forgot about it too to be honest :-) ) If I get a chance I will look into it

**Comment by McJty** [comment]
A work around will be present in next version of rftools. You will be able to set a config option so that tile entities are also harvested. Hopefully that fixes the issue. This is still false by default though

**Comment by Balrog994** [comment]
Thanks for the fix ;)
