### ISSUE TITLE
[1.8.9] Screens cause inventory to get darker

### ISSUE THREAD

**Issue by Slikrick** [McJty/RFTools#417]
This occurs when holding the item in first person or by viewing them in JEI. Seen here:

Normal: http://i.imgur.com/rYkC76s.png

Screens searched for in JEI: http://i.imgur.com/LZEL6jb.png

Also when they are looked at in JEI the tooltip is broken, not sure if its the same issue, but thought i might as well mention it.

**Comment by mezz** [comment]
Just to confirm, another player ran into this issue
https://dl.dropboxusercontent.com/u/13531495/ShareX/2016/01/2016-01-09_18-01-13.png

**Comment by McJty** [comment]
I can reproduce this. Will try to fix next beta

**Comment by McJty** [comment]
Fixed in next release
