### ISSUE TITLE
[Suggestion] Make Auto Crafter keep non consumed items in the input inventory

### ISSUE THREAD

**Issue by imbrucy** [McJty/RFTools#418]
When trying to use the Auto Crafter for Pam's HarvestCraft recipes, the crafter outputs tools like the pot or skillet to the output after every craft. If you set the crafter to Keep mode then it won't craft at all. It would be very useful if the crafter behaved the same as a Cyclic Assembler does, in that it crafts the item, but keeps non consumed items in the internal inventory and can keep using them for repeated crafting.

**Comment by SnowShock35** [comment]
Yeah totally agree here. This is definitely something that would be really handy. I mean sure it's possible to fix this by extracting single stack crafting items and pump them around in a loop but that's just more lag on the server and client. (depending on the transport method).

**Comment by simonappleton** [comment]
Agree- this would be v useful... I currently have a chain of cyclic assemblers making carrot cake, but they get jammed up. I'd far prefer to use the crafter as it has better control of inputs... but the only solution seems to be to look the bakeware around (not good).

**Comment by McJty** [comment]
Will be implemented next release (for 1.9.4/1.10)
