### ISSUE TITLE
Client Crash - Shield Projector Tier 4

### ISSUE THREAD

**Issue by djbrooks06** [McJty/RFTools#419]
Hello Play on a public FTB Inifinity Evolved Expert server, I decided to make a Shield Projector Tier 4 and used the Shape Card to make a dimension of 100 blocks out.  once i used a wrench it crash my client.  Now anybody entering my chunks will client crash.  The Error Message when it kicks me says: " Internal Exception: io.netty.codec,DecoderException: java.ioexception: packet was larger than I expected, found 60172 bytes extra whilst reading packet 53"

This is the Paste in the logs.
<script src="//pastebin.com/embed_js/ffgjH2DM"></script>

**Comment by djbrooks06** [comment]
[ffgjH2DM.txt](https://github.com/McJty/RFTools/files/83797/ffgjH2DM.txt)

**Comment by McJty** [comment]
This is fixed in 4.20. What version are you on?

**Comment by djbrooks06** [comment]
its the 2.2.2 ftb version which is rftools 4.13

**Comment by McJty** [comment]
yes so this is fixed. Upgrading would help but that requires the server to upgrade too. Otherwise they can do mcedit to try to remove the shield projector
