### ISSUE TITLE
Problem with JEI integration

### ISSUE THREAD

**Issue by blockbreaker1361** [McJty/RFTools#420]
While I have your mod typed into the search bar, as you can see in the first image, you cannot see the tooltips for any items from any mods. This only occurs with your mod in the search bar.
http://imgur.com/a/2gzJf

**Comment by McJty** [comment]
That is probably related to the screen. I fixed that bug already. Will release in a day or two

**Comment by blockbreaker1361** [comment]
OK. Thank you. :)

**Comment by McJty** [comment]
This was fixed some time ago
