### ISSUE TITLE
[1.8.9-4.20beta2] Coal Generator Bug

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#422]
Coal Generator will accept any item being piped into it and treat it as coal (I have a quarry which outputs cobblestone to adjacent generators and that generates power).

![2016-01-12_20 43 56](https://cloud.githubusercontent.com/assets/8670392/12274878/40c38f22-b96d-11e5-9260-6595ef7ac0e1.png)
![2016-01-12_20 43 58](https://cloud.githubusercontent.com/assets/8670392/12274879/40c8184e-b96d-11e5-9c91-c4c9ea2ab9ae.png)

**Comment by McJty** [comment]
That is actually a very funny bug but I suppose I better fix it :-)

**Comment by Xiaminou** [comment]
Yeah cobblestone powered quarry is the best :D

**Comment by McJty** [comment]
Fixed in upcoming release

**Comment by Xiaminou** [comment]
another thing, is the coal generator supposed to work like a furnace? or accept only coal? because I couldn't use alumentum.

**Comment by McJty** [comment]
It only accepts coal. It is a 'coal' generator after all :-)
