### ISSUE TITLE
[1.8.9] Can't run RFTools in an obfuscated dev env

### ISSUE THREAD

**Issue by Tbsc** [McJty/RFTools#423]

**Comment by McJty** [comment]
Um? Can you clarify?

**Comment by Tbsc** [comment]
Yeah, I clicked enter without entering the description. Wait a moment.

**Comment by Tbsc** [comment]
I'm trying to code a mod for 1.8.8 using your "new" power system, and since it doesn't have any power generation I also installed RFTools. RFTools (obviously) can't be launched from a dev env since it uses obfuscated method names and in a dev env they are deobfuscated.

**Comment by McJty** [comment]
Ah. Well I don't really have a good place to host a non obfuscated version of RFTools. You can of course try to compile it yourselves. Atm that would be the only solution I think.

**Comment by wlhlm** [comment]
I believe this was just fixed in forge, so that stuff automatically gets deobfuscated and -dev jars are no longer necessary.

See MinecraftForge/MinecraftForge@9a737b0c906d2dd7d9a679eb099ff733b8f31453.

**Comment by McJty** [comment]
Ah nice! That would be an even better solution

**Comment by Tbsc** [comment]
@McJty Just saying, CurseForge allows you to upload additional files.

**Comment by McJty** [comment]
Yes but makes it somewhat more confusing for users. I tried it in the past and got confused users who couldn't get my mod to work because the downloaded the dev version.

**Comment by wlhlm** [comment]
@Tbsc as I said above. This is no longer necessary. Try forge build 1696

**Comment by Tbsc** [comment]
Alright, thanks for the help!
