### ISSUE TITLE
CtD on world reload

### ISSUE THREAD

**Issue by Sj212** [McJty/RFTools#427]
Whenever I reopen a world with an active builder I get a CtD. Even when I'm in the same dimension. I have a ChickenChunks chunkloader keeping it's area loaded.

Crashlog: http://pastebin.com/ejAHZDkc

**Comment by McJty** [comment]
Ok, there seems to be a chunkloading conflict. To get your world to load you can probably disable the chunkloading ability of the builder in the config:

    B:quarryChunkloads=false

**Comment by Sj212** [comment]
Yup, that fixed it. For future reference does a builder only load the chunk it's currently placed and working in?

**Comment by McJty** [comment]
Only the chunk it is working in. It doesn't attemp to chunkload its own chunk

**Comment by McJty** [comment]
This was fixed in 4.21
