### ISSUE TITLE
Painted glowstone (EnderIO) placed with Builder cannot be removed

### ISSUE THREAD

**Issue by Firnagzen** [McJty/RFTools#428]
Hello,
Using:
-EnderCore 1.7.10-0.2.3.0_beta
-EnderIO 1.7.10-2.3.0417_beta
-RFTools 4.0.1n573 
in the Direwolf20 1.7.10 pack, I placed Glowstone painted in the Painting Machine with a Chisel factory block texture.

When placed, the Glowstone reverted to its default texture, though the WAILA tooltip showed Painted Glowstone. The RFTools builder could not subsequently remove these blocks, instead scanning through the area as if there was nothing there but removing other blocks, and additionally, attempting to break the glowstone with a pickaxe ejected me from the server (but did not crash the server).

**Comment by StevenStone014268** [comment]
Had this problem or at least something like it on our server the only thing we could do to remove them was using a "Filler" on clear mode or something to that effect basically it deleted all blocks in the outlined 64x64 area the mod the block is from is called "Buildcraft" hope it helps at least a little long story short using painted blocks is a no no xD

**Comment by McJty** [comment]
RFTools 4.01n573 is ancient. Please use the latest version and if the problem is still present you can reopen the ticket
