### ISSUE TITLE
Issue with Phased Field Generator

### ISSUE THREAD

**Issue by BuckitHead** [McJty/RFTools#434]
We have created a Draconic dim that requires 500031 rf per tick. Now with a fully infused builder we are able to build only using about 82,000 rf per tick. Current power never  gets above 82,000 rf. Now if we take 5 Phased field Generators in the dim it allows us about 20 min of time to set up a quarry and get out allowing the quarry to keep running on the dim for only 82,000 rf per tick. Seems that the PFG only cost 1000 per tick in any dim to keep you alive no matter the upkeep cost and you can quarry a dim that does not have total power.

**Comment by McJty** [comment]
This is intentional. There is also a config option to change the PFG to have a tick cost relative to the maintenance cost of the dimension. If you prefer you can enable that.

**Comment by BuckitHead** [comment]
ok Sound good...I will pass on to Tfox for the pack... Thanks for quick reply
