### ISSUE TITLE
[4.20] Restarting minecraft while the quarry is running crashes

### ISSUE THREAD

**Issue by Rseding91** [McJty/RFTools#437]
http://pastebin.com/UM87TkUz

I had the ender quarry powered by a tesseract set to receive energy only. A vanilla chest on top of the quarry and a transfer node extracting stacks from the chest into a tesseract.

This was in the overoworld dimension 0.

**Comment by McJty** [comment]
As a temporary workaround disable chunkloading in the rftools config. I'll try to find a more permanent fix

**Comment by McJty** [comment]
Possibly fixed in next release (4.21). Will upload soon
