### ISSUE TITLE
[1.8] Dialer doesn't show new dimension

### ISSUE THREAD

**Issue by Daenyth** [McJty/RFTools#438]
I made a new dimension in the dimension builder with no dimlets, just to experiment in creative. I have a dialing device and a teleporter next to it. The dialer doesn't show my new dimension in its list though, even though the builder is at 100% and it's just adding rf to the dimension

**Comment by McJty** [comment]
What happens if you teleport to the dimension with the probe? Is there a spawn platform?
What happens if you make another dimension? Can you reproduce this?

**Comment by Daenyth** [comment]
I teleported using `/rfttp`, I didn't see a platform (but maybe I flew away from it before the world finished spawning).

I placed a teleporter and receiver in the dimension, went to overworld, made a second new dimension, and then the dialer showed it.

**Comment by Daenyth** [comment]
I'm guessing there was no platform because the dialer's target for that dimension is the receiver I manually placed
