### ISSUE TITLE
Crafter rf/t limit peer side

### ISSUE THREAD

**Issue by DarkLight66** [McJty/RFTools#44]
The crafter can only accept 80rf/t peer side, but with a fast enough extra utilities cobble gen setup and every single step up to octuple compressed coble going on at the same time it can use up to ~500rf/t on fast mode with 0% infusion before it can't keep up with the coble gen. I had to use a transvector interface from thaumic tinkerer to be able to power it.

**Comment by McJty** [comment]
In the next version the internal buffer will be increased to 50000 and it will be able to receive 500RF/tick.
