### ISSUE TITLE
[Feature request] Specify the liquids default tendrils generate with.

### ISSUE THREAD

**Issue by wekateka** [McJty/RFTools#440]
If I make a dimension with [Material Default] [Feature Tendrils] then water and lava randomly flows down from those tendrils. Looks cool, but I would love to be able to change these into different liquids. Is it possible to make [Feature Tendrils] take (multiple, preferably) Liquid-type dimlets to influence this?

Thank you for considering.

**Comment by McJty** [comment]
That's not really possible as the tendril generation and lake generation are totally independent

**Comment by wekateka** [comment]
Ok, thanks for your reply.
