### ISSUE TITLE
CoFHLib Requirement

### ISSUE THREAD

**Issue by Zsashas** [McJty/RFTools#443]
Is there a reason it requires CoFHLib specifically, instead of just the RF API?

**Comment by McJty** [comment]
What version of RFTools? RFTools just needs CoFHCore but not CoFHLib

**Comment by Zsashas** [comment]
Latest version from curseforge for 1.7.10 as of yesterday.

CoFHCore includes CoFHLib but I had neither before. Is there a reason it needs the coremod beyond the RF API?

**Comment by Zsashas** [comment]
The error message definitely said it needed lib not core.

**Comment by McJty** [comment]
Sorry that's what I meant. I mean that RFTools requires CoFHLib (not core). So that should be fine right?

**Comment by Zsashas** [comment]
Yeah it's fine, I was just wondering why it needed it. I was just trying to avoid the CoFH mods before because I had no use for any of them.

**Comment by McJty** [comment]
Well I need the RF API and that can be found only in CoFHLib. So yes this is needed

**Comment by Zsashas** [comment]
But several other mods also include the RF API, why not just have the API itself be a dependency instead of a specific mod?

Example: Ender IO. (Can't think of others off the top of my head)

**Comment by McJty** [comment]
The RF API is part of CoFHLib. So if you want the RF API as a dependency you need a dependency on CoFHLib

**Comment by Zsashas** [comment]
Except that this is the first mod using RF I've encountered other than the CoFH mods themselves that require CoFHCore or CoFHLib.

**Comment by McJty** [comment]
Weird... Well I have no idea how these do it then...

**Comment by XFactHD** [comment]
They are shipping the RF API with their mod.

**Comment by Zsashas** [comment]
Some are. Some just look for the API in any mod.

**Comment by McJty** [comment]
Well that ends up confusing. In the end there is something that has to implement it. And personally I think that's the job of CoFHLib. Other mods shouldn't do that IMHO
