### ISSUE TITLE
Lakes can generate in and destroy the platform made in Dimensions

### ISSUE THREAD

**Issue by howtonotwin** [McJty/RFTools#444]
This is not something that happened to me, but I came across it in someone else's video and it doesn't seem like it has been reported here yet.
[Video in Question](https://youtu.be/059wHETS5og?t=23m15s)

**Comment by McJty** [comment]
Yes, I have no solution for this. Some things generate after my platform and I have not yet found a way to change that.

**Comment by howtonotwin** [comment]
Alright, I'll close this for now.
