### ISSUE TITLE
Rf Tools Worlds "Hang" ?

### ISSUE THREAD

**Issue by StevenStone014268** [McJty/RFTools#445]
Upon entering a RFTools world all is well with the teleport there and basic creation(this problem presists when using effectively a blank world tab and a modified/custom one too) but upon entering the world what i can only guess happens is the tick rate becomes zero or something to that effect to explain sand and gravel are no long affected by gravity water, lava and other fluids do not behave as they should they do not flow or move from a source block, placing a bucket of water also creates the same effect though my game generally just closes all on its own by the point i try to do much more inside the world other than break a block here or there. Also attempting to leave the dimension by the matter teleporter block(sorry cant remember the name right this moment not infront of the game at the time of writing this) results in the same thing happening the game will close itself Im not even sure what to make of it ive never seen minecraft worlds behave this way before though from the people i have talked to mystcraft had this problem alot too not that I ever played with that mod before. I really like the mods other features and would like to play around with the world gen features too if my issue can be resolved any help that i get from anyone will be very appreciated!!! Also im will to provide any further information I can once I can get home from work and get some instructions on how to get said information because as i mentioned right now the game closes completely without any subsequent screens like a normal vanilla crash report does

**Comment by McJty** [comment]
Does the dimension have power?

**Comment by StevenStone014268** [comment]
Yes? Or at least it should the block which powers the dimension is powered by a draconic evolution tier 7 energy multiblock which has something like a 2million RF output with a cryo stabilized fluxduct from thermal expansions dynamics pipes mod or something like that which the tool tip for it says it has infinite throughput ... ? is this not enough should i just smack a creative energy cell on it or something honestly wondering I have no idea how much energy a world should need to run in the mod although my big reactor is pumping out a quite large sum of power .. Should I include screen shots?

**Comment by McJty** [comment]
Screenshots might help but your issue is very weird. I have never heard of this before

**Comment by xvolution** [comment]
Sorry for necroing, but I just encountered this bug when teleporting to my base in the same dimension using the "remote teleportation" device [can't look up the name since my game is currently running at 0fps]. It seems to occur when the Matter Receiver the device is linked to isn't chunkloaded. Both the receiver and device are fully charged. The only way to get out of the hang is to exit the game somehow and reload the world. This is for v.3.42

**Comment by McJty** [comment]
Cannot reproduce
