### ISSUE TITLE
Void warns if given material/liquid

### ISSUE THREAD

**Issue by HoldenMatheson** [McJty/RFTools#446]
with a void dimension, giving it either a liquid or material results in a warning. It does accept them and build properly if you ignore the warning.

Not specifying results in them being randomly chosen.

Personally, it makes sense to me that it shouldn't take nor generate a liquid or material.

Running FTB Infinity Evolved 2.3.5

**Comment by McJty** [comment]
I don't understand. In a void world there is no material or liquid to generate so what's the problem exactly? The warning is specifically to tell you that it doesn't make sense to add a material or liquid

**Comment by HoldenMatheson** [comment]
Because it will random generate them if you don't supply one, which you will then have to pay for even though nothing actually gets spawned.

**Comment by McJty** [comment]
Ah right

**Comment by McJty** [comment]
From now on if you don't specify and material or liquid for 'void' it will always randomly generate stone and water to prevent undesired bad costs, So material default and liquid default are not needed. This will be in next version (both 1.7.10 and 1.8.9)
