### ISSUE TITLE
(Mod Compatability Issue) FTB Utility Chunk Loading

### ISSUE THREAD

**Issue by dbridle** [McJty/RFTools#447]
Hello,
I hope its acceptable to post issues with other mods?  I'm using FTB Infinity and have noticed that chunk loading in RFTools dimensions doesn't seem to work right.

I have a void world (just a void terrain dimlet).  I have built a small platform and stuck my AE system on there, with an ender chest and an import bus.  I chunk loaded the base using FTB Utilities.

I have an enderman spawner, 500 blocks away, feeding to the ender chest linked to the one on my AE system.  Again, I have chunk loaded this area too.

The items are not transferring between the ender chests, even though the area is chunk loaded.  I will also report this on the FTB Utilities issues log, but wanted to make you aware in case it was something on your side?

Many thanks

Tirm

**Comment by McJty** [comment]
I don't think this is on my side as rftools dimensions don't do or prevent any chunkloading. But I'm interesting to hear what the other guys say about this

**Comment by dbridle** [comment]
Cool, thanks McJty!

**Comment by njensen12** [comment]
I also have the same problem.  I have my solar there to make RF, but they don't load it when my server restarts.  If I go there its fine.  I am using a Tesseract to transfer the energy.

**Comment by McJty** [comment]
Many chunkloaders are having issues with rftools dimensions on startup. I think chickenchunks in 1.7.10 worked fine but other then that not much does. I think the problem may actually be in forge itself as most of those chunkloaders use the forge chunkloading system
