### ISSUE TITLE
SimpleChannelHandlerWrapper exception and players being disconnected

### ISSUE THREAD

**Issue by Scratchman** [McJty/RFTools#451]
The server has started to experience a severe error that's causing players to be disconnected unexpectedly.

The server's log is being spammed with this error. http://pastebin.com/0j4j6nSM

Also when players are being disconnected i'm seeing this error. http://pastebin.com/YPkNtCxH

Rftools-4.20

We have disabled the dimensions aspect of your mod as well as all the machines to do with dimensions. Also we don;t have the alternate recipe for dimensional shards even though that option is enabled in the cfg. 

This is a Kcauldron server. version 1.7.10-1614.192. 

A complete list of mods on the server can be found at http://imaginescape.tk/forums/index.php?topic=3.0 , Of course, all the core mods are also installed too.

**Comment by McJty** [comment]
Hmm. I need more information. I would need to know what exactly happened when this started. Was this caused by some dimension? How did you disable the dimension part? Was there perhaps an environmental controller that was put somewhere? Also the full client and server log would be helpful

**Comment by smbarbour** [comment]
The issues started roughly around the same time that we had placed an Environmental Controller.  The spam on the server occurs even when it is turned off as well as when no one is in the area (no chunkloaders).  The player disconnection is occurring when we attempt to open the GUI, though upon reconnecting, we are able to access it.

If only Java's NPE would indicate precisely what in particular is null...

**Comment by McJty** [comment]
What modules are in the environmental controller? Also can you get full logs?

**Comment by McJty** [comment]
Also is enough power given to the controller?

**Comment by Scratchman** [comment]
Current fml-server-latest.log .. https://www.dropbox.com/s/jd56abyr8bof0ri/fml-server-latest.log?dl=0

The controller is placed in melonar/smbarbour's region but he hasn;t been on for the last 5-6 hours but i'm stiil seeing the errors in the log.

"(Melonar) So... it's being supplied with 1000 RF/t (from an EIO cap)"

"<smba​rbour> We have the second tier regeneration module and the first tier saturation module, though we just added that one"

    # Enable the dimension builder recipe.
    B:enableDimensionBuilderRecipe=false

    # Enable the dimension editor recipe.
    B:enableDimensionEditorRecipe=false

Other dimension machine recipes are disabled using minetweaker.  Also dimlets have been removed from the loot chest table.

Join us in irc.esper.net/#imaginescape if it would help you.

**Comment by smbarbour** [comment]
Client logs (though no stacktrace at the time of disconnect): https://gist.github.com/smbarbour/f3404afc2e4092efb1bf

**Comment by McJty** [comment]
And 1000 RF/t is enough to feed those two modules? If you try removing those modules does it help?

**Comment by Scratchman** [comment]
"(Melonar) Yes, 1000 RF/t is more than enough. It uses 35 RF/t"

Taking the modules out of the machine didn't generate any errors in the log.

**Comment by McJty** [comment]
Hmm ok. Seems something wrong there. I'll investigate. Thanks for the help

**Comment by Scratchman** [comment]
Update:

Seems the problem was caused by Kcauldron 1614, after changing over to Thermos 1614 the problems and spam have disappeared.

Thanks for all the help. Also, thank you, for all the time and effort you put into your mod.

**Comment by McJty** [comment]
Ah thanks for letting me know and glad you found the issue.
