### ISSUE TITLE
RF Monitor does not support large (long) RF storage

### ISSUE THREAD

**Issue by fraenkelc** [McJty/RFTools#452]
The RF Monitor block does not properly emit Redstone when used together with large RF storages (such as the Draconic Evolution one). Looking at the source it uses EnergyTools.getEnergyLevel(...) instead of EnergyTools.getEnergyLevelMulti(...). I'm not sure if theres a good reason for that, but I suspect its the source of the issue.

**Comment by XFactHD** [comment]
The RF API is using integer, if someone provides an energy storage which uses long, he has to provide the compatibility by himself and not have it so the authors of mods providing displaying methods.

**Comment by fraenkelc** [comment]
RFTools already has working support for the large rf storage fromDraconic evolution (and lots of other mods), see https://github.com/McJty/RFTools/blob/815c358fddb1e91816b25450d97f2e66ac663b9c/src/main/java/mcjty/rftools/varia/EnergyTools.java#L62. My point here is that RFMonitorBlockTileEntity .checkStateServer() uses the "normal" method instead of the multiblock storage compatible one.

**Comment by XFactHD** [comment]
Oh, ok, didn't know that.
