### ISSUE TITLE
Many of the craftable dimlets blacklisted with the default configs.

### ISSUE THREAD

**Issue by Entoarox** [McJty/RFTools#454]
As in the title, many of the craftable dimlets are blacklisted with the default config, I am also uncertain as to how to go about whitelisting them by editing the dimlet config.

Edit: Forgot to say this is with 1.8.9

**Comment by McJty** [comment]
The blacklisted dimlets are simply not implemented yet. They will be in a future version

**Comment by Entoarox** [comment]
Even the Material Stone dimlet??

**Comment by McJty** [comment]
Hmm. Will check that tomorrow but the one you should use for stone is 'Material Default'

**Comment by Entoarox** [comment]
Yep, that is the dimlet I meant, its blacklisted.
![2016-02-14_21 07 36](https://cloud.githubusercontent.com/assets/4977187/13036107/09824222-d35f-11e5-9a7a-d88708c70113.png)

**Comment by McJty** [comment]
Fixed in next release (for stone and water dimlets, the rest remains unimplemented for now)
