### ISSUE TITLE
Effect Dimlet RF Error

### ISSUE THREAD

**Issue by leroy627** [McJty/RFTools#457]
I'm quite sure if Health Boost 2 (Rarity 5) costs 950000 RF/tick to create, Health Boost 3 (Rarity 6) wouldn't cost 100000 RF/tick to create, typo?

**Comment by leroy627** [comment]
I'm using 4.20 btw, changelog didnt mention it being fixed or anything, and I don't have time to test (yet)

**Comment by McJty** [comment]
Typo indeed. Thanks for noticing. Will be fixed next release

**Comment by leroy627** [comment]
Great, I'm honestly surprised nobody noticed it before me xD
