### ISSUE TITLE
Build with quarry shape card only quarries the border of the defined area

### ISSUE THREAD

**Issue by Entoarox** [McJty/RFTools#458]
As in the title, I have a builder with a silk-touch quarrying shape card, but only the borders of the defined area are actually being quarried.

**Comment by McJty** [comment]
Select 'Solid Box' as shape instead of just 'Box'

**Comment by Entoarox** [comment]
Thank you, just as a suggestion, could you make that the default shape for quarry cards? It seems to me that it would also be the most commonly used one you see.

**Comment by McJty** [comment]
Yes, you are not the first one hitting this issue. It is perhaps not 100% clear :-)
