### ISSUE TITLE
advanced porter bug

### ISSUE THREAD

**Issue by xotonashix** [McJty/RFTools#459]
we did a java update on the 17.2.16  to the newest version and since then we cant teleport from some dimensions to the overworld
we get teleported but stay in the same dimension the coordinates are right we are on ftb infinity envolved 2.3.3 (also worked on this version for a while) and we have no clue how to fix this 
if the teleport with the advanced porter works there is a chance that the entire player gets duped (he can kill himshelf with a sword and drop his item)

**Comment by xotonashix** [comment]
downgrade java didnt fix this

**Comment by McJty** [comment]
What version of Minecraft and what version of RFTools? This seems extremely weird. I have never heard this before

**Comment by McJty** [comment]
So many people are playing with that version of RFTools and I have never heard this reported before. I really have no clue what could be going on here...

**Comment by McJty** [comment]
That will not really help debug it and also I don't have an infinity instance ready I'm afraid. Thanks for the offer though

**Comment by McJty** [comment]
I'm curious though. It started happening after upgrading java but didn't go away when downgrading? Any other things you modified? i.e. server settings? updated mods? added mods?

**Comment by xotonashix** [comment]
nothing was changed and it didnt go away after a downgrade of java

**Comment by Saereth** [comment]
I can confirm we're experiencing this issue as well, and ONLY with the advanced porter. Happens when going from another dimension back to the overworld. Standard porter works fine.

**Comment by McJty** [comment]
The advanced porter uses exactly the same teleportation code as the normal porter. Also I have never encountered this before and I haven't seen it with other people either (except in this report). I think it must be some interaction with another mod but not sure which one.

**Comment by Saereth** [comment]
its possible, I was able to get this to happen with the normal porter as well, this time simply teleporting from over world to overworld.

**Comment by xotonashix** [comment]
at least im not the only one xD

**Comment by McJty** [comment]
Probably vanilla teleportation issues and not related to rftools. There doesn't appear to be much that I can do about this I'm afraid
