### ISSUE TITLE
Multiple Template Colors/Channels

### ISSUE THREAD

**Issue by Aedda** [McJty/RFTools#46]
It could be super interesting and useful if Shield Template blocks could be colored using dye and would not connect to blocks of a different color. This would allow for things like controllable doorways through shields without bringing the entire shield down. Each color would obviously needs its own Projector connected to it. It would also make extending the shield coverage easier since colors could be alternated every 256 or 1024 blocks without concern of their edges becoming fused when in shield construction mode.

**Comment by McJty** [comment]
That's a nice idea. I'll think about how I can most easily do that.

**Comment by McJty** [comment]
Implemented already
