### ISSUE TITLE
Unable to set existing channel on a new transmitter

### ISSUE THREAD

**Issue by yarzzk** [McJty/RFTools#461]
Versions:

- Minecraft version 1.8.9
- mcjtylib version: 1.8.9-1.8.1beta6
- rftools version: 1.8.9-4.22beta22

Steps to reproduce:

1. Place a new transmitter
2. Rightclick with a receiver on the transmitter placed at step 1
3. Place the receiver
4. Rightclick on the transmitter placed at step 1 with a new transmitter, this places a new transmitter on a new channel.
5. Rightclick on the receiver placed at step 2 with a new transmitter, this places a a new transmitter on a new channel

Expected behaviour:
Steps 4 and 5 should produce transmitters set on the same channel as the transmitter receiver pair created at steps 1,2,3 as explained in the manual and tool tip for the transmitter.

**Comment by McJty** [comment]
I will check it out. Thanks for reporting

**Comment by McJty** [comment]
Fixed in next release
