### ISSUE TITLE
Trees growing with RFTools Chambers

### ISSUE THREAD

**Issue by Ryahn** [McJty/RFTools#465]
###### Issue
> This may be a one off but some trees are growing with Chambers on them.

###### Steps to reproduce
> Just grow a tree in 1.8.9

###### Image
> http://i.imgur.com/TZ4Bum1.png

###### Logs
> No error messages were generated

We are running a forge server and this is happening. @McJty You can contact me in the #rr irc channel for access to the server.

**Comment by McJty** [comment]
That looks like something got messed up adding or removing mods/blocks. Not something I can do anything about

**Comment by Ryahn** [comment]
Thank you, I will see what I can do on my end <3
