### ISSUE TITLE
[FTB Infinity Evolved] Crash when entering RFTools dimension

### ISSUE THREAD

**Issue by herrgutt** [McJty/RFTools#466]
Hey,

I am posting my bug here since this is most likely RFTools related. I created a fresh RFTools world and upon entering the game crashed. Now the problem is that when i am trying to reenter the game i am stuck at the 'downloading world' for 1 second before the game crashes again. 

Link to ftb [forumpost.](http://forum.feed-the-beast.com/threads/ftb-infinity-crash-after-trying-to-enter-rftools-dimension-restart-is-not-working.148066/)
Link to error log [pastebin.](http://pastebin.com/J9mD5RAB)

**Comment by McJty** [comment]
This has been posted before but I'm not sure this is a bug in RFTools. The stacktrace also does contain code from Immersive Engineering. I believe IE is doing something that it shouldn't. Perhaps try submitting a ticket to that project?

**Comment by herrgutt** [comment]
Thanks for your feedback. I will do post to Immersive Engineering git.

**Comment by McJty** [comment]
This will be fixed next release of Immersive Engineering
