### ISSUE TITLE
1.8.9 - Crash when entering RFTools dimension 

### ISSUE THREAD

**Issue by RyanP1991** [McJty/RFTools#467]
Currently using RF Tools version - rftools-1.8.9-4.22beta28
RF Tools Dimensions - rftoolsdim-1.8.9-4.22beta25

Whenever I create a dimension and teleport through it the game instantly crashes.

Link to pastebin - http://pastebin.com/RHiCjXv5

Using Forge version 1756

List of additional mods: http://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-8-9

**Comment by McJty** [comment]
I will check it out. Thanks for reporting

**Comment by McJty** [comment]
Fixed next version
