### ISSUE TITLE
Lockdown'd creative dimension starts up with odd dimension changes, but reverts after first reload

### ISSUE THREAD

**Issue by rockobonaparte** [McJty/RFTools#468]
I have Lockdown loading a creative dimension. The original dimension has an ender starfield and a normal day/night cycle. However, it comes up as permanent day with a blue sky instead. If I save the game and then re-enter it, the ender starfield comes back.

If you're feeling up to it, you can see it in the Baby's First Space Race Beta:
http://www.technicpack.net/modpack/bfsr-beta.806674

Just create a new world, look outside, and save. Restart the game and it will change.

I am assuming it may be some side-effect of block/item ID migration that gets patched up ones the game is being loaded more normally. I am suspecting I could just edit the dimension information and set it straight. Do you have a method for doing that? I can handle editing NBT data, and possibly a proprietary format if it isn't a huge pain and has some documentation.

(side conversation: I'll take any advice on how to explain a good progression for RFtools for stuff that is _not_ the dimension builder, since I don't know that stuff as well.)

**Comment by McJty** [comment]
Check out this page for commands: https://github.com/McJty/RFTools/wiki/RFTools-Commands

There is a lot you can do to edit dimensions and stuff

Perhaps a direwolf20 spotlight on rftools would help to explain the rest

**Comment by rockobonaparte** [comment]
If I'm reading the information correct, everything looks okay. It just looks like on the initial load, the sky's blue.

I can reload and it will do the ender starfield, and if I create a new world after that with the lockdown business, I will still get the ender starfield. So I don't know what to make of that.

**Comment by rockobonaparte** [comment]
I figured it out. RandomThings and CompactMachines were climbing over each other to try to get their greasy hands on dimension #3, which was the tutorial dimension. It looks like they'd play with it a bit.
