### ISSUE TITLE
[1.8.9] Fatal error, cant connect to server after creating new dimension

### ISSUE THREAD

**Issue by Saereth** [McJty/RFTools#470]
After creating a new dimension with a liquid manyullyn liquid I get fatal error and cant connect. It had a warning of a hanging modifier but let me create it anyway. It isnt a crash, so no crashlog but here is the clientside log when I get disconnected if it helps:

http://pastebin.com/RyQs1fNz

**Comment by McJty** [comment]
What versions of rftools, rftoolsdim and mcjtylib?

**Comment by Saereth** [comment]
ah sorry,can't believe I left that out
rftools-1.8.9-4.22beta31
rftoolsdim-1.8.9-4.22beta27
mcjtylib-1.8.9-1.8.1beta8

**Comment by McJty** [comment]
Other dimensions work fine? Can you give me more information about that dimension? I've never seen this before so I'm wondering what went wrong

**Comment by Saereth** [comment]
other dims do work fine, the dim itself Im pretty sure I screwed up making, I found a liquid dimlet for manyullyn and just slapped that in the enscriber, when it created and tried to teleport me is when it died. After server reboot it seemed to have stopped booting me and the worldgen was all screwy like patches that repeated.

**Comment by McJty** [comment]
Can you show a screenshot of that?

**Comment by McJty** [comment]
Found the problem. Will be fixed next release today
