### ISSUE TITLE
[1.7.10] CC function Documentation not up to date

### ISSUE THREAD

**Issue by Nathan1852** [McJty/RFTools#471]
The Documentation shown in NEI is not up to date. 
The interrupt function for a Dialing Device still lists x,y,z as arguments, but actually only wants the id of the transmitter.

Also the OC functions for the Dialing Device are not working, I did not test other blocks.
Some of the functions are defined as table instead of as function and the functions that are defined correctly are crashing OCs machine.lua.

**Comment by McJty** [comment]
CC support needs to be redone in 1.10.2
