### ISSUE TITLE
[1.8.9-4.22beta27] Fatal Error when making dimensions with dimlets

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#472]
I get a Fatal Error every time I tried to make a dimension with any dimlet. The "basic" dimension without any dimlet works fine.
The server keeps running just fine, but I can't join.
The error happens when the dimension is built.

Log: https://drive.google.com/file/d/0BxQWn9jKBIAJMGxveVpGM0RlQWM/view?usp=sharing (error is at the end of the log)

**Comment by McJty** [comment]
What exactly did you put in as dimlets?

**Comment by McJty** [comment]
Also can you hold the dimension tab in your hand, do shift-right click and then give me that information?

**Comment by Xiaminou** [comment]
![2016-03-15_16 24 57](https://cloud.githubusercontent.com/assets/8670392/13783161/8142abe4-eaca-11e5-9a6b-86008f6e0f32.png)
I've tried it with Lush Swamp and Chaotic, both give fatal error.

**Comment by McJty** [comment]
I need right click information. Not the tooltip

**Comment by McJty** [comment]
i.e. hold tab in hand, right click (or shift right click). That will dump info on the console

**Comment by Xiaminou** [comment]
there's right click information at the bottom left.

**Comment by Xiaminou** [comment]
it's all that shows for this tab.

**Comment by McJty** [comment]
That's strange.... It should give a lot more info. Did you try with shift too?

**Comment by Xiaminou** [comment]
Yup, and I agree, the "default" dimension gave all the right informations, this one doesn't.

**Comment by McJty** [comment]
Weird.... I'll investigate

**Comment by McJty** [comment]
I found a problem. Will be fixed in next release today

**Comment by Xiaminou** [comment]
It's fixed however new dimensions don't show up in the Dialing Device

**Comment by McJty** [comment]
None of them? That's strange... Can you show a screenshot of the dialing device gui?

**Comment by Xiaminou** [comment]
![2016-03-16_18 31 10](https://cloud.githubusercontent.com/assets/8670392/13822271/4a790190-eba5-11e5-96a8-92ef9371cdf5.png)
![2016-03-16_18 31 11](https://cloud.githubusercontent.com/assets/8670392/13822274/4db181de-eba5-11e5-8e1b-02d9238f5af7.png)
![2016-03-16_18 31 17](https://cloud.githubusercontent.com/assets/8670392/13822279/51d7d376-eba5-11e5-93f8-231e15142f02.png)

**Comment by McJty** [comment]
Was that one of the dimensions that was broken earlier or a new one?
If it is one that was broken earlier then that's normal. Otherwise that's weird.

**Comment by Xiaminou** [comment]
It's a new one, the old dimension still gives me fatal errors.

**Comment by McJty** [comment]
That shouldn't be. Can you give me those errors? It should now be ok

**Comment by Xiaminou** [comment]
https://drive.google.com/file/d/0BxQWn9jKBIAJNmlDSHZrTGplUnc/view?usp=sharing

**Comment by McJty** [comment]
Ok, seems there is still a problem there. I will check it out

**Comment by McJty** [comment]
Ok, I think I fixed it for real now. Making a new version now

**Comment by McJty** [comment]
Can you try the latest version? It should at least avoid the corruption issues you got

**Comment by Xiaminou** [comment]
works, I was able to create the dimension that used to cause the fatal error and it the destination is showing in the DHD.
