### ISSUE TITLE
[1.8.9-4.23beta32] RF Monitor doesn't emit redstone signal

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#473]
In my modpack, the RF Monitor indicates the power level but does not emit redstone signal no matter how I set it up (above/below, 0-100%, tried selecting multiple different machines and pipes). It emits on all sides, right?
I have never played with it before so it might just be me but that's unlikely, will do further testing with RFTools alone.
![2016-03-16_15 51 05](https://cloud.githubusercontent.com/assets/8670392/13816510/ecb0bb90-eb8e-11e5-9c3c-8264081e76ae.png)
![2016-03-16_15 51 25](https://cloud.githubusercontent.com/assets/8670392/13816515/f4dc96ae-eb8e-11e5-805e-6539128b372f.png)

**Comment by McJty** [comment]
Did you try with regular redstone? Maybe there is a compatibility problem with the redstone pipes that you are using

**Comment by McJty** [comment]
Also placing the monitor next to the generator controller might work better

**Comment by Xiaminou** [comment]
that's why I have the redstone lamp under it, but yeah I will try with redstone.

**Comment by Xiaminou** [comment]
![2016-03-16_16 15 19](https://cloud.githubusercontent.com/assets/8670392/13817391/4f09ffd8-eb92-11e5-91a2-037a577459cc.png)

**Comment by Xiaminou** [comment]
Okay my bad, it's not like the power monitor from ender IO, it only emits redstone in the back. Maybe this should be mentionned in the manual or changed to emit on all sides, I find it helps when it emits on all sides.
