### ISSUE TITLE
Client crashes when viewing dimlets in JEI

### ISSUE THREAD

**Issue by T-Bone523** [McJty/RFTools#474]
Minecraft v1.8.9
Issue: When you search for dimlets using JEI, and you hover your mouse over the symbol, your client crashes. Through in-game testing, it appears to affect most or all of the grey colored dimlet icons, screenshot of affected icons outlined below
Repeatability: This issue was repeated across multiple clients, one running Windows 8.1, another running Arch Linux
Screenshot:
![2016-03-17_22 39 47](https://cloud.githubusercontent.com/assets/17918692/13867935/19bed136-ec92-11e5-9bda-ef91b7f0b169.png)
Crash Report: 
[crash-2016-03-17_22.10.21-client.txt](https://github.com/McJty/RFTools/files/179045/crash-2016-03-17_22.10.21-client.txt)

**Comment by McJty** [comment]
I could not reproduce this but I did a blind fix for next version
