### ISSUE TITLE
Enhancement-Power relay

### ISSUE THREAD

**Issue by patchchristensen** [McJty/RFTools#476]
He first thanks for all you hard work on this great mod. I have one idea that I think would be really useful and not to hard to implement. Add to the power relay block an rf counter. Like the power meter on your house. You could see how much power has passed through it. Very useful to see how much you have really used on a dimension or anything else. We thought it would also be useful when playing with a large group and every one is sharing power. You could limit how much power is being used and/or have just have a count of what they are using. You could then bust heads for those heavy consumers.
Also have a reset button to set the counter back to zero.
Also can send a redstone signal when counter hits a set point.

**Comment by McJty** [comment]
Yes, that's a good idea. I'll probably implement this in the (near) future

**Comment by patchchristensen** [comment]
Sweet thanks! Let me know and I can help with testing if needed.

**Comment by McJty** [comment]
The powercells can do this in 1.10.2

**Comment by patchchristensen** [comment]
Sweet thanks for all your hard work.
