### ISSUE TITLE
Structure Dimlet related question

### ISSUE THREAD

**Issue by Entoarox** [McJty/RFTools#477]
On our 1.8.9 server we have a mod that adds a unique loot specifically to desert temples.

Now I had the idea of making a desert rftools dim to make temples more common (BoP is on the server, so deserts can be rare at times) but there does not seem to be a 'desert temple' dimlet or anything similar to it.

Do desert temples fall under another dimlet type or is there simply no dimlet for them?

**Comment by McJty** [comment]
Desert temples fall under the 'scattered' dimlet type. For now you can't create those dimlets on 1.8.9 though. That's still to be implemented

**Comment by Entoarox** [comment]
Ah, that is a shame, so there is no way to get temples to spawn in a RFTools desert dimension in 1.8 atm?

**Comment by McJty** [comment]
No not under your control. You could get extremely lucky and get unstructured dimlet generated randomly. I will soon start to implement these features but I'm currently hard at work with other stuff too

**Comment by Entoarox** [comment]
Ok, any chance I could simply edit the NBT to force-add the dimlet without the server crashing on me? :P (It is my server so I have that ability, and that unique loot really is extremely rare, only 1 in 4 temples even gets it to begin with!)

**Comment by McJty** [comment]
If you are admin you should be able to use the /rftdb createdimlet command like this:

/rftdb createdimlet structure scattered

Let me know if that works

**Comment by Entoarox** [comment]
The dimlet shows up, but it has the 'this dimlet is blacklisted' tooltip, and from what I gather that means you cant add it to a dim tab?

**Comment by McJty** [comment]
Um right. Sorry. It seems I have to do a bit more to get this to work. So for now you can't I'm afraid

**Comment by McJty** [comment]
I do plan an update of rftoolsdim today. I'll see if I can get this working quickly

**Comment by McJty** [comment]
Oh, found out it is case senstive. So you have to do:

/rftdb createdimlet structure Scattered

(capital 'C')
That should work

**Comment by Entoarox** [comment]
It worked, Temples are now showing up in the desert dimension, ty! :smile:
