### ISSUE TITLE
Inventory Module does not seem to read a Storage Drawers drawer

### ISSUE THREAD

**Issue by Ricket** [McJty/RFTools#478]
I sneak-clicked the 2x2 storage drawers and then put the module into my screen. No matter what IDs I fill in, I can't get the items from the storage drawers to show up on the screen.

RFtools 4.20 (FTB Infinity Evolved Expert)

**Comment by McJty** [comment]
Hmm. Perhaps these storage drawers do inventories in a weird way. Did you try reporting to them? Maybe they can give advice and this can be resolved
