### ISSUE TITLE
Error Ticking Matter Transmitter

### ISSUE THREAD

**Issue by voxelv** [McJty/RFTools#479]
Had a server crash related to the Matter Transmitter. It could also be something to do with Twilight Forest, but I'm not sure.

[crash-2016-03-23_08.12.26-server.txt](https://github.com/McJty/RFTools/files/186296/crash-2016-03-23_08.12.26-server.txt)

**Comment by zack11111111** [comment]
I had the same issue with singleplayer on my "Machinery" playthrough, had to reset without twilight forest

**Comment by McJty** [comment]
Cannot reproduce it I'm afraid
