### ISSUE TITLE
[1.9] Server crash when trying to use builder

### ISSUE THREAD

**Issue by dirtyfargo** [McJty/RFTools#480]
Description: When I try to use the builder with the quarry module on a server, the server crashes with the report below. Seems to work just fine in singleplayer. :) 
Forge Version: 12.16.0.1802 for MC 1.9
Mcjtylib 1.8.1beta8
RfTools 4.23beta33
Server Crash Report: https://gist.github.com/dirtyfargo/1dbf7d7ecad6b71a332d

**Comment by McJty** [comment]
I'll soon check this out once I'm done with DR. Thanks for reporting

**Comment by McJty** [comment]
Hmm. I cannot reproduce this. Works fine for me. Perhaps try upgrading forge?

**Comment by McJty** [comment]
Fixed next release
