### ISSUE TITLE
[1.9] 4.23beta35 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [McJty/RFTools#484]
Issue: rftools-1.9-4.23beta35 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/57e1f1f32b2fdbbc41ae

fml server latest:
https://gist.github.com/80df2db44df91bc5df26

**Comment by McJty** [comment]
Yes, RFTools hasn't been updated to that version of Forge yet. I believe from 1805 on a lot will break (not only rftools btw)

**Comment by kreezxil** [comment]
Yep, I'm reporting on every one of them, surprisingly i'm receiving fixes
within 5 to 10 minutes after every report.

**Comment by McJty** [comment]
I'll fix this tomorrow. It is already a bit late for me :-)

**Comment by McJty** [comment]
Fixed
