### ISSUE TITLE
1.9 Charged Porter cannot re-set targeted receiver

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#485]
When I set a porter to another receiver, it says target is set to new receiver, but yet the porter description still says the old one, and when used, it still teleport the old receiver.

**Comment by McJty** [comment]
What version of rftools?

**Comment by LordHellscream** [comment]
the latest version (for 1.9)

**Comment by McJty** [comment]
I cannot reproduce this. Exactly how are you doing this? As much details as you can? Also advanced or normal version of the porter?

**Comment by LordHellscream** [comment]
Advanced was the version I tested.
These are what I did (unsure in what order).
Have 2 receivers
1. destroyed and re-placed one or both the receivers.
2. changed names for one or both of the receivers (the ID does not change as I can see from the tooltip when the receiver(s) is in inventory
What happened was I have 1 receiver I named Home (Overworld, id: 5), one receiver I carry with me and named (travel id: 4). Before I leave I set the Advanced porter to target the home receiver (in inventory it says target is set to 4 as expected). 
I then went to a nether fortress, I set the travel receiver down near the outside of the fortress, then I used the charged porter to connect to travel receiver (it says connected successfully, and any subsequent attempt messages says porter already connected to 4, even tho its still actually connected to 5(home)). Then I went killing wither skeletons, after a couple of hours, I was loaded and so I used the adv. porter to go back to my travel point (outside the fortress), but then i was immediately teleported back to the home position (5, the receiver i first connected to)
This still happen even after i remove both of the receivers, place both to overworld, and attempted to connect porter to 4 again (it says already connected), but its really still connected to 5 and teleport me to 5.

**Comment by LordHellscream** [comment]
ok, this is not a bug. the adv. charger can hold multiple destination (this is not documented so only found out after reading this somewhere on the forum, and took sometime to figure out to use shift-click without targeting). Anyhow, closing this.
