### ISSUE TITLE
RF Monitor not Emitting redstone signal

### ISSUE THREAD

**Issue by AndrewSack** [McJty/RFTools#486]
Version 4.23 Beta33

The RF monitor is visually displaying the proper proportion of rf in a machine but it's not emitting a redstone signal regardless of percentage it's set to and whether it's on high, low, or none.  I have tested this with comparators, repeaters, and dust.  Unless I am doing something drastically wrong, I think this is an error.

**Comment by McJty** [comment]
It only gives a redstone signal at the back of the machine. Is that where you are testing?

**Comment by AndrewSack** [comment]
Oh man my mistake, I think I must have tested every other side!
