### ISSUE TITLE
[Dupe] Tier 1 Crafter

### ISSUE THREAD

**Issue by VariablePwn** [McJty/RFTools#487]
Tier 1 crafter can be used to duplicate items.
Place crafter on top of hopper, and without selecting a recipe, proceed to insert ghost items as if creating a recipe. The hopper will then take out these items as if they existed and place it in the hopper's inventory

Version: BETA 35, MC 1.8.9

**Comment by McJty** [comment]
I will check it out but I think I already have an idea what is wrong

**Comment by VariablePwn** [comment]
I did notice at one point one of the items had a value of 0, if that helps at all.
Btw, good effort on the fast response :)

**Comment by McJty** [comment]
Fixed for next release
