### ISSUE TITLE
RfTools builder clearing quarry not mining Draconium ore

### ISSUE THREAD

**Issue by th4umiel** [McJty/RFTools#488]
The title says everything :)

**Comment by McJty** [comment]
Known problem. By default RFTools does not quarry tile entities and draconium ore is a tile entity. You can enable this in the config (disabled by default)

**Comment by th4umiel** [comment]
Fast and exhaustive at the same time. Thank you very much.

**Comment by jaydog175** [comment]
ok so enabling the tile entities doesn't seem to work for me am i missing something? does it not work with the silk touch quarry?
