### ISSUE TITLE
Crash at startup with Forge 1811

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFTools#489]
Crash report:  http://pastebin.com/raw/hEXBywUf

Using:
- mcjtylib-1.9.0-1.8.1beta11.jar
- rftools-1.9.0-4.23beta36.jar

**Comment by McJty** [comment]
I *think* (not 100% sure) that this is a bug in moreplayermodels. I guess they forget to inject a capability. I think you should first check with them and see if they agree/can fix it

**Comment by kwpugh** [comment]
Indeed, you seem to be correct.  Out with moreplayermodels and in with RFTools.

Thank you.
