### ISSUE TITLE
problem with matter trans/recv when moving

### ISSUE THREAD

**Issue by excid** [McJty/RFTools#49]
There is a little problem with the Matter Transmitter and Receiver, when moving them with Funky Locomotions.

I love moving world eaters, that continuously move forward and mine for ever.

So i was hoping that a moved Transmitter and Receiver keeps their "config". Surprisly they do.

But the landing to the moved Receiver is the same where it was when dialing before moving. And the beam from the moved Transmitter is wrong too. 
And you teleport back on the Transmitter, not the beam.

I know, that's not a rly bug/issue (maybe the beam). 

Picture to descripe the issue a little better:
![little broke teleport](https://cloud.githubusercontent.com/assets/5160504/6305719/7d50ccc0-b92d-11e4-9da2-957257864d98.png)

Edit: Using version 2.42, and after breaking the Transmitter, the wrong placed beam will not disappear.
Edit v2: This is done on a server, and even after restarting the server, it will still not disappear. But it will, after placing a Transmitter underneath, and breaking it.

Greetings eXcid

**Comment by McJty** [comment]
This is a known problem and actually already reported here on the github. I will probably try to do something about it in the near future though. Not sure how yet though.

**Comment by McJty** [comment]
This will be fixed in 2.51
