### ISSUE TITLE
Will the 1.7.10 version of RFTools be split up into RFTools + the dimension mod 

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#496]
I like the RFTools mod and dimension mod, but my modpack is not ready for yet dimension mod yet, or will I need to keep the recipes removed in mine tweaker.

**Comment by McJty** [comment]
Splitting RFTools in two mods in 1.7.10 is not possible without breaking everyone's world. So it will not happen. Just remove the recipes in mine tweaker (or disable the dimension builder recipe in the rftools config)
