### ISSUE TITLE
(1.8.9) Timeout on trying to join server

### ISSUE THREAD

**Issue by drewbit** [McJty/RFTools#498]
Honestly not 100% sure if this is on RFTools's end but I'm at a bit of a loss here. Every time I try to join my server I'm getting a timeout because of a metric ton of error messages. It mentions RFtools in some of them:

"java.lang.NullPointerException: GameData.getItemRegistry().getNameForObject returned null for: class mcjty.rftoolsdim.items.DimletParcelItem"

Makes me think it might be something RFtools related. 

Here's the full log: http://paste.ee/p/4FFKI

Forge Version: forge 1.8.9-11.15.1.1847
RFToolsDim Version: rftoolsdim-1.8.9-4.22beta27
RFTools Version: rftools-1.8.9-4.23beta37

Not sure what else to give you. Let me know if you need more information.

**Comment by drewbit** [comment]
..... After I wrote that attempt number 14 or so got me on. Wat.

**Comment by McJty** [comment]
RFTools Dimensions 4.22beta27 is really old though. The latest version is 4.22beta31. I recommend upgrading. Many bugs have been fixed
