### ISSUE TITLE
NEI Dimlet Construction

### ISSUE THREAD

**Issue by Gideonseymour** [McJty/RFTools#50]
Not certain how possible this is, but it would be pretty cool if you could add integration for Not Enough Items that would allow for one to see the parts used in a Dimlet Workbench to make a certain dimlet. E.X. Showing the base, the control circuit, the essence, etc. It would probably help in the construction of these things, as determining the parts you need is somewhat difficult.

**Comment by Alec-WAM** [comment]
Here is an extremely quick stab at NEI integration(Warning very basic)
http://pastebin.com/6GtNvbmj

**Comment by McJty** [comment]
I'll check this out soon.

**Comment by McJty** [comment]
No longer relevant in 1.10.2
