### ISSUE TITLE
Question: TCon ore disabled in config -- still generates in rftools dim. Bug?

### ISSUE THREAD

**Issue by landaro** [McJty/RFTools#502]
I am using MC 1.7.10 with (among other mods)
- rftools 4.22
- Tinkers' Construct 1.8.8
- Thermal Foundation 1.2.2-111
- CoFH Core 3.1.1-324

The pack is configured to handle almost all worldgen ore placement via CoFH. Accordingly, I disabled the generation of TCon Copper in the TCon config:

    B:"Generate Copper"=false

Instead I configured CoFH to place sensible amounts of TF Copper. This works perfectly in the overworld (Dim 0) and (for other resources) in the Nether and End (Dim -1 and Dim 1).

Next I generated a number of RFTools dimensions, expecting them to replicate the overworld ore generation, unless I either explicitly ask for something specific, or the dimensions is underspecified and the RNG picks something special.

Of the 3 Dimensions I used to test this, it appears that the overworld distro was used, but _ in addition _ I also got TCon copper. The first was completely randomized, but the other two explicitly asked for default oregen, which again let to the placement of the disabled TCon copper ore.

Is there a configuration I am overlooking? Or another workaround (e.g. with Minetweaker) to disable the unwanted extra ore generation? What could be the origin of this strange behaviour and whose responsibility would it be to fix it?

As this only appeared once I started generating RFTools dimensions, I place the question here (I haven't tested mystcraft), but could imagine that the issue lies with TCon ...

**Comment by McJty** [comment]
This would indeed be a TCon issue. You'll have to see if you can disable TCon ores in other dimensions. RFTools cannot do much about that.

**Comment by landaro** [comment]
Thank you for the quick reply.

FYI: I posted the Issue on the TCon project page: [here](https://github.com/SlimeKnights/TinkersConstruct/issues/2011)
