### ISSUE TITLE
Permission Nodes

### ISSUE THREAD

**Issue by ohiomeister** [McJty/RFTools#504]
I run an Infinity Evolved server with GroupManager and want to allow players to be able to delete their dimensions with the /rftdim safedel command. I've already changed the RFTools config, but I also need to add the permission node to the GroupManager config. Is it possible I could get a list of the permission nodes for RFTools, or is there somewhere where I could find a list of them?

Sorry if this isn't the correct place to ask this.

**Comment by McJty** [comment]
What is GroupManager and what are permission nodes?

**Comment by ohiomeister** [comment]
GroupManager is a server side plugin that allows you to designate permissions to different server roles. In other words, you can create different ranks and give them access to different commands, examples being owner, admin, mod, trusted, and guest ranks. 

Examples of permission nodes would be:

- thaumic.tinkerer.common.core.commands.KamiUnlockedCommand
- vanilla.command.scoreboard

When these are added to say the 'trusted' rank in the GroupManager plugin configuration file, it gives the players, who are assigned that rank, access to the Thaumic Tinkerer command '/iskamiunlocked', or the Vanilla command '/scoreboard'.

**Comment by McJty** [comment]
RFTools currently doesn't support that I'm afraid. But why not let the players delete their dimensions using the in-game method? (i.e. sending a TNT block to the dimension using the dimension editor)

**Comment by ohiomeister** [comment]
That's okay. I was just hoping to avoid letting players use TNT. We try keep things like that banned on the server to keep players from using it to do major griefing.
