### ISSUE TITLE
[1.9] Game hangs on "Logging in" screen when logging in to an RFTools dimension (on server)

### ISSUE THREAD

**Issue by Brennan-S** [McJty/RFTools#509]
rftools-1.9.0-4.23beta40.jar
rftoolsdim-1.9.0-4.23beta33.jar
Forge 1858

Essentially, the title. I've been playing a self-made 1.9 pack with a friend on his server. Whenever I log out inside the RFTools dimension, I can't then log back in; the game gets stuck, throwing Java errors about network stuff and "concurrent" things.

If I MCEdit my player back into the overworld, I can log in again (spawning in in the overworld), and I can transfer to/from the dimension fine while I'm logged in. No issues when logging out in the overworld, or, as far as I'm aware, other vanilla dimensions.

For what it's worth, I have *not* tried logging in with another player in the dimension, nor do I have any chunkloading in the dimension. 

The dimension (if I remember correctly -- I can't log in) is Terrain:flat, Material:stone (normal), Effect:none -- essentially, normal but flat, as far as I'm aware (but there *is* an extra 10 RF/tick coming from some randomly added effect that I don't know what it is). The dimlet is 100% completely powered up.

Here's the relevant (I think) snippet of my error log. I can give you the whole latest.log if you want, but other than the extract below, it's essentially full of 
    Caused by: java.lang.NullPointerException
	    at net.minecraft.client.network.NetHandlerPlayClient.func_147263
type things being spammed over and over (until I hit "cancel" and stop trying to log in).

[RFToolsErrorLog1.9.txt](https://github.com/McJty/RFTools/files/233736/RFToolsErrorLog1.9.txt)
(Note: The log doesn't actually have the newlines. I did that for readability, so any weird formatting issues in the log are probably my fault)

[Edit: This seems to be somewhat similar to [this](https://github.com/McJty/RFTools/issues/499) issue, but in 1.9, not 1.8]

**Comment by McJty** [comment]
I will check it out but note that you are using an outdated version of both rftools and rftools dimensions.

**Comment by Brennan-S** [comment]
I know that I am a version behind -- friend doesn't want to update to newer Forge versions (and lose a few mods), and I don't seem to get the crash in singleplayer so I can't test independently. 

I hadn't seen anything about networking updates or bugfixes in the RFTools/Dimensions changelogs, so I figured I'd open a bug report in case you hadn't made any relevant bugfixes and it still may be an issue.

**Comment by McJty** [comment]
I can reproduce this. Now have to find a way to fix this

**Comment by McJty** [comment]
Ok, found it. Will be fixed next release (today)

**Comment by F3RRO** [comment]
hello. i have the same problem

**Comment by McJty** [comment]
Yes but this has been fixed so just update
