### ISSUE TITLE
Client crash when activating elevator (MC1.9 server)

### ISSUE THREAD

**Issue by PlacidK** [McJty/RFTools#510]
powered elevator block on bottom with 6 block platform in front of it, gave redstone signal to top elevator block with a lever. (also crashed when i used a screen + elevator button module)

Client log from crash --> http://pastebin.com/vEpcwb8n

**Comment by McJty** [comment]
Hopefully fixed next release.

**Comment by dirtyfargo** [comment]
I get this same client crash still on the latest release (4.43). I am playing on a server, if that is of any importance :)

**Comment by McJty** [comment]
Can you show me the crashlog for the 4.43 version?

**Comment by dirtyfargo** [comment]
Client crash report: https://gist.github.com/dirtyfargo/185bfab9d44325a3e8c40895daf3a3c4

**Comment by PlacidK** [comment]
I also had the crash, turning the elevator sounds volume to 0.0 in the config fixed the crash.

**Comment by McJty** [comment]
Ok, can anyone here use the version of rftools from here: https://drone.io/github.com/McJty/RFTools/files
and see if that fixes things? Download the top link from that page. If that works I'll release a new version

**Comment by dirtyfargo** [comment]
Fixed for me =)

**Comment by McJty** [comment]
Ok thanks for testing. I will release a new fix (again) today

**Comment by dirtyfargo** [comment]
No problem, really cool elevator by the way! Loving the possibilities with this =)
