### ISSUE TITLE
[1.9] "Invalid transmitter!!" - Matter Transmitter Won't Dial In The End or Nether

### ISSUE THREAD

**Issue by beanzen** [McJty/RFTools#511]
Minecraft 1.9, using Forge 12.16.0.1865, RFTools 1.9.0-4.30, RFTools Dimensions 1.9.0-4.23beta33

When trying to use the dialing device to activate a matter transmitter placed in The End, it gives a "Invalid Transmitter!!" error and refuses to dial. I've renamed and moved the transmitter and the dialing device, and everything is fully powered (and I have a working teleport network in the overworld that functions fine). I know the dialer has the right coordinates of the transmitter, because it will highlight the correct block when I check, so I don't know why or how the thing is listed as invalid. Note: I can teleport INTO The End just fine from the overworld, to a matter receiver in The End. I can also use the personal teleporter thing to teleport out of the end. 

UPDATE - I tried to set up a teleport station with a dialing device in the nether and that doesn't work either, giving the same "Invalid Transmitter!!" error in the dialing device as happens when I try the same thing in The End.

**Comment by McJty** [comment]
Hmm. I cannot reproduce this. Very strange. Is this single player or server?

**Comment by beanzen** [comment]
It's a server. I can use the dialing device to check the destination, and that turns up okay. Also, there's a matter booster under the transmitter, and I have the chunks kept loaded with a chunkloader to be safe. Everything is powered with a linked RFtools power cell array that works across dimensions and is kept topped off.

**Comment by McJty** [comment]
I'm going to try to debug this on a server but this will take some time setting up

**Comment by McJty** [comment]
I cannot reproduce this problem on a server either. Can you show me a few screenshots of your setup? Need to figure out what is going on here

**Comment by beanzen** [comment]
Thank you for looking into this! I have asked for a server reboot to see if that helps. Either way, I will jump on tomorrow and gather some screenshots and info for you. Will update this post then.

**Comment by beanzen** [comment]
UPDATE - Unfortunately a server restart did not fix the problem :(
I have taken screenshots of the configurations in the End and Nether for you to look at. Note that these are clones of the way it's set up in the overworld, where everything works.

![2016-04-26_12 48 39](https://cloud.githubusercontent.com/assets/9071526/14832244/2b3ae18a-0bae-11e6-8e9d-11e56a61667c.png)
![2016-04-26_12 48 46](https://cloud.githubusercontent.com/assets/9071526/14832250/32c57424-0bae-11e6-91be-ceac71795247.png)
![2016-04-26_12 48 58](https://cloud.githubusercontent.com/assets/9071526/14832253/36c80348-0bae-11e6-8334-acecac14aa40.png)
![2016-04-26_12 49 08](https://cloud.githubusercontent.com/assets/9071526/14832258/3a07c606-0bae-11e6-9636-04f4dccd5fcb.png)
![2016-04-26_12 49 15](https://cloud.githubusercontent.com/assets/9071526/14832261/3c112b04-0bae-11e6-9b8d-747059818fa8.png)
![2016-04-26_12 51 42](https://cloud.githubusercontent.com/assets/9071526/14832263/3e633366-0bae-11e6-9a11-e649b7716d30.png)
![2016-04-26_12 52 31](https://cloud.githubusercontent.com/assets/9071526/14832265/409ed48c-0bae-11e6-81af-dc4a8a247ff5.png)
![2016-04-26_12 52 48](https://cloud.githubusercontent.com/assets/9071526/14832268/427b79e0-0bae-11e6-9a1c-627abde6c122.png)
![2016-04-26_12 52 56](https://cloud.githubusercontent.com/assets/9071526/14832270/449a3644-0bae-11e6-9b9e-7d8c297c27ae.png)
![2016-04-26_12 53 01](https://cloud.githubusercontent.com/assets/9071526/14832274/4953470c-0bae-11e6-91f7-80b7e7e64c91.png)

First is the nether config, showing the destination analyzer and matter booster, along with the power cell, dialing device, matter transmitter/receiver. Then the error messages showing they don't work, even trying to teleport within the same dimension. Second set is in the End, basically the same config, showing the same issues.

Note - I have removed everything extraneous to the teleport in an attempt to see if they mattered - I removed the chunk loader, the matter booster, the destination analyzer, and even the power cell (after making sure everything is topped off energy-wise first), and there has been no change in the result. I've also tried putting the whole setup elsewhere, again with no change.

**Comment by McJty** [comment]
I'm baffled by this report and can't think of anything that would cause this. Will keep this open until more information appears

**Comment by beanzen** [comment]
I have updated to Forge 12.16.0.1868, RFTools 1.9.0-4.45, and RFTools Dimensions 1.9.0-4.23beta37

As of this writing, the issue no longer exists, and I am able to teleport between dimensions using the dialer without issue. I don't know what changed, but it seems to be working now!

**Comment by McJty** [comment]
Ah that's excellent news! Thanks for letting me know
