### ISSUE TITLE
ComputerCraft turtles can break protected blocks [RFtools 4.23] Minecraft 1.7.10

### ISSUE THREAD

**Issue by Stekeblad** [McJty/RFTools#512]
A few days ago someone asked on the Computercraft forums about how to stop a turtle from mining into a base and break things and I suggested to test with RFtools.

Today I decided to test myself to make sure it worked and discovered that a block protected by a Block Protector can be destroyed by a mining turtle, I could not break the blocks myself. 

I also tried breaking shield blocks then set to default solid but this prevented the turtle from advancing. 

This was tested on FTB Infinity Evolved 2.5.0

![2016-04-26_15 12 45](https://cloud.githubusercontent.com/assets/12627375/14819267/974d8b30-0bc1-11e6-9d25-f2c8e6ee98d3.png)
![2016-04-26_15 12 58](https://cloud.githubusercontent.com/assets/12627375/14819269/9bc7cdb0-0bc1-11e6-9735-c404bb2505cd.png)

**Comment by McJty** [comment]
Not sure if it is actually possible to fix this without some serious ASM. As far as I know the fault is actually on ComputerCraft's side for not firing the appropriate BreakBlock event first

**Comment by Stekeblad** [comment]
Ok, I will send a report on this to Computercraft then so they can look at it too.

**Comment by BombBloke** [comment]
As of CC 1.74 for MC 1.7.10, there's an API in the mod which should hopefully allow you to control what turtles can destroy. Check for "dan200.computercraft.api.permissions" in the API documentation bundled in the mod archive, see if it's any use to you.

**Comment by McJty** [comment]
Yes but such an API is not needed if mods that break blocks would first send out the forge event for breaking a block. RFTools cannot be expected to access the special API for any mod that has a way to break blocks. That's up to the mod itself and properly send out the appropriate event that is made for this purpose

**Comment by Saereth** [comment]
Yeah unfortunately alot of mods do this, Mekanism comes to mind by simply replacing the block with air and calling dropped items with the digital miner, there is unfortunately going to be many ways to bypass until mod authors uniformly change their approach to miners.

**Comment by BombBloke** [comment]
Not that I have a clue about Minecraft modding, but digging around I get the impression that the reason for taking this alternate route is that the regular block-breaking functions don't seem to _work_. It may also be to prevent items from dropping into the world? I dunno.

In any case, it's unlikely CC will see any further updates for MC 1.7.10. As for its block-breaking behaviour under later builds... who knows.

https://github.com/dan200/ComputerCraft/issues/103

**Comment by Deathlymad** [comment]
Well in the CC config there is the following line:


    # If set to true, Turtles will be unable to build, dig, or enter protected areas (such as near the server spawn point)
    B:turtlesObeyBlockProtection=true

i suppose that you should check that. if it is set to true something is wrong if set to false switch it that should fix that :D

**Comment by Stekeblad** [comment]
Did not know of that config option, but it is already set to true
