### ISSUE TITLE
[1.8.9] Logic Gate server crash

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#513]
![2016-04-27_16 15 34](https://cloud.githubusercontent.com/assets/8670392/14855245/4dfee212-0c93-11e6-8d3d-8d6c33d8643f.png)

Placing a logic gate on the wall above the timer and rotating it so the redstone signal will go throught causes a server crash.

Crash Report: http://pastebin.com/Vx830nYu

**Comment by McJty** [comment]
I can reproduce and will try a fix soon

**Comment by McJty** [comment]
Will be fixed in 1.8.9 and 1.9 later
