### ISSUE TITLE
Crash when using barrel on builder

### ISSUE THREAD

**Issue by Grygon** [McJty/RFTools#514]
Experiencing [this issue](https://github.com/McJty/RFTools/issues/404) again. Crashlog [here](http://pastebin.com/YbGnte4S).

**Comment by McJty** [comment]
This looks like a bug in JABBA. Not sure if there is much that I can do about that in RFTools I'm afraid.

**Comment by Grygon** [comment]
Since it's a sided inventory, couldn't you use [canInsertItem](https://lazdude2012.github.io/YATS/interfacenet_1_1minecraft_1_1inventory_1_1_i_sided_inventory.html#ab81668cda52667d434cba964f0775892)? That should prevent a crash.

**Comment by McJty** [comment]
Handled better in 1.10.2
