### ISSUE TITLE
Client crash when looking at a mob/entity [1.9-4.42]

### ISSUE THREAD

**Issue by dirtyfargo** [McJty/RFTools#515]
Description: When I look at a mob, I get the following client side [crash](https://gist.github.com/dirtyfargo/29632b7478671a0d45be937daccd088f) on the newest release of RFTools. 
Mcjtylib: 1.8.2
Forge: 12.16.0.1866

**Comment by McJty** [comment]
I will fix asap

**Comment by McJty** [comment]
Fixed in 4.43 which should be public in a few moments

**Comment by dirtyfargo** [comment]
Yay thx for the quick fix =)
