### ISSUE TITLE
Teleportation Issue

### ISSUE THREAD

**Issue by LogicalEnigma** [McJty/RFTools#519]
Teleporting randomly causes this (Picture below) to happen. The odd part about it is that if I exit the world and reopen it, it renders the room as if I was standing there all along.
![2016-04-30_13 58 55](https://cloud.githubusercontent.com/assets/13333949/14937633/d411ab24-0edb-11e6-83f7-6eb75e5e1167.png) After teleporting, before leaving the world
![2016-04-30_14 01 53](https://cloud.githubusercontent.com/assets/13333949/14937644/353a098c-0edc-11e6-889a-289e128ba261.png) After restarting the world, My actual location

It should also be mentioned that this only happens when I'm teleporting to a receiver that is outside of my render distance. Teleporting between receivers within 5 chunks goes without a hitch. It doesn't _always_ happen, but if it's beyond 5 chunks, there _chance_ that it might happen. Any help would be very appreciated. Thanks!

**Comment by McJty** [comment]
What version of RFTools?

**Comment by LogicalEnigma** [comment]
4.20. I assume that I should update it?

**Comment by McJty** [comment]
That is pretty old although not sure if anything was fixed there. You can try updating

**Comment by LogicalEnigma** [comment]
Yeah, I updated it. Still having the issue. Are there any mods that don't work well with rftools that I should look out for? Any settings that might make a difference?

**Comment by McJty** [comment]
Not that I know

**Comment by RigorMortis13** [comment]
This might be a minecraft issue. I got the same sreen when playin on unstable 1.8 sever and useing the /rtp command (random teleport position).
