### ISSUE TITLE
Customizable Material Dimlets

### ISSUE THREAD

**Issue by Gideonseymour** [McJty/RFTools#52]
Not sure how possible this is, but it would be nice if a config was provided to create custom material dimlets. Say, the end user puts in the name of the block and the metadata, and then a dimlet is created in-game for that block.

E.X.:
Say I want to create a "Manganese Block" dimlet. I would place in the config:
OresPlus oreManganese 0

Which follows the format:
modid name metadata

Obviously you could change the format for whatever would work best for you, but I'm just using that as an example.

**Comment by McJty** [comment]
You are supposed to be able to define your own material dimlets in config/rftools/userdimlets.json.  However, when looking at this I think it is currently broken. I'll fix it.

**Comment by McJty** [comment]
Fixed in next version. The format for userdimlets.json will be:

[
	["material", "minecraft","planks",5],
	["material", "minecraft","planks",4]
]

i.e. that means: type (currently only material), modname, blockname, metadata
