### ISSUE TITLE
[1.9]Crash with screen teleporting back to area

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#520]
Forge 1865
Rftools 4.45

When teleporting back to base this happened http://pastebin.com/VTZe1iYB I wasn't using RFTools teleporters it was a silentgems teleport and the screen in question, well we have only one

http://i.imgur.com/1t29dBO.png

**Comment by McJty** [comment]
Hmm, that's strange. Does it happen every time if you go to that spot? Perhaps try wrenching the screen a few time (to cycle between modes) to see if that helps?

**Comment by b0bst3r** [comment]
No I've returned to that spot loads of times, it happened just the once.

**Comment by McJty** [comment]
Not exactly sure what is wrong but I will add a safety for this in next release (soon)
