### ISSUE TITLE
ERROR: Players cannot delete dimensions on singleplayer world (1.7.10)

### ISSUE THREAD

**Issue by Famous5000** [McJty/RFTools#521]
Self-explanitory. When I have a dimension created in creative mode, and try to destroy it in creative mode, it doesn't delete. Note: I'm using the Dimension Editor on a dimension created by me in a Creative Dimension Builder. Yes, I am putting in TNT to the LEFT slot.

**Comment by Famous5000** [comment]
Also: I can use the Teleporter Probe. And that requires admin+?

**Comment by Famous5000** [comment]
Nvm, B:editorCanDeleteDimensions was set to FALSE. I'm silly. Closed.

**Comment by Famous5000** [comment]
I tried it using the config variable set to true, and it's still not working. I'll need an answer for this, as I'm planning on hosting a server with this and I want to be able to delete non-used dimensions with the block itself.

**Comment by McJty** [comment]
This config has to be set on the server. Did you do that?

**Comment by Famous5000** [comment]
I was on SINGLEPLAYER. Note: SINGLEPLAYER. I will set it to true on the server once I know it is completely resolved, but I was on SINGLEPLAYER and I couldn't delete it.

**Comment by Famous5000** [comment]
I'm going to try it again. Wish me luck.

**Comment by Famous5000** [comment]
![2016-05-01 2](https://cloud.githubusercontent.com/assets/9399230/14944590/fdee632c-0fb4-11e6-9feb-0df5375ed13b.png)
This is the image of the editor trying to delete the dimension. And some updates, including the message "Players cannot delete dimensions!"

**Comment by Famous5000** [comment]
![2016-05-01 3](https://cloud.githubusercontent.com/assets/9399230/14944605/4c824544-0fb5-11e6-9596-5b06a2564360.png)
As well as the DIMENSION TABLET INFO. I can copy it and read off the contents it shows there.
![2016-05-01 4](https://cloud.githubusercontent.com/assets/9399230/14944613/77d50f42-0fb5-11e6-8b5f-544c81508f12.png)
^^^^^
Info about the Dimension Tablet and its dimension

**Comment by Famous5000** [comment]
I can delete it via command, but I can't delete it using this block. I want to be able to change this so that I can have people delete their own world while at the same time not being able to delete other people's dimensions. I'm the only person OP'd so there should be no problems with permissions there.

**Comment by Famous5000** [comment]
![2016-05-01 5](https://cloud.githubusercontent.com/assets/9399230/14944657/5b8e99be-0fb7-11e6-8b50-dfb4b951b611.png)
This is the dimension editor trying to delete no dimension. You can still see that "Players cannot delete dimensions!" is still there.

**Comment by McJty** [comment]
If you get that message then you forgot to change another flag in the config. There are two flags:

B:playersCanDeleteDimensions=true 

and:

B:editorCanDeleteDimensions=true 

Are both set to true?

**Comment by Famous5000** [comment]
OOOOOH. *facepalm* I did NOT see that config. I'll launch MultiMC and open up the configs. If that fixes the problem, closed. Otherwise, it'll still be open.

**Comment by Famous5000** [comment]
Yea, that config variable was FALSE. I'm testing it right now.

**Comment by Famous5000** [comment]
I don't even need to destroy a dimension to know that this needs to be closed. As soon as I saw no messages and the percent sent going up my heart lit up. Thank you so much! I am going to copy the config over to my new server and close it here. Thanks for helping!!!
