### ISSUE TITLE
[1.9] Shift clicking recipe for shield template causes crash

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#524]
rftools-1.9.0-4.45
jei_1.9-3.3.2.196
Forge 1865

Shift clicking recipe (the +) in JEI for shield template causes client disconnect with the following message - http://i.imgur.com/hrBQ5c3.png

Log traps this which might be a Forge error ? http://i.imgur.com/TpOpnzX.png

**Comment by McJty** [comment]
I would report this to the JEI guys. Doesn't seem to be a RFTools but but I may be mistaken

**Comment by b0bst3r** [comment]
It's not, I did further invetigation into the crashing and it appears isolated to Refined Storage crafting tables, sorry to bother you with this.
