### ISSUE TITLE
Crafter stops crafting after a while when crafting Minechem buckets

### ISSUE THREAD

**Issue by kurtu5** [McJty/RFTools#525]
I created recipe for a MineChem Hydrogen Chemical Bucket and set it to external and told it to remember slots so returning empty buckets are not blocked by the incoming Minechem Hydrogen vials.  It works great for a couple of minutes and then it stops crafting.  The internal inventory has all required items and the external buffer is not blocked.  I can watch it in the Crafter UI stopping.  If I then click the recipe name it suddenly starts crafting again.

I am playing Galactic Science by Cathleen Version: 1.5.9 on the Curse launcher.  It's rftools-4.21.jar under Minecraft 1.7.10 using forge-10.13.4.1558.  I made sure it was not a chunk boundary issue.  I explicitly made multiple slots for buckets and vials, only one slot for buckets and other permutations with repeated results.  I tried setting the Crafter to fast and slow.  I tried using redstone to turn of and on the Crafter, hoping a time could reset it, and it would not restart.  I and am not sure what else I could test before reporting this.

Here are some screen shots of it failing under one of the many testing conditions;

[This is it after it stops](http://i.imgur.com/yA9p4Iq.png)

[This is it after I click the recipe name and it starts again](http://i.imgur.com/PuBgShw.png
)

**Comment by McJty** [comment]
Cannot reproduce and outdated version
