### ISSUE TITLE
[Feature Request] Screen Modules update and NBT

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#527]
Hello again, as you know I've been playing with RFTools' screens quite a bit in the last few days, they're great but I feel that a couple of things are missing:
1. The ability to Align Center and Align Right for the text would go a long way toward global presentation.
2. RF/t is not really that, it's the difference in the power buffer over the last, 5 seconds? Would it be possible to have the actual RF/t use of the machines? I don't know how the RF API works so I'm gonna assume you did it this way for a good reason, but still worth asking.
3. Now for the complicated stuff, would it be possible to make a module that reads NBT, I know [Practical Logistics](http://minecraft.curseforge.com/projects/practical-logistics) had a device that was able to read NBT, and you were able to use that for example to determine the burn time of a furnace and show it on screens. I think it would be a fantastic addition to RFTools' screens.

**Comment by McJty** [comment]
1. Yes that's possible
2. Actual RF/t usage of the machines is not possible in general since the RF API doesn't have anything for that. I can only measure the RF contents of a machine at a certain point
3. Having the ability to just read NBT at random might be useful but this can be abused in several ways. Many mods use NBT to store various information in a block which you are not supposed to know about. Not sure how to implement this in a way that wouldn't be consider very OP in some situations

**Comment by Xiaminou** [comment]
3. That is a good point, I must admit I hadn't though of it. But if we're talking purely mod interaction balance I would say it's up to the modpack makers to decide if they want the players to have this power (of course that's the good old debate, should mod authors or modpack authors do the balance? and what is taking it too far?), Maybe have it disabled by default?
It remains your call, I won't try to push if you decide you don't want the mod to have it.

**Comment by Xiaminou** [comment]
Just thought of something I forgot to mention, the bottom of the actual screen (what shows modules) seems to be shorter than what you see in the world, when it feels like a module would still fit at the bottom of the screen, it doesn't. Could it be made so it can extend a bit out of the screen like it does on the right edge for longer texts?
And something else, for the Energy modules, if you enter more than 7 characters the text will go into the energy bar/text. Maybe make it so you can't enter more than 7 characters, or make it push the energy bar/text further to the right? Depending on the size of your RF Buffer there's usually space to put more than 7 characters.
