### ISSUE TITLE
Crash: inserting RCL module into screen

### ISSUE THREAD

**Issue by dreness** [McJty/RFTools#528]
Hi,

Here's a repeatable crash after I inserted an RCL module into a screen, after binding the module to a tank with RCL in it.

http://pastebin.com/sM7nn1hu

I currently can't load the world, but I can always edit out the screen if this isn't fixed by the next time I play :)

Thanks!

**Comment by McJty** [comment]
Update Deep Resonance. Your version is not compatible with RFTools
