### ISSUE TITLE
[1.7.10] DraconiumOre cannot be quarried because it always returns false for canEntityHarvest

### ISSUE THREAD

**Issue by oceth** [McJty/RFTools#530]
DraconiumOre cannot be harvested by the Builder because it always returns false for canEntityHarvest. I'm not sure if this is a bug in RFTools for checking this method or in DraconicEvolution for returning false.

**Comment by McJty** [comment]
Enable harvesting of tile entities in the rftools config. This is disabled by default for safety reasons.

**Comment by oceth** [comment]
I have it enabled, still doesn't work. Actually, I meant canEntityDestroy, not canEntityHarvest

**Comment by McJty** [comment]
Hmm. No clue. In any case, RFTools must call that method. That cannot be prevented. Not sure why it would return false though.

**Comment by oceth** [comment]
It's hardcoded that way, not sure why though:

https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/blocks/DraconiumOre.java#L39

**Comment by oceth** [comment]
Actually, I now know why, to prevent the dragon destroying the ore:
https://github.com/brandon3055/Draconic-Evolution/commit/b0b063bbe588872aabed8c8c37c03dc9605d22a8

I guess it is a bug in DE.
