### ISSUE TITLE
[1.9] Breaking Advanced Powercell immediately loses 1m RF

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#532]
So I have 2 Powercells + 1 advanced powercell = 3m RF
http://i.imgur.com/B0uxml2.png

If I break the Adv powercell the remaining 2 basic ones retain the 1m RF (500k each)
http://i.imgur.com/OAN39Y3.png

However the 2m RF which is supposed to be kept in the Adv Powercell is only 1m RF
http://i.imgur.com/Fc7nwrW.png

So when I replace the adv powercell down again my 3m RF is now 2M RF and starts charging up again
http://i.imgur.com/A90sN2p.png

rftools-1.9.0-4.47.jar
mcjtylib-1.9.0-1.8.3.jar
Forge 1887

**Comment by McJty** [comment]
Fixed next release
