### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rcistano** [McJty/RFTools#533]
How about having something like an Energy Acceptor. Like the one from AE2

**Comment by McJty** [comment]
To do what exactly?

**Comment by rcistano** [comment]
To convert energy from external mods to RF (IndustrialCraft uses EU, RotaryCraft uses Watts/Joules, etc) It would be nice to have something that converts it all  to RF so that I can store it all as my energy system doesnt accept certain mods

**Comment by McJty** [comment]
Well RotaryCraft already has its own system to convert to RF. And I believe that for IndustrialCraft there are also solutions already so I'm not sure this is really needed?
