### ISSUE TITLE
[1.8.9] Client + Server crash when creating a new dimension and old dimensions wiped

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#539]
so apparently a recent update wiped out all of the RFTools dimensions (cannot access the matter receivers except for my void dimension which got reset).
Attempting to re-create my mining dimension crashed the server and client when dimension building finished.
so much for moving to a void dimension to improve FPS/TPS.

Client crash report: http://pastebin.com/kXnK5GWh
Server crash report: http://pastebin.com/WmXwSsWB

**Comment by McJty** [comment]
What was updated?

**Comment by Xiaminou** [comment]
here's the latest updates: http://imgur.com/y9Ho7QM

**Comment by McJty** [comment]
Old version
