### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Neodark7** [McJty/RFTools#54]
Crash report : http://pastebin.com/QRJgbt3P

**Comment by McJty** [comment]
It is actually crashing in the code from the Translocator (ChickenCore) so I doubt this is a problem in RFTools. When exactly does this happen?

**Comment by Neodark7** [comment]
it's on server start or client login... now i have removed translocator and i have

java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.carpentersblocks.block.BlockCoverable

>.<

**Comment by Neodark7** [comment]
i have all those errors since i updated cofh mods :/ yesterday it was https://github.com/CrazyPants/EnderIO/issues/1976

**Comment by Neodark7** [comment]
Fixed this need to backdate all cofh mods to december versions and update again with stable ones
