### ISSUE TITLE
Pearl Injector bug

### ISSUE THREAD

**Issue by Myknakryu** [McJty/RFTools#542]
Minecraft version: 1.9.4
RFTools version: 1.9.4-4.48
McJtyLib version: 1.9.4-1.8.6

When you try place Pearl injector near Endergenic Generator, client crashes. But after loading game again Pearl Injector is placed near generator. Game crashes only when you place Pearl Injector near the Endergenic Generator.

Crash Logs:
http://pastebin.com/tVcCr8sb

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
Fixed next release (today)
