### ISSUE TITLE
Builder and Quarry Card Issuse

### ISSUE THREAD

**Issue by RigorMortis13** [McJty/RFTools#545]
Im playing on a 1.8 Unstable server. 
My **Quarry Cards** (Silktouch and Fortune both clearing and non clearing) **getting simply deleted** after a short when they are in a builder. Happend 7 times so far. The space chamber card im useing havent shown this issue so far.  After the card had been deleted (and i checked if they were anywhere else) the **Builders Ownership had been reset** (error msg~: the ownership isnt set properly. pls palce this block again ...).
**Additionall** effect was that my **Power Generators from Deep Resonance** had like  **-  20 billion energy stored (negative energy)**.  Happend every time the cards had been deleted and the builders ownership had been reset. 
The setting on the card had been different ones (preset direction and/or own values). Both with preview activated/deactivated.
Area was chunkloaded by neotech chunkloader. 

_greetings Rigor_

**Comment by McJty** [comment]
What...
I have never seen this reported and can't think of anything that would cause this. Extremely weird...

**Comment by RigorMortis13** [comment]
Well... If u need further Informations or something im allways pleased to help.
its the official 3.0.41. FTB Unstable pack.

**Comment by McJty** [comment]
Yes, it is as if the builder is resetting to the situation as it was freshly created. So something is causing the chunk to reset all information. I would suspect (but not 100% sure) that if you had other machines there from other mods they might also get cleared like that.

**Comment by McJty** [comment]
BTW, in what dimension was all this?

**Comment by RigorMortis13** [comment]
Everything happend in the overworld. I had a chunkloader from neotech next to it, a receiver and an advanced powercell. It didnt seemed they were resetting at all.

**Comment by McJty** [comment]
Yes, RFTools Dimensions is a separate mod and is not included in Unstable.

I wonder if the neotech chunkloader is to be trusted...

**Comment by RigorMortis13** [comment]
I forgot to tell that the spacechamber card didnt worked anymore after  the bug and after i used the same builder for copying. the builder simply refused to work at all. he showed the layer he was working on but never moved. 
Ill check if the issue is related to the neotech chunkloader ty alot :).

**Comment by RigorMortis13** [comment]
Ok i tested the chunkloader. I was standing right next to my builder and inserted the quarry card after adjusting the offset. Got Instantly deleted this time. Same Issue as before.

**Comment by McJty** [comment]
Can you show me a screenshot of that setup? What about other machines there?

**Comment by RigorMortis13** [comment]
for testing purposes i removed the chunkloader. afterwards i placed it again.
before the bug the build had been infused and were owned by me. i didnt even started the quarry (so far i mentioned it) just inserted the card. 

http://postimg.org/image/3n09it9az/
http://postimg.org/image/d6t8xzo7v/
http://postimg.org/image/amf8kx74r/
http://postimg.org/image/d392slefv/
http://postimg.org/image/6xd6pvk9n/

**Comment by McJty** [comment]
I don't know what to say...

**Comment by RigorMortis13** [comment]
just for the sake of the protocoll here a screenshot of the deep resonance generators:
http://postimg.org/image/b3ksuflnf/

**Comment by McJty** [comment]
Just one thing. I'm interested in the full log from Minecraft when this happens (i.e. when the builder is cleared) to see if there is anything suspicious in that log

**Comment by RigorMortis13** [comment]
I asked one of the Admins for a logfile. Sadly only the owner and the headadmin are able to give me the logfile. Both arent avaiable atm. Ill see if im able to contact the headadmin via the forum.

Btw. i found that the issue with the negative energy stored in the generator block only appears if they are connected to an advanced powercell. Earlier on and recently i hooked up the generator directly to the builder and there hadnt been any issues (for a good while with with the quarry and never for the generator).
