### ISSUE TITLE
Advanced Charged Porter [Bug?]

### ISSUE THREAD

**Issue by RigorMortis13** [McJty/RFTools#546]
Im playing on a Unstable 1.8 Server.
Useing the **Advanced Charged Porter** to a properly set receiver sometimes **kills player** instantly. All conditions (Energy/free space etc.) had been matched. This issue might be connected to another issue: the porter doesnt identify the receiver name anymore while the number of the receiver is still shown. Replaceing the receiver seem to solve the problem fo a while. I didnt checked if the ownership of the receiver is getting lost like for the builder (see the other issue). 

_PS: great mod - one of the best in ftb :) . love it a lot._  
_Greetings Rigor_

**Comment by McJty** [comment]
The receiver keeps having enough power? What message do you get when the player dies? Is the receiver in the same dimension?

**Comment by RigorMortis13** [comment]
It got enough energy and is in the same dimension. The message i get is ~: not enough energy or location obstructed (but both is not matching). Happend frquently and i checked the power and other conditions more than one time.

**Comment by McJty** [comment]
Can you show a screenshot of the receiving end? With the mouse looking at the receiver?

**Comment by RigorMortis13** [comment]
here is a screenshot.
http://s33.postimg.org/76htym127/2016_05_25_20_05_38.png

**Comment by McJty** [comment]
I think that screenshot is the wrong link. It is not working

**Comment by RigorMortis13** [comment]
updated the screenshot. hope its valid.

**Comment by McJty** [comment]
yes it is valid but I have no clue what is wrong...

**Comment by McJty** [comment]
Cannot reproduce and old version of Minecraft
