### ISSUE TITLE
Client Crash when being present in a dimension with a huge shield

### ISSUE THREAD

**Issue by condensedapple** [McJty/RFTools#548]
My friend created a shield projector with ~31k blocks on my hosted vserver (not that bad, 8gig ram, SSD) running a custom modpack. After he activated the shield projector, he crashed to title screen (the server did not, no error message in console), and everybody else does if someone joins the dimension with the sield projector. Luckily, there are mainly afk farms for various things, and if someone is stuck in that dimension, I can TP them out immediately after they joined. Every other dimension works fine, no additional server lag, even though the shield projector is chunkloaded. Everybody who is playing on the server has a pretty stable connection. Here is the error message in the client-log: https://gist.github.com/condensedapple/336d52263656b2e104855afd25065b19
In SP, I can create any shield I want, and it works, like everything in your awesome mod, like a charm. 

EDIT: using the latest 1.7.10 version

**Comment by McJty** [comment]
Yes, this is a known problem. In the 1.9.4 version of RFTools this finally got solved but it is hard to backport that solution to 1.7.10 really. The issue is that the shield is so big that it overflow the packet size for sending from server to client

**Comment by condensedapple** [comment]
Thanks for the quick answer! Does removing the Shield Projector via MCEdit help?

**Comment by McJty** [comment]
yes that should fix it

**Comment by condensedapple** [comment]
I will try this...

**Comment by condensedapple** [comment]
a bit late, but after removing the Shield Projector and (not necessarily, but recommended if you dont want to have 30000 blocks lurking around) the Shield Blocks everything works again!
