### ISSUE TITLE
Overworld rain causes sun to disappear in Time Noon dimension

### ISSUE THREAD

**Issue by Zarkov2** [McJty/RFTools#550]
RFTools 4.32 (1.7.10 FTB Infinity Evolved 2.50 normal mode)

I created a desert biome void dimension and included a Time Noon dimlet. While there is rain in the overworld, the sun disappears within the created dimension. It doesn't get dark enough to cause mob spawns, but solar panels stop generating power. When the rain stops (for instance when sleeping) the sun immediately reappears in the created dimension.

The dimension was not created with any weather dimlet, using black for sky, clouds and fog.

**Comment by McJty** [comment]
That's actually not a bug but this is normal behaviour. Only the time is controlled with Time Noon. You also need wather control to make sure it is always clear
