### ISSUE TITLE
Clicking buttons opens screen GUI

### ISSUE THREAD

**Issue by hypernova1912** [McJty/RFTools#551]
As the title states, whenever I click a button on a screen, instead of actually working, it opens the screen GUI. I feel like I'm just doing something stupid, but it just won't work. Is there an item I need to use, or is it a bug, or what? Redstone modules verify the button press did nothing. RFTools 4.23 on FTB Infinity Evolved.

**Comment by McJty** [comment]
You need to use left-click. Not right-click
