### ISSUE TITLE
EnderIO conduits and Modular storage crash

### ISSUE THREAD

**Issue by BrokenHearted2** [McJty/RFTools#552]
Getting this when trying to extract from modular storage with EnderIO item conduits, Using 1.9.4-4.50. It doesn't CTD but goes to the server screen. [server log](http://pastebin.com/D9NTD1vF)

**Comment by McJty** [comment]
This looks like a bug in EnderIO which seems to have an unwanted hard dependency on The One Probe

**Comment by BrokenHearted2** [comment]
Ok sorry I saw the mcjty/theoneprobe/network/NetworkTools and figured that was the cause.

**Comment by McJty** [comment]
yes, but that wouldn't have made it an RFTools bug either as class is part of The One Probe (which is another mod still). So in any case, this is the wrong spot

**Comment by McJty** [comment]
Ok, turns out it was a bug in rftools after all. Fixed in next upcoming release (version 51)
