### ISSUE TITLE
Freeze when entering new dimension

### ISSUE THREAD

**Issue by RaineAndrews** [McJty/RFTools#553]
I created my first dimension, but when I entered it, it froze my entire computer.  Now I play the save, because Minecraft hangs on loadup (presumably because I'm in the dimension now).

**Comment by McJty** [comment]
More information please. What version of RFTools? Also can you give me the log?

**Comment by RaineAndrews** [comment]
Is a log generated if a crash doesn't occur?

**Comment by McJty** [comment]
yes sure. There is always a log in your minecraft instance folder

**Comment by RaineAndrews** [comment]
[FML latest log.zip](https://github.com/McJty/RFTools/files/296891/FML.latest.log.zip)

Its too large to pastebin.  Is this what you need?

Its the latest 1.9 build (4.23beta40)

**Comment by RaineAndrews** [comment]
Is the dimension folder the name I gave the dimension in game?

**Comment by McJty** [comment]
Hmm you should really try to upgrade to 1.9.4. Many fixes have been done to forge and other mods in that version

**Comment by RaineAndrews** [comment]
I'm sorry, I meant the 1.9.4 build :(

**Comment by McJty** [comment]
Cannot reproduce and retry in 1.10.2
