### ISSUE TITLE
Sometimes builder works without redstone signal

### ISSUE THREAD

**Issue by MrRiegel** [McJty/RFTools#554]
At least with this setup

![2016-06-04_11 48 38](https://cloud.githubusercontent.com/assets/13290261/15798933/495986c4-2a4b-11e6-8acf-47c0db12bc83.png)

If there is a log a redstone signal is given.
But the builder keeps running and breaks the sapling.

**Comment by McJty** [comment]
What are the settings of the builder? On ForgeCraft 2 I did something similar but I used a piston to move the tree up as soon as it had grown so that the sapling was always out of reach of the builder

**Comment by MrRiegel** [comment]
keep running with redstone signal.
I fixed it by breaking the lowest log with an usual block breaker
