### ISSUE TITLE
[Feature/Enhancement] Builder block quarry 

### ISSUE THREAD

**Issue by th4umiel** [McJty/RFTools#555]
It would be nice if you could add an option (maybe in the config) in order to use cobblestone instead of dirt as a replaceable block for the builder when it works as a quarry. 
I feel it's necessary when I mine in a mining dimension (like one of yours or the Aroma1997 one) and I don't want to leave big holes in the ground (and replacing with dirt isn't a good option, considering that the terrain is grass/dirt blocks everywhere). I hope I explained myself (english is not my native language). 
Thanks in advance! :-)

**Comment by McJty** [comment]
Config option added for next release

**Comment by ghost** [comment]
Suggestion: Would consider providing an in-game UI for this option?  

It would be great if it enabled the default block for the dimension(Overworld = Stone, Nether = nether rack, End = End Stone, etc.) to be the replacement.

**Comment by josephcsible** [comment]
@Sorbe That would be quite overpowered unless #1419 were also implemented.
