### ISSUE TITLE
Too many dimensions error.

### ISSUE THREAD

**Issue by UnfoundHopes** [McJty/RFTools#556]
I admit I am completely new to this modpack but no matter how many or how few dimlets I use (even when following the listed dimension guides here) when I place the Realized Dimension Tab into the Dimension Builder I am given the Too many dimensions! message.  I don't know exactly what I am doing wrong here...  

If it matters at all I am using the modpack through the FTB Skyblocks Evolved modpack.

**Comment by McJty** [comment]
Are you on a server? Then your server admin has configured RFTools with a maximum number of dimensions per player

**Comment by UnfoundHopes** [comment]
I am not on a server but I suppose that could still be the problem?  I will have to try and find how to change that...

**Comment by McJty** [comment]
You can find the setting for this in the rftools config. MaxDimensionsPerPlayer or something

**Comment by douglasg14b** [comment]
Is this configurable via roles or by player in some way? Say you want some players to have more possible dimensions than others.
