### ISSUE TITLE
[1.9.4] Builder Support Block can be mined with silk touch

### ISSUE THREAD

**Issue by tommyTT** [McJty/RFTools#557]
When I activate the preview mode for the builder it shows the support blocks. They are solid and I can't pass through. If I break the support blocks with a normal pick it vanishes. If I use it with a silk touch pick, I get the block. I think this might not be intentional and the support blocks should not be solid for player, at least.

Versions:
Forge 12.17.0.1948
RFTools 1.9.4-4.51
McJtyLib 1.9.4-1.8.7

**Comment by McJty** [comment]
Fixed next release
