### ISSUE TITLE
Recovering Lost Dimensions.

### ISSUE THREAD

**Issue by PiggyWhiskey** [McJty/RFTools#56]
I've created a dimension with only the Void Dimlet, and moved everything in there. However I died and can't get back.
I've tried to recreate the same Dimensional Tab to get back, but after 4 attempts, its not working.
Is there a reliable way to find out what dimension values were used? or to get a Dimensional Tab again?

**Comment by McJty** [comment]
One cheaty way is to use the creative 'teleporter probe' to teleport there.

In that dimension you can then /rftdim info which will show you a string from which you can get the id's of the used dimlets.

**Comment by McJty** [comment]
BTW, another non-cheating way to get back is to make a matter transmitter from the overworld and teleport back to your dimension.

**Comment by PiggyWhiskey** [comment]
Not quite possible. The Dimensional Tab ram put of power in this situation.

**Comment by McJty** [comment]
Yes but you can power it again if you create a new dimension tab with the same dimlets. If that's what you mean at least.

**Comment by McJty** [comment]
Closing this because I think there are solutions for this problem. In the last version of rftools you can also make a phased field generator to temporarily go to an unpowred dimension.
