### ISSUE TITLE
Support blocks

### ISSUE THREAD

**Issue by jaydog175** [McJty/RFTools#564]
is there a way to make the support blocks disappear? i set down a quarry and found out it would go over my base but now the support blocks are still there..

**Comment by McJty** [comment]
They should go automatically if you disable the 'support' button in the builder or if you break the builder. Doesn't this work? In that case exactly what did you do and what version of RFTools?

BTW, right clicking will remove a bunch of them at once

**Comment by jaydog175** [comment]
ok yeah i disabled the support button and that didnt work and ive moved the builder and drained it of energy but they still were there but the right clicking worked

**Comment by McJty** [comment]
What version of RFTools and MC?

**Comment by McJty** [comment]
Lack of info

**Comment by wkyle** [comment]
I'm getting this right now on a server. Minecraft 1.10, Direwolf 20 modpack. RFTools version 1.1x-5.75. Tried breaking builder, toggling preview. Support blocks persist. They're staying within the boundaries of a structure but disappearing outside of the structure.

**Comment by Fuxy22** [comment]
@McJty that right click tip on the support block saved me a lot of hastle thanks.
I'm using the Direwolf 20 Minecraft 1.10 pack and it seems in order to re produce it you just need to enable support and walk away from the builder.

Probably far enought from it to get unloaded?

**Comment by Paxination** [comment]
Still have this problem and clicking them isnt an option as im trying to fill in the areas around my underground base.  latest version of the dw20 modpack, minecraft 1.12.2

I dont think its because its being unloaded as mine remained loaded.  I have a chunk loader near it keeping a 6 chunk radius around it loaded.

didnt matter if the support blocks were outside or inside the loaded chunks, they all stayed

**Comment by McJty** [comment]
I still don't know what causes this and if the builder looses track of them then there is no automatic way to remove them I'm afraid.

**Comment by Paxination** [comment]
Restarting the server doesnt do anything either.

How about adding a button in the builder that will scan the area that is defined and remove them if it finds them at no cost?

Or how about a command to do so?

Or have it when its scanning at all to have it automatically remove any it finds during the scan as its working?

**Comment by Paxination** [comment]
I think pulling the cards out while support is turned on is whats doing it.  Will test once i can get rid of whats here.  Also have a theory that a filter card set on whitelist with just the support block in it in a builder with a quarry card might get rid of them as well.

**Comment by Paxination** [comment]
quarry card or void card will not remove them either

**Comment by sanomi78** [comment]
Not sure if this is still relevant - but sleeping on top of the support blocks with a sleeping bag removes them

**Comment by ghost** [comment]
> Not sure if this is still relevant - but sleeping on top of the support blocks with a sleeping bag removes them

It works.... but why

**Comment by McJty** [comment]
Just right clicking them will also remove them. No need to go to sleep on them :-)

**Comment by ALPolizzi** [comment]
If SupportBlock.removeBlock() checked the diagonals of blockPos for other SupportBlocks it would help tremendously in removing bugged support blocks in curved structures.

**Comment by SplenectomY** [comment]
This happens if you activate the preview, change the shape to something else or move it/change dimensions, and then reactivate the preview. Confirmed on 1.12.2, FTB Revelations 3.5.0, rftools 1.12 7.73

**Comment by JannisPfeiffer** [comment]
Luckily a server restart did fix my problem, fyi. Playing on FTB Presents Direwolf20 1.16

**Comment by JannisPfeiffer** [comment]
Maybe also try to reselect the area with the original shape/ quarry card and toggle the preview twice. This should revalidate the area and update and remove all blocks properly :)

**Comment by McJty** [comment]
I fixed this bug in 1.16 and 1.18
