### ISSUE TITLE
[1.9.4] Cannot walk on Solid Shields

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#565]
When trying to walk on Solid Shields the client will think you're falling through

Video example: https://youtu.be/Z9OAdfVr0VE

**Comment by McJty** [comment]
What version of RFTools? Can you also show how the shield is configured?

**Comment by Xiaminou** [comment]
rftools-1.9.4-4.60

![2016-06-14_16 53 31](https://cloud.githubusercontent.com/assets/8670392/16047505/98579a9c-3250-11e6-9c20-067bb010333d.png)

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed next release (today)
