### ISSUE TITLE
game crashed after i put down a storage modual and now game crashes on loading 

### ISSUE THREAD

**Issue by 5kedone** [McJty/RFTools#566]
i have attached crash log 
[crash-2016-06-14_16.58.01-client.txt](https://github.com/McJty/RFTools/files/314370/crash-2016-06-14_16.58.01-client.txt)

**Comment by McJty** [comment]
You must update Deep Resonance. The version you have is not compatible with McJtyLib 1.9.0

**Comment by 5kedone** [comment]
So sorry due I checked for updates today even for them but did not even think of deepres as did not think one would affect other like that lol
