### ISSUE TITLE
Storage Scanner Search box not capturing input

### ISSUE THREAD

**Issue by choekstr** [McJty/RFTools#568]
When using the search input field in the storage scanner on 1.9.4 (FTB Unstable), NEI/JEI hotkeys for "r" and "u" are picked up while typing.  If the mouse happens to be over an item the recipe or usage show up instead of inputting in the search box.  I would expect rftools to capture the input so any text could be entered despite the location of the cursor.  

An example can be seen [here](https://youtu.be/O3KrALNmbxQ?t=805).

**Comment by McJty** [comment]
Fixed in next release of mcjtylib
