### ISSUE TITLE
[1.9.4][RFTDimensions] Client crash: java.lang.ArrayIndexOutOfBoundsException: -129718

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#569]
client crashed when first entering a new dimension, server did not.

Crash Report: http://pastebin.com/cTafTSSa

**Comment by McJty** [comment]
Hmm that doesn't say much. What happens if you try to enter again? What about other dimensions?

**Comment by Xiaminou** [comment]
Nothing happens, as for other dimensions I don't know yet my server crashed before I got around to make my void world dimension.

**Comment by Xiaminou** [comment]
Same crash when creating a void dimension (digit dimlet 1 + void dimlet):

Crash Report: http://pastebin.com/wLErdUpS
Client Log: https://drive.google.com/open?id=0BxQWn9jKBIAJR3JiTEo5eUplSzQ
Server Log: https://drive.google.com/open?id=0BxQWn9jKBIAJanVTUUo4ZWtMQVE

**Comment by Xiaminou** [comment]
I just made a couple of Dimension and the last one did not crash my client, looks like it's doesn't happen every time like I though:

![2016-06-23_15 53 31](https://cloud.githubusercontent.com/assets/8670392/16305616/ee7319e0-395a-11e6-9c5a-72857afeaf02.png)
![2016-06-23_15 53 55](https://cloud.githubusercontent.com/assets/8670392/16305617/ee768274-395a-11e6-9e08-44916200f76e.png)

Any news on this?

**Comment by McJty** [comment]
That's a really weird crash. Not sure what is going on. I'll try to investigate this

**Comment by Xiaminou** [comment]
Just got it when entering a Dimension I had previously visited:

Crash Report: http://pastebin.com/GWmn88i3
Log: https://drive.google.com/open?id=0BxQWn9jKBIAJQ1dxS1l5RmVVcmM

**Comment by McJty** [comment]
Probably fixed in 1.10.2
