### ISSUE TITLE
Crash attempting to build dimlet dimension - Factorization

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#57]
Hey there.

I received the following crash when attempting to build a blank dimlet dimension. It seems to be an x-mod conflict with Factorization in some form.

I'm not sure if there is anything you can do about this on your end or not so I have also reported it with neptunepink.

http://pastebin.com/phD55KMZ

If you need any further information just let me know.

**Comment by McJty** [comment]
Hmm, that looks a bit weird but indeed I'd like to hear what the Factorization people think about it

**Comment by sciguyryan** [comment]
Unfortunately it made it completely impossible to load up the generated dimension. Trying to create a new one didn't work either. I had to go into the world files and delete a couple of dat files to allow a new one to generate.

That of course didn't help either since the issue above simply reoccurred.

**Comment by sciguyryan** [comment]
Seems like neptunepink has posted an update to Factorization that is meant to resolve this. Closing for now. if the issue persists then I will re-open it.
