### ISSUE TITLE
[1.9.4] Server crash: conflict with ExtraUtils2? (java.lang.UnsupportedOperationException)

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#570]
Looks like there was a conflict with ExtraUtils2 when the Builder (Silk Quarry) attempted to mine a block:

Crash Report: http://pastebin.com/5s1qPRBJ

Extra Utilities Issue: https://github.com/rwtema/extrautilities/issues/890

**Comment by McJty** [comment]
This is a bug in Extra Utilities. Better make a ticket there

**Comment by Xiaminou** [comment]
I was doing just that, but you're just too fast :p

**Comment by McJty** [comment]
Scratch that. It is my bug... I will fix it in next release
