### ISSUE TITLE
[1.9.4] [bug] NPE ticking player exception modular storage

### ISSUE THREAD

**Issue by tyler489** [McJty/RFTools#572]
Im using knoxz testpack on the curse launcher
Its a pack where we test all 1.9 mods and find bugs

Got this crash today

 http://pastebin.com/qYGKP3xc
Not sure what i did i was breaking some blocks from exu2 and i think i may have put the module storage in my offhand

**Comment by tyler489** [comment]
Possibly related #537

**Comment by tyler489** [comment]
#475 #503 
My bad didnt see thesei was getting shot by skeletons so that may be it

**Comment by McJty** [comment]
Will be fixed next release
