### ISSUE TITLE
XP dropping from Builder causing issues.

### ISSUE THREAD

**Issue by Kris1432** [McJty/RFTools#575]
The builder now drops xp orbs due to the new BlockHarvest event, which when left is creating an IMMENSE amount of Orbs, bringing me down to 2 fps and crashing the server: http://pastebin.com/LmiK9pG9

You will need to make it so xp doesn't drop from the builder because its causing issues.

Latest Version in 1.9.4

**Comment by McJty** [comment]
I cannot reproduce this. the BlockHarvest event is from forge and normally shouldn't cause XP orbs to drop. Do you happen to know what ore is doing this?

**Comment by RealGrep** [comment]
I wonder if it's not caused by Fortune Ores. I know I've been quarrying plenty in Forge version 1965 with no such issues. Perhaps trying without Fortune Ores on to see if that helps?
