### ISSUE TITLE
[1.9.4][Suggestion] Solid Top/Bottom Dome

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#578]
I like living in void worlds, and I am now using the Builder Block to automatically build my platforms. I usually go for a spherical shape to produce a kind of floating island.

For this I use Solid Sphere and then remove the top part, which is a two parts process.
I am proposing that Solid Top/Bottom Dome be added to the Shape Card's shapes to make it a one part process.

![2016-06-20_18 48 01](https://cloud.githubusercontent.com/assets/8670392/16202944/4011ca48-3718-11e6-8ce1-3bdb61b294d6.png)

**Comment by McJty** [comment]
Will be in next release
