### ISSUE TITLE
[1.9.4] - Ticking block entity

### ISSUE THREAD

**Issue by Lazarix** [McJty/RFTools#579]
Compatibility issue with Ender IO:

https://gist.github.com/Lazarix/a69a9c61033bd0eaeb154053ea043c68

**Comment by McJty** [comment]
We need more info. Both mods are being used together in my LP as well as on ForgeCraft with no issues. A full log can help

**Comment by Lazarix** [comment]
Full log:

https://gist.github.com/Lazarix/650d545278a06adff6e88f684af48ccb

**Comment by McJty** [comment]
Apparently it is a problem with Mekanism. The issue has been reported to them
