### ISSUE TITLE
[1.9.4][RFTDimensions?] Server crash while in the mining world

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#585]
I recently integrated Mekanism in my modpack and soon found out that my mining world somehow dropped my FPS down to 1. While I am not convinced that it is Mekanism (I update mods daily, needs further testing), I think it's too much of a coincidence.
Now that was only client side until today, I stayed a bit longer than usual (as I have decided to build a new one and hopefully get more FPS) in my mining world and the server ended up crashing with this weird crash report:

Crash Report: http://pastebin.com/h3qxVYUV

**Comment by McJty** [comment]
Hmm... Did you report this to mekanism too? I see mekanism in the crashlog but not rftools dimensions

**Comment by Xiaminou** [comment]
I wasn't sure if Mekanism was involved, but I will report it to them now.
