### ISSUE TITLE
Enderman ignore Environmental Controller module

### ISSUE THREAD

**Issue by cj89898** [McJty/RFTools#588]
Enderman still teleport even with my environmental controller set up and powered. Here is a screenshot of my controller: https://gyazo.com/c509d878a0c3573b7e5c7bb659150aef

Minecraft Version: 1.9.4
RFTools Version: 1.9.4-4.65
Forge version: 1.9.4-12.17.0.1968

**Comment by McJty** [comment]
You have configured your controller wrong. The mode is set to 'WL' (whitelist). That means it will only work for whitelisted players. You must set it so that it affects hostile mobs. Then the enderman will not teleport
