### ISSUE TITLE
[1.9.4] [4.66] Elevators attempt to function when the bottom isn't powered.

### ISSUE THREAD

**Issue by zlyfire** [McJty/RFTools#589]
I have three elevators set up, previously two: a ground floor and a second floor. I added a basement floor, but kept the ground floor as the powered elevator block. The button module on the screen indicated that all was well, but when I hit the button to move the elevator from the second floor to the ground floor, it moved down, then failed to reform as a block, and continued making the "moving elevator" sound.
Perhaps elevators could be changed to allow any elevator block to be the powered source, or prevent the blocks from becoming an elevator platform at all if the bottom block is not powered?

**Comment by RigorMortis13** [comment]
I had similiar Issues while not powering the elevatorblock. There had been a soundloop and the elevatorplatform moved a single time but stoped working afterwards and created indestructable blocks afterwards.
Tested it in 1.8.9 Ftb Unstable, 1.9.2 Dannys Sirenus Pack, 1.9.4 Ftb Unstable. Allways the same Issue and reproducible :-/
And to be fair i didnt even know that the bottomlayer elevator blok or any of them needed power. Couldnt find a tooltip/Wiki topic about that. 

Oh not to forget your elevator is one of the best ideas/mashines in modded minecraft. Asolutly love it ! :)

greetings Rigor

**Comment by McJty** [comment]
Will be fixed next release
The fact that the bottom elevator block needs power is documented in the in-game manual
