### ISSUE TITLE
Dimlet Workbench: Infuse Status lost when broken while extracting dimlets

### ISSUE THREAD

**Issue by Pandemoneus** [McJty/RFTools#59]
In the Infinity 1.2.0 modpack, when breaking a Dimlet Workbench with a pickaxe while it is extracting a dimlet, it loses all infused shards (it returns as an item without the infused tooltip, when you put it into the infuser it then shows 0%).

**Comment by McJty** [comment]
This is not really a bug and happens with all rftools machines that are infused. But perhaps I should make sure that this does not happen as it can be somewhat annoying.

**Comment by McJty** [comment]
Fixed, in the next version of rftools all machines will remember ALL their settings (including infusing bonus) when breaking them with a pickaxe even.
