### ISSUE TITLE
[Request] Environmental Controller/Dimension Buff HUD Config

### ISSUE THREAD

**Issue by Mohron** [McJty/RFTools#591]
Could we get a config option, probably under the environmental controller, to move the buff icons on the screen?  Something similar to how you can move TOP through the four available config options (right/left-x/y).

**Comment by McJty** [comment]
Do /rftcfg buffs -1 -1

That disables those icons

**Comment by Mohron** [comment]
That's not a known command in 1.9.4.

**Comment by McJty** [comment]
Hmm... it should be. What does /help say? Are you sure you typed it correctly? What exactly did you type?

**Comment by Mohron** [comment]
I copied it exactly. /rftcfg buffs -1 -1

![](https://s32.postimg.org/wlw7xmq7p/RFTHelp_CC.png)

**Comment by McJty** [comment]
Yes, you are right. I messed up there. Will fix next reelase

**Comment by McJty** [comment]
Fixed next release
