### ISSUE TITLE
[1.9.4] Quarry card 

### ISSUE THREAD

**Issue by jsmart17** [McJty/RFTools#594]
1) The tootips for the voids are off center
2) The void setting on cobble at least doesn't seem to work
3) the non clearing upgrade turns tall grass/flowers to dirt

**Comment by McJty** [comment]
2) with a silk touch, fortune or normal card? Note that voiding happens *before* quarrying and you usually don't have a lot of couble in the world
3) yes I know. Have to think on how to handle that

**Comment by jsmart17** [comment]
It is used with the fortune card

**Comment by McJty** [comment]
Cannot reproduce and not maintaining 1.9.4 anymore
