### ISSUE TITLE
[1.10.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFTools#597]
Forge: 2002
Mod: mcjtylib-1.10-1.9.2.jar

also: rftools-1.10-4.67.jar & rftoolsdim-1.10-4.30beta44.jar

Crash report: http://pastebin.com/raw/V3mEvFGL

**Comment by McJty** [comment]
I will check it out. Very strange though

**Comment by RealGrep** [comment]
Yep, same here. Worked ok with the previous version of mcjtylib, but the mcjtylib-1.10-1.9.2.jar one causes that error on startup. I have the same versions as kwpugh. From my console:

http://pastebin.com/n1rPkcC4

**Comment by McJty** [comment]
I think I know what's wrong

**Comment by McJty** [comment]
Should be fixed in McJtyLib 1.9.3. Reopen if it is still not working please.

**Comment by kwpugh** [comment]
Appears to work fine.   Thank you very much and thank you for making great mods!
