### ISSUE TITLE
Liquid Absorber: Progress lost when placed over "air"

### ISSUE THREAD

**Issue by Pandemoneus** [McJty/RFTools#60]
In the Infinity 1.2.0 modpack, I absorbed liquid cryotheum. Then I broke the liquid absorber and placed it somewhere else, but not over a liquid. WAILA then showed that all progress was lost (the tooltip was missing) and when I absorbed some more liquid cryotheum, it was back at 1%.

**Comment by McJty** [comment]
Ok, will look into this.

**Comment by McJty** [comment]
Fixed in next release.
