### ISSUE TITLE
[1.10.2] Remote Storage dimension access button has wrong tooltip

### ISSUE THREAD

**Issue by tommyTT** [McJty/RFTools#600]
When you look into the remote storage block you have the option to toggle on or off if there should be access to it if you are in another dimension. When I want to have that, it tells me "Cross-dimension access enabled" which is correct. When I unselect it, the title says "Inter-dimensional access only", which means basically the same thing. This should be "Inner-dimensional access only". To further simplify it, I would change it to "Cross-dimensional access disabled" or something.

Minecraft Version 1.10.2
Forge 12.8.0.2004
RFTools 1.10-4.67

**Comment by McJty** [comment]
Fixed next release
