### ISSUE TITLE
[1.10.2] No item tooltips in Storage Module Tablet

### ISSUE THREAD

**Issue by tommyTT** [McJty/RFTools#601]
The items in the storage module tablet don't show their tooltips when hovering. In the modular storage I can see them fine.

Minecraft: 1.10.2
Forge: 12.8.0.2006
Mods:
  mcjtylib-1.9.4-1.9.1
  rftools-1.10-4.67

http://paste.ee/p/KY4UC

**Comment by McJty** [comment]
I can reproduce this. No idea why yet though

**Comment by McJty** [comment]
Fixed next release
