### ISSUE TITLE
[1.7.10] [RFTDimensions] [Question] Hiding a realized dimension for a quest

### ISSUE THREAD

**Issue by rockobonaparte** [McJty/RFTools#603]
I'm trying to explain how to access RFTools dimensions in the quest book I edit for my tutorial modpack. I have hit a snag with trying to give the player a prepared dimension. The progression is that they work towards build a sample dimension, and then I give them a specific, realized dimension. It is set up in the save they start with and has creative power. I am hoping that given the realized dimension tab to the existing dimension, they could enter it into their builder to power it, dial into it, and work from there. There's already a matter receiver there for them in the realized dimension.

The problem is I don't want them to know about that existing receiver in the dimension prematurely, but I still want them to be able to beam into the dimension once they have the realized dimension tab. Is this kind of thing even possible?

Can you think of any ways I might be able gate access to that dimension until they get the realized dimension tab? I don't expect to gate them if they go through somebody else's matter transmitter on a multiplayer server though.

**Comment by McJty** [comment]
Hmm, one way that might be possible is if you (through HQM or something) only place the matter receiver in that other dimension at a certain point. Not sure if that's possible though

**Comment by rockobonaparte** [comment]
Ehh I guess what I'll do then is just tell them to go to the conspicuous dimension showing up in their dialing device for the quest right after they build that. I suppose that makes for a better intermediate step than having them build dimensions first and then feed them the sample dimension.
