### ISSUE TITLE
1.9.4 Effective bonus from infusing endergenic generator

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#609]
Not sure if this is a bug or not but it seems like the bonus we get from FULLY infused all four of the endergenic generators (using the setup on youtube I believe you made?) is less than only around 40%. 
For intance with just the uninfused generator, I am getting a bit over 8000 rf/tk, but when maximized infused (for example, using the creative wand), I am only seeing 11500 rf/tk or so. 
Consider it takes 16 full stacks of shards to do this, its not that good of a bonus. 
Shards are pretty rare without heavily investing into dimensions, at least at the point where I am, it seems more convenient (if not cheaper) to build a second endergenic generator setup. 

Otherwise, the endergenic generator really kick ass, keep up to good work!

**Comment by McJty** [comment]
I will increase the benefit a little but not too much as once you get into RFTools dimensions it is actually not that hard to get shards.
