### ISSUE TITLE
Liquid Absorber: Also absorbs flowing blocks

### ISSUE THREAD

**Issue by Pandemoneus** [McJty/RFTools#61]
In the Infinity 1.2.0 modpack, the liquid absorber also takes flowing blocks and counts them toward the progress. I am not sure whether that is intended. Tried this with gelid cryotheum.

**Comment by McJty** [comment]
Hmm, gelid is a bit special as the source blocks actually follow gravity rules. Can you confirm this with any other fluid? I couldn't personally.

**Comment by Pandemoneus** [comment]
I just tried it with lava. Works as well.
I also placed the liquid absorber over a 2x2 pool of lava in a corner. It wouldn't absorb the whole pool, only the corner the absorber is in and the opposite corner. If you remove that absorber and place it at the same position again, you can absorb lava again. In fact, you can absorb an infinite amount of lava like that, you only need the 2x2 pool.

**Comment by McJty** [comment]
Ok, that is *not* the intention. Will try to fix that :-)

**Comment by McJty** [comment]
Fixed in next release.
