### ISSUE TITLE
[1.10.2] Compatibility with Actually Additions Laser Relays and PowerCells

### ISSUE THREAD

**Issue by b0bst3r** [McJty/RFTools#610]
RFtools 5.02
ActuallyAdditions-1.10.2-r49

Image - http://i.imgur.com/FLZ6N2W.png

-- Explanation 
To the left we have an AA leaf generator (breaks leaves to create RF) on top of that leaf gen is a Laser Relay (wireless RF transmitter).  To the right we have one of your PowerCells (doesn't matter which tier this happens with them both) which contains no cards and is not linked to any other Powercell.  On top of this powercell is another Laser Relay.  The powercell is set to Input.

-- What happens
When the Laser Relays are connected the power gets wirelessly transferred across from the leaf generator into the powercell but the power then gets eaten up and the powercell ends up empty.  There is nowhere for the power to go except back out through the Laser Relays, but that shouldn't happen as the cell is set to Input.

The same setup but using an EnderIO capacitor bank and the RF is kept in the cap bank it does not go back out.

According to Ellpeck (AA modder) here http://minecraft.curseforge.com/projects/actually-additions?comment=107 this is your issue?

**Comment by McJty** [comment]
The PowerCell *is* handling this correctly. RF is based on a 'push' RF system. Not an extraction based system. You should never etract RF manually out of machines. Instead RF should be pushed into you. That's how RF generators and the powercell (in output mode) work. They push RF to machines around it.

The extractEnergy() is meant for internal usage in most cases.

So in summary, not a bug in RFTools. Don't extract energy from it please.
