### ISSUE TITLE
[1.10.2] Exception Placing PowerCell next to EnderIO Capacitor Bank

### ISSUE THREAD

**Issue by veirden** [McJty/RFTools#612]
Received the following exception when placing a Red PowerCell next to an EnderIO Basic Capacitor Bank.  Duplicated in a creative world with just these two blocks directly next to each other.  Reversing which block is placed first does not seem to change anything.

[http://pastebin.com/14VvP2fR](http://pastebin.com/14VvP2fR)

Forge: 1.10.2-forge1.10.2-12.18.0.2008

**Comment by McJty** [comment]
Did you also report to EnderIO?

**Comment by McJty** [comment]
I will add some protective code in RFTools but I think enderio shouldn't call this code from rftools

**Comment by veirden** [comment]
I will also report to EnderIO.  Just figured I would start here first.

**Comment by veirden** [comment]
I was a version behind in EnderIO.  Updated to EnderIO-1.10.2-3.0.1.64_beta and exception has been fixed.
