### ISSUE TITLE
Forcefield error

### ISSUE THREAD

**Issue by SkylordMilkyway** [McJty/RFTools#613]
So, I was messing about with force fields in Direwolf20 on my server, and came upon an error with reading packet 53.
https://gyazo.com/35754e3b54b01a7847d359dc74bf4af3
This issue wasn't happening before until after I placed the and activated to forcefield doing a large area. 
I'll have to go test in 1.10 and see if it reoccurs there.

**Comment by McJty** [comment]
yes, known problem in the 1.7.10 version of RFTools. If you make the shield too large you get this problem. In later versions this no longer occurs. Best would be to try to remove the shield projector using mcedit or something

**Comment by SkylordMilkyway** [comment]
Alright, so if I were to update RF tools would that work in theory? Or was it not fixed until 1.8?

**Comment by SkylordMilkyway** [comment]
Updating RFtools also works

**Comment by McJty** [comment]
Ah yes, if the shield is not too big then that's a solution as I partially solved that problem to allow some bigger shields. Forgot about that
