### ISSUE TITLE
No Dense Ore Dimlet

### ISSUE THREAD

**Issue by Rnrn13** [McJty/RFTools#614]
Today I got the Dense Ores Mod and I was looking at the Rftools' dimlets to see if there we're dense ore dimlets - which there we're not. If you could add that it would be greatly appreciated.

**Comment by Rnrn13** [comment]
Also I'm using Rftools V 3.35 and McJty lib 1.4.0

**Comment by McJty** [comment]
RFTools uses the 'oregen' dimlet for that
