### ISSUE TITLE
[1.10.2] Silk Quarry doesn't move items to chest

### ISSUE THREAD

**Issue by c0rn3j** [McJty/RFTools#615]
After being turned on the quarry turns stuff into dirt but doesn't put it in chest, it just vanishes. Tried with chest and dimensional transceiver. Also I'd expect the block in front of quarry to be harvested too.

http://imgur.com/a/aKHc9

rftools-1.10-5.03.jar

Rest of the mods: 
http://pastebin.com/pS3DyxP8

**Comment by c0rn3j** [comment]
Alright I figured out that the output is on top. Could the quarry not work if there's no chest attached to it or, I'd prefer this, could you have the chest in any direction instead?

**Comment by McJty** [comment]
Weird. Without a chest on top (or bottom) it should not do anything at all.. I have to check that

**Comment by McJty** [comment]
The block in front of the quarry is not harvested. i.e. a 3x3x3 area with the builder in the middle is protected from harvesting

**Comment by McJty** [comment]
BTW, I can reproduce this bug

**Comment by McJty** [comment]
Will be fixed next version of McJtyLib (was a bug in that mod)
