### ISSUE TITLE
[1.10.2] Silk Quarry mines sideways spruce wood weirdly

### ISSUE THREAD

**Issue by c0rn3j** [McJty/RFTools#616]
http://i.imgur.com/CJqP3Nq.png

http://i.imgur.com/ovG3OQK.png

Placing the weird block puts down a normal spruce wood.

**Comment by c0rn3j** [comment]
Also happens with Dark Ore from EvilCraft. 
Mining both those items with Tinker's construct pickaxe with silk touch drops them normally.

**Comment by McJty** [comment]
Merging with ticket https://github.com/McJty/RFTools/issues/627
