### ISSUE TITLE
Inconsistent UI behaviour in modular storage

### ISSUE THREAD

**Issue by Arminius** [McJty/RFTools#617]
If I open up a modular storage block, the search bar is automatically selected. If I open up a storage scanner, which also has a search bar, I have to click on it before I can type. The search bar behaviour should be consistent between all blocks that have search bars in my opinion - either both blocks select it on opening, or none does. Otherwise, it just messes with expectations.

Personally, I'd prefer it if it wasn't selected - having the search bar selected prevents me from closing the window with my inventory key, even if I rebind it to something like tab.

**Comment by McJty** [comment]
Yes I know. It is a common critique. BTW, you can disable the automatic selection of the search bar for modular storage in the config

**Comment by McJty** [comment]
I changed the defaults for next release (will require deleting rftools.cfg to get the new defaults)
