### ISSUE TITLE
Issue with Crafter and Block ID's

### ISSUE THREAD

**Issue by jambaugh** [McJty/RFTools#618]
Using Version 5.03 for MC 1.10, along with ExtraUtils2 v1.0 for MC1.10

When using Crafter Tier II or III, with multiple recipes the crafter was "eating" blocks.  Specifically I was using it to in conjunction with ExtraUtilities2 to recursively compress cobble stone blocks.  I realized the single, double, triple, etc compressed cobble uses same block ID with "meta data" distinguishing the level of compression; e.g. #4370/0, 4370/1, 4370/2 ....  So the crafter used triple compressed in its inventory to make double compressed and so on, thinking it was 1-to-1 equivalent of single compressed cobble since they have same block id number.  It would be *really really great* if the crafter could be updated to use text based block ID's to avoid this issue or if we could toggle ignoring/considering the extra meta-data.

**Comment by McJty** [comment]
Hmm the crafter should look at block ID's. I have to check this. But can you confirm this also works with latest rftools + mcjtylib as some changes to inventory handling have been done

**Comment by McJty** [comment]
Ok, I found it. Will be fixed next release
