### ISSUE TITLE
Craft Absorbers with progress to reset it

### ISSUE THREAD

**Issue by Pandemoneus** [McJty/RFTools#62]
Instead of absorbers automatically resetting when they are placed on a new biome/block/liquid, maybe they should just do not do anything when they already have progress with a different biome/block/liquid. I suggest that we put them into the crafting window to reset them back to 0% progress or blank them, if we want to absorb something different.

**Comment by McJty** [comment]
Agreed. That's a good suggestion. I will see to it in one of the upcoming versions.

**Comment by McJty** [comment]
Fixed in next release.
