### ISSUE TITLE
[1.10.2][rftools-1.10-5.06] Bottom Screen Button does not work

### ISSUE THREAD

**Issue by nikkimas** [McJty/RFTools#620]
As written in the title, sometimes the bottom Button does not work. I Uploaded a YouTube video showing the bug: [https://www.youtube.com/watch?v=01Rp_ZjzMqQ](https://www.youtube.com/watch?v=01Rp_ZjzMqQ)

I hope that is enough to locate the problem.

**Comment by McJty** [comment]
Trying to reproduce. Without success so far

**Comment by McJty** [comment]
Ok, can reproduce now

**Comment by McJty** [comment]
Fixed next release
