### ISSUE TITLE
[1.9.4]Redstone Transmitters Not Changing Channels

### ISSUE THREAD

**Issue by Stuart74** [McJty/RFTools#622]
Have been trying to setup my endergens the way mcjty did in his youtube video 

https://www.youtube.com/watch?v=u0E1-qBH3i4

But all the redstone Transmitters wont change channels each time i place a new one down they all say channel 5 and when hovering over them with WAILA it says channel 0 

Endergens are fairly useless in 1.9.4 if these blocks do not work as advertised i am hoping its just me doing something wrong.

**Comment by ShadowDrakken** [comment]
I can't seem to get redstone transmitters/receivers to work _at_all_ in 1.9.4

When I place them down, they show channel 0. When I try to link them I get a message stating channel 1 has been created, however they still show channel 0. Hovering over them, WAILA briefly shows channel 1 before switching to showing channel 0.

**Comment by McJty** [comment]
Not doing maintenance on 1.9.4 since upgrading to 1.10.2 is so easy and there everything appears to be working

**Comment by Wrsaith** [comment]
i'm having this issues on the release for mc 1.12

**Comment by McJty** [comment]
To @Wrsaith please explain your setup and what you're trying to do
