### ISSUE TITLE
Dimension maintenance cost wrong

### ISSUE THREAD

**Issue by Pandemoneus** [McJty/RFTools#63]
In the Infinity 1.2.0 pack, I tried making a dimension using (in this order):
- Biome Deep Ocean
- Liquid Gelid Cryotheum
- Terrain Flat
- Controller Single

The Gelid Cryotheum dimlet has a maintenance cost of 20k RF/t according to the tooltip.
However, the fully created dimension has a specified maintenance cost of 200k RF/t (Note, it's x10!).
There's something wrong there.

**Comment by McJty** [comment]
Note that the cost can increase after creation due to random generated features. But 200kRF/t is a lot though. Can you tell me what the dimension was created with? i.e. shift-right click with the dimension tab and paste all the information you get here.

**Comment by Pandemoneus** [comment]
See this screenshot:
http://imgur.com/D5XRMFX

**Comment by McJty** [comment]
Ok, that doesn't look as if it should be that expensive. I will look into this and see what's the problem here.

**Comment by McJty** [comment]
Ah oops no. This is actually normal (although a bit excessive). Material and liquid modifiers cost 10 times more when used as a terrain modifier (as opposed to using them as a feature modifier like lakes or tendrils). The reasoning is that there is a lot more of it when used like that.

**Comment by Pandemoneus** [comment]
Ah. That should be mentioned in the manual. :)

**Comment by McJty** [comment]
Yes, and for that reason I will reopen this so that I can make the manual more clear. Thanks for reporting.

**Comment by Gideonseymour** [comment]
Oh, I'm working on the manual now. I can write that in.

**Comment by McJty** [comment]
Manual is updated for next release
