### ISSUE TITLE
Crash with the Powercell

### ISSUE THREAD

**Issue by canitzp** [McJty/RFTools#635]
This crash happenes one time at the client, while placing the powercell. After rejoining the Server everythings works fine.

Minecraft Version: 1.10.2
Forge Version: 1.10.2-12.18.1.2011
RFTools Version: 1.10-5.06

Crash: http://pastebin.com/3N12Js0h

An my Rarmor mod only call the getEnergy() method, so don't say it's my fault, please.

**Comment by McJty** [comment]
Could be a bug with the in world tooltips mod:

canitzp.rarmor.InWorldTooltips.showTooltipAtBlock

**Comment by canitzp** [comment]
I'm 100% sure vit isn't but it doesn't matter

**Comment by McJty** [comment]
Well the problem is that you call:     mcjty.rftools.blocks.powercell.PowerCellTileEntity.getEnergyStored(PowerCellTileEntity.java:447)
from client side and that's not legal since this information is not present client side. This must be done server side.
