### ISSUE TITLE
Void Dimensions

### ISSUE THREAD

**Issue by COLDF1R3** [McJty/RFTools#636]
Using the dimensions on a sky factory server creates nothing but a void world. Another thread under the YUNOMGM git said he found a fix in one of the configs about a blacklist of certain dimlets ive searched both the main.cfg and dimlet.cfg but cannot find anything referencing the terrain flat dimlet or anything terrain for that matter. Is there an option to enable worlds to not be a void world in any configs or is there another fix im not aware of?

RFTools Version: 4.23
Sky Factory 2.5.3

**Comment by sherkas** [comment]
Can you give us a dimlet example of what your trying to create?

**Comment by McJty** [comment]
In rftools config there is a 'voidOnly' option. Set that to false and it should be ok
