### ISSUE TITLE
Crash on item insert with Builder.

### ISSUE THREAD

**Issue by Ceruleann** [McJty/RFTools#642]
Hi McJty,

I have been having this crash with the builder on quarry. I tried to change the storage Modular Storage, vanilla chest or Iron Chest to no avail. Would you mind looking into it please?

See crash file attached.
[crash-2016-07-23_11.54.52-server.txt](https://github.com/McJty/RFTools/files/379509/crash-2016-07-23_11.54.52-server.txt)

**Comment by McJty** [comment]
Hmm weird. Can you give more information? Perhaps a screenshot?

**Comment by McJty** [comment]
Closing due to lack of info
