### ISSUE TITLE
[1.10.2] Wrench causes client crash

### ISSUE THREAD

**Issue by Tessellry** [McJty/RFTools#645]
MC: 1.10.2
Forge: 12.18.1.2011
RFTools Version: 1.10-5.06
http://pastebin.com/waKfEze9
Sneak right klicking doesnt pick up the machine and only right klicking causes an immediate crash every time no matter what machine is klicked at. The message is "shutting down internal server". Did this in singelplayer but it has happened for others 2 at the server Im on and they live abroad so it cant be just me.

**Comment by McJty** [comment]
Should be fixed now
