### ISSUE TITLE
[1.10.2]Crash on Rclicking a powered block protector with a SmartWrench

### ISSUE THREAD

**Issue by EtherG** [McJty/RFTools#647]
Forge: 2011
RFTools: 1.10-5.06
http://paste.ee/p/JuP6A
this is the log

edit: with rclicking any machine

**Comment by cryptrol** [comment]
Same crash here right clicking any rftools block.
Same forge, same mod version.

**Comment by McJty** [comment]
Will fix this soon. I know what the problem is
