### ISSUE TITLE
Massive lag with Endergenic generators

### ISSUE THREAD

**Issue by BootyToast** [McJty/RFTools#654]
I was scratching my head for hours trying to figure out what the source of my lag is and well, take a look for yourself.

While on: 
![2016-07-28_15 51 34](https://cloud.githubusercontent.com/assets/10050188/17227308/b36cafd6-54db-11e6-8693-8fc529384a72.png)

When turned off:
![2016-07-28_15 53 10](https://cloud.githubusercontent.com/assets/10050188/17227320/c02c61b2-54db-11e6-812a-76dbfd1b54d7.png)

**Comment by McJty** [comment]
More info would be nice. What version of RFTools for example?
Also in my world and also on FC1 the endergenic has pretty much been lag free. So not sure what would be causing that

**Comment by BootyToast** [comment]
RFTools 1.10-5.0.7. All I know is that it has nothing to do with the redstone but rather when the generators fire the pearls. I broke every redstone transmitter and receiver and really anything but the generators and the pearl injector. Fired a pearl manually from one generator to another and that's when the lag spike happened (immediately stopping once the pearl in the receiving generator was lost). Obviously I'm using a similar design to the one that you've built so I have no idea what causes this.

**Comment by McJty** [comment]
I may have an idea what is causing it and why it only affects some people. I guess you have a lot of other stuff (machines, C&B things whatever) in that same chunk? I'll try to fix it

**Comment by BootyToast** [comment]
Oh boy, you haven't seen Chisels & Bits until you've seen my base. And yes indeed, there are some machines around. It also may be worth noting that my generator setup is in two different chunks (I do have them chunkloaded though).

**Comment by McJty** [comment]
Ok, so if I'm right that means that everytime you see a generator flash it will rerender two chunks. I'll fix this. I misinterpreted how something works in MC so I'll do it a better way now

**Comment by McJty** [comment]
Should be fixed next release. Note, to really fix this you should also make sure you have no vanilla redstone anywhere as that also causes render updates when it changes state. To do that I made a new 'wire' logic block which you can use to replace the redstone dots on the ground with.
