### ISSUE TITLE
[1.10.2] Level Emitters Spreading 

### ISSUE THREAD

**Issue by Stuart74** [McJty/RFTools#655]
Wierdest thing i have ever seen but seems rftools level emitters have started sprouting all over the map

http://puu.sh/qituX/5a01dcf0c6.jpg

RFTools Version rftools-1.10-5.08

**Comment by McJty** [comment]
That is very unlikely to be related to RFTools. Did you update your pack? Apparently something got messed up in the update then. Not much I can do about that I'm afraid

**Comment by Stuart74** [comment]
I was hoping there was a way of removing the level emitters temporarily once i have restarted the server and the emitters have been removed i can then re add them back in and hopefully it should work. I do believe its a item id conflict when i disabled tall grass spreading in terraquous as thats when it started to occur.

**Comment by McJty** [comment]
No idea what I can do to help with this I'm afraid. Sorry
