### ISSUE TITLE
Crash when using RFTools dimensions and trying to join world.

### ISSUE THREAD

**Issue by KristjanKr** [McJty/RFTools#656]
RFTools Dimensions: rftoolsdim-1.10-4.30beta46 
Forge: 12.18.1.2024
Java: Java 8 build 101

Crash log: https://paste.ee/p/c4yfV

Issue: The game starts fine and main screen works but when trying to join the world I get this crash.

**Comment by DoughnutDev** [comment]
Also getting this crash

**Comment by DoughnutDev** [comment]
Here is my crash for the crash too. http://hastebin.com/erupagomew.coffee I am running all of the same things as he is.

**Comment by DoughnutDev** [comment]
Okay so I did some testing. The issue seems to be Router Reborn update, and we are both running the new version.

**Comment by RyanP1991** [comment]
Okay so Router Reborn has just updated and has fixed this issue :)
