### ISSUE TITLE
Minor bug: Unable to change Builder mode without Space card loaded

### ISSUE THREAD

**Issue by trevorjd** [McJty/RFTools#659]
Put a space card in a builder, change the mode (for example, to Collect).
Swap out the space card for a quarry card.
The mode remains on Collect and cannot be changed unless the space card is put back in.

It's a minor issue obviously but I think it would be preferable if the mode was auto-set to Move on the insertion of a quarry card.

**Comment by McJty** [comment]
Well the mode is not used with a quarry card so this is not really an issue I think?

**Comment by trevorjd** [comment]
I made a second builder, infused it and was planning to set it up as a collector (thus had set the mode to Collect). I then decided to use the infused one for my main quarry. I swapped out the builders and stuck the quarry card in the infused builder but it wasn't digging. Took me a little while to figure out that it was still set to Collect mode.

You're right. It's a reasonably uncommon set of circumstances that leads to this issue being encountered. Perhaps I should've labelled this ticket as "Very Minor bug" :-) Thanks for the quick reply!

**Comment by McJty** [comment]
That's weird. Are you sure it is because of that because the quarry shouldn't look at that. But I'll check it out in any case

**Comment by trevorjd** [comment]
I admit that I'm new to the builder so it's very possible that operator error is to blame. However I'm pretty sure that all settings remained the same between having the mode set to Collect vs Move. Once in Move, I heard the telltale sound of blocks being broken.

**Comment by McJty** [comment]
Well I don't see how this is possible. The mode isn't even used when a quarry card is inserted. I double checked the code and no idea what the problem could be. So perhaps you forgot to set redstone mode at some point or something? No idea otherwise...

**Comment by trevorjd** [comment]
OK. I'll assume it was operator error. Thanks for the quick responses!
