### ISSUE TITLE
CTD when right-clicking space card

### ISSUE THREAD

**Issue by trevorjd** [McJty/RFTools#660]
I created a space chamber and received the notification that it had been created successfully. I then right-clicked the card (per advice from the manual) to display the contents of the chamber and CTD. Reloaded and right-clicked again with the same result.

Tile entities present within the bounds of the chamber are... an EnderIO Vacuum Chest, conduits, Attractor Obelisk; ExtraUtils2 trashcan; Two active RFTools shield projectors and their 'shield' textured blocks; various vanilla blocks. I think the only floating items were a couple of snowballs.

The setup itself is working fine. Just CTD's when it tries to render the new GUI.
When I had the space chamber defined in a different location, the GUI popped up empty but no CTD.

http://pastebin.com/VKkA74JL

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
It is the snowballs... I know the problem and I will fix this

**Comment by McJty** [comment]
Fixed next release
