### ISSUE TITLE
[1.10.2] Modular storage deletes items if item is not successfully created with the grid

### ISSUE THREAD

**Issue by DietmarKrause** [McJty/RFTools#664]
I play RF Tools as part of the ftb unstable 1.10.2. build which was upated on 28.7. 
I had successfully build a remote storage block with modular storage and modular storage items (3) and used it without issues. But after 28.7, when trying to build with the bulld-in grid in the modular storage block  i had an issue.
I tried to build a block by copying its receipe into the grid with JEI without having enough material (in this case diamonds as far as i remember) but pressed "1" anyway. As a result the missing items were lit up red (as it should be) and the diamonds were gone out of the storage, all but 1 without the item beeing build (for there were not enough items for the receipt) . From now on, addying diamonds to the storage and after that pressing the key to compress items into one stack (i forgot which one it is in the moment), the added diamonds disapear, only one item (diamond) is shown. For instance you add 20 diamonds, press the key and they are gone, you always see only one diamond. I complety emptied the modular storage to be sure that they are not used to build something. The item i tried to build was a deep resonance laser block. 
PS: after draining the storage items completly, the one used  in this issue disapperared soemhow. It was gone... the other two were left empty as i should be after draining them.

**Comment by McJty** [comment]
What version of rftools is in the pack?

**Comment by DietmarKrause** [comment]
rftools-1.10-5.08.jar as far as i can see

**Comment by McJty** [comment]
This has been fixed some time ago

**Comment by DietmarKrause** [comment]
can you pleae tell me which build fixes this?

**Comment by McJty** [comment]
I recommend using latest RFTools. Many storage related bugs have been fixed (5.11)
