### ISSUE TITLE
Timer Causing Frame Drops

### ISSUE THREAD

**Issue by Codeick** [McJty/RFTools#665]
I am currently using a timer for an endergenic generator power system. I have only made one setup that consists of 4 endergenic generators, 5 ender monitors, 6 sequencers, 1 pearl injecter, and 1 timer. The timer is set to 30 and every time a redstone signal is transmitted I experience a quick drop in frames. I am using vanilla redstone (no repeaters, just redstone dust) to transmit the signal.

I have seen a previous post in which you said it was most likely not the timer, however, I have tried your solution which did not work. Your solution suggested to use EnderIO (most recent stable build) redstone conduits. You also suggested using conduit facades as it has fixed the issue before. This did not fix the lag spikes I was experiencing.

I am running Java Version 8 Update 101 (64 bit) on Windows 10. The Minecraft version is 1.10.2 with Forge running 12.18.1.2042 and RFTools version is 1.10-5.09.

I followed this guide for the setup so you know what the system looks like (if that could be what is causing the frame drop issue from redstone impulses). http://forum.craftersland.net/topic/10815-rftools-endergenic-generator-designed-by-me/

I apologize if there is something blatant causing this issue. I am very new to creating my own modpack and trying to troubleshoot stuff like this is very new to me. I did try looking up solutions before this post, but I am clueless as to what else could be causing it.

**Comment by McJty** [comment]
It is vanilla redstone causing this. Every time vanilla redstone changes the chunk has to be rerendered. I recommend avoiding vanilla redstone and using (for example) my new 'wire' block or some other non-laggy means to transmit redstone
