### ISSUE TITLE
Crash using Builder Block in normal Quarry mode

### ISSUE THREAD

**Issue by togreglove** [McJty/RFTools#666]
Repeated crashes. Restoring from a backup, it crashed again at about the same time during the next run through.  I changed the area of the quarry (moved and made larger), and the quarry ran fine for an hour or so, then crashed again.

Crash log here: http://pastebin.com/T3Jv5eE0

Hope this helps.
Thanks

Note: Crash corrupts world or re-occurs immediately upon login. Restoring from a backup is the only way to recover.

**Comment by McJty** [comment]
How is this quarry used? What container are you using? A screenshot of the setup would help. Thanks

**Comment by togreglove** [comment]
Quarry is used to simply quarry item, most basic settings, no fortune, no silk touch, no clearing.

The container is a Small Storage Crate from Actually Additions

Setup is: http://imgur.com/a/rxk8H

Storage containers to the right of quarry are for me to sort stuff.

The quarry can/will run for hours without issue, then crash. Not sure if it's based on something it hits underground or the size of the quarry, or what.

**Comment by McJty** [comment]
Hmm, it seems to be that the builder is getting an invalid item quarried. This is probably a bug in some other mod but finding out what is going to be hard. I'm going to try to put in diagnostic code in the builder for this so that at least it doesn't crash and the error will be reported in the log then

**Comment by togreglove** [comment]
Thanks! For now I guess I'll just move the quarry area and restart it till it happens again. Repeat. One item I have expected to get, but haven't is the Resonance Crystal from Deep Resonance. They are fairly rare, but I expected at least one by now. Maybe the culprit? Who knows. Figured I would mention it.

**Comment by McJty** [comment]
Well Deep Resonance ores and crystal mine fine for me so I don't think it is that.

**Comment by togreglove** [comment]
Moved quarry and it almost instantly crashed (2 mins) this time. Gonna just turn it off, resources are ok for now :)

**Comment by McJty** [comment]
I will release a new version with diagnostics today. It would be extremely helpful if you try again with that version (once it is released) to find out what block is causing it

**Comment by togreglove** [comment]
Will do.

**Comment by togreglove** [comment]
Forgot to be specific. This is the 1.10.2 build, not the 1.9.4 build.

**Comment by McJty** [comment]
5.10 should have the diagnostics

**Comment by togreglove** [comment]
So, it'll still crash, but have a more useful dump? or no crash?

**Comment by McJty** [comment]
It should no longer crash. Instead the builder should pause and give an error message on screen to anyone near the builder telling what block is causing the problem

**Comment by McJty** [comment]
Obviously I haven't been able to try it out since I don't have such a failing block :-)

**Comment by togreglove** [comment]
Cool, will idle by the builder block

**Comment by togreglove** [comment]
First bad item  "Terraqueous:Foliage2"

**Comment by McJty** [comment]
Never heard of that mod but I think you better report to them that their foliage block getDrops() method is returning itemstacks that have a null item. That's basically invalid

**Comment by togreglove** [comment]
Will do, will probably remove that mod just in case, since I don't think it adds a ton of stuff

**Comment by togreglove** [comment]
Added a bug report to the most obvious place I could find. They don't have a github or anything.
