### ISSUE TITLE
Suggestion: Storage Scanner shows the name of the storage module.

### ISSUE THREAD

**Issue by Rated01010010** [McJty/RFTools#668]
I haven't gotten on Minecraft in awhile so don't hate me too much if it already does this, but I noticed recently from some YouTube videos you added the ability to name storage modules in an Anvil. This got me to thinking of a good idea, in that your Storage Scanner should show a list according to the name of the storage module, instead of just saying Modular Storage. That way you can create a file system. Can view the list of close Modular Storage blocks by Ores, Stone, Wood, RFTools Parts, or whatever you named the module. Would also be nice if you renamed chests or any other inventory tile entity, it would show the custom name. So if I named an Iron Chest "Misc Parts" it would show up as Misc Parts in the Scanner.

**Comment by Famous5000** [comment]
That would be interesting indeed! I would like to see this in a new version
of RFTools!

**Comment by McJty** [comment]
Not sure I totally get this suggestion? The storage scanner already shows the name of those modules no?
