### ISSUE TITLE
Yellorite Dimlets

### ISSUE THREAD

**Issue by ipodtouchdude** [McJty/RFTools#67]
Was wondering if you could add Yellorite from BigReactors to Dimlets.

**Comment by McJty** [comment]
I have plans for adding more dimlets for ores and stuff. So yes, this will happen at some point.

**Comment by Veggetossj** [comment]
Use a yellorium liquid dimlet instead, pump it inot a casting basin and u get yellorium blocks

**Comment by McJty** [comment]
2.53 adds all ores that are in the ore dictionary. So it should be there now.
