### ISSUE TITLE
Dimlets not using the correct maintain values.

### ISSUE THREAD

**Issue by iNightmaree** [McJty/RFTools#670]
Hello!

It seems after configuring the liquid lava dimlet to only use 250RF/t to maintain, it's not recognising it. I've put it in the dimlets.cfg file, and it seems to recognise this when executing the /rftcfg dimletcfg command (Probably not exactly it but you get the point.)

Tooltip hover shows the following: https://puu.sh/qr5EE/7207040025.png

Putting it in the dimension enscriber to work it's magic won't update it either, and right now I'm at a dead end on what I'm supposed to do here. Any advice or help would be appreciated.

**Comment by McJty** [comment]
How did you configure it?Did you put the config on clients and server?

**Comment by iNightmaree** [comment]
I didn't know it needed to be on clients as well.. I've configured the lava's rfmaintain value like this: https://puu.sh/qrS0J/ee20c4b7f0.png

**Comment by McJty** [comment]
yes it has to be on clients too. In 1.10.2 version of rftools this information is sent to the clients but not in 1.7.10

**Comment by iNightmaree** [comment]
That's a bit annoying, okay. Thank you, let me try it now and I'll let you know if it works or not before closing this.

**Comment by iNightmaree** [comment]
Yeah, working now. Thanks.
