### ISSUE TITLE
Server Crash !Help Please!

### ISSUE THREAD

**Issue by Rnrn13** [McJty/RFTools#671]
pastebin : http://pastebin.com/EgtT0n7B

**Comment by McJty** [comment]
That looks like a bug in the immibis chunkloader to me

**Comment by Rnrn13** [comment]
Oh ok I was refering to the bottom of the crash where it says dim 20 isn't there

**Comment by Rnrn13** [comment]
Do you think you could help me anyways? I cant seem to find the Immimbis Dimensional Anchors github

**Comment by McJty** [comment]
How can I even help with that? That's not my mod. I don't know how it works even

**Comment by Rnrn13** [comment]
Idk sorry I'm not experienced in fixing server issues but I did it so its ok
