### ISSUE TITLE
Sensor range not working

### ISSUE THREAD

**Issue by yutang13** [McJty/RFTools#672]
When trying to use the sensor block and changing the range it'll only detect entities directly in front of it.

Eg: Go to detect Players mode, set range to "Area 5" and stand three blocks in-front. No redstone signal. 2 blocks? Nope. One block, output! 

Using Rf tools: 1.10-5.11

Strangely it detects blocks further than 1 block away...

**Comment by McJty** [comment]
Will fix this for next release
