### ISSUE TITLE
Efficiency Essence is non-existant

### ISSUE THREAD

**Issue by mzx987** [McJty/RFTools#674]
I've tried finding a solution to this, but I can't find anything on the matter.
I'm having an issue trying to craft the Efficiency essence in RFTools 1.10-5.11.

Is there something I am doing wrong, or is it truly missing?

**Comment by McJty** [comment]
yes it is missing. I need to add a lot more to rftools dimensions before I can move it out of beta

**Comment by mzx987** [comment]
Alright. Thanks for the quick response.
