### ISSUE TITLE
storage drawers and modular storage

### ISSUE THREAD

**Issue by shrael** [McJty/RFTools#677]
Hi im using the enderio panel with the awareness upgrade and item conduits as well, the items seem to go into the modular storage and try to go back into the storage drawers even setting the priority doesnt seem to fix the issue.

**Comment by McJty** [comment]
I need a LOT more information. Also it sounds like it is EnderIO not behaving here and not rftools? What is the actual setup and what isn't working right?

**Comment by shrael** [comment]
W/e I would put an item into the panel it seems like it's going into the drawer which is locked, so it should go there but it's not. it's like spacing out into the modular storage and trying to go back into the drawer at the same time. This is 1.10.2

Sent using Boxer

On Aug 12, 2016 12:44 AM, McJty <notifications@github.com> wrote:

I need a LOT more information. Also it sounds like it is EnderIO not behaving here and not rftools? What is the actual setup and what isn't working right?

**Comment by McJty** [comment]
This does sound like a bug in EnderIO to me. Why do you think this involves RFTools?

**Comment by McJty** [comment]
Closing this for now. Please reopen this if you find it is actually a bug in RFTools
