### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [McJty/RFTools#683]
Not sure if this is you or not, but I looked through the crash report (with my very limited knowledge) and saw your name pop up quite a bit so figured I'd try it out here. Let me know if I need to go elsewhere.

<script src="//pastebin.com/embed_js/W4QMknUA"></script>

**Comment by awkwaRdcaRRot** [comment]
This might help haha

http://pastebin.com/W4QMknUA

**Comment by canitzp** [comment]
Downgrade your Forge Version to 2061 fix this issue

**Comment by McJty** [comment]
Not related to rftools either

**Comment by McJty** [comment]
BTW, upgrading to forge 2063 will also fix it

**Comment by canitzp** [comment]
No this is already forge 2063 but lex hasn't fix this npe. i see it in my dev env too

**Comment by awkwaRdcaRRot** [comment]
Oh ok, thanks guys. I actually just tried to see if it was ender io and left ender io where it was at and upgraded everything else and that has apparently fixed the issue as well.
