### ISSUE TITLE
Redstone Transmitter - clear / change the channel - rftools-1.10-5.11

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#684]
Hi McJty,

This may be related to issue #622 

I have managed to accidentally get two transmitters on the same channel. Is there a way to reset the transmitter such that a new channel will be created when it's placed?

I've tried breaking and replacing, putting into a crafting window, left & right clicking in air and shift L&R clicking in air.

Changing the transmitter channel by right-clicking another transmitter works normally. The problem is in reusing the device with a new channel.

Thanks!

Cosmetic issue you probably already know about: WAILA shows channel 0 but the console is reporting the channel number correctly.

**Comment by McJty** [comment]
Hmm, strange about WAILA. Did you to see if TOP (The One Probe) is correct?

Aslo there might not be a way to reset the channel. I'll check it out

**Comment by McJty** [comment]
Putting a redstone transmitter in the crafting table clears the channel so you can use that. Please reopen if this is not working for you but it did for me

**Comment by xenoflot** [comment]
I swear that didn't work when I tried it. It did this time. Thanks!

**Comment by xenoflot** [comment]
Hey, I found out why I was confused. Putting the transmitter in a crafting grid will reset it, but this doesn't work with other devices like sequencers, receivers, etc. 

Not a major issue but while they retain settings, they won't stack in the inventory. As time and enthusiasm allow, you may care to add that functionality to all your blocks.

**Comment by ExDomino** [comment]
There is no way to reset a Redstone Receiver on 1.12 with the latest version.

**Comment by mcdodge34** [comment]
I can confirm that I'm stuck with a redstone receiver set on channel 2 by accident, had to craft and place a new one just so I could have separated channels to control 2 mob spawners.

**Comment by josephcsible** [comment]
@mcdodge34 You didn't have to do that. Channels aren't permanent, so you could have reassigned one of the receivers' channels that you already set, just by setting it again the same way on a different transmitter.

**Comment by mcdodge34** [comment]
Not using transmitter, but screen button to control a mob spawner wirelessly from a screen...

**Comment by josephcsible** [comment]
Good point. There's indeed currently no way to give a button a new channel without also simultaneously giving a formerly-blank receiver the same channel.

**Comment by mcdodge34** [comment]
Maybe something for a new version then...

**Comment by josephcsible** [comment]
Indeed. I'll try to rework how channels get assigned sometime this week.

**Comment by josephcsible** [comment]
Okay, here's how I'm going to make this work:
* Transmitters will no longer automatically get a channel when placed.
* Crafting a transmitter, receiver, or button by itself will unset its channel.
* Right-clicking a transmitter or receiver that has a channel with a transmitter, receiver, or button (whether or not it has a channel) will set the channel of what you're holding to match what you clicked on.
* Sneak-right-clicking a transmitter or receiver (whether or not it has a channel) with a button that has a channel will set the channel of what you clicked on to match the button you're holding.
* Right-clicking a transmitter or receiver that doesn't have a channel with a transmitter, receiver, or button (whether or not it has a channel) will create a new channel and set it on both what you clicked on and what you're holding.

**Comment by mcdodge34** [comment]
Great, that will make such a difference, now if we could get redstone conduits like in enderio that can be totally hidden, but we can always dream of that I guess...
