### ISSUE TITLE
Crafter Doesn't Obey Redstone Mode

### ISSUE THREAD

**Issue by Winrylive** [McJty/RFTools#685]
RS mode selection seems to be ignored. Active with signal, but no RS applied and it still runs. Active without signal, with RS applied and it still runs.....

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Ah but first, what version of rftools?

**Comment by Winrylive** [comment]
1.10-5.11 Will be updating to 5.14 tomorrow. Is it fixed in that version?

**Comment by McJty** [comment]
No not yet. I can reproduce the bug though so will fix it today

**Comment by McJty** [comment]
Fixed in next relese
