### ISSUE TITLE
Use string ID's to identify dimlets instead of damage value

### ISSUE THREAD

**Issue by McJty** [McJty/RFTools#69]
To make dimlets cross-world compatible we need to convert dimlets to using string ID's intead of numeric ids (damage values). Be we also need compatibility. If a string ID is present then it will be the master and the appropriate numeric id will be calculated from that (for NEI support in getSubItems).

**Comment by Ivorforce** [comment]
I highly support this ticket. Great idea :P

**Comment by raxixor** [comment]
Supportive.

**Comment by McJty** [comment]
Besides a lot of testing this should be ok and will be in version 2.60
