### ISSUE TITLE
RFTools liquid monitor crashed with EnderIO VAT

### ISSUE THREAD

**Issue by seulil** [McJty/RFTools#690]
Trying to autmate Vat from Ender IO with liquid monitor, but when adjusting (touching the bar in liquid monitor's GUI) after selecting the VAT server ctd.
[crash-2016-08-19_10.38.57-server.txt](https://github.com/McJty/RFTools/files/426620/crash-2016-08-19_10.38.57-server.txt)

[2016-08-19-5.log.gz](https://github.com/McJty/RFTools/files/426623/2016-08-19-5.log.gz)

**Comment by McJty** [comment]
Bug in EnderIO and they are aware of it

**Comment by McJty** [comment]
BTW, here is the relevant ticket: https://github.com/SleepyTrousers/EnderIO/issues/3621#issuecomment-240959216
