### ISSUE TITLE
Enviromental Controller No Teleport Effect remains

### ISSUE THREAD

**Issue by sherkas** [McJty/RFTools#692]
Noticed this bug while using this in a enderman farm.

Setup is: Ender IO Spawner/killer joe with vacuum chest in a enderman setup.

I have a enviromental controller setup with a 20 yard range, +-10 range height and only effect in it is the no teleport effect.

If you turn on the machine, it will apply the effect to you and if you try to use the porter (or advanced) it will just ... say its starting and then end it there. I believe all RF is deducted but the move is not performed. If you try to teleport to a receiver in this 'area' it will also say your teleporting but never move you (Even if your long ways away).

If the controller runs out of mana or is redstone deactivated and if you even wait... say 1 minute so the effect should be fully removed, you still cannot teleport. If you go into the machine and remove the effect then place it back in, you can teleport just fine.

I recommend you add teleport messages (to and from) incase they are blocked so the user knows why. (I spent a good 10 mins figuring this out LOL) and of course address the bug nature of it if at all possible.

Using 1.10, RFTools 5.11, Dim 4.30 beta46 (pretty much all rftools as a week ago or so).

**Comment by McJty** [comment]
That bug has been fixed. RFTools 5.11 is pretty old (we're at 5.15 now)

Note also that you should set the environmental controller to affect mobs only so that you as a player are not affected
