### ISSUE TITLE
[1.10.2]Spawner keep amounts of items when swapping syringe

### ISSUE THREAD

**Issue by ImperaServ** [McJty/RFTools#695]
When you swap syringe in a Spawner,  the amount of items of each type stays,  so you can bypass the need of mob-specific items. For example,  if I place a Skeleton syringe, inject three bones, then swap the syringe with a Wither one,  the Spawner will have three nether stars stored for spawn.

**Comment by McJty** [comment]
I cannot reproduce this. How exactly are you doing this? How are you swapping the syringe?

**Comment by ImperaServ** [comment]
Simply left clicking the current syringe with the new one in the spawner GUI.

**Comment by McJty** [comment]
Fixed next release
