### ISSUE TITLE
Elevator suggestions

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#699]
Would it be possible, to be able to right click a elevator floor marker with a block to set in to that block's texture and right click with empty hand to set it to the default one. Also if this does not confuse floor marker have it give of redstone single when the elevator or maybe there can be another block monitor if it is at that level.

**Comment by McJty** [comment]
Camouflage of elevator block was already suggested in another ticket.

And the elevator block already gives a redstone signal when the elevator is at that level (see the orange arrow at the back)
