### ISSUE TITLE
[Request] No-Mobs Dimlet | Platinum more expensive

### ISSUE THREAD

**Issue by unpure** [McJty/RFTools#70]
Hey there.
I love it to to build my base inside of void worlds.
Building some cool stuff and sometimes huge half-spheres of grass.
Currently the only way to get rid of all the mobs is to use desert.
Unfortunately desert makes some ugly grass/leaves.
I've seen that there are some dimlets to add mobs to the dimension.
I've also seen that there is a "peacefull" dimlet.
It would be awesome if there would be a dimlet to completly remove ALL passive mobs.

The other point i would like to suggest is molten platinum.
Most of the uptodate modpacks are using BigReactors.
Only 2 things are realy needed for them. Resonant Ender and Platinum/Shiny.
We managed it to get an ocean of molten platinum for about 8k RF/t.
With this an with the use of tinkers smeltery it's easy to get tons of shiny.
Maybe the tier should be a bit higher because its way to easy to farm everything needed to get more RF/t.

Sorry for my bad english, i hope its not to hard to understand. :/

**Comment by McJty** [comment]
A passive mob removal dimlet may be an option yes.

Note that molten platinum will be a lot more expensive if you added the dimlet manually. If you get a random feature like that you get a 10% discount in cost so you just got very lucky :-)

**Comment by unpure** [comment]
I only added molten platinum, single biome, ocean.
I think its way to cheap for this huge amount.. :D 
But thats just my opinion.
Still the passive mob would be awesome!
Love this mod. I just hope to see maybe a few others ways to create energy.
Need some cool mods so i'm not going to use only BigReactors for energy. :(
RFTools is a realy great mod and it seems like its getting a absolutly must have! :)

A small bug that i maybe found (its on 2.31b because i'm just updating my pack atm.)
I tried to use 5 creative energy cells from TE directly on the Dimension Builder but it seems like its not working. There is absolutly no energy that goes into the builder. (Should be 100k RF/t)
With the creative capacitor bank everything works fine.
If i place a tesseract on the creative energy cell and the tesseract ontop of the builder its working fine too!

**Comment by McJty** [comment]
Hmm that may be an outdated CoFH and is likely fixed with a more recent version of Thermal Expansion and/or RFTools. I don't have that problem at least.

**Comment by unpure** [comment]
I will test that again with the latest version after updateing my modpack.
If this problem still exists i will post a more detailed bugreport for that! ;)

**Comment by McJty** [comment]
The No Animals feature has been implemented
