### ISSUE TITLE
1.10.2 bug elevator sound keeps playing

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#703]
Just updated my mod pack and when I used the elevator the sound does not stop unless I breake the bottom floor marker.

RFTools version 1 .10-5.17

**Comment by Dijkstra1** [comment]
This bug may be with McJty Lib as, I am getting the same bug with the deep resonance generator.

**Comment by helium2s1** [comment]
Same issue here. Playing All The Mods 1.17, with RFTools 5.20. I changed the config setting for the loopVolume, but haven't checked if that is a good workaround. Personally, I like the elevator sound when it's running, so hopefully this can be fixed soon.

**Comment by Dijkstra1** [comment]
Same pack @helium2s1 but in the fastest version for ne it seemed to be fixed, though have not check if what the drunk has sneeked something in the last couple of dayd

**Comment by McJty** [comment]
Probably caused by Botania:

https://github.com/williewillus/Botania/issues/458

**Comment by Dijkstra1** [comment]
O it back in the latest update, @williewillus what every you did fix it or revert to an early state

**Comment by McJty** [comment]
What versio nof Botania?

**Comment by Dijkstra1** [comment]
Botania-unofficial.r1.8-320, which seems to be latest going by cruse anyway

**Comment by Famous5000** [comment]
williewillus commented an hour ago
It's not in a release build yet. I'll probably put out a final build of Botania U within the next couple days now that vaz is back
@Dijkstra1 Looks like we'll be getting this fix soon. Hopefully.

**Comment by williewillus** [comment]
Sorry about the delay, been busy

**Comment by mcdodge34** [comment]
2 yrs later, but I have this exact same issue now in 1.12.2 with rftools latest version, botania latest version and dynamic surroundings latest version, any idea if there's a config file I could tweak to avoid this annoying sound bug. Should I create a new issue, that's the question, happened to me 3 times already, if I lower the block sounds to 0, go back in the world, then set it back, its fixed, until the sound decide to crash again and go in a loop.

**Comment by josephcsible** [comment]
If you remove Botania, can you still reproduce this?

**Comment by mcdodge34** [comment]
Hum, I can't tell, that would break everything in my world, don't have time to create separate instance for testing on my side.

**Comment by josephcsible** [comment]
Good idea. Also, can you find out whether you need Botania, Dynamic Surroundings, or both for this to happen?

**Comment by mcdodge34** [comment]
Will try to find time tonight (I'M in GMT-5 timezone), will have to get a custom pack running with only theses 3 mods, otherwise, it would take awhile to load, but I got a feeling that updating to the latest beta of Dynamic Surroundings will solve the issue somehow, I was sure I was on a newer release but turns out only beta were done since september last year.

**Comment by mcdodge34** [comment]
Since I updated Dynamic Surrounding to a beta version, I never experienced the issue again.

**Comment by josephcsible** [comment]
I'm going to assume it was their bug and leave this closed then. If it does reoccur, just post here again and I'll reopen it.

**Comment by Buttcrackofthunder** [comment]
now I'm having this bug...

latest version of dynamic surroundings, botania and rftools and the elevator sound just keeps on playing.

**Comment by josephcsible** [comment]
Never, ever say you're running the "latest" version of anything. Please post the actual version numbers.

**Comment by Buttcrackofthunder** [comment]
alright:

rftools: 7,33

mcjtylib: 2.6.7

botania: 354

dyn surroundings: 1.12.2-2.4.9 13
