### ISSUE TITLE
Crash when activating Elevator (rftools-1.10-5.19)

### ISSUE THREAD

**Issue by Godkyra** [McJty/RFTools#705]
Updated about ten minutes ago. I was using a screen with the Elevator Button module. The elevator is two floors, and uses Quark Basalt Bricks (3x3) as the mobile platform. Clicking on the lower button (attempting to get down to ground level) immediately crashed the game with the first crashlog. Reloading the world immediately locks the game and produces the second crash report.

World is currently unusable.

[crash-2016-08-25_18.31.56-client.txt](https://github.com/McJty/RFTools/files/438042/crash-2016-08-25_18.31.56-client.txt)

[crash-2016-08-25_21.45.45-server.txt](https://github.com/McJty/RFTools/files/438034/crash-2016-08-25_21.45.45-server.txt)

**Comment by DreamingLamb** [comment]
I can confirm I'm experiencing the same issue with 5.19, however I am able to log back in.  The issue only occurs when moving a player or entity, the elevator works when nothing is being moved.

**Comment by McJty** [comment]
I will check this out as soon as possible

**Comment by McJty** [comment]
Fixed in 5.20
