### ISSUE TITLE
[Question] Dimension Builder Powering in Rftool dim (on sever)

### ISSUE THREAD

**Issue by Ldmf** [McJty/RFTools#711]
I have build a Void Dim with Noon time and power gen on a sever (Chunk Loader [FTBU]) so it have evri time power but i die in it so my question is it my problem or mabe on a sever restart

my english is bead i know...

**Comment by McJty** [comment]
How do you die in it? Is the dimension builder chunkloaded? Also what version of FTB utilities? There was a recent bugfix release for it

**Comment by Ldmf** [comment]
yes it was chunkloaded we play with FTB Infinity Evolved 17 (v2.6.0)
FTBUtilities-1.7.10-1.0.18.3

**Comment by McJty** [comment]
And where is that dimension builder located exactly?

**Comment by Ldmf** [comment]
Per powert it on ow too enter it a second time

![2016-08-26_15 31 07](https://cloud.githubusercontent.com/assets/15316448/18006960/59e19656-6ba2-11e6-93a1-3954a8b51848.png)
![2016-08-26_15 31 12](https://cloud.githubusercontent.com/assets/15316448/18006961/59e1bb9a-6ba2-11e6-8f95-2dd21596c591.png)
![2016-08-26_15 31 20](https://cloud.githubusercontent.com/assets/15316448/18006962/59e50b10-6ba2-11e6-8cd5-ccded2d1b27e.png)

**Comment by McJty** [comment]
And how is the dimension builder itself getting power?

**Comment by Ldmf** [comment]
With a  Resonant Solar Panel (512/t) in a always day dimansion

**Comment by McJty** [comment]
Well not sure what is going on but I do know that chunkloader often have problems in rftools dimensions and only work after visiting them at least once. So perhaps it is not a good idea to put the builder there

**Comment by Ldmf** [comment]
ok :) thx 4 the help and you mod is realy good :) thx 4 the work on it

can be closed now

sory not the best english in the world :(
