### ISSUE TITLE
[1.10.2][Bug]SERIOUS issues (item loss/item dupe) caused by Modular Storage (gif inside)

### ISSUE THREAD

**Issue by Johnnybeg00d** [McJty/RFTools#714]
Pretty easy to replicate. First, get a modular storage and put a storage module tier 1 in it. Then fill it up with items. After that, use JEI to pull up the recipe for Storage Module Tier 2, the use the '+' to move it to the crafting section of the Modular Storage. After that, hover over the 'craft 1' button, and bam.
https://i.gyazo.com/5416de119fb74eebb869a3fa80217a3d.mp4

Either it's resetting to a previous state of no items, (which happened to me and made me lose everything) or else it resets to a time when it was full of items, letting you grab them out again, duping them. Not sure if there's something strange going on with trying to craft a Storage Module while using a storage module.

For the time being, because this is apparently pretty buggy, I won't be using modular storage at the risk of losing my items or getting tempted to dupe them.

**Comment by McJty** [comment]
What version of RFTools?

**Comment by McJty** [comment]
The reason I ask is that this bug has been fixed in RFTools 5.18 so I want to confirm that you are using an older version

**Comment by McJty** [comment]
And BTW, this bug can only occur when upgrading storage cards. There is no other way to trigger it

**Comment by Johnnybeg00d** [comment]
Well that was fast. I had just downloaded this to play with a friend. But apparently you're right, it's 5.17. I'll update and try again. Sorry for the false bug report. Looks like your chest system is back on the menu. Thanks!
