### ISSUE TITLE
Storage Module Block (RFtools) Bug Ftb Unstable Latest Version 1.10.2

### ISSUE THREAD

**Issue by FearMyGaze** [McJty/RFTools#717]
When i am going to craft new storage module tier 1 to tier 2 inside my module storage block  then he delete my old one with all my items inside

**Comment by Yavin7** [comment]
Can confirm, just lost my original storage module when attempting to craft a tier 1 to tier 2 while a tier 3 was already inside

**Comment by McJty** [comment]
I guess FTB Unstable has RFTools 5.17? Then that's a known bug fixed in 5.18

**Comment by Yavin7** [comment]
Awesome! Thanks for letting us know
