### ISSUE TITLE
Mark Dimensions and/or allow deletion from disk

### ISSUE THREAD

**Issue by Thiana** [McJty/RFTools#72]
Could you please mark the dimensions you create as belonging to RFtools. Mystcraft names them DIM_MYST#, so perhaps you could do something like DIM_RFT#? When you've been doing lots of exploring you can get lots of dimensions you're never going to visit again so it would be nice to have a way to delete them easily. Even better would be a way to permanently delete them from within the game :) Thanks.

**Comment by McJty** [comment]
Note that you can already use the /rftdim safedel <id> command from the console. That will delete the dimension from the perspective of RFTools (you still have to delete the actual dimension files on disk) and as a bonus the id will be reusable again for a new rftools dimension.

**Comment by McJty** [comment]
Renaming the dimension folders is hard to do in a compatible way and as to deleting dimensions that is already possible. So I'm closing this issue.
