### ISSUE TITLE
1.10.2 Crash whe teleporting to Nether, world corrupted does not load.

### ISSUE THREAD

**Issue by jonabrv1965** [McJty/RFTools#721]
Here the crash log. It trash my world entirely, it does not load... I restore a backup,  and trying to do the same steps it crashes (this is consistent, not random)
[Uploading crash-2016-09-02_19.37.16-server.txt…])

**Comment by jonabrv1965** [comment]
[crash-2016-09-02_19.37.16-server.txt](https://github.com/McJty/RFTools/files/453109/crash-2016-09-02_19.37.16-server.txt)

**Comment by McJty** [comment]
Was the nether reset or something? RFTools can't find a receiver there. I can fix the crash but the reason the crash is there is weird though

**Comment by jonabrv1965** [comment]
Nope, the funny thing is that I do have other receiver in Nether far away (1800 blocks) from this one in and that works just fine... the only thing that is different between those two nether locations are that I recently installed a Mod called futuretech and this mod created big structures all over the nether (except in the place tha is working), that's why i have to go lenghts to reach this structures. In other words, the receiver location that crash has new structures from futuretech mod, that the old receiver (one that works) does not...

Thank you for your promptly answer!!!

**Comment by McJty** [comment]
So probably the structure mod overwrote the receiver. That can cause problems...

**Comment by jonabrv1965** [comment]
Do you think I should report this to Futuretch guys?

**Comment by McJty** [comment]
Well the problem is that this kind of thing is probably hard to avoid. Adding a mod later that adds worldgen like that is bound to give problems. This is most likely something they can't do a lot about either. I did add some protection in rftools so that it will not crash at least but the receiver will not function

**Comment by jonabrv1965** [comment]
I understand, no problem then, I manage to workaround this by creating a Nether portal (that takes me to overworld at 12k block away from home :-) and there I place the receiver, and it works fine, just one more "jump" to travel to the futuretech complex in nether... I guess you can close this...
