### ISSUE TITLE
1.10.2 - Crash when taking items out of Storage Monitor

### ISSUE THREAD

**Issue by viper2g1** [McJty/RFTools#727]
Using:

Minecraft: 1.10.2
RFTools: 1.10-5.22
RFTools Dim: 1.10-4.30beta48
RFToolsCTRL: 1.10-0.0.1beta2.jar

I am unsure if other mods are conflicting here, prior to updating my modpack I did not have this error.  The following mods are the ones I updated (and added RFTools Ctrl.  

Mekanism
Mekanism Tools
Mekanism Generators
RFTools
Storage Drawers
Quark
Psi
Neat
Mcjtylib
Forestry
Evilcraft
EnderCore
Ender IO
CyclopsCore
AutoRegLib

This is the crash log that I have when taking an item out of the storage monitor.

https://gist.github.com/viper2g1/1440f149cb2dea5baf5ce251ab6e356c

Another Log:

https://gist.github.com/viper2g1/ae913a5318dd458ee5a68d24b54d2a52

**Comment by viper2g1** [comment]
I just tried removing items from a Vanilla chest with no problems including inserting them back in.  I then went to the storage scanner and chose one modular storage and withdrew about ten stacks without problem.  They all inserted back into the system fine.

The error occured again when I searched for an item, this time it was redstone I believe.  It was fine while I selected the item on the right side, but as soon as I selected the item in the area to withdrawl the item into my player inventory the game crashed.

Here is the crash log from that instance: 

https://gist.github.com/viper2g1/4c536d7c04e8746f9ae4bf936f124e31

**Comment by McJty** [comment]
Yes I can reproduce this. Fixing now

**Comment by McJty** [comment]
Fixed in McJtyLib 2.0.1 (the bug was there and not in rftools)

**Comment by viper2g1** [comment]
Thank you for the quick fix :+1:
