### ISSUE TITLE
Storage scanner hide inventories 

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#730]
I have a big bank of drawers as main storage in base and they all linked to my storage scanner one drawer controller, I would like the options to hide the 20 odd drawers that my storage scanner does not need to know about, this does not mean hide all unroutable inventories, as I have cell that is unroutable that like I to send low charged item to charge on the go including the storage scanner tablet itself.

**Comment by McJty** [comment]
The easiest way to do that right now is simply to move all those inventories to the bottom of the list

**Comment by Dijkstra1** [comment]
What have done I have got a ridiculously small scroll bar, plus when I add something new, I have to more it top then past about 15 item I want above it. So way of hidden them in the further would nice.

**Comment by McJty** [comment]
Implemented for next release
