### ISSUE TITLE
(BUG) "Invalid Device" when trying to teleport back from RFTDim to Overworld

### ISSUE THREAD

**Issue by Vaygrim** [McJty/RFTools#731]
Title says it all. I teleported into an RF Tools Dimension, created by me,  only to get stuck there because the dialing device & transmitter I setup there (I was in creative mode) told me "Invalid Device". Couldn't get back to the overworld and had to resort to slash commands.

**Comment by McJty** [comment]
Can you show a screenshot of that error and the setup where you got it from?

**Comment by Vaygrim** [comment]
It is quite literally just a Dialing Device, Matter Transmitter, and Matter Receiver .. on both ends. Creative Capacitor supplying the power on both ends. In each setup, Matter Receiver is on the left, Dialing Device in the middle, and Matter Transmitter on the right. (No destination analyzers, nothing else like that.)

The first dimension we tried to create was an Eternal Noon void dimension. It was a void dimension, but.. not eternal day. Anyway... when trying to connect the Matter Transmitter there named "Test1" to the Matter Receiver back at spawn (called "Spawn"), we get "Invalid Device!" as an error.

That is literally it. Just a simple little popup message in the Dialing Device.

**Comment by ShaCraft** [comment]
Same here! Confirmed I am using All The Mods Pack. I'll get a SS on the next dim.

**Comment by ShaCraft** [comment]
![2016-09-18_22 27 48](https://cloud.githubusercontent.com/assets/13075796/18621309/3f64f070-7def-11e6-8503-d5aaf48a0d79.png)

**Comment by ShaCraft** [comment]
So after doing some other things and using pads and Adv Charged porter for a bit I went back to the dim while recording and was going to show my viewers what happened... it worked with no issue. go figure lol. So some how it fixed its self. Not sure if this is any help or not..

**Comment by McJty** [comment]
yes, seems this is an intermittent problem that only happens some times. At this moment I have no clue what is causing it. I'm busy debugging this right now but I have not been able to reproduce it yet

**Comment by McJty** [comment]
Ok good news. I *can* reproduce this on a server setup. So there is something wrong when RFTools Dimensions is used on a server. I'm on it

**Comment by Vaygrim** [comment]
If it helps, it will sometimes (but not always) clear up on reboot.

**Comment by McJty** [comment]
Nah problems that happen all the time are usually easier to debug

**Comment by McJty** [comment]
Ok, got something. Apparently for some reason the client thinks it is in the overworld while the player is in the rftools dimension. Debugging...

**Comment by Vaygrim** [comment]
This would explain why the "Coordinates Selector" tool from Ender IO thought the coordinates I was selecting were in the Overworld (when it was in an RF tools Dimension).

**Comment by McJty** [comment]
Ok, I know what's causing the bug. Just need to find out how to fix it safely and properly

**Comment by McJty** [comment]
FOUND AND FIXED!. Preparing release now
