### ISSUE TITLE
Quarry problems in RFToolsDim

### ISSUE THREAD

**Issue by mcjonesmike** [McJty/RFTools#735]
I recently set up an RFTools quarry in an RFToolsDIM dimension. I am using the RFTools wireless redstone blocks to transmit a signal from the overworld to the quarry, and it doesn't work. The quarry only activates when I break the redstone dust going from the receiver to the builder, and will only run while I am in the dimension. Even then, it only runs for a few seconds before it stops. It isn't running out of power, as I have a creative capacitor bank attached for testing purposes. This is the only quarry in the pack, as buildcraft hasn't updated yet. I honestly don't know what's happening. I am on the latest version of RFTools, RFToolsDIM, and McJityLib for Minecraft 1.10.2.

**Comment by McJty** [comment]
Screenshots of the setup?

**Comment by Ronzan** [comment]
Sounds like the dimension is not chunkloaded?

**Comment by mcjonesmike** [comment]
![2016-09-19_15 06 18](https://cloud.githubusercontent.com/assets/16712053/18645401/0c4d47aa-7e7b-11e6-9959-f360ae2fe62d.png)

**Comment by McJty** [comment]
Can you show me the GUI of the builder?

**Comment by mcjonesmike** [comment]
![2016-09-19_18 22 24](https://cloud.githubusercontent.com/assets/16712053/18650931/0ce61a3c-7e96-11e6-9eb0-61cb5a7bf8ac.png)

**Comment by mcjonesmike** [comment]
By the way, the area is loaded thanks to that extrautilities2 chunk loader

**Comment by Daenyth** [comment]
@mcjonesmike Check that your grid power is sufficient to run the loader, and that your GP generation is also chunk loaded? If your GP generation isn't chunk loaded then when it unloads, this chunk loader will fail. I have a working setup with the builder quarry in a dimension, loaded by that chunk loader and using the wireless redstone to turn it on/off.

**Comment by McJty** [comment]
Can you retest with RFTools Dimensions 4.30beta50 that was just released. I fixed a pretty major bug there. Not sure if this is related but it might be

**Comment by mcjonesmike** [comment]
After Further examination, it seems that my quarry wasn't breaking any blocks, or getting any items. I feel smart...

**Comment by McJty** [comment]
I suppose this is no longer relevant?
