### ISSUE TITLE
[1.10.2] Screens disappearing

### ISSUE THREAD

**Issue by p455w0rd** [McJty/RFTools#736]
Forwarded from MinecraftModDevelopment/MMD-Dev-Server#133 by @Tat2soupRhero : 
=========
Screens disappear when looking down from them

**input from @p455w0rd :**
I believe TileEntity#getMaxRenderDistanceSquared takes care of this. It's either that or 
TileEntity#getRenderBoundingBox ..can't quite recall atm...

**Comment by McJty** [comment]
Do you have a screenshot that shows this?

**Comment by Tat2soupRhero** [comment]
I do not. I believe it is fixed now. Thanks!
