### ISSUE TITLE
Storage module tablet displaying wrong maximum amount of items stored

### ISSUE THREAD

**Issue by phantomholo** [McJty/RFTools#737]
Issue description: the Storage module tablet does not display the correct amount of maximum storage when I click cycle

What happens: maximum number stays at either 100 or 300 when cycling though

What you expected to happen: Storage module tablet to display the correct maximum storage

Steps to reproduce:

Place storage module tier 1 into remote storage (remote id:3)
Place another storage module tier 3 in second remote storage slot(remote id:2)
Place remote storage module beside tier one storage module to obtain remote id of 3
Place the same remote storage module in the slot beside tier 3 storage module to obtain remote id of 2
Open the storage module tablet and click cycle, number sometimes stays at 100 for both pages or stays at 300 on both pages
Version (Make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge: 12.18.1.2076
RF Tools version: rftools-1.10-5.22
Does this issue occur on a server? Singleplayer world

**Comment by McJty** [comment]
Fixed next release
