### ISSUE TITLE
[1.7.10] Advanced Charged Porter Duped Player

### ISSUE THREAD

**Issue by Hazmatik** [McJty/RFTools#738]
So I sneak + right click to bind the Advanced Charged Porter to a Matter Receiver and then when I used it to TP there it created a duplicate player. This has happened to me twice in the same day now. The first time it happened I was able to literally kill myself which then duped my inventory in the grave from Openblocks. The second time it happened it was in an area on the server where PvP is not allowed so I couldn't kill the clone.

Modpack: Unabridged r13 (ATLauncher)
RFTools Version: 4.23

Screenshots:
First Time:
![2016-09-13_14 10 06](https://cloud.githubusercontent.com/assets/8119393/18497787/6c303bee-79ff-11e6-88f5-31f548a536fe.png)

Second Time:
![2016-09-13_22 03 02](https://cloud.githubusercontent.com/assets/8119393/18497771/442713b6-79ff-11e6-8134-8c6533688fab.png)

**Comment by McJty** [comment]
Has been reported before but I have no clue what causes this and I'm also no longer doing 1.7.10 development
