### ISSUE TITLE
[1.10.2] Crash on startup

### ISSUE THREAD

**Issue by jwmwebdev** [McJty/RFTools#739]
Recently downloaded the update to rftools. It crashes before minecraft can fully load. The crash report is attached. It seems to not be able to find a certain class from within the McJtyLib class? "java.lang.NoClassDefFoundError: mcjty/rftools/blocks/generator/CoalGeneratorTileEntity" Or do I need to update my forge?

Forge 2073. RFTools 1.10-5.23 . McJtyLib 1.10-2.1.0

[crash-2016-09-17_09.30.47-client.txt](https://github.com/McJty/RFTools/files/478192/crash-2016-09-17_09.30.47-client.txt)

**Comment by McJty** [comment]
I think you may have to upgrade forge

**Comment by jwmwebdev** [comment]
Updating my forge version to 2089 (latest as of this typing) fixed this problem. Is it possible that the mod's minimum forge version is not updated, or am I overthinking? Either way this is fixed.
