### ISSUE TITLE
Essence for other dimlets

### ISSUE THREAD

**Issue by Veggetossj** [McJty/RFTools#74]
Currently there are only some essences for creating dimlets in a dimlet worktable, not all dimlet can be created because there exist no essence for that type of dimlet.

For example i am able to break down a terrain type dimlet, but because there is not sort of essence for this, i cant make this type of dimlet in the work table.

**Comment by McJty** [comment]
Yes I know. I plan that in the very near future. Probably next release.

**Comment by Veggetossj** [comment]
ok cool :)
