### ISSUE TITLE
[1.10.2] game crash when opening gui

### ISSUE THREAD

**Issue by MikeJazz** [McJty/RFTools#740]
I installed RFT and RFT Control through the curse launcher to try out RFT Control.

Whenever i try to open an GUI I get a crash.
The three latest crashes.

Powercell:
[crash-2016-09-18_09.57.07-client.txt](https://github.com/McJty/RFTools/files/478586/crash-2016-09-18_09.57.07-client.txt)

Processor:
[crash-2016-09-18_09.50.51-client.txt](https://github.com/McJty/RFTools/files/478587/crash-2016-09-18_09.50.51-client.txt)

Programmer:
[crash-2016-09-18_09.49.47-client.txt](https://github.com/McJty/RFTools/files/478588/crash-2016-09-18_09.49.47-client.txt)

**Comment by McJty** [comment]
What version of McJtyLib?

**Comment by MikeJazz** [comment]
Ooooooh, the one that installs as a dependency is version 1.9.0-1.8.3, and rftools is 1.9.0-4.46. I'll update both to latest when i get home and try again.

**Comment by McJty** [comment]
RFTools Control can't work with those versions of McJtyLib and RFTools. You need the versions for 1.10.2

**Comment by MikeJazz** [comment]
Yeah, I think it must be the curse launcher that installs the wrong version as a dependency. I only installed RFTools Control, the launcher added McJtyLib and RFTools.
