### ISSUE TITLE
Crash when right clicking or middle clicking items in remote storage module

### ISSUE THREAD

**Issue by phantomholo** [McJty/RFTools#741]
The crash report is here : http://pastebin.com/qCdHrxKz

I'm currently using forge 2088, mcjtylib-1.10-2.1.0 and rftools-1.10-5.23

**Comment by McJty** [comment]
Not a bug in my mods. The crash is in:

at code.elix_x.excore which is a part of FEI.

FEI is known to cause many issues. Please report to them
