### ISSUE TITLE
Crash when placing down a Coal Generator

### ISSUE THREAD

**Issue by MrAmericanMike** [McJty/RFTools#746]
I got this crash on my Dev environment when placing a Coal Generator next to a Power cell.
http://pastebin.com/ScBP1MDt

And this one when trying to launch outside my Dev Environment with just RFTools and the Lib.
http://pastebin.com/K6Q320FQ

Both cases using:
  mcjtylib-1.10-2.1.1
  rftools-1.10-5.23

**Comment by McJty** [comment]
Update forge. It is updated

**Comment by MrAmericanMike** [comment]
Ohh Thanks ;) I forgot to check that.

**Comment by MrAmericanMike** [comment]
Now the error is another :S 
http://pastebin.com/bYW58eVU

The world reloads, but when trying to access another GUI, for example the Power Cell in this case:
http://pastebin.com/J45dFCje

Maybe I'm still using a wrong combination of mod versions?

mcjtylib-1.10-2.1.1
rftools-1.10-5.23
Updated to Forge 12.18.1.2092

**Comment by McJty** [comment]
Yes, you don't have JEI.

Apparently my mods now have a hard dependency on JEI due to a wrong AT. I'll fix that but for now I recommend adding JEI

**Comment by MrAmericanMike** [comment]
Thanks. I guess I'm used to Forge telling me when a mod is missing and needed by others lol. Most the times that wont be a problem on my Packs, but when on Dev Environments and just testing, I try to not use JEI to reduce "Conflicts" in case of any.

Gonna add the newest JEI to both now.

PS: Sorry, a curious question (Totally off-topic), as I make some mods also, I'm not familiar with Energy production (RF) and I'm trying to dig into it. I see you have a COFH Api that works on 1.10.2. Is that something "Official" to use? I want to start with Capabilities and that stuff, and I'm not sure what mod to use to test if what I'm doing is right, that's why I'm adding RFTools to my dev environment to test if "for example" a solar panel I'm trying to make, can charge a battery/cell/capacitor from another mod. But I'm trying both things, using just Forge Capabilities and trying to use COFH Api (I updated the 1.7.10 to 1.10 on my own, but I see that what I did is different to the one you using)
I know you have tutorials and that, not sure where I saw that, do you have any tutorial on things like this?
Sorry to take your time, I'm asking too much already :D

**Comment by McJty** [comment]
The RF API is not really official I'm afraid. It is just that the modding community has ported it manually to 1.10.  The version that I use in McJtyLib is what we unofficially decided as the correct port. So if you want to use RF I recommend to use that

**Comment by MrAmericanMike** [comment]
Thanks a lot, at least now I know I'm not using something I did by my own, but at least something that other modders are using also.
Thanks once again, time to start learning and crashing and debugging and crashing and learning more and fixing and get it working somehow :D
