### ISSUE TITLE
Request (1.10.2) A cheaper early-mid game option for power cell

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#748]
Power cell is cool and all, but even the basic ones are pretty difficult to come by without a lot of luck to finding ocean monument. 
Perhaps a cheaper variant that transmit less power (1k vs 5k) that uses more primitive materials?

I really want to get my base look nice/clean from the get-go without forcibly dragging cable everywhere in early game.

Thanks!

**Comment by McJty** [comment]
Working on it

**Comment by McJty** [comment]
Done
