### ISSUE TITLE
Server Crash- Rf tools elevator - java.lang.IllegalArgumentException: Cannot get property PropertyDirection

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/RFTools#749]
http://pastebin.com/LhnBnbFS

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:gravel, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at mcjty.rftools.blocks.elevator.ElevatorTileEntity.isPlatformHere(ElevatorTileEntity.java:574)
	at mcjty.rftools.blocks.elevator.ElevatorTileEntity.func_73660_a(ElevatorTileEntity.java:92)

**Comment by McJty** [comment]
What did you do exactly? Try to use gravel as the block to move?

**Comment by ProsperCraft** [comment]
I don't know sorry its a multiplayer server and no players have come forward with an explanation.

**Comment by McJty** [comment]
This seems to be caused by sponge. I don't trust sponge. It is known to cause various issues here and there. There is nothing that I can do about this I'm afraid

**Comment by Zidane** [comment]
@McJty 

This has literally nothing to do with Sponge.

https://github.com/McJty/RFTools/blob/1.10/src/main/java/mcjty/rftools/blocks/elevator/ElevatorTileEntity.java#L574

Your code calls getBlockState from the World by passing in your pos. The blockstate at the Pos is gravel. Gravel has no facing direction.

Not a Sponge problem.

**Comment by McJty** [comment]
Note where that pos comes from. That's the position of MY tile entity (calling getPos() in my TE). How can my tile entity be at a position where gravel is? That never happens otherwise and Sponge *is* in the stacktrace if you look at it closely
