### ISSUE TITLE
RFTools breaks destabilizes/breaks /help

### ISSUE THREAD

**Issue by Aedda** [McJty/RFTools#75]
According to Help Fixer and my own review the compareTo() method in com/mcjty/rftools/commands/DefaultCommand.java is invalid and as such will randomly break help.

Solution below, I still don't know how to do a proper PR or I would...

@Override
public int compareTo(Object o) {
    return 0;
}

to

@Override
public int compareTo(Object o) {
    return getCommandName().compareTo(((ICommand)o).getCommandName());
}

**Comment by McJty** [comment]
Fixed in next release.
