### ISSUE TITLE
creation cost of dimlets too high

### ISSUE THREAD

**Issue by danksquaw** [McJty/RFTools#750]
I'm playing DireWolf20 pack, and I am looking to expand my big reactor. The one I have now produces 6k RF per tick. I wanted to make a yellorite world, so I did and the maintenance cost was like 40k per tick, which I can't maintain. So I gave it efficiency dims and now it's down to 5k, but the creation cost is 700k rf for 7k ticks, which is like 5 billion RF. With my power system, that would take over 11 hours straight just to create the dimlet. Yellorite isn't too common in a normal world, how am I supposed to create that?

**Comment by McJty** [comment]
People usually complain that RFTools is too easy to do this not the other way around :-)

Anyway, for a powerful ingredient like yellorite I'm afraid you have to pay a lot of power.
