### ISSUE TITLE
Bug: Developer's Delight and Teleport Probe are usable without actually having the item.

### ISSUE THREAD

**Issue by calvinbalke13** [McJty/RFTools#755]
If the Developer's Delight or Teleport Probe is added to the client-side inventory without actually being in the server-side inventory and it is used, it will still work.  There should be a check in the packets which checks if the Developer's Delight or Teleport Probe is in the player's hand before doing what the packets request.

**Comment by McJty** [comment]
I can't fix this for the developers delight item as it is fully client side. So there is no packet to the server.

With the teleport probe I can also not easily prevent opening the GUI but I can prevent the teleport. So I'll do that then

**Comment by McJty** [comment]
The probe abuse is fixed next release
