### ISSUE TITLE
[1.10.2] Dimlets in Chests in a RFTools Dim show a 0 Number

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/RFTools#756]
![mmd](https://cloud.githubusercontent.com/assets/10524952/18815420/049407c6-8374-11e6-9833-3ad3d78d844f.png)

When going to chests within this Dimlet, the chests often show dimlets as a 0 number and dissapear when clicked on or when using the chest sorting

**Comment by McJty** [comment]
I cannot reproduce this all but it has been reported lots of times. However, I did a blind fix which I hope fixes the problem next release. Reopen if this still happens (for new generated chests, chests that are already generated will remain broken)

**Comment by Morpheus1101** [comment]
Once curse shows the update i'll give it a test and see how things go.
