### ISSUE TITLE
Unable to craft items that have an empty slot in recipe

### ISSUE THREAD

**Issue by MakeLord95** [McJty/RFTools#758]
When playing I noticed that I can't shift-click any items from JEI that have an empty slot in the crafting recipe. Only RFTools items weren't working.

Forge .2094
McJtyLib: 1.10-2.1.3
RFTools: 1.10-5.24

Forced Crash Report: http://pastebin.com/QGbCyghT
![2016-09-27_17 14 53](https://cloud.githubusercontent.com/assets/3233364/18877687/a2da04b8-84d6-11e6-9ee7-2c6dcaadab5a.png)

**Comment by McJty** [comment]
Hmm @mezz, any idea what could cause this?

What crafting station are you using btw?

**Comment by MakeLord95** [comment]
This happens on EnderIO Inventory Panel, vanilla crafting bench and TiC workbench

**Comment by MakeLord95** [comment]
I just tested this with only JEI, RFTools, RFTools Control, RFTools Dim, McJtyLib using a vanilla crafting table. Still happens

**Comment by McJty** [comment]
What version of JEI are you using?

**Comment by MakeLord95** [comment]
3.11.2.278

**Comment by MakeLord95** [comment]
I tested this with JEI .276 and it worked, but .277 -> not working

**Comment by McJty** [comment]
ok that's an important clue. Might be a bug in JEI instead of RFTools then

**Comment by MakeLord95** [comment]
weird thing is that with other mods it works fine. Only one not working is RFTools

**Comment by McJty** [comment]
Yes, but this crafting recipe copying is not something that rftools is doing. Taht's fully JEI code

**Comment by mezz** [comment]
This is almost certainly a JEI issue, I'll take a look.

**Comment by mezz** [comment]
The key thing that changed is the way JEI handles null ingredients.
RFTools' Machine Frame has a null ingredient in the center.
Before, null ingredients were removed from `IGuiIngredient` rotations. Now they are kept, so people can have null in the list of ingredients for a slot.

The recipe transfer handler did not take this into account, I'll fix it shortly.

**Comment by mezz** [comment]
Fixed in JEI 3.11.2.280

**Comment by McJty** [comment]
Thanks!
