### ISSUE TITLE
Dimension Builder and Machine Vanishing

### ISSUE THREAD

**Issue by permdaddy** [McJty/RFTools#76]
I made a dimension. 
It was crazy. 
I took it out, disassembled it, changed it a little, and reassembled it. 
I put it back into the builder. 
It built up to 99% and then the machine just vanished, taking the dimension inside it with it. 
It is just gone.

**Comment by permdaddy** [comment]
Ok it looks like the server deletes blocks that are about to crash it so that what happened there.

**Comment by McJty** [comment]
Hmm, that's weird. Do you also know what the crash was? Does the server keep a log of that somewhere?

**Comment by McJty** [comment]
Closing due to lack of information.
