### ISSUE TITLE
[1.10.2][5.24] Crash involving RFTools Endergenic Generator and Integrated Dynamics

### ISSUE THREAD

**Issue by Aedda** [McJty/RFTools#763]
Steps to reproduce:
1) Connect an Integrated Dynamics (ID) Machine Reader to an RFTools Energenic Generator
2) Connect ID Logic Cable, followed by ID Display Panel
3) Right click ID Machine Reader to open GUI. Click scroll bar or attempt to scroll.

Game should crash at this point.

I successfully connected ID to the following machines:
RFTools Crafter Tier 1
RFTools Matter Beamer
Mekanism Crusher
Mekanism Energy Cube
EnderIO SAG Mill
EnderIO Capacitor Bank
Immersive Engineering Fluid Pump
Immersive Engineering Capacitor

Versions of mods used:
Minecraft 1.10.2
Forge 2093
RFTools 5.24
Mekanism 9.2.0.292
EnderIO 3.0.1.112_beta
Immersive Engineering 0.10-42
Integrated Dynamics 1.9.4-0.5.1

Crash report:
https://gist.github.com/Aedda/8d5b81ac6d8d06c4383ddb0b928fd805

**Comment by McJty** [comment]
I think the bug is in integrated dynamics. It may have a wrong version of the CoFH API or something. Did you report to them?

**Comment by Aedda** [comment]
Not yet, I will do so now.

**Comment by rubensworks** [comment]
My (author of ID) bad, I was doing a wrong cast, this can be closed.
