### ISSUE TITLE
Broken texture image in sky for various dimensions

### ISSUE THREAD

**Issue by RealGrep** [McJty/RFTools#765]
I've been seeing the magenta two offset squares thing in the sky somewhat often in various dimensions. First time, I thought it might be some sort of double moon/planet or something. But last night, there were giant ones wrapping around the sky, and it was quite obvious. Doing /rftdim info [dim number here] told me it was supposed to be the inferno sky. I do have a screenshot, but I'm pretty sure you know what the broken texture thing looks like. :)

rftools-1.10-5.26.jar, rftoolsdim-1.10-4.40.jar, mcjtylib-1.10-2.1.3.jar, on Forge 2094 and MC 1.10.2.

**Comment by McJty** [comment]
Hmm I'll check it out. Did you have any celestial bodies in your dimension?

**Comment by RealGrep** [comment]
I'll take a look shortly at the inferno one to find out. Just needed to MCEdit out some blocks because Chisel is causing Botania to crash the client on load. Yay.

**Comment by RealGrep** [comment]
The complete info is:

Dimension ID 7
Description string @Bminecraft:mutated_swampland,CSingle,#mminecraft:stone@0,TFlat
Owned by: Addle42
  Base seed: 1956332983
  World version: 1
  Terrain: TERRAIN_FLAT
    Base block: Stone
    Base fluid: null
  Biome controller: CONTROLLER_SINGLE
  Biome: Swampland M
  Sun brightness: 1.0
  Star brightness: 1.0
  Sky color: 0.0, 0.6, 0.6
  Fog color: 1.0, 1.0, 1.0
  Sky type: SKY_INFERNO
  Weather rain: 1.0
  Mob: net.minecraft.entity.monster.EntitySilverfish

Doesn't seem to say there, but looking around, all I have in the sky are giant magenta offset squares wrapping around the horizon. I see no celestial bodies.

A lovely dimension, isn't it? As a side note, I forgot to put it back in the Dimension Builder before going to look for celestial bodies, and died in a collapsing world. Go me. lol

P.S. Button doors still suck.

**Comment by McJty** [comment]
Fixed next release. Note try to report dimension issues in the RFTools Dimension issue tracker

**Comment by RealGrep** [comment]
Thanks! And oops, I derped. I did mean to report it in the RFTools Dimensions issue tracker, I swear. XD
