### ISSUE TITLE
[request] Dimlet Storage System

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#77]
Hey there.

While attempting to store lots and lots of dimlets it occurred to me that it would be pretty handy to have a catalogue system dedicated to their storage and retrial. I'm not sure if something like this is already in your plans but it would definitely help reduce the clutter.

At the moment the optimum method seems to be to stash them in a filing cabinet from extra utilities. Maybe you can come up with something better?

**Comment by Skar78** [comment]
I also think that would be a great addition.

I dont know why but I was thinking of something that could be placed next to the enscriber and could be accessed from the describer menu. Similar as TiC workbenches can access nearby chests.

"Dimlet Archiver" storing all dimlets and neatly sorting them - with rf cost increasing by amount of dimlets stored.

**Comment by McJty** [comment]
Yes, this is still on my todo and I also considered the 'placing next to enscriber' idea. Currently busy with something else but I'll probably start on this after that has finished.
