### ISSUE TITLE
Hollow hand (??) Issue with version 5.50

### ISSUE THREAD

**Issue by Alaberti** [McJty/RFTools#772]
Tore apart my modpack trying to find this, updating to this version causes the top side of the hand in first person only (afaik) to not render. No optifine or anything else (except the KH mod, but the problem goes away when I take out your mod)

![2016-10-07_15 46 56](https://cloud.githubusercontent.com/assets/10929796/19205172/5afd8390-8ca6-11e6-8750-8d960f732dea.png)

**Comment by McJty** [comment]
Will fix

**Comment by McJty** [comment]
Fixed in 5.51 (in a few minutes)

**Comment by Alaberti** [comment]
Thanks!
