### ISSUE TITLE
[1.10.2][5.51] Powercell doesn't support new Forge Energy API

### ISSUE THREAD

**Issue by ckaraviotis** [McJty/RFTools#774]
I've been implementing the new Forge Energy API on a project, and I'm using RFTools to test compatibility. When I connect an Powercell to a simple Forge Energy generator, on energy is received. When I connect a Matter Transmitter, energy is received by the transmitter correctly. No wires are used, connections are block-to-block.

I had a look through your code and it seems like the Powercell is extending GenericTileEntity (and directly implements cofh EnergyProvider/Reciever), which doesn't provide the new energy capabilities as in GenericEnergyHandlerTileEntity, GenericEnergyProviderTileEntity & GenericEnergyReceiverTileEntity

rftools-1.10-5.51.jar
mcjtylib-1.10-2.1.4.jar

**Comment by McJty** [comment]
Ok, that's an oversight. I will fix this in the next version

**Comment by ckaraviotis** [comment]
Just did some further testing, and your items also don't expose capabilities, so they can't be charged by forge energy. The items are rftools charged porter & advanced charged porter, Rftools dimensions: dimension monitor & phased field generator.

**Comment by McJty** [comment]
The items was actually intentional as it seemed pretty complicated to implement forge energy on them (and not efficient). But it seems there is a better way so I might still do it

**Comment by McJty** [comment]
Fixed next release:
  * Powercells will receive forge energy
  * Powercells will charge items with forge energy
  * Charged porter and tablet support being charged with forge energy now
