### ISSUE TITLE
[1.10.2] Quarry does not use the Storage Filter Module

### ISSUE THREAD

**Issue by TWJedi** [McJty/RFTools#777]
I am using a Silk Quarry setup to send items through a Dimensional Transceiver to my base. I installed a Storage Filter Module, but the Quarry ignores all of the settings in the filter.

Here is a picture album: http://imgur.com/a/25SBf

As you can see, the Filter is set to whitelist only specific blocks. But the Quarry is still mining all blocks.

Minecraft version: 1.10.2
RFTools version: 5.51
Forge version: 12.18.1.2095

**Comment by McJty** [comment]
ah. I think I know what's wrong. I forgot to implement this for the silk quarry module. I will fix that later today

**Comment by McJty** [comment]
Fixed next release
