### ISSUE TITLE
Enviromental Controller No Teleport Effect isnt 100% on enderman

### ISSUE THREAD

**Issue by sherkas** [McJty/RFTools#783]
I have a simple spawner setup that has caused much issue in my world. I dont think the enviromental controller is applying the no teleport effect strong enough on enderman.

I had setup a void world with a simple walkway and room for enderman spawner. It spawns them, they converyor into a shield wall which kills/loots them from underneath. A simple setup.

The enviromental controller is doing a 32 radius and the enderman are still over time teleporting out of the kill room. 

I setup a test spot to see why enderman were causing me issues and with a 4xender io spawner with oct upgrades (lots of enderman) it took maybe 5 minutes and I had 40+ enderman outside the kill chamber.

It was a enviromental controller with 0-100 (we sat at about 60 Y) with radius 100 and it was fed with creative power. (A maximum no teleport zone). I then did the above spawners with a RFTools shield box to kill on drop and after 5 minutes there was 40+ enderman around me.

Im 100% convinced enderman are escaping before the no-teleport is applied. Is there something more I can test or do for this?

**Comment by McJty** [comment]
Was the environmental controller set to affect hostile mobs? By default it doesn't

**Comment by ozymandiasocabe** [comment]
Thanks for this, McJty.  I had the same problem and did not see that setting in the environmental controller.

**Comment by McJty** [comment]
I got no answer to the original question so I suppose this is solved
