### ISSUE TITLE
Major dup bug with builder and crafter

### ISSUE THREAD

**Issue by tod** [McJty/RFTools#786]
1) put crafter on top of builder
2) configure crafter to have block you want to dub "remembered" in the input area
3) build giant structure with duped block

I discovered this by setting up a crafter to take IE hemp->string->wool and I wanted it to build the thing with wool. I used cobble to fill up the extra spots in the crafter I didn't need. When I build the structure, it duped the cobble. I then tested again using clay instead of cobble and it duped that. I haven't tested if it can dup everything, but I don't see why it wouldn't.

**Comment by tod** [comment]
I just tested, and you have to leave the extra items (cobble/clay) in the crafter

**Comment by McJty** [comment]
I will check this out tomorrow. Thanks for letting me know

**Comment by McJty** [comment]
Fixed next release (later today)
