### ISSUE TITLE
[Request][RFTools Control] Show instruction position under mouse in Programmer

### ISSUE THREAD

**Issue by Aedda** [McJty/RFTools#791]
One thing I am finding tedious with RFTools Control program debugging is finding the related instruction to an error, "[7,5] Internal Error" and having to count 0 1 2 3 4 5 6 7 0 1 2 3 4 5 to find the offending instruction. It would be most helpful if the position of the cell under the mouse could be displayed somewhere in the GUI or as a tooltip.

**Comment by McJty** [comment]
Nice suggestion. I'll do that

**Comment by McJty** [comment]
Implemented but btw, wrong issue tracker :-)
