### ISSUE TITLE
Builder: Torus shape card makes hollow sphere

### ISSUE THREAD

**Issue by ronsardis** [McJty/RFTools#793]
Version 5.53 in allthemods pack
the builder makes a hollow sphere when given a shape card with torus selected.

![2016-10-19_22 16 15](https://cloud.githubusercontent.com/assets/20866241/19535899/d6e61cae-9649-11e6-9601-7b0978833784.png)

**Comment by Bebabo10** [comment]
have u tried a bigger radius ?

**Comment by ronsardis** [comment]
half a sec, will try

**Comment by ronsardis** [comment]
it worked with bigger, my bad.
![2016-10-19_22 23 12](https://cloud.githubusercontent.com/assets/20866241/19536054/a425d0ba-964a-11e6-93ad-a7ca25458431.png)

**Comment by McJty** [comment]
You can control both the outer and inner radius with the x and y dimensions. That way you can make the torus any shape you want
