### ISSUE TITLE
No Teleport Module prevents Matter Transmitters from teleporting

### ISSUE THREAD

**Issue by Timecheater** [McJty/RFTools#797]
I have this Issue on both Hermitcraft and Ftb Unstable so this seems to be 10.2 bug

My Matter Transmitters spam me with start teleportation... message but don't actuallly teleport me.
I played around with them a bit and realized that this only happens near my base, i checked everything that affected the area around it and found the No Teleport Module in the Environmental Controller to be the problem. I know that it is supposed to stop teleportation but it only refers to endermen in the tooltip so i am assuming it is a bug.

**Comment by McJty** [comment]
No it is not a bug
It will stop all teleportation. But you have to set the environmental controller to only work on hostile mobs. Not on players. It has an option for that in the gui. That way it will only affect enderman
