### ISSUE TITLE
Disable Ore Dictionary Dimlets

### ISSUE THREAD

**Issue by Gideonseymour** [McJty/RFTools#80]
I'm using a version of RFTools built off of the current github (2.53) and I was looking through the ore dimlets, and found that there were quite a few dimlets made from ores that were basically useless for my pack.

I looked into the dimlets.cfg, and found that those dimlets did not appear there. I know that they can be disabled via dimlets.json, but it would be beneficial to be able to disable them via the dimlets.cfg like other dimlets.

**Comment by McJty** [comment]
You can actually do that. You can still put <...>.id = -1 in the knowndimlets section of the config. You just have to find the name. An easy way for that is to dump all dimlets in game: /rftdim dumprarity

**Comment by Gideonseymour** [comment]
Oh, thanks!
