### ISSUE TITLE
[1.10.2] [bug] - items crafted in modular storage crafted to void because of no room in inv

### ISSUE THREAD

**Issue by ronsardis** [McJty/RFTools#802]
RFTools ver 5.56 in AllTheMods pack ver 1.39

Inside a modular storage if you craft an item but do not have room in inventory or one of the items on the card in the modular storage the item just disappears on being crafted.  It uses the resources but the item is not given or stored.

In the testing I did I used an iron block turned into ingots with no inventory room and no iron ingots inside the modular storage machine's card.  I had it happen the first time when turning draconium blocks into ingots.

here is a link to a video I made demonstrating the bug.

https://drive.google.com/file/d/0B7HlAwkXQZlRN2s5cHR5cG5fVWM/view?usp=sharing

**Comment by McJty** [comment]
The item should drop on the ground. Did you check that that didn't happen?

**Comment by ronsardis** [comment]
yes, that is why I exited the machine to show no item on the ground in the video

**Comment by McJty** [comment]
I cannot reproduce this. For me the items fall on the ground as they should. Are you sure there is nothing sucking up the items? Also the items can fall pretty far from the storage

**Comment by ronsardis** [comment]
It might possibly be an issue with multiplayer as I am on a server.  I know for sure it is not something sucking up the items.  I will share this with the server admins and we can see more from there perhaps.

Thanks,
Ron

**Comment by ronsardis** [comment]
I am unsure what exactly the server admins did but now it is no longer destroying the items, but throwing them.  If I can get more info from them I will notify you.

Thanks for your hard work with the mod,
Ron
