### ISSUE TITLE
[1.7.10] Server hanging when loading RFTools dimension

### ISSUE THREAD

**Issue by elijahlorden** [McJty/RFTools#807]
We have encountered a strange issue that occurs sometimes when the server attempts to load an RFTools dimension.  It appears to happen randomly, and no matter what type of dimension is loaded (Normal, Void, etc).  The issue can occur either when a player enters a dimension, or when they log into the server already in a RFTools dimension.  We are using RFTools v4.23, log file included.
[fml-server-latest.txt](https://github.com/McJty/RFTools/files/560076/fml-server-latest.txt)

**Comment by McJty** [comment]
This is weird. There seems to be a matter transmitter behaving weirdly for some reason. Perhaps try removing that and replacing? Other then that this kind of problem is extremly hard for me to debug

**Comment by elijahlorden** [comment]
That has not fixed the issue.  Is there anything I can do to provide more information?  We did not have this problem on our previous server, and we were running the same version of RFTools.

**Comment by McJty** [comment]
What modpack is this?

**Comment by elijahlorden** [comment]
We are using a custom set of mods, here is a list: http://prnt.sc/d0jrft

**Comment by McJty** [comment]
Then the only thing I can imagine is some kind of mod conflict but not sure how to find that out.

**Comment by elijahlorden** [comment]
Thank you for your quick responses.  We are going to try using Mystcraft and see if we encounter the same issues.  This will at least tell us whether or not the issue is RFTools-related.

**Comment by McJty** [comment]
Do you have this always and on every rftools dimension? Because in the first post you seemed to indicate it only happened sometimes?

**Comment by elijahlorden** [comment]
At first it only happened sometimes, but currently It is happening every time a RFTools dimension is loaded.

**Comment by McJty** [comment]
I'm out of clues. Never heard a report like this before as well

**Comment by elijahlorden** [comment]
Interesting...  The other person running the server with me Has indicated something to the effect of RFTools only using one of the server's cores, and switching between them repeatedly.  I do not have an extensive knowledge of hardware, so I am not able to elaborate on the issue.

**Comment by elijahlorden** [comment]
Alright.  The same issue is happening with Mystcraft dimensions.

**Comment by elijahlorden** [comment]
It appears that this is completely unrelated to RFTools.  I have just checked the Warpdrive space dimension, and it is happening to that one aswell.

**Comment by McJty** [comment]
aha ok. That is good to know

**Comment by elijahlorden** [comment]
Since this is not an RFTools issue, should this issue be closed?

**Comment by McJty** [comment]
yep
