### ISSUE TITLE
[Bug] Builder with Quarry Card/Filter Fluid Interaction

### ISSUE THREAD

**Issue by Mohron** [McJty/RFTools#809]
RFTools: rftools-1.10-5.56.
McJty: mcjtylib-1.10-2.2.0

When using the builder as a quarry with a white-list filter, the builder still quarries fluids. If using a standard quarry card this means they get replaced with dirt instead of the expected behavior, being ignored.

**Comment by McJty** [comment]
Yes, I have also noticed this. Will fix for next version

**Comment by McJty** [comment]
Fixed next release
