### ISSUE TITLE
Crash when using the builder to make a wither

### ISSUE THREAD

**Issue by utoc** [McJty/RFTools#813]
Good morning!  A user was trying to use the builder to make withers and crashed the server.  This is pretty straightforward

Some pictures here: http://imgur.com/a/JqBFn
Crash here: http://pastebin.com/bCRLi0CY

rftools-1.10-5.57, mcjtylib-1.10-2.2.0 with FML 2114

Let me know if you need any other information!

**Comment by McJty** [comment]
Fixed next release
