### ISSUE TITLE
[5.57] Crash when teleporting to RFDimension

### ISSUE THREAD

**Issue by Crazy-KSK** [McJty/RFTools#816]
https://gist.github.com/1188aaaa51c011f151d7ef4e11e2a0d0
I'm pretty sure the dimension tab got destroyed
The crash happens where the world would normal start loading after entering the teleporter

**Comment by McJty** [comment]
Link doesn't work

**Comment by Crazy-KSK** [comment]
Fixed the link
I also found out some more; There seems to be some underlying RFTDim bug that is repeatably causing newly created dimension tabs to show "Dimension information Missing!" after restarting minecraft and subsequently refusing to work and as a result of that the matter transmitter breaks and causes aforementioned crash on trying to teleport.

**Comment by kurokuno** [comment]
can confirm also happening to me all worlds get deleted on restarting minecraft all  become invalid

**Comment by McJty** [comment]
There is no crash in the provided log so that's not very useful for me. Does it crash client or server side? Is this single or multiplayer?

Sorry people, but I am going to need a lot more information then this. What exactly is your minecraft setup? Are you using a server? And I would need a real crash log.

**Comment by kurokuno** [comment]
thats sort of the problem jty there is no real crash log using the lastest RF tools dim thats public make a dimension in single player close mc open it back up the world is corrupt and gone and teleporting there of course crashes with a generic error as there is no dimension to go to

**Comment by McJty** [comment]
Well then I need more info on the mods you're using. Note that rftools dimensions *is* being used with no issues by several people so there must be something specific in your setup of mods that is causing this issue. Also did you try other dimension mods?

**Comment by kurokuno** [comment]
other dimensions seem to work fine its only RFtools dims i can post up a full mods list give me a few

**Comment by kurokuno** [comment]
http://pastebin.com/skZwc11w there we go

**Comment by McJty** [comment]
Does this happen for every single dimension? How many did you try? Does the dimension itself work while you're in it the first time?

**Comment by kurokuno** [comment]
every one i make yes i can go in there it works perfectly its only when closing out of minecraft fully down then restart it the world comes out like http://imgur.com/a/CUIpz this

**Comment by McJty** [comment]
Are you doing anything special when starting your world? What launcher are you using? That information is stored in a special location (saves/YourWorld/data/RFToolsDimensionManager.dat). It looks as if somehow that file is getting corrupted or overwritten

**Comment by kurokuno** [comment]
i am using curse saving is done normally nothing special at all other than firing it up make a dim then close and re-open and boom i will try making a dim in a brand new world just to make sure its not sthing strange like that but if  that does not work i can just drop you my mods/config folder if you would like so you can take a look see if its possible to de-bug whatever the hell cross mod conflict is causing it

**Comment by McJty** [comment]
I am also interested in the full log (the biggest logs in your logs folder) btw. Would like to see if there is something special in there

**Comment by kurokuno** [comment]
i will gladly send you everything i have on the instance see if you can work it out like 95% of the errors i get i can explain from a code stand point even and report accurately this just seems very obscure almost like on world load its losing the world info

**Comment by kurokuno** [comment]
https://www.dropbox.com/s/4h20lpfk2bbt2gx/mcinstance.rar?dl=0 thats the instance logs included no saves for size but it seems to happen in any world just make a quick world power it go in teleport back then close down mc all together open it back up and the world is broken using latest forge on curse

**Comment by McJty** [comment]
Not 100% sure but it *might* be a conflict with hardcore wither. I submitted a bug report to them:

https://gitlab.com/thor12022/HardcoreWither/issues/54

It would be great if you could temporarily remove that mod and try in a new world to see if the problem still occurs. That way we know for sure if it is that mod or not.

Thanks

**Comment by kurokuno** [comment]
welp i removed it and its still doing it sadly D'=

**Comment by McJty** [comment]
On a new world with new dimensions?

**Comment by kurokuno** [comment]
yeppers removed all the RFtools world files made a new world all together then made a new dim in that and still does it

**Comment by McJty** [comment]
Ok then (for now) I give up. No clue what can cause this

**Comment by Crazy-KSK** [comment]
you have to click on the banner at the top to see the part of the log with the crash 
"This file has been truncated, but you can view the full file."

I'm going though adding mods one by one right now looking for the culprit

**Comment by Crazy-KSK** [comment]
Success! I replicated it with only these 3 mods so it looks like JEI is the mod causing the worlds to corrupt
forge-1.10.2-12.18.2.2118
jei_1.10.2-3.13.0.341
rftools-1.10-5.57
rftoolsdim-1.10-4.43

and another time the crash log of trying to teleport to it with the RFTools block
https://gist.github.com/b9c27e41418f355cac830bd3daabefec

**Comment by kurokuno** [comment]
well that or some change to the newer forges

**Comment by McJty** [comment]
@mezz_mc Any explanation for how JEI could cause that?

**Comment by McJty** [comment]
I can reproduce this with that verison of JEI. We will investigate this
@mezz I can reproduce this now. Seems that version of JEI causes an issue with the rftools dimension information. Most likely cause is that fake world but as of now I have no clue why. This is a pretty critical bug though. Completely breaks my mod

**Comment by McJty** [comment]
Bug if fixed in 4.44
