### ISSUE TITLE
Liquid Monitor not working MC 1.10.2

### ISSUE THREAD

**Issue by Animal7865** [McJty/RFTools#818]
Attempting to set up Liquid Monitor to control Lava Levels in Deep Resonance Tank for refinement process.

deepresonance-1.10-1.2.9
rftools-1.10-5.57
Forge 12.18.2.2114

**Comment by McJty** [comment]
Works fine for me so you will have to give more information. Like a screenshot or some description of what you're doing

**Comment by Animal7865** [comment]
So i have the Liquid detector adjacent the Tank, and its set to emit when liquid levels > 40%.  Placed Redstone Lamp on top.  As you can see from images below, it does see the tank, and the tank is at 50%.


![image](https://cloud.githubusercontent.com/assets/23202950/19942986/88b990b4-a103-11e6-9517-c6fdb0eea21b.png)


![image](https://cloud.githubusercontent.com/assets/23202950/19943001/9e3b894c-a103-11e6-8572-24b6704e7929.png)

**Comment by McJty** [comment]
The redstone only is at the back of the liquid monitor (where the red arrow is). There is no redstone coming out at the top

**Comment by Animal7865** [comment]
Thanks... I tried that (I thought) but now it appears to be working :)..

![image](https://cloud.githubusercontent.com/assets/23202950/19945822/d009edc2-a10f-11e6-8729-4a2c90b034bb.png)
