### ISSUE TITLE
Builder no longer pumps molten metals in 5.56

### ISSUE THREAD

**Issue by JosiahpMartin** [McJty/RFTools#820]
I upgraded from 5.53 to 5.56 and the builder will not pump any molten metals, but it did work fine with lava and a few other liquids. I reverted back to 5.53 and it started pumping molten metals again.

**Comment by McJty** [comment]
That doesn't make sense. Nothing has changed there. Can I see your setup?

**Comment by JosiahpMartin** [comment]
This is an unrelated crash log with my setup.  
[crash-2016-11-03_03.09.37-server.txt](https://github.com/McJty/RFTools/files/569190/crash-2016-11-03_03.09.37-server.txt)
This is the latest log with rftools 5.56 
[fml-client-latest.txt](https://github.com/McJty/RFTools/files/569231/fml-client-latest.txt)

**Comment by McJty** [comment]
That crash is in Refined Storage. Not in RFTools

**Comment by JosiahpMartin** [comment]
Yes, I only uploaded it because its easier to see my setup.  rftools never crashed.

**Comment by McJty** [comment]
What tank are you using btw?

**Comment by JosiahpMartin** [comment]
I'm using the extrautilities drum and the quantum storage tank.  I just removed every mod except extrautilities, jei, mantle,and mcmultipart with no luck.

**Comment by JosiahpMartin** [comment]
Do you know if anyone else is having this issue?  I could try doing a fresh minecraft/forge install if i'm the only one.

**Comment by McJty** [comment]
Checking it out

**Comment by McJty** [comment]
BTW, which liquids exactly are not working? Can you be more specific?

**Comment by JosiahpMartin** [comment]
I just did a fresh minecraft and Forge install and it still doesn't work.  
Here is a list of every fluid I have tried.  Using a builder with a clearing pump module and extrautilities' drums above and below the builder, i first tested it by placing water and lava, which it succesfully pumped and filled the drums.  After replacing the drums with empty ones, I systamatically tested each of these fluids:
Tinkers Construct fluids: molten iron, molten pigiron, molten knightslime, molten cobalt, molten ardite, molten manyullyn, molten gold, molten stone, molten obsidian, molten clay, liquid dirt, molten emerald, molten glass, blood, milk, liquid blue slime, liquid purple slime, molten copper, molten aluminum brass, molten aluminum, molten lead, molten silver, molten nickel, molten electrum, molten steel, molten tin, molten bronze, molten zinc, molten brass, molten chrome, molten invar, and molten platinum.  
Substranum: liquid redstone, liquid glowstone, and liquid enderpearl.
Foundry: liquid iron, liquid gold, liquid copper, liquid tin, liquid bronze, liquid electrum, liquid invar, liquid nickle, liquid zinc, liquid brass, liquid silver, liquid steel, liquid cupronickel, liquid lead, liquid platinum, liquid aluminium, liquid chromium, liquid signalum, liquid lumium, liquid enderium, liquid alumina, liquid manganese, and liquid titanium...didn't feel like testing the rest.
AbyssalCraft: liquid coralium, and liquid antimatter.
Biomes O' Plenty: Poison, blood, honey, and quicksand. 
EnderIO: Cloud seed, conecentrated cloud seed, rocket fuel, vapor of levity, liquid sunshine, and hootch
Forestry: Ethanol, biomass, honey, crushed ice, fruit juice, seed oil, and short mead.
Immersive engineering: Molten uranium, and molten constatine.
Industrial craft: uu-matter, construction_foam, coolant, hot_coolant, pahoehoe_lava, biomass, biogas.

So as you can see only lava and water are successfully pumped. Could it have something to do with the fluid registry? I find it strange that it worked in 5.53 and not 5.54+.

**Comment by McJty** [comment]
I have some ideas

**Comment by McJty** [comment]
I know what is wrong. Will fix soon

**Comment by McJty** [comment]
Fixed next release (soon)
