### ISSUE TITLE
Issue: Elevator module stops only lets me label 7 floors

### ISSUE THREAD

**Issue by Kaisoul** [McJty/RFTools#821]
I made about 11 floors with elevators but i can only name 0 to 7    the remaining floors i am unable to label / name.   

Unless there is a cmd that lets me label floors past 7  the gui / coding could use an upgrade for the elevator button modules.

Love the mod just figure i would mention this.

**Comment by McJty** [comment]
Check the gui for the elevator button module. There is a button to enable two colums

**Comment by Kaisoul** [comment]
hmm will go check again.  i just never noticed a way to name floors past 7
:p

**Comment by Kaisoul** [comment]
hmm i still do not see a way to name floors past 0-7 
my floors go from 0-11     and looking at the gui options of the elevator button module  i don't see an option that lets me name floors 8-11.

O_o  am i missing something?

**Comment by xenoflot** [comment]
> Check the gui for the elevator button module. There is a button to enable two colums

I remember reading about that somewhere but I just had a look and I can't see it. Only buttons I have are:

* Button Color / Current Level Color
* Vertical / Large
* Lights / Start 1
8 boxes for names

Toggling the Vertical button _does_ result in two columns of buttons being displayed on the screen, _but no additional name boxes are offered._

mcjtylib 1.10-2.2.0
rftools 1.10-5.58

**Comment by McJty** [comment]
Ah for naming. No, that isn't possible yet. The GUI is a bit limited for that so I couldn't find a way to name more then that

**Comment by xenoflot** [comment]
Would it be possible to have a button to toggle the boxes between column1_names and column2_names?
Or even add a 1-field GUI to the elevators where you specify the name.
Or name elevators in an Anvil and have it display that!

**Comment by McJty** [comment]
Next version you will be able to name elevator blocks
