### ISSUE TITLE
Opening Dialer GUI crashes server

### ISSUE THREAD

**Issue by DigitalSketch** [McJty/RFTools#822]
When we right click to open the GUI for the dialers that the matter transmitters use, it immediately crashes the server.

**Comment by McJty** [comment]
Please: This is SOOO little information. What version of RFTools? Also I need a crashlog.

**Comment by DigitalSketch** [comment]
It's not my server, let me see if I can get it from the owner.. we may be able to whitelist you so you can get on as well.

**Comment by DigitalSketch** [comment]
http://manage.thatmumbojumbo.com/fml-server-latest.log and http://manage.thatmumbojumbo.com/fml-server-3.log
Were the latest logs before we stopped using the dialers.   We're running the Hermit Pack (latest stable) with RFTools 1.10-5.52 and RFTools Dimensions 1.10-4.42

**Comment by McJty** [comment]
Update RFTools Dimensions to 4.44. There was a critical bug in that version
