### ISSUE TITLE
Suggestion: Elevator Button Sync

### ISSUE THREAD

**Issue by ph1x3r** [McJty/RFTools#824]
Allow all screens attached to the same elevator control block to show the same labels.

Reason: It is a pain to have to go to every level and re-edit the buttons when you alter/add a level.

**Comment by xenoflot** [comment]
A (better?) way to implement this would be to shift-click the ebutton on a screen that already contains an ebutton, and have it copy the settings from the screen.  That way those players who do want to have different labels for the same floors can do so.

**Comment by ph1x3r** [comment]
In issue #821 a comment was made that would also 'solve' my issue.

If the elevator block itself could have a name from either re-naming or from a data field, then that could be used for the default floor name.

If people wanted to change a name, then they could do so on the button module that would override the default text.

**Comment by McJty** [comment]
Next release you will be able to name elevator blocks
