### ISSUE TITLE
Power relay has its sides mixed up

### ISSUE THREAD

**Issue by curiosity-a** [McJty/RFTools#826]
If you are facing west with a block in front of you, you will be looking at the east side of that block. However, such side is labeled "W" on a power relay. Same for north/south.

**Comment by McJty** [comment]
That's intentional. The sides are relative to the block. Not to the world. So not a bug

**Comment by curiosity-a** [comment]
Conventionally a west side of a thing is the side that is situated to the west of the thing's center (meaning it's facing the west of the world). It can't be said to be relative to anything.

**Comment by McJty** [comment]
It is relative to the front of the power relay itself. i.e. the front of the power relay is the 'relative' south orientation

**Comment by McJty** [comment]
It is relative to the front of the power relay itself. i.e. the front of the power relay is the 'relative' south orientation. Additionally the sides are marked that way

**Comment by curiosity-a** [comment]
Yes, I understand that the sides are marked. But without looking at them one can't guess which side is which from the notation. It's misleading.
...Wait, by "relative to the front" you mean the marks actually rotate along with the block? Hmm, they do. Now the notation is just outright weird and makes no sense whatsoever.
What exactly is the advantage of the sides being relative to the rotation of the relay? Because I can only see disadvantages.

**Comment by McJty** [comment]
The advantage is that you can look at the side of the block, see the label and then use that in the GUI directly without having to worry about where north is in your world

**Comment by curiosity-a** [comment]
No, no. That's not what I mean. You can do that regardless of whether the sides are relative. What is the advantage of them _depending on the rotation_ of the block? As opposed to being fixed regardless to where the block is facing.

**Comment by McJty** [comment]
Well the side texture of the block depends on how it is rotated. i.e. that's how it is placed in the world.

Anyway, I don't think we're going to agree on this. I like it the way it is now and also I can't change it because that would break builds

**Comment by curiosity-a** [comment]
Yes, it does. But that doesn't answer my question. Also I don't expect you to agree with me, at the very least I wanted to find out your motives behind this design decision.

Anyway, the change breaking builds is a good enough point (although there are ways around it). But maybe at the very least change the texture so it's not misleading? Mark the sides with numbers or colors or letters that don't imply cardinal directions or something.

**Comment by McJty** [comment]
Maybe I don't understand your question then. Note that those cardinal directions are actually standard in minecraft. i.e. in the code the sides of a block are also refered with those cardinal directions

**Comment by curiosity-a** [comment]
I don't know how exactly Minecraft works, but even if so, it doesn't justify the misleading interface.

In fact, **F**ront, **B**ack, **L**eft and **R**ight seem to be a perfect description to how the sides are actually determined.

**Comment by McJty** [comment]
I could do that yes

**Comment by McJty** [comment]
Done for next release
