### ISSUE TITLE
Builder eating quarry cards when it burps on Chisels & Bits

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#827]
I lost a few quarry cards tonight trying to disassemble an old base. The builder appears to be being reset as per #545 in that the card vanishes and the power buffer is emptied. The crash log suggests that it's burping when its hitting something from C&B.

However it wasn't consistent. To try to narrow down what was causing the problem, I pulled apart the base chunk by chunk and when I noticed C&B in the crash log, I explicitly selected a small area containing some chiseled bits and it quarried them without a problem. So sadly I can't give you a more specific pointer to where the problem is.

This base only had a tiny bit of C&B in it and I'm pretty confident that the only blocks used were quartz blocks, glowstone and EnvironmentalTech's Hardened Stone.

chiselsandbits 12.7
mcjtylib 1.10-2.20
rftools 1.10-5.58
environmentaltech 1.10.2-0.10.5g

http://pastebin.com/KwudaF6u

**Comment by McJty** [comment]
This seems to be a bug in Chisel & Bits though. Did you report to them?

**Comment by xenoflot** [comment]
Not yet as I wasn't sure where the bug lay. I'll report it to them now and reopen if necessary. Thanks!

**Comment by xenoflot** [comment]
Algo has sorted it.
