### ISSUE TITLE
Problems crafting efficiency dimlets

### ISSUE THREAD

**Issue by possiblyasleep** [McJty/RFTools#83]
I have been playing FTB Infinity 1.2.0 and I've been trying to craft a Special Efficiency Dimlet in the workbench, and it isn't working.

If I understand correctly these should be the right parts: dimlet base, rarity 5 circuit, advanced energy, advanced memory, special controller, efficiency essence (which is another issue: it will not craft according to the NEI recipe on 2.53 but would on 2.50), but nothing happens.

**Comment by McJty** [comment]
Can you clarify? You mean that it also doesn't work in 2.53?

**Comment by possiblyasleep** [comment]
Crafting the Special efficiency dimlet in the workbench does not work in 2.53 nor 2.50, and crafting the Efficiency essence using the recipe from NEI worked in 2.50 but does not in 2.53.

However if I take an efficiency essence that was crafted in 2.50 an uncraft it in an Uncrafting Table from Twilight Forest mod, I can then recraft those items into the efficiency essence.

**Comment by McJty** [comment]
Can you describe to me exactly how you are crafting the efficiency essence? I will try to do it myself. You're using a enchanted diamond pickaxe. right?

**Comment by possiblyasleep** [comment]
Yes. An Efficiency III enchanted Diamond pickaxe in the top center, ender eye in the middle left, middle right, and bottom center slots, and a nether star in the middle center slot.

**Comment by McJty** [comment]
Hmm, works perfectly for me:

http://i.imgur.com/txuseDu.png

Going to do a few more tests in some specific modpacks but I see no problem so far

**Comment by possiblyasleep** [comment]
This is what I see: http://i.imgur.com/1as6aTd.png

Strange thing is the same recipe worked in 2.50, before I tried changing to 2.53 to see if that fixed the efficiency dimlet in the workbench (unless I just have the recipe wrong there but it looked right.)

And if I just uncraft one and craft it together again it works fine. Huh.

**Comment by McJty** [comment]
Ah, you are doing it in AE. Could you try in a regular crafting table? Maybe there is a mod interaction problem with AE here.

**Comment by possiblyasleep** [comment]
Same thing. Also here is the pick I'm trying to use:

http://i.imgur.com/AX6fqIG.png

**Comment by McJty** [comment]
Very weird... At the moment I have no explanation. I will investigate this further.

**Comment by possiblyasleep** [comment]
After doing some more testing, I've discovered that crafting for the efficiency essence for me breaks at version 2.52 (meaning it works on 2.51 or earlier) which is also the same version that fixed a bug in efficiency essence and environmental module crafting.

**Comment by McJty** [comment]
Ok thanks for the testing. I will investigate this further. If I can't find a real solution I'll probably make a custom machine to do the crafting instead. Or else I tweak the recipe somehow.

**Comment by McJty** [comment]
I got some help from someone and we think we know what is wrong. I'll implement a fix for next version.

**Comment by McJty** [comment]
Ok, I fixed the problem I think. At least it still works for me and I hope it will now work for you too. I also fixed the actualy efficiency dimlet creation in the workbench as that was also broken. The latest dev build which you can find here:
https://drone.io/github.com/McJty/RFTools/files
should have the fix. Please reopen if it is still not working for you with that build.
