### ISSUE TITLE
[5.58] Builder can crash when quarrying and outputting items to Immersive Engineering's Storage Crate

### ISSUE THREAD

**Issue by SPMoo66** [McJty/RFTools#837]
I'm not quite sure whose side this is on, so I apologize in advance if it's not yours.
I activated a quarry with an IE Wooden Storage Crate on top and the server crashed. It only happened the second time I activated it, not the first, so it doesn't happen 100% of the time.

http://pastebin.com/HbHcbH33

Thanks!

**Comment by McJty** [comment]
That looks like a bug in IE. Best to report to them. I'll keep this open in any case though

**Comment by BluSunrize** [comment]
issue on my side indeed. Feel free to close this! ^^
