### ISSUE TITLE
How to disable the ocean dimlet

### ISSUE THREAD

**Issue by xorinzor** [McJty/RFTools#839]
We keep running into the problem that players generate worlds with the ocean dimlet that will create immense lag because the fluids fall straight into the void.

How can we disable the ocean dimlets to prevent this from happening? I can't figure out what it's configuration option in the dimlets.cfg file is.

**Comment by McJty** [comment]
I actually might have to fix this bug and add a bedrock layer to it. But first you need to tell me what version of RFTools because this has changed

**Comment by xorinzor** [comment]
We're at RFTools 4.23 (perhaps another useful detail, it's a part of Project Ozone 2: Reloaded)

**Comment by McJty** [comment]
To disable the dimlet hold it in your hand and type /rftcfg dimletcfg
Then you will get instructions on how to disable it
