### ISSUE TITLE
RFTools Builder (quarry) losing data on ArchitectureCraft blocks

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#840]
Hi,

I used an RFTools Builder Block to pull down a crappy build and found that instead of returning the carved Architecture Blocks, it returned raw "Architectural Blocks". Ideally it would return the carved block.

Not sure if this is one for you or gcewing so I've crossposted it there. https://github.com/gcewing/ArchitectureCraft/issues/13

architecturecraft-1.5.1-mc1.10.2
mcjtylib 1.10.2-2.2.0
rftools 1.10-5.59
forge 2122

Cheers

**Comment by McJty** [comment]
Not much that I can do about that I'm afraid. I just use the regular harvesting system
