### ISSUE TITLE
[Crash] Fluid Monitor: NullPointerException

### ISSUE THREAD

**Issue by Mohron** [McJty/RFTools#841]
RFtools: rftools-1.10-5.59.jar
MJtyLib: mcjtylib-1.10-2.2.0.jar
Forge: forge-1.10.2-12.18.2.2124-universal.jar

[Crash](http://hastebin.com/igizulobez.scala)

Need to check if fluidhandler is null:
https://github.com/McJty/RFTools/blob/1.10/src/main/java/mcjty/rftools/blocks/monitor/LiquidMonitorBlockTileEntity.java#L137

**Comment by McJty** [comment]
Not my bug. Report this to whatever mod the tank above it belongs too. If line 136 in my code returns true then the capability MUST return non null on the line below

**Comment by Mohron** [comment]
It was your Deep Resonance tank I selected...

**Comment by McJty** [comment]
Oh then I'll check it out.

**Comment by McJty** [comment]
What version of Deep Resonance?

**Comment by Mohron** [comment]
deepresonance-1.10-1.2.9.jar

There is a EnderTank(endertanks-1.10.0-1.4.3.jar) in range but it wasn't the one tank selected before the crash.

**Comment by McJty** [comment]
Ah but that might still cause the problem as it will try to scan them. Can you try to reproduce it without the endertank or with only the endertank?

**Comment by Mohron** [comment]
Seems to only happen when the endertank is there. I've made an issue with the mod author. Would still be good for RFTools to handle the possibility of null. Thanks anyways

**Comment by McJty** [comment]
I added a safety for this
