### ISSUE TITLE
EndergenicTileEntity.java minor bug (with fix)

### ISSUE THREAD

**Issue by Astinasha** [McJty/RFTools#842]
Line 279
`if (random.nextInt(1000) <= EndergenicConfiguration.chanceLost) {`

This should be:
`if (random.nextInt(1000)+1 <= EndergenicConfiguration.chanceLost) {`

Reason: `nextInt `is exclusive, and starts at 0. As such, it will return a random number between 0 and 999. This means the chance to discard a pearl is slightly higher than intended (by default 0 through 5 will discard a pearl, as opposed to 1 through 5 as the config suggests).

**Comment by Astinasha** [comment]
Thinking on it, you could also just change <= to < instead, and keep the 0-999.

**Comment by McJty** [comment]
I'm not going to change this as this is rather delicate and too many builds depend on how it works right now
