### ISSUE TITLE
[Suggestion] Endergenic Ticking Tweak.

### ISSUE THREAD

**Issue by Astinasha** [McJty/RFTools#843]
So I've looked at a few of the older issues, suggestions, and such, and notice that people suffer from tile entities not ticking at quiiiite the right rate, resulting in things like one generator ticking at 9 when it should be ticking at 10, or things like that.

I couldn't come up with a way to fix tile entity ticks vs redsotne ticks or what not line up, but I did think of a stop-gap until something else can be invented.

What if you just increase the charge time from 15 to 16, and allow for a 2-tick window for maximum output at 9 and 10, or 10 and 11?  Just a thought.

**Comment by McJty** [comment]
I'm not going to change this as this will break too many builds and it is actually possible to get it to work accurately with some experimentation. i.e. just tweak the settings until it arrives correctly
