### ISSUE TITLE
[1.10.2] Items disappearing with the remote storage module

### ISSUE THREAD

**Issue by Nullga** [McJty/RFTools#847]
RFTools 5.58
Forge 2120

Not sure of conditions to reproduce the situation however items from random mods including Minecraft sometimes got disappeared when storing them thru remote storage module (tablet).

**Comment by McJty** [comment]
Sorry, but bug reports like these are totally useless. Without logs or a reproducible situation there is literally nothing I can do about this. At least a picture of your setup and more explanation about what you are doing could help

**Comment by Nullga** [comment]
Here is what I have done.
1) Crafted some Ender IO items
2) Entered RFT dim's dimension while holding them in inventory
3) Stored some dropped items with the remote storage module
4) Got back to Overworld and some more E-IO crafting
5) Stored all the crafted items in inventory thru the remote storage module then they got disappeared 

As much as I remember for recent cases it happened mostly to items from Ender IO. I hope this helps you a bit.

http://imgur.com/a/mychQ

**Comment by McJty** [comment]
I would doubt that they really disappear as that is not very likely. It is more likely that they somehow got moved into a chest or storage somewhere. Double check everything

**Comment by Nullga** [comment]
Yeah I actually did checking all the other chests and elsewhere even tried moving each storage module from the remote storage block to a module storage block and seeking inside. I would rather think it'll be that I'm missing them by other reasons but I noticed it a minute after I moved them into the remote storage module, when I tried to craft something by using those disappeared items. Umm, I will make some tries to confirm this...

**Comment by Nullga** [comment]
By the way I'm on a sever. I will ask OP to get logs. Thanks.

**Comment by Nullga** [comment]
http://pastebin.com/87keyUMy

Hope that helps.

**Comment by McJty** [comment]
Nope, that's not the log I need. I need the full server log (the biggest one)

**Comment by Nullga** [comment]
You mean the whole server log that starts at server launching?

**Comment by McJty** [comment]
yep

**Comment by McJty** [comment]
BTW, no guarantee it will help me though. I'm still not convinced there is a bug here...

**Comment by Nullga** [comment]
Well, due to the fact that I've not yet succeeded to reproduce what's experienced and the OP won't be able to respond for a couple of days, I will close this issue for now at least until I have more detailed info to share with. I appreciate your response though.
