### ISSUE TITLE
Energy Usage in dimlets.

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#85]
Good Day,

We have created the age but seems like that it is using around 2x of the energy it should use.
Below is the image of the problem, you can see that Ender IO Capacitors banks drain 2x as much they should use. Only dimension builder is connected to those capacitors...
http://puu.sh/gkMTN/c404217bf1.jpg

Best Regards,
DeForce

**Comment by McJty** [comment]
I will investigate this.

**Comment by McJty** [comment]
Very good catch. ALL dimensions are using twice as much power as they should. I will fix this for 2.54 which I will release in a moment.
