### ISSUE TITLE
Storage Scanner Crash

### ISSUE THREAD

**Issue by Plurp13** [McJty/RFTools#851]
It's possible that one storage mod was involved....multi-storage maybe? I think the thing i was trying to click on in the storage scanner was one of those stone lockers from that mod, apparently it didn't like that inventory.

http://pastebin.com/EgmT66CR

**Comment by McJty** [comment]
That looks like a bug in another mod. It is crashing in code that doesn't belong to me.
I'll try to add some protection but no guarantee that it will work
