### ISSUE TITLE
placing Elevators is broken.

### ISSUE THREAD

**Issue by 3Pixel** [McJty/RFTools#852]
i dunno how to describe this exactly but:
placing one creates a broken elevator. you dont even lose the elevator in the inventory. trying to break it leaves a invisible ghost block and after a relog or server restart the elevators are still there even those in my inventory. it can soft crash the client (on my server i get kicked back to the mp menu) and can crash the server. i tested it in creative mode on SP again and got the same results.

we are using RFtools 5.60 and Forge 12.18.2.2125

here is the Log
http://pastebin.com/7GDkAP9F

edit: added a litte more info

**Comment by leglerm** [comment]
Identical problem here. Crash when trying to right click the elevator. Cant break the elevator (ghost block and reapears after block update). 


[crash-2016-11-17_23.50.40-client.txt](https://github.com/McJty/RFTools/files/598667/crash-2016-11-17_23.50.40-client.txt)

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed next release
