### ISSUE TITLE
Client crash when shift right clicking EnderIO conduits with wrench

### ISSUE THREAD

**Issue by Bodidl** [McJty/RFTools#856]
forge: 12.18.2.2147
rftools: 1.10-5.61 
(EnderIO-1.10.2-3.0.1.128_beta)
(EnderCore-1.10.2-0.4.1.58-beta)

Something about BlockProtectors... 
I can break conduits with a pick without crashing. Works fine with RFTools 1.10-5.60.
[crash-2016-11-18_16.54.08-client.txt](https://github.com/McJty/RFTools/files/600348/crash-2016-11-18_16.54.08-client.txt)

**Comment by Bodidl** [comment]
Also crashes when shift right clicking other stuff like a RFTools Redstone Transmitter

**Comment by xannor** [comment]
I can confirm this, it also appears to be a client only issue as my server both did not crash and has no logs or anything on the console.

**Comment by MinecraftXwinP** [comment]
I got the similar exception when shift right click a mekanism universal cable with configurator in wrench mode.
Here's my crash report : http://pastebin.com/erj7QXue
Hope this will help.

**Comment by McJty** [comment]
Fixed in 5.62

**Comment by xannor** [comment]
Confirming, this is indeed fixed in 5.62, thank you!
