### ISSUE TITLE
Elevator Block dupe crash

### ISSUE THREAD

**Issue by ExeQue** [McJty/RFTools#857]
I was removing and repositioning Elevators, where, when placing down the recovered Elevator in another spot next to an RF source, the block was placed, but the item didn't leave the inventory - Confused as hell by this behavior, I tried mining the newly placed elevator, and the game just crashed - And keeps crashing on the world whenever I try to reload.

Using the newest version of "All The Mods" modpack (v1.44) with no additional mods and no changes to the config.
[crash-2016-11-18_19.24.12-server.txt](https://github.com/McJty/RFTools/files/600653/crash-2016-11-18_19.24.12-server.txt)

**Comment by McJty** [comment]
Already fixed in 5.61 released today

**Comment by ExeQue** [comment]
Awesome! Manual update it is
