### ISSUE TITLE
Possible x-mod issue with Mekanism

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#858]
Hi,

One of my players is getting a crash when he tries to use a Mek Configurator (Mek's wrench) in any mode on a Mek block. You'd think I'd report this to the Mek author however the crashlog says it's mcjty.rftools.blocks.blockprotector.BlockProtectors.getProtectors having the problem. 

He gave me a couple of crashlogs but they appear virtually identical to me. http://pastebin.com/FpWCRdts
I haven't independently verified the crash but I'm willing to do so and provide the full log if you'd like.

Cheers!

mcjtylib 2.20
rftools 5.61

**Comment by McJty** [comment]
Fixed next release (soon)

**Comment by xenoflot** [comment]
Thanks very much!
