### ISSUE TITLE
Default Dimlet Cost

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#86]
Good Day,

I see that we can change known dimlets configuration, but can I change the default rf-tick cost for "unknown" dimlets. For example all Nether Ores dimlets cost 10 rf/t for maintaining. I, for, example want to make all "default, unkown" dimlet cost for example 20k rf/t. Is possible now and I just didn't see the config option or you can make a setting for that?

Best Regards,
DeForce

**Comment by McJty** [comment]
You can edit main.cfg and go to the 'typerfmaintain' section. There you can change the default costs for all dimlet types. This will be used for every dimlet of that type unless there is a specific value for a given dimlet.

**Comment by DeForce** [comment]
Is it client-side or server-side values when looking at tooltip in NEI/dimlet in inventory?
If client-side, is it possible to make it server-side?

**Comment by McJty** [comment]
If you modify the values on the server config then it will be server-side. However, the tooltip uses the client side values but the server is the master. It is recommended to copy the server config to the clients after making these changes so that the clients get the real information.

**Comment by DeForce** [comment]
Thank you for your support.

**Comment by McJty** [comment]
I assume this can be closed? If you have further questions/problems please reopen.
