### ISSUE TITLE
[Request] Weather Dimlets

### ISSUE THREAD

**Issue by unpure** [McJty/RFTools#87]
Hey there.
Currently trying to create an awesome dimension to build a new base.
Sadly it seems like there is no way to change th weather of that dimension.
Would be awesome if there are some dimlets to control that.
Like always Rain, always Snow, no weather and default weather.

Sorry for my bad english, i hope its not to hard to understand.

//edit:
Oh and btw, i dont know if that is a bug or supposed to happen, but it seems like single biome is not realy single biome. I tried to create a forest only dimension but i got something like roofed forest, enchanted forest and many more "forest" biomes. Its hard to find a nice place without that color changing stuff from enchanted forest. :(

**Comment by McJty** [comment]
Yes, this is a planned feature. Weather dimlets will come in one of the next releases.

**Comment by unpure** [comment]
Wow thats a fast answer.. :D 
Nice to know that this is comming. 
Is it possible to add that feature into existing dimensions without problems?
Would be bad if i build my base and had to build it again.. :D 

Did you saw my quick edit in my first post? :P

**Comment by McJty** [comment]
yes you will be able to 'inject' weather dimlets into existing worlds.

About the biomes, what exactly did you specify for dimlets? Did you also specify a controller?

**Comment by unpure** [comment]
Material None
Liquid None
Terrain Void
Controller Single
Biome Forest
Sky Normal
Sky Normal Day
Sky Normal Night
Sky Normal Fog
Sky Body None
Mob Default
Effect None
Feature None
Structure None
Time Noon


If if talk about Single Biome then yes.

**Comment by McJty** [comment]
And you got multiple biomes in that world? That's weird...

**Comment by unpure** [comment]
Yeah i got multiple biomes. Atleast Roofed Forest, Enchanted Forest and normal forest, maybe more.

**Comment by McJty** [comment]
Are you sure you didn't insert Controller Forest instead of Biome Forest?

**Comment by unpure** [comment]
I'm completly sure i used single biome and biome forest.
I checked the dimension tab and for some reasons there is
Biome Controller: CONTROLLER_MAGICAL

**Comment by McJty** [comment]
Here is a test you can do. Go to the dimension builder, take out your realized tab. Put it in the enscriber. Hit extract. That will put all the dimlets back and there you can see what you inserted. You can simply press 'store' again to restore the dimension (it will not make the dimension again)

**Comment by unpure** [comment]
Already did that and posted the Output a few posts above.

All dimlets in the tab:
Material None
Liquid None
Terrain Void
Controller Single
Biome Forest
Sky Normal
Sky Normal Day
Sky Normal Night
Sky Normal Fog
Sky Body None
Mob Default
Effect None
Feature None
Structure None
Time Noon

This is the output from Shift + RMB
http://fs1.directupload.net/images/150306/hbmzpztu.png

**Comment by McJty** [comment]
Hmm, looks like there was a mismatched ID somewhere. Is this on a server or single player? Also was this dimension created in previous versions of RFTools? What version of RFTools are you using now?

**Comment by unpure** [comment]
The dimension is created on a server.
It should be created on v2.31b but i'm not sure.
We are currently running v2.52

**Comment by McJty** [comment]
Ok, back in these old versions there were many ways for dimlet ids to get outdated. My guess is that at some point the dimlet id for single controller changed to magical controller.

**Comment by unpure** [comment]
Sad to hear that. Is this problem fixed in the newer versions?
Is there any way to change the biomes in an existing dimension?
If not, how big is the chance for this to happen again?
I know bugs happen, but is it "almost" save to build a new base?

**Comment by McJty** [comment]
This problem has been fixed for a while. It was only present in versions older then 2.40 (as I remember). So you should never have this problem again from now on. I don't know if/how you can change biomes in an already existing dimension. I know there are some mods that can change biomes but I have never done that. But for new dimensions you should not have this problem anymore.

**Comment by McJty** [comment]
Weather dimlets will be in next version.
