### ISSUE TITLE
Feature Request. 1.10.2 - Blast-Resistant Shield Blocks

### ISSUE THREAD

**Issue by MeinKraft** [McJty/RFTools#873]
Could you add Blast-Resistant Shield Blocks

I tried building a Wither spawner/killer. The shield blocks worked great for killing them on easy mode. Normal and Hard mode the shield blocks are destroyed by the explosions. I had the spawner inside the shield blocks inside a bedrock box.

thank you, such a great mod, loving it !

**Comment by McJty** [comment]
The shields are wither proof already but you must make sure you don't make it too big because bigger shield means bigger power consumption. Additionally make sure you use a tier 3 shield or higher. Tier 1 and 2 are not always sufficient for this
