### ISSUE TITLE
1.11 crash

### ISSUE THREAD

**Issue by Myknakryu** [McJty/RFTools#874]
Minecraft Version: 1.11
Forge Version: 1.11 2160
CompatLayer Version: 1.11- 0.0.21 alpha
McJtyLib Version: 1.11 2.2.0 alpha10
RFTools Version: 1.11- 5.62 alpha3
Java version: Oracle JDK 8 u102

What have i done:
When i was playing on creative i tried to open RFTools Tab. As soon as i clicked that tab game crashed.
I also tried with search tab scrolling down crashed my game. 
Using JEI does not crash game.

Logs:
Opening RFTools creative tab
http://pastebin.com/Ju43RWYt
Opening search tab then scrolling donw
http://pastebin.com/k9rkFk7n

**Comment by McJty** [comment]
I'll check it out

**Comment by Tahkra** [comment]
Also had this crash on MC 1.10 Forge 2151. Occurred while attempting to load into the game I assume because I have an Advanced Charged Porter on my hotbar.

Log: http://pastebin.com/gyDpQrcp

CompatLayer 1.10-0.0.17alpha
McJtyLib 1.11-2.2.0alpha10
RFTools 1.11-5.62alpha3

**Comment by McJty** [comment]
I'll check it out

**Comment by djhandy** [comment]
i have the same issue with charged porter but mine is not on my hotbar but in my inv
 
LOG; http://pastebin.com/dJxPmqRX

**Comment by McJty** [comment]
Fixed next release (later today)
