### ISSUE TITLE
Teleportation Not Working - Won't Dial

### ISSUE THREAD

**Issue by madalienist** [McJty/RFTools#875]
I am running the HermitPack modpack on 1.10.2.  RFTools is 1.5.2.  (1.10-5.59) I have 2 Teleport locations.  Each with a Transmitter, Receiver, Dialing Device and Analyzer.  Ample power at each location.  The locations are in the Overworld.  

I name each destination and they appear in the dialer.  The Analyzer says that the receiver is "Dial Ok!"

But the Dial Button is not highlighted.  I got the probe and it shows the teleporter network and I am able to move between the receivers with no trouble.  When I am in the dialer If I double click the location it says - in chat - "The Receiver is Now Highlighted"  But still no dial.  

I created a creative testing world and I have the same problem and cannot teleport 50 blocks.  

I redownloaded the mod pack and just copied my saves folder over and it still does not work.

**Comment by McJty** [comment]
First select a transmitter. And AFTER you have selected a transmitter in the top list select a receiver in the bottom list. Only then will the dial button be active

**Comment by madalienist** [comment]
Damn, I feel stupid.  That worked.  Though it was not real obvious in the manual.  

Thanks!
