### ISSUE TITLE
crash on startup (4/7) withe RFTool 1.11.5.62alpha3

### ISSUE THREAD

**Issue by ARatfat** [McJty/RFTools#878]
Hi on startup I get this crash http://pastebin.com/Qep6JBMZ

I have compact layer 1.10-0.0.21alpha

**Comment by Watchful1** [comment]
Same here http://pastebin.com/1mJaiPNL

**Comment by McJty** [comment]
You cannot mix the alpha versions of rftools + mcjtylib with the non alpha version of Deep Resonance. The McJtyLib that belongs to the alpha version of rftools is not compatible with the McJtyLib that belongs to the non-alpha version of Deep Resonance

**Comment by Watchful1** [comment]
That would explain it.

Doesn't look like the alpha of deep resonance is on curse though.

**Comment by McJty** [comment]
No because I haven't made that one yet. Still working on it :-)
