### ISSUE TITLE
Dimensions deletet/corrupt after update

### ISSUE THREAD

**Issue by Vanir2314** [McJty/RFTools#88]
I just upgraded to 2.54 to fix the SFM crash (wich works fine now) But the problem no is, my dimensions are no longer accessible (goodbye Frame Miner)
They are now all called Unnamed and upon teleporting there using a previously dialed Matter Transmitter results in a crash (Log: http://pastebin.com/Lsa3QU7V). Dialing is no longer possible ("Invalid destination") after trying once.
Is it possible to recover these worlds or are they gone and I need to rebuild them?

Edit: I'm using a slightly modified version of FTB Infinity 1.2 if this helps

**Comment by McJty** [comment]
Hmm that's very strange. From what version of RFTools did you upgrade? Was this with a server or single player? I need a bit more information to find out what went wrong here.

Can you also try the command /rftdim list and see if it lists your dimensoins?

Did you get a crash at some point during upgrade?

**Comment by Vanir2314** [comment]
I previously used 2.53 on Singleplayer, no crash during upgrade, The command only lists Vanilla dims and one for Compact Machines

**Comment by McJty** [comment]
Do you have a backup of your world so you can try to upgrade this again?

**Comment by Vanir2314** [comment]
Just noticed, it tells me two blocks are Missing an entering a non-updated world
rftools:teleportBeamBlock (twice)

I loaded up the most recent backup and here the worlds are working, I'll try to add them to the current savegame and see if it works

**Comment by McJty** [comment]
I'm trying to figure out what went wrong. Here. Hold on.

**Comment by McJty** [comment]
I know it is a bit of work but if you start from your working 2.53 world and upgrade to 2.54 again does it again corrupt all dimensions?

**Comment by Vanir2314** [comment]
I hope I did what you wanted me to do there
I went back to 2.53 and loaded up my most recent backup (from yesterday)
Then I closed and went to 2.54 and loaded it up again, this time it didn't corrupt
It just did it with my most recent version of the world.

I guess I could just continue to play using the backup but I would prefer if I could add the worlds to my new world. Do you know if there is a way to do so?

If I can do anything to help, just let me know

**Comment by McJty** [comment]
I'm not at my computer right now but there may be a way to fix your corrupt world by copying some data from the non-corrupt world. I can tell you what data exactly in a few hours from now when I get back to my computer. Thanks for being patient

**Comment by McJty** [comment]
Ok, if you go to your backup saves folder and there to the folder of your world then there you will find a 'data' folder (so minecraft/saves/<world>/data) and in that folder you should be able to find files like 'RFToolsDimensionManager.dat' and 'RFToolsDimensionStorage.dat'. Copy these files to your non-working version and hopefully that will fix it. Let me know if that worked.

**Comment by Vanir2314** [comment]
Yes that worked, I can now enter my Dimensions again and the dimension tabs got their names and info back
Thank you for your help, anything more that you need to know?

**Comment by McJty** [comment]
I'm very happy that you got it working but I still have a bug to solve. This kind of corruption should never happen. Thanks for helping me with this though.

**Comment by Vanir2314** [comment]
Glad I was able to help
I also found out your rf meter stuff (monitor and the tool showing the network, don't know the names currently) can't detect stored rf in Draconic Evolution storages, it always shows as full. Or should this be a new issue and this one closed?

**Comment by McJty** [comment]
Better make that a new issue but I am already aware of compatibility issues with draconic evolution.
Also please don't close this ticket yet. I would like to close it only when I have something fixed for real.

**Comment by Vanir2314** [comment]
Hey, got a problem again.
I was pretty sure, I have been in a RFTools Dim last time I played. When I logged back in (SP) just now, I was at my overworld Spawnpoint. I guess I should have noticed something is wrong, because I never close the game outside.
I went to grab my Mobile teleporter to my Dimension with my Base in it and used it => crash (http://pastebin.com/2AD4ffL2)
When I log in now, all I see is my Hotbar on black background and then crash. (http://pastebin.com/deSMiA2j)

Tried to get myself back to the overworld by editing the level.dat and the one in playerdata, but according to these I am in the overworld.

Ok, so third (or fourth?) login let me back in, still in the overworld, now to see what happened.

Corrupted Dims again. I don't think anything was updated since last play, at least I can't remember to do so. At least I know what to do now.
Still going to post this so you know about it.
I should probably increase Backup frequency from now on, although I have no Idea what causes this. One would think there were more reports if it happened more often.

This is in the (modified) Infinity Pack, as it is my main save file.
I don't know if this could affect this, but The pack says I should tell you that fastcraft is enabled. Forgot it earlier.

Anyways as always, if you need sth don't hesitate to ask ;)

**Comment by McJty** [comment]
Thanks for reporting this. I will also examine this. Note however that today I released version 2.55 which ,ight (not 100% sure) fix this issue. In any case for now you are the only report I got of this.

**Comment by Vanir2314** [comment]
I found out what corrupted the dims the last time (not the first one, the one without update)
I had a crash with SFM (copied a program using steves addons, pasted it on a inv manager, opened it and then got a crash) while in a RFTools Dim.
I haven't noticed last time, since I quit playing after the crash, so I didn't start Minecraft again.
Tried the same thing again and remembered about the crash then.
This time the Dims got corrupt again. 
I am already using your newest version (2.55), but at least I can confirm /rftdim recover is working perfectly fine.
I don't know if the corruption is related to SFM or if it can happen generally when Minecraft crashes while inside one of your Dimensions.
It doesn't happen always, I tried again and nothing happened, but the third time they were gone again.

**Comment by McJty** [comment]
That's very useful. I can easily add a way for me to crash while in an RFTools dimension (adding bugs is easy :-) ) so perhaps I can reproduce this that way. That would be very helpful indeed. Unless the bug is specific to SFM however. But this is a very interesting path to investigate at least. Thanks for testing this.

**Comment by Vanir2314** [comment]
If you try it this route, maybe I should add, that the crash in question was not a crash to desktop, but one to main menu. I don't know if this makes any difference (I'm no programmer :p) So I don't have a crash log
But no problem, that was an easy test :D

**Comment by McJty** [comment]
I could reproduce the problem by forcing a crash. Going to try to find out how to avoid the dimensions getting corrupt.

**Comment by McJty** [comment]
I'm very happy to declare this bug fixed for the next release of rftools (2.60)!
