### ISSUE TITLE
[1.7.10] Cannot Disable/Remove <Unknown Dimlet>s

### ISSUE THREAD

**Issue by Wealthyturtle** [McJty/RFTools#881]
After Adding AOBD, then Removing AOBD, there are MANY Unknown Dimlets

Example:
http://i.imgur.com/UeFl6Kj.png

I Tried Deleting dimlets.cfg and main.cfg, but Nothing Works.

**Comment by McJty** [comment]
Where do you see those dimlets?

**Comment by Wealthyturtle** [comment]
From NEI?

**Comment by McJty** [comment]
hmm that's weird then

**Comment by Wealthyturtle** [comment]
Is there some sort of cache where RFTools Stores dimlet data?

(Apart from the config folder)

**Comment by McJty** [comment]
It might actually be that NEI itself is caching this. Does NEI have some kind of cache for this?

**Comment by Wealthyturtle** [comment]
Let me Check the Creative Inventory

**Comment by Wealthyturtle** [comment]
http://i.imgur.com/E2zWUQT.png

... Nope.

**Comment by McJty** [comment]
I have no idea what is happening. Never saw this problem. Might be that adding and removing that mod did some corruption. Do you have a backup?

**Comment by Wealthyturtle** [comment]
Backup of?

**Comment by McJty** [comment]
Your world. So you can go back to the version before things were going wrong

**Comment by Wealthyturtle** [comment]
Yeah... I've actually had this Issue in my modpack for months. Let me just make a new world

**Comment by Wealthyturtle** [comment]
After making the new world, the broken dimlets still appear in the creative inventory and NEI

**Comment by Wealthyturtle** [comment]
I found the Method to Fix the Issue, You Need to Delete [World Name]\data\RFToolsDimletMapping.dat
