### ISSUE TITLE
1.7.10 Crash

### ISSUE THREAD

**Issue by Tommyboulianne** [McJty/RFTools#883]
Server Crash
fml-server-latest:
https://gist.github.com/Tommyboulianne/bcc024e0d4b2d167ced105bed0ff0113#file-gistfile1-txt

**Comment by Tommyboulianne** [comment]
https://gist.github.com/Tommyboulianne/bcc024e0d4b2d167ced105bed0ff0113#file-gistfile1-txt

**Comment by McJty** [comment]
Why do you report this on rftools? It is crashing in flans mod:

[19:41:37] [Server thread/INFO] [STDERR/flansmod]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.flansmod.common.guns.ShootableType.read(ShootableType.java:104)

**Comment by Tommyboulianne** [comment]
NO because when I removed the mod, It works

**Comment by Tommyboulianne** [comment]
It says that everytime but it didn't crash

**Comment by Tommyboulianne** [comment]
I try it more than 8 times

**Comment by McJty** [comment]
Well it *is* crashing in flans mod. So apparently flans doesn't like something that rftools does

**Comment by Tommyboulianne** [comment]
But I like both
