### ISSUE TITLE
[1.10.2] Timers killing tickrate

### ISSUE THREAD

**Issue by phit** [McJty/RFTools#885]
https://timings.aikar.co/v2/?id=b63c6cf62a434737bd9d8a5575d7baa6

Timers take about 20% of all ticktime on the server alone and there's only a handful running energetic generator setups, when removing them tickrate jumps to a stable 20

I hope there is some way to optimize them, thanks!

pack direwolf20 1.10
rftools-1.10-5.59

**Comment by McJty** [comment]
Can you show me the entire setup? The timer of rftools is really very efficient but it of course depends on what's after it. i.e. don't put vanilla redstone after the timer for example

**Comment by phit** [comment]
Some users are using vanilla redstone , some are using enderio redstone conduits.
Here's an example http://i.imgur.com/Qqd2gsr.png
Both seem to be performing poorly, what is the recommended way if not vanilla redstone?

**Comment by McJty** [comment]
Well two solutions that I know are:
1. Full RFTools. Use wireless redstone and the 'wire' logic block. If you do that there will be no block updates/chunk updates
2. Super Circuit Maker

There might be other options but those are the ones that I know

**Comment by phit** [comment]
alright, I'll try to get all my players to switch over and report back!
thanks

**Comment by phit** [comment]
closed, works fine with redstone of any form that doesnt do block/chunk updates
