### ISSUE TITLE
invalid recipe shape

### ISSUE THREAD

**Issue by stclaus4** [McJty/RFTools#887]
http://pastebin.com/fTaGKwkU
i believe we have a problem here with the recipes shape for the machine frame. this crash is from start up.

**Comment by McJty** [comment]
Looks like a bug in 'miscblocksitemsandmore' mod or something. Not in rftools

**Comment by stclaus4** [comment]
it was a mod renamed to be "end point" by mow master ill report it to him, just a incompatability
