### ISSUE TITLE
Non-clearing quarries should not collect dirt (or whatever block they're configured to replace with)

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#891]
well the title says everything.

When the builder is in quarry mode with a quarry shape card and the config is set to fill with cobble, then ignore all the stone/cobble blocks (maybe another config point), since it's kind of weird to get all that cobble extracted from the rock and at the same time be filling with cobble, this way the terrain gets less modified, and we only extract valuable materials. this makes the builder in quarry mode a lot easier on the server, as less blocks get modified, 

As and added bonus maybe you can make another config to not put a block on non block entities, so it can pick up plants, seeds, flowers, and that kind of stuff, without putting a block in it's place.

Thanks.

**Comment by winsrp** [comment]
I'll add another one, now that I'm testing it, for liquids to that config as well, don't replace liquids with blocks.

**Comment by josephcsible** [comment]
This seems to already be the case. The builder doesn't currently seem to collect whatever its quarry replacement block is when it's in non-quarry mode.
