### ISSUE TITLE
Cannot right click ghost items into any interface.

### ISSUE THREAD

**Issue by xannor** [McJty/RFTools#894]
I just updated to 5.62 beta 1 and I cannot add ghost items to any rftools interface, i.e. filters, crafters, etc.
Clicking does nothing but clear whatever was in there. No errors are logged, and I tried it with a fresh RFtools only install and could reproduce. Forge 2171, MC 1.10.2.

**Comment by McJty** [comment]
yes I know. I'm busy trying to figure out this bug

**Comment by xannor** [comment]
I backed forge down to the version you build with, 2105, incase that was it, and could still reproduce. I also stepped back to release and could verify it was correct. I did notice however, when I tested with the beta I had a filter module and an item filter block in my inventory, when I went back to release the filter module remained but the item filter block had disappeared. This has me worried about backing down my server world as other tile entity blocks could disappear. I also tested in 1.11 and could reproduce in it.

**Comment by xannor** [comment]
I backed down the server and everything seems ok, the disappearance may have been due to creative or  the fact that it was from a beta inventory.

**Comment by McJty** [comment]
Fixed next beta release tomorrow

**Comment by xannor** [comment]
Just loaded my 1.10.2 test instance and I can confirm it is fixed. As an interesting side note, the filter I was testing with had a bunch of the item in it, sort of like it was marking the filter just not displaying it in the bugged version.
