### ISSUE TITLE
Server crash when placing Matter transmitter or reciever

### ISSUE THREAD

**Issue by Saereth** [McJty/RFTools#899]
Crashlog: https://dl.dropboxusercontent.com/u/28829658/crash-2016-12-04_17.36.55-server.txt
MC 1.10.2 rftools 5.6.2
rftools dim 4.45
Forge 12.18.2.2151
Custom modpack

Created a new cheater void dimension, entered the dimension. When I placed down a creative energy cell and then connect a matter receiver to it the server crashed with this log. When I logged back in I put down a matter transmitter and same thing again.

**Comment by McJty** [comment]
That crash is in FTB Utilities. Please report to them

**Comment by Saereth** [comment]
This has been fixed in the new version
