### ISSUE TITLE
Incompatibility with Draconic Evolutions energy storage

### ISSUE THREAD

**Issue by Vanir2314** [McJty/RFTools#90]
The RF Network Monitor and the Energy Module for the Monitor (Standard and Plus) are unable to correctly show the stored amount of RF in the Energy Core of Draconic Evolution. If I point the Modules at the Energy Pylons they just show the storage is full all the time. It's not possible to target them at the Core itself, it just says it is cleared. The network tool shows the pylons as being full as well.

I am not 100% sure, but I kind of remember that at least the modules have worked before. If it helps you I can try to figure out, which update by which mod caused it to break.

Edit: Now I feel dumb for not seeing the other issue for that mod, even though I just looked to see if there is one -.-

Edit2: Can confirm it worked earlier, now to find the version that broke compatibility

Edit3: After some extensive testing, down- and upgrading mods, I can confirm It works just fine with current Draconic Evolution(hasn't updated recently) and RFTools 2.31 2.40 2.41 2.42 2.5 2.51 2.52 2.53 and 2.54, now on to finding out why it doesent in my regular installation
ng out why it doesent in my regular installation

Edit4: I think I understand the problem now. Since the max throughput of the energy pylons is set to Integer_max thats the most of energy that can (at any point) be stored inside any pylon. So at that point, that the Energy in the Energy core surpasses 2,147,483,647 None of your tools are able to "see" that energy since it is not stored in the block that they check for the ammount of stored energy. This also applies to the fact that your tools show a maximum capacity of about 2 billion.

So to actually find out how much Energy is stored, you would basically need to find out were that data is stored, find a way to access the pylons data to find out which energy core they are connected to (if there are multiple in the world/region) and then read the value from there.

That would explain why I thought it worked earlier but not anymore, it is just due to the fact that I didn't have as much energy back then.

**Comment by Vanir2314** [comment]
I updated my first post with any information I could find in the last couple hours, I hope this helps you find out how/if it is possible to add extended compatibility.

**Comment by McJty** [comment]
Thanks!

**Comment by McJty** [comment]
This should hopefully be fixed in the next release of rftools. Haven't been able to test it however.
