### ISSUE TITLE
Coal generator runs as long as it has fuel, even when power buffer full

### ISSUE THREAD

**Issue by jco2641** [McJty/RFTools#905]
I would expect that the generator would stop burning fuel when its internal energy storage is full, is this intended behavior?

Forge: 12.18.3.2185
CompatLayer: 1.10-0.1.1
RFtools: 1.1x-5.70

Steps:
Place coal generator with no valid power output
Fuel generator
When buffer reaches 500k/500k RF fuel consumption does not stop.

**Comment by McJty** [comment]
yes, that's intended. RFTools has sufficient other blocks (power monitor and so) to turn off the generator when needed
