### ISSUE TITLE
Builder Block with Clearing Pump card not clearing lava.

### ISSUE THREAD

**Issue by Apocryphai** [McJty/RFTools#906]
RFTools v. 1.10-5.62

I was using a Builder Block to clear water & lava from a quarried area and noticed that the water was being cleared but not the lava. Tested on a much smaller area and I can't get the Builder to clear even a single source block of lava.

**Comment by McJty** [comment]
Can you give more specifics? What card is in it? How is it configured?

**Comment by Apocryphai** [comment]
Sorry, it was using a Shape Card (Clearing Pump) which was configured by using mark mode, shift-clicking the card on the Builder Block then selecting the 2 corners of the area to be cleared.

When I noticed that it wasn't clearing the lava from the initial large area (32x32x60 blocks) I set it up again with a test area made of dirt in a 3x3x3 shape with a hole in the middle and a single bucket of lava placed there. I'm activating the Builder with a lever. I've just tested it again and it definitely isn't working, unless I've just got something wrong in how I'm using it.

**Comment by SmokiestBeatman** [comment]
Hi, I have the same problem with "Molten Uranium" from "Immersive Engineering"
I treid the same things.

(the pump from "Ranged Pumps" could not do it either. There's maybe a problem with the fluid.)

**Comment by McJty** [comment]
Yes, use 'solid box' instead of just 'box' as the latter only does the outline

**Comment by vaughnsoft** [comment]
Not clearing lava for me either in Foolcraft pack. Solid block, even triple checked the dimensions. Even did preview mode to verify I set the pump clearing card correctly.

**Comment by McJty** [comment]
Ah known problem and this is a problem in EnderIO. Not RFTools
