### ISSUE TITLE
[1.11] Crashing with java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Nullga** [McJty/RFTools#907]
Similar crash to https://github.com/McJty/RFTools/issues/890 but this time is only with some of special dimlets such Cheater while other dimlet types are fine. Thanks!

Forge 13.19.0.2180
CompatLayer 0.1.0
McJtylib 2.3.0
RFTools 5.70
RFTools Dimensions 4.50

Logs
http://pastebin.com/CLCaP5WK

**Comment by McJty** [comment]
Fixed next release
