### ISSUE TITLE
Fluid Monitor cannot see Deep Resonance tank

### ISSUE THREAD

**Issue by Darkere** [McJty/RFTools#908]
The deep resonance tank does not appear in the Fluid Monitors UI.
Rftools Version: 1.1x-5.70
Deep Resonance Version : 1.1x-1.4.1

**Comment by McJty** [comment]
Strange I cannot reproduce this. I need more information. Can you show a screenshot of your setup?

**Comment by Darkere** [comment]
Oh right, this was still open. Sorry, I don't know what caused it my guess is it was tech reborn screwing with the fluid code. works well now ty
