### ISSUE TITLE
Infused powercells with EnderIO and/or Draconic Evolution

### ISSUE THREAD

**Issue by Kenny164** [McJty/RFTools#909]
Hi,

Tonight I have found that the infused powercells give a net gain of power on IO with EnderIO or Draconic Evolution

When you place an **infused** power cell with one side set to 'In' and the other set to 'Out' to either a mulitblock like EnderIO's capacitors or between two Draconic Evolution pylons, the powercell will fill itself and then also the connected blocks with power. (one of the blocks should have some residual power to start things off)

EDIT: forgot to mention, it seems to be in relation of the machine's infusion (i.e. in my picture it shows a gain of +2.5K with 100% infusion; but with 42% infusion it gives 1074RF/t)

I'm using version 5.62 on Direwolf20's latest 1.10.2 modpack (version 1.1.3)

![image](https://cloud.githubusercontent.com/assets/192534/21037217/f5a1a2ac-bdc3-11e6-9e62-cdbef6a35ad2.png)

_Thanks for reading and for the amazing work!_

**Comment by McJty** [comment]
Hmm, so what is the problem exactly? You mean that you get more total power out of it then you get in? In that case that's a bug. If it is only the RF/t that goes higher then that's normal

**Comment by Kenny164** [comment]
Yeah, this setup above is generating 2500 RF/t by itself, it seems to put in more power than it receives... I originally found this out on a advanced powercell with full infusion on a draconic power ball, I was wondering how i was generating 10k per tick with no power gen

**Comment by McJty** [comment]
Well my question is: is the TOTAL amount of power that comes out more then what comes in? That's still not clear to me. Try to enter a known amount of RF and check what you can get out

That the RF/t is more is fine. That's no problem. But the total RF should stay the same

**Comment by Kenny164** [comment]
Sorry for being unclear, both the capacitor and the powercell start at 0 total rf with this setup they will fill each other up to full for free

**Comment by Kenny164** [comment]
It seems to be something like total output io = input * infusion

**Comment by McJty** [comment]
Ok, that's not good. I'll check it out then

**Comment by McJty** [comment]
Fixed next release. Didn't even need another mod to do it. One infused next to a non-infused powercell would do the trick too
