### ISSUE TITLE
Unable to craft Saturation Module 

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#91]
Good Day,

So, basically instead of Saturation Module I can craft only Regeneration. As you see from screenshot there is (blacked out) regeneration module instead of saturation with Zombie Syringe.

Best Regards,
DeForce

**Comment by McJty** [comment]
What version of RFTools? Also what screenshot?

**Comment by DeForce** [comment]
Forgot to add... Sorry: http://i.imgur.com/xkYN25S.png
2.53 though, not 2.54

**Comment by McJty** [comment]
It is possible that this is fixed in 2.54 as I did some crafting fixes there. I'll leave this ticket open until you can confirm or unconfirm this.

**Comment by DeForce** [comment]
With 2.55, still the issue:
Zombie Syringe http://i.imgur.com/UJKZgt0.png
gets me
Feather Falling Module http://i.imgur.com/4PQn9El.png

**Comment by McJty** [comment]
I will investigate this and see if I can get it fixed for next release

**Comment by McJty** [comment]
Very strange, just tried this in infinity and there it correctly crafts the saturation module... (with rftools 2.55+). I'm confused why it wouldn't work for you. Did you try it in a regular crafting table?

**Comment by DeForce** [comment]
It is Rotary Craft is somehow messes with syringe info and i'm unable to craft the module. Without Rotary Craft it is all working good...

**Comment by McJty** [comment]
I'll check with Reika

**Comment by ReikaKalseki** [comment]
This reminds me of the magical wood recipe issue with ExU.
https://github.com/rwtema/extrautilities/issues/525

Thing is, I do not touch crafting recipes. At all.

**Comment by DeForce** [comment]
With DragonAPI it is all good, only when I add Rotary.
EU issue is with ReactorCraft...

**Comment by McJty** [comment]
Still looks somewhat related though.

**Comment by TomeWyrm** [comment]
Keep an eye on the ExU issue, MrPotatoGaming has an idea that they're testing out

**Comment by McJty** [comment]
Yes, I have subscribed to that issue.

**Comment by TomeWyrm** [comment]
This has been fixed. Turns out it was an odd interaction with Forge's Ore Dictionary.

You should also be able to close #175.

**Comment by BBoldt** [comment]
So... I'm getting this issue and I don't have Rotarycraft or any of Reika's mods.

BUT, luckily I do know which mod is causing it.

Vegan Option

**Comment by DoughnutDev** [comment]
Hey, this issue seems to be back in 1.10.2 version 5.06

**Comment by ReikaKalseki** [comment]
I removed the code on my end that contributed, and have long had a logger notifying about invalid recipe timing.

**Comment by DoughnutDev** [comment]
Your mods are not present in 1.10.2 and that is the version of MC it is
happening in.
