### ISSUE TITLE
IllegalArgumentException with Timer

### ISSUE THREAD

**Issue by Orcinuss** [McJty/RFTools#913]
The RFTools timer is not being ticked correctly in some cases and causes servers to crash.
Please be aware that sponge is installed.

RFTools 1.10-5.62
Crash Report: http://pastebin.com/8JrJSFxK

**Comment by McJty** [comment]
Well... I have *never* ever seen this before so this is really very weird

**Comment by Orcinuss** [comment]
Looks like it is happening with a couple different blocks in the mod as per the issue i referenced above. It also seems like the timer isn't updating the redstone around it correctly although I think this might be a sponge bug. 
I made another issue regarding that here: https://github.com/SpongePowered/SpongeForge/issues/1099

**Comment by McJty** [comment]
I added a safety check to my code in any case. So the crash with the logic blocks should not occur. Still not convinced this is a bug in rftools though
