### ISSUE TITLE
1.10.2 - liquid monitor crashes server if set to inspect block that does not contain liquid

### ISSUE THREAD

**Issue by cexikitin** [McJty/RFTools#915]
I'm not sure which machine it had displayed, but upon selecting it, it crashed my server this morning.

Heres the crash report

http://pastie.org/private/ldjwltjz2kmf5nhw2gf4wa

**Comment by cexikitin** [comment]
Ah, found it.

http://i.imgur.com/vR7Og4h.png

Placed next to a Crusher from Extrautils2

**Comment by McJty** [comment]
Can you paste the crash elsewhere? I can't load that site

**Comment by cexikitin** [comment]
http://pastebin.com/raw/1SYZWGJs

**Comment by McJty** [comment]
That seems like a bug in ExtraUtilities though as it is crashing in their handler

**Comment by cexikitin** [comment]
Why is it even selectable? In the screenshot it shows the base block that is used in all the EU equipment rather then the actual entity.

**Comment by McJty** [comment]
Apparently it implements IFluidHandler but does it in a wrong way. Maybe it should not even implement that
