### ISSUE TITLE
Filtered controller not working as expected?

### ISSUE THREAD

**Issue by alkyth** [McJty/RFTools#916]
I can't seem to get the filtered controller dimlet to work. I'm currently trying to have only the Alps and Frozen River biomes with normal terrain. Anytime I use a filtered controller with those two biomes it generates a dimension with forest, swampland, or some other bland biome. Is there supposed to be some kind of specific order you place the dimlets or is the filtered controller just bugged at the moment? 

I should note that when I used the checkered controller with the Alps and Frozen River biomes, it worked perfectly. 

Also I'm using the latest RF tools version on the curse client in a slightly altered 1.10.2 DW20 modpack.

**Comment by luigge** [comment]
I'm having the same issue, I'm trying to select some biomes for example the mesa biome, and the biomes from nibiru planet (galacticraft extra planets mod) but the dimlet always create the same biomes like desert, roofed forest, river, swampland but I don't want to create these biomes.

**Comment by josephcsible** [comment]
Will be fixed in the next release of RFTools Dimensions.
