### ISSUE TITLE
[1.10.2 Bug] Storage scanner crash

### ISSUE THREAD

**Issue by Wolvie2446** [McJty/RFTools#919]
Hi just leaving a feedback for a bug i found while setting up some automation.  When using the storage scanner to dump coal directly into a seeder from the Progressive Automation mod the game crashes and renders the map you did this on unusable until you either start over or mcedit the map getting rid of the scanner from the world entirely and starting the process over.  Loving the mod as it has a ton of useful things.  Keep up the great work.

**Comment by McJty** [comment]
Can you give me a bit more information? Like the actual crash and also version of the mods?

**Comment by Wolvie2446** [comment]
Will do this evening.  Just about to leave for work.  I will set up a small world to recreate the crash so i can get you the crash report.  Until then the mod file names are rftools-1.10-5.51 and ProgressiveAutomation-1.10.2-1.6.50  I apologize for the wait of the crash report but i wont have time to set things up and duplicate this before work.  Tonight for sure though.

**Comment by Wolvie2446** [comment]
Ok here we go  First up is all the mod versions rftools 1.10-5.51  progressive automation 1.6.50 running with Forge 12.18.2.2179  Below is the crash report.  When recreating the crash i noticed linking the storage scanner to the Diamond Planter does not cause the crash its only when any coal attempts to be pushed into it.  This may not even be a bug with your mod but could be one with the progressive automation mod instead i have no idea as i dont know how to make sense of the crash report.  Hope this helps

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPluginBuildingBricks (Building-Bricks-Mod-1.10.2.jar)
  NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  LoadingPlugin (Random-Things-Mod-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 12/13/16 1:28 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_180462_a(BaseTileEntity.java:530)
	at mcjty.lib.container.InventoryHelper.mergeItemStackInternal(InventoryHelper.java:337)
	at mcjty.lib.container.InventoryHelper.mergeItemStackSafe(InventoryHelper.java:312)
	at mcjty.lib.container.InventoryHelper.insertItem(InventoryHelper.java:231)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.injectStackInternal(StorageScannerTileEntity.java:214)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.func_73660_a(StorageScannerTileEntity.java:160)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_180462_a(BaseTileEntity.java:530)
	at mcjty.lib.container.InventoryHelper.mergeItemStackInternal(InventoryHelper.java:337)
	at mcjty.lib.container.InventoryHelper.mergeItemStackSafe(InventoryHelper.java:312)
	at mcjty.lib.container.InventoryHelper.insertItem(InventoryHelper.java:231)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.injectStackInternal(StorageScannerTileEntity.java:214)
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.func_73660_a(StorageScannerTileEntity.java:160)

-- Block entity being ticked --
Details:
	Name: rftools_storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity
	Block type: ID #1135 (tile.rftools.storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerBlock)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-94,7,-1100), Chunk: (at 2,0,4 in -6,-69; contains blocks -96,0,-1104 to -81,255,-1089), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Actual block type: ID #1135 (tile.rftools.storage_scanner // mcjty.rftools.blocks.storagemonitor.StorageScannerBlock)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Think Tank
	All players: 1 total; [EntityPlayerMP['Wolfie2446'/215, l='Think Tank', x=-95.32, y=7.00, z=-1100.60]]
	Chunk stats: ServerChunkCache: 569 Drop: 0
	Level seed: 8477499289243577296
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-92,4,-1271), Chunk: (at 4,0,9 in -6,-80; contains blocks -96,0,-1280 to -81,255,-1265), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Level time: 598071 game time, 27711 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 48222 (now: false), thunder time: 73439 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1886239552 bytes (1798 MB) / 3451617280 bytes (3291 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2179 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2179.jar) 
	UCHIJAAAA	Forge{12.18.2.2179} [Minecraft Forge] (forge-1.10.2-12.18.2.2179.jar) 
	UCHIJAAAA	buildingbrickshooks{1.10.2-2.0.12} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r62} [Actually Additions] (ActuallyAdditions-1.10.2-r62.jar) 
	UCHIJAAAA	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-Mod-1.10.2.jar) 
	UCHIJAAAA	bagelsmore{1.0.0} [Bagelsmore: The Return] (Bagelsmore Mod 1.10.2.jar) 
	UCHIJAAAA	bdlib{1.12.1.6} [BD Lib] (bdlib-1.12.1.6-mc1.10.2.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (Better-Builders-Wands-Mod-1.10.2.jar) 
	UCHIJAAAA	buildingbricks{1.10.2-2.0.12} [Building Bricks] (Building-Bricks-Mod-1.10.2.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-Library-1.10.2.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (Cooking-for-Blockheads-Mod-1.10.2.jar) 
	UCHIJAAAA	correlatedpotentialistics{1.1.3} [Correlated Potentialistics] (Correlated-Potentialistics-Mod-1.10.2.jar) 
	UCHIJAAAA	crossbowmod{1.3} [Crossbow Mod] (crossbowmod-1.3.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (Extra-Utilities-Mod-1.10.0.jar) 
	UCHIJAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	immersiveengineering{${version}} [Immersive Engineering] (ImmersiveEngineering-0.10-38.jar) 
	UCHIJAAAA	JEI{3.7.7.233} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHIJAAAA	cyclicmagic{1.8.14} [Cyclic] (Cyclic-1.10.2-1.8.14.jar) 
	UCHIJAAAA	cyclopscore{0.7.7} [Cyclops Core] (CyclopsCore-1.9.4-0.7.7.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	enhancedvisuals{1.0} [Enhanced Visuals] (Enhanced-Visuals-Mod-1.10.2.jar) 
	UCHIJAAAA	everlastingabilities{1.1.0} [EverlastingAbilities] (Everlasting Abilities Mod 1.10.2.jar) 
	UCHIJAAAA	fastleafdecay{v10} [Fast Leaf Decay] (FastLeafDecay-Mod-1.10.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (HarvestCraft-Mod-1.10.2.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (Hopper-Ducts-Mod-1.9.4-1.10-1.10.2.jar) 
	UCHIJAAAA	immcraft{1.1.7} [Immersive Craft] (immcraft-1.9.4-1.1.7.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.9.4.jar) 
	UCHIJAAAA	jurassicraft{2.0.3} [JurassiCraft] (JurassiCraft-2.0.3.jar) 
	UCHIJAAAA	lootbags{2.1.0} [Loot Bags] (LootBags-1.10.2-2.1.0.jar) 
	UCHIJAAAA	malisiscore{1.9.4-4.0.2} [MalisisCore] (malisiscore-1.9.4-4.0.2.jar) 
	UCHIJAAAA	malisisdoors{1.9.4-5.0.1} [MalisisDoors] (malisisdoors-1.9.4-5.0.1.jar) 
	UCHIJAAAA	mocreatures{10.0.0} [DrZhark's Mo'Creatures] (Mo-Creatures-Mod-1.10.2.jar) 
	UCHIJAAAA	mobdrops{1.2.7.4} [MobDrops] (MobDrops 1.2.7.4.jar) 
	UCHIJAAAA	mysticalagriculture{1.2.2} [Mystical Agriculture] (mysticalagriculture-1.2.2.jar) 
	UCHIJAAAA	powerinventory{2.3.0} [Overpowered Inventory] (OverpoweredInventory-1.10.2-2.3.0.jar) 
	UCHIJAAAA	simplerecipes{1.9.4-1.10.2a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	progressiveautomation{1.6.50} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.50.jar) 
	UCHIJAAAA	randomthings{3.7.4} [Random Things] (Random-Things-Mod-1.10.2.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (Redstone-Paste-Mod-1.10.2.jar) 
	UCHIJAAAA	rftools{5.51} [RFTools] (rftools-1.10-5.51.jar) 
	UCHIJAAAA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJAAAA	simplebarrels{1.25g} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25g.jar) 
	UCHIJAAAA	slabcraftmod{6.01} [Slabcraft] (Slabcraftmod v6.01 - MC1.10.2 Forge.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (Storage-Drawers-Mod-1.10.2-1.10.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UCHIJAAAA	wallcraftmod{6.01} [Wallcraft] (Wallcraftmod v6.01 - MC1.10.2 Forge.jar) 
	UCHIJAAAA	WIT{1.0.20} [WIT] (WIT-1.9.4-1.0.20-38.jar) 
	UCHIJAAAA	XaeroMinimap{1.9.6} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.10.2.jar) 
	UCHIJAAAA	XaeroWorldMap{1.2} [Xaero's World Map] (XaerosWorldMap_b1.3_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
LoadingPluginBuildingBricks (Building-Bricks-Mod-1.10.2.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  net.fybertech.nwr.NWRTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (Random-Things-Mod-1.10.2.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (22) from ActuallyAdditions-1.10.2-r62.jar
		* ChiselAPI (0.0.1) from Chisel-Mod-1.10.2.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-Mod-1.10.2.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.50.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.50.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Extra-Utilities-Mod-1.10.0.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.10-2.1.4.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.50.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-38.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-38.jar
		* JustEnoughItemsAPI (4.0.0) from Just-Enough-Items-Mod-1.10.2.jar
		* McJtyLib (1.10-2.1.4) from mcjtylib-1.10-2.1.4.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from Storage-Drawers-Mod-1.10.2-1.10.jar
		* WIT-API (1) from WIT-1.9.4-1.0.20-38.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Wolfie2446'/215, l='Think Tank', x=-95.32, y=7.00, z=-1100.60]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by McJty** [comment]
The crash is actually in progressiveautomation. So most likely not a bug in RFTools. If you make a report to them you can say that they apparently don't properly support 'null' facing in the IItemHandler. And that is required. With facing equal to null they should give access to internal slots. Many mods make mistakes with that.
