### ISSUE TITLE
[Suggestion] Add high/low levels for RF Monitor (and other monitors?)

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#921]
Hi,

I am concerned that with a single threshold on the RF Monitor that using it to turn my reactor on/off will result in "flickering" as the constant power usage and power supply bounce the reactor on and off. I experienced this with an IE diesel generator when I was using a vanilla comparator to control it.

It would be nice to be able to have the monitor turn on the signal when it drops below a Low threshold then back off when it hits the High threshold. I might thus set it to turn on when the powercell is below 25% and off when 90%.

In addition to possible TPS concerns with 'flickering' (Are there any? I'm not a programmer.) there are also in-game warmup-time and fuel efficiency benefits to such a system.

Thanks!

**Comment by McJty** [comment]
It is easy to do this with two monitors. One for lower thresshold and one for upper thresshold

**Comment by xenoflot** [comment]
That would need additional logic to AND the outputs, wouldn't it?  Certainly doable but it would be nice to have it built into a single block.

**Comment by McJty** [comment]
Well depends on what you consider nice. RFTools is already accused of being too many 'magic block solutions'. I think it is good that there are some things for which you need to setup some more advanced setups. Not sure that having every solution in a single block is a good thing

**Comment by xenoflot** [comment]
hehe, nice for me who enjoys single block solutions :-) Thanks for the quick replies!

**Comment by xenoflot** [comment]
Thanks to you and your complete unwillingness to be cooperative... I now know how to make an RS-Latch in SuperCircuitMaker! :-D \o/
