### ISSUE TITLE
1.11 error loading mod

### ISSUE THREAD

**Issue by Newa98** [McJty/RFTools#924]
[crash-2016-12-13_12.35.57-client.txt](https://github.com/McJty/RFTools/files/650130/crash-2016-12-13_12.35.57-client.txt)
 I can't figure it out please help

**Comment by McJty** [comment]
What mods do you have?

**Comment by Newa98** [comment]
Dooglamoocities, just enough items, minecolonies, overlord, and viescraft-airships. but it throws the same errors when i remove everything but rftools, compatlayer, and mcjtylib.

**Comment by McJty** [comment]
I need the exact versions

**Comment by Newa98** [comment]
rftools-1.1x-5.71, compatlayer-1.10-0.1.3, mcjtylib-1.1x-2.3.1, ViesCraft-4.0.1a-mc1.11.0, Overlord-1.11-2.0.1, minecolonies-universal-1.11-0.6.2020, jei_1.11-4.0.5.203, and dooglamoocitiesmod-1.11-1.3.

**Comment by Newa98** [comment]
deleted and redownloaded the rftools, compatlayer, and mcjtylib (for the third time) and it works now.

**Comment by McJty** [comment]
You were using the wrong version of compatlayer. i.e. the one for 1.10
