### ISSUE TITLE
Elevator Crash

### ISSUE THREAD

**Issue by vohan1212** [McJty/RFTools#926]
Running a private lan game and went to place the elevator about the nether bedrock, as i did so the server main Lan host crashed
[crash-2016-12-15_01.42.57-server.txt](https://github.com/McJty/RFTools/files/655329/crash-2016-12-15_01.42.57-server.txt)

**Comment by McJty** [comment]
Do you have sponge?

**Comment by vohan1212** [comment]
I don't.

On Dec 15, 2016 11:46 AM, "McJty" <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have sponge?

**Comment by McJty** [comment]
No idea why this is needed but I'll work around this for next release
