### ISSUE TITLE
Storage module won't keep connection

### ISSUE THREAD

**Issue by kgreenhalgh** [McJty/RFTools#927]
I'm using the direwolf 20 modpack. Playing in a biomes o plenty map. If I start a new game and throw down a few components (enderio creative power, storage scanner, chest) it works. But if I go to a survival world and play for a while (been using mostly immersive engineering for power etc) the storage module will not work. I shift right click it on the storage scanner and it says it connected. But when I place that module in a screen or a tablet it says that it is not connected. I've tried breaking down the whole system and placing it in a new area but still get the same results. The scanner and the tablet are powered. The screen works with other modules such as a button connected to a receiver. The only part that isn't working is the storage module.

edited for clarity...

**Comment by McJty** [comment]
Is the scanner chunkloaded?

Also what version?

**Comment by kgreenhalgh** [comment]
Scanner is chunk loaded. Not working even while standing right next to it. I'm using rftools-1.1x-5.71.

**Comment by McJty** [comment]
Can you show a full screenshot of your setup? I need more information because this is something that works fine for me.

Also 1.10 or 1.11?

**Comment by kgreenhalgh** [comment]
MC: 1.10.2
Forge:
![2016-12-15_13 10 51](https://cloud.githubusercontent.com/assets/3612071/21240525/ee3c4aee-c2c8-11e6-9d98-f65ed3e6c110.png)
![2016-12-15_13 11 01](https://cloud.githubusercontent.com/assets/3612071/21240526/ee5c4574-c2c8-11e6-86db-fdcf2dffe926.png)
![2016-12-15_13 11 28](https://cloud.githubusercontent.com/assets/3612071/21240528/ee5fd176-c2c8-11e6-94bb-c608ba7700b2.png)
![2016-12-15_13 15 51](https://cloud.githubusercontent.com/assets/3612071/21240527/ee5e6fa2-c2c8-11e6-9fa4-8c1dc190dfc4.png)
![2016-12-15_13 15 54](https://cloud.githubusercontent.com/assets/3612071/21240529/ee653fd0-c2c8-11e6-9afe-52ddf8d7e624.png)
![2016-12-15_13 16 05](https://cloud.githubusercontent.com/assets/3612071/21240530/ee66d048-c2c8-11e6-9d52-69d3a2994ae6.png)





 12.18.3.2185

**Comment by McJty** [comment]
That's really strange. I'll check it out but for now I have no explanation

**Comment by McJty** [comment]
BTW does the tablet have power? i.e. did you charge it?

**Comment by Dannerick** [comment]
This issue is being caused by the iron backpacks mod. When you wear an iron backpack that has the quick deposit upgrade, the client-side and iron backpack mod is stealing the shift-right click and the action is not sent to the server. This means the linking of the storage module to the scanner never actually happens though it looks like it on the client-side. This is a known bug in iron backpacks mod and the author has said he is working on it. In the mean time, unequip your iron backpack before doing shift-right click actions on entities.
