### ISSUE TITLE
[1.10.2] [Bug] Crafter james

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#929]
The crafter will not craft item even if it has enough item if they are not in the same item stack 
![image](https://cloud.githubusercontent.com/assets/11648771/21250625/cbae5938-c33e-11e6-8b18-2e03385a0e15.png)
in this example there a lot of stick that get left as item stack of there enough to do the craft but it does not until make them into one item stack

**Comment by McJty** [comment]
Did you enable the 'Keep' option for the recipe?

**Comment by Dijkstra1** [comment]
That looks that what it was and I did not enable, you can blame the person I am playing with, sorry 4 wasting time, keep the good work looking forward to your mod pack when you release it
