### ISSUE TITLE
Explosion when sleeping in a bed?

### ISSUE THREAD

**Issue by McJty** [McJty/RFTools#93]
If you sleep in a bed in an RFTools dimensions it explodes (like in the nether). Have to decide if that's good or not and if it is not good, what to do instead.

**Comment by DeForce** [comment]
Maybe dimlet for that setting?
Make it cost %, "feature".

**Comment by McJty** [comment]
Yes, that's an interesting idea :-)

**Comment by McJty** [comment]
Next version of rftools (2.60) will make this behaviour configurable.
