### ISSUE TITLE
Material Absorber not absorbing IC2 Uranium Ore

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#930]
Hi,

Playing DW20 and haven't had any luck finding Uranium or Yellorium dimlets so decided to make one.
Placed a material absorber on a pile of IC2 Uranium Ore and it just sat there. 

Further testing with cheaty goodness - Material Absorber ignores:
* Extreme Reactors - Yellorite Ore and Yellorium Blocks
* IC2 - Uranium Ore and Uranium Blocks
* IE - Uranium ore and Blocks

An old post let me to believe that generic ore support was added in 2.53.  Is lack of support for Uranium a feature or a bug?

Cheers!

rftools 1.10-1.5.2
rftoolsdim 1.10-4.45
IE 0.10-52
Extreme Reactors 1.10.2-0.4.5.21
IC2 2.6.105-ex110

**Comment by McJty** [comment]
It is a configuration thing. Unless rftools dimensions is configured to allow this dimlet (in dimlets.json) it will not be there. You can check availability of a certain dimlet in the dimlet workbench. If it is not listed there it does not exist. If you are playing SP then you can edit dimlets.json to allow this
