### ISSUE TITLE
[1.10.2] Crash on loading

### ISSUE THREAD

**Issue by MrAmericanMike** [McJty/RFTools#931]
Ok, so testing the newer versions I get this error:

http://pastebin.com/aDUKqGXp

Versions:
MC: 1.10.2
Forge: 1.10.2-12.18.2.2139-universal
compatlayer-1.11-0.1.4
mcjtylib-1.1x-2.3.1
rftools-1.1x-5.71
rftoolsdim-1.1x-4.51

**Comment by RedstoneMaster256** [comment]
I am also having this issue without rftoolsdim.

**Comment by MrAmericanMike** [comment]
Thanks RedstoneMaster256 yup that was the problem. So many updates I was doing, I missed that detail.
