### ISSUE TITLE
RFTools accepts, but doesn't output to Mekanism's Universal Cables

### ISSUE THREAD

**Issue by RedTech64** [McJty/RFTools#936]
Other rftools machines will accept power from universal cables, but the power relay doesn't seem to like it.

**Comment by McJty** [comment]
How did you configure the relay? Screenshot of gui would be handy

**Comment by RedGuy54** [comment]
![capture](https://cloud.githubusercontent.com/assets/12768272/21301099/f634a79c-c56f-11e6-95f8-8c5d043207cd.PNG)
![capture](https://cloud.githubusercontent.com/assets/12768272/21301110/0961dd58-c570-11e6-8e3f-42c9a662cb8a.PNG)

**Comment by McJty** [comment]
Hmm weird. Does it work with enderio conduits? If so I would say it might be a bug in mek.

Also what version of rftools?

**Comment by RedGuy54** [comment]
It does work with EnderIO, but the mek cables work with other rftools stuff. Version 5.62.

**Comment by McJty** [comment]
Does sound like an issue with the mek cables then to be honest. Not sure what I could do on my side to make them work

**Comment by GuntherDW** [comment]
This probably has to do with the fact that the Mekanism power system doesn't have caps yet, and is using an old(er) RF API (Don't quote me on that though). The fact that aidan is busy with school doesn't help either.

There is Tesla support, but I guess it's not complete yet or just outdated?

**Comment by RedGuy54** [comment]
It appears that mek cables don't accept power from pretty much anything outside of mek itself. I added Tesla and that completely broke mek cables. Thanks for he help, just have to wait for aidan to become active again.

**Comment by RedTech64** [comment]
@McJty So it has been a while, and Mekanism does have Tesla support, and this problem still exists. RFTools machines will accept power, but won't output it to universal cables. Interestingly, if I add Minecraft-Flux to my mod pack, it works perfectly, but unfortunately, it creates a memory leak so I have to remove it. Is there anything you can do or recommendations you might have?

**Comment by RedTech64** [comment]
Also what is really weird about this is that universal cables work perfectly with Thermal Expansion, and EnderIO so I don't understand what the difference is.

**Comment by legodude17** [comment]
Can you add the Tesla api?

**Comment by RedTech64** [comment]
Tesla API is added already.

**Comment by legodude17** [comment]
Does it work if you add Thermal Expanision (which adds the RF api)

**Comment by RedTech64** [comment]
@legodude17 Thermal Expansion is installed in my modpack

**Comment by josephcsible** [comment]
Works for me on Forge 2589, RFTools 7.23, and Mek 9.4.3.330. If it still doesn't work for you, please post the exact versions.

**Comment by FriendlySurvival** [comment]
I am having this issue too and also the RFTool's monitor not picking up these cables (saying they are empty) along with their Energy Cube. The following are the versions of the relevant mods...  

Minecraft: 1.12.2 
Forge: ending in 2759 
Mekanism: Version 9 ending in 349 

If any other information is needed let me know or if I should bounce these issues to Mekanism.

**Comment by josephcsible** [comment]
What version of RFTools and McJtyLib?

**Comment by FriendlySurvival** [comment]
> What version of RFTools and McJtyLib?

Sorry my bad those versions are... 
RFTools: for Minecraft 1.12.2 Ending in 56 
McJtyLib:3.0.5
