### ISSUE TITLE
Builder Block crashing client.

### ISSUE THREAD

**Issue by iEnergyX** [McJty/RFTools#938]
I placed down a builder block with a quarry card on it and when i try to start it, the world crashes.

MC: 1.11
Forge: 13.19.1.2195
RF Tools: 1.1x-5.71
McJtyLib: 1.1x-2.3.1
CompatLayer: 1.11-0.1.4

crash report: http://pastebin.com/c0UatpFt

**Comment by McJty** [comment]
It is actually crashing in techreborn. Report to them
