### ISSUE TITLE
Client crash on server on login

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#94]
Good Day,

Clients crash when they enter server, log below:

http://pastebin.com/Yb1awsyz

Saw RFtools there, decided to post here.
Best Regards,

DeForce

**Comment by McJty** [comment]
What version of RFTools?

**Comment by DeForce** [comment]
2.55

**Comment by McJty** [comment]
Can you give more information? When did this start happening? What happened between the time it worked and between the time it stopped working? Does this happen for every player?

**Comment by DeForce** [comment]
Yesterday, we had test launch of ReactorCraft reactor in RFtools Void dimension.

When we shut off the reactor and left the dimension it started to lag really hard (400ms+) on the age (There was no chunkloaders at the time). 

We have purged dimension via opis and server crashed. (Probably will be able to find crash-report, not sure)

Server started again fine.

There was flat desert dimension with hungry node in it, was set up spot loader (from ChickenChunks). Traveling really fast and chunks were not unloading, tried to purge them with no success. Then didn't do anything about that.

Then later went back in ReactorCraft dimension, then left dimension, it started to lag again (4500ms+) and got kicked from server with "a fatal error has occurred this connection is terminated" when I pressed Run in opis.
http://puu.sh/gtPUz/630ec6d2d3.png
http://puu.sh/gtSnn/c5240f1389.png

Tried to join back couple times, server didn't let me. Opis saved the results from scan, seems like.
Then, restarted client. Went back in, removed all ender IO conduits. Dimension unloaded at 100ms for about 10-15 seconds. Added chunkloaders, all went fine now. Sleep, today, all clients that want to connect to server gets this error.

If you need more information, I can answer here, or you can contact me on skype: czt.vladislav, if you want to see it yourself. I will not rollback server for some time, so you can check if it is something wrong.

**Comment by McJty** [comment]
Hmm, that looks like a complicated 'cooperation' of different mods to reproduce this bug... Not sure what I can do about this. I will investigate that crash report however but it is something that should not be possible to occur.

**Comment by DeForce** [comment]
I'll be happy to help you with what I can, and if you need, try to reproduce it. 
Maybe we will be able to find culprit of that in near future...

**Comment by McJty** [comment]
Yes that would be great. If you have any more useful information feel free to add it here.

**Comment by DeForce** [comment]
Were not able to reproduce the issue in a week. 
Closing this because cant duplicate.
