### ISSUE TITLE
Small tweak: Right click to cycle backward through lists

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#940]
When cycling through a list in RFTools I tend to miss the option I want, it would be nice to be able to right click to cycle backward so I don't have to go through the entire list again.

**Comment by McJty** [comment]
You can do shift-click to do that

**Comment by Xiaminou** [comment]
Oh, well then I'd like to suggest to change it to right-click, if that's not too much of a problem, as it's what most mods use to cycle backward.
