### ISSUE TITLE
Shield is always in shape mode [1.11] v 5.71

### ISSUE THREAD

**Issue by Necessitysslave** [McJty/RFTools#942]
I'm using forge 13.19.1.2195

Steps to reproduce:

Start new world (creative)
place shield projector
Place coal generator next to it
Load 2 coal in generator
place a couple of shield template blocks touching the shield projector
right click on shield with smart wrench

Expected: shield templates to be replaced with shield blocks
Actual: Shield blocks replace air blocks in a  5x5x5 cube centering on the shield projector as if it has a blank shape card installed.

only mods installed

RF Tools
RF Dimensions
RF Control
all the prerequisites

**Comment by McJty** [comment]
I will check it out. I think I have an idea

**Comment by Necessitysslave** [comment]
Thank you for such a quick reply.

**Comment by McJty** [comment]
Fixed next release (probably later today)
