### ISSUE TITLE
Horses + transmitter

### ISSUE THREAD

**Issue by levaritie** [McJty/RFTools#947]
so try riding a horse and go through a transmitter

you end up on the reciever but instantly teleport back on the transmitter and a endless loop acourse. this happend on a server I was playing on.

since it was a vanilla horse + rftools I cant realy see how it might becaused by another mod.

rftools version: 1.1x-5.72
forge version: 12.18.3.2185
minecraft version: 1.10.2
modpack: MMD project Ultimate version 1.3

edit: the reason it goes sofast is because of the infusion being 100%,

**Comment by McJty** [comment]
Fixed next release (by simply not teleporting if you're riding a horse)
