### ISSUE TITLE
Spelling error in description of module.

### ISSUE THREAD

**Issue by BrickVoid** [McJty/RFTools#948]
![2016-12-24_09 39 31](https://cloud.githubusercontent.com/assets/7897425/21463935/304ab830-c9bd-11e6-8348-a28c9e2dd500.png)

"Right click on an elector block ..."  I think "elector" should be either "elevator" or "selector" block, I'm not sure what you originally intended here.

Not a severe or game-breaking issue, just a spelling check request.  :)  Please don't shoot the messenger.

RFTools version 1.1x-5.71

Modpack: Direwolf20's 1.10 modpack, version 1.2.1

(I dunno if any of the above is required for bug reporting, but hey, it seemed relevant.)

**Comment by McJty** [comment]
Funny typo :-)
I will fix it
