### ISSUE TITLE
Question: Material dimlets with metadata?

### ISSUE THREAD

**Issue by davqvist** [McJty/RFTools#949]
I'm working on a modpack now and want to add ore dimlets. That works fine for some mods, but some mods have their different ore separated by metadata, so I can't differentiate them with different power values. I guess specifying a block with metadata is possible, but I don't know the syntax. I tried adding for example @4 or .4 but both didn't work.

**Comment by McJty** [comment]
You can use "meta": 3 or "meta": [3,4,5] in the filter

**Comment by davqvist** [comment]
Thanks a lot for the help. It worked.
