### ISSUE TITLE
Placed Elevator Block causing crash

### ISSUE THREAD

**Issue by Ben-Winn** [McJty/RFTools#954]
I was trying to figure out the Elevator block. I dug a hole in the ground, placed the block, server crashed. Restarted and joined fine. Right clicked the block and my client crashed. Server is running fine by my client is not able to join. I've attached the crash report and the output in my server terminal when trying to connect.

Any help would be appreciated. I probably broke something by just placing the block in a hole in the ground I just can't figure out how to get the client back into the server.

[crash-2016-12-26_19.53.10-server.txt](https://github.com/McJty/RFTools/files/673438/crash-2016-12-26_19.53.10-server.txt)

[Servers terminal output.txt](https://github.com/McJty/RFTools/files/673449/Servers.terminal.output.txt)

**Comment by McJty** [comment]
Please update. RFTools 5.60 is old. If this bug also appears with recent versions of rftools then please reopen
