### ISSUE TITLE
[issue] builder on quarry mode cannot extract tinkers minerals ardite/cobalt

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#955]
Well, the subject says it all, those minerals show up in the nether and the builder cannot extract those, I also made an admin test with it, and it just ignores those 2 blocks Ardite Ore and Cobalt Ore, none of the cards work on them, not even void.

Happy holidays and regards, 

Winsrp

**Comment by McJty** [comment]
I need more information as this is working for me. In my Lets Play I got tons of ardite and cobalt ore from my builder in the nether. What version of rftools? What kind of card? i.e. tons more info please

**Comment by winsrp** [comment]
Sure, I'll post everything I have

I'm using MC 1.10.2

I'm using rftools 1.1x-5.72, I also have the latest versions of rftool controls, dimensions, deep resonance, last version of tinkers (2.6.1)

I've tried all the cards, normal quarry, fortune, silk, all clearing variants and the void one, none of them worked (I tried in creative mode as I'm the admin of the server, and got that complain from one of the users, I also tried swapping to survival mode, and tried quarring it in the nether, overworld, and one of the dimensions, and nothing worked).

client/server mods

architecture craft
biomes o plenty
currency
ftblib/ftb utilities
advanced generators
grave stone mod
immersive engineering
iron backpacks
Minecraft comes alive
preasure pipes
progressive automation
spice of life
storage network
waila

and server side only:

rogue like dungeons
fast leaf decay
geographicraft
IvToolkit
REcurrent Complex
rough mobs
special ai

if you need anything else. let me know

**Comment by winsrp** [comment]
never mind I just reset the server and tried again and now it works =/
