### ISSUE TITLE
Crash on startup - NoClassDefFoundError: EntityWitherSkeleton

### ISSUE THREAD

**Issue by KnightMiner** [McJty/RFTools#958]
The latest RFTools (5.73) crashes on startup when played in 1.10.2 due to the missing class `net/minecraft/entity/monster/EntityWitherSkeleton`. 5.72 functions correctly since the commits calling that class were added between versions.

[Full crash report](http://pastebin.com/rDMqwYfM)

**Comment by McJty** [comment]
Oh right. I'll have to fix that. On it

**Comment by McJty** [comment]
Fixed in 5.74
