### ISSUE TITLE
Right clicking RFTools spawner crashes the client

### ISSUE THREAD

**Issue by SharkWipf** [McJty/RFTools#959]
Like the title says.  

Spawner is completely set up and worked fine pre-latest-update, I haven't been able to test it on a "loose" spawner yet, as I've managed to report this entire issue while waiting for my client to start again, will report back when I have.

EDIT: new, empty spawners don't cause this crash. A completely different already set up spawner however also crashed my client on right click. Other RFTools devices work fine. [New crash log](http://pastebin.com/rXzmW6Kz)

Crash log: [Here](http://pastebin.com/e4GKuAKh)
Minecraft version: 1.10.2
Forge version: forge-1.10.2-12.18.3.2185-universal
RFTools version: rftools-1.1x-5.74.jar

**Comment by LightningLdr180** [comment]
I can also confirm this bug.

Right clicking the spawner causes:
Description: Rendering screen
java.lang.ArithmeticException: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY
at mcjty.rftools.blocks.spawner.GuiSpawner.showSyringeInfo(GuiSpawner.java:130)

Crash log: [http://pastebin.com/uGaXCWDS](http://pastebin.com/uGaXCWDS)
Minecraft version: 1.10.2
Forge version: forge-1.10.2-12.18.3.2185-universal
RFTools version: rftools-1.1x-5.74.jar

**Comment by McJty** [comment]
Fixed in 5.75

**Comment by DemonXeron** [comment]
I'm getting this bug now. Has it reappeared?
EDIT: I'll check my version of RFtools to check.

**Comment by MichaelHillcox** [comment]
Update :P We don't support any version under 1.12 anymore, sorry.

**Comment by DemonXeron** [comment]
I'm using Valhelsia 2 (02/10/20 release) from the twitch Launcher, so whatever is in there. It uses Minecraft 1.15.2 and RFTools for 1.15 above 
![image](https://user-images.githubusercontent.com/70936339/98440474-da33cd80-20f0-11eb-9043-6988f8300262.png)

**Comment by MichaelHillcox** [comment]
Check the versions, you might have found a new bug, if it's crashing you then pastebin a crash log as well

**Comment by DemonXeron** [comment]
Here's the pastebin if it helps! Good luck. https://pastebin.com/b8REJQPU
Open in Pastebin Manager: pastebinmanager://pasteview?key=b8REJQPU

**Comment by MichaelHillcox** [comment]
Okay, looks to be a mod compatability issue, if you could open up an issue here https://github.com/McJtyMods/RFToolsUtility/issues with that crash log :+1: but before that, please try updatting RFToolsUtilities to 2.1.14 first
