### ISSUE TITLE
[enhancement] make elevator block emit redstone signal when floor is active

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#963]
Hi, 

If the elevator block can emit a redstone signal while the elevator is stooped at that floor, we can put an iron door on top of the elevator block and make it open automatically when the elevator reaches that floor, would be cool to not see the hole of the elevator and fall off.

Regards, 

Winsrp

**Comment by McJty** [comment]
It already does that (see the red arrow from the back, that's where the redstone signal comes out)

**Comment by winsrp** [comment]
yes did I noticed that, but the redstone signal goes on the lower back block, and that is 1 level under where the elevator stops, if you put the redstone signal on top of the block I can put the door there, and make everything more compact, becuase I put the elevator block where the person enters with a door on top, and the rest is controlled by the screens, but if the signal is behind and under it, then to make it fit I have to put the block some other place and try to make it go all the way around to lower it one level to make it activate the block on top which takes space that sometimes you don't have.
