### ISSUE TITLE
Adding userdimlets.json to Project Ozone 2 v2.2.1 causes server to fail at startup

### ISSUE THREAD

**Issue by Skotavus** [McJty/RFTools#972]
I've attempted to create and add in a userdimlets.json file to our server running Project Ozone 2, in order to add in the Awakened Draconium block from Draconic Evolution. The code from the JSON file is as below, and I've tried both UTF8 and ANSI encoding versions.
http://pastebin.com/yekymifW

The server clearly doesn't like it as it will fail to start up when this JSON file is added. When it's removed, the server starts with no issue. The crash dumps are located below:
http://pastebin.com/iSyXSjVj
http://pastebin.com/ckpgkT80

I've heard that RFTools and Draconic Evolution don't always play the nicest with each other, but if someone can spot a legitimate issue in the logs or let me know what I might be doing wrong, that would be much appreciated.

**Comment by McJty** [comment]
That's not a valid json (the first line ends with a ',' and nothing after it). Also where are all the other rules?

**Comment by McJty** [comment]
I mean you removed all standard RFTools rules which is *not* a good idea at all

**Comment by Skotavus** [comment]
There was no userdimlets.json in the server folder, so I had to create a new document in Notepad++.

I have only followed the instructions based on this wiki page (https://github.com/McJty/RFTools/wiki/Adding-a-Dimlet), so if there are standard rules that should also be included in the JSON file I do not know what they are, sorry.
I guess I put in the comma where it should only be used before a line break, instead of not at the end.

**Comment by McJty** [comment]
Ah sorry I was confused. This is another json. You are right. But the extra comma was indeed an error.

But are you on 1.7.10 or 1.10?

**Comment by Skotavus** [comment]
I'm currently on 1.7.10.
Removing the comma at the end now allows the server to boot up fine, so it was just that I had an invalid JSON file because of that ^^'

I still can't see the new material added, but at least I've found what was preventing the server from starting, thank you.
