### ISSUE TITLE
Energy module shows only the internal buffer of energy pylons (Draconic Evolution)

### ISSUE THREAD

**Issue by jk1895** [McJty/RFTools#973]
It shows only 2.147.483.647 RF and says 100%.
The multi block storgae is only filled with 10 BRF (0.47%) so it shows the wrong information.
I'm playing Sky Factory 3 version 3.0.4 (RFTools version is 1.1x-5.76)

Edit: Two pics added 1st shows the energy screen 2nd shows the RF storage a few seconds later.
Am I the only one with this bug?
![2017-01-12_13 29 33](https://cloud.githubusercontent.com/assets/20401451/21889922/9024bf7c-d8cb-11e6-9067-67fe5810fef7.png)
![2017-01-12_13 29 40](https://cloud.githubusercontent.com/assets/20401451/21889923/90283bd4-d8cb-11e6-9468-b7f2c813ce62.png)

**Comment by zogarr** [comment]
I am seeing the same bug - just came to see if an update fixed this problem.  Playing the DW20 1.10.2 pack.

**Comment by jk1895** [comment]
I tried 5.80 and brand new 5.81. The issue is still there. :-(

**Comment by McJty** [comment]
Yes I haven't had time to look into this

**Comment by jk1895** [comment]
No probs! Glad that you will. :-)
Thank you very much!

**Comment by zogarr** [comment]
Just an interesting update.  I tried this in the latest version of Sky Factory 3.  It seems to be able to read from a Tier 2 core perfectly.  I was using a T5 core in the other world where I ran into the problem.   Not trying to be pushy - just to help track down the issue whenever someone gets to it.  If I had time I would track it down and do a pull request.

**Comment by McJty** [comment]
The tier 2 probably can't handle more then 2gig which fits in a normal integer. The RFTools modules are currently not equiped for more then 32 bits. It is on my todo

**Comment by McJty** [comment]
Can you test out if it works if you use the latest McJtyLib from here:

http://jenkins.k-4u.nl/job/McJtyLib%201.11/lastSuccessfulBuild/artifact/build/libs/mcjtylib-1.1x-2.3.6-SNAPSHOT.jar

I implemented support but was not able to test it. Thanks

**Comment by jk1895** [comment]
Morning, 
yes, it seems to work (after short test). Game is loading. RF ammount is correct, RF/tick also. :-)
Thank you very much!

**Comment by McJty** [comment]
Ok, very nice. Now waiting to see if I can get test results for EnderIO and Mekanism too. Thanks!
So will be fixed in next release of McJtyLib
