### ISSUE TITLE
Cant put any thing in the machine infuser

### ISSUE THREAD

**Issue by Killer-Awesome-Phantom** [McJty/RFTools#975]
It doesn't seem that you can put and machine in the machine infuser the only thing i found that you can put in their is dimensional shards

**Comment by McJty** [comment]
You are inserting it in the right slot? i.e. the right slot? The left slot is for the shards and the right one for the machines

**Comment by Killer-Awesome-Phantom** [comment]
Yea i was putting it in the wrong slot so it was my fault. It working fine now
