### ISSUE TITLE
CTD activating Storage Module Filter in the nether

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#976]
Hi,

A player reports a CTD when programming a Storage Module Filter when in the nether. He things he was shift-clicking Quark's Basalt at the time.

I just made a trip into the nether and variously spammed right-click and shift right click, on air and on blocks including Quark's Basalt, but I didn't have a problem.

Nevertheless, here's the crashlog http://pastebin.com/0ff7RY5w

Let me know if there's not enough to go on and I'll work with the player to try to narrow it down.

compatlayer-1.10-0.1.7
mcjtylib-1.1x-2.3.1
rftools-1.1x-5.76
forge 2185
mc 1.10.2

**Comment by McJty** [comment]
Probably a very rare thing. I fixed it for next release in any case
