### ISSUE TITLE
Quirks with elevator screens above Y=125

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#977]
Hi,

I have a 4 level elevator in my mountain-top base.
* Level 1 block at Y=74, screen at Y=76, Screen Ctrl at Y=77
* Level 2 block at Y=111, screen at Y=113
* Level 3 block at Y=121, screen at Y=123, Screen Ctrl at Y=121
* Level 4 block at Y=131, screen at 133

Elevator functionality is fine for all levels. Screens for levels 1-3 work absolutely fine, getting the display name from the elevator block and the new TTF support looks great! However, _Level 4's block name isn't being picked up by the button module, and there're some rendering issues on the screen._ 

As I hope you can see in the linked image, the letters are being clipped on their right side and the font fill is sitting proud of the background. http://i.imgur.com/vEVhz1g.png This image shows (left) what I get on levels 1-3 and (right) what I get on level 4.

I have Vertical, Large and Lights selected, plus a colour for current level.

The reason I mention the Y levels is this: 
* If I break that dodgy screen and place it below Y126, it renders fine.
* If I break the Level 4 elevator block and place it below Y126, the name is picked up fine.

compatlayer-1.10-0.1.7
mcjtylib-1.1x-2.3.1
rftools-1.1x-5.80

The "pick up name" issue also happened with 5.76

Cheers!

**Comment by xenoflot** [comment]
If I may tack on a feature-request while I'm here... 

At the moment from a glance at the screen we can determine:
* The available destinations
* The current position of the elevator

What we can't see is where we are right now. I know that I can put a vanilla button on the elevator block as a "Call button" but it breaks the aesthetic of the high-tech looking screen. 

If possible, it would be nice if there were some kind of marker to indicate the current floor. Perhaps emboldening of the name, or switch current position to a chevron and use the background highlight to indicate "you are here".

Reasoning it out, I guess the easiest way to do that would be to bind the button module to the elevator block for the floor it "owns", rather than on the master block. Not a small amount of work, I'm sure :) Anyway, just throwing out ideas. I'll keep using wooden call buttons for now :-)

Cheers!

**Comment by McJty** [comment]
I'll check out the issue and think about the 'current floor' thing

**Comment by McJty** [comment]
I found the bug and will fix next release. Could you make the feature request a separate ticket because I'm not going to do that right away. Thanks

**Comment by xenoflot** [comment]
Wonderful! Thank you.
