### ISSUE TITLE
Multi-byte characters in truetype font Screen freezes client completely

### ISSUE THREAD

**Issue by zlainsama** [McJty/RFTools#979]
Versions:
1. forge-12.18.3.2209
2. rftools-1.1x-5.81
3. mcjtylib-1.1x-2.3.2
4. compatlayer-1.10-0.1.7

It happens in a clean install, when client try to render the Screen with multi-byte characters (I used Chinese characters), it freezes.
It does not crash the client nor do server think the player has issues.
It simply freezes.

How to reproduce:
1. Place a screen, make sure it has power and it is in truetype font rendering mode.
2. Type some random multi-byte characters through InputMethods.

Please:
1. Properly support InputMethods for language like Chinese, Japanese, etc.
2. or Filter out any multi-byte characters, completely.

Confirmed:
1. Disable truetype font rendering through config file can avoid this.

I don't think you can survive if you set the Screen to always use truetype font rendering.

By the way, truetype font text rendering overwrites button modules' background texture.

**Comment by McJty** [comment]
I'll check out the freeze. You don't happen to have anything in your log that is relevant?

Also: 'By the way, truetype font text rendering overwrites button modules' background texture.' What do you mean by that?

**Comment by zlainsama** [comment]
Nothing interesting in the log: [Pastebin Link](http://pastebin.com/iYCuCNxg)

I was going to take a screenshot to show what i mean, but I can't reproduce it in a clean environment, it might have something to do with other mods' in-world block rendering.

**Comment by McJty** [comment]
Hmm I have trouble reproducing this as I have no clue how to input those characters into the screen gui

**Comment by zlainsama** [comment]
I can type some for you to copy&paste them in.
我可以打一些让你能复制并粘贴他们进去。

**Comment by McJty** [comment]
But copy/paste is not working for my screen input

**Comment by zlainsama** [comment]
This is a world save: [Puush Link](https://puu.sh/tmRND/baa0a7a8e9.zip)
Here is a picture: [Imgur Link](http://imgur.com/a/9roZg)
The screen is a creative one, it has been set to "Vanilla" font rendering mode.
The world is saved with listed mods in the first comment.

**Comment by zlainsama** [comment]
This is what i mean by that: [Imgur Link](http://imgur.com/a/T8CFZ)
Although i can't reproduce this in a clean environment.

**Comment by McJty** [comment]
I managed to reproduce this bug by implementing ctrl-v/paste support for the text field

**Comment by zlainsama** [comment]
Great! that means a possible fix for this is coming?

By the way, the rftools builder breaks [Colossal Chests](https://minecraft.curseforge.com/projects/colossal-chests).
I was placing diamond variant chest walls from that mod using rftools builder, the builder placed invisible chest wall blocks ( i guess they are invalid ), upon breaking those invisible chest wall blocks, they all turn into iron variant chest wall blocks.
Builders wand from ExtraUtilties2 placed them correctly.
Should i open another issue to properly report this to you?

**Comment by McJty** [comment]
If I can find out what's wrong yes.

Anyway for the builder thing a separate ticket is best

**Comment by McJty** [comment]
This bug will be fixed in mcjtylib 2.3.4 (doesn't require an update in rftools) which is currently awaiting approval on curse.

Note that this fix will discard those characters. I have not yet found a way to actually render them and it all depends if they are actually in the font or not

**Comment by zlainsama** [comment]
I think they are in the font.
A picture to prove this: [Imgur Link](http://imgur.com/a/m4Mck)
Windows font viewer in a Chinese environment shows them.
The font is extracted from rftools-1.1x-5.81.jar.
