### ISSUE TITLE
[1.10.2] Elevator screens don't show levels when greater than ~65 blocks from base elevator #605

### ISSUE THREAD

**Issue by Flashken** [McJty/RFTools#981]
basically the same as in a previous issue - https://github.com/McJty/RFTools/issues/605
![2017-01-14_16 42 21](https://cloud.githubusercontent.com/assets/25016176/21956044/c18c42da-da77-11e6-8555-ea12da9c2a88.png)

Elevators work fine but the screens stop showing the corresponding names after a certain height from the base elevator. Screens have different screen controllers starting from the last 3 (so the first one on the seperate controller does actually show the name).

Modpack: Direwolf 20 1.10 version 1.3.2

**Comment by McJty** [comment]
What version of RFtools? I only fixed this bug in a VERY recent rftools update so it is likely not fixed there

**Comment by Flashken** [comment]
version 1.6.3 I believe - http://puu.sh/tmbz5/4b2aebbc32.jpg

**Comment by McJty** [comment]
That's RFTools Control. I mean RFTools. But anyway, it is likely that you are not having the right version. This bug was only very recently fixed

**Comment by McJty** [comment]
Ah 5.75 is more like it. In that case this bug is already fixed

**Comment by Flashken** [comment]
if it's fixed, any reason the names aren't showing up on the upper levels? Or is there a maximum of elevator buttons once can use?

**Comment by Flashken** [comment]
in which version can we find the fix then?
also, thanks for such quick replies

**Comment by McJty** [comment]
It was fixed in 5.81
