### ISSUE TITLE
New screen font doesn't apply to Inventory Module numbers

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFTools#983]
![2017-01-15_16 41 33](https://cloud.githubusercontent.com/assets/8670392/21963869/fda30cac-db41-11e6-958c-bcae3c6fb865.png)

Shouldn't they?

**Comment by Xiaminou** [comment]
No answer, so I'm going to assume the answer to my question is "no".

**Comment by McJty** [comment]
Sorry forgot about this but indeed. This is a bit harder as the count is rendered by mc itself
