### ISSUE TITLE
Crash with RFTools Builder when trying to move a space

### ISSUE THREAD

**Issue by RKAHN82** [McJty/RFTools#985]
This happens whenever I try to move anything using the builder in SkyFactory 3.

[crash-2017-01-16_07.51.47-server.txt](https://github.com/McJty/RFTools/files/708553/crash-2017-01-16_07.51.47-server.txt)

**Comment by McJty** [comment]
Can you be more specific about what 'anything' is? What exactly are you trying to move and how?

**Comment by McJty** [comment]
Not enough info. Closing
