### ISSUE TITLE
Incorrect Package Identifier

### ISSUE THREAD

**Issue by shadowfacts** [McJty/RFTools#99]
You should be using mcjty.rftools not com.mcjty.rftools because you don't own [mcjty.com](http://mcjty.com).

**Comment by McJty** [comment]
Where does it say that you actually have to own <xxx>.com in order to use package name com.<xxx>? Just curious. I never heard of that.

**Comment by shadowfacts** [comment]
From the Oracle website:
> Companies use their reversed Internet domain name to begin their package names—for example, 
> com.example.mypackage for a package named mypackage created by a programmer at example.com.

**Comment by McJty** [comment]
Well I don't know 'mcjty' domain either. So why can I use that then?
I don't think I will change this. I see practically every mod starting with 'com' in their package name and it is a major hassle to change this.

**Comment by shadowfacts** [comment]
Well mcjty just **isn't** a valid domain name. As for the second thing, refractors all the packsges should be too hard if you use a good IDE, I know for a fact that in IDEA this can be done by dragging the package to a different location.

**Comment by McJty** [comment]
Move done
