### ISSUE TITLE
Builder does not place ColossalChests' chest wall block correctly

### ISSUE THREAD

**Issue by zlainsama** [McJty/RFTools#990]
Versions:
1. forge-1.10.2-12.18.3.2215
2. mcjtylib-1.1x-2.3.4
3. rftools-1.1x-5.81
4. CyclopsCore-1.9.4-0.9.0
5. ColossalChests-1.10.2-1.4.2
6. compatlayer-1.10-0.1.7

Pictures: [Imgur Link](http://imgur.com/a/3tyUm)

How to reproduce:
1. setup a builder to place blocks in an area.
2. put diamond variant chest wall blocks from [ColossalChests](https://minecraft.curseforge.com/projects/colossal-chests) mod into the input chest.
3. give power and redstone signal to the builder block.
4. see invisible blocks get placed in the designated area.
5. break one of those invisible blocks, see them all turn into iron variant chest wall blocks. (only those in a valid position to form a ColossalChest will be updated to iron variant chest wall blocks)

**Comment by McJty** [comment]
Not much I can do about this. Many modded blocks work, many modded blocks don't. It is too hard to special case every block there is
