### ISSUE TITLE
Disjointed shields not working

### ISSUE THREAD

**Issue by gmoff01** [McJty/RFTools#991]
It does not appear to be possible to add non-contiguous blocks to a shield using the smart wrench as of 5.75.  You can make a contiguous shape and then remove blocks while the shield is still running, but as soon as you turn it off and back on you lose the disjointed blocks again.

**Comment by McJty** [comment]
yes, that's how it is supposed to work. Don't turn off the shield when you remove blocks like that manually. It has no way to remember what you removed.

**Comment by gmoff01** [comment]
So its not possible to add non contiguous blocks to a shield like this anymore? https://www.youtube.com/watch?v=0uN851ly3R4

**Comment by McJty** [comment]
yes why wouldn't that work? It is just not remembered when you dismantle the shield again

**Comment by gmoff01** [comment]
That was the actual bug that I'm reporting, doing that isnt working.  I was just adding the observation that you could get disjointed shields by disassembling but that it isnt permanent.  The correct way to do it, by adding it with the wrench, has no effect.

**Comment by gmoff01** [comment]
Specifically, I can turn the shield on, put the wrench into select mode, select the shield, and then attempting to select the disconnected template blocks has no effect.

**Comment by McJty** [comment]
Ok I'll check it out

**Comment by McJty** [comment]
Fixed next release
