### ISSUE TITLE
CTD Possible X-mod issue

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#994]
https://gist.github.com/xenoflot/16ed83d032b21d2a6c50525cd3983119

Player on the server had switched to SSP to test the powercell linking and CTD. 
I don't know the specifics of what he did, but I expect it wasn't much more than spawning in a generator and some powercells. Please let me know if the crashlog doesn't have enough information and I'll do some testing to narrow it down.

advancedrocketry-1.10.2-1.0.6
compatlayer-1.10-0.1.7
mcjtylib-1.1x-2.3.2
rftools-1.1x-5.81
libvulpes-1.10.2-0.1.13-universal

Cheers!

**Comment by McJty** [comment]
I don't know what libVulpes is but what it does is VERY wrong. It is trying to send RF into the powercells on client side! This is not rftools bug. Report this to libVulpes

**Comment by xenoflot** [comment]
Will do! Thanks for the snappy reply!
