### ISSUE TITLE
Screens GUI do not open.

### ISSUE THREAD

**Issue by RaresKool** [McJty/RFTools#998]
After multiple attempts of opening the Screen GUI me and other players had no luck opening it.
It either opens for a second and closes on its own or does not open at all?

**Version: rftools-1.1x-5.75**

**Comment by McJty** [comment]
Sneak right click to open the GUI of a screen. That has changed recently

**Comment by RaresKool** [comment]
I know, but it does not work.

**Comment by McJty** [comment]
Ah but you're still on 5.75. For that version it should still be normal right click. No idea why they wouldn't open for you. Weird. Any kind of protection on the gui preventing interaction with user interfaces?

**Comment by RaresKool** [comment]
https://youtu.be/AdrIURzJIL0

**Comment by McJty** [comment]
Does it work in survival?

**Comment by McJty** [comment]
Ah, do you have sponge? In that case you must upgrade rftools. There is a bug with screens and sponge in 5.75

**Comment by RaresKool** [comment]
That must be it. The server is running sponge indeed.
Thanks for the help!
